Congreso aprueba el transposición de Mifid que sucedió el primero de noviembre
Al costado su acto parlamentario, eso terminó hoy con el votar parcial del Congreso en las enmiendas incorporadas al proyecto en el Senado, el gobierno se ha sometido al público que oye la regulación que desarrollará la nueva ley, con el objetivo de la fuerza venidera de ino antes de los fines de año. 
Los representantes de grupos diferentes concordaron a acentuar los esfuerzos hechos por diputados y senadores para negociar y concordar la mejor legislación para garantizar la protección de los inversionistas y regulando en detalla la actividad de organizaciones para que los mercados trabajen eficientemente. 
El Mifid, cuál enmendación el Acto de Mercado bursátil, implica la modernización de mercados financieros, mientras refuerza la protección de inversionista, mejorando los poderes de supervisión del del de Comisión Nacional Mercado de Valores (CNMV) y alenta la cooperación entre los varios supervisores de la Unión Europea. 
Las nuevas regulaciones otorgarán servicios consultivos financieros a compañías especializadas así como a individuos naturales o legales, y crean un nuevo tipo de compañías consultores financieras (ESIS), las compañías consultores financieras (AFI), eso incluye las firmas de acciones, los corredores, y las firmas de la gestión de carteras. 
Además, extiende el número de sistemas disponibles para la ejecución de operaciones financieras, así que incluido en la regulación son los mercados secundarios, los sistemas multilaterales que comercian, y los sistemas de interiorización de órdenes, éstos competirán con los directores actuales de mercado de valores. 
La ley requiere también las compañías de servicios de inversión a revelar al mercado los detalles claves de su perfil del negocio, la exposición del riesgo y formas de la gestión de riesgos, y para mantener un registro de todas sus operaciones para facilitar la supervisión por el CNMV. 
En su pasaje por el Comité en Asuntos Económicos del Congreso, varias modificaciones fueron introducidas, sobre todo deudas de securitised deben ser consideradas como un instrumento financiero "complejo" debido a su riesgo alto para el inversionista, que ha sido demostrado por lo que sucedió con el riesgo alto norteamericano hipoteca deudas (subprime). 
Además, el transposición se aprovechó de la directiva para definir legalmente las funciones que pueden desarrollar a graduados en la Economía y Finanzas en 30 años después de que el decrete la aprobación en 1977, eso delimita las funciones profesionales reservadas a economistas profesionales. 
Para su parte, el Senado promovió la creación de nuevos papeles en el sector financiero, tal como el asesor financiero, que trabajará para emplea o recompensa, no requiere la aprobación de la SEC y podrá proporcionar sus servicios y el marketing correduría de productos a clientes en varias firmas de la inversión al mismo tiempo. 
