La Capital política: El Guardia húngaro ha elevado el nivel del riesgo del país
Las acciones por el Guardia húngaro, establecido en agosto con el apoyo del Movimiento para un Hungría más Correcto, ha levantado el nivel político del riesgo de Hungría y la región entera de varios aspectos, según el Riesgo que Analiza la División de la Capital Política. 
La entidad de investigación publicó un "el riesgo que advierte," escribiendo: las acciones del Guardia húngaro provocan un exceder el riesgo político "que las tensiones étnicas ya existentes entre el gitano y residentes no-gitanos de Hungría podrían calentar a niveles tóxicos tan temprano como el a corto plazo, llevando a los conflictos étnicos que podrían girar violento". 
El motivo principal para esto es esa estrategia política húngara de Guardia aparece ser apuntado a provocar la acción de esta naturaleza, el instituto de investigación agregado. 
Esto es el resultado de uno de los fracasos más graves de jugadores políticos de Hungría: "Los actores primarios en la vida pública girada sobre el debate público de asuntos de Roma a representantes del radical y fuerzas políticas extremistas, que ha construido una estrategia política fuera de diferencias gitano húngaros". 
Esto, la Capital Política cree, ha intensificado el problema, rindiendo algún diálogo normal imposible, reforzando a los extremistas, y elevar la probabilidad que conflictos violentos ocurrirán. 
Además, el instituto de investigación cree que la atención extensa, doméstica e internacional de medios a acciones húngaras de Guardia "ha dañado apreciablemente la imagen internacional de Hungría, especialmente considera como la creencia en la estabilidad del país y en la sofisticación de su democracia". 
Ellos indican que la publicidad y el impulso crecientes dados a la reorganización de grupos de radical y extrema derecha en empezar de Hungría en el otoño de 2006 han formado parte de la razón por qué varias organizaciones llamando a sí mismo las alianzas nacionales de defensa propia fueron establecidas empezar en el verano de 2007. 
"La característica común de estos grupos es que ellos llaman a sí mismo las organizaciones cívicas mientras declarando abiertamente que ellos preparan a sus miembros para defensivo - inclusive armado - las tareas (citando el desastre la administración, la defensa nacional, la aplicación de la ley) al declarar que la policía y las fuerzas armadas, es decir, el gobierno, es impropios para el papel," la Capital Política agrega. 
Ellos notaron que todo éstos mueven han sido hechos dentro de una configuración que depende de anti humor anti política y del partido político de la sociedad para encubrir varias ambiciones políticas bajo una manto de la acción cívica. 
Es decir, su énfasis en la naturaleza cívica de sus acciones y su elección de la asociación como su forma de la organización no es solamente tretas para soslayar trampas legales a la matrícula con los tribunales, pero son también parte de una estrategia política. 
Según el análisis, la actividad del Guardia húngaro eleva el riesgo de dañar nuestras relaciones con nuestros vecinos, también. 
"En los últimos meses varios de vecinos de Hungría han citado al Guardia húngaro como un peligro potencial. El ultranationalist jugadores políticos entre algunos de estos vecinos se han referido al establecimiento del Guardia húngaro como un argumento para justificar sus propias políticas anti-húngaros. 
Todos estos factores influyen la estabilidad política de la región," agrega. 
El instituto de investigación nota que el establecimiento del Guardia húngaro no es un fenómeno extraordinario en Central y Europa del Este, y cuando tal eleva el riesgo político para toda la región. 
Nota que la operación del Guardia húngaro es semejante a eso de la Guardia nacional búlgara, establecido en agosto 2007 por la extrema derecha la Unión Nacional búlgara. (BNU). 
Los conflictos graves que estallaron entre Roma y no-Roma en un distrito de Sofia (Krasna Polyana) estuvieron detrás del establecimiento del guardia búlgaro. 
BNU se aprovechó de los alborotos para establecer a su guardia, reclamando que la meta de la organización fue "defensa propia nacional. 
Ellos discutieron que durante los pasados 17 años Bulgaria habían sido susceptible a "el terror gitano," en que el gobierno estuvo la Capital impotente e indiferente y Político notó. 
La iniciativa provocó calentó el debate entre el público búlgaro, agregó. 
Un signo que el riesgo del conflicto étnico ha aumentado, los analistas escribieron, son que algunas organizaciones de Roma en Bulgaria han anunciado que los planes para establecer a un guardia de su propio como una fuerza de resistencia. 
Desde que el Guardia húngaro ha actuado hasta ahora bastante semejantemente a la Guardia nacional búlgara, es bastante posible que la comunidad de Roma de Hungría podría responder a la amenaza organizando su propia defensa propia, escribió la Capital Política en la advertencia del riesgo. 
El director Principal político de investigación Atila Juhász respondió a una pregunta del MTI el servicio de teletipo húngaro diciendo ese análisis del riesgo fue uno del instituto de investigación las actividades principales. 
Cada año, él dijo, ellos publican el riesgo analiza, y si ellos descubren cualquier factor que quizás altere los riesgos, ellos notifican la opinión pública publicando una advertencia del riesgo, como ellos ahora han hecho. 
