EnvironMin y seis por ciento de Hungría
El ministro para el Ambiente, Gábor Fodor ha dicho que las reuniones planas profesionales en el poste-2012 asuntos internacionales del clima terminarán el martes. La conferencia que él mismo abre oficialmente el miércoles, cuando los ministros toman el asunto. 
Los profesionales y los políticos de 192 países son designados para discutir el Mapa de carreteras de Bali que enfoca en esfuerzos de cortar las emisiones de gas invernadero después de 2012, cuando el Protocolo de Kyoto expira. 
En presenta el desarrollar y las naciones desarrolladas están en medio de una disputa calentada. 
Los Estados Unidos han permitido que lo fuera sabido que está no dispuesto negociar los números precisos aunque no sea opuesto a concordar a un corte del 25-40 por ciento en gases invernaderos por 2020 cuando comparado a 1990. 
La otra pregunta grande en la conferencia es si las naciones desarrolladas están listo no sólo reducir sus emisiones pero para ofrecer también ayuda financiera y tecnológica a países que necesitan lo. 
Un acuerdo alcanzado estuvo en el apoyo a paises en vías de desarrollo. 
Una tabla de 16 miembros manejará la financiación para esto, que es puesto por el Protocolo de Kyoto, y hace la mayoría de los trabajo probables dentro de las NNUU la Facilidad Global del Ambiente (GEF), escribe la Ganancia local de és de publicación Piac. 
Seis por ciento de Hungría
Representar Hungría. El Ministro del ambiente Gábor Fodor está listo para sostener las tentativas de UE para retener su papel bandera en el esfuerzo global de la protección del clima y promover un nuevo acuerdo internacional, para ser alcanzado por 2009. 
Fodor notó que la UE tiene sus vistas en una gota del 20 por ciento en emisiones de gas invernadero por 2020 comparado a 1990, si el acuerdo “post-2012" es alcanzado o no, y está lista para cortarlos por 30 por ciento si las otras regiones desarrolladas mayores del globo y paises en vías de desarrollo están también listas para aceptar las obligaciones a la extensión de sus habilidades y responsabilidades. 
Fodor dijo que atrás en 1997, los países que adhieren al Protocolo de Kyoto habían concentrado en una reducción del 5,2 por ciento en emisiones en conjunto. Dentro de ese grupo, la UE de 15 miembros concordó a un descenso del 8 por ciento. 
Hungría concordó en cortar sus emisiones de gas invernadero por el 6 por ciento comparado a 1985-1987, una meta que lo piensa encontrar, dijo el comunicado de prensa del ministerio del ambiente. 
Las estacas en Bali son altas, para un acuerdo internacional a largo plazo en necesidades de política de clima para estar en secreto dentro de dos años o seguramente no poder entrar en vigor por 2012.. Debe eso sucede, las promesas hechas durante la validez del Protocolo de Kyoto no serían seguidas inmediatamente por otro régimen de emisiones-reducción, la necesidad para que el Premio Nobel de NNUU el cuerpo científico victorioso, el Entrepaño Intergubernamental en el Cambio del Clima - IPCC- ha indicado en su último informe. 
El resultado podría ser una demora en la reducción de emisiones, que pondría la Tierra en un cierto curso hacia una subida media de la temperatura que excede 2 grados Centígrados. Debe eso sucede, los científicos dicen que las consecuencias serían horribles e irrevocables. 
