"Sangre de mayo", un reto épico por Garci. 
Jose Luis Garci, inspirado por la novela Episodios Nacionales de Banito Pérez Galdós, recrea en Sangre de mayo el español popular motín en contra del los franceses. Éste es el trabajo más ambicioso de su filmography, con un presupuesto casi 15 millones de euro. 
Con esta película el director ha probado a "explicar el torrente de personajes y al mismo tiempo el social análisis" eso él siempre admirado en el trabajo de la famosa novelista, decía hoy, durante la película 'presentación de s, con que Quim Gutierrez y Paula Echevarría encabecen mayor emitidos de intérpretes. 
Sangre de mayo, una película más larga que 2.30 horas, debuta este viernes en los cines, para convertirse en un cuatro mini series de TV de horas en TeleMadrid en el próximo futuro. 
Gran admirador de la literatura de Galdós, reclamaciones de Jose Luis Garci de que este tiroteo se daban cuenta "de sueño de su una". Le gusta agradecer a Esperanza Aguirre, quien, tres años más temprano, lo había encargado disparar el segundo centenario a una película para conmemorar del Madrid 2º de mayo. Éste era el deseo expresado por la Comunidad de Madrid. El director estaba de acuerdo con condición que la historia fundaba en la novela Episodios Nacionales. 
Los 15 millones de "el presupuesto totalmente asignado por la Comunidad de Madrid representada para Garci" una "oportunidad exclusiva" de recrear las correspondientes fija y los trajes para retratar un España que escogía el líder equivocado para luchar por y el hecho de que la lucha por independencia conducía personas a una demora enorme en el desarrollo durante el reinado de Fernando "decía a Garci. 
Sin embargo el director lamenta no haber recibido fondos iguales de fantasmas de Alatriste o Los Goya - más de dos veces comparado con Sangre de mayo. Hasta aquí, no era posible disparar algunas escenas incluidas en el plan, él mismo había firmado juntamente con Horacio Valcarcel, su colaboracionista largo de carrera. 
La diferencia de presupuesto influía en la forma habitual de trabajo del director de Volver un empezar: por ejemplo, la puesta en escena con los actores, con los cuales a menudo utiliza para ensayar antes de disparar juntamente con aquéllos que no pertenecen al la emitidos, que considera esto "humillante" y pensando eso "el trabajo de las mentiras de director al ir al teatro y al cine para darse cuenta de cómo está continuando la industria para la cual está trabajando. 
Una cierta cantidad de intérpretes, algunos de los cuales caen dentro del reparto de Sangre de mayo, repiten delante de su cámara de vídeo. Es el caso de Michael Rell, Carlos Larranaga o Fernando Guillen Cuervo. 
Cuatro veces en las nominaciones de Oscar - ganando a uno - Garci cree que ninguna de las tres películas de candidato para representar España en Hollywood este año, su Sangre de mayo, los de billar francés de mesetas de Siete, y el Los seleccionaba ulitmo girasoles ciegos representan el cine español 'generación más joven de s', eso debería ser sabido en cambio. 
Garci no espera premios de esta película. 
"al Principio Usted pensar en trabajar para la posteridad, entonces se da cuenta de que solamente trabaja para la prosperidad, y en algún punto sólo rueda una película más", dice Garcia después de más 30 años de carrera. 
