Office abierto, aquí está la tercera edición de Microsoft » de the"anti paquete. 
Hoy ve la presentación de Openoffice.org 3.0, la suite de productividad personal de fuente abierta que aspira a ganar más usuarios, de domésticos a origen los usuarios, de profesionales a administración pública, como una gratuita alternativa para los más conocidos Microsoft Office. 
Después de un esfuerzo que dura durante casi un año en nombre de desarrolladores de voluntario, con Microsistema de SOL que supervisa en sus espaldas, los nuevos Abren oficina es revelado al general público con varias novedades: a la con pantalla y a una interfaz de usuario revisitada, menos Espartana, sea añadido otros más sustanciales como compatibilidad nativa con el sistema operativo de X de Mac OS de Manzana y apoyo para el ODF de formato nuevo (Formato de Documento Abierto) 1.2, el último estándar de versión ISO. 
La atención se ponía también en interoperabilidad con la Oficina 2007 suite, Office Abierto es susceptible de documentos de apertura con la nueva extensión de Microsoft (.docx, .xlsx, .pptx). 
Interesando son algunas funciones específico de algunos módulos como aquél que permite la reducción en tamaño de presentaciones de PowerPoint, útil por ejemplo para enviarlos mediante correo electrónico, o la posibilidad de importar un fichero PDF en el gráficos módulo, manteniendo la original apariencia de la página. 
Siempre en el mismo camino, es posible para crear "el PDF híbrido" documenta, que se reúne el gráfico estándar del formato de Adobe con los elementos de una hoja de cálculo o un procesador de palabra. 
La colaboración es uno de las características dentro de las solicitudes que ha sido mejorado considerablemente: en la aplicación de hoja de cálculo varios usuarios pueden hacer funcionar simultáneamente, evitando conflictos en las modificaciones, en la palabra transformador, cada uno los usuarios es asignado un color que comenta para mejorar reconocimiento durante revisión. 
Algunas compañías están funcionando también con porting algunos de los functionalities de OpenOffice a la web (en la nube), y durante las próximas semanas deberían publicar el definitivo producto. 
La versión italiana está disponible para transferir en la alocución Aung: / it.openoffice.org / transferir / 3.0.0 / download300.html y es añadido a la versión inglesa que ha estado disponible en lugares de espejo desde el viernes. 
Además de para ventanas y Mac OS, como de costumbre la suite está también disponible para el sistema operativo de Linux. 
Bajo solicitud la instalación CD se pueden enviar a su casa o lugar de trabajo. 
Y si el invento de gratis podría ser una fuerza de mando para la difusión en casas, está en la puesta de negocio que abrirá oficina está probando la gran apuesta desde que puede contar ya con varios proyectos de los cuales se da cuenta dentro de la administración pública y las escuelas. 
Y hay instituciones uniformes que la formación de oferta revisa, consultoría, y asistencia, ideal pequeño a empresas medias, que podrían crear más negocio oportunidades de. 
Office abierto se compone de cinco principal módulos: Escritor, para el tecleo de onscreen que corresponde a Palabra; Calc, la aplicación de hoja de cálculo que aspira a sustituir Destacar; Impresione, para presentaciones en la emulación de Powerpoint; Dbase, como en el caso del los más famosos acceso la aplicación que consiente está funcionando con bases de datos; Dibuje, sea el gráfico módulo. 
El objetivo para 2008 es lograr 5 millones transfiere, y considerando eso hacia arriba de hasta que hoy somos en casi 3 millones 600 mil, con la presentación de la nueva versión que ello es probable que la cifra predicha se podría superar incluso. 
