Járóka: El círculo vicioso de la pobreza, se debe eliminar la segregación 
La Cumbre de Igualdad Europea se ha abierto hoy en París, que es organizado por Francia este año, representando el Presidencia - dentro - oficina de la Unión Europea. 
En su mensaje que dirigía al plenum járóka de fidesz, Representativo de del Europeo Popular 'la Fiesta de s convocaba atención de la escolar desde que es una de la infracción más grave que afectaba etnia gitana los niños. Además, ésta es el mayor obstáculo para su bienestar. 
La alto nivel conferencia ha sido inaugurada por Xavier Bertrand, francés Ministro para Asuntos Laborales y Sociales y Vladimir Spidla, Comisario europeo responsable de Empleo, Asuntos Sociales y Igualdad de Oportunidades. 
Los representantes de los gobiernos, los socios sociales europeos y las principales europeo legal ayuda organizaciones y los NGOs del el ámbito de la igualdad oportunidades eran invitados a tener un puesto en la conferencia. 
Járóka - según la oficina de prensa del grupo de Fidesz en el Parlamento Europeo - indicaba que, además de la discriminación experimentada al aplicar para un puesto de trabajo, la gente de Roma es separada del el laboral mercado principalmente a causa de su baja educativa cualificación. 
"la Mayoría de los jóvenes gitanos hacen no tener una Secundaria calificación, y debido a la calidad baja de la educación básica solamente una parte insignificante de ellos pueden obtener colegio o universitario grado". 
Járóka también enfatizaba que la educación, como un fundamental humano bien, desempeña un papel clave en la ejecución de otro los humanos derechos. 
Invirtiendo en la temprana educación de gitanos los niños pueden contribuir a reforzar la economía de los estados miembros de Unión Europea. 
Según el representante, es necesario informar la más amplia gama de gente - gitanos y no-Roma habitan también - sobre estas interrelaciones. 
cuanto más temprano un joven Romaní estudiante empieza a asistir a escolarizados, tanto mayor sus posibilidades serán convenirle a una productiva miembros de del laboral mercado; a través de los ingresos y los impuestos pagados por ellos contribuirían al nacional presupuesto. 
"Encima motivos de la ciudadanía bien solicitado en la Unión Europea, la derecha de educación de baja calidad se debe garantizar para gente de Roma y calidad baja, la educación separada debe ser eliminaba", Lívia Járóka añadido. 
También decía que para acelerar instantáneamente los procesos de supresión de la segregación de escuela, es necesario garantizar un objetivo - y cooperación orientada de acción dentro de la Unión Europea. Para lograr este objetivo, es fundamental imponer correctamente las directivas de anti-discriminación existentes y planeadas. 
"el círculo vicioso de la pobreza la segregación, el desempleo se debe eliminar, a gitanos los niños se les deben proporcionar las oportunidades de vida democrática para que podrían contribuir al futuro de Europa como ciudadanos con lleno derechos", Járóka exigido. 
En el marco del "Año Europeo de la igualdad", la Cumbre de Igualdad Europea - primero organizado en Berlín el pasado año y desde que entonces abrazado en una base anual - los objetivos para proporcionar un foro exclusivo para promover los objetivos de oportunidades iguales y anti-discriminación en europeo y estado miembro nivelan también. 
