Oposición de Lukashenko: 
No se elegía a ningún representante de oposición al parlamento de Belarusian durante el domingo 'comicios de s. 
Según rusa los observadores, las razones para esto son el bienestar y estabilidad en el país dirigido por Alexander Lukashenko, mientras la Organización para Seguridad y Cooperación en Europa (OSCE) lo explica como fraudes de recuento de voto. 
Delegando OSCE a 450 observadores de 43 países rechaza reconocer la elección. 
aunque la 100 legislación de miembro del país de 10 millones de ha sido oposición desaparecida durante más de una década, antes de que las elecciones ayer se reunieran las fuerzas de la oposición bajo el nombre de Fuerzas Democráticas Unidas (UDF) habían esperado gravemente que Lukashenko, que reanudaba su presidencia para la cuarta vez durante los comicios polémicos en 2006 después de las enmiendas de la Constitución, se estaba yendo a "permitir" presencia de algunos representantes de oposición en el parlamento esta vez. 
Basado en esto Basada desistía del boicot anteriormente considerado, demasiado. 
Los antecedentes de las expectativas de la oposición eran eso el económicamente cada vez más persona a cargo de Rusia Bielorrusia - eso había levantado un préstamo para reducir la más y más caro ruso del gas importación y aceptado que los gasoductos que reconocen de Beltransgas cruzaran el país que se convertía en propiedad rusa - deseada mejorar sus relaciones con la UE, donde de visados no es concedido para Lukashenko y para una cantidad de políticos superiores debido al sistema político de Belarusian, que se considera anti-democrático. 
El hecho que OSCE cuándo haber evaluado que la campaña de las elecciones más bien se concentraba en cambios positivos en lugar de carencias - como prohibir un tercio de los candidatos de oposición de prender se separan en los comicios - indicaba distensión anteriormente. 
Sin embargo, el lunes de OESC levanta acta hoja levantada objeciones en contra de la campaña durante la cual los candidatos de oposición no eran permitidos prácticamente para aparecer en los medios de comunicación y especialmente la oposición que no se permite para estar presente en el recuento de votos. 
Según la oposición, la mejora es todavía perceptible en el sistema político: los prisioneros políticos han sido puestos en libertad y Minsk se induce a confrontar con Moscú en una pequeña forma cerca todavía no reconociendo Sur Osetia del y Abjasia que tienen separación de Georgia, aunque Rusia - formando un estado federal con Bielorrusia sobre papel - ha estado considerando ya independientes los dos territorios durante un mes. 
"Nosotros haber dado dos pasos delante y uno hacia atrás, pero lo más importante es ese diálogo entre Bielorrusia y la UE tiene empezaba", dicho Alexander Milinkevich a nuestro documento. 
Según el candidato de oposición de las presidenciales elecciones de 2006 ese diálogo necesita ser mantenido a pesar del hecho que el "poder ha conseguido asustado de permitir incluso un miembro de oposición para entrar el parlamento de ningún peso". 
Viendo los resultados la oposición no hace planes proclamando las acciones, más bien aspira a contactar con votantes con su mensaje sobre la importancia de reformas económicas. 
"Nosotros tener muchos problemas con esto por supuesto, tenemos que imprimir periódicos de oposición en Rusia, la distribución es obstaculizada por las entidades locales, pero puedo ver todavía que está a favor de los cambios más y más gente, entre los viejos demasiado", decía refiriéndose Milinkevich al hecho que Lukashenko 'régimen de s, cuál considera el establecimiento de la Seguridad como su más importante resultado, es considerado inadecuado incluso por pensionistas que son oficialmente la mayor parte de los respaldados clase de la sociedad de todos. 
"debido al el endeudamiento del país y el aumento de déficit comercial, el pausa abajo de seguridad social 'similar a muertos silencio' es una cuestión de tiempo", Milinkevich reclamado. 
rusa Los observadores describían tan democráticos las elecciones, en la contradicción respecto al el de la oposición político. 
el líder de misión de Commonwealth of Independent States Sergei Lébedev decía agencia de noticias rusa, Ria Novosti: "La gente cree en acciones no palabras", así la falta de oposición no es nada más que las pruebas de la madurez de votantes de Belarusian. 
