El Congreso apruebe la transposición de la MIF que tuvo lugar el 1 de noviembre
Junto con sus procedimientos parlamentarios, que ha terminado hoy con la votación parcial del Congreso sobre las enmiendas incorporadas al proyecto en el Senado, el gobierno ha presentado a la audiencia pública el reglamento que se va a desarrollar la nueva ley, con el objetivo de próximos INO vigor antes de que termine el año.
Los representantes de los distintos grupos de acuerdo a la hora de hacer hincapié en los esfuerzos realizados por diputados y senadores para negociar y acordar la mejor legislación para garantizar la protección de los inversores y regular en detalle la actividad de las organizaciones para que los mercados trabajen eficientemente.
La MIF, que modifica el Acto del mercado de Valores, implica la modernización de los mercados financieros, mientras que refuerza la protección de los inversores, la mejora de los poderes de control de la Comisión del Mercado de Valores (CNMV) y fomenta la cooperación entre los diversos supervisores de la Unión Europea.
Las nuevas reglamentaciones van a conceder, servicios de asesoramiento a las empresas especializadas, así como a las personas físicas o jurídicas, y crea un nuevo tipo de empresas asesor financiero (ESIS), los asesores financieros empresas (afi), que incluyen las firmas de Valores, intermediarios, y las empresas de gestión de la cartera.
Además, amplía el número de los sistemas disponibles para la ejecución de operaciones financieras, para incluir en el Reglamento son los mercados secundarios, los sistemas multilaterales de comercio, y la internalización de los sistemas de órdenes, se podrá competir con los actuales gestores del mercado de Valores.
La Ley exige también las empresas de servicios de inversión revelar al mercado los detalles clave de su negocio perfil, la exposición a los riesgos y las formas de gestión de riesgos, y mantener un registro de todos sus operaciones a facilitar la supervisión por la CNMV.
En su paso por la Comisión de Asuntos Económicos del Congreso, se han introducido varias modificaciones, principalmente securitised deudas deben considerarse como un "instrumento financiero complejo" debido a su elevado riesgo para los inversores, que se ha demostrado por lo que sucedió con el alto riesgo de las hipotecas estadounidenses deudas (hipotecas).
Además, la transposición aprovecharon la Directiva legalmente a definir las funciones que pueden desarrollar graduados de economía y finanzas en 30 años después de la aprobación decreto en 1977, que delimits las funciones profesionales reservado a los economistas profesional.
Por su parte, el Senado promovió la creación de un nuevo papel en el sector financiero, como el asesor financiero, ¿quién trabajará para contratar o recompensa, no requiere el SEC aprobación y serán capaces de ofrecer sus servicios de mediación y de la comercialización de productos a los clientes en varias empresas de inversión, al mismo tiempo.
