La mirada celta en Milán una pena octavo punto
MILAN y céltica están desempeñando el martes a San Siro en busca de la cuestión que se necesita para alcanzar sus respectivos objetivos en el cierre de la "LIGA de campeones", como los italianos están acostumbrados a estar en primer lugar y los escoceses por su condena clasificación.
Los italianos añaden diez puntos y certificadas ya en el quinto día pasar con una corbata en Portugal, mientras que ha celta nueve puntos, pero todavía hay otra para asegurarnos de que el Shakhtar, con seis, y que Benfica, que ha cuatro, no se precipiten.
Estos dos partidos de grupo D será desempeñado en una semana antes de finales de la sexta día, desde Milán tiene que desempeñar en el Mundial de Clubes en Japón, donde hacen su estreno en el 13 en la semi-finals en busca de un lugar para la última sobre 16.
Así, este grupo será cerrado antes de que el resto y Giuseppe Meazza parece a esperar una corbata como el resultado, pero los dos equipos intentará ir de ganar, y los italianos no querrá especular en casa y céltica sabe que ganar sería la primera y aseguraría un mejor cruce a la cuarta parte de Europa.
A los Gordon strachan equipo podría servir incluso una derrota para clasificadas Shakhtar si no gane, pero no puede SER confiado porque la igualdad en nueve puntos significa que la Ukranians aprobar, quienes perdieron la semana pasada en Glasgow (2-1), pero ganó (2-0) en otro duelo vivir.
Así, Milanists amenazan con convertirlo en un amargo noche para los escoceses, que dependen de entrar en los círculos por segunda vez en un corredor de la Liga de Campeones reestructurado, después de que fueron derrotados precisamente en esta última ronda por un objetivo de Kaka ampliado en el tiempo (1-0) después de 0-0 en la ronda.
A la espera de la victoria del « rossoneri "será el Shakhtar a que sólo el ganar hará, en el caso de que perdieron tanto celta entrar en cuartos de continuar con la UEFA.
Y en cuanto a Benfica, a pesar de SER el último y sin ninguna esperanza de permanecer en la cima la competencia europea, podría llegar a un tercer lugar con una victoria, que desempeñan la UEFA.
