Capital político: la guardia húngaro ha realzado el nivel de riesgo del país
Las acciones por parte de la Guardia húngara, establecido en agosto con el apoyo de la circulación de Righter Hungría, ha planteado el nivel de riesgo político de Hungría y a toda la región de una serie de aspectos, según el riesgo analizando división de capital político.
La entidad de investigación emitió un "riesgo advertencia," escrito: las acciones de la Guardia húngara son desencadenar un rebasamiento de riesgo político "que la ya existente entre las tensiones étnicas y de etnia gitana non-Gypsy residentes de Hungría podría calor hasta niveles tóxicos ya en el corto plazo, lo que ha conducido a los conflictos étnicos que pudiera tornarse violenta".
La razón principal de esto es que el húngaro guardia sobre la estrategia política parece estar destinadas a provocar acción de esta naturaleza, el añadido del Instituto de Investigación.
Este es el resultado de una de las más graves fracasos de actores políticos húngaros: "Los principales actores de la vida pública volcó debate público de los romá cuestiones a representantes de los radicales y extremistas fuerzas políticas, que han construido una estrategia política de Gypsy-Hungarian diferencias".
Este, capital político cree, se ha intensificado el problema, por lo que cualquier diálogo normal imposible, reforzando los extremistas, y acentuando la probabilidad de que se produzcan conflictos violentos.
Además, el Instituto de Investigación cree que la extensa interna e internacional a la atención de los medios de guardia húngara "acciones ha perjudicado notablemente la imagen internacional de Hungría, sobre todo en lo que respecta a la creencia en la estabilidad del país y en la sofisticación de su democracia".
Señalan que el aumento de la publicidad y el impulso dado a ã radical y de grupos de extrema derecha en Hungría empezando en el otoño de 2006 han sido parte de la razón por la cual un número de organizaciones llaman a sí mismos "nacional" autodefensa las alianzas se establecían empezando en el verano de 2007.
"El rasgo común de estos grupos es que se autodenominan organizaciones cívicas mientras declarar abiertamente que se están preparando para sus miembros - incluidos defensiva - armados tareas de gestión de catástrofes (alegando, la defensa nacional, el cumplimiento de la ley) mientras declarar que la policía y las fuerzas armadas, en otras palabras, el gobierno, inadaptada para el papel," capital político añade.
Señalaron que todas estas iniciativas que se han hecho dentro de una configuración que se basa en la sociedad y anti-politics anti-political-party humor para manto diferentes ambiciones políticas bajo el manto de la acción cívica.
En otras palabras, su insistencia en la naturaleza cívica de sus acciones y la elección de la asociación como su forma de organización no son meros ruses a esquivar escollos legales para el registro en los tribunales, sino que también forman parte de una estrategia política.
Según el análisis, la actividad de la Guardia húngara está acentuando el riesgo de perjudicar a nuestras relaciones con nuestros vecinos, demasiado.
"En los últimos meses varios de los vecinos húngaros han citado la guardia húngara como un potencial peligro. La ultranationalist actores políticos entre algunos de estos vecinos se han referido a la creación de la guardia húngara como argumento para justificar sus propias políticas contra los húngaros.
Todos estos factores influyen en la estabilidad política de la región ", añade.
El Instituto de Investigación observa que el establecimiento de la Guardia húngara no es un fenómeno único en Europa central y oriental, y como tal, aumenta el riesgo político para el conjunto de la región.
Se observa que el funcionamiento de la Guardia húngaro es similar a la de la guardia nacional búlgaro, establecido en agosto de 2007 por la extrema derecha de la Unión nacional búlgaro. (BNU).
Los graves conflictos que estalló entre romaníes y no romaníes en un distrito Sofía (Krasna Polyana) estaban detrás de la creación de la guardia búlgaro.
Bnu se ha aprovechado de los disturbios para establecer la Guardia, al afirmar que el objetivo de la organización era "nacional" autodefensa.
Argumentaban que durante los últimos 17 años, Bulgaria había sido objeto de terror "gitano", en que el gobierno se mostró inerme y indiferentes, capital político nota.
La iniciativa ha desencadenado un debate acalorado entre la opinión pública búlgara, se ha añadido.
Una señal de que el riesgo de un conflicto étnico ha aumentado, los analistas escribió, es que algunas organizaciones romaníes en Bulgaria han anunciado planes para establecer un guardia de sus propios como una fuerza de resistencia.
Desde la guardia húngaro ha actuado hasta ahora muy similar a la guardia nacional búlgaro, es muy posible que la comunidad romaní de Hungría podrían responder a la amenaza de organizar su propia defensa propia, escribió capital político en la advertencia del riesgo.
Capital político gestor de investigación Attila Juhász respondió a una pregunta del servicio de alambre húngara MTI diciendo que el análisis de riesgos fue una de las actividades jefe del Instituto de Investigación.
Cada año, dijo, publican análisis de riesgo, y si se descubre cualquier elemento que pudiera alterar riesgos, que notificar a la opinión pública por publicar una advertencia de riesgos, como lo han hecho ahora.
