La Fed espera que reducir los tipos, va a conducir al mundo emergente mercado accionario
Comparte saltó a ambos lados del Atlántico después de mercado ayer espera que la Reserva Federal va a tratar de calmar las condiciones de crédito con nuevas reducciones de los tipos de interés eran contemporizadora, impulsado por los comentarios de los EU vicepresidente del Banco Central.
Los mercados accionarios situado volando en Londres, Nueva York y en toda Europa después de Donald Kohn, n º 2 a Ben Bernanke, Presidente de la Reserva Federal, dijo que los estrategas políticos deben SER flexibles "y" pragmáticas para responder a la continuación de estrés en los mercados financieros.
En un claro intento de tranquilizar a los mercados fretful en medio de señales de crédito renaciente cepas, señor Kohn dijo que los recientes turbulencias "habían invertido en parte algunas de las mejoras en el funcionamiento del mercado a lo largo de la tarde parte de septiembre y en octubre de".
Si la elevada turbulencias persisten, aumentaría la posibilidad de una regulación más estricta en condiciones financieras para los hogares y las empresas, dijo.
Los comentarios fueron adoptadas por parte de los inversionistas como una señal de que la Reserva Federal está dispuesta a paso en con nuevas inyecciones de capital en los mercados estadounidenses, y a las posibles nuevas reducciones de los tipos de interés, para estabilizar las condiciones de crédito.
Las observaciones también contribuyó a la calma Wall Street en medio de más malas noticias sobre la economía estadounidense, como las ventas de los hogares un golpe bajo récord en octubre.
Las consecuencias de las turbulencias financieras fue subrayado por un anuncio de tener stearns, el Banco de Inversiones, que recortará 650 puestos de trabajo, o 4 por ciento de su fuerza de trabajo global, en una ronda de reducir costes para compensar pérdidas de perder sus apuestas con respecto a los Estados Unidos de las hipotecas de los préstamos hipotecarios sector.
Sólo el 20 de estos cargos se espera a ir en Londres, donde el Banco emplea a 1.500 personas.
En Nueva York, el promedio industrial Dow Jones saltó por 331 puntos, o 2.55 por ciento, para terminar en 13,289.40 sobre una base más amplia, mientras que el índice S & P 500 aumentó un 65 por ciento.
En Londres, el índice FTSE 100 aumentó 165.5 puntos, o un 2,7%, cerrar en 6,306.2, añadiendo más que £39 millones de dólares para el valor de Reglamento de Gran Bretaña.
El índice bursátil DAX aumentó 2.6 por ciento, y Francia se CAC40 2,3 por ciento.
Antes, el estrés reemergence de crédito en los mercados ha sido puesto suficientemente en evidencia tras la fuerte demanda en una subasta de fondos de tres meses por el Banco Central Europeo presenciamos aquellas prestado a los bancos comerciales en una fuerte 4,7 por ciento, la tasa más alta desde abril de 2001.
La presión sobre el Banco de Inglaterra a seguir a la Fed y el BCE e inyectar fondos adicionales en los mercados de dinero en Londres montado como vimos cepas de crédito "de tres meses libor" para los préstamos los tipos entre los bancos del Reino Unido empujado a su punto más alto desde finales de septiembre, en 6.59 por ciento, después de un constante ascenso desde noviembre de 12.
