Environmin Hungría y seis por ciento
Ministra de Medio Ambiente, Gábor Fodor ha dicho que el nivel profesional reuniones sobre cuestiones del clima internacional posterior a 2012 terminará el martes. La propia Conferencia abre oficialmente el miércoles, cuando los Ministros tomar la palabra.
Los profesionales y políticos de 192 países están proyectadas para discutir la Hoja de Ruta de Bali, que se centra en los esfuerzos para reducir las emisiones de gases de efecto invernadero después de 2012, cuando expire el Protocolo de Kyoto.
En la actualidad las naciones en desarrollo y desarrollados son en medio de una acalorada disputa.
Los Estados Unidos ha hecho saber que no está dispuesto a negociar cifras exactas, aunque no se opone a aceptar un recorte 25-40 por ciento en las emisiones de gases de invernadero en 2020, en comparación con 1990.
La otra gran cuestión en la Conferencia es si las naciones desarrolladas están dispuestos no solo a reducir sus emisiones, sino también a ofrecer asistencia técnica y financiera a los países que la necesiten.
Un acuerdo alcanzado fue en el apoyo a las naciones en desarrollo.
Una junta 16-member va a gestionar los fondos para este, que está fijado por el Protocolo de Kyoto, y lo más probable es que trabajar en el Medio Ambiente Mundial de las Naciones Unidas Facility (gef), escribe la publicación locales Piac és beneficios.
Seis por ciento de Hungría
En representación de Hungría. Ministra de Medio Ambiente Gábor Fodor está dispuesta a apoyar los esfuerzos de la UE para conservar su buque insignia papel en la protección del clima global esfuerzo y promover un nuevo acuerdo internacional, para SER alcanzado en 2009.
Fodor observaba que la UE tiene su mirada en un 20 por ciento de reducción en las emisiones de gases de efecto invernadero para 2020 en comparación con 1990, si el "acuerdo posterior a 2012" es alcanzado o no, y está dispuesta a recortar ellos en un 30 por ciento si las otras grandes regiones desarrolladas del mundo y las naciones en desarrollo también está dispuesta a aceptar las obligaciones de la magnitud de sus capacidades y responsabilidades.
Fodor dicho que ya en 1997, los países que se adhieren al Protocolo de Kyoto había dirigido un 5, 2 por ciento de reducción de las emisiones globales. En el seno de ese grupo, la UE de 15 miembros acordaron un 8 por ciento de la decadencia.
Hungría acordaron reducir sus emisiones de gases de efecto invernadero en un 6 por ciento en comparación con el 1985-1987, un objetivo va a cumplir, dijo el comunicado de prensa del Ministerio de Medio Ambiente.
Las apuestas en Bali es alto, por un acuerdo internacional a largo plazo en la política climática debe estar bajo la manta dentro de dos años o sin duda no podrán entrar en vigor por 2012.. En caso de que eso suceda, las promesas hechas durante la vigencia del Protocolo de Kyoto no sería seguido inmediatamente por otro régimen emissions-reduction, la necesidad de que las Naciones Unidas, órgano científico Nobel-Prize ganar, el Panel Intergubernamental sobre Cambio Climático - IPCC- ha señalado en su último informe.
El resultado podría SER un retraso en la reducción de emisiones, que dejaría a la tierra en el camino hacia un promedio de temperatura superior a 2 grados Celsio. En caso de que eso suceda, los científicos dicen las consecuencias serían terribles e irreversible.
