El programa nuclear pakistaní genera una gran intranquilidad en los EE.UU. 
Islamabad produce armas atómicas en "una tasa más rápido que cualquier otro país". 
Las filtraciones de Wikileaks confirmar los lazos entre los talibanes y el Pakistán. 
El contenido de la correspondencia entre la embajada estadounidense en Pakistán y el Departamento de Estado de los Estados Unidos filtrados por el portal de Wikileaks confirma la enorme inquietud que el programa nuclear pakistaní provoca en Washington. 
Además de las esclarecedoras y sustanciales que se ofrecen detalles sobre el contenido de las conversaciones y las ideas de los representantes diplomáticos acreditados de América del Norte en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de seguridad nuclear, en lugar de aumentar, "disminuye", y que la inestabilidad en el país asiático produce armas nucleares con "un ritmo más rápido que cualquier otro país". 
La peculiaridad del programa nuclear paquistaní, que las armas no están reunidos pero siguen almacenadas por componentes para dificultar su destrucción en caso de attack-- constituye una de las principales causas de preocupación en Washington. 
Así es enumerados por el embajador en Pakistán, Anne W. Patterson, en un informe anterior a la visita del ex asesor de Seguridad Nacional, James Jones: "La proximidad de algunas centrales nucleares en el territorio bajo ataque talibán, los rumores de dispersión de los materiales nucleares y la vulnerabilidad de transporte de materiales nucleares". 
El elevado número de personas implicadas en los arsenales nucleares y programas de misiles se está tomando en consideración, no sólo por los Estados Unidos, sino también por Rusia, tales como la razón para mantener su guardia. 
"Pakistán ha tenido que contratar a personal con estrictas creencias religiosas a fin de proteger a las centrales nucleares; dada la escasa niveles educativos y culturales, las organizaciones extremistas tienen más oportunidades para reclutar personas para trabajar en los programas nucleares o de misiles", dijo el experto Yuri Carole, desde el Ministerio de Relaciones Exteriores, en una reunión con sus homólogos norteamericanos. 
La información más reciente sobre los documentos filtrados por el portal de Julian Assange, es la disminución de la cooperación entre los Estados Unidos y Pakistán en temas de la proliferación nuclear y la elevada tasa paquistaní de producción de armas nucleares. 
Una oficina de la embajada en mayo, que describe como "frustrante" la comunicación con el Pakistán, afirma que: "La transparencia es a menudo inexistente; las ofertas de asistencia siguen sin respuesta o se negó". 
En otro mensaje, Peter Lavoy, funcionario de la Inteligencia Nacional para el sur de Asia, afirma que "a pesar de la catástrofe económica, el Pakistán produce armas nucleares a un ritmo más rápido que cualquier otro país del mundo". 
El embajador Patterson también pide Washington, durante una visita del jefe del Ejército, el general Ashfaq Kayani, para dar órdenes claras a la persona encargada de que "el Ejército de Pakistán debe acabar con el apoyo tácito a los grupos terroristas". 
