El geriatra afirma que las muertes fueron causadas por "la falta de medios" 
Los dueños del centro de Olot no desechan a aquel su asistente matado más de 11 personas mayores 
La gente responsable con el hospital geriátrico que el La Caritat de Olot (Gerona) ofreció a una rueda de prensa ayer a fin de subrayar el daño que ha causado a la institución la conducta criminal de Joan Vila Dilmé, la enfermera quien mientras allí mató a al menos once personas mayores que él tenía bajo la vigilancia. 
El director de la residencia, Joan Sala, pareció acompañado por el abogado del centro, la abogada Joan Canada, y anunció que "la intención de La Caritat iba para fijar la culpa en el individuo responsable de las muertes, pero "legalidad y la responsabilidad nos obliga a asumir la situación procesal de la gente responsable civil." 
Y esto además de la pérdida social del prestigio que organización puede encontrar no haber descubierto a tiempo las actividades delictivas del vigilante, la gran amenaza para Caritat tiene ahora adopta la forma de una indemnización sustancial que es calculada ya por los representantes legítimos de los familiares de las víctimas. 
Joan Vila Dilmé ha admitido que el primer delito vuelve hasta agosto de 2009 y que desde entonces no dejó de matar. 
El juez ya ha mencionado en el documento que se pedía la exhumación de ocho cuerpos - viejos pacientes del hospital geriátrico - a quien sospechó que en muchos casos ningún doctor personalmente exploró los cadáveres, pero, teniendo en cuenta edad y las patologías de los pacientes, el procedimiento se hizo por teléfono. 
El La Caritat, por su director, totalmente negó este final ayer y mencionó que "la falta de medidas no habría sido en cualquier momento la causa de lo que había sucedido." 
El abogado de La Caritat añadió que "en la causa no hay indicación que se ha producido una acción imprudente en nombre de cualquier otra persona que no sea la culpable." 
El que bautizado como "El ángel de la Muerte" admitió 11 asesinatos anteayer y detalló esto destinó el primer delito el 29 de agosto de 2009 y un mes y medio más tarde, mató a otra abuela. 
En este caso una sobredosis de la insulina le trajo la muerte; a diferencia del primer delito destinó con una mezcla de pastillas sedativas. 
El director de Caritat dice que se complica para controlar esto el personal del centro tiene el acceso a medicinas. 
La sobredosis de la insulina y el cóctel sedativo habría sido el mecanismo usado en seis de los nueve delitos que la enfermera, en su ansia por aliviar el sufrimiento de los pacientes, usados o matanza de ellos. 
Pero las pruebas que se están realizando en el laboratorio tendrán que clarificar si Vila no está y procesado para asegurar para sus primeras víctimas una muerte menos cruel o si, al contrario, quemado ellos internamente al darles la lejía ya que él ya admitiera que había hecho con las tres mujeres que él mató entre el 12do y el 17 de octubre. 
En el La Caritat no dan la credibilidad a la aparición del vigilante, ni al número de asesinatos admitidos, que no refutan ser superior, y justifica su actitud en las versiones diferentes que Vila ha dado en sus visitas al tribunal y las tonterías de cambiar su método de matar después haber destinado con éxito, ocho asesinatos. 
Por eso dicen que se ponen a disposición de justicia para aclarar el alcance de este acontecimiento. 
