Nombramientos de Grammy: El cantante del jazz Esperanza Spalding es una elección de sorpresa en la mejor nueva categoría del artista 
Funcione a petición de un presidente, y la gente está obligada a hacer caso. 
Esperanza Spalding, el bajista del jazz de 26 años y cantante escogido a mano por el presidente Obama para operar en su ceremonia el Premio Nobel de Paz en 2009, marcó una de las sorpresas de Grammys este año con un nombramiento destacado en la mejor nueva categoría del artista. 
La consideración que Spalding ha sido una cifra famosa en la fase de jazz desde su álbum de 2008, "Esperanza", el nombramiento es un poco un jefe-scratcher, pero es coherente con las normas de Grammys de un artista que no publica más de tres álbumes antes de la grabación que "establece la personalidad pública de aquel artista." 
Su álbum de 2010 ambicioso, "Sociedad de la Música de cámara," seguramente marcó un paso adelante, y dado su estilo vocal atractivo de manera confiada y una mano hábil con música pop, canguelo e influencias latinas, es posible retirar al menos una línea de puntos a Spalding del éxito fugitivo de Norah Jones en 2003, el equivalente más estrecho con votantes de Grammy que miran hacia la vecindad del jazz en esta categoría en los últimos años. 
En lo contrario, los votantes de Grammy correctamente cumplieron "la Historicidad" del Trío Vijay Iyer en la categoría de álbum instrumental, un paseo por la emoción vigorizante de un registro que fue un favorito crítico el año pasado. 
Entre aquellos Iyer competirá contra incluyen a "Moody del saxofonista veterano James Moody 4B" y "Positootly" de John Beasley keyboardist. 
Shorty del trombón, una Nueva Orleans estentórea invitado favorito y frecuente en "Treme" del HBO, se honró en la categoría de jazz contemporánea, que, de otro modo, se inclina pesadamente hacia la fusión con cabezadas hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
La sociedad secreta de Darcy James Argue salvaje, steampunk-informado ganó un poco de reconocimiento merecido en la categoría del conjunto grande, que compite contra el jazz de la cámara rico de Billy Childs Ensemble y Dave Holland alguna vez aventurero, cuyo álbum en directo del octeto "Caminos" era un ejemplo fino de la mano democrática del bajista como un bandleader. 
