Con la Literatura pueden poner el dedo en ello 
El segunda ronda de Los placeres de lengua era un paseo sobre el que los participantes decretaron la narración 
¿Esto del sexo en la lengua entiendo que, pero... el dedo en ello? ¿Qué se espera que haga? se informó la escritora Luisa invitó a Valenzuela invitado a abrir el segundo round de Los placeres de la lengua, acontecimiento que celebra la Literatura en español y que esta vez usó el subtítulo de su pregunta (de otro modo la mesa redonda se dedicó al sexo en la lengua, explicó). 
El dedo en ello... "esto nos coloca en una posición difícil," dijo dulcemente directamente el escritor argentino al público, principalmente de jóvenes, que se reunieron en la Feria Internacional del Libro de Guadalajara (FIL) para escuchar esta mesa redonda moderada por Marisol Shultz y participaron Valenzuela, Sergio Ramirez, Mayra Montero y Luis Garcia Montero todos participaron. 
Luisa Valenzuela leyó un texto que dedicó a Gonzalo Celorio y que Shultz definiría más tarde como una gran historia, con Luisa en la primera persona como el protagonista que en busca del conocimiento conocido como "ello", va del doctor al doctor, de quien no obtiene respuestas aunque se atasque en el mismo hilo narrativo. 
Se va el doctor convenció: "quizás la paciencia no es mi fuerte, tal vez es mi llaga." 
Al final, después de un enfoque frustrante con el doctor del trauma quien quien clarifica que la llaga no es un término científico; es el psicoanalista que desenmaraña el misterio: "la llaga es la verdadera cosa abierta; la cosa simbólica es la cicatriz." 
El protagonista suspiró aliviado y concluido "en la llaga sólo logré saber que la verdadera cosa está abierta y que esto no existe," pero convenció de que se tienen que mezclar los placeres y las bromas de la lengua. 
Valenzuela, el escritor, jugó con ambos. 
El nicaragüense Sergio Ramirez también expuso una narración encantadora que tituló la Alabanza de la invención, donde el dedo en la llaga no se llama, pero se descubre. 
En amplios términos del realismo mágico, conta la historia de una bruja famosa, que por nubes conmovedoras, devolvió a hombres que habían ido lejos o habían reparado las virtudes perdidas por una criada, narración que se convirtió en el hablar sobre América, una gran novela que no careció a partir del mismo principio de sus propios cronistas que lo dijeron y mencionaron a Bernal Diaz del Castillo que critica los excesos de las cosas dichas por los capitanes conquistadores. 
Cervantes que inventó a todos (los escritores) se rió de los testigos falsos que aparecieron en historias presentadas como verdaderos, pero de lo contrario, nunca habría dicho la historia de Estados Unidos con la imaginación que carecen de timidez. 
Sin embargo, enfatizó "a las personas loca y los mentirosos son los que mejor imaginan cosas" y ahí es donde la realidad y la falsedad se mezclan, donde uno sabe si la cosa relatada pertenece a uno u otro, donde la Literatura ficticia alcanza su apogeo. 
De hecho se llama "la tradición de Cervantes. 
"Para su filosofía de: somos lo que se dice de nosotros." 
En cuanto a ella, el escritor Mayra Montero vio y aplaudió a la diversificación de interpretaciones que la invitación de FIL causa con su mesa redonda El dedo en la llaga. 
El cubano-puertorriqueño la señaló propio hacia la gran llaga de la violencia social que cruza su país - y divide América Latina - el producto de las disputas sobre venta de la droga y tráfico. 
Creo que Literatura buena, poesía buena, las canciones buenas cierran un compromiso tácito que por supuesto no es premeditado, indicado, después de mencionar que la realidad de Literatura es la comunicación y la dimensión del compromiso que se instala entre autor y lectores, y es una "reacción química" de esta última. 
La noche fue cerrada por el poeta español Luis Garcia Montero cuya intervención también puso el énfasis "que el dedo en la llaga del escritor puso por escrito." 
Él consideró que en un mundo que viven en prisa, también en la aduana intelectual y el control del conocimiento que tiene efectos en dogmatismos, olvidando "que detrás de cada afirmación hay un pequeño no y detrás de cada negación allí es pequeño sí." 
"A fin de ser dueños de nuestro pensamiento y realidad que debemos clarificar: y a menudo clarifique medios para establecer el dedo sobre la llaga y molestar a las personas que es el pensamiento mucho más cómodo sobre el dibujo animado, negro sobre blanco,, en ideas establecidas sin lugar y también molestarse a los poderes que prefieren un mundo blanco o negro," dijo, invitando para recuperar el sentido de escritura. 
