IP solicita resultados del Congreso 
Eduardo Dávalos, el presidente del CEC, propuso que las autoridades asuman la gran responsabilidad de ser un ejemplo para mejor Sinaloa por los desafíos diversos que se vuelve. 
Una Legislatura de trabajos decentes y libre de acuerdos entre partidos y el estado Ejecutivo está siendo exigida por el sector de la empresa de Mazatlán, porque hay Sinaloa convulsionado que afronta grandes problemas. 
Ayer la 60 legislatura se votó en, integrada por siete fuerzas políticas, 19 diputados del PRI, 13 de la CAZUELA, tres del Partido Nueva Alianza, dos de los PRD, uno del PUNTO, uno de Convergencia y uno más de los PVEM, queriendo decir un total de 40 representantes populares. 
Entre la lista de expectativas de los nuevos diputados al Congreso del S-estado se menciona que vienen a cumplir una dirección limpia de compromiso con la sociedad y los diferentes sectores que requieren un trabajo legislativo responsable. 
Eduardo Dávalos Zamora, el presidente del Consejo de Coordinación de la Empresa, propuso que los 40 diputados liberados justos del Congreso del estado asumieran la gran responsabilidad de ser un ejemplo para mejor Sinaloa por los desafíos diversos que se vuelve. 
Esperamos que las autoridades realmente ejerzan su derecho, libre de acuerdos entre las partes porque es una costumbre para hacer acuerdos para protegerse por sus propios intereses y ellos se convierten en un carácter en un carnaval de los gobernadores y los líderes de las fracciones parlamentarias. 
Por este motivo, ha hablado de la certificación del compromiso con el fin de establecer los puentes necesarios que podrían ayudar al Gobernador a seguir adelante. 
Esperamos que vengan para hacer un trabajo digno y principalmente destinado a la sociedad y los sectores porque los habitantes de Sinaloa eran aquellos que les dieron el voto de confianza durante las últimas elecciones. 
Jose Ramon Manguart Sanchez, el presidente de la Asociación de Hoteles Tres Islas, consideró que uno de los mayores desafíos para los 40 representantes populares es el que de empujar y añadir fuerzas en busca del crecimiento económico del estado, porque hoy día la situación económica es muy complicada. 
Lo más importante es empujar el crecimiento económico, que genera incentivos para inversión e infraestructura y la de alguna manera formará una nueva generación de empleos. 
En cuanto a la actividad turística, exigió que los nuevos legisladores den el peso revisado en el presupuesto estatal para fortificar al Secretario de Turismo. 
Como he entendido que se trata el segundo departamento del estado con menos presupuestos y es incongruente unas divisas de generación de la actividad económica e importantes e inversión y esto directamente compite con la industria agro. 
Aparte del requerimiento de recursos de etiquetaje el turista que detona preve que ayudan a la seguridad que da al estado y actualizan la Ley de Alcohol que no ha sido capaz de solucionar en las legislaturas anteriores. 
