Israel: Caos Lab.
"Nada viene de la violencia y no podría nunca", de Sting 's Frágil, donde uno de los principales versículos del estribillo es "Para que nos olvidamos de lo frágil que son".
"Si mis hijos no quiere la guerra, no sería nada", dijo el moribundo Gutle Schnapper, esposa de Mayer Amschel Rothschild en 1849.
La última ola de violencia entre Israel y la Franja de Gaza, como siempre, ha suscitado mucha reacción.
Algunos están por Israel, argumentando que tiene el derecho de auto-defensa, y los palestinos se presentan como terroristas, mientras que otros de apoyo a los palestinos, alegando el racismo por parte del Estado de Israel, afirmando que se está cometiendo un genocidio contra los árabes palestinos, y que Israel es un Estado terrorista.
No quiero detenerme en estas repetidas olas periódicas de matar, sobre quién es el transgresor y la víctima, que es, después de todo, hoy 's habitantes de Israel, incluida la auto-sobre territorios, nacieron en la situación política actual, y no viven en el inicio de la violencia.
Me gustaría ofrecer a los lectores una mirada detrás de bastidores, un vistazo a las que, sobre todo, este año 95-tensión está cumpliendo (a partir de Balfour 's declaración en noviembre de 1917) en este pequeño pedazo de tierra en el Oriente Medio.
Algunos de mis pensamientos están disponibles con el apoyo de los hechos históricos, mientras que otros se derivan de mi propia comprensión de que, es decir, que un grupo de personas es la principal fuente de los acontecimientos en la historia moderna.
La historia de la humanidad es en primer lugar sobre la lucha por el poder.
En cada época podemos encontrar un Alejandro Magno o un Napoleón.
Lo que no es tan evidente es si estos fueron las personas que habían elegido el camino de manera independiente, o si detrás de su trono era alguien que dirigen sus acciones hacia una pre-objetivo calculado.
Debemos aceptar que vivimos en un momento en que el mundo 's la riqueza se concentra en manos de unos pocos individuos, y que esa concentración de la riqueza y el poder que emana no podría ocurrir en una generación 's vida.
Entre estos astronómicamente familias ricas, destaca, lo que podría considerarse el maestro de marionetas (si alguien está por encima de ellos, no sé, pero yo no descartarla) - los Rothschilds.
No mucho se ha escrito acerca de ellos.
Es comprensible.
La primera agencia de noticias (Reuters) compraron en los 90 's del siglo XIX, con el fin de evitar que su nombre está relacionada con los actos de alta delincuencia, que apareció en sus antecedentes y que siempre significa conservar el poder y la riqueza, o ambas cosas.
Poseen participaciones mayoritarias en casi todos los bancos centrales del mundo, y contra los países que no poseen un juego, ellos están librando o la preparación para la guerra (antes del ataque a Afganistán era de 7 países, después de que el Iraq se 5, tras el derrocamiento de Gadafi 4, pero en el ínterin Rusia presentó su banco central para el Gobierno ruso).
Quienquiera que intentaron desafiar esta familia murieron.
Abraham Lincoln se negó a renovar la situación del banco central para el Banco Rothschild de América, y durante la Guerra Civil comenzó a emitir su propia (que es estado-emitió) dinero y fue asesinado en 1865 en el teatro.
JFK comenzó a expedir su propio dinero y quería cerrar la Fed (Reserva Federal), y fue asesinado en 1963, el congresista Louis Gates fue envenenado en 1936, después de haber tenido la intención de demandar a la Reserva Federal para causar la Gran Depresión de 1929.
Su sed de poder mundial conducido en los años de 1859 - 1871 a la formulación de un plan de guerra de tres-mundo-masón por el líder de la 33ª grado, Albert Pike.
La primera guerra era eliminar a los grandes órganos estatales monárquica en Europa, el segundo fue para eliminar la dominación colonial, especialmente de Gran Bretaña, y la tercera reducirá el mundo 's población hasta 0,5 - 1 000 millones de personas (el número de esclavos será suficiente para su confort y lujo, y no consume muchos recursos), la creación de una fe universal (el ecumenismo es solo un aperitivo para esta solución) y, finalmente, la toma del poder absoluto.
El método, que el grupo de familias adineradas con los Rothschilds mostrando el camino, es la instigación de las crisis, seguido por el ofrecimiento de una solución (orden ab chao - el orden del caos).
Estas soluciones son falsas, sin embargo, y siempre dar lugar a una situación peor (véase la creación de la Reserva Federal, para que la crisis no se repetiría de 1907).
Así, después de haber logrado asesinar Ferdinando Habsburgo, el heredero del trono, Austro-húngaro en Sarajevo para desatar la Primera Guerra Mundial, destruyeron la Rusia zarista con la revolución bolchevique.
La Primera Guerra Mundial terminó abruptamente, militar y económicamente de fundamento, con la capitulación alemana (la guerra ya no era necesario para destruir la Rusia zarista) y el centro de potencias europeas de Austria-Hungría posteriormente fueron desmantelados.
Para facilitar el inicio de la Segunda Guerra Mundial, permiten que los banqueros y los políticos para crear un conflicto latente situación imponiendo a Alemania con enormes indemnizaciones de guerra, haciendo radicalist un ejemplo de las masas empobrecidas, sólo quedaba suficientemente convincentes para introducir un culpable y un líder con una solución simple, y al mismo tiempo crear un multi-racial Checoslovaquia con una fuerte minoría alemana para jugar y, de hecho, hizo el papel de un quinto colonia, una vez que la guerra había sido encendidos.
A finales del siglo XIX, los Rothschilds instigaron la creación del movimiento sionista, una rama de la que se esforzó para formar el Estado judío, buscando un espacio histórico de Judea, Jerusalén, para hacer de su capital (el Retorno a Sión).
La mencionada Declaración de Balfour fue la base de la inmigración masiva de los judíos a Palestina, donde los primeros conflictos comenzó con la población árabe.
Los ataques terroristas ocurridos en ambos bandos.
La Segunda Guerra mundial, y si Hitler se soltaron de la correa, que los banqueros internacionales estaban celebrando sobre él, o si sus acciones formaban parte del plan, es difícil de determinar, sin embargo el sufrimiento de los judíos europeos en los campos de concentración creó la fundación para el mundo 's aceptación del Estado judío.
Israel fue oficialmente creada en 1948, y al igual que las indemnizaciones de guerra durante la Segunda Guerra Mundial fueron sea inglés (en Alemania, el anuncio del Estado de Israel se convirtió en la tercera guerra 's semillero.
Siempre que el éxito de los banqueros internacionales, la nación judía, como con el segundo, serán las víctimas en la línea del frente, ahora junto con el árabe o, más en general, musulmán, con una población de Oriente Próximo.
Israel es como un gran laboratorio, una fuente de discordia y el caos no sólo en el país, sino a nivel internacional (sólo mirar a la firmeza con la que la gente se dividen entre partidarios y adversarios de Israel).
¿Quién es el mal-hacedor y quién es la víctima en el conflicto Palestina-Israel, donde la injusticia engendra la injusticia en un ciclo interminable de violencia, mientras que todo comenzó por la codicia de unos pocos y su ansia de poder mundial?
En este sentido, debemos diferenciar entre Israel 's población general y sus dirigentes, porque, al igual que sucede aquí, los banqueros internacionales introducir su propia selección de candidatos a la gente a votar a favor.
Israel 's actual Primer Ministro Netanyahu, la 'halcón', es un ejemplo típico de un político fascista, leales a los banqueros internacionales, que hace todo lo posible para instigar la guerra con Irán, que, debido a su condición de miembro de la Organización de Cooperación de Shangai (China, India, Rusia, Pakistán,...) conducen a una mayor amenaza de conflicto mundial, y a través de su control del Estrecho de Ormuz, donde el 20% del petróleo mundial 's deben navegar (el canal está a sólo 2 km de ancho), a la destrucción del mundo 's economía.
En lo que la luz resistir las palabras, habladas por David Rockefeller en 1994: "Todo lo que necesitamos es una gran crisis y las naciones aceptarán el Nuevo Orden Mundial".
El Nuevo Orden Mundial en sus ojos es uno de maestro y esclavo.
Un mundo en el que el resto de la población humana servir el lujo de un puñado de aristócratas.
Un mundo donde cada nuevo-nacido es implantado con un chip, lo que hace que su existencia completamente sometida.
"También obligado a todos, grandes y pequeños, ricos y pobres, libre y esclavo, para recibir una marca en la mano derecha o en la frente, por lo que nadie podría comprar o vender a menos que tenía la marca, que es el nombre de la bestia o el número de su nombre.
Si alguien tiene intuición, calcular el número de la bestia
Por ello es el hombre 's número y su número es seiscientos sesenta y seis ".
