"Sangre De mayo", una épica reto por Garci. 
José Luis Garci, inspirada en la novela Episodios Nacionales de Banito Pérez Galdós, recreates en Sangre De mayo la revuelta spanish popular contra los franceses, que es el más ambicioso trabajo de su filmography, con casi 15 millones de euros de presupuesto. 
Con esta película, el director ha intentado "explican el torrente de personajes y al mismo tiempo el análisis social" que siempre admirado en el trabajo de la novelista famoso, dijo hoy, en la película la presentación, con Quim Gutiérrez y Paula Echevarría encabezando una mayor emitidos de intérpretes. 
Sangre De mayo, una película más de 14: 30 horas, debuts este viernes en los cines, a convertirse en cuatro horas de televisión miniseries sobre TeleMadrid en el futuro próximo. 
Gran admirador de Galdós « material, José Luis Garci reivindicaciones este tiroteo dieron cuenta "un sueño de su infancia", le gusta dar las gracias a Esperanza Aguirre, que, tres años antes, había encargado a disparar una película para conmemorar el segundo centenario del Madrid 2 de mayo: era la voluntad expresada por la Comunidad de Madrid; el director acordado con la condición de que la historia basada en la novela Episodios Nacionales. 
Los 15 millones de presupuesto totalmente por la Comunidad de Madrid por Garci una oportunidad "único" para recrear la marca adecuado y trajes para dibujar un "atónita España que optó por el líder equivocado a luchar por ellos y el hecho de que la lucha por la independencia que llevaba a un enorme retraso en desarrollo durante el reinado de Fernando VII" dijo Garci. 
Sin embargo, el director se lamenta de no haber recibido fondos igualdad de Alatriste o Los fantasmas de Goya, más del doble respecto a Sangre De mayo., no fue posible a disparar algunas escenas incluido en el plan, que él mismo había firmado junto con Horacio Valcarcel, su colaborador career-long. 
La diferencia de presupuesto influido la forma habitual de trabajo del director del Volver un empezar: por ejemplo, la organización con los agentes, con el que suele utilizar a recuperar antes de disparar junto con los que no pertenecen a la, este "" y que "la labor del director reside en ir al teatro y el cine para la industria que está trabajando para está pasando". 
Una serie de intérpretes, algunas de las cuales son emitidos de Sangre De mayo, repetir en frente de su video-camera. Es el caso de Michael Rell, Carlos Larranaga o Fernando Guillen Cuervo. 
Cuatro veces en los Oscar candidaturas, ganar, Garci cree que ninguno de los tres candidatos las películas para representar a España en Hollywood este año, su Sangre De mayo, mesas Siete De francés billar, y Los ulitmo seleccionados girasoles ciegos representan a los cines españoles jóvenes ", que se conocerá en lugar". 
Garci no espera premios de esta película. 
"Al principio de trabajo para la posteridad, advierten que sólo trabajo para la prosperidad, y en cierto momento sólo disparar una película más", dice García después de más de 30 años de carrera. 
