Usted lo comparte 
Sobre su cumpleaños 10º Google puede admitir: allí en el pueblo del bolsillo, así como sobre su cabeza, en el cielo. Google sabe dónde ir de vacaciones, qué tipo de consultas médicas que visita y lo que les interesa. 
A pesar de todo, Eric Schmidt, una persona clave de la compañía es aún no satisfechos. 
Por otro lado, los escépticos que en paralelo con Orwell de fantasía terrible no puede ver la esencia de la web 2.0. 
Eric Schmidt declaró recientemente al Financial Times que el principal objetivo de Google fue a recoger más información personal de los usuarios es necesario mantener los fundadores de Google « objetivo original, a saber: "para crear un sistema para toda la información del mundo", añadió. 
Según la Google-chief, la empresa, después de haber para todo el mundo en los últimos 10 años, aún está en el inicio de la vía hacia la capacidad de tratamiento de la información. 
Ante la pregunta sobre sus planes para los próximos 5 años dijo que se ocupa de que Google sea capaz de responder a preguntas como "¿Qué voy a hacer mañana?", o "¿Qué tipo de puestos de trabajo me mejor?", sin embargo, el software no puede dar las respuestas adecuadas a estas preguntas, aparentemente sencillo puesto que el importe de información al usuario no es suficiente. 
No todos los usuarios de Internet son conscientes de que los términos registrados por ellos se registran, así como la dirección IP utilizado para la búsqueda y las páginas visitadas por posteriormente. 
Utilizando la 2-year-old Personalized función busca, los usuarios pueden almacenar surfing propios historias, que podrán revisar lo que buscábamos, qué tipo de relaciones que buscadas: en el largo plazo, puede ofrecer los usuarios con resultados personalistas. La función llamó las recomendaciones se basará en la misma lógica: se nos pueden ofrecer productos y servicios por parte de la ayuda de las preferencias y registrado antes. 
"¿Qué sucede si mis datos personales son utilizados contra mí, si se descubre lo que hago?", algunos de los usuarios de la information-monopoly de Google. 
Normalmente es el grado de el potencial de la compañía que genera contrarrestar reacción en los usuarios, no sentimiento de culpa, miedo, de castigo, deseo de libertad o la rebelión contra la autoridad. 
Sin embargo, se ha confirmado que todos los registrados términos se registran y, en su caso, puede incluso ser transferidos a terceros. En estos casos no protege la privacidad de los usuarios de Internet. 
El mejor ejemplo de ello es la acción concertada contra algunos los pedófilos brasileña; Google transferido el gobierno brasileño alguna información de uno de sus redes sociales páginas, llamado Orkut. Los datos suministrados ayudado al Gobierno identificar pederastas varios. 
Los usuarios que se preocupa por la invasión de la intimidad personal podría alivio en mayo cuando Google, en asociación con la EEF electrónico ayuda jurídica organización con éxito demostrado su derecho contra el FBI: el tribunal confirmó que en ningún punto de la Constitución el FBI a Google para cualquier tipo de, en secreto pedido información. 
(Sin embargo, a la confirmación de la protección de la infancia una ley aprobada varios años antes, el Gobierno federal sí ha logrado acceder a 50.000 telaraña aborda y 1.000 filtra; sin embargo, no podría adquirir los usuarios individuales "búsqueda listas, ni una lista completa de las páginas web y palabras clave que abarcan un periodo de dos meses). 
Al parecer, hay opiniones controvertidas sobre Google. Es atacada por quienes temen de dar sus datos personales, porque consideran que su esfera íntima y vida privada se vería afectada por los servicios prestados por Google, han preferido representan la resistencia al grupo de empresas conservador multinacional. 
Mientras tanto, la cultura estadounidense geek y su oat salvajes, incluidos los entusiastas seguidores, activistas, los usuarios en varios países considerarlas como la próxima generación de grandes empresas, una corporación "fría", en contraste con su opinión sobre su rival, Microsoft, del creador de Windows y el conquistador del mundo, a pesar de que las dos compañías lucha por el mismo objetivo. 
Una de las razones de que puede ser que Google, Microsoft, no requiere identificación de sus usuarios y dinero para las solicitudes, además, la luz y continuamente código fuente y paquete programa, comparando al software oficial gigante en la práctica, parece más disponibles, juvenil y fría. 
O tal vez porque el hecho de que especialistas puede precisamente ver la relación problemática entre privilegio personal y de Internet, que está en consonancia con las más debatida expresión clave de los últimos años, web 2.0. 
Web 2.0 es una colaboración a intencionadamente abandonar rastros de nuestro ordenador actividades y explotar la comunicación disponibles los canales, aunque el grado de este acto puede ser diferentes, según el usuario, el punto principal es el mismo: mostrar al mundo. 
Una persona media jóvenes pueden abrir un perfil en varios públicos páginas como Facebook o Xanga, incluso pueden enlazarlos a otros servicios como Twitter o la música lista cineasta last.fm, entonces ellos pueden ser conectado a un sistema de seguimiento como FriendFeed o Blip.fm. Además, los usuarios pueden crear blogs que automáticamente actualizar la foto recientemente uploaded galerías almacenados en Flickr o Picasa. 
Podemos leer sobre historias varios: la niña, comprobar la abundancia de fotos uploaded en la mañana por amigos comunes, averiguar dónde novio no pasaron su noche anterior. O otra: un empleado podría perder su empleo sólo porque compartió su opinión sobre la gestión en su bitácora. Una consecuencia puede ser definitiva: la definición de la privacidad ha sido reevalúa. 
Si alguien que vive una vida en línea, son las que dan de sí mismos, esta es la idea detrás del comportamiento juventud de hoy. 
Si alguien tiene algo de mantener en secreto o si simplemente quiere evitar Google del monopolio, también es posible (por ejemplo con Scroogle, que también se aplica la búsqueda Google sistema pero bien no deja rastro detrás). 
El número de quienes deliberadamente no matricular a redes sociales son significativas. Este modo pueden evitar ser descubierto, Google las aplicaciones online de texto editor a imagen gestor y newsreader pueden ser sustituidas por versiones alternativas que no están en relación con servidor enorme parques y no intentar crear nuestra mejor perfil nunca. 
Público está deseando ver qué es todavía ocultas por Google. 
La empresa, con su valor de dólares 156 millones, vale más de IBM (140 000 millones de dólares), Intel (dólares 124 millones) o Coca-Cola (110 millones); además, los espacios de AdWords / AdSense amenazan la renta agencias de publicidad y servicios introducido a gran velocidad causa Microsoft y software varios otros desarrolladores un dolor grave. 
Sin embargo, los críticos también puede encontrar la counterpoints inquietante: la gestión totalmente rechazado los empleados « objeción, que pronto, porque la tasa de la empresa del jardín se habían duplicado. El comedor diario - el uso de la que se había permitido en cualquier momento y varios también fue considerada demasiado costoso por la gestión, pero todos estos no son nada comparado con el hecho de que Google ha doblegado ante el gobierno chino en 2006 y, en función de su acuerdo, la empresa ha filtrado todo busca resultados que ofenden buen sabor o los intereses del régimen chino. 
Una de las normas internas de la empresa dice que los nuevos servicios no anunciarse antes, sólo cuando están listos para ser utilizado., los próximos meses y años va a tener enorme influencia en el mundo: algunos predicen que el libro y revistas y archivo proyecto de Google pueda alcanzar pronto tales proporciones que deberá afrontar el Tribunal Supremo, al que hay que tener miedo de la Sanidad, que tiene la capacidad para construir una salud completar perfil de nosotros, incluidos sus resultados anteriores médica, médicos y problemas. 
Por último, el hecho de que Google es crear una base de datos genética puede proporcionar una base perfecto material para la sci-fi escritores de la generación siguiente. Cory Doctorow la novela popular, Scroogled se aplica Orwell estilo en la descripción de un futuro donde una persona puede ser gente incultura bien con datos de Google. 
