Oficina abierta, esta es la tercera edición de la anti-Microsoft "" paquete. 
Hoy la liberación de Openoffice.org 3,0, el código abierto productividad personales suite que pretende ganar más usuarios, de carácter interno a los usuarios, de los profesionales a la administración pública, como una alternativa libre para el Microsoft Office. 
Después de un esfuerzo duradera durante casi un año en nombre del promotores, con SUN Microsystem supervisar a sus espaldas, el Open nueva Oficina es decir al público general con novedades: la pantalla con satisfacción y a un renovado, menos usuario espartano interfaz, se añaden otros más importantes, como la compatibilidad nativos con el Apple Mac OS X sistema operativo y apoyo para el nuevo formato ODF (Open Documento Format) 1,2, la última ISO versión estándar. 
Atención fue también sobre interoperabilidad con la Oficina de 2007 suite, Open Oficina es capaz de abrir los documentos con Microsoft nuevos prórroga (.docx, .xlsx, .pptx). 
Interesantes son algunas funciones específicas para algunos módulos como la que prevé la reducción del volumen de PowerPoint presentaciones, útil por ejemplo para enviarlas a través del correo electrónico, o la posibilidad de importación de una PDF expediente en el grafismo módulo, mantener la apariencia original de la página. 
Siempre en la misma línea, es posible crear híbridas "PDF documentos", que unirá el grafismo estándar de la Adobe formato con los elementos de una hoja de cálculo o un procesador. 
Colaboración es una de las características en las aplicaciones que se ha mejorado considerablemente: en la hoja de aplicación a los usuarios varios puede operar simultáneamente, evitar conflictos sobre las modificaciones, en el procesador, cada uno de los usuarios es una referencia para mejorar el reconocimiento durante la revisión. 
Algunas empresas están trabajando también en porting algunos de la funcionalidad de OpenOffice teleoperadores la Web (en la nube), y durante las próximas semanas deberían entregar el producto definitivo. 
La versión italiana está disponible para descargar en la dirección http: / / it.openoffice.org / de descargar / 3.0.0 download300.html / y es a la versión inglesa, que ha estado disponibles en espejo emplazamientos desde el viernes. 
Además de Windows y Mac OS, como es habitual, la suite también está disponible para el Linux sistema operativo. 
A petición de la instalación cd puede ser remitido a su casa o de trabajo. 
Y si el artilugio de libre podría ser un motor de la difusión en casas, es en el establecimiento que Abierta Oficina está intentando la apuesta grande ya que puede contar ya con varios proyectos en la administración pública y escuelas. 
Y hay incluso instituciones que ofrecen servicios de formación, consultoría y asistencia, ideal pequeñas o medianas empresas, que podría crear más oportunidades de negocio. 
Oficina abierta se compone de cinco módulos principales: Writer, para onscreen mecanografiar correspondiente a la Palabra; Calc, la hoja de aplicación en sustitución de cabeza; Impress, por presentaciones en emulación de Powerpoint; Dbase, como en el caso de las más accesibles famoso es la aplicación las autorizaciones de trabajo sobre bases de; redactase, es el módulo gráfico. 
El objetivo para 2008 es alcanzar los 5 millones de descargas, y teniendo en cuenta que hasta hoy casi 3 millones de 600 mil, con la liberación de la nueva versión es probable que la previsible cifra podría ser incluso superado. 
