Adiós del cine viejo Paradiso, ciudades cancelar históricos teatros 
Teatros históricos cinematográficas en favor de Multiplex. 
"Una ciudad sin teatros cinematográficas es una ciudad gorda, que es una cara sin ojos". 
La imagen ofrecida por el director Giuseppe Tornatore dinero de fotografías lo que está ocurriendo no sólo en la gran italiana centros urbanos, sino también en las ciudades de provincias. 
Los dirigentes de los cines, con el nacimiento en las afueras de multi-hall grandes teatros y la pena pagar por consumo de la single-hall teatros en las áreas centrales de la ciudad, es uno de los acontecimientos que parece inevitable e indiscutibles y también tiene todas las características de un auténtico crimen cultural. 
Con frecuencia, es lugares históricos que están llenas de recuerdos que desaparezcan, "es como si un amigo está perdido, un conocido con el que hemos compartido la forma y recuerdos muchos", señala el director de Nueva el cine Paradise, la película que hace veinte años dio Tornatore la Oscar y el Gran Premio del jurado de Cannes, y que narrada el poema de una sala de provinciales y la nostalgia de un modo de vida el cine que, quizá, se ha perdido para siempre. 
Las cifras facilitadas por Anec, la cinema-operators principal asociación, hablar claramente: en los últimos cinco años 316 estilo tradicional cines han cerrado sus puertas, y los a pagar el precio fueron sobre todos los teatros en las ciudades principales: 10 menos en Florencia, 9 en Milán, Nápoles, Bolonia, y Roma, 6 menos en Turín, 5 en Palermo. 
Entre las regiones más afectadas por los cierres, Emilia-Romaña toma la iniciativa con 82 single-hall cines perdido, seguida de Toscana (44), y por Lombardía (41). 
Y para demostrar que la llegada de la multiplex es la más responsables de su desaparición, estos son exactamente las tres regiones italianas con el mayor número de multiplex nuevos cines registradas: 195 más pantallas en Lombardía en los últimos cinco años, 81 en ambos Toscana y Emilia-Romaña. 
Formar parte, El negocio italiano ha desarrollado de forma irracional "observa Paolo Protti, Anec del presidente," es útil que nuevas estructuras construidas pero es también fundamental que la supervivencia de los existentes está garantizada, porque una vez un teatro en una ciudad cierra, no todos sus clientes pueden sentirse inclinados a trasladar al retirarse ante. 
Por no mencionar la perdida de la asignación de fondos en favor de los operadores: la cuenta anterior por el Estado es de unos 10 millones de euros. 
Es lamentable, de la ética y desde el punto de vista moral, que el Gobierno no respetar las leyes existentes. 
Para apoyar el sector entre 16 y 18 millones de euros un año son necesarias ". 
Un ejemplo interesante es que de Bolonia, la ciudad ante el italiano que, preocupada por los cierres, ha decidido dar cobertura al firmar un protocolo entre el ayuntamiento y Anec, la primera de su clase en Italia, para proteger y promover single-hall cines tanto en el centro histórico, así como en las afueras. 
Entre los previsto disposiciones existen desgravaciones fiscales medidas en favor de los operadores y ventajas para el público desde el punto de vista de la movilidad: el espectador puede entrar en la zona traffic-limited y han tarifas especiales para el estacionamiento y en algunos los aparcamientos. 
Formar parte, es una iniciativa que me gusta "observa Giuseppe Tornatore" y espera que otras ciudades seguir el ejemplo de Bolonia en acción otras medidas. 
Es seguro, que a cambio al exceso de poder del multiplex, teatros tradicionales han también para mejorar la imagen y sonido de calidad, porque el público hoy en día es más exigente. 
La defensa de los cines tradicional es un tema que para mí siempre ha sido importante: el cierre de la Bagheria Supercinema, el lugar de mi infancia y adolescencia, fue la chispa que me convenció para crear "Nueva el cine Paradiso", en el que ya he estado pensando en los últimos 10 años. 
He estado viviendo en Roma por 25 años, y cuando me pasan delante de la Rialto o la Quirinal en Nacional Street tanto cerrado por ahora, donde he vivido muchos compartían emociones, para no ver los carteles alquitranados por el polvo ". 
