El programa nuclear del Pakistán genera una gran intranquilidad en los EE.UU. 
Islamabad produce armas atómicas en "un ritmo más rápido que cualquier otro país". 
El filtrations de WikiLeaks confirmar los lazos entre el pueblo y el talibán de Pakistán. 
El contenido de la correspondencia entre la embajada de Estados Unidos en Pakistán y el Departamento de Estado de los Estados Unidos filtrados por WikiLeaks el portal confirma la gran inquietud que provoca el programa nuclear del Pakistán en Washington. 
Además los esclarecedor y sustancial que se ofrecen detalles sobre el contenido de las conversaciones y los pensamientos del mérito de representantes diplomáticos en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de seguridad nuclear, en lugar de aumentar, "reduce", y que la inestable país asiático produce armas nucleares con "un ritmo más rápido que cualquier otro país". 
La peculiaridad del programa nuclear del Pakistán, que las armas no están reunidos pero siguen almacenadas por componentes para hacer difícil su destrucción en caso de attack-- constituye una de las principales causas de preocupación en Washington. 
Por lo tanto es enumerados por el embajador de Pakistán, Anne W. Patterson, en un informe anterior a la visita del ex asesor de Seguridad Nacional, James Jones: "la proximidad de algunas centrales nucleares en el territorio bajo ataque talibán, según la dispersión de los materiales nucleares y la vulnerabilidad de transporte de materiales nucleares". 
El gran número de personas implicadas en los arsenales nucleares y de misiles de los programas se tenga en cuenta, no sólo por los Estados Unidos, sino también por Rusia, como la razón para mantener la guardia. 
"Pakistán ha tenido que contratar personal con las creencias religiosas estrictas para proteger a las plantas de energía nuclear, habida cuenta del bajo nivel cultural y educativa, las organizaciones extremistas tienen mayores posibilidades de contratar a personas que trabajan en los programas nucleares o de misiles", dijo el experto Yuri Carole, desde el Ministerio ruso de Asuntos Exteriores, en una reunión con su homóloga estadounidense. 
La última información sobre los documentos filtrados por el portal, Julian Assange, es la disminución de la cooperación entre los Estados Unidos y Pakistán en temas de proliferación nuclear y la alta tasa de Pakistán de producción de armas nucleares. 
Una oficina de la Embajada en mayo, que describe como "frustrante" la comunicación con el Pakistán, afirma que: "La transparencia es a menudo inexistente; los ofrecimientos de ayuda siguen sin respuesta o se negó". 
En otro mensaje, Peter lavoy, funcionario de la inteligencia nacional para el sur de Asia, afirma que "a pesar de la catástrofe económica, el Pakistán produce armas nucleares a un ritmo más rápido que cualquier otro país del mundo". 
La Embajadora Patterson también pide a Washington, durante una visita del jefe del Ejército, el general Ashfaq Kayani, para dar instrucciones claras a la persona encargada de que "el Ejército de Pakistán debe poner fin al apoyo tácito a los grupos terroristas". 
