Romano va hacia su primer título 
Rubén Omar Romano cuenta con tres derrotas en la final, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna Monterrey y en la última, además de dos estilos diferentes caracterizado por sus técnicos ", que se encuentran entre sí con una diferencia marcada por los resultados. 
Rubén Omar Romano cuenta con tres derrotas en la final, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora no había alcanzado el objetivo, y esta es la razón por la que esta oportunidad es muy especial para él. 
El argentino ha acabado con el consuelo de la medalla de segundo clasificado, y se quedaron un paso por detrás de los ganadores y particularmente con el mismo equipo que ha jugado las finales consecutivas. 
Santos llegó a su primera última como entrenador en el primer partido de 2002, cuando tomó las riendas de Morelia con la que se le cayó por 4-2 ante Toluca; más tarde, en el acto de clausura 2003 también llegaron al duelo decisivo y perdió por 3-1 también, y de hecho antes de Rayados. 
Ya con Santos Laguna, en el bicentenario partido de 2010, una vez más ante los diablos, Rubén sufre de nuevo el contrario, puesto que su equipo acabó igual de lugares 2-2 ante la salchicha después de los 210 minutos de juego, pero en el giro de sanciones colocado en ventaja de 3-1 con dos oportunidades para sellar el título, pero finalmente tres jugadores desde los 11 pasos falló y sufrió el 4-3 cambio. 
Rubén perdido ya dos diablos rojos con las finales y con Monterrey, su rival en turno, por tanto, no quiero sufrir la misma suerte, quiere celebrar un título por primera vez, y afirma que lo más importante para él es la institución. 
Quiero ser un defensor, no quiero romper cualquier dato, esto es por un club, por una pasión y en consecuencia el título será para mí, pero la última cosa es más importante, comentó el timonel al ser cuestionado sobre las cifras que ha de jugar contra las finales. 
Muy eficaces que los anteriores, desde final que, asegura, ha aprendido mucho, "la única lección es que hasta el árbitro señala el fin no podemos celebrar, nos preparamos así como los actores porque la anterior ocasión, con dos sanciones que estaban a punto de abandonar y creo que es una lección que aprender, no podemos celebrar hasta que termine el juego". 
A sabiendas de que esta serie podría definirse de pena, algo en lo que no, porque confía en sus jugadores: " uno nunca espera para ir a sanciones, sino para terminar en tiempo regular; a veces no tienen ninguna alternativa y es necesario estar preparados; en el partido anterior estábamos preparados, lamentablemente el destino en nuestras manos; a veces, por la preocupación o los nervios por tener el título en un mano, pero nosotros no alcanzar este objetivo, y esto nos queda algo por esta última que esperamos ganar. " 
Roman debe dejar de ser el técnico y segundo clasificado por primera vez saboreando la gloria que los títulos dan. 
