La NASA va a anunciar el descubrimiento de la vida extraterrestres 
La agencia espacial estadounidense llama la prensa mañana para presentar un descubrimiento que causen impacto en la búsqueda de los seres vivos en el espacio. 
La Administración Nacional de Aeronáutica y del Espacio (NASA) de los Estados Unidos presentará mañana, jueves, un descubrimiento Astrobiología, que podría resultar la teoría de que exista vida extraterrestres. 
El descubrimiento se presentarán en una conferencia de prensa de mañana jueves a 13: 00 horas en la sede de la NASA en Washington por expertos en astrobiología; una ciencia descrito como la que analiza el origen, evolución, la distribución y el futuro de la vida en el Universo. 
Cuando la prensa, la NASA aseguró que hará "un descubrimiento que causen impacto en la búsqueda de la vida extraterrestres", lo que provocó especulaciones por expertos en otros países. 
El descubrimiento podría demostrar la teoría de que existan criaturas que nos parecen vivir en espacios hostil que se considera como inhabitables, y se puso sobre la mesa la posibilidad de que lleguen a ser seres inteligentes como seres humanos para que mejoren sus condiciones de vida. 
Aparentemente se trata de un microbio se centró en que se encuentra en el fondo del lago mono del parque nacional Yosemite, California, donde vive en un entorno en el que se considera muy tóxico para cualquier forma de vida, desde el lago es rica en arsénico. 
De alguna manera, la criatura utiliza el arsénico como medio de supervivencia y por esta capacidad aumenta la posibilidad de que podría existir vida similares en otros planetas que no tienen nuestro entorno benévolo. 
Según astrobiologists, si estos organismos uso arsénico en su metabolismo, se demostró que "de hecho hay otra forma de vida, un segundo tipo de vida, diferente de la que conocemos". 
La Agencia Espacial presentará el pleno alcance de los descubrimientos en la conferencia de prensa de mañana jueves. 
Pamela Conrad, que estudia la posibilidad de vida en Marte; y el biólogo Steven Benner, uno de los científicos que estudian Titán (la mayor luna de Saturno), bajo la perspectiva de que su química es similar a la de la tierra, tanto a asistir a la Conferencia. 
