Las "personas enfadadas" desafían a las autoridades en Nueva York
Los cientos de protestadores estaban rodeando delante de cuadrado de Zuccotti para acampar.
Una parte de los protestadores escuchaban el orden de evicción y cambiaban a un parque cercano.
Los miembros del movimiento Ocupan Calle de Muro desafiada el martes las autoridades de Nueva York al probar entrar otra vez, bajo la protección de un mandamiento judicial, en el Cuadrado de Manhattan donde se evacuaban al amanecer al probar ocupar otro parque de la Manzana Grande.
Los cientos de protestadores agolpados alrededor del Zuccotti cuadran, donde querían entrar gracias a un mandamiento judicial que permite "las personas enfadadas" para acampar en el lugar, mientras otra parte del movimiento respondía a la evicción ocupando un parque al norte la ciudad donde allí haber sido hechas otras detenciones.
"Nuestra idea es eso si el tribunal no nos permite volver a campo en el cuadrado, acamparemos en algún otro sitio y continuamos la batalla legal para volver a Zuccotti, y mediante ocupaciones pacíficas y demostraciones", decíamos uno de los portavoces del movimiento "Ocupan Wall Street", Mark Bray.
Rebuzno explicado que la respuesta de las "personas enfadadas" a la evacuación del campo emitido personalmente por el alcalde de Nueva York, Michael Bloomberg, venía a cortejar, donde el Juez Lucy Billings emitía un orden que prohibía la evacuación forzada del lugar y que admitía que los manifestantes para permanecer acampaban.
Además, las "personas enfadadas" iban a la ocupación de un parque nuevo localizado en la confluencia de la Calle de Canal céntrica y la Sexta Parte Avenida, cerca de la entrada al Túnel de Holanda, que conecta Nueva York y Nueva Jersey, poseída por la parroquia de Iglesia de Trinidad.
Por lo menos durante una hora que podían ocupar el lugar, pero que entonces la policía viniera y ponerse a detener algunos de los protestadores, aunque Rebuzno no podría confirmar el número preciso, mientras dice a Efe que veía a varios periodistas que eran esposados también.
La organización asegura que hay varios cientos de gente alojada en ese punto, donde una delegación de líderes religiosos ha ido ya para enseñar su apoyo a los miembros del movimiento que intenta mediar con la policía.
Mientras tanto, cuadrado de Zuccotti, que es un lugar poseído de forma particular, restos cerrados esperando un oído de tribunal hecho programar para este martes en el cual examinar la legalidad de la evacuación de esta mañana.
Algunos de los protestadores movidos allí se estaban transmitiendo y distribuyendo en aquella época copias de ese mandamiento judicial e incluso ellos daban" a quien afirmaba "a que los oficiales vigilaran el lugar, que conducía a "algunas pequeñas confrontaciones", decía Rebuzno, "a estas copias" que algunos oficiales golpeados los manifestantes.
El mandamiento judicial prohíbe las autoridades para evacuar los miembros de Ocupan Wall Street e imponer "leyes que se promulgaban después del principio de la ocupación o para prohibir manifestantes recobran acceso del parque con tiendas y otra propiedad utilizada antes."
El alcalde Bloomberg les decía a reporteros que, a causa de ese mandamiento judicial, la ciudad había suspendido la reapertura del espacio público y los protestadores eran informados, sin embargo, de que las leyes locales no les permiten reinstalar con tiendas de camping y sacos de dormir.
El councilman personalmente defendía la evacuación del cuadrado de Zuccotti realizado al amanecer, una operación en la cual aproximadamente 200 detenciones se hacían y esto se decidía así porque los protestadores estaban "violando la ley."
Bloomberg decía que daba "un lugar" al orden para evacuar el cuadrado porque se estaba convirtiendo "donde no venía a proclamar la gente, pero romper la ley y, en algunos casos, hacerles daño a otros" como "Algunos negocios habían recibido amenazas'y los vecinos temían por la calidad de vida."
"La evacuación de esta mañana estaba repugnando y se ve que profundo dentro de Bloomberg está más "interesado en preservar los intereses financieros de trabajadores americanos", añadía el portavoz del movimiento, que acusaba al alcalde de "falta de respeto por la libertad de expresión"."
El responsable de "Ocupar Wall Street" también indicado que piensan organizar "grandes acciones" para jueves en la colaboración con organizaciones de la comunidad y uniones, para conmemorar los últimos dos meses de protestas, que empezaban el 17 de septiembre.
