No SOY el asfalto evitaría baches
Rafael Herrera, un investigador en la Facultad de Química de UNAM, desarrolla asfalto modificado de polímero para producir una mezcla con la mejor actuación, sin tener en cuenta las condiciones de medio ambiente y temperatura
Si se asistiera a las señales enviadas por el pavimento, sería necesario retirarse sobre 200 mil baches todas las temporadas lluviosas en el Área Metropolitana de Valle de México, decía Rafael Herrera Najera, un investigador en la Facultad de Química (CF) del NO-SOY, quién decía que si el proceso de construcción y mantenimiento de una acera de asfalto es adecuado, los baches se podrían reducir o incluso completamente eliminarse.
En su conferencia visión tecnológica de A del bache, emitido bajo el Año Internacional de Química, anunciada de que el laboratorio para el cual es responsable está desarrollando un polímero modificado asfalto para producir una mezcla con características similares al asfalto, pero con una resistencia mecánica mejor, tanto en temperaturas altas y bajas.
Herrera Nájera decía que este tipo de asfalto modificado se podría utilizar en lugares donde el tiempo está sumamente caliente, como algunas ciudades en el norte, para mejorar su actuación y, por lo tanto, la formación de baches.
Explicaba eso el asfalto, el más pesado el aceite en parte es un conjunto de moléculas de hidrocarburo, algunos de peso molecular alto, llamado asfaltenos, y otro de peso molecular bajo, llamado maltenes, que juntamente dan su comportamiento característico viscoelastic al pavimento.
El comportamiento viscoelastic del asfalto consiste en el hecho de que en temperaturas altas cerca de 180 grados, se comporta como un líquido a 120 ° C, su viscosidad es muy alta y a 50 grados el celsio tiene un estado casi sólido, mientras que en temperaturas muy bajas el asfalto se vuelve frágil, decía.
Esto significa que la resistencia del asfalto de calle no es uniforme, pero se modifica durante el día según las condiciones de medio ambiente y temperatura, decía el especialista en ingeniería química.
El investigador de CF observaba que las calles de Ciudad de México son cubiertas en su mayoría por pavimento flexible, que se compone de seis capas de material, fuera del cual el último tres implican el asfalto.
Entre las capas más superficiales está el asfalto, compuesto de piedras pequeñas mojadas en el asfalto y entonces comprimidas.
Cada una de las piedras que componen este cubrimiento, decía, se moja con asfalto.
Al conducir vehículos y esfuerzo de generación, permite a las fuerzas extender muy bien en la acera.
Si se modificaba asfalto que extendería incluso mejor, decía el ingeniero químico.
En el cubrimiento de asfalto, añadía, es puesto una capa final llamada cubrimiento rodante, que se hace de un material de piedra fino, significando arena también mojada en el asfalto.
Desde que ésta es la capa que estará en contacto con las ruedas del vehículo, debe tener una resistencia mecánica mejor que el cubrimiento de asfalto y proporcionar rozamiento de carretera.
Como siendo la parte de la acera que recibirá y difundirá los esfuerzos, el balanceo que cubre también requiere espesor correcto y el material se hace de debe ser tomar en consideración.
El tiempo, especialmente la humedad y las variaciones de temperatura son también un factor muy importante para considerar, especialmente humedecerse, decía, porque sumamente afecta a la actuación del asfalto.
Cuando el suelo es húmedo, el agua se difumina dentro del cubrimiento y es difícil salir, causando esto un ablandamiento de todas las capas de la acera y, por lo tanto, la formación de baches.
En la formación de un bache, decía, el primero desgastarse es cubriendo el balanceo y solamente después de que eso se afecte el asfalto, sino el daño no sucede instantáneamente, es un proceso al cual se debería asistir en el primero firma con programas de mantenimiento apropiados.
También un miembro del Sistema Nacional de Investigadores a los cuales se les explica que la carga de vehículo es otro factor importante en la formación de baches y, por lo tanto, el espesor de cada capa de la acera debería hacer siempre en relación con el vehículo cargar y asegurar este cumplimiento, para prevenir la formación frecuente de baches.
Rafael Herrera decía que hay todavía mucho para investigar y trabajar para hacer en el asfalto, por ejemplo, emulsiones de asfalto, que en otros países están ya en el mercado e incluso los baches de reparación de ayuda con la facilidad y sin utilizar temperaturas altas.
