MSS anuncia un protocolo para gen de obesidad de búsqueda
La seguridad social dirige a una investigación encontrar el gen para la obesidad en niños y gente joven; es respaldado por especialistas del IPN
El Instituto de Seguridad Social mejicano (MSSI) ha anunciado que eso conduce una investigación para descubrir el gen para la obesidad en niños y gente joven, llamada el protocolo de 'Genética de obesidad en infancia y adolescencia', que proporcionará contando con marcadores asociados con el sobrepeso.
En una declaración, la cabeza de la Unidad de Investigación Médica en la Bioquímica del Hospital de Especialidades, Centro Médico Nacional, Miguel Cruz Lopez, de XXI Siglos explicaba que se integraba un equipo multidisciplinario de médicos, enfermeros, nutriólogos y asistentes sociales.
El equipo es respaldado por especialistas y universitarios del Instituto Nacional de Sanidad Pública (NIPH) y el Centro para la Investigación y Avanzado Estudia (Cinvestav) a National Polytechnic Institute (NPI).
La investigación invita la población titulada o no, participar yendo a las unidades de deporte de participante del MSSI en el Valle de México, donde allí será llevado fuera de las pruebas a niños, todos los sábados desde 8:00 en punto.
Recalcaba que el protocolo empezaba en la unidad de deportes de Cuauhtémoc (Estado de México Occidental) y desde el 8 de octubre, la actividad tiene lugar en la unidad de Deporte de Netzahualcoyotl (Estado Oriental de México).
Una vez pasado el objetivo de traerles 500 a 600 niños, el estudio continuará en la Unidad de Deporte de Independencia (Al sur el Ciudad de México) y finalmente en la Unidad de Deportes de Morelos (Al norte el Ciudad de México).
Explicaba que el propósito de esta investigación tiene que entender las componentes y la importancia de genética en relación con el desarrollo de obesidad e identificar en niños y mejicanos jóvenes los factores de riesgo para prevenir el aspecto de enfermedades degenerativas crónicas.
El 14 de noviembre, allí será celebrado la Diabetes Mundial Día, y el objetivo es recoger tres mil niños y gente joven entre 6 y 14 años, con la supervisión de consentimiento y de los padres para la implementación de cuestionarios específicos en comida.
Se preguntarán también sobre actividad material e historia hereditaria de familia de enfermedad, para evitar factores de riesgo que dan lugar a enfermedades como fracaso de diabetes o riñón.
Explicaba que el sábado a todos los participantes se aplicarán mediciones antropométricas (peso, altura, y circunferencia de cintura), mediciones de presión sanguínea, y determinación de glucosa, triglicéridos, colesterol e insulina y genética (pretendiendo identificar genes que se asocian a obesidad de infancia).
Cruz Lopez decía que esta investigación refleja el asunto de profesionales de salud para el peso alarmante ganan en niños.
Las Encuestas de Salud hacían entre 1999 y 2006 informaban de que en solamente seis años que había un aumento en el caso de los chicos, 77 por ciento eran obesos, y 47 por ciento en el caso de las chicas; en términos de sobrepeso allí era observado también "un aumento drástico, "decía el especialista del MSSI.
Decía que la justificación para registrar los marcadores está basada en eso la población del país difiere de otro en su historia genética.
Informaba de que por término medio, el mejicano tiene un 65 por ciento de patrimonio indio americano, 30 por ciento del europeo y cinco por ciento del africano y esta condición se refleja en los genes que se asocian con la diabetes y sobrepeso.
Explicaba que generalmente, las genéticas de obesidad dan lugar a la incapacidad de quemar la energía excesiva que consumimos (calorías) y que se almacena como gordo.
El investigador explicaba que el beneficio directo para los participantes es una evaluación completa de los niños, que puede detectar si tienen algún grado de sobrepeso u obesidad.
Incluso, decía, la presencia de pliegues oscuros de color (acantos) sobre el cuello y antebrazo indica la verosimilitud de sufrimiento de desórdenes metabólicos e incluso la prediabetes.
La información se domina con la confidencialidad, los doctores se lo proporcionan por escrito a los padres, a los cuales les explican cada uno de las mediciones y los cambios en el estilo de vida que se tienen que emprender para prevenir enfermedad.
Cruz Lopez explicaba que hay tres componentes esenciales que causan sobrepeso, obesidad y otras enfermedades crónicas: estilo de vida sedentario, que es la falta de actividad diariamente material, quedándose la mayor parte de los del día y mirando TV y utilizando medio de transporte en lugar de andar distancias cortas.
También ello es debido a la admisión caloric alta, sentido, y el consumo aumentado de bebidas azucaradas, carbohidrato (tamales, pan, pizza, hamburguesa, etc.) con grasa alta y proteína y genética analizada en este protocolo.
