Analizan la posibilidad de un "voto por voto" contar en Michoacán
Según los datos transmitidos por el PERP la diferencia entre el primero y segundo lugar en los comicios gubernatorial es de solamente 27 por ciento, incluso sin contar los votos que corresponden a 879 del total de 6,074 minutos.
La posibilidad del recuento "voto por voto" es una realidad en cuanto al proceso electoral de este año en Michoacán, dónde según los datos obtenidos del Programa de Resultados Electoral Preliminar (PERP) está la diferencia entre el primero y el segundo lugar de los comicios del gobernador de solamente 27 por ciento, incluso sin contar los votos que corresponden a 879 del total 6.074 minutos.
En esta mirada, el Presidente del Consejo General de Instituto de Michoacán Electoral (MEI), Maria de los Angeles Llanderal Zaragoza, recordaba que hace unos cuantos días, el último 9 de noviembre, el electorado aprobaba un conjunto de pautas para armonizar la reglamentación local con la reforma federal electoral.
Como se retirará, Michoacán no autorizaba la Constitución o el Código Electoral del Estado o el Acto de Justicia Electoral, desde que el Congreso del estado aprobaba las reformas dentro de poco antes del plazo legal para que entraran en vigor en este proceso electoral y el Gobernador Leonel Godoy Rangel omitía su publicación dentro de los periodos especificados en la Ley en el Boletín Oficial de Estado, sosteniendo que tenía algunas objeciones.
El mismo 9 de noviembre, el tribunal supremo de Justicia (SCJ) resolvía la controversia constitucional promovida por la legislatura local y descrita como "nulo e ilegal" el voto del representante de estado por las reformas constitucionales, desde que no tiene ningún derecho a "sancionar o votarlos."
Entrevistado sobre la posibilidad del "voto por voto", Maria de los Angeles Llanderal afirmaba que con la adopción de las pautas apropiadas por el Consejo General del MEI será posible realizar cálculos parciales y totales del voto por el electorado local.
De esta forma, la frecuencia parcial cuenta de uno o más cajas electorales pueden ocurrir en las suposiciones que: los resultados de los discos no coinciden; no hay ningún disco del cálculo sobre el disco de la caja o no se incluyen en el poder del presidente; o cuándo hay errores obvios o alteraciones de los minutos.
Además, el cálculo total del voto recibido en todas las cajas de los comicios puede tener lugar cuando hay una indicación de que la diferencia entre el ganador de candidato supuesto de los comicios en cuestión y aquél que ha obtenido el segundo lugar en la votación, es igual a o menos que un punto porcentual, mientras al principio de la sesión haya una petición del representante de la fiesta y/o coalición que designaba el segundo de los candidatos mencionados.
El cálculo de voto total se hará también si al extremo del cálculo corriente es establecido que la diferencia entre el ganador y el candidato situado en segunda posición es igual a o menos que un punto porcentual, mientras haya una petición del representante del partido político cuyo candidato venía en la segunda posición, envuelve en el cual allí será excluido las cajas electorales que se han considerado durante la frecuencia parcial cuentan.
Allí debería ser fijado que en esta situación es los comicios de Morelia, donde según PERP la diferencia entre el primero y el segundo lugar está de sólo 0,16 por ciento, incluso sin contar los votos de 129 de los 923 minutos totales.
