La adversidad climática reducía la economía
Durante el primer año de gestión de Mario Lopez Valdez, en Sinaloa aumentaba el desempleo y la informalidad, la inversión extranjera declinada y la economía era reducido.
2011 es un año que será recordado en la historia de la economía de Sinaloa, que es relacionado con el primer año de gobierno de Mario Lopez Valdez también llamado el año de cambio, qué grandes expectativas generadas en cuanto al desarrollo de la economía, sino dada la adversidad climática del principio del año, no había crecimiento, sin embargo allí era registrado una caída en general indicadores de desarrollo económico.
Las temperaturas de febrero bajas, no solamente causaban pérdidas de millones para el sector agrícola, sino que limitaban las posibilidades de la economía de estado para crecer, causando una contracción de la actividad económica en general de 3,6 por ciento en el primer tiempo del año, principalmente sostenido por la caída histórica de 31,16 por ciento en la agricultura, que afectaba a la dinámica de otros sectores económicos.
Según el informe en cuanto a las áreas afectadas por la escarcha, publicado por el Consejo Mejicano para Desarrollo Rural Sostenible allí eran dañados 835,582 hectáreas, fuera de las cuales 78,03 por ciento sufrían daño total y los restantes de 21,07 por ciento tenían daño parcial. Las cosechas dañadas principales eran las verduras, callo y garbanzo.
La caída en la actividad económica ha generado, hasta noviembre, un aumento constante del desempleo en el estado, según el Instituto Nacional de Estadística y Geografía, el ritmo de estado de desempleo durante los primeros tres cuartos del año percibía un crecimiento acelerado, de enero a marzo que 55,053 habitants de Sinaloa estaban parados, con un ritmo de 4,53 por ciento del económicamente población activa para el segundo cuarto, el ritmo se convertía en 5,28 por ciento, y entre julio y septiembre el promedio continuaba aumentando a 6,19 por ciento, un ritmo que en términos de la cantidad de gente representa más de 74,000 de parado habitants de Sinaloa, un aumento comparado con el primer tiempo de 18,969 individuos.
Liquidez más baja
El desempleo en Sinaloa durante el año es multi-factorial, para el economista Gerardo Lopez Cervantes, director en la Facultad de Ciencias de Economía y Sociales del UAS, el crecimiento de desempleo se puede explicar indirectamente, dependiendo de las acciones que la política pública se han tomado.
"Lo que estamos viendo ahora es un aumento del desempleo que tiene que hacer con varios factores, incluyendo la pérdida de liquidez en el mercado con el fin de una coacción de recurso impuesta por la legislación que pasaba en el Congreso para combatir blanqueo de dinero desde entonces para la gente que ilegalmente poseen dólares no es fácil trabajo con, invertir y utilizar ellos en algo" decía.
Inmigración Detenida
Lopez Cervantes decía que en el aumento de desempleo hay también un factor demográfico.
"La cantidad de gente quien sale del estado en busca de un trabajo en el extranjero, en los Estados Unidos han sido limitados, primero de todo debido a las dificultades para entrar, y segundo de todo "porque una vez que entran ya tienen demasiadas dificultades en encontrar un trabajo, que se está quedando grupo de gente y exigen trabajos aquí, en el estado, causando el índice de desempleo para levantarse, decía.
Informalidad
El análisis de mercado laboral de Sinaloa empeora cuándo considerando el nivel alto de informalidad que prevalece entre las condiciones de trabajo, según INEGI, trabaja 60,38 por ciento de la población activa en el estado sin ser citado como trabajadores a ninguna institución de seguridad social.
Además del desempleo e informalidad, otra notificación laboral de estado es representada por sueldos bajos; la entidad tiene los sueldos más bajos en el país, según los discos del Instituto de Seguridad Social Mejicano y el Ministerio de Trabajo y Bienestar Social.
Los ingresos de media mensual de trabajadores de Sinaloa eran, hasta septiembre, 5,352 pesos, bien por debajo del promedio nacional, eso es de 7,375 pesos.
Contracción de FDI
Además de la caída en la actividad económica e índice de desempleo alto, en 2011 allí era registrado la mayor caída en extranjero inversión directa a lo largo de los 10 años pasados, según el Ministerio de Contabilidad de enero a junio que el FDI de estado sumaba 630,697 dólares, que transmite una caída de 87,74 por ciento comparados a los dólares de 5.143.312 durante el mismo periodo del último año.
Para su parte, el Ministerio de Desarrollo Económico del Gobierno de Estado consideraba una inversión total de 17.280.000 pesos durante el año, que ocurría principalmente en compañías de sector terciario.
Deuda
Contra el telón de económico vuelta hacia abajo, el gobierno de estado necesitaba en julio durante el congreso de estado, la aprobación de un crédito de 3000 millones de pesos, que sería ya que la inversión en la infraestructura se proyecta en 18 municipios, para reactivar la economía, la aprobación del congreso local fuera para un total de 2,600 millones de pesos, y hasta noviembre ningún beneficio de la deuda se observara en ningún sector de la economía de estado.
Reacciones
Para representantes de negocio, el primer año de gobierno de Mario Lopez Valdes demuestra una falta de capacidad del gobierno.
Miguel Loredo Lopez, presidente de la Cámara Nacional de Industria de Transformación, decía que durante 2011 había una falta de armonización de las voluntades de diversos sectores, incluyendo el gobierno de estado mismo.
"La actuación de la economía en Sinaloa al año ha sido realmente pobre, uno tiene que trabajar mucho para recobrar el suelo perdido este año, en 2012 debemos redoblar nuestros esfuerzos, fracasábamos en alinear los esfuerzos de todo y por encima de todo el movimiento bueno y sincronizado del equipo de gobierno nuevo, esperamos que el próximo año será mucho mejor" decía.
Lentitud económica
Lopez Loredo decía que los acontecimientos como primera escarcha que este año detenía la economía de estado y su actuación y crecimiento se limitaba.
"El flujo económico bajo es el producto de varios acontecimientos, incluyendo escarcha, uno de los efectos principales ha sido generando una economía lenta que no se vuelve lo bastante rápida para un dinamismo económico que permite tener un nivel de flujo aceptable de los procesos, productos y servicios y por lo tanto, al extremo del año lo estamos cerrando por debajo de nuestras expectativas", decía.
Redefiniendo la vocación
Teodoro Salazar Uriarte, presidente de los Empresarios" Confederación de la República Mejicana en Sinaloa, decía que se exige que el estado procesara las actividades productivas más dinámicas.
"En conjunto, encontrábamos que ha habido trabajando en, creemos que es necesario desarrollar un programa de plazo largo que redefine la vocación y el curso económico del estado, es importante detonar todo el recurso potencial material y humano que Sinaloa tiene", decía.
Trabajo para Hacer
El Presidente de Coparmex enfatizaba la importancia de establecer una visión futura para guiar mejor los esfuerzos del gobierno.
En conjunto diría que el Gobierno se ha estado esforzando por tener éxito en diversos campos, en términos de desarrollo económico que hay un poco de progreso pero es importante desarrollar un programa a largo plazo", decía.
Se fijaba en que la administración actual ha enseñado progreso en su propia manera de conducir la política pública.
"Hay elementos que permiten diciendo que el gobierno se esté volviendo más incluido, y qué puedo decir es que hay trabajo hecho y creo que el gobierno es consciente de que hay trabajo para hacer", decía.
