El tribunal valida "transición de televisión digital" en México en 2015
La reposición de cosa análoga con digital es uno de los cambios más importantes que ha alcanzado el mundo en los últimos años
El tribunal supremo de Justicia (SCJ) rechazaba las controversias constitucionales traídas por el Senado y Cámara de Representantes en contra del decreto presidencial que avanza la "transición de televisión digital" denominada de 2021 a 2015, desde que los ocho votos necesitados para invalidarlo no se obtenían.
Una minoría de cuatro ministros, incluyendo el Presidente del Tribunal, Juan Silva Meza, consideraban que el Presidente Felipe Calderon no superaba su autoridad saliendo un despiece de decreto las acciones para llevar en orden para lograr la transición a la televisión terrestre digital.
Con este resultado, la controversia constitucional promovida por el Senado, era rechazado para no encontrar la mayoría cualificada de ocho votos para que el Tribunal pronunciara en la constitucionalidad o inconstitucionalidad del decreto, y esto queda en gran número.
El proyecto de frase preparado por el Ministro Olga Sánchez Cordero, proponía declarar anticonstitucional el decreto, porque la regulación de materiales de radio y televisión es un poder reservado por la ley a la Comisión de Telecomunicaciones Federal (Cofetel), en la violación de los principios de reserva de subordinación y ley jerárquica.
Solamente Zaldivar, Jorge Mario Pardo, Margarita Luna y Sánchez Cordero votaban a favor del proyecto.
Con este argumento, tanto el Senado como la Cámara de los Diputados promovían dos controversias constitucionales para contradecir el decreto, y para respaldar las reclamaciones, el ministro Sánchez Cordero suspendía la aplicación del decreto y todas las acciones estipuladas allí en cuanto a la transición digital.
En que "los ministros" se encontraran había también decidido para rechazar la reclamación presentada junto a la Cámara de los Diputados, sin entrar en la discusión del proyecto, también encargada del ministro Sánchez Cordero.
En su discurso, el ministro decía que no estaba de acuerdo con los argumentos del proyecto en el sentido de que el ejecutivo federal no puede estructurar a través de reglas generales las medidas para que la administración pública se preparara.
"Ni considero que si se haga afectaría a la autonomía del cuerpo legal"," y retiraba eso la planificación de políticas públicas en áreas estratégicas como el sector de telecomunicaciones le corresponden al ejecutivo federal, que tiene un mandato constitucional, la orientación del Estado.
La reposición de cosa análoga a digital es uno de los cambios más importantes que han afectado al mundo en los últimos años, y da lugar a una utilización mejor del espectro eléctrico de radio, la mejor calidad de señal y más canales.
Retrasar el cambio, decía, significaría retrasando los beneficios de digitalización, que implica una decisión de interés pública, que tiene no solamente una dimensión técnica, "como cubre la seguridad económica, social, política y nacional sale."
Estas cuestiones, decía, "exigen que la operación del sistema entero establecía bajo el principio del stewardship económico de estado, compone un grupo de poderes que la Constitución conduce al poder ejecutivo de estado."
Recordaba que una gran cantidad de países alrededor del mundo han completado ahora la transición digital, y lo han hecho a través del ejecutivo, a pesar de de haber especializado se altamente cuerpos técnicos.
Allí no puede ser concluido que el gobierno, promulgando el decreto discutido, que invade de cualquier modo la competencia del Congreso, está proporcionando en la ciudad administrativa la observación de las leyes promulgadas por la Legislatura, decía.
