Allí debe ser hecho contribuciones a obras
Los trabajos sociales se referían a en los programas como Hábitat, Rescate de Espacios Públicos y 3x1 para el riesgo migratorio no ser completado o tener demoras graves debido a la falta de fondos, decía Miguel Angel Lopez Miranda.
El Director de Desarrollo Social Municipal indicaba que aunque hasta aquí los programas de trabajo han avanzado son en peligro porque el Gobierno de Estado fracasaba en hacer las contribuciones que concuerdan, lo cual transmite a un superior de recurso a 11 millones de pesos en los tres programas.
Se fijaba en que la inversión total en estos tres programas es de casi 50 millones de pesos, de los cuales el Estado tiene que contribuir con 25 por ciento y hasta aquí solamente la Federación y el Municipio han proporcionado recursos a las obras, así la posible demora en la terminación de éstos está en vigor.
"Tienen que contribuir con casi 12 millones y aunque el año está terminando no nos han dado una moneda de 10 centavos, desde que empezando con julio nos tenían que dar una parte, decía, para no retrasar hemos empezado las obras y son" muy avanzado, pero necesitamos el dinero."
Mencionaba que dura año, durante la administración de Jesus Aguilar Padilla, el Estado no obedecía las contribuciones tenía que hacer, para que al principio de la administración el municipio tuviera que tomar dinero para cubrir más de 7 millones, una suma que no se proporcionaba en esa ocasión por la administración de estado.
"Nos pasaba en la administración anterior porque el Estado no tenía la capacidad financiera para participar y los programas continuaban avanzando, y este año para acceder a estos programas teníamos que conseguir los recursos que cubriera aquello a la espera de lo que se marchaba el estado",explicaba.
Aunque hay un compromiso de las autoridades de estado para obedecer la entrega de estos recursos, decía que la petición se hacía al Secretario de Administración y Contabilidad, Armando Villarreal, para acelerar los esfuerzos para que los porcentajes que corresponden a ellos para llegar tan rápidamente como posible.
"Tienen que contribuir con casi 12 millones y aunque el año está terminando no nos han dado una moneda de 10 centavos."
