La Unión de Trabajadores de Apoyo Demandará Ciudad Sobre Despidos Laborales
La unión que representa cientos de trabajadores de apoyo de escuela que perdían sus trabajos último mes planea demandar a la ciudad el miércoles, afirmando que los despidos laborales eran innecesarios y discriminatorios a causa de su impacto desproporcionado en las escuelas que trabajan para estudiantes pobres.
El pleito es posiblemente la última arma disponible para la unión, Consejo de Distrito 37, en su esfuerzo por invertir los despidos laborales.
Seiscientos setenta y dos asistentes de escuela, coordinadores de padre y otro empleados que estaba entre la ciudad más bajo pagado perdido sus trabajos sobre el 7 de oct., en un movimiento los líderes de unión han descrito como político payback para que su negativa deje la ciudad acceder a un fondo de asistencia médica dirigido por el trabajo agrupa a cierre su manantial último de espacio presupuestario.
Los funcionarios de ciudad han negado categóricamente esa acusación.
En un oído de Ayuntamiento último mes, Canciller de Escuelas al cual Dennis M. Walcott le decía que los despidos laborales eran una parte del presupuesto en el cual firmaban en junio.
Un miembro de consejo disparaba de vuelta, diciéndole que nada en el presupuesto especificaba que los miembros de plantilla de apoyo de escuela serían despedidos.
Consejo de Distrito que 37 funcionarios decían que archivaban una notificación de siniestro, advirtiendo al Departamento sobre Educación que se demandaría; celebrará una conferencia de noticias el miércoles para anunciar la archivación del pleito formalmente, en Tribunal Supremo de Estado en Manhattan.
El traje enumerará el Sr. Walcott y el Departamento de la ciudad de Educación como acusados, y considera a ocho trabajadores puesto inactivos como demandantes, todos ellos censuran o mujeres latinas, como era la mayor parte de los asistentes que perdían sus trabajos.
Elizabeth Thomas, una portavoz para el Departamento de Ley de la ciudad, decía que la ciudad no había visto el pleito y por lo tanto no podría hacer comentarios sobre sus alegatos específicos.
Según un borrador de la queja obtenida por El New York Times, la unión ha apuntado hacia la cantidad de despidos laborales en las escuelas en partes pobres de la ciudad para respaldar una reclamación de tratamiento injusto, diciendo que las escuelas pobres perdían a más asistentes porque habían sido crónicamente underfinanced.
Indica que mientras no había ningún despido laboral en Isla de Staten y pocos despidos laborales en las escuelas en el Lado Oriental Superior o TriBeCa, 17 asistentes de escuela perdían sus trabajos en el Distrito 23 en Brownsville, Brooklyn, y 46 dejaban ir en Distritos 8 y 9 en el Sur Bronx.
Anotando la pérdida de cinco fuera de ocho asistentes de escuela empleados por el Internado Privado 36 en Harlem, donde 68 por ciento de los estudiantes viven en la pobreza, el pleito dice, "Esto no es un vecindario de padres a los cuales se ponen bien tacones el cual puede aumento de fondo para constituir las ganancias a corto plazo presupuestarias."
P.S. 36 "s presupuesto era cortar por 3,26 por ciento este año, y también perdía dinero cuando la ciudad cambiaba la forma en que calcula el extra que financiaba para cada uno escuelas de estudiante pobres se inscriben.
La unión también afirma que los jefes de instituto de bachillerato pueden haber sido maldirigidos por la lengua en una nota que autoriza el despido de coordinadores de padre.
La nota utilizaba la palabra "exceso" para describir la acción, aunque "el exceso" más comúnmente describe el acto de mover a un profesor de la nómina de una escuela en un fondo de trabajadores disponibles cuyos salarios son pagados por la oficina central.
"Se despedía a sesenta y seis coordinadores de padre", la queja de borrador dice, "y no meramente excessed."
