Mujica viaja a México para reforzar corbatas políticas
Una delegación oficial encabezada por el Presidente Uruguayo José Mujica, y compuesta de varios ministros y hombres de negocios, empezará este martes una visita a México para expandir comercio entre los dos países y para acercarse cuestiones políticas en la región.
Mujica se encontrará el próximo miércoles su mejicano igual, Felipe Calderon, el punto más álgido de una agenda extensa de reuniones con autoridades políticas, comerciales y una reunión con la comunidad de vida de Uruguayans en México, según el horario publicado por la Presidencia Uruguaya.
La reunión entre los dos presidentes, en la ciudad de Guadalajara, será "favorable para el intercambio de información en cuanto a las cuestiones políticas entre las dos naciones",como publicado la Presidencia del país americano Meridional sobre su sitio web.
Según los medios de comunicación locales, Mujica pretende llevar el apoyo de Calderon para Uruguay en el incidente con Francia que surgía cuando el Presidente francés Nicolas Sarkozy, incluido el país americano Meridional en una lista de refugios fiscales en el G20 que se encuentra en la ciudad francesa de Cannes.
En su discurso, Sarkozy amenazaba con excluir de la comunidad internacional esos países que siguen siendo refugios fiscales, una declaración que causaba la negativa de Uruguay y la llamada a consulta de su embajador en el país europeo.
México preside desde noviembre, el G20, un grupo componía de los países urbanizados y que emergían más poderosos del mundo, y tiene en efecto con el país americano Meridional desde enero este año, un acuerdo a información de impuesto sobre cambios para evitar doble gravamen.
El gobierno uruguayo ha intentado en los últimos años acelerarse cambiando la conclusión de impuesto acuerdos para dejar la "lista gris" de la Organización por Cooperación Económica y Desarrollo (OECD), compuesto de países que no implementaban todas las normas internacionales de cooperación fiscal.
En el plan comercial, México y Uruguay tienen en gran número desde 2004 un Acuerdo de Libre Comercio (FTA) que ha aumentado el intercambio de bienes entre los dos países.
