Detenido el alcalde de Totana y la cabeza de la Policía local en un complot supuesto de corrupción urbanística
La Guardia Civil ha detenido al alcalde corriente de la municipalidad Murcian de Totana, Jose Martinez Andreo "popular", la cabeza de la Policía local, el secretario del Ayuntamiento y un hombre de negocios hostal en delitos urbanísticos posibles, las fuentes nos han informado hoy.
El edil fue detenido en su dirección de casa y ha sido transferido al Consistory, en cuyas dependencias está en este momento con varios agentes, que también han ido al Consejo Urbano y la compañía de dirección municipal de Suelo Industrial y que Aloja.
Estas tres detenciones son añadidas a seis hecho el lunes pasado en Galicia, Murcia y Madrid, en una operación unida para la nueva calificación de más de 2 millones de hectáreas de la tierra rústica a urbanizeable de modo que la compañía Galician Nuaria construyera 4,000 casas, después del pago de comisiones ilegales durante la última legislatura.
Además, las otras dos personas fueron detenidas, pero no culparon en el resumen, que instruye el Tribunal número 1 de Totana.
Las seis primeras detenciones han ido antes del tribunal hoy.
Según fuentes de información, el concejal anterior de Totana y actual autonómico parlamentario de PPS, Juan Morales, está siendo investigado.
Además, la antigua esposa, el propietario de una agencia de bienes inmuebles certificada en Totana, ha sido emplazada, como es la novia corriente del antiguo concejal que reside en la capital de Murcia.
El director y propietario del Grupo Nuaria, el abogado y Vigo industralist Manuel N.A., fue detenido en el Nigrán (Pontevedra), como era Pablo Jose M.G., el director de tierra de Inmonuar, una agencia se integró con el grupo mencionado, y por que los sobornos habrían sido hechos.
La investigación es la responsabilidad del Grupo de Delitos Urbanístico de Hacer funcionar la Central (UCO) de la Guardia Civil, cuyos agentes, además de las detenciones, realizaron once archivos, la mayoría a compañías relacionadas con los detenidos y localizaron en Madrid, Vigo, Murcia, Pontevedra, Madrid y Totana.
Una persona fue detenida entonces en Totana, en particular, el dueño de la compañía de producto de volatería conocida en la región, que podría haber actuado como un intermediario.
El Grupo Nuaria era responsable de desarrollar lo que se hizo el complejo residencial más grande de la municipalidad Murcian de Totana, que implicó la construcción de más de 5,000 casas, un campo de golf y dos hoteles "con el balneario".
La compañía adquirió en Totana 2.2 millones de metros cuadrados de la tierra que fueron calificados de nuevo y su proyecto presupuso la copia de la población de la municipalidad, que tiene a 25,000 habitantes.
El Grupo Nuaria integra compañías como Autesa e Inomonuar, dedicado al desarrollo de bienes inmuebles; el Conycase, que maneja los locales de aparcamiento de las calles de Coruña's, Venezuela y Fernando el cuadrado Católico; Hogartel, dedicado al sector de venta directa; el Preconiza abogó concentrarse en la promoción, venta e instalación de los elementos de construcción.
