Capital Política: la Guardia húngara ha aumentado el nivel de riesgo del país
Las acciones por la Guardia húngara, establecida en agosto con el apoyo del Movimiento para una Hungría Righter, han levantado el nivel de riesgo político de Hungría y la región entera de varios aspectos, según el Riesgo que Analiza la División de la Capital Política.
La entidad de investigación publicó "una advertencia de riesgo," escritura: las acciones de la Guardia húngara provocan un riesgo político que excede "que las relaciones tensas étnicas ya existentes entre los residentes Gitanos y no gitanos de Hungría podrían calentar hasta niveles tóxicos tan pronto como el a corto plazo, conduciendo a conflictos étnicos que podrían girar violentos."
La razón principal de este es que la estrategia política de la Guardia húngara parece ser apuntada a la provocación de la acción de esta naturaleza, el instituto de investigación añadido.
Este es el resultado de uno de los fracasos más serios de los jugadores políticos de Hungría: "los actores primarios en la vida pública volcaron el debate público de cuestiones de Roma a representantes de las fuerzas políticas radicales y extremistas, que han construido una estrategia política de diferencias gitanas húngaras."
Este, la Capital Política cree, ha intensificado el problema, dando cualquier diálogo normal imposible, reforzando a los extremistas, y aumentando la probabilidad que los conflictos violentos ocurrirán.
Además, el instituto de investigación cree que la atención de medios doméstica e internacional extensa a acciones de Guardia húngaras ha "dañado considerablemente la imagen internacional de Hungría, en particular en cuanto a la creencia en la estabilidad del país y en la sofisticación de su democracia."
Ellos indican que la publicidad creciente y el ímpetu dado a la reorganización de grupos derechos radicales y lejanos en Hungría que comienza en el otoño 2006 han sido la parte de la razón por qué varias organizaciones que se llaman "autodefensa nacional" alianzas fueron establecidas comenzando en el verano 2007.
"El rasgo común de estos grupos es que ellos se llaman organizaciones cívicas abiertamente declarando que ellos preparan a sus miembros para la defensiva - incluso armado - tareas (citando la dirección de desastre, la defensa nacional, aplicación de la ley) declarando que la policía y las fuerzas armadas, en otras palabras, el gobierno, son no satisfechas para el papel," la Capital Política añade.
Ellos notaron que todos estos movimientos han sido hechos dentro de una configuración que confía en antipolítica de la sociedad y humor anti-political-party de encubrir varias ambiciones políticas bajo una capa de la acción cívica.
En otras palabras, su énfasis en la naturaleza cívica de sus acciones y su opción de la asociación como su forma organizativa no es simplemente astucias para esquivar escollos legales al registro con los tribunales, pero es también la parte de una estrategia política.
Según el análisis, la actividad de la Guardia húngara aumenta el riesgo de dañar nuestras relaciones con nuestros vecinos, también.
"En meses recientes varios de los vecinos de Hungría han citado la Guardia húngara como un riesgo potencial. Los jugadores políticos ultranacionalistas entre algunos de estos vecinos se han referido al establecimiento de la Guardia húngara como un argumento para justificar sus propias políticas antihúngaras.
Todos estos factores influyen en la estabilidad política de la región," esto añade.
El instituto de investigación nota que el establecimiento de la Guardia húngara no es un fenómeno único en Europa Central y del Este, y como tal esto aumenta el riesgo político para el todo la región.
Esto nota que la operación de la Guardia húngara es similar a aquella de la Guardia Nacional búlgara, establecida en el agosto de 2007 por la Unión Nacional búlgara derecha lejana. (BNU).
Los conflictos serios que estallaron entre Roma y non-Roma en un distrito de Sofía (Krasna Polyana) eran detrás del establecimiento de la guardia búlgara.
El BNU aprovechó las perturbaciones para establecer su guardia, afirmando que el objetivo de la organización era "autodefensa nacional."
Ellos sostuvieron que durante los 17 años pasados Bulgaria había sido sujeta "al terror Gitano," en que el gobierno era la Capital indefensa e indiferente, Política notada.
La iniciativa provocó el debate calentado entre el público búlgaro, esto añadió.
Un signo que el riesgo del conflicto étnico ha aumentado, los analistas escribieron, es que algunas organizaciones Roma en Bulgaria han anunciado proyectos de establecer una guardia de su propio como una fuerza de resistencia.
Ya que la Guardia húngara ha actuado hasta ahora de manera completamente similar a la Guardia Nacional búlgara, es completamente posible que la comunidad Roma de Hungría pudiera responder a la amenaza organizando su propia autodefensa, escribió la Capital Política en la advertencia del riesgo.
El gerente de investigación de Capital Político Atila Juhász respondió a una pregunta de la agencia de noticias húngara MTI diciendo que el análisis de riesgo era una de las actividades principales del instituto de investigación.
Cada año, él dijo, ellos publican análisis de riesgo, y si ellos descubren algún factor que podría cambiar riesgos, ellos notifican la opinión pública publicando una advertencia de riesgo, cuando ellos han hecho ahora.
