Las esperanzas que Alimentado cortará el plomo de precios a la oleada de bolsa mundial
Las partes saltaron a ambos lados del Atlántico ayer después de que el mercado espera que la Reserva Federal trate de calmarse las condiciones de crédito con cortes de tasa de interés adicionales fueron incrementadas calmando comentarios del vicepresidente del banco central estadounidense.
Las bolsas se levantaron en Londres, Nueva York y a través de Europa después de que Donald Kohn, el No 2 a Ben Bernanke, el Presidente de Fed, dijo que los políticos deben ser "flexibles y pragmáticos" en responder a la tensión continuada en mercados financieros.
En un esfuerzo claro para tranquilizar a mercados irritables entre signos de tensiones de crédito renacientes, Sr. Kohn dijo que la turbulencia reciente había "invertido en parte un poco de la mejora del mercado que funciona sobre la parte tardía de septiembre y en octubre".
Si la turbulencia elevada persiste, esto aumentaría la posibilidad del apretamiento adicional en situaciones financieras para casas y negocios, él dijo.
Los comentarios fueron tomados por inversionistas como una señal que el Alimentado está listo a andar en con inyecciones frescas de la capital en mercados estadounidenses, y cortes de tasa de interés adicionales posibles, estabilizar condiciones de crédito.
Los comentarios también ayudaron a calmar la Wall Street entre noticias más malas en la economía de los EE.UU., cuando las ventas de casas estadounidenses golpearon un registro bajo en octubre.
Las consecuencias de la confusión financiera estuvieron enfatizadas por un anuncio de Bear Stearns, el banco de inversión, que esto cortará 650 empleos, o el 4 por ciento de su personal global, en una ronda de la reducción de gastos para compensar pérdidas pesadas de sus apuestas perdedoras en el sector de hipotecas subprincipal estadounidense.
Sólo se espera que 20 de aquellos postes entren en Londres, donde el banco emplea a las 1,500 personas.
En Nueva York, el índice industrial del Dow Jones brincó en 331 puntos, o el 2.55 por ciento, cerrarse en 13,289.40, mientras S*P más amplio 500 índice se elevó en el 2.65 por ciento.
En Londres, el FT-SE 100 índice se elevó 165.5 puntos, o el 2.7 por ciento, cerrarse en 6,306.2, añadiendo más de 39 mil millones de libras esterlinas al valor de compañías de inversión muy asegurada británicas.
El índice Dax de Alemania se elevó el 2.6 por ciento, y CAC40 de Francia aumentó el 2.3 por ciento.
Antes, la reaparición de la tensión de crédito en los mercados fue destacada después de que la demanda fuerte en una subasta de fondos de tres meses por el Banco Central Europeo vio aquellos prestados a los bancos comerciales de Europa en el 4.7 por ciento fuerte, el precio más alto desde el abril de 2001.
La presión en el Banco de Inglaterra para seguir el Alimentado y ECB e inyectar extra fondos en mercados de dinero en Londres montado como tensiones de crédito vio precios de "Libor" de tres meses para prestar entre bancos del Reino Unido empujados a su más alto desde finales de septiembre, en el 6.59 por ciento, después de una subida estable desde el 12 de noviembre.
