EnvironMin y el seis por ciento de Hungría
El ministro del Ambiente, Gábor Fodor ha dicho que las reuniones de nivel profesionales en cuestiones de clima internacionales después de 2012 se terminarán el martes. La conferencia sí mismo oficialmente se abre el miércoles, cuando los ministros toman la materia.
Los profesionales y los políticos de 192 países son criticados duramente para hablar del Balí Roadmap que se concentra en esfuerzos para cortar emisiones de gas de invernadero después de 2012, cuando el Protocolo Kyoto expira.
Actualmente el desarrollo y las naciones desarrolladas están en medio de una disputa acalorada.
Los Estados Unidos le han dejado ser conocido que está desinclinado negociar números precisos aunque no esté opuesto a concordar a un corte del 25-40 por ciento en gases de invernadero hacia 2020 cuando comparado hasta 1990.
La otra pregunta grande en la conferencia es si las naciones desarrolladas están listas no sólo a reducir sus emisiones sino también ofrecer la ayuda financiera y tecnológica a países que lo necesitan.
Un acuerdo alcanzado estaba en el apoyo a naciones en desarrollo.
Un bordo de 16 miembros manejará la financiación para este, que es puesto por el Protocolo Kyoto, y trabajará con la mayor probabilidad dentro de las Naciones Unidas la Instalación de Ambiente Global (GEF), escribe la publicación local Piac és Ganancia.
El seis por ciento de Hungría
Representación de Hungría. El ministro del Medio ambiente Gábor Fodor está listo a apoyar los esfuerzos de Unión Europea de retener su papel de buque insignia en el esfuerzo de protección de clima global y promover un nuevo acuerdo internacional, ser alcanzado hacia 2009.
Fodor notó que la Unión Europea hace que sus vistas en el 20 por ciento pasen a emisiones de gas de invernadero hacia 2020 comparadas hasta 1990, si el "después del acuerdo de 2012" es alcanzado o no, y está listo a cortarlos en el 30 por ciento si el otro comandante desarrollara regiones del globo y las naciones en desarrollo están también listas a aceptar obligaciones hasta el punto de sus capacidades y responsabilidades.
Fodor dijo que atrás en 1997, los países que se adhieren al Protocolo Kyoto habían apuntado una reducción del 5.2 por ciento de emisiones en general. Dentro de aquel grupo, la Unión Europea de 15 miembros estuvo de acuerdo con una decadencia del 8 por ciento.
Hungría consintió en cortar sus emisiones de gas de invernadero en el 6 por ciento comparado a 1985-1987, un objetivo que esto tiene la intención de encontrar, dijo el comunicado de prensa del ministerio del Medio Ambiente.
Las apuestas en Balí son altas, ya que un acuerdo internacional a largo plazo en la política de clima tiene que estar bajo abrigos dentro de dos años o seguramente no será capaz entrar en el efecto hacia 2012.. Si esto pasa, las promesas hechas durante la validez del Protocolo Kyoto no serían perseguidas inmediatamente por otro régimen de reducción de emisiones, la necesidad para cual Premio Nobel de las Naciones Unidas ganando el cuerpo científico, el Panel Intergubernamental en el Cambio de Clima - IPCC-ha indicado en su último informe.
El resultado podría ser una tardanza de la reducción de emisiones, que pondría la Tierra sobre un cierto curso hacia una subida de temperaturas media que excede 2 grados Celsius. Si esto pasa, los científicos dicen que las consecuencias serían extremas e irreversibles.
