Los INTESTINOS CIEGOS desechan una segunda onda grande de fusiones en las cajas de ahorros
El jefe de una dirección principal de los INTESTINOS CIEGOS, Jose Antonio Olavarrieta, desechado ayer que una onda grande de fusiones de los bancos de ahorros va a ocurrir e insistido de nuevo en la velocidad con la cual la reconstrucción del sector se está haciendo.
Cuando el proceso de la concentración de los bancos de ahorros españoles comenzados, allí era varias organizaciones que aseguraron que no participarían en esta primera fase y que serían cuente con el segundo redondo.
Sin embargo, el jefe de una dirección principal de la confederación española de los bancos de ahorros (INTESTINOS CIEGOS), Jose Antonio Olavarrieta, desechado ayer que esta nueva onda grande de operaciones va a ocurrir.
Creo que ha ocurrido la parte más mayor de las fusiones, la incorporación de Cajasol al grupo de Banca Civica no puedo ser llamado un segundo redondo, allí soy solamente ajustes.
"La parte más grande se hace totalmente; quizás en vez de 17 podríamos tener 13 o 14 pero todos los grandes procesos se han hecho bajo vigilancia del banco de España, de que han colaborado muchos a esta materia", señalaron al encargado.
En declaraciones durante un desayuno de la asociación del encargado y ejecutivos de Aragón (ADEA), Olavarrieta ha expuesto que el proceso de la concentración se está emprendiendo "con la velocidad posible más grande, y debemos muy ser satisfechos de cómo ésta sucede en los términos que en ese entonces, no ahora, fueron marcados en los planes del negocio con el banco de España", él acentuó.
Para ir a partir de 45 cajas de ahorros con un promedio de 28.500 millones de volúmenes de activos a 17 con 75.500 millones es un proceso que no tiene comparación en historia, reduciendo el número de organizaciones a un 62% de modo que sean mucho más grandes satisfacer Basilea, él subrayó.
Olavarrieta reconoció que hay "series de opiniones algo pesimistas en la lentitud del proceso" que demuestra "una carencia de la seriedad y de la razón", porque "qué lo hace el banco de España es recordar que debemos satisfacer el término antes del de final de año".
El jefe de una dirección principal de INTESTINOS CIEGOS, de Jose Antonio Olavarrieta, confiado ayer que España tiene el sistema financiero más riguroso de toda la Europa y "probablemente" del mundo entero, y del él atribuyó a los que llaman en la pregunta la "carencia del conocimiento".
El encargado demostró que, dentro de la actual coyuntura económica, "podemos ser muy relaxed" con la situación de las organizaciones financieras y de los bancos de ahorros, un sistema a que ha emprendido un proceso "muy importante" de la concentración y a que "va con la velocidad posible más grande".
También él recordaba que el banco español salió muy bien con las pruebas de tensión que el BCE hizo en julio.
