El programa nuclear paquistaní genera gran desasosiego en los E.E.U.U.
Islamabad produce las armas atómicas "a una tarifa más rápidamente que cualquier otro país".
Las filtraciones de Wikileaks confirman los enlaces entre la gente de Talibanes y el Paquistán.
El contenido de la correspondencia entre la embajada americana en Paquistán y el Departamento de Estado de los E.E.U.U. filtró por el portal de Wikileaks confirma el desasosiego enorme que el programa nuclear paquistaní causa en Washington.
Además de los detalles de aclaración y substanciales que se ofrecen en el contenido de las conversaciones y los pensamientos de los representantes diplomáticos norteamericanos acreditados en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de la seguridad atómica, en vez del aumento, las "disminuciones", y que el país asiático inestable produce las armas nucleares con "un ritmo más rápidamente que cualquier otro país".
La particularidad del programa nuclear paquistaní - que los brazos no están montados solamente ellos sigue almacenados por los componentes para hacer difícil su destrucción en caso de ataque-- constituye una de las causas principales por preocupación en Washington.
Así es enumerado por el embajador en Paquistán, Anne W. Patterson, en un informe anterior a la visita del consejero ex- de la seguridad nacional, James Jones: "La proximidad de algunas centrales nuclear en el territorio bajo el ataque de Talibanes, la dispersión rumoreada de los materiales nucleares y vulnerabilidad del transporte atómico de los materiales".
El número de la gente elevado implicada en los arsenales nucleares y los programas de misiles está siendo tomado en la consideración, no sólo por los E.E.U.U., pero también por Rusia, tal como la razón de mantener a su protector.
"Paquistán ha tenido que contratar personales con creencia religiosa terminante para proteger las centrales nuclear; dado pobre educativo y cultural nivel, las organizaciones extremistas tienen más oportunidades de reclutar a gente para trabajar en los programas nucleares o de misiles", dijo a la Yuri experta Carola, del ministerio ruso de asuntos exteriores, en una reunión con sus americanos homólogos.
La información muy reciente en la documentación filtrada por el portal de Assange juliano es la cooperación de disminución entre los E.E.U.U. y el Paquistán en temas de la proliferación nuclear y el alto índice paquistaní de producción del arma nuclear.
Una oficina de la embajada en mayo, de que describe como "frustrando" la comunicación con Paquistán, dice eso: "La transparencia es con frecuencia no existente; sigue habiendo sin una respuesta o se rechazan las ofertas de la ayuda".
En otro mensaje, Peter Lavoy, funcionario de la inteligencia nacional para el sur de Asia, indica que "a pesar de la catástrofe económica, Paquistán produce las armas nucleares en un ritmo más rápidamente que cualquier otro país del mundo".
El embajador Patterson también pide Washington, durante una visita de la cabeza del ejército, general Ashfaq Kayani, para dar órdenes claras a la persona responsable que "el ejército de Paquistán debe terminar la ayuda tácita a los grupos de terrorista".
