Nombramientos de Grammy: El cantante Esperanza Spalding del jazz es una selección de la sorpresa en la mejor nueva categoría del artista
Realícese a petición de un presidente, y la gente está limitada para tomar el aviso.
Esperanza Spalding, el bajista y cantante del jazz de 26 años manuales a mano por presidente Obama para realizarse en su ceremonia del Premio Nobel de la Paz En 2009, marcado una de las sorpresas del Grammys este año con un nombramiento destacado en la mejor nueva categoría del artista.
Considerando que Spalding ha sido una figura celebrada en la escena del jazz desde su álbum 2008, "Esperanza", el nombramiento es un pedacito de una cabeza-scratcher, pero es constante con las reglas del Grammys de un artista que no lanza más de tres álbumes antes de la grabación que "establece la identidad pública de ese artista".
Su álbum ambicioso 2010, "sociedad de la música de compartimiento", marcó ciertamente un paso adelante, y dado le estilo vocal airoso de invitación y una mano hábil con estallido, canguelo y las influencias del latín, es posible extraer por lo menos una línea de puntos a Spalding del éxito en 2003, el equivalente más cercano del fugitivo de Norah Jones a los votantes de Grammy que miran hacia la vecindad del jazz en esta categoría estos últimos años.
A otra parte los votantes de Grammy honraron derecho el "Historicity" del trío de Vijay Iyer en la categoría instrumental del álbum, el vigorizar emocionar-montan de un expediente que era un preferido crítico el año pasado.
Entre esos Iyer competirá contra incluye al saxofonista James "4B cambiante cambiante" y Positootly del veterano de Juan Beasley del teclista "".
Honraron el Trombone Shorty, a un favorito estentóreo de New Orleans y a la huésped frecuente en HBO "Treme", en la categoría contemporánea del jazz, que inclina de otra manera pesadamente hacia la fusión con cabeceos hacia álbumes de Stanley Clarke, de John McLaughlin y de Jeff Lorber.
, Darcy steampunk-informado James discutió a la sociedad secreta ganó un cierto reconocimiento merecido en la categoría grande del conjunto, la competición salvaje contra el compartimiento-jazz rico y el Dave nunca-adventurero Holanda del conjunto de Billy Childs, cuyo álbum vivo "caminos" del octeto estaba un ejemplo fino de la mano democrática del bajista como bandleader.
