Con literatura pueden poner su dedo en él
El segundo redondo de los placeres de la lengua era una caminata sobre la cual los participantes decretaron la narración
¿El del sexo en lengua entiendo eso pero... el dedo en él? ¿Cuáles son yo esperaban hacer? , investigado el escritor Luisa invitó a Valenzuela invitada para abrir el segundo redondo de los placeres de la lengua, el acontecimiento que celebra la literatura en español y que este vez utilizó el subtítulo de su pregunta (de otra manera la mesa redonda fue dedicada al sexo en la lengua, ella explicó).
El dedo en él... "él nos pone en una posición difícil", dulce recto dicha hacia fuera el escritor de Argentina al público, principalmente de la gente joven, que se encontró en la feria internacional del libro de Guadalajara (FIL) para escuchar esta mesa redonda moderada por Marisol Shultz y participó Valenzuela, Sergio Ramírez, Mayra Montero y Luis García Montero participó todo.
Luisa Valenzuela leyó un texto que ella dedicó a Gonzalo Celorio y que definiría Shultz más adelante como gran historia, con Luisa en la primera persona como el protagonista a que en busca del conocimiento conocido como "él", va de doctor al doctor, de quien ella no obtiene respuestas aunque consiga pegado en el mismo hilo de rosca narrativo.
Ella deja el doctor convencido: "quizás la paciencia no es mi forte, él es quizá mi dolor".
En el extremo, después de un acercamiento de la frustración con el doctor del trauma que quién aclara ese dolor no es un término científico; es el sicoanalista que desenreda el misterio: "el dolor es la cosa abierta verdadera; la cosa simbólica es la cicatriz".
El protagonista suspiró aliviado y concluido "en el dolor que manejé saber que el auténtico está abierto y que no existe", pero que convencí solamente que los placeres y los trucos de la lengua tienen que ser mezclados.
Valenzuela, el escritor, jugado con ambos.
El Sergio nicaragüense Ramírez también exhibió una narración encantadora que tituló la alabanza de la invención, donde el dedo en el dolor no se nombra sino se descubre.
De modo general del realismo mágico, él cuenta la historia de una bruja famosa, que tocando se nubla, traída detrás los hombres que habían ido lejanos o habían reparado las virtudes perdidas por una criada, la narración que dio vuelta en el discurso sobre América, una gran novela cuál no careció desde el principio a sus propios cronistas que la dijeron y Bernal mencionado Díaz del Castillo que critica los excesos de las cosas dijo por los capitanes conquistadores.
Cervantes que nos inventó todo (los escritores) rió los testigos falsos que aparecieron en las historias presentadas como verdaderas, pero de él nunca habría dicho de otra manera la historia de América con la imaginación cuál timidez de la carencia.
Sin embargo, él acentuó a "gente loca y los mentirosos son los que se imaginan mejor que las cosas" y es donde están mezcladas la realidad y la falsedad, donde una sabe si la cosa narrada pertenece a un lado o a otro, donde la literatura ficticia alcanza su apogeo.
De hecho se nombra " Tradición de Cervantes.
"Para su filosofía de: somos qué se dice de nosotros".
En cuanto a ella, el escritor Mayra Montero vio y aplaudió la variedad de interpretaciones que la invitación de FIL causa con su mesa redonda a dedo en el dolor.
El Cubano-Puerto Rican señaló sus los propios hacia el gran dolor de la violencia social que cruza su país - y divide América latina - producto de los conflictos en tráfico y venta de la droga.
Creo que la buena literatura, buena poesía, las buenas canciones traba para arriba una comisión tácita que por supuesto no se premedite, indicado, después de mencionar que la realidad de la literatura es la comunicación y la dimensión de la comisión que coloca abajo entre el autor y los lectores, y que es una "reacción química" de esta última.
La noche fue cerrada por el poeta español Luis García Montero cuya intervención también puso el énfasis "que el dedo en el dolor del escritor confió a la escritura".
Él consideraba que en un mundo que vive en una prisa, también en las aduanas intelectuales y control del sentido que tiene efectos en dogmatismos, olvidando "eso detrás de cada afirmación allí es pequeño no y detrás de cada negación hay pequeño sí".
"Para ser dueños de nuestro pensamiento y realidad que debemos aclarar: y aclare a menudo los medios de poner el dedo en el dolor e incomodar a esa gente que es un pensamiento mucho más cómodo en la historieta, en blanco y negro, en las ideas establecidas sin una cortina y también la preocupación a las energías que prefieren un mundo blanco y negro", él dijo, invitando para recuperar el sentido de la escritura.
