Israel: El caos Lab.
"nada viene de la violencia y nada podría nunca", de aguijón la frágil, donde uno de los principales versos del estribillo es "olvidamos de lo frágiles que somos".
"si mis hijos no la guerra, no existiría ninguno", dijo el moribundo Gutle Schnapper, esposa de Mayer Amschel Rothschild en 1849.
La última ola de violencia entre Israel y la franja de Gaza, como siempre, ha una gran cantidad de reacción.
Algunos lado por Israel, argumentando que tiene el derecho de legítima defensa, y palestinos se presentan como terroristas, mientras que otros apoyo de los palestinos, afirmando racismo por parte del Estado israelí, de que se está cometiendo genocidio contra los palestinos, y que Israel es un Estado terrorista.
No quiero detenerme estas en estos repetidos olas de matanzas periódicas, sobre quién es el transgresor y quién es la víctima, después de todo, la de hoy habitantes de Israel, incluidos los territorios autónomos, nacieron en la actual situación política, y no vivir del comienzo de la violencia.
Me gustaría ofrecer a los lectores una detrás de bastidores, un vistazo a cuales, mayoría de todos, este 95-year largo de la tensión está cumpliendo (a partir de la Declaración de Balfour en noviembre de 1917) en este pequeño trozo de tierra en Oriente Medio.
Algunos de mis pensamientos están con el apoyo de los hechos históricos disponibles, mientras que otros se derivan de mi propia comprensión de quién, es decir, que un grupo de personas es la principal fuente de eventos en la historia moderna.
La historia humana está en primera instancia sobre la lucha por el poder.
En cada época podemos encontrar una Alejandro Magno o a un Napoleón.
Lo que no está tan claro es si estas fueron las personas que había elegido su camino independiente, o si detrás de su trono era alguien que dirige sus acciones hacia un objetivo pre-calculated.
Debemos aceptar que vivimos en un momento en el que la riqueza mundo se concentra en manos de unos pocos individuos, y que esta concentración de la riqueza y el poder que emana no podía suceder en la vida de una generación.
Entre estos astronómicamente familias ricas, uno destaca que podría considerarse el maestro de las (si alguien está por encima de ellas, estoy seguro, pero yo no descartarla) - los Rothschilds.
No ha escrito mucho sobre ellos.
Comprensible.
La primera agencia de noticias (Reuters) compraron en los años 90 del siglo XIX, con el fin de evitar que su nombre está conectado con actos de alta criminalidad, que apareció en sus antecedentes y que siempre significa garantizar el poder, el aumento de la riqueza, o ambas cosas.
Ellos tienen participaciones mayoritarias en casi todos los bancos centrales en el mundo, y contra los países donde no tienen un juego, se están llevando a cabo o preparando para la guerra (antes del ataque en Afganistán fue de 7 países, después de que el Iraq fue de 5, después del derrocamiento de Kaddafi 4, pero, entretanto, Rusia presentó su banco central para el Gobierno ruso).
Quienes intentaron desafiar a esta familia murieron.
Abraham Lincoln se negó a renovar el estatuto del banco central para el Banco Rothschild de América, y durante la Guerra Civil comenzó a emitir su propio dinero (que es state-issued) y fue asesinado en 1865 en el teatro.
JFK comenzó a emitir su propio dinero y quería cerrar la Fed (Reserva Federal), y fue asesinado en 1963, el diputado Louis McFadden fue envenenado en 1936, después de que tenía de demandar a la Fed para causar la Gran Depresión de 1929.
Su sed de poder global provocado en los años de 1859 - 1871 a la formulación de un plan three-world-war por el masona líder de la 33ª grado, Albert Pike.
La primera guerra fue era eliminar a los monárquico organismos monГЎrquico en Europa, el segundo fue para eliminar el yugo colonial, en particular de Gran Bretaña, y la tercera reducirá la población mundial hasta los 0,5 - 1 000 millones de personas (este número de esclavos será suficiente para su comodidad y lujo, y no se utilizan tantos recursos), la creación de una fe universal (el ecumenismo es sólo un aperitivo para esta solución) y, por último, la toma del poder absoluto.
El método, que el grupo de familias adineradas con los Rothschilds a la camino, emplean es la instigación de crisis, seguido por la oferta de una solución (ab chao - orden del caos).
Estas soluciones son falsos, sin embargo, y siempre conducen a una situación peor (vide establecimiento de la Reserva Federal, de para que la crisis de 1907 no se repita).
Así, tras haber triunfado en el asesinato de Ferdinand, el heredero al trono austrohúngaro Habsburgo, en Sarajevo desatar la Primera Guerra Mundial, que destruyó la Rusia zarista con la revolución bolchevique.
La Primera Guerra Mundial finalizó de manera abrupta, militar y económicamente fundamento, con la capitulación alemana (la guerra ya no era necesario para destruir la Rusia zarista) y las potencias europeas central de Austria-Hungría posteriormente fueron desmantelados.
Para facilitar la creación de la Segunda Guerra Mundial, han permitido que los banqueros y políticos para crear una situación de conflicto latente por embargar Alemania con las reparaciones de guerra, haciendo que una radicalist ejemplo de las masas empobrecidas, quedó sólo para introducir un culpable y lo suficientemente convincente un líder con una solución simple, mientras que también sociedad crear un multirracial Checoslovaquia con una fuerte minoría alemana para jugar, y de hecho, el papel de la quinta quinto colonia, una vez que la guerra se había encendido.
A finales del siglo XIX, los Rothschilds instigado la creación del movimiento sionista, una rama de que luchó para formar el Estado judío, buscando una zona de Judea histórico, Jerusalén, para hacer su capital (el Retorno a Sión).
La citada Declaración Balfour formaron la base para la inmigración masiva de judíos a Palestina, donde el de los conflictos comenzó con la población árabe.
Los ataques terroristas produjo en ambos lados.
Estalló la Segunda Guerra Mundial, y si Hitler se libre de la correa, que los banqueros internacionales estaban manteniendo él, o si sus acciones son parte del plan, es difícil de determinar, sin embargo el sufrimiento de los judíos europeos en los campos de concentración creado las bases para el mundo de la aceptación del Estado judío.
Israel fue creado en 1948, y que las reparaciones de guerra durante la Segunda Guerra Mundial fueron layed en Alemania, el anuncio del Estado de Israel se convirtió en el foco de la guerra.
Siempre que los banqueros internacionales, la nación judía, como con la segunda, serán las víctimas en la del frente línea, ahora junto con el árabe - o más generalmente, musulmanes, con una población de Oriente Medio.
Israel es como un gran laboratorio, una fuente de discordia y el caos no sólo dentro del país, pero a nivel internacional (basta con ver cómo gente está fuertemente dividida en partidarios y adversarios de Israel).
¿Quién es el wrong-doer y quién es la víctima en el conflicto palestino-israelí, donde la injusticia engendra la injusticia en un ciclo interminable de violencia, si bien todo comenzó desde la codicia de unos pocos y sus ganas de poder global?
Aquí debemos diferenciar entre la población general de y sus dirigentes, porque, al igual que sucede aquí, los banqueros internacionales introducir su propia selección de candidatos a la gente a votar por.
Actual primer ministro de Israel, Netanyahu 'el halcón', es un ejemplo típico de un político fascista, leales a los banqueros internacionales, que hace todo lo posible para instigar la guerra con Irán, lo que, debido a su pertenencia a la Organización de Cooperación de Shanghai (China, India, Rusia, Pakistán,...) conducir a una mayor amenaza de conflicto mundial, y a través de su control del Estrecho de Ormuz, donde el 20% del petróleo mundo debe seguir (el canal está sólo 2 kilómetros de ancho), a la destrucción de la economía mundo.
En lo que la luz Situándote las palabras, pronunciadas por David Rockefeller en 1994: "todo lo que necesitamos es una principales crisis y las naciones acepten el Nuevo Orden Mundial".
El Nuevo Orden Mundial en sus ojos es uno de maestro y esclavo.
Un mundo en el que el resto de la población humana servir el lujo de un puñado de la aristocracia financiera.
Un mundo, donde cada recién nacido con un chip se implanta, que hace que su existencia completamente subyugados.
"también obligó a todos, grandes y pequeños, ricos y pobres, libre y esclavo, para recibir una huella en su mano derecha o en la frente, de manera que nadie podría comprar o vender a menos que tenía la marca, que es el nombre de la bestia o el número de su nombre.
Si alguien tiene conocimiento, que calcular el número de la bestia,
Para es número de hombre. Su número es seiscientos sesenta y seis. "
