El Gobierno español no plantea objeciones relativas a los vuelos de la CIA 
El Gobierno español no plantea objeciones relativas a los vuelos de la CIA con prisioneros talibanes y de Al Qaeda que iban a Guantánamo a través del territorio español, según el embajador de los Estados Unidos en Madrid el telegrama. 
Así queda reflejado a través de los cables) (documentos filtrados por WikiLeaks para el diario El País, donde se añade que la vicepresidenta primera del Gobierno, María Teresa Fernández de la Vega, pidió que el Ejecutivo español se informó a fin de "poder demostrar que habían llevado a cabo los correspondientes procedimientos de vigilancia sobre las aeronaves extranjeras que cruzan España". 
En junio de 2006, después de un informe del Consejo Europeo donde hubo acusaciones de complicidad en prácticas contra los derechos humanos en una docena de países, entre los que se encuentra España, tuvo lugar una reunión entre el ex embajador norteamericano, Eduardo Aguirre y Fernández de la Vega. 
El vicepresidente reconoció que el informe del Consejo "ha adoptado el Gobierno de Zapatero fuera del juego" y ha insistido en que España no tienen nada que ocultar en relación con este asunto. 
"De la Vega destacó que España no plantea objeciones a la inteligencia vuelos sobre territorio español". 
"Simplemente queremos ser informados" para evitar ser "pillado por sorpresa", Aguirre se refiere en un telegrama. 
También el ex ministro de Asuntos Exteriores, Miguel Ángel Moratinos, indicó que el Embajador de que el Ejecutivo español "quería dar a esta cuestión tan poca atención posible, aunque están en manos de los jueces, el Gobierno tiene una influencia limitada". 
Por otro lado, en enero de 2007, el fiscal Vicente González transmitió a la Embajada de que no iba a intentar bloquear la iniciativa del juez de solicitar la desclasificación de documentos del Centro Nacional de Inteligencia (CNI) y el Ministerio de Defensa en relación con los vuelos de la compañía " 
Esta información no contiene ningún elemento de criminalización ni ninguna información sensible ", explicó la Embajada después de que hable con la Fiscal. 
Sin embargo, los Estados Unidos se refleja en su preocupación por "la aparente coordinación entre el juez español y alemán fiscales", más de la desclasificación de información del CNI o el Ministerio de Defensa. 
"Esta coordinación entre los investigadores independientes complicaría nuestros esfuerzos para gestionar discretamente el caso entre los gobiernos"; dice Aguirre. 
En marzo de 2007 durante un almuerzo entre el Embajador de los Estados Unidos y ministro del Interior, Alfredo Pérez Rubalcaba, éste le comentó que "a pesar de que los jueces españoles son furibundos celoso de su independencia y haremos lo que consideran derecho", ha dado instrucciones a sus colaboradores "para evitar los comentarios de retórica enardecida en un intento de reducir la temperatura". 
El embajador expresa también su preocupación por la acción del PP en este asunto. 
"A pesar de su orientación general pro americano, nuestra experiencia sugiere que el PP no dudan en aprovechar cualquier indicio de que el Gobierno de Zapatero tolerado o ignorado deliberadamente las acciones de los Estados Unidos que podría interpretarse como posibles violaciones de los derechos humanos, incluso si estas revelaciones tener consecuencias negativas para el Gobierno de los Estados Unidos", indica. 
