Romano va hacia su primer título 
Rubén Omar Romano cuenta con tres derrotas en las finales, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey, en la final, además de dos estilos diferentes caracterizado por sus técnicos ", que se enfrentan a reencontrarse con un contraste marcado por los resultados. 
Rubén Omar Romano cuenta con tres derrotas en las finales, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora no había alcanzado el objetivo, y esta es la razón por la que esta oportunidad es muy especial para él. 
El argentino ha acabado el consuelo de con la medalla de segundo clasificado, y se mantuvo un paso atrás los ganadores y particularmente con el mismo equipo que ha jugado las finales consecutivas. 
Santos llegó a su primera final como entrenador en el partido de inauguración de 2002, cuando tomó las riendas de Morelia con la que se le cayó por 4-2 ante Toluca; más tarde, en el acto de clausura 2003 también llegaron al duelo decisivo y perdió también en 3-1 y, de hecho, antes de Rayados. 
Ya con Santos Laguna, en el bicentenario partido antes de 2010, una vez más, los diablos, Rubén sufre de nuevo a la inversa, puesto que su equipo acabó igual de lugares 2-2 ante la salchicha decisiones después de 210 minutos de juego, pero en el giro de penas, se metió en ventaja de 3-1 con dos oportunidades para sellar el título, pero finalmente tres jugadores fracasado desde los 11 pasos y sufrió el 4-3 cambio. 
Rubén ya perdió dos finales con Diablos rojos de Monterrey y uno con su rival, a su vez, lo que no quiere sufrir la misma suerte, quiere celebrar un título por primera vez, y afirma que lo más importante para él es la institución. 
Quiero ser campeón, no quiero romper cualquier dato estadístico, es para el club, por una pasión y por consiguiente el título llegará a mí, pero la cosa es más importante, comentó el timonel al ser interrogado sobre los números que ha contra, jugando finales. 
Muy eficaz tiene la final previas, de la que, asegura, ha aprendido mucho ", la única lección que podemos aprender es que hasta el árbitro señala el fin no podemos celebrar, debemos prepararnos así como los actores porque la anterior ocasión, con dos sanciones que estaban a punto de abandonar y creo que es una lección a extraer, no podemos celebrar hasta que termine el juego". 
A sabiendas de que esta serie podría definirse la pena patadas, algo que no él, porque confía en sus jugadores: "uno nunca espera para ir a sanciones, sino para terminar en tiempo regular; a veces no tienen ninguna alternativa y es necesario estar preparados; en el partido anterior estábamos preparados, lamentablemente el destino en nuestras manos; a veces, por los nervios o ansiedad por tener el título en la mano, pero no lograr este objetivo, y eso nos deja algo para esta última que esperamos ganar". 
Roman debe dejar de ser el técnico y segundo clasificado por primera vez saboreando la gloria que los títulos dan. 
