El Congreso apruebe la transposición de MIFID que tuvo lugar el 1 de noviembre
Junto a sus procedimientos parlamentarios, que terminaron con la votación parcial del Congreso sobre las enmiendas incorporadas al proyecto en el Senado, el Gobierno se ha sometido a la audiencia pública la regulación que desarrollará la nueva ley, con el objetivo de la fuerza que antes de finales de año.
Los representantes de diversos grupos de acuerdo en acentuar los esfuerzos hechos por los diputados y senadores para negociar y aceptar la mejor legislación para garantizar la protección de los inversores y regular en detalle la actividad de las organizaciones de modo que los mercados funcionen eficazmente.
La MiFID, que corrige el hecho de mercado de valores, tiene que ver con la modernización de los mercados financieros, al tiempo que refuerza la protección de los inversores, mejorando los poderes de la Comisión nacional de valores (cnmv) y la cooperación entre los diversos supervisores de la Unión Europea.
La nueva reglamentación concederán servicios consultivos financieros a las empresas especializadas así como a las personas naturales o legales, y crea un nuevo tipo de empresas de asesoría financiera (esis), las compañías de asesoría financiera (afi), que incluyen las empresas, los corredores, y las empresas de gestión de cartera.
Además, se amplía el número de sistemas disponibles para la ejecución de operaciones financieras, para incluir en la regulación son los mercados secundarios, los sistemas de comercio multilateral y los sistemas de órdenes, puedan competir con los gerentes de mercado de valores actuales.
La ley también exige que las empresas de servicios de inversión para descubrir el mercado los detalles clave de su perfil comercial, exposición de riesgo y formas de gestión del riesgo, y mantener un registro de todas sus operaciones para facilitar la supervisión por el cnmv.
En su paso por la Comisión de Asuntos Económicos del Congreso, se introdujeron varias modificaciones, sobre todo la deuda debe ser considerado como un instrumento financiero "complejo" debido a su alto riesgo para el inversor, que se ha demostrado por lo que sucedió con el alto riesgo de la hipoteca deudas (de).
Además, la transposición aprovechó la directiva para definir legalmente las funciones que pueden desarrollar graduados en la economía y las finanzas en 30 años después de la aprobación del decreto en 1977, que delimita las funciones profesionales reservadas a los profesionales.
Por su parte, el Senado promovió la creación de nuevas funciones en el sector financiero, como el asesor financiero, que trabajará de alquiler o recompensa, y no requiere la aprobación de la SEC y serán capaces de ofrecer sus servicios y el corretaje de productos de comercialización a clientes en varias empresas de inversión al mismo tiempo.
