Capital político: el protector húngaro ha aumentado el nivel de riesgo
Las acciones por la Guardia húngara, establecido en agosto con la ayuda del Movimiento para una Hungría ha levantado el nivel de riesgo político de Hungría y de toda la región de una serie de aspectos, según el análisis de riesgo de división de capital político.
La entidad de investigación publicó un "aviso de riesgo", escribe: las acciones de la guardia húngara provocan un riesgo político que excede "que las tensiones étnicas ya existentes entre los gitanos y los residentes de Hungría podrían calentar a niveles tóxicos tan pronto como el a corto plazo, llevando a los conflictos étnicos que podrían convertir violento".
La principal razón de ello es que la estrategia política de la guardia húngara parece estar destinadas a provocar la acción de esta naturaleza, la institución de investigación.
Este es el resultado de una de las más graves fracasos de Hungría actores políticos: "los actores principales en la vida pública se convirtió en el debate público de cuestiones de Roma a representantes de las fuerzas políticas radicales y extremistas, que han construido una estrategia política de diferencias".
Esto, capital político cree, ha intensificado el problema, dejando imposible cualquier diálogo normal, reforzando a los extremistas y aumentando la probabilidad de que los conflictos violentos ocurrirá.
Además, el Instituto de Investigación cree que la amplia atención de los medios de comunicación interna e internacional a acciones húngaras de guardia "ha perjudicado considerablemente la imagen internacional de Hungría, en particular en cuanto a la confianza en la estabilidad del país y en la sofisticación de su democracia".
Indican que el aumento de la publicidad y el impulso dado a la reorganización de los grupos radicales y de extrema derecha en la partida de Hungría en el otoño de 2006 han formado parte de la razón una serie de organizaciones que se llaman las alianzas nacionales de defensa propia fueron establecidas desde el verano de 2007.
"el rasgo común de estos grupos es que se llaman organizaciones cívicas declaran abiertamente que están preparando a sus miembros para defensivo - incluso armados - tareas (citando la dirección de desastre, la defensa nacional, la aplicación de la ley) declarando que la policía y las fuerzas armadas, en otras palabras, el Gobierno, es inadecuado para el papel capital político añade:".
Señalaron que todas estas medidas se han hecho dentro de una configuración que se basa en la sociedad y humor para encubrir varias ambiciones políticas bajo una capa de acción cívica.
En otras palabras, su énfasis en la naturaleza cívica de sus acciones y su elección de la asociación como su forma de organización no es solamente ardides para esquivar escollos legales a la inscripción con los tribunales, pero también son parte de una estrategia política.
Según el análisis, la actividad de la guardia húngara aumenta el riesgo de perjudicar nuestras relaciones con nuestros vecinos, también.
"en los últimos meses varios de los vecinos de Hungría han citado la guardia húngara como un peligro potencial, los actores políticos entre algunos de estos vecinos se han referido al establecimiento de la guardia húngara como un argumento para justificar sus propias políticas'.
Todos estos factores influyen en la estabilidad política de la región, "suma.
El Instituto de Investigación se observa que el establecimiento de la guardia húngara no es un fenómeno único en Europa Central y Oriental, y como tal aumenta el riesgo político para la totalidad de la región.
Observa que la operación de la guardia húngara es similar a la de la Guardia Nacional búlgara, establecido en agosto de 2007 por la extrema derecha de la Unión nacional búlgaro. (bnu).
Los conflictos serios que estallaron entre Roma y quienes no lo son en Sofía (krasna polyana) estaban detrás del establecimiento de la guardia búlgara.
Bnu sacaba provecho de las perturbaciones para establecer la guardia, afirmando que el objetivo de la organización haya sido "nacional".
Se argumentó que durante los últimos 17 años Bulgaria había sido objeto de "terror gitano", en la que el Gobierno fue impotente e indiferente y capital político eminente.
La iniciativa provocó un debate acalorado entre el público búlgaro, añadió.
Una señal de que el riesgo de conflicto étnico ha aumentado, los analistas escribió, es que algunas organizaciones de Roma en Bulgaria han anunciado planes de crear una guardia de su propio como fuerza de resistencia.
Desde la guardia húngaro ha actuado hasta ahora bastante similar a la Guardia Nacional búlgara, es muy posible que la Comunidad de Roma de Hungría podría responder a la amenaza organizando su propia defensa propia, escribió el capital político en la advertencia del riesgo.
Gerente de investigación de capital político Atila respondió a una pregunta de la agencia de noticias húngara al decir que el análisis de riesgo fue una de las actividades principales del Instituto de Investigación.
Cada año, decía, publican análisis de riesgo y si se descubren algún factor que podría cambiar, la opinión pública se notifican publicando un aviso de riesgo, como han hecho ahora.
