Las esperanzas que alimentadas tasas de incremento de los mercados de valores
Las partes saltaron a ambos lados del Atlántico ayer después de que el mercado espera que la Reserva Federal trate con más calma condiciones de crédito de los tipos de interés se aumentaran calmando observaciones del Vicepresidente del Banco Central estadounidense.
Las bolsas se levantaron en Londres, Nueva York y a través de Europa después de Donald kohn, 2 a Ben bernanke, el Presidente del FED, dijo que los políticos deben ser "flexibles y pragmático" respondiendo a la tensión en los mercados financieros.
En un esfuerzo claro para tranquilizar a los mercados señales de tensiones entre créditos, Sr. kohn dijo que las recientes turbulencias "había invertido en parte algunas de las mejoras en el funcionamiento del mercado sobre la última parte de septiembre y octubre".
Si la turbulencia elevada persiste, aumentaría la posibilidad de más lejana en condiciones financieras para las familias y las empresas, dijo.
Los inversionistas tomaron los comentarios como una señal de que el FED se preparan para actuar con nuevas inyecciones de capital en los mercados de los Estados Unidos, y el mayor de los tipos de interés, para estabilizar las condiciones del crédito.
Los comentarios también contribuyó a calmar Wall Street entre más malas noticias en la economía de EEUU, como nos acaba de casas de un registro bajo en octubre.
Las consecuencias de la confusión financiera fue acentuada por un anuncio del oso stearns, el Banco de Inversiones que cortará 650 puestos de trabajo, o 4 por ciento de su fuerza de trabajo, en una serie de la reducción de los costes para compensar pérdidas cuantiosas de sus apuestas que pierden en los Estados Unidos prestan en casa el sector.
Sólo el 20 de esos puestos se van en Londres, donde el Banco emplea a las personas.
En Nueva York, el Dow Jones saltado por los puntos 331 o el por ciento, cerrar en mientras el índice de S & P 500 se elevó por ciento.
En Londres, el índice FTSE 100 puntos se o el por ciento, cerrar en agregar más de 39 millones de libras esterlinas al valor de compañías de Gran Bretaña.
El índice DAX de Alemania se elevó por ciento, y Francia estaba encima de 2,3 por ciento.
Anteriormente, el de la tensión de crédito en los mercados después de que la demanda fuerte en una subasta de fondos por el Banco Central Europeo, los bancos comerciales prestados a Europa en un 4,7 por ciento pesado, la tasa más alta desde abril de 2001.
La presión en el Banco de Inglaterra para seguir el FED y el BCE y inyectar fondos adicionales en los mercados de dinero en Londres montado como de crédito de tres meses "," para los tipos entre los bancos británicos empujados a su alto desde finales de septiembre, en el 6,59 por ciento, después de una subida constante desde el 12 de noviembre.
