Environmin y seis por ciento de Hungría
El Ministro del medio ambiente, del ha dicho de que las reuniones planas profesionales en cuestiones de clima internacional se terminarán el martes, la conferencia misma abre oficialmente el miércoles, cuando los Ministros llevar el asunto.
Los profesionales y los políticos de los países 192 duramente para hablar de la hoja de ruta que se centra en los esfuerzos por reducir las emisiones de gas de efecto invernadero después de 2012, cuando expira el Protocolo de Kyoto.
En la actualidad, el desarrollo y las naciones desarrolladas en medio de una disputa acalorada.
Los Estados Unidos ha hecho saber que no está dispuesto a negociar números exactos aunque no se oponen a aceptar un porcentaje de reducción de los gases de efecto invernadero de aquí a 2020 cuando en comparación con 1990.
Otra gran cuestión en la Conferencia es si los países desarrollados están preparados no sólo a reducir sus emisiones sino también para ofrecer ayuda técnica y financiera a los países que lo necesitan.
Un acuerdo alcanzado estaba en el apoyo a los países en desarrollo.
Un Consejo se manejan la financiación para esto, que se establece en el Protocolo de Kyoto, y probablemente trabajar en el fondo para el medio ambiente mundial de las Naciones Unidas (gef), escribe la publicación de la zona és ganancia.
El seis por ciento de Hungría
Representación de Hungría, el Ministro de Medio Ambiente de la UE está dispuesta a apoyar los esfuerzos de bandera para conservar su papel en el esfuerzo global de la protección del clima y promover un nuevo acuerdo internacional, se alcanzará antes de 2009.
Reconoce que la UE ha de sus vistas en el 20 por ciento de las emisiones de gases de invernadero para el año 2020 en comparación con 1990, si el "es el acuerdo alcanzado o no, y está dispuesta a cortar el 30 por ciento mayor que si las otras regiones del mundo y los países en desarrollo están también dispuestos a aceptar las obligaciones a la extensión de sus capacidades y de sus responsabilidades.
Dicho de que en 1997, los países que se adhieren al Protocolo de Kyoto habían concentrado en una reducción del 5,2% de las emisiones totales. Dentro de ese grupo, la UE de 15 miembros acordaron un descenso del 8 por ciento.
Hungría acordó reducir sus emisiones de gas de efecto invernadero por 6 por ciento en comparación 1985-1987, un objetivo que piensa encontrar, dijo el comunicado de prensa del Ministerio de Medio Ambiente.
Lo que está en juego en Bali son altas, para un acuerdo internacional a largo plazo en la política de clima tiene que estar en secreto dentro de dos años o seguramente no podrá entrar en vigor en 2012.. si esto sucede, las promesas hechas durante la validez del Protocolo de Kyoto no se siguió inmediatamente por otro régimen, la necesidad de que las Naciones Unidas ganando el cuerpo científico, el panel intergubernamental sobre cambio climático - el ha señalado en su último informe.
El resultado podría ser una demora en la reducción de las emisiones, que pondría la tierra en un cierto rumbo hacia una media de levantamiento de temperatura de 2 grados centígrados. Si eso sucede, los científicos dicen que las consecuencias serían terribles e irreversible.
