El geriatra afirma que las muertes fueron causadas por "falta de medios" 
Los propietarios del centro de Olot no se descarta que su asistente mató a más de 11 personas mayores 
Los responsables de la geriatría del hospital de La Caridad de Olot (Gerona) ofreció una conferencia de prensa ayer en el fin de subrayar el daño que ha causado a la institución de la conducta criminal de Joan Vila Dilmé, la enfermera que si bien mataron al menos a once personas mayores las personas que había bajo vigilancia. 
El director de la residencia, Joan Sala, se presentó acompañado por el abogado del centro, el abogado Joan Canadá, y anunció que "la intención de La Caridad que echar la culpa a la persona responsable de las muertes, pero" la legalidad y las fuerzas de la responsabilidad que nos asumir la situación procesal de los derechos civiles a los responsables. " 
Y que, además de la pérdida de prestigio social que la organización puede encontrar por no haber detectado a tiempo las actividades delictivas de la atalaya, la gran amenaza para la Caritat ahora toma la forma de una indemnización sustancial que ya está calculada por los representantes legales de los familiares de las víctimas. 
Joan Vila Dilmé ha confesado que el primer crimen se remonta a agosto de 2009 y que desde entonces no dejó de matar. 
El juez ya se ha mencionado en el documento que ordenó la exhumación de ocho cuerpos - los pacientes de edad geriátrica del hospital quien se sospecha que en muchos casos ningún médico exploró personalmente los cadáveres, pero, teniendo en cuenta la edad y las patologías de los pacientes, el procedimiento fue realizado por teléfono. 
La Caridad, a través de su director, totalmente negado tal fin ayer y dijo que "la falta de medidas no podría haber sido en cualquier momento la causa de lo que había sucedido". 
El abogado de La Caridad agregó que "en la causa no hay indicios de que ha habido una acción imprudente por parte de cualquier otra persona que no es el culpable". 
El bautizado como "Ángel de la Muerte", confesó 11 asesinatos al día antes de ayer y detallada que cometió el primer crimen el 29 de agosto de 2009 y un mes y medio después, mató a otra abuela. 
En este caso, una sobredosis de insulina le trajo la muerte, a diferencia del primer crimen que cometió con una mezcla de pastillas sedantes. 
El director de la Caritat, dice que es complicado de controlar que el personal del centro tienen acceso a los medicamentos. 
La sobredosis de insulina y el cóctel de sedantes habría sido el mecanismo utilizado en seis de los nueve crímenes que la enfermera, en su afán de aliviar el sufrimiento de los pacientes, utilizados o matarlos. 
Pero las pruebas que se están llevando a cabo en el laboratorio tendrá que aclarar si Vila no está mintiendo y trató de asegurar a sus primeras víctimas de una muerte menos cruel o si, por el contrario, los quemó internos, dándoles la lejía como ya confesó que había hecho con las tres mujeres que murieron entre el 12 y el 17 de octubre. 
En La Caridad no dan credibilidad a la aparición de la guardia, ni el número de asesinatos confesados, que no refutan ser superior, y justifica su actitud en las diferentes versiones que Vila ha dado en sus visitas a la corte y el disparate de cambiar su método de matar después de haber cometido con éxito, ocho asesinatos. 
Es por eso que dicen que se ponen a disposición de la justicia para aclarar el alcance de este evento. 
