La CECA descarta una segunda ola de grandes fusiones en las cajas de ahorro 
El jefe de la dirección general de la CECA, José Antonio Olavarrieta, descartó ayer que una gran ola de fusiones de cajas de ahorro se va a tener lugar, e insistió una vez más en la rapidez con que se realiza la reconstrucción del sector hizo. 
Cuando el proceso de concentración de las cajas de ahorros españoles comenzaron, el había varias organizaciones que aseguró que no participaría en esta primera etapa y que se espera que la segunda ronda. 
Sin embargo, el jefe de una dirección general de la Confederación Española de Cajas de Ahorros (CECA), José Antonio Olavarrieta, descartó ayer que esta nueva oleada de operaciones va a tener lugar. 
Creo que la mayor parte de las fusiones se ha producido la incorporación de Cajasol al grupo de la Banca Cívica no puede ser llamado una segunda vuelta, hay ajustes solamente. 
"La mayor parte está completamente hecho, tal vez en lugar de 17 que podría haber 13 o 14, pero todos los grandes procesos se han realizado bajo la supervisión del Banco de España, que ha colaborado muchísimo con este asunto", señaló el gerente. 
En declaraciones durante un desayuno de la Asociación de Gerente y Ejecutivos de Aragón (ADEA), Olavarrieta ha puesto de manifiesto que el proceso de concentración se lleva a cabo "con la mayor velocidad posible, y debemos estar muy satisfechos de cómo sucede esto en los términos que en el tiempo, no ahora, fueron marcados en los planes de negocios con el Banco de España ", enfatizó. 
Para ir de 45 cajas de ahorro con un promedio de 28.500 millones de volumen de activos al 17 con 75.500 millones es un proceso que no tiene parangón en la historia, lo que reduce el número de organizaciones a un 62% por lo que son mucho más grandes para cumplir con Basilea, subrayó. 
Olavarrieta reconoció que hay "una serie de opiniones más bien pesimista sobre la lentitud del proceso" que demuestra "una falta de seriedad y de la razón", porque "lo que el Banco de España hace es recordar que tenemos que cumplir con el plazo antes del final del año. " 
El jefe de la dirección general de la CECA, José Antonio Olavarrieta, aseguró ayer que España tiene el sistema financiero más riguroso de toda Europa y "probablemente" de todo el mundo, y atribuyó a los que ponen en tela de juicio la "falta de conocimiento. " 
El gerente puso de manifiesto que, dentro de la coyuntura económica actual, "podemos estar muy relajado" con la situación de las entidades financieras y las cajas de ahorros, un sistema que ha llevado a cabo una "muy importante" proceso de concentración y que "va con el más grande posible velocidad. " 
También recordó que el banco español salió muy bien con las pruebas de estrés que el BCE hizo en julio. 
