Con la literatura que puede poner su dedo en la llaga 
La segunda ronda de los placeres de la lengua fue un paseo durante el cual los participantes promulgó la narración 
Eso de sexo en el lenguaje Entiendo eso, pero ... el dedo en la llaga? ¿Qué se espera hacer?, Preguntó la escritora Luisa Valenzuela invitó invitado a abrir la segunda ronda de los placeres de la lengua, un evento que celebra la literatura en español y que esta vez utiliza el subtítulo de su pregunta (de otra forma la mesa redonda fue dedicado al sexo en la lengua, explicó). 
El dedo en la llaga ... "Nos pone en una situación difícil", dijo con dulzura hacia fuera el escritor argentino al público, principalmente de los jóvenes, que se reunieron en la Feria Internacional del Libro de Guadalajara (FIL) para escuchar a esta mesa redonda moderada por Marisol Shultz y participó Valenzuela, Sergio Ramírez, Mayra Montero y Luis García Montero, participaron. 
Luisa Valenzuela leer un texto que dedicó a Gonzalo Celorio y que Shultz definiría más tarde como una gran historia, con Luisa en primera persona como protagonista que en la búsqueda del conocimiento conocido como "ella", va de médico en médico, de quien no obtener respuestas, aunque se queda atascado en el mismo hilo narrativo. 
Ella se va al médico convencido: "tal vez la paciencia no es mi fuerte, tal vez es mi dolor". 
Al final, después de un enfoque frustrante con el médico que el trauma que aclara que dolor no es un término científico, es el psicoanalista que desentraña el misterio: ". El dolor es lo real abierta, lo simbólico es la cicatriz" 
El protagonista suspiró aliviado y concluyó que "en la llaga Sólo he podido saber que la cosa real está abierto y que no existe", pero convencido de que los placeres y las trampas del lenguaje tiene que ser mezclado. 
Valenzuela, el escritor, juega con ambas. 
El nicaragüense Sergio Ramírez también mostraron un relato delicioso que tituló Elogio de la invención, donde el dedo en la llaga no se nombra, pero es descubierto. 
En términos generales, del realismo mágico, que cuenta la historia de una bruja famosa, que por tocar las nubes, trajo de vuelta los hombres que habían ido lejos o reparar las virtudes perdidas por una criada, la narración que se convirtió en hablar de América, una gran novela que no faltaron desde el principio su propia cronistas que lo dijo y mencionó Bernal Díaz del Castillo, quien critica los excesos de las cosas que dijo a los capitanes conquistadores. 
Cervantes que nos inventó a todos (los escritores) se rió de los testigos falsos que aparecieron en las historias presentadas como reales, pero de otra manera nunca habría dicho la historia de América con la imaginación que carecen de la timidez. 
No obstante, hizo hincapié en "los locos y mentirosos son los que mejor imaginar cosas", y es donde la realidad y la mentira se mezclan, donde se sabe si lo narrado pertenece a un lado u otro, donde la literatura de ficción alcanza su apogeo. 
De hecho, es llamado "la tradición de Cervantes. 
"Por su filosofía de: somos lo que dijo de nosotros". 
En cuanto a ella, la escritora Mayra Montero vio y aplaudió la variedad de interpretaciones que la invitación de las causas de la FIL, con la mesa redonda El dedo en la llaga. 
El cubano-Puerto Rico señaló su propia hacia el gran dolor de la violencia social que atraviesa su país - y divide a América Latina, producto de las disputas sobre el tráfico y venta de drogas. 
Creo que la buena literatura, la buena poesía, buenas canciones encierran un compromiso tácito de que, por supuesto, no es premeditado, indicó, tras señalar que la realidad de la literatura es la comunicación y la dimensión del compromiso que se establece entre autor y lectores, y que es una "reacción química" de este último. 
La noche fue cerrada por el poeta español Luis García Montero, cuya intervención también puso énfasis "que el dedo en la llaga del escritor comprometido a escribir". 
Consideró que en un mundo que vive en un apuro, también en las costumbres intelectual y el control de la conciencia que tiene efectos en los dogmatismos, sin olvidar "que detrás de cada afirmación hay un pequeño no y detrás de cada una negación que es pequeño sí". 
"Con el fin de ser dueños de nuestro pensamiento y la realidad hay que aclarar, y aclarar a menudo significa poner el dedo en la llaga y molestar a las personas que están pensando mucho más cómodo sobre la historieta, en blanco y negro, en las ideas establecidas, sin una sombra y también molesta a los poderes que prefieren un mundo en blanco y negro ", dijo, invitando a recuperar el sentido de la escritura. 
