IP pide resultados del Congreso 
Eduardo Dávalos, presidente de la CCA, propuso que los diputados asuman la gran responsabilidad de ser un ejemplo para un Sinaloa mejor los diversos desafíos que enfrenta. 
La Legislatura de obras decente y libre de los acuerdos entre las partes y el Ejecutivo del Estado está siendo demandado por el sector empresarial de Mazatlán, porque hay un convulsionado Sinaloa que se enfrenta a grandes problemas. 
Ayer, el legislador 60 fue votado, integrado por siete fuerzas políticas, 19 diputados del PRI, 13 del PAN, tres del Partido Nueva Alianza, dos del PRD, uno del PT, uno de los de Convergencia y uno más de el PVEM, es decir, un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso de la S-estado en el que se menciona que vienen a cumplir una gestión limpia de compromiso con la sociedad y los diferentes sectores que requieren un trabajo legislativo responsable. 
Eduardo Dávalos Zamora, presidente del Consejo Coordinador Empresarial, propuso que la acaba de sacar 40 diputados del Congreso del Estado asume la gran responsabilidad de ser un ejemplo para un Sinaloa mejor los diversos desafíos que enfrenta. 
Esperamos que los diputados realmente ejercer su derecho, libre de los acuerdos entre las partes, ya que es una costumbre de hacer acuerdos con el fin de velar por sus propios intereses y se convierten en un personaje en un carnaval de los gobernadores y líderes de las fracciones parlamentarias . 
Por eso habló de la certificación de las compromiso a fin de establecer los puentes necesarios que podrían ayudar al gobernador a seguir adelante. 
Esperamos que vengan a hacer un trabajo digno y sobre todo comprometida con la sociedad y los sectores, porque los habitantes de Sinaloa fueron los que les dieron el voto de confianza en las últimas elecciones. 
José Ramón Manguart Sánchez, presidente de la Asociación de Hoteles Tres Islas, consideró que uno de los mayores desafíos para los 40 representantes populares es el de empujar y sumando fuerzas en la búsqueda del crecimiento económico del Estado, porque hoy en día la situación económica es muy complicado. 
Lo más importante es impulsar el crecimiento económico, que genera incentivos para la inversión e infraestructura y que de alguna manera se forma una nueva generación de puestos de trabajo. 
En cuanto a la actividad turística, exigió que los nuevos legisladores dar el peso revisada en el presupuesto del Estado con el fin de fortalecer la Secretaría de Turismo. 
Como he entendido este es el segundo departamento del estado con menos presupuestos y es incongruente una importante actividad económica y la generación de divisas y la inversión y que compite directamente con la agroindustria. 
Aparte de los recursos que requieren el etiquetado de los proyectos turísticos detonantes que ayudan a dar seguridad al Estado y actualizar la Ley de Alcoholes que no ha sido capaz de resolver en las legislaturas anteriores. 
