Los fiscales no cobrará el Senador Ensign 
Fiscales del Departamento de Justicia ha desactivado el senador John Ensign de las denuncias penales derivadas de su relación con un ex asesor de campaña y sus esfuerzos para garantizar el trabajo de cabildeo para el marido de la mujer, los abogados del senador anunció el miércoles. 
La decisión pone fin a la amenaza legal más grave que enfrenta el Sr. Ensign, republicano de Nevada que fue considerado un posible candidato presidencial republicano en 2012 hasta que el escándalo por su relación fue noticia nacional el año pasado y dañó su carrera. 
la oficina del Sr. Ensign dijo que estaba "ciertamente complacido" por la decisión, que siguió a una investigación de un año. 
El senador aún podría enfrentar una acción disciplinaria por el comité de ética del Senado. 
los abogados del Sr. Ensign dijo que el Departamento de Justicia "nos informó que el Senador Ensign ya no es un objetivo de su investigación y que no tiene planes de traer todos los cargos en su contra en este asunto". 
El Departamento de Justicia se negó a comentar sobre el caso. 
El anuncio se produjo como una especie de sorpresa para muchos abogados de la ética fuera del Departamento de Justicia, que dice que parece ser una evidencia significativa para indicar que el señor alférez pudo haber conspirado para violar una prohibición penal en cabildeo federal. 
Entrevistas, correo electrónico y otros documentos de la primera comunicación en octubre de 2009 en The New York Times indicó que el señor alférez había ayudado a Douglas Hampton, que fue uno de sus ayudantes, el trabajo seguro de cabildeo lucrativo para ganar el silencio del señor Hampton y su esposa , Cynthia, sobre el asunto del senador con ella. 
La señora Hampton, una vez sirvió como tesorero de una campaña de Alférez. 
El Sr. Ensign en contacto con un número de partidarios políticos en busca de trabajo para el señor Hampton y luego defendió en su nombre después de que había contratado el señor Hampton cabildear a su favor, según los documentos y entrevistas. 
Porque el señor Hampton había sido recientemente un asesor del Sr. Ensign, fue prohibido por la ley de lobby a su antiguo empleador o el Senado en su totalidad durante un año. 
expertos en ética, dijo el inusual acuerdo entre el Sr. Alférez y Hampton señor, que eran amigos cercanos antes de que el asunto, se presentó en contra de la denominada prohibición de gira de cabildeo de la puerta. 
Desde la evidencia de que se haya hecho pública, "no parecía ser un caso prima facie de una conspiración para violar, y la violación sustancial del estatuto puerta giratoria", dijo Stanley Brand, abogado de Washington que se especializa en la defensa de los clientes investigados por el gobierno . 
Mientras que funcionarios del Departamento de Justicia se negó a explicar el razonamiento detrás de la decisión en el caso de Ensign, el señor Brand y otros abogados de la ética, dijo el departamento parecía desconfiar de tomar sobre los procesos políticos después de una serie de reveses de alto perfil para su sección de integridad pública, incluida la decisión del año pasado a caer la acusación contra el ex senador Ted Stevens, en medio de acusaciones de mala conducta del fiscal. 
Los fiscales federales "están claramente Gun Shy", dijo Melanie Sloan, directora ejecutiva de Ciudadanos por la Responsabilidad y la Ética en Washington, un grupo de defensa que llevó a varias denuncias contra el Sr. Alférez en el caso. 
"Esto básicamente dice que los funcionarios gubernamentales de alto rango pueden ahora asumir las leyes no se aplican a ellos", añadió. 
Paul Coggins, abogado principal del Sr. Ensign, dijo en una entrevista que recibió una llamada telefónica de un fiscal del Departamento de Justicia el lunes y un seguimiento al día siguiente, diciéndole que el departamento no estaba buscando cargos contra su cliente. 
el equipo del Sr. Ensign defensa había estado cooperando con los fiscales para tratar de persuadirlos de que el senador, como su oficina reiteró en un comunicado el miércoles, "actuó de acuerdo con la ley". 
Coggins se negó a explicar los argumentos jurídicos que hizo a los fiscales. 
"No me siento cómodo entrar en los detalles de mis conversaciones con el Departamento de Justicia, excepto para decir que creemos que tomó la decisión correcta", dijo. 
El mes pasado, la Comisión Federal Electoral decidió abandonar una investigación sobre una queja separada por el grupo de la ética basada en que un pago de 96.000 dólares de sus padres el señor Alférez de los Hamptons violado la ley electoral federal. 
La comisión electoral dijo que no tenía suficiente evidencia para probar que el dinero era otra cosa que un regalo. 
Una empresa para la que el Sr. Alférez ayudó al Sr. Hampton encontrar un trabajo de cabildeo se NV Energy, una importante empresa de Nevada que había apoyado durante mucho tiempo el senador. 
Un correo electrónico enviado en diciembre de 2008 mostró que después que la compañía trajo el señor Hampton como cabildero, jefe el Sr. Alférez de personal, Juan López, se comunicó con el señor Hampton y le dijo que estaba "golpeando" el Departamento del Interior sobre una cuestión en litigio. 
El Sr. Ensign también asistió a un almuerzo con el señor Hampton y otro cliente Nevada, Allegiant Air, y llamó a la secretaria de transporte para establecer una reunión en nombre de la aerolínea después de que había contratado el señor Hampton hacer trabajo de lobby. 
Cuando la noticia de la primera aventura surgió el año pasado, el Sr. Alférez pidió disculpas a sus electores y renunció a su posición como el líder republicano de cuarto rango en el Senado. 
Después de mantener un perfil bajo durante muchos meses, el Sr. Ensign dijo a la prensa hace dos semanas que planeaba postularse para un tercer mandato en el Senado. 
Al anunciar que el señor alférez ya no era el blanco de una investigación criminal, su portavoz, Jennifer Cooper, dijo el senador esperaba que el comité de ética antes que seguir el ejemplo del Departamento de Justicia y poner fin a su investigación. 
"El Senador Ensign espera continuar su trabajo en nombre del pueblo de Nevada", dijo. 
