Los delitos antimusulmanes han aumentado en el 50 %
Entre 2009 y 2010, los delitos antimusulmanes aumentan en casi el 50 %, mientras durante el mismo período otras formas de la violencia racial y religiosa se habían caído ligeramente, o no habían cambiado, según la estadística de Brigada de Investigación Criminal publicada el lunes.
Según estas cifras, el número total de casos de la violencia contra Musulmanes se movió de 107 en 2009 a 160 en 2010, igual a un aumento del 49 %, en comparación con un aumento del 13 % de casos de la violencia contra católicos, una caída del 4 % de ataques contra judíos y un aumento global del 14 % en delitos antireligiosos.
El número global de delitos de odio aumentó muy ligeramente a 6628 casos, de los cuales el 47,3 % fue motivado por diferencias raciales y el 20 % por diferencias religiosas, según la Brigada de Investigación Criminal.
"Después de una disminución en 2009, es inquietante para ver estos delitos aumentar otra vez, acentuó los derechos de la organización de hombre, Derechos humanos Primero, "el aumento de casos de la violencia antimusulmana es particularmente significativo," añadió la organización en un comunicado.
"Los derechos humanos Primero han subrayado mucho tiempo que los actos de la violencia contra Musulmanes, así como todas las formas del delito de odio, deben ser considerados como violaciones serias de derechos humanos," añade uno de los gerentes de la organización, Paul Legendre.
"El gobierno americano puede y debe hacer más para tratar con su abuso, él añade, juzgando que esto podría ser debido a la edición de informes de policía sobre delitos de odio."
"Delito de odio" en la Ley federal, es una herencia a partir del período de lucha por derechos civiles.
Esta legislación fue pasada después de la muerte de Martin Luther King para castigar actos de la violencia unida a raza, color de piel, religión, origen y ahora orientación sexual.
