Las "personas enojadas" desafían las autoridades en Nueva York
Cientos de protestantes se apiñaban por ahí delante de Zuccotti square para acampar.
Una parte de los protestantes escuchó el pedido de desahucio y se movió a un parque cercano.
Los miembros del movimiento Ocupan Wall Street desafiada el martes las autoridades de Nueva York tratando de entrar otra vez, bajo la protección de una orden judicial, en el Cuadrado de Manhattan donde ellos fueron evacuados al amanecer tratando de ocupar otro parque de la Manzana Grande.
Cientos de protestantes se apiñaron alrededor de Zuccotti square, donde ellos quisieron entrar gracias a una orden judicial que permite "que las personas enojadas" pongan el sitio en espera, mientras otra parte del movimiento respondió al desahucio ocupando un parque al norte la ciudad donde allí han sido hechos detenciones adicionales.
"Nuestra idea consiste en que si el tribunal no permite que nosotros volvamos para acampar en el cuadrado, acamparemos en otra parte y seguiremos la batalla legal para volver a Zuccotti, y por sentadas pacíficas y demostraciones," dijo uno de los portavoces del movimiento "Ocupa Wall Street," Mark Bray.
El rebuzno explicó que la respuesta de las "personas enojadas" a la evacuación del campo publicado personalmente por el alcalde de Nueva York, Michael Bloomberg, vino al tribunal, donde el Juez Lucy Billings publicó un pedido que prohíbe la evacuación forzada del lugar y permitiendo a los demostradores permanecer acampó.
Además, las "personas enojadas" siguieron a la ocupación de un nuevo parque localizado en la confluencia del centro de la cuidad Canal Street y Avenida 6, cerca de la entrada al Túnel de Holanda, que une Nueva York y Nueva Jersey, poseído por la parroquia de la iglesia de Trinidad.
Al menos durante una hora ellos eran capaces de ocupar el lugar, pero entonces la policía vino y se puso a detener a algunos protestantes, aunque el Rebuzno no pudiera confirmar el número preciso, diciendo Efe que él vio a varios periodistas que también fueron esposados.
La organización asegura que hay varios cientos de personas acampados a aquel punto, donde una delegación de líderes religiosos ha ido ya para mostrar su apoyo a los miembros del movimiento que trata de mediar con la policía.
Mientras tanto, Zuccotti square, que es un sitio privado, permanece la espera cerrada de una audiencia de tribunal programada para este martes en el cual examinar la legalidad de la evacuación de esta mañana.
Algunos protestantes movidos allí llevaban y distribuían entonces copias de aquella orden judicial y hasta ellos dieron estas copias a oficiales que guardan el lugar, que llevó "a algunas pequeñas confrontaciones," dijo el Rebuzno, quién afirmó que algunos oficiales pegados los demostradores.
La orden judicial prohíbe las autoridades para evacuar a los miembros de Ocupan Wall Street y hacen cumplir "leyes que fueron publicadas después del principio de la ocupación o prohibir a demostradores recobran el acceso al parque con tiendas y otra propiedad usada antes."
El alcalde Bloomberg dijo a reporteros que, debido a aquella orden judicial, la ciudad había suspendido el reabrimiento del lugar público y los protestantes fueron informados, sin embargo, que las leyes locales no permiten que ellos instalen de nuevo con tiendas que acampan y sacos de dormir.
El concejal personalmente defendió la evacuación de Zuccotti square realizada al amanecer, una operación en la cual aproximadamente 200 detenciones fueron hechas y esto fue decidido así porque los protestantes "violaban la ley."
Bloomberg dijo que dio el pedido de evacuar el cuadrado porque se hacía "un lugar donde la gente no vino a la protesta, pero violar la ley y, en algunos casos, hacer el daño a otros" como "Algunos negocios había recibido las amenazas y los vecinos temieron" por la calidad de vida."
"La evacuación de esta mañana era asquerosa y muestra que profundamente dentro de Bloomberg está más interesado en la conservación de los intereses financieros de trabajadores americanos," añadió el portavoz del movimiento, que acusó al alcalde "del desacato para la libertad de expresión."
Los responsables de "Ocupan Wall Street" también indicó que ellos tienen la intención de organizar "grandes hechos" para el jueves en la colaboración con organizaciones de comunidad y uniones, a fin de conmemorar los dos meses pasados de protestas, que comenzaron el 17 de septiembre.
