El tribunal valida "la transición de televisión digital" en México en 2015
El reemplazo de análogo con el digital es uno de los cambios más importantes que ha golpeado el mundo en años recientes
La Corte Suprema de Justicia (SCJ) rechazó las controversias constitucionales traídas por el Senado y Cámara de Representantes contra el decreto presidencial que presenta la llamada "transición de televisión digital" de 2021 a 2015, ya que los ocho votos tenían que invalidarlo no fueron obtenidos.
Una minoría de cuatro ministros, incluso el presidente del Tribunal, Juan Silva Meza, consideró que el presidente Felipe Calderon no excedió su autoridad publicando un decreto que detalla las acciones para tomar a fin de conseguir la transición a la televisión terrestre digital.
Con este resultado, la controversia constitucional promovida por el Senado, fue rechazado para no encontrar la mayoría calificada de ocho votos por el Tribunal para expresar una opinión sobre la constitucionalidad o no constitucionalidad del decreto, y esto permanece en vigor.
El proyecto de oración preparado por la Ministra Olga Sánchez Cordero, propuesta para declarar inconstitucional el decreto, porque la regulación de radio y materiales de televisión es un poder reservado según la ley para la Comisión de Telecomunicaciones federal (Cofetel), en la violación de los principios de subordinación jerárquica y reserva de la ley.
Sólo Zaldivar, Jorge Mario Pardo, Margarita Luna y Sánchez Cordero votaron por el proyecto.
Con este argumento, tanto el Senado como la Cámara de Autoridades promovieron dos controversias constitucionales para contradecir el decreto, y apoyar las reclamaciones, el ministro Sánchez Cordero suspendió la aplicación del decreto y todas las acciones estipuladas allí en cuanto a la transición digital.
En los ministros" que se encuentran allí también fue decidido para rechazar la reclamación archivada por la Cámara de Autoridades, sin firmar la discusión del proyecto, también responsable del ministro Sánchez Cordero.
En su discurso, el ministro dijo que no estuvo de acuerdo con los argumentos del proyecto en el sentido que el ejecutivo federal no puede estructurar por reglas generales las medidas para la administración pública para estar preparada.
"Tampoco considero que de ser hecho afectaría la autonomía del órgano regulador," y recordó que la planificación de políticas públicas en áreas estratégicas, como el sector de telecomunicaciones equivale al ejecutivo federal, que tiene un mandato constitucional, la dirección del estado.
El reemplazo de análogo al digital es uno de los cambios más importantes que han golpeado el mundo en años recientes, y causa una mejor utilización del espectro eléctrico por la radio, mejor señale la calidad y más canales.
Retrasando el cambio, él dijo, significaría retrasar las ventajas de digitalización, que implica una decisión de interés público, que no tiene sólo una dimensión técnica, "ya que esto cubre cuestiones de seguridad nacional y económicas, sociales, políticas."
Estas cuestiones, él dijo, "requiera que la operación del sistema entero establecido bajo el principio de la administración económica estatal, comprenda un grupo de poderes que la Constitución lleva al poder ejecutivo estatal."
Él recordó que un gran número de países alrededor del mundo ha completado ahora la transición digital, y lo ha hecho por el ejecutivo, a pesar de haberse especializado muy cuerpos técnicos.
Allí no puede ser concluido que el gobierno, publicando el decreto impugnado, que invade de cualquier modo el competencia del Congreso, proporciona en el área administrativa la observación de las leyes publicadas por la Legislatura, él dijo.
