Sindicato de trabajadores de apoyo Demandará Ciudad Sobre Despidos
La unión que representa cientos de escuela apoya a trabajadores que perdieron sus empleos el mes pasado planea demandar la ciudad el miércoles, afirmando que los despidos eran innecesarios y discriminatorios debido a su impacto desproporcionado a escuelas que sirven a estudiantes pobres.
El pleito es posiblemente la última arma disponible para la unión, Ayuntamiento 37, en su esfuerzo de invertir los despidos.
Seiscientos setenta y dos ayudantes escolares, coordinadores paternales y otros empleados que estaban entre la ciudad peor pagada perdieron sus empleos el 7 de octubre, en unos dirigentes sindicales de movimiento han descrito como el reembolso político para su respuesta negativa de dejar a la ciudad tener acceso a un fondo de asistencia médica dirigido por grupos de trabajo para cerrar su hueco de presupuesto la primavera pasada.
Las autoridades municipales han negado categóricamente aquella acusación.
En un Ayuntamiento que oye el mes pasado, el Canciller de Escuelas Dennis M. Walcott dijo que los despidos eran una parte del presupuesto en el cual ellos se despidieron en junio.
Un miembro de consejo disparó atrás, diciéndole que nada en el presupuesto especificó que los empleados de apoyo de escuela serían despedidos.
El Ayuntamiento 37 funcionarios dijeron que ellos archivaron un aviso de la reclamación, advirtiendo el Ministerio de Educación que sería demandado; esto creerá que una conferencia de prensa el miércoles anunciará la clasificación del pleito formalmente, en la Corte Suprema del Estado en Manhattan.
El pleito pondrá en una lista al Sr. Walcott y el Ministerio de Educación de la ciudad como demandados, y cuenta ocho puesto - de trabajadores como demandantes, todos ellos negros o mujeres de Latino, como eran la mayor parte de los ayudantes que perdieron sus empleos.
Elizabeth Thomas, una portavoz del Departamento Jurídico de la ciudad, dijo que la ciudad no había visto el pleito y por lo tanto no podía comentar sobre sus acusaciones específicas.
Según un esbozo de la queja obtenida por New York Times, la unión tiene zeroed en en el número de despidos en escuelas en partes pobres de la ciudad para apoyar una reclamación del tratamiento injusto, diciendo que las escuelas pobres perdieron a más ayudantes porque ellos habían sido crónicamente underfinanced.
Esto indica que mientras no había ningunos despidos a la Isla Staten y pocos despidos en escuelas en los Barrios este de Nueva York Superiores o TriBeCa, 17 ayudantes escolares perdieron sus empleos en el Distrito 23 en Brownsville, Brooklyn, y 46 fueron dejados entran en Distritos 8 y 9 en Bronx del sur.
Notar la pérdida de cinco de ocho ayudantes escolares empleados por la Escuela pública 36 en Harlem, donde el 68 por ciento de los estudiantes vivos en la pobreza, el pleito dice, "Esto no es una vecindad de padres adinerados que pueden financiar - levanta para arreglar los déficits de presupuesto."
P.S. 36 "s presupuesto fue cortado en el 3.26 por ciento este año, y también perdió el dinero cuando la ciudad cambió el modo que calcula la financiación suplementaria para cada pobres que las escuelas estudiantiles matriculan.
La unión también afirma que los principales de escuela secundaria pueden haber sido engañados por la lengua en una nota que autoriza el descarte de coordinadores paternales.
La nota usó la palabra "exceso" para describir la acción, aunque "el exceso" más comúnmente describa el acto de mover a un profesor de la nómina de una escuela en un fondo de trabajadores disponibles cuyos sueldos son pagados por la central.
"Sesenta y seis coordinadores paternales fueron despedidos," la queja preliminar dice, "y no simplemente excessed."
