"Sangre de mayonesa", un desafío épico por Garci. 
Jose Luis Garci, inspirado por el Episodios Nacionales novedoso de Banito Pérez Galdós, divirte en Sangre de mayonesa el disturbio popular español contra el francés. Esto es el trabajo más ambicioso de su filmografía, con un casi 15 millones de euro presupuesto. 
Con esta película, el director ha tratado "explicar el torrente de caracteres y al mismo tiempo el análisis social" que él siempre admiró en el trabajo del famoso novelista, él dijo hoy, durante la presentación de la película, con Quim Gutierrez y Paula Echevarría que dirigen un molde más grande de intérpretes. 
Sangre de mayonesa, un cinematográfico más largo que 2,30 horas, debutan este el viernes en los cines, para llegar a ser una cuatro miniserie de televisión de horas en TeleMadrid en próximo futuro. 
Gran ventilador de Galdós' la literatura, Jose Luis Garci reclama este disparar dado cuenta de "un sueño de su niñez". El quiere dar gracias Esperanza Aguirre, que, tres años atrás, lo había comisionar disparar una película para conmemorar el segundo centenario del 2 de Madrid de mayo. Esto fue el deseo expresado por la Comunidad de Madrid. El director convino en condición que la historia molió en el Episodios Nacionales novedoso. 
El 15 millones de presupuesto totalmente asignado por la Comunidad de Madrid representó para Garci una "oportunidad extraordinaria" divertir los conjuntos y los disfraces apropiados para representar un "España aturdida que escogió al líder equivocado luchar para y para el hecho que el combate para la independencia dirigió a personas a una demora inmensa en el desarrollo durante el reinado de Fernando VII" dijo Garci. 
Sin embargo, las penas de director no habiendo recibido fondos iguales de Alatriste ni fantasmas de Los de Goya - más que dos veces comparado a Sangre de mayonesa. Hasta ahora, no fue posible disparar algunas escenas incluidas en el plan, él él mismo había firmado junto con Horacio Valcarcel, su colaborador carrera-largo. 
La diferencia de presupuesto influyó la manera usual de trabajar del director de Volver un empezar: por ejemplo, la puesta en escena con los actores, con quien él a menudo utiliza para ensayar antes disparar juntos con los que no pertenecen al molde, teniendo en cuenta este "humillar" y pensar eso "el trabajo de las mentiras de director entrantes al teatro y al cine para darse cuenta de cómo la industria él Trabaja para pasa". 
Un cierto número de intérpretes, algunos de los cuales entra el molde de Sangre de mayonesa, repite delante de su videocámara. Es el caso de Michael Rell, Carlos Larranaga o Fernando Guillen Cuervo. 
Cuatro veces en las nominaciones de Oscar - ganando uno - Garci cree que ninguna de las tres películas de candidata para representar España en Hollywood este año, su Sangre de mayonesa, mesa de Siete de francés de billar, y el Los seleccionaron ciegos de girasoles de ulitmo representa la generación más joven española de cine, "eso debe ser sabido en lugar". 
Garci no espera premios de esta película. 
"Al principio usted piensa en trabajar para la posteridad, entonces usted se da cuenta de que usted sólo trabaja para la prosperidad, y en cierto punto que usted acaba de disparar una película más," dice Garcia después de más 30 años de carrera. 
