El élite en peligro 
El fenómeno ya se había manifestado un par de días apoyan con el voto en la Cámara de Representantes contra el plan de rescate de 700 mil millones dólares norteamericanos pasó la Casa Blanca: una porción significativa de norteamericanos fue, y todavía es, más interesado en castigar Wall Street que en guardar la economía. 
Una confirmación fue dada por New York Times cuando informó que la crisis actual causa una separación dentro del Partido republicano, siempre más dividido entre su alma vieja de Costa Este, modera, a favor de instituciones federales y las esferas empresariales, y su nueva alma, en lugar conservador, hostil a" ésos en Washington" y al mundo financiero, especialmente fuerte dentro del Central y el sur de estados. 
El alma, para ser exacto, que se ha hecho arrogantemente vivo con el voto mencionado inicialmente. 
El último es pero sólo un ejemplo de los cambios, de los cambios grandes, que el terremoto económico actual anuncia quizás o permite ser percibido: no sólo en Estados Unidos pero también en todo el Oeste y quizá no sólo aquí. 
En EEUU como en Europa que la crisis parece actuar como un catalizador para fenómenos que han estado en la incubación durante un tiempo y que en el nuevo clima se ha solidificado y por último viene a encender. 
El primer de estos fenómenos es el devolver reciente, el extraordinario relanza, de la estado-soberanía gemela de categoría en relación con un tipo de renacionalización de la economía. 
La crisis, de hecho, es una crisis para las instituciones financiero-bancarios que tienen, verdaderamente, corbatas fuertes con países extranjeros, pero con que trata sobre todo con los presupuestos de personas o familias que viven en una sola nación, en un solo estado. 
Esto crea inmediatamente un problema político para quienquiera que está en el gobierno: y eso es de cómo responder a las dificultades y las protestas de esas personas y esas familias eso, además, también forma el electorado. 
En otras palabras la crisis parece ser económicamente mundial pero políticamente es casi exclusivamente un problema nacional. 
El internacionalismo político parece ser substancialmente fuera de juego o no tener mucho en decir: la prueba clara de esto es dada por la Unión Europea eso, dividido como de costumbre entre los varios intereses y las estrategias diversas de estado, no puede decidir en un sendero político común. 
Y así que es del gobierno de cada solo Estado que toda espera para la intervención, se lanuears en paracaídas y relanza planes, nuevas reglas, y ayuda especialmente financiera: desde que eso cuando viene a derrotarlo es sólo los Estados que tienen recursos financieros, la masa de recursos financieros capaces de tratar y fijar cosas. 
Y ellos poseen igualmente los medios necesarios, y las razones legítimas para utilizarlos: dos recursos de valor inconmensurable, bajo ciertas circunstancias, de que probablemente ningún mercado y ninguna asociación internacional jamás podrían deshacerse de en una medida análoga. 
Este nuevo énfasis que la crisis coloca en el elemento statal-nacional es después de todo perfectamente afinada con la importancia creciente que los últimos desarrollos económicos tienden a atribuir a un coeficiente que muy es conectado de cerca a ese elemento: la territorialidad. 
Paradójicamente, de hecho, mientras tuvieron la convicción de que habíamos entrado el reinado de la web, de una tecnología cada vez más más sofisticado, del inmaterial, mientras tuvieron la convicción de que finanza globalizada fue destinada ya dominar el mundo, nosotros llegamos a ser de repente enterados que nuestro futuro tuvo en lugar para tratar en una moda creciente con esas cosas que son muy poco inmaterial como agua, las cosechas, el petróleo. 
Accidentalmente, todo es artículos que ciertamente pueden ser transportados de un lugar a otro pero en cualquier caso son referenciados una moda absoluta a un espacio bien definido, a un territorio. 
Para que quienquiera que se encuentre ser el soberano, tiene seguramente más tarjetas en su plataforma que quien no es, que quien sucede vivir en un lugar sin cosechas, engrasar, o regar. 
Llego a la segunda novedad que sin embargo predice una separación. 
Quienquiera que dice que el Territorio, el Estado, el Gobierno, implica inevitablemente la Política, y de ahí Liderazgo. 
En este sentido la crisis económica parece producir dos fenómenos convergentes. 
Por una parte el conocimiento de la necesidad objetiva para el liderazgo autoritario, la demanda para alguien que sabe cómo manejar la situación. 
Por otro lado una onda de descrédito para el liderazgo existente, un tipo económico, reveló para ser tan inadecuado y lleno de áreas grises. 
Y juntos algo jamás más profundo y en una cierta manera que perturba: un descrédito, una intolerancia, una imagen de insuficiencia, un sentido de la lejanía que tiende a implicar la clase gobernante entera de un número creciente de países Occidentales. 
Más bien, parece avanzar aún más en secciones vastas de la población la convicción que antes que sus acciones son las mismas ideas al el élite social arriba hasta ahora en favor, su manera de sentimiento y son, su cultura en todos significados aceptados de la palabra, para haber tenido su día, y siempre ser más extranjero a la opinión de la mayoría. 
Es decir, la llamada para comidas de liderazgo clandestinamente un movimiento ramificado pero poderoso de delegitimization de la clase directorial y de las estructuras políticas tradicionales, que manifiesto mismo en el repentino electoral" se rebela" o torsiones bruscas en los humors colectivos en estos últimos y últimos tiempos, de la subida conservadora en Austria – Baviera al desplome del consenso de trabajo en Gran Bretaña, a la rebelión de los congresistas norteamericanos Contra Bush (y quizás aún la victoria del derecho en Italia tiene algo que ver con ello). 
Uno tiene la impresión de que el élite tradicional, sus partidos, sus programas, pero también sus ritos, sus periódicos, sus intelectuales acreditados, algunos dirían que sus formatos, lo encuentran siempre más difícil de comprender, y de ahí representar, el que ha estado perfilándose dentro de las capas más profundas de sociedades occidentales y de que la crisis económica refuerza, aumenta, agita potencialmente sin restricción. 
Frente a todo esto, hablando de un" rebelión de las masa" es como la orden del día puede ser exagerada francamente. 
Pero manteniendo uno observa abierto de par en par, no es seguramente. 
