Usted es lo que usted comparte 
En sus cumpleaños décimos Google puede admitir: está allí en el bolsillo de las personas, así como encima de la cabeza, en el cielo. Google sabe donde personas van de vacaciones, qué clase de consultas médicas que ellos visitan y lo que ellos son interesados en. 
A pesar de todo eso, Eric Schmidt, una persona clave de la compañía todavía no es satisfecha. 
Por otro lado, los escépticos que traen en paralela con la fantasía espantosa de Orwell justo no pueden ver la esencia de web 2,0. 
Eric Schmidt indicó recientemente a los Tiempos Financieros que el principal objetivo de Google fue de reunir información personal adicional sobre los usuarios. Es necesario para mantener el objetivo original de fundadores de Google, a saber: "Crear un sistema para toda la información del mundo", él agregó. 
Según el Google-Jefe, la compañía - después de que habiendo subvertido el mundo entero en los últimos 10 años - es todavía al principio del camino hacia la capacidad de tratar toda la información. 
¿Contestar la pregunta con respecto a sus planes para los próximos 5 años que él dijeron que él querría asegurar que Google podrá contestar a preguntas como "Qué haré yo mañana"? , O "Qué tipo de trabajos me conviene mejor"?. Sin embargo, el software no puede dar las respuestas correctas a estas preguntas aparentemente sencillas desde que la cantidad disponible de información de usuario no es suficiente. 
No todos usuarios de Internet son conscientes del hecho que los términos buscados por ellos son registrados, así como la dirección de IP utilizó para la búsqueda y las páginas frecuentados por ellos después. 
Utilizando la función Personalizada de 2 años de edad de Búsqueda, los usuarios pueden almacenar sus propias historias del surf, ellos pueden revisar lo que ellos buscaban, qué clase de lazos que ellos hicieron clic en antes. A largo plazo, puede proporcionar a los usuarios con conclusiones personalizadas. La función llamó Recomendaciones serán basadas en la misma lógica: podrá ofrecernos productos y servicios por la ayuda de las preferencias proporcionada y registrada más temprano. 
"Lo que sucede si mis datos personales son utilizados contra mí, si son descubiertos lo que hago"?, pregunta a algunos de los usuarios que preocupan por el información-monopolio de Google. 
Es generalmente el grado del poder potencial representado por la compañía que engendra reacción contraria en los usuarios, no sentimiento de culpa, el temor de castigo, el deseo para la libertad ni la rebelión contra la autoridad. 
No obstante, ha sido confirmado que todos los términos buscados son registrados y - donde apropia - esos puede ser transferido aún a terceros partidos. En tal no embala nada protege la intimidad de los usuarios de Internet. 
El mejor ejemplo para que es la acción concertada contra algunos pedófilos brasileños; Google transfirió el gobierno brasileño alguna información de uno de sus páginas sociales de interconexión, llamado Orkut. Los datos suministrados ayudaron el gobierno identifica a varios pedófilos. 
Los usuarios que se preocupaban por la invasión de intimidad personal pueden alivio atrás en mayo cuando Google - conjuntamente con el EEF organización legal electrónica de ayuda - demostró exitosamente su derecho contra el FBI: el tribunal confirmó que bajo ningún punto de la Constitución puede el FBI obliga Google a proporcionar cualquier clase de, información en secreto preguntada. 
(No obstante, - refiriéndose a la confirmación de la ley de la protección de niño aprobó varios años atrás - el gobierno federal logró conseguir acceso a 50 000 direcciones web y 1 000 términos de la búsqueda. Sin embargo, no podría adquirir listas de la búsqueda de los usuarios individuales, ni una lista completa de páginas web y palabras clave que cubren un período de dos-mes). 
Cuando parece, hay opiniones polémicas en Google. Es atacado por los que temor del repartir sus datos personales porque ellos se sienten que su esfera íntima y la vida privada serían disminuidos utilizando los servicios proporcionados por Google. Así, ellos representan más bien el grupo que resiste de compañías multinacionals conservadoras. 
Mientras tanto, la cultura norteamericana de tipo y su avena salvaje inclusive ventiladores apasionados de computadora, los activistas, los usuarios en varios países los consideran como la próxima generación de compañías grandes, un "refresca la corporación", por contraste a su opinión acerca de su rival, Microsoft, el creador de Windows y el conquistador del mundo, aunque las dos compañías luchen para el mismo objetivo. 
Uno de las razones para lo puede ser que Google - a diferencia de Microsoft - no requiere nombre de identificación de sus usuarios y el dinero para las aplicaciones. Además, el paquete abierto y continuamente actualizado de código fuente y programa - comparando a la práctica del oficial gigante del software - mira más disponible, juvenil y fresco. 
O quizá es a causa del hecho que tipos pueden ver precisamente la relación problemática entre privilegio e Internet personales, que es de acuerdo con la expresión clave más con frecuencia discutida de los últimos pocos años, la web 2,0. 
Web 2,0 están acerca de una colaboración de dejar intencionalmente huellas acerca de nuestras actividades de computadora y explotar los canales disponibles de comunicación. Aunque el grado de este acto puede ser varios, dependiendo de al usuario, la idea fundamental es el mismo: nosotros nos mostramos al mundo. 
Una joven persona media puede abrir un perfil en varias páginas públicas como Facebook o Xanga, ellos aún los pueden ligar a otros servicios como Gorjeo o el dura.fm de fabricante de lista de música, entonces ésos pueden ser conectados a un sistema que rastrea como FriendFeed o Parpadeo.fm. Además, los usuarios pueden crear blogs que actualizan automáticamente las galerías recientemente cargadas de foto almacenadas en Flickr o Picasa. 
Podemos leer acerca de varias historias como esto: la chica - verificando las muchas fotos cargadas por la mañana por amigos comunes - averigua donde su novio inconfiable gastó su noche anterior. U otro uno: un empleado quizás pierda su trabajo simplemente porque él compartió su opinión en la gestión en su blog. Una consecuencia puede ser dibujada definitivamente: la definición de intimidad ha sido revalorizada. 
Si alguien vive una vida en línea, ellos son lo que ellos exposición de sí mismos - esto es el concepto básico detrás del comportamiento de juventud actual. 
Si alguien tiene algo mantener secreto o si alguien simplemente sólo quiere evitar el monopolio de Google, es también posible (por ejemplo utilizando Scroogle, que también aplica el sistema de búsqueda de Google pero deliberadamente no deja huella atrás). 
El número de esos intencionalmente no registrando a la interconexión social que sitios son significativos. Esta manera que ellos pueden evitar ser descubierta, aplicaciones en línea de Google del redactor de texto para imaginar a director y el locutor puede ser reemplazado por versiones alternativas que no están con respecto a parques inmensos de servidor y no tratando de crear nuestro mejor perfil jamás. 
El gran público espera ver lo que todavía es ocultado por Google. 
La compañía - con su valor de UTILIZO 156 mil millones - vale más que IBM (UTILIZO 140 mil millones), Intel (UTILIZO 124 mil millones) o la Coca Cola (UTILIZO 110 mil millones). Además, los espacios de publicidad de AdWords/AdSense amenazan los ingresos de agencias de publicidad y servicios introdujeron en causa creciente de velocidad Microsoft y varios otros reveladores de software un dolor de cabeza grave. 
No obstante, los críticos también pueden encontrar los contrapuntos perturbadores: la gestión rechazó completamente la objeción de los empleados, que estalló porque el honorario del jardín de la infancia de la compañía había sido duplicado. La cantimplora diaria - el uso de que había sido permitido en tiempo e incluso varias veces - también fue considerado para ser demasiado costoso por la gestión. Sin embargo, todo éstos no son nada comparado al hecho que Google se inclinó antes el gobierno chino en 2006 y - según su acuerdo - la compañía ha filtrado todos resultados de búsqueda que ofenden sabor bueno o los intereses del régimen chino. 
Uno de las regulaciones internas de la compañía dice que nuevos servicios no serán anunciados en el avance, sólo cuando ellos están listos para ser utilizado. Todavía, los meses y los años venideros tendrán definitivamente influencia inmensa en el mundo: algunas personas predicen que el libro y la revista que escudriñan y proyecto de archiving de Google pronto alcanzará tales proporciones que lo tendrá que encarar el Tribunal Supremo. Otros tienen temor del sistema de la Salud, que tiene la capacidad de construir un perfil completo de la salud acerca de nosotros, inclusive nuestras conclusiones, los médicos y los problemas médicas anteriores. 
Por último, el hecho que Google construye una base de datos genética puede proporcionar una materia despreciable perfecta para los escritores de ciencia ficción de la próxima generación. Doctorow de Cory popular novedoso, Scroogled aplica el estilo de Orwell en la descripción de un futuro donde una persona puede ser imaginada espantosamente bien sólo utilizando los datos de Google. 
