Járóka: El círculo vicioso de la pobreza, la segregación debe ser eliminada 
La Igualdad europea Cumbre ha sido abierta hoy en París, que es organizado por Francia este año, representando la Presidencia en oficina de la Unión Europea. 
En su mensaje que ella dirigió a la asamblea plenaria, Lívia Járóka de Fidesz, el Representante de Partido de las Personas europeo llamó atención para la segregación educativa desde que es uno de la infracción más grave afectando a niños de Roma. Además, esto es la barrera más grande a su prosperidad. 
La conferencia alta del nivel ha sido abierta por Xavier Bertrand, Ministro francés para Partido Laborista y Asuntos Sociales y para Vladimir Spidla, Miembro de una comisión europeo responsable de Empleo, Asuntos Sociales e Iguala Oportunidades. 
Los representantes de los gobiernos, los socios sociales europeos y las organizaciones de ayuda y ONGS legales, europeas y más significativas del campo de oportunidades iguales fueron invitados a tener un asiento en la conferencia. 
Járóka - según la oficina de prensa del grupo de Fidesz en el EP - indicó eso, además de la discriminación experimentó al solicitar un trabajo, personas de Roma son segregadas del mercado de trabajo principalmente a causa de su requisito educativo bajo. 
"La mayor parte de las jóvenes personas de Roma no tienen un requisito de instituto de enseñanza secundaria, y debido a la calidad baja de la educación básica sólo una parte insignificante de ellos puede obtener el colegio o la licenciatura". 
Járóka también acentuó esa educación, como un derecho humano fundamental, es clave en la aplicación de otros derechos humanos. 
Invertir en la educación temprana de niños de Roma puede contribuir a refuerzo de la economía de los paises miembros de la Unión Europea. 
Según el representante, es necesario para informar la gama más ancha de personas - Roma y personas de no-Roma también - acerca de estas interrelaciones. 
Los más temprano un jóvenes comienzos del estudiante de Roma que asisten la escuela, las más grandes sus oportunidades serán de llegar a ser un miembro productivo del mercado de trabajo; por los ingresos y los impuestos pagados por ellos ellos contribuirían al presupuesto nacional. 
"En el motivo del derecho de ciudadanía aplicó en la Unión Europea, el derecho de la educación de calidad debe ser asegurado para personas de Roma y calidad baja, la educación segregada debe ser eliminada", agregó Lívia Járóka. 
Ella también dijo que eso acelerar instantáneamente los procesos de supresión de la segregación de escuela, son necesario para garantizar un objetivo- y cooperación orientada hacia la acción dentro de la Unión Europea. Para lograr este objetivo, es fundamental imponer apropiadamente el existir y directivas anti discriminación planeadas. 
"El círculo vicioso de la pobreza, la segregación, el desempleo debe ser eliminado, niños de Roma deben ser proporcionados con las oportunidades de la vida democrática para que ellos puedan contribuir al futuro de Europa como ciudadanos con derechos llenos", Járóka demandado. 
Dentro de la armazón del "Año europeo de Oportunidades Iguales", la Igualdad europea Cumbre - organizó primero en Berlín el año pasado y desde entonces tuvo anualmente - objetivos para proporcionar un foro extraordinario para promover los objetivos de oportunidades iguales y anti discriminación en europeo y nivel de país miembro también. 
