La Lukashenko-oposición: 110-0 
Ningún representante de la oposición fue elegido al parlamento bielorruso durante la elección del domingo. 
Según observadores rusos, las razones para esto son el bienestar y la estabilidad en el país dirigido por Alexander Lukashenko, mientras Organización para la Seguridad y la Cooperación en Europa (OSCE) explica lo vota como contando fraudes. 
OSCE que delega a 450 observadores de 43 desechos de países para reconocer la elección. 
Aunque la 100 legislación de miembro del país de 10 millones haya estado perdiendo oposición para más que una década, antes la elección unió ayer fuerzas de la oposición bajo el nombre de Fuerzas demócratas Unidas (UDF) había esperado gravemente que Lukashenko, que renovó su presidencia por la cuarta vez durante las elecciones polémicas en 2006 después de las enmiendas de la constitución, iba a "permitir" presencia de algunos representantes de oposición En el parlamento esta vez. 
Basado en esto, UDF desistió del boicot anteriormente considerado, también. 
El fondo de las esperanzas de la oposición fue que la Bielorrusia económicamente cada vez más Rusia-Dependiente - eso había levantado un préstamo para reducir la importación rusa cada vez más cara de gas y aceptó Beltransgas que posee gasoductos que cruzan el país propiedad rusa bonita - deseó mejorar sus relaciones con la UE, donde visa no es otorgada para Lukashenko y para varios políticos primeros debido al bielorruso El sistema político, que es considerado anti-democrático. 
El hecho que OSCE cuando habiendo evaluado la campaña electoral se centró más bien en cambios positivos en vez de deficiencias - como prohibir la tercera parte de los candidatos de oposición de tomar parte en las elecciones - distensión indicada anteriormente. 
Sin embargo, hoja de minuto del lunes de OESC puso objeciones contra la campaña durante cuál candidatos de oposición prácticamente no fueron permitidos parecer en los medios y especialmente oposición para no ser permitida asistir al contar de votos. 
Según la oposición, la mejora es todavía perceptible en el sistema político: presos políticos han sido descargados y Minsk es inclinado a confrontar con Moscú en una manera secundaria por todavía no reconocer Ossetia del sur y Abjazia que se han separado de Georgia, aunque Rusia - formando un estado federal con Bielorrusia en el papel - ya ha estado teniendo en cuenta los dos territorios independientes durante un mes. 
"Hemos tomado dos pasos adelante y uno hacia atrás, pero lo más importante es ese diálogo entre Bielorrusia y la UE ha comenzado", Alexander Milinkevich dicho a nuestro papel. 
Según el candidato de oposición de la elección presidencial de 2006, estas necesidades de diálogo para ser mantenidas aunque el "el poder haya conseguido atemorizado de permitiendo aún un miembro de oposición para entrar el parlamento de ningún peso". 
Viendo los resultados, la oposición no planea acciones que protestan, más bien objetivos para alcanzar a votantes con su mensaje acerca de la importancia de reformas económicas. 
"Tenemos mucho problema con esto por supuesto, tenemos que imprimir periódicos de oposición en Rusia, la distribución es dificultada por las administración local, pero por yo todavía puedo ver que cambios son favorecidos por cada vez más personas, entre el viejo, también", dijo Milinkevich que refiere al hecho que el régimen de Lukashenko, que considera el establecimiento de la seguridad social como sus la mayoría de los resultados importantes, son consideradas inadecuado aún por jubilados que son Oficialmente la mayoría de las clases apoyadas de la sociedad de todo. 
"Deber a la deuda del país y el aumento de déficit en la balanza comercial, la avería de seguridad social silencio absoluto que semejante es cosa de tiempo", Milinkevich reclamó. 
Los observadores rusos describieron las elecciones como democrático, en la contradicción al político de la oposición. 
La república de líder Independiente de misión de Estados Sergei Lebedev dijo la agencia de noticias rusa, Ria Novosti: "Personas creen en acciones no palabras", así que la falta de oposición es nada más que la evidencia de la madurez de votantes bielorrusa. 
