Detenidos el alcalde y el jefe de la Policía local de Totana por una presunta trama de corrupción urbanística 
La Guardia Civil ha detenido al alcalde de la localidad murciana de Totana, el "popular" José Martínez Andreo, al jefe de la Policía local, a la secretaria del Ayuntamiento y a un empresario hostelero por posibles delitos urbanísticos, han informado hoy fuentes de la investigación. 
El edil fue arrestado en su domicilio y ha sido trasladado al Consistorio, en cuyas dependencias se encuentra en estos momentos junto a numerosos agentes, que también han acudido a la Concejalía de Urbanismo y a la empresa municipal de gestión del Suelo Industrial y Vivienda. 
Estas tres detenciones se suman a las seis realizadas el pasado lunes en Galicia, Murcia y Madrid, en una operación relacionada con la recalificación de más de 2 millones de hectáreas de suelo rústico en urbanizable para que la empresa gallega Nuaria construyese 4.000 viviendas, tras el pago de comisiones ilegales durante la pasada legislatura. 
Además, otras dos personas no fueron detenidas pero están imputadas en el sumario, que instruye el Juzgado número 1 de Totana. 
Los seis primeros detenidos han pasado hoy a disposición judicial. 
Según han informado las fuentes, el anterior regidor de Totana y hoy parlamentario autonómico del PP, Juan Morales, está siendo investigado. 
Además, la ex mujer, propietaria de una agencia inmobiliaria registrada hoy en Totana, ha resultado imputada, al igual que la actual novia del antiguo regidor, que reside en Murcia capital. 
El director y propietario del Grupo Nuaria, el abogado y empresario vigués Manuel N.A., fue detenido en Nigrán (Pontevedra), al igual que Pablo José M.G., director de Suelo de Inmonuar, agencia integrada en el Grupo citado, y a través de la cual se habrían realizado los sobornos. 
La investigación corre a cargo del Grupo de Delitos Urbanísticos de la Unidad Central Operativa (UCO) de la Guardia Civil, cuyos agentes, además de las detenciones, practicaron once registros, la mayoría en empresas relacionadas con los detenidos y ubicadas en Madrid, Vigo, Murcia, Pontevedra, Las Rozas (Madrid) y Totana. 
Una sola persona fue arrestada entonces en Totana, en concreto, el dueño de una empresa de productos avícolas muy conocido en la región, que podría haber actuado de intermediario. 
El Grupo Nuaria era el encargado de desarrollar el que sería el mayor complejo residencial del municipio murciano de Totana, que supondría la construcción de más de 5.000 viviendas, un campo de golf y dos hoteles con "spa". 
La empresa adquirió en Totana 2,2 millones de metros cuadrados de terreno que fueron recalificados y su proyecto supondría duplicar la población del municipio, que tiene 25.000 habitantes. 
El Grupo Nuaria integra a empresas como Autesa e Inomonuar, dedicadas a la promoción inmobiliaria; Conycase, que gestiona los aparcamientos vigueses de las calles Coruña, Venezuela y de la plaza de Fernando el Católico; Hogartel, dedicada al sector del marketing directo; Preconiza, centrada en la promoción, venta e instalación de elementos de la construcción. 
