El Congreso aprueba la transposición de la Mifid, que entró en vigor 1 noviembre 
Paralelamente a su trámite parlamentario, que finalizó hoy con la votación por parte del Congreso de las enmiendas incorporadas al proyecto en el Senado, el Gobierno ha sometido a audiencia pública el reglamento que desarrollará la nueva ley, con el objetivo de que ambos entren en vigor antes de que acabe el año. 
Los representantes de los diferentes grupos coincidieron en destacar el esfuerzo realizado por diputados y senadores para negociar y consensuar la mejor normativa en aras de garantizar la protección de los inversores y regular con detalle la actividad de las entidades para que los mercados funcionen eficientemente. 
La Mifid, que modifica la Ley del Mercado de Valores, supone la modernización de los mercados financieros, al tiempo que refuerza la protección al inversor, mejora las potestades supervisoras de la Comisión Nacional del Mercado de Valores (CNMV) y fomenta la cooperación entre los distintos supervisores de la Unión Europea. 
La nueva normativa permitirá prestar servicios de asesoramiento financiero tanto a firmas especializadas como a personas físicas o jurídicas y crea un nuevo tipo de firmas de servicios financieros (ESIS), las sociedades de asesoramiento financiero (AFI), que se unen a las sociedades de valores, las agencias de valores y las sociedades gestoras de cartera. 
Además, amplía el número de sistemas para la ejecución de operaciones sobre instrumentos financieros, de forma que a los mercados secundarios regulados se les suman los sistemas multilaterales de negociación y los sistemas de internalización de órdenes, que competirán con los actuales gestores de bolsa. 
La Ley también obliga a las empresas de servicios de inversión a divulgar en el mercado información sobre los aspectos clave de su perfil de negocio, exposición al riesgo y formas de gestión del riesgo y les exige llevar un registro de todas las operaciones que realicen, para facilitar la supervisión por parte de la CNMV. 
En su paso por la Comisión de Economía del Congreso, se incorporaron varias modificaciones, entre las que destaca que las deudas titulizadas sean consideradas como un instrumento financiero "complejo" dada su alta peligrosidad para el inversor, que ha quedado demostrada con lo ocurrido con la deuda de hipotecas de alto riesgo estadounidenses (subprime). 
Además, se aprovechó la transposición de la directiva para delimitar legalmente las funciones que pueden desarrollar los diplomados en Económicas y Empresariales 30 años después de que en 1977 se aprobara el real decreto que delimita las funciones profesionales reservadas a los economistas. 
Por su parte, el Senado incorporó la creación de nuevas figuras en el sector financiero, como la del mediador, que trabajará por cuenta ajena, no requerirá la autorización la CNMV y podrá prestar sus servicios de comercialización de productos y de captación de clientes a distintas empresas de inversión a la vez. 
