El Celtic busca en Milan un punto que vale los octavos 
Milan y Celtic se miden este martes en San Siro en busca del punto que les falta para lograr sus respectivos objetivos en el cierre de la liguilla de la 'Champions', ya que a los italianos les sirve para ser primeros y a los escoceses para sentenciar su clasificación. 
Los italianos suman diez puntos y ya certificaron en la quinta jornada su pase con un empate en Portugal, mientras que el Celtic tiene nueve puntos, pero aún necesita otro para asegurarse que el Shakhtar, con seis, y que recibe al Benfica, que tiene cuatro, no le adelante. 
Estos dos partidos del Grupo D se jugarán una semana antes de que termine toda la sexta jornada, ya que el Milan tiene que disputar el Mundial de Clubes en Japón, donde debuta el día 13 en semifinales en busca de una plaza para la final del 16. 
Así, este grupo quedará cerrado antes que el resto y el empate en el Giuseppe Meazza parece el resultado más esperado, aunque los dos equipos tratarán de salir a por una victoria, ya que los italianos no querrán especular en casa y el Celtic sabe que ganando quedaría primero y se aseguraría un mejor cruce en octavos. 
Al conjunto de Gordon Strachan podría servirle incluso una derrota para clasificarse si el Shakhtar no gana, pero no podrá confiarse porque a igualdad de nueve puntos el pase es para los ucranianos, que perdieron la semana pasada en Glasgow (2-1), pero ganaron (2-0) en el otro duelo directo. 
Así, los milanistas tratarán de amargarle la noche a los escoceses, que confían en meterse en octavos por segunda vez en la reestructurada Champions League y de forma consecutiva, después de que fueran precisamente derrotados en esa ronda la pasada campaña con un gol de Kaka en la prórroga (1-0) tras el 0-0 de la ida. 
Esperando la victoria de los 'rossoneri' estará el Shakhtar al que sólo le vale el triunfo, en el caso de que pierda el Celtic, tanto para meterse en octavos como para seguir en la UEFA. 
Y es que el Benfica, a pesar de ser último y sin opciones de seguir en la máxima competición europea, podría alcanzar la tercera plaza con una victoria, con lo que jugaría la UEFA. 
