Bush arranca un acuerdo entre israelíes y palestinos 
El presidente George Bush anunció, durante la abertura de la conferencia de paz internacional reunida por él mismo el martes a Annapolis, en Maryland, que los israelíes y los palestinos se habían por fin puesto de acuerdo sobre una declaración común. 
Precisó que el Primer ministro israelí Ehud Olmert y el presidente palestino Mahmoud Abbas se habían puesto de acuerdo para entablar inmediatamente negociaciones en vista de encontrar un reglamento definitivo del punto litigioso viejo de 60 años entre sus dos pueblos. 
En presencia de ambos hombres, Bush prometió que haría todo para ayudarles para concluir un "tratado de paz" antes de fines del año 2008. 
Entre tanto, los palestinos deben desmantelar " las infraestructuras terroristas " e Israel debe poner fin a sus actividades de colonización, declaró Bush, recordando ambas partes a sus obligaciones respecto al itinerario para la paz que aceptaron en 2003. 
El jefe de la Casa blanca subrayó que las negociaciones entre Israel y la Autoridad palestina presidida por Abbas intentarían " a concluir un tratado de paz que resolvería todas las cuestiones pendientes, sin excepción, incluido las cuestiones centrales ". 
Esta denominación recubre los tres problemas peliagudos principales del punto litigioso entre israelíes y palestinos: las fronteras futuras de Palestina, el estatuto de Jerusalén y la suerte de los refugiados árabes expulsados de sus hogares durante el conflicto de 1948. 
Tomando la palabra después del presidente americano, Abbas insistió para que las negociaciones venideras sean "globales y aprofundizadas" y se refieran en todos los aspectos de un reglamento, citando " Jerusalén, los refugiados, las fronteras, las colonias, el agua, la seguridad, entre otras cosas ". 
Subendo a su vuelta en la tribuna, Olmert se comprometió a lo que las negociaciones venideras sean "directas y continuas" y a hacer " un esfuerzo para concluirlas en el trascurso del año 2008 ". 
Bush fijó a fines del año 2008 el término de la puesta en marcha de su " visión de dos Estados " palestino e israelí que coexisten. 
Arabia Saudita reveló que había conseguido un empeño en este sentido de parte de Bush antes de decidir participar en la conferencia. 
Arabia, cuya participación a Annapolis es un éxito para Washington, está al principio de un plano, endosado por todos los países árabes, que propone a Israel la paz a cambio de su retirada de todos los territorios árabes ocupados durante la guerra de 1967, incluido Jerusalén del Este. 
Annapolis marca " un punto de confrontación en la historia del Oriente Medio, más particularmente porque se ataca a las raíces del conflicto y a sus aspectos centrales ", estima el príncipe Saoud en su entrevista periódico árabe con capitales saudíes. 
