Fodor y los seis por cientos húngaros 
Según informó el Ministro de Medio Ambiente e Hidrología Gábor Fodor los encuentros a nivel de expertos se terminarán el martes y el miércoles después de la inauguración oficial continuarán las negociaciones a nivel de ministros sobre el régimen climático internacional posterior a 2012. 
Los expertos y políticos procedentes de 192 países del mundo deliberan sobre la Hoja de Ruta de Balí que dispone sobre los esfuerzos posteriores al período de reducción de emisiones, establecida en el Protocolo de Kyoto, vigente hasta 2012. 
En la actualidad se llevan a cabo animadas discusiones sobre el particular entre los países en vías de desarrollo y los industrializados. 
Estados Unidos ya ha indicado que por el momento no desea negociar sobre cifras precisas, aunque tiende a llegar al acuerdo de que en comparación con la situación de 1990, hasta el ano 2020 disminuya con un 25 a un 40 por ciento la emisión de los gases responsables por el efecto invernadero. 
Otro gran tema de la conferencia es que si los países industrializados, además de reducir las emisiones, están o no dispuestos a ofrecer ayuda material y tecnológica a los países que la necesiten. 
Se llegó a un acuerdo además sobre las ayudas a ofrecer a los países en vías de desarrollo. 
El fondo de apoyo, previsto en el Protocolo de Kyoto, será dirigido por un consejo de dirección integrado por 16 miembros, probablemente dentro del Fondo Global para el Medio Ambiente de la ONU (GEF) - escribe el "Piac és Profit". 
Los seis por cientos de Hungría 
En nombre de Hungría, el Ministro de Medio Ambiente e Hidrología Gábor Fodor apoya los esfuerzos de la UE de conservar su papel de vanguardia en la protección global del clima y promover la firma del nuevo acuerdo internacional hasta 2009. 
El ministro declaró que la UE se compromete reducir hasta 2020, con respecto al nivel de 1990 en un 20 por ciento sus emisiones de gas, responsable por el efecto invernadero, independientemente de si se firmará o no el "acuerdo posterior a 2012" y está dispuesta a comprometerse en disminuir incluso un 30 por ciento si las otras grandes regiones desarrolladas del mundo y los países en vías de desarrollo también están dispuestos a asumir compromisos conforme con su responsabilidad y sus capacidades. 
Gábor Fodor apuntó que los países signatarios del Protocolo de Kyoto de 1997 se comprometieron a disminuir en un 5,2 por ciento, dentro de esto los entonces 15 Estados miembros de la UE se comprometieron en cumplir un 8 por ciento de disminución. 
El compromiso de Hungría es de disminuir con un 6 por ciento la emisión de gases responsables por el efecto invernadero con respecto al período entre 1985 y 87, que nuestro país cumplirá - senala el comunicado de prensa del Ministerio de Medio Ambiente. 
Es mucho lo que está en juego en Balí, puesto que dentro de dos anos habrá que firmar el acuerdo internacional de la política climática a largo plazo, porque si no, es seguro que su entrada en vigor se aplazaría para después de 2012. En este caso los compromisos de reducción, asumidos en el Protocolo de Kyoto no serían seguidos inmediatamente por un nuevo sistema internacional de reducción de emisiones, cuya necesidad fue advertida en su más reciente informe por el IPCC, asociación científica internacional de la ONU que se ocupa con el cambio climático, que obtuvo el Premio Nobel de la Paz. 
Con ello, la reducción de las emisiones sufriría un retraso y no se podría impedir un aumento de más de 2o C de la temperatura media de la Tierra, hecho que según los científicos tendría consecuencias inconmensurables e irreversibles. 
