"Sangre de mayo", un reto por Garci épico. 
José Luis Garci, inspirada en la novela episodios nacionales de Banito Pérez Galdós, recreates en sangre de mayo la revuelta popular contra los franceses y es la más ambiciosa de su labor de filmography, con un presupuesto de casi 15 millones de euros. 
Con esta película, el director ha intentado "explicar el torrente de personajes y al mismo tiempo el análisis social" que él siempre admirado en el trabajo de la famosa novela, dijo hoy durante la presentación de la película, con Quim Gutiérrez y Paula Echevarría dirige una mayor emitidos de intérpretes. 
Sangre de mayo, una película más de 30 horas, debuts este viernes en los cines, para convertirse en una de las cuatro horas de televisión en miniseries TeleMadrid en el futuro. 
Gran admirador de Galdós", literatura, José Luis Garci afirma esta resolución se dio cuenta de que" el sueño de su infancia". Que gusta de agradecer a esperanza Aguirre, que, tres años antes, había encargado a él para disparar una película para conmemorar el segundo centenario del 2 de mayo en Madrid: era el deseo expresado por la comunidad de Madrid, con el director accedió a condición de que la historia basado en la novela episodios nacionales. 
El presupuesto total de 15 millones de euros concedidos por la comunidad de Madrid representados por Garci "una oportunidad única" para recrear las series y vestuario para mostrar una "sorprendidos España que eligió el mal líder a luchar para y por el hecho de que la lucha por la independencia llevaba a un enorme retraso en el desarrollo durante el reinado de Fernando VII" dijo Garci. 
Sin embargo, el director lamenta no haber recibido fondos igual de Alatriste o los fantasmas de Goya - más del doble en comparación con sangre de mayo: hasta la fecha, no fue posible para disparar algunas escenas contenidas en el plan, que él mismo había firmado junto con Horacio Valcarcel, su carrera - largo colaborador. 
La diferencia de presupuesto influido la forma habitual de trabajar del director de volver un empezar: por ejemplo, la organización con los agentes, con quien utiliza con frecuencia a ensayar antes de disparar junto con los que no pertenecen al emitir, teniendo en cuenta esta "humillante" y pensar que "el trabajo del director reside en ir al teatro y para el cine para darse cuenta de cómo el sector que está trabajando para está pasando". 
Un cierto número de intérpretes, algunas de las cuales son de emitir de sangre de mayo, repetir en frente de su vídeo - Cámara: es el caso de Michael Rell, Carlos Larranaga o Fernando Guillen Cuervo. 
Cuatro veces en los Oscar nominaciones - ganar un Garci cree que ninguna de las tres películas de candidatos para representar a España en Hollywood este año, su sangre de mayo, siete mesas de billar francés, y el de los seleccionados ulitmo girasoles ciegos representan a la generación más joven del cine español", que debe ser conocido en su lugar". 
Garci no esperan que la adjudicación de esta película. 
"Al principio pensamos de trabajar para la posteridad, entonces se dan cuenta de que usted sólo trabajan para la prosperidad, y en algún momento se acaba de disparar una película más", dice García después de más de 30 años de carrera. 
