Usted lo que comparten 
En su décimo cumpleaños Google puede admitir: no existe en el bolsillo del pueblo, así como sobre su cabeza, en el cielo. Google sabe donde la gente ir de vacaciones, ¿qué tipo de consultas médicas que visita y lo que les interesa. 
A pesar de todo, Eric Schmidt, una persona clave de la compañía aún no está satisfecho. 
Por otro lado, los escépticos que comparecer en paralelo con la de Orwell espantosa fantasía no puede ver la esencia de la Web 2.0. 
Eric Schmidt declaró recientemente al financial times que el principal objetivo de Google fue para recabar más información sobre el personal de los usuarios es necesario mantener el objetivo inicial de los fundadores de Google, a saber: "Para crear un sistema para toda la información del mundo", añadió. 
Según el jefe de Google, la compañía - después de haber manipulado a todo el mundo en los últimos 10 años - aún está en el inicio del camino hacia la capacidad de tratar de toda la información. 
La respuesta a la pregunta sobre sus planes para los próximos 5 años dijo que le gustaría que aseguran que Google será capaz de responder a preguntas como "¿Qué debo hacer mañana?" o "¿Qué tipo de trabajos me encajan mejor?"; sin embargo, el software no puede dar las respuestas adecuadas a estas preguntas aparentemente sencillo desde la cantidad disponible de información de los usuarios no es suficiente. 
No todos los usuarios de Internet son conscientes de que los términos registrados por ellos están registrados, así como la dirección IP utilizados para la búsqueda y las páginas visitado por ellos después. 
Utilizando el 2 años personalizada búsqueda funcionar, los usuarios pueden almacenar sus propias historias de navegación por Internet, se puede revisar lo que buscábamos, qué tipo de vínculos que un clic antes de que, a la larga, puede ofrecer a los usuarios con personalizada hallazgos. La función llamó recomendaciones se basará en la misma lógica: será capaz de ofrecer productos y servicios con la ayuda de las preferencias y registrado antes. 
"¿Qué pasa si mis datos personales son utilizados contra mí, si se descubre qué hago yo?", se preguntan algunos de los usuarios preocuparse de la informaci ón-monopolio de Google. 
Normalmente es el grado de la potencial poder representada por la compañía que genera contrarrestar reacción en los usuarios, no la sensación de culpa, el miedo de castigo, deseo de libertad o la rebelión contra la autoridad. 
No obstante, se ha confirmado que todos los semejantes términos están registrados y - en su caso - quienes incluso pueden ser transferidos a terceros. En esos casos nada protege la privacidad de los usuarios de Internet. 
El mejor ejemplo de esto es la acción concertada contra algunos pederastas brasileño; Google transferido el gobierno brasileño una información de uno de sus páginas de redes sociales, llamado Orkut. Los datos facilitados ayudó al gobierno identificar varios pederastas. 
Los usuarios que se preocupa por la invasión de la intimidad personal podría alivio en mayo, cuando Google - en asociación con la organización de ayuda legal electrónico EEF - demostró su derecho contra el FBI: el Tribunal confirmó que en ningún momento de la constitución puede el FBI obligan a Google para dar ningún tipo de información, pidió en secreto. 
(Sin embargo, - Refiriéndose a la confirmación de la ley de protección de la infancia aprobado varios años antes de que el gobierno federal consiguió acceder a 50.000 direcciones web y mil términos de búsqueda, sin embargo, no podría adquirir las listas de búsqueda de los usuarios individuales, ni una lista completa de las páginas web y palabras clave que abarca un período de dos meses). 
Al parecer, hay opiniones controvertidas en Google. Es atacada por parte de aquellos que temen de enviar sus datos personales, porque consideran que su esfera íntima y vida privada se vería afectada por el uso de los servicios prestados por Google y, por tanto, que no representan el grupo conservador de resistencia a las empresas multinacionales. 
Mientras tanto, la cultura geek estadounidense y su salvaje oat incluidos entusiastas seguidores, informática, activistas de los usuarios en varios países considerarlas como la próxima generación de grandes compañías, una corporación "cool", en contraste con su opinión sobre su rival, Microsoft, el creador de las ventanas y el conquistador del mundo, a pesar de que las dos empresas luchar por el mismo objetivo. 
Una de las razones de que puede ser que Google - a diferencia de Microsoft - no requiere el nombre de identificación de sus usuarios y dinero para las solicitudes y, además, la luz y continuamente actualizada código fuente y el programa oficial del paquete de comparar a la práctica del gigante de software - parece más accesibles, juvenil y fresca. 
O tal vez es porque el hecho de que los especialistas precisamente puede ver la problemática relación entre el privilegio y personal de Internet, que está de acuerdo con la más debatida clave de expresión de los últimos años, la Web 2.0. 
La web 2,0 es sobre una colaboración a intencionalmente dejar rastros sobre nuestras actividades informáticas y aprovechar los canales de comunicación disponibles. Aunque el grado de este acto puede ser diversas, dependiendo del usuario, el punto principal es la misma: mostrar al mundo. 
Un promedio joven puede abrir un perfil público en varias páginas como Facebook o Xanga, pueden incluso vincularlos a otros servicios como Twitter o la música lista pluma last.fm, entonces los puede estar conectado a un sistema de seguimiento como FriendFeed o Blip.fm. además, los usuarios pueden crear blogs que automáticamente actualizar la recientemente uploaded foto galerías almacenados en Flickr o Picasa. 
Leemos varios artículos como esta: la niña - comprobar la abundancia de fotos uploaded en la mañana por amigos comunes - donde se encuentra su novio poco fiables dedicó su anterior de la noche, o de otra: un empleado podría perder su empleo sólo porque compartió su opinión sobre la gestión en su bitácora. Una consecuencia puede ser definitivamente trazado: la definición de la privacidad ha sido reevalúa. 
Si alguien vive una vida online, son las que muestran de sí mismos - este es el concepto básico tras el comportamiento de los jóvenes de hoy. 
Si alguien tiene algo de mantener en secreto o si alguien simplemente sólo quiere esquivar el monopolio de Google, también es posible utilizar Scroogle (por ejemplo, que también se aplica el sistema de búsqueda Google pero deliberadamente no deja huella tras). 
El número de registro de redes sociales no intencionadamente sitios es considerable; de este modo pueden evitar ser descubierto, las aplicaciones online de Google de texto editor de imagen y gestor newsreader pueden ser sustituidas por otras versiones que no están en relación con enorme servidor parques y no intentar crear nuestra mejor perfil nunca. 
Público general está deseando ver lo que está siendo disimulados por Google. 
La compañía - con su valor de 156 millones de dólares - vale más que IBM (140 millones de dólares), Intel (124 millones de dólares) o la Coca-Cola (110 millones de dólares); además, los espacios publicitarios de AdWords y AdSense amenazan el ingreso de agencias de publicidad y servicios introdujo a gran velocidad causa Microsoft y varios otros software un serio quebradero de cabeza. 
Sin embargo, los críticos también puede encontrar la preocupante: la gestión counterpoints completamente rechazó la objeción de los trabajadores, que se partió de porque la cuota de la guardería de la compañía se había duplicado. Cotidiano de la cantina - el uso de lo que se había permitido en cualquier momento e incluso varias veces - también fue considerada demasiado costoso por la administración; sin embargo, todos estos no son nada comparado con el hecho de que Google doblegado ante el gobierno chino en 2006 y - según su acuerdo - la empresa ha filtrado todos los resultados de búsqueda que ofenden buen gusto o los intereses del régimen chino. 
Uno de los reglamentos internos de la compañía dice que los nuevos servicios no será anunciado previamente, sólo cuando están listos para ser utilizada. Todavía, en los próximos meses y años definitivamente tienen gran influencia en el mundo: algunos predicen que el libro y la revista escanear y archivo de proyecto de Google pronto llegaremos a tales proporciones que tendrá que enfrentarse a la Corte Suprema, otros tienen miedo del sistema sanitario, que tiene la capacidad para construir un perfil de salud sobre nosotros, incluidos nuestros conocimientos médicos previos, los médicos y los problemas. 
Por último, el hecho de que Google es la creación de una base de datos genética puede ofrecer una base perfecta para el material sci - fi escritores de la próxima generación. Cory Doctorow, la novela popular Scroogled aplica Orwell de estilo en la descripción de un futuro donde una persona puede ser imaginamos bien hecho sólo mediante el uso de datos de Google. 
