La Oficina abierta, aquí es la tercera edición del "paquete" de Microsoft. 
Hoy se ve la liberación de Openoffice.org 3.0, el código abierto personales de productividad suite que pretende obtener más usuarios, a casa de los usuarios, de los profesionales de la administración pública, como una alternativa libre para mejor conocido Microsoft Office. 
Después de un esfuerzo duradero durante casi un año en nombre de voluntarios desarrolladores, con sol Microsystem supervise a sus espaldas, la nueva oficina abierta se reveló que el público en general con varias novedades: con la pantalla y a un propósito, menos espartana usuarios interface, se añaden otros más importantes como los nativos de compatibilidad con el sistema operativo Mac OS X Apple y apoyo para el nuevo formato ODF (documento abierto formato) 1.200, la última versión estándar ISO. 
La atención fue también sobre interoperabilidad con la Oficina de 2007 suite, abrir el cargo es capaz de abrir documentos con la nueva Microsoft extensión (.docx, .xlsx, .pptx). 
Interesante son algunas funciones específicas de algunos módulos, como la que permite la reducción del tamaño de las presentaciones Powerpoint, útil por ejemplo para sus proyectos a través del correo electrónico, o la posibilidad de importar un PDF ficha en el grafismo módulo, mantener la apariencia original de la página. 
Siempre en el mismo camino, es posible crear "híbrido PDF" documentos, que se unen el estándar gráficos de Adobe formato con los elementos de una spreadsheet ni una palabra transformador. 
La colaboración es una de las características de las aplicaciones que se ha mejorado considerablemente: en la aplicación spreadsheet varios de los usuarios pueden operar simultáneamente, evitar los conflictos en las modificaciones en la palabra transformador, cada uno de los usuarios se asignó una comenta color a mejorar el reconocimiento durante la revisión. 
Algunas empresas están trabajando también en porting algunos de la funcionalidad de OpenOffice hacia la Web (en la nube), y durante las próximas semanas deben liberar el producto definitivo. 
La versión italiana está disponible para descargar en la dirección http://it.openoffice.org/descargarse/3.0.0/download300.html y se suma a la versión inglesa que ha estado disponible en sitios espejo desde el viernes. 
Además de las ventanas y Mac OS, como es habitual, la suite también está disponible para el sistema operativo Linux. 
A petición de la instalación cd puede ser enviados a su casa o de trabajo. 
Y si el invento del libre podría ser una fuerza motriz para la difusión en casas, es en el entorno empresarial que abrir el cargo está tratando la gran apuesta desde ya puede contar con varios proyectos factible dentro de la administración pública y en las escuelas. 
Y hay incluso instituciones que ofrecen servicios de formación, asesoramiento y asistencia, ideal de pequeñas y medianas empresas, lo que podría crear más oportunidades de negocio. 
La Oficina abierta se compone de cinco módulos principal: el escritor, por onscreen tipificación correspondiente a la palabra; Calc, la aplicación spreadsheet apuntan a sustituir sobresalir; impresionar por presentaciones Powerpoint; en la emulación de Dbase, como en el caso de los más famoso de acceso es la aplicación que autorizaciones trabajando sobre bases de datos; sacar, es el módulo gráficos. 
El objetivo para 2008 es alcanzar downloads 5 millones, y teniendo en cuenta que hasta hoy casi 3 millones de 600 mil, con la liberación de la nueva versión es probable que preveía la cifra podría incluso ser superado. 
