UNAM asfalto evitaría baches
Rafael Herrera, un investigador de la facultad de química de la UNAM, desarrolla polymer modificados asfalto para producir una mezcla con el mejor rendimiento, independientemente de las condiciones ambientales y temperatura
Si las señales enviadas por el pavimento participaban, sería necesario para reparar unos 200 mil baches cada temporada de lluvias en la zona metropolitana del Valle de México, dijo Rafael Herrera Najera, un investigador de la facultad Química (CF) de la UNAM, quien dijo que si el proceso de construcción y mantenimiento de un asfalto pavimento es adecuado, los baches se podrían reducir o incluso totalmente eliminados.
En su charla tecnológica una vista del bache, emitido en el año internacional de la Química, anunció que el laboratorio es responsable de está desarrollando un polymer modificados asfalto para producir una mezcla de características similares al asfalto, pero con un mejor resistencia mecánica, tanto en altas y bajas temperaturas.
Nájera Herrera dijo que este tipo de asfalto modificados para ser usados en lugares donde el clima es muy caliente, como algunas ciudades en el norte, a mejorar su desempeño y, por tanto, la formación de baches.
Explicó que el asfalto, la mayor parte del petróleo es un conjunto de moléculas de hidrocarburos, algunas de gran peso molecular, llamado asphaltenes, y otras de bajo peso molecular, llamado maltenes, que dar juntos el pavimento viscoelastic característica su comportamiento.
El comportamiento del asfalto viscoelastic consiste en el hecho de que a altas temperaturas cerca de 180 grados, se comporta como un líquido en 120 ° C, su viscosity es muy alto y en los 50 grados centígrados ha estado casi un sólido a temperaturas muy bajas, mientras que el asfalto se vuelve frágil, dijo.
Esto significa que la resistencia de la calle de asfalto no es uniforme, pero es modificados durante el día, según las condiciones ambientales y la temperatura, dijo el especialista en ingeniería química.
Según los investigadores observaron que las calles de la ciudad de México son en su mayoría cubiertos por pavimento flexible, que se compone de seis capas de material, el último de los cuales tres implicar el asfalto.
Entre las capas más superficial es el asfalto, compuesto por pequeñas piedras cayó en el asfalto y luego compactado.
Cada una de las piedras que componen esta cobertura, dijo, se bajó con asfalto.
Cuando la conducción de vehículos y la generación de esfuerzo, permite que las fuerzas para difundir muy bien en el pavimento.
Si fuera modificada asfalto sería extender incluso mejor, dijo el ingeniero químico.
Sobre el asfalto que abarca, añadió, se ha colocado una última capa de rodadura llamado abarca, que se haga un buen material ​​of piedra, arena significado también cayó en el asfalto.
Dado que se trata de la capa que va a estar en contacto con las ruedas del vehículo, debe tener un mejor resistencia mecánica que cubre el asfalto y proporcionar carretera fricción.
Como parte de la calle que va a recibir y difundir los esfuerzos, el material que abarca también requiere grosor adecuado y el material que se debe tomar en consideración.
Las condiciones meteorológicas, especialmente de humedad y temperatura variaciones son también un factor muy importante a considerar, especialmente del agua, dijo, porque se afecta en gran medida a la actuación del asfalto.
Cuando el suelo es húmedo, agua diffuses dentro de la cobertura y es difícil salir, esta causando un relajamiento de todos los estratos del pavimento y, por tanto, la formación de baches.
En la formación de un bache, dijo, el primero en llevar es el material que abarca y sólo después de que se vea afectado el asfalto, pero el daño no ocurra instantáneamente, es un proceso que debe ser atendidos en las primeras señales con adecuado mantenimiento programas.
También miembro del sistema Nacional de investigadores, explicó que el vehículo de carga es otro factor importante en la formación de baches y, por tanto, el espesor de cada capa de la calle debería ser siempre en relación con el vehículo de carga y garantizar el cumplimiento de esta, a fin de evitar la formación de frecuentes baches.
Rafael Herrera dijo que aún queda mucho por investigar y trabajo por hacer en el asfalto, por ejemplo, asfalto emulsions, que en otros países ya están en el mercado y incluso ayudar a reparar baches con easiness y sin utilizar las altas temperaturas.
