Debe haber cotizado a obras
Las obras sociales que se hace referencia en los programas como Hábitat, rescate de espacios Públicos y 3x1 para migrantes corren el riesgo de no ser completado o a tener graves retrasos debido a la falta de fondos, dijo Miguel Ángel López Miranda.
El director municipal de desarrollo social, indicó que aunque hasta ahora la labor programas han avanzado que están en riesgo porque el Gobierno estatal no cumplían con las aportaciones que corresponden, que representan un recurso superior a los 11 millones de pesos en los tres programas.
Observó que la inversión total en estos tres programas es de casi 50 millones de pesos, de los que el estado debe contribuir con 25 por ciento y hasta ahora sólo la federación y el municipio han proporcionado los recursos para las obras, por lo que la posible retraso en la finalización de estos está en vigor.
« Tienen que contribuir con casi 12 millones y aunque el año termina no han dado un dime (10 centavos, desde que comenzó con julio tuvieron que nos dan una parte », dijo, « con el fin de no retrasar hemos empezado las obras y están muy avanzadas, pero necesitamos el dinero. »
Mencionó que el año pasado, durante la administración de Jesús Aguilar Padilla, el estado no ha cumplido con las contribuciones que había que hacer, así que al inicio de la administración el municipio ha tenido que pedir dinero prestado para cubrir más de 7 millones, una cantidad que no estaba prevista en esa ocasión por la administración estatal.
« Se nos ocurrió en la administración anterior, porque el estado no tiene la capacidad financiera para participar y los programas de continuo avance, y este año, con el fin de acceder a estos programas que tenía para obtener los recursos para cubrir el estado pendientes », explicó.
Aunque hay un compromiso de las autoridades estatales para cumplir con la entrega de estos recursos, dijo que la petición se hizo ​​to el Secretario de administración y finanzas, Armando Villarreal, para acelerar los esfuerzos para que los porcentajes que le corresponden a llegar cuanto antes.
« Tienen que contribuir con casi 12 millones y aunque el año termina no han dado un dime (10 centavos. »
