Mujica viaja a México para fortalecer los lazos políticos
Una delegación oficial encabezada por el presidente José Mujica agentes uruguayos, y compuesta por varios ministros y empresarios, se iniciará este martes una visita a México con el fin de expandir el comercio entre los dos países y abordar las cuestiones políticas en la región.
Mujica se reunirá el próximo miércoles su mexicana iguales, Felipe Calderón, el punto más alto de una amplia agenda de reuniones con autoridades políticas, comerciales y una reunión con la comunidad de uruguayans viven en México, según el calendario liberado por los agentes uruguayos presidencia.
La reunión entre ambos presidentes, en la ciudad de Guadalajara, será « favorables para el intercambio de información en cuanto a las cuestiones políticas entre las dos naciones », tal y como lo publicó la presidencia del país sudamericano en su sitio web.
Según los medios locales, Mujica busca obtener Calderón del apoyo a Uruguay en el incidente con Francia que surgió cuando el presidente francés, Nicolas Sarkozy, incluido el país sudamericano en una lista de paraísos fiscales en la reunión del G20 en la ciudad francesa de Cannes.
En su discurso, Sarkozy amenazados para excluir de la comunidad internacional a los países que siguen siendo paraísos fiscales, una declaración que provocó el rechazo de Uruguay y el llamado a consultas de su embajador en el país europeo.
México preside desde noviembre, el G20, un grupo compuesto por el más poderoso del mundo desarrollado y los países emergentes, y en efecto con el país sudamericano desde enero de este año, un acuerdo de intercambio de información fiscal con el fin de evitar la doble imposición.
Los agentes uruguayos gobierno ha intentado en los últimos años para acelerar la conclusión de intercambio de disposiciones fiscales, para dejar en la « lista gris » de la organización para la cooperación y el desarrollo económicos (OCDE), compuesta de países que no aplicar todos los estándares internacionales de cooperación en materia fiscal.
Sobre el plan de comercio, México y Uruguay han en vigor desde 2004 un Tratado de Libre comercio (TLC) que ha aumentado el intercambio de mercancías entre ambos países.
