El grupo catalán ha facilitado miles de pasaportes a Al Qaeda 
Además de los siete detenidos en Barcelona, en Tailandia hubo tres 
Los siete pakistaníes y un nigeriano detenido por agentes de la policía secreta de Barcelona General formaron un grupo yihadista que, dirigido por Tailandia, facilitado pasaportes a diferentes grupos de Al Qaeda, entre ellos "Los Tigres de Liberación del Territorio Tamilm" (LTTE) y "Laskar e Taiba" (Let), autor de esta última uno de los atentados de Bombay que causó la muerte de 106 personas en 2008. 
El Ministerio del Interior ha prestado atención a estas investigaciones, hasta el punto de asegurar que con "Kampai" operación; ha sido "debilitar" el aparato de falsificación de Al Qaeda a nivel internacional y, por lo tanto, su capacidad operativa ". 
Los investigadores calculan que la celda, durante los dos años que ha participado activamente en Cataluña, ha podido enviar miles de pasaportes a Tailandia, donde fueron falsificados y pronto a los grupos que integran la galaxia penal de Al Qaeda para que su "combatientes" pueden cruzar las fronteras europeas y las de otros países occidentales con total impunidad. 
La célula desmantelada no es la única que la red yihadista en Europa, por este motivo en las investigaciones no han participado, además de los servicios de Tailandia, otras unidades de policía europeas, razón por la que no descartan que en el territorio de la UE se producen acontecimientos similares al elaborado la noche del martes en Barcelona. 
En coordinación con esta operación (La Junaid Humayun paquistaní, Rehman Atiqur, Jabran Asghar, Malik Iftikhar Ahmad, Mohammad Saddique Khan Begum, Tanveer Arshad y el nigeriano Agunbiade Babatunde fueron detenidos), en Tailandia otro había elaborado con la captura de los pakistaníes Muhammad Athar Butt y Zeeshan Ehsan Butt y tailandés Kijbumrung Sirikanlaya. 
El grupo sentados en España y otros países europeos se dirigía desde Bangcock 
La red catalana, parte de él fue golpeado en 2009, principalmente robado pasaportes a los turistas que cumplen los requisitos marcados por el llamado "Worldwide frente Islámico". 
Es decir, los documentos tenía que estar en el nombre de los hombres de entre 25 y 45 años, con validez de varios años y sin visados impresos. 
En los medios de la investigación se hizo hincapié en que, por el momento, no se ha encontrado datos relativos a las personas detenidas en Cataluña en relación con el atentado de Bombay, aunque el autor de este ataque, "Laskar e Taiba", ha sido uno de los grupos que reciben el robo de pasaportes falsificados en España y pronto en Tailandia. 
Sin embargo, cabe mencionar que días antes de este cometido el ataque, desde Cataluña no fueron enviados a través de una agencia de transferences sobre algunos miles de dólares que fueron "invertido" en la compra de tarjetas de telefonía móvil antes fueron utilizados por los miembros del "comando" que acabó con la vida de 106 personas. 
Los policías han capturado un montón de documentación. 
