Grammy candidaturas: La cantante de jazz Esperanza Spalding es una sorpresa meterse en la categoría de mejor artista nuevo 
Realizar a petición de un presidente, y las personas están obligados a tomar nota. 
Esperanza Spalding, la cantante de jazz y 26 bassist elegidos por el Presidente Obama a realizar en la ceremonia del Premio Nobel de la Paz en 2009, marcó uno de los " Grammys sorpresas este año con una nueva nominación en la categoría de mejor artista. 
Considerando que Spalding ha sido un célebre figura en el escenario de su álbum de jazz desde 2008, "Esperanza", la candidatura es un poco head-scratcher, pero es compatible con las normas Grammys " de un artista no liberar a más de tres álbumes antes de la grabación que "se establece la identidad pública de este artista". 
Su ambicioso álbum de 2010, "Cámara de la Sociedad Musical", sin duda marcó un paso adelante, y dada su airily invitar abiertamente y una mano hábil estilo pop, y hace temblar las influencias Latina, es posible sacar al menos una línea de puntos a Spalding de Norah Jones "gran éxito en 2003, el equivalente más cercano a los votantes Grammy mirando hacia el vecindario de jazz en esta categoría en los últimos años. 
En el resto de los votantes Grammy cumplieron con razón el trío Vijay Iyer del "Historicity" en el álbum instrumental de la categoría, un vigorizante thrill-ride de un registro que era un favorito crítico del año pasado. 
Entre esas Iyer competirá contra incluir saxophonist veterano James Moody 's "Moody 4B" y keyboardist John Beasley "Positootly". 
Tuba Shorty, un raucous Nueva Orleans y favorito de la HBO invitado frecuente sobre "Treme", fue conmemorado en la categoría de jazz contemporáneo, que de lo contrario se inclina hacia la fusión con cierto fuertemente hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
La salvaje, steampunk-informed Darcy James Argue 's Secret Society ganaban alrededor de un merecido reconocimiento en el gran ensemble categoría, compitiendo contra el Billy Childs Ensemble de los ricos y los chamber-jazz ever-adventurous Dave Holland, cuya octet álbum en directo "Camino" fue un buen ejemplo de la mano del bassist democrático como bandleader. 
