El geriátrico afirma que las muertes no fueron por "falta de medidas" 
Los dueños del centro de Olot no descartan que su celador matara a más de 11 ancianos
Los responsables del geriátrico La Caritat de Olot (Gerona) ofrecieron ayer una rueda de prensa para poner de relieve el daño que le ha causado a la institución la conducta criminal de Joan Vila Dilmé, el enfermero que mientras estaba allí empleado mató al menos a once ancianos que tenía a su cargo.
El director de la residencia, Joan Sala, compareció acompañado del letrado del centro, el abogado Joan Cañada, y anunció que "el deseo de La Caritat sería poder ejercer la acusación contra el responsable" de las muertes pero "la legalidad y la responsabilidad nos obligan a asumir la situación procesal de responsables civiles".
Y es que además del desprestigio social que pueda sufrir la entidad por no haber detectado a tiempo las actividades criminales del celador, la gran amenaza para La Caritat cobra ahora forma de sustanciosa indemnización que ya están calculando los representantes legales de los familiares de las víctimas.
Joan Vila Dilmé ha confesado que el primer crimen se remonta a agosto de 2009 y que desde entonces no ha dejado de matar.
El juez ya apuntó en el auto que ordenaba la exhumación de ocho cuerpos - antiguos pacientes del geriátrico - que sospechaba que en muchos casos ningún doctor exploraba personalmente a los fallecidos sino que, atendiendo a la edad y a las patologías de los pacientes, se despachaba el trámite por teléfono.
La Caritat, a través de su director, negó ayer rotundamente este extremo y apuntó que "la falta de medidas no puede haber sido en ningún momento la causa de lo que ha pasado".
El abogado de La Caritat añadió que "en la causa no hay un solo indicio de que haya habido una acción imprudente por parte de cualquier otra persona que no sea el propio imputado".
El ya bautizado como "Ángel de la Muerte" confesó anteayer 11 asesinatos y detalló que el primer crimen lo cometió el 29 de agosto de 2009 para, un mes y medio más tarde, matar a una segunda abuela.
En este caso provocó la muerte pinchándole una sobredosis de insulina, a diferencia del primer crimen que lo cometió ayudándose de una mezcla de pastillas sedantes.
El director de La Caritat apunta que es complicado controlar que el personal del centro tenga acceso a los medicamentos.
Los pinchazos de insulina y el cóctel de sedantes habrían sido el mecanismo empleado en seis de los nueve crímenes que el enfermero, en su afán para aliviar el sufrimiento de los internos, usaba para darles muerte.
Pero serán los análisis que se están haciendo en el laboratorio los que deberán aclarar si Vila no miente y buscó para sus primeras víctimas una muerte menos cruel o si, por el contrario, las abrasó por dentro dándoles lejía como ya ha confesado que hizo con las tres mujeres que mató entre el 12 y el 17 de octubre.
En La Caritat no dan credibilidad a las manifestaciones del celador, ni tan siquiera al número de asesinatos confesados, que no descartan que sea superior, y justifican su actitud en las diferentes versiones que ha dado Vila en sus visitas al juzgado y en el poco sentido que tiene que cambie su modo de proceder después de haber cometido, con éxito, ocho asesinatos.
Es por eso que dicen que se ponen a disposición de la justicia para esclarecer el alcance de este suceso.
