El Gobierno español no puso reparos a los vuelos de la CIA 
El Gobierno español no puso reparos a los vuelos de la CIA con prisioneros talibanes y de Al Qaeda con dirección a Guantánamo por territorio español, según expresó en un telegrama el embajador de EEUU en Madrid.
Así lo reflejan los documentos filtrados (cables) por Wikileaks al diario El País, donde se añade que la entonces vicepresidenta primera del Gobierno, María Teresa Fernández de la Vega, pidió que el Ejecutivo español estuviese informado para "poder demostrar que ejercían una vigilancia apropiada sobre los aviones extranjeros que atraviesan España".
En junio de 2006, tras un informe del Consejo de Europa en el que acusaba de complicidad en prácticas contrarias a los derechos humanos a una docena de países, entre ellos España, se produjo una reunión entre el ex embajador norteamericano Eduardo Aguirre y Fernández de la Vega.
La vicepresidenta reconoció que el informe del Consejo "había cogido al Gobierno de Zapatero fuera de juego" e insistió en que España no tenía nada que ocultar en este asunto.
"De la Vega subrayó que España no tiene reparos a los vuelos de inteligencia a través de territorio español."
"Ellos simplemente quieren ser informados" para evitar ser "pillados desprevenidos", relata Aguirre en un cable.
También el entonces titular de Exteriores, Miguel Ángel Moratinos, señaló al embajador que el Ejecutivo español "quería dar a este asunto el perfil más bajo posible, aunque, al estar en manos de los jueces, el Gobierno tenía una limitada capacidad de influencia".
Por su parte, en enero de 2007, el fiscal Vicente González transmitió a la Embajada que no intentaría bloquear la iniciativa del juez de pedir la desclasificación de los documentos del Centro Nacional de Inteligencia (CNI) y del ministerio de Defensa sobre los vuelos de la CIA.
"Estos informes no contienen ningún elemento incriminatorio ni ninguna información sensible", explicó la Embajada después de hablar con el fiscal.
Sin embargo, EEUU reflejó su preocupación por la "aparente coordinación entre el juez español y los fiscales alemanes", más que por la información desclasificada del CNI o del ministerio de Defensa.
"Esta coordinación entre investigadores independientes complicará nuestros esfuerzos para manejar el caso discretamente entre Gobiernos", lamenta Aguirre.
En marzo de 2007 en un almuerzo entre el embajador de EEUU y el ministro del Interior, Alfredo Pérez Rubalcaba, éste le comentó que "aunque los jueces españoles son rabiosamente celosos de su independencia y harán lo que consideren adecuado", él había dado instrucciones a sus colaboradores "para que evitasen comentarios de inflamada retórica, en un intento por rebajar la temperatura".
El embajador también expresa su preocupación por la actuación del PP en este asunto.
"Pese a su orientación general proamericana, nuestra experiencia sugiere que el PP no dudará en capitalizar cualquier indicación de que el Gobierno de Zapatero toleró o deliberadamente ignoró acciones de EEUU que pudieran ser interpretadas como posibles violaciones de los derechos humanos, incluso si éstas revelaciones tienen consecuencias negativas para el Gobierno de EEUU", señala.
