La célula catalana facilitó miles de pasaportes a Al Qaida 
Además de los siete detenidos en Barcelona, en Tailandia hubo tres
Los siete paquistaníes y el nigeriano detenidos por agentes de la Comisaría General de Información de la Policía en Barcelona formaban una célula yihadista que, dirigida desde Tailandia, facilitaba pasaportes a diferentes grupos de Al Qaida, entre ellos "Los Tigres para la Liberación de la Tierra Tamil" (LTTE) y "Laskar e Taiba" (Let), autor este último de los atentados de Bombay que causaron la muerte a 106 personas en 2008.
El Ministerio del Interior ha dado gran importancia a estas investigaciones, hasta el punto de asegurar que con la "operación Kampai" ha quedado "debilitado" el aparato de falsificación de Al Qaida a nivel internacional y, "por tanto, su capacidad operativa".
Los investigadores calculan que la célula, en los dos años que ha estado activa en Cataluña, ha podido enviar miles de pasaportes a Tailandia, donde eran falsificados y luego distribuidos a los grupos que integran la galaxia criminal Al Qaida para que sus "combatientes" puedan cruzar las fronteras europeas y de otros países occidentales con total impunidad.
La célula destamantelada no es la única que la red yihadista tenía operativa en Europa, de ahí que en las investigaciones hayan participado, además de los servicios tailandeses, otras unidades policiales europeas, por lo que no se descarta que en territorio de la UE se lleven a cabo en los próximos días golpes similares al desarrollado en la noche del pasado martes en Barcelona.
En coordinación con esta operación (fueron detenidos los paquistaníes Junaid Humayun, Atiqur Rehman, Jabran Asghar, Malik Iftikhar Ahmad, Mohammad Saddique Khan Begum, Tanveer Arshad y el nigeriano Babatunde Agunbiade), en Tailandia se desarrolló otra con la captura de los paquistaníes Muhammad Athar Butt y Zeeshan Ehsan Butt y el tailandés Sirikanlaya Kijbumrung.
Estos eran los que dirigían desde Bangkok la célula asentada en España y en otros países europeos.
La red catalana - parte de ella fue golpeada en 2009 - robaba principalmente a turistas pasaportes que cumplían con los requisitos marcados por el llamado "Frente Islámico Mundial".
Es decir, los documentos debían estar a nombre de varones de entre 25 y 45 años, con una validez de varios años y sin visas estampadas.
En medios de la investigación se subraya que, de momento, no se ha encontrado ningún dato que vincule a los arrestados en Cataluña con el atentado de Bombay, pese a que el autor de este ataque, "Laskar e Taiba", haya sido uno de los grupos receptores de los pasaportes robados en España y luego falsificados en Tailandia.
No obstante, cabe recordar que días antes de que fuera cometido este atentado, desde Cataluña fueron enviados a través de una agencia de transferencias unos mil dólares que fueron "invertidos" en la compra de tarjetas de móviles que luego fueron utilizadas por los integrantes del "comando" que acabó con la vida de 106 personas.
La Policía se ha incautado de abundante documentación.
