Nominaciones a los Grammy: la cantante de jazz Esperanza Spalding es la elección sorpresa en la categoría de Artista revelación.
Actúa a petición de un presidente y posiblemente la gente se fijará en ti.
Esperanza Spalding, la bajista y cantante de jazz de 26 años seleccionada personalmente por el Presidente Obama para actuar en su ceremonia del premio Nobel de la Paz en 2009, supuso una de las sorpresas de los Grammys este año con una nominación de alto nivel en la categoría de Mejor Artista Revelación.
Teniendo en cuenta que Spalding ha sido una aclamada figura del jazz desde su álbum de 2008, "Esperanza", la nominación da qué pensar, pero respeta las normas de los Grammys según las cuales debe ser un artista que no haya sacado al mercado más de tres álbumes antes de grabar el que "determina la identidad pública de dicho artista".
Su ambicioso álbum de 2010, "Chamber Music Society", sin duda supuso un gran avance y, teniendo en cuenta su estilo vocal ligero y agradable, así como una gran habilidad con influencias de pop, funk y ritmos latinos, se puede al menos establecer una distinción entre Spalding y el camino hacia el éxito de Norah Jones en 2003, el equivalente más cercano para los votantes de los Grammys, que últimamente se han concentrado en el ámbito del jazz para esta categoría.
En las restantes categorías, los votantes de los Grammy hicieron honor con razón a "Historicity" de Vijay Iyer Trio, un emocionante y magnífico disco que fue uno de los favoritos el año pasado.
Entre los competidores de Iyer se encuentra el veterano saxofonista James Moody con "Moody 4B" y el teclista John Beasley por "Positootly."
Trombone Shorty, un estridente favorito en Nueva Orleans e invitado habitual en "Treme", de la HBO, fue honrado en la categoría de jazz contemporáneo, que por el resto se inclina considerablemente hacia la fusión como en los álbumes de Stanley Clarke, John McLaughlin y Jeff Lorber.
El salvaje punk de Darcy James Argue's Secret Society obtuvo un merecido reconocimiento en la categoría de grandes grupos, compitiendo contra el gran jazz de cámara del Billy Childs Ensemble y el siempre arriesgado Dave Holland, cuyo álbum en vivo con su octeto, "Pathways", fue un gran ejemplo del liderazgo democrático del bajista en su banda.
