Advertencia sobre los pesticidas ingeridos por los niños
Un niño de 10 años ingiere en un día 81 sustancias químicas diferentes, según indica un estudio publicado el miércoles por la asociación Générations Futures (el antiguo movimiento por los derechos y el respeto de las generaciones futuras).
La asociación, que advierte de que sus resultados "no tienen un valor estadístico significativo teniendo en cuenta el limitado número de muestras analizado, pero son ilustrativos de la problemática tratada", adquirió en supermercados de Oise y París entre julio y septiembre los alimentos que suele consumir un niño de unos diez años en cuatro comidas y un tentempié al día.
Estas comidas tomadas como modelo, que respetan las recomendaciones oficiales (cinco partes de frutas y verduras frescas, tres de productos lácteos y 1,5 litros de agua al día), así como las golosinas, fueron examinadas en los laboratorios en busca de sustancias químicas, pesticidas, metales pesados y otros contaminantes.
El balance del plato resulta abrumador: 81 sustancias químicas, de las cuales 42 clasificadas como cancerígenos posibles o probables y cinco sustancias clasificadas como cancerígenos seguros, así como 37 sustancias susceptibles de actuar como perturbadores endocrinos (PE), según los estudios de diversas instituciones como el Centro internacional de investigación sobre el cáncer.
"Aunque, en prácticamente la totalidad de los casos, no se superan los límites legales para cada una de las sustancias químicas de forma individual, nuestro estudio muestra claramente que la exposición de los consumidores a contaminantes posiblemente cancerígenos y/o PE resulta preocupante", señala la asociación.
Para el desayuno, la mantequilla y el té con leche contienen por sí solos más de una decena de residuos cancerígenos posibles y tres considerados como cancerígenos seguros, así como cerca de una veintena de residuos que pueden perjudicar al sistema hormonal.
La manzana, importada de Brasil, prevista como tentempié para el colegio, contiene trazas de seis sustancias químicas, incluido un fungicida prohibido en Francia.
Lo mismo se aplica a las judías verdes de Kenia, incluidas en la comida, en las que el estudio ha detectado trazas de un potente insecticida prohibido en la UE.
Además, el filete ruso, el atún en lata e incluso la barra de pan o el chicle estaban aderezados con pesticidas y otras sustancias químicas.
En el agua del grifo, los análisis descubrieron la presencia de nitratos y cloroformo.
En la cena, la rodaja de salmón era la más "nutritiva" con 34 residuos químicos detectados e incluso el análisis del plato de plástico utilizado para calentar la comida en el microondas no estaba completamente limpio.
El riesgo final que generan estos "cócteles de contaminantes" para el consumidor "probablemente se subestima", dice el estudio.
La Alianza Europa Ecología-Les Verts (EE-LV), por su parte, ha propuesto "frente a la gravedad de la situación" aplicar una moratoria sobre la utilización de pesticidas para frenar "el aumento de las enfermedades asociadas a la civilización".
En julio, un estudio de la Agencia Europea de Seguridad Alimentaria (AESA) indicaba la presencia de residuos de 365 pesticidas diferentes identificados en la fruta y la verdura consumidas en Europa, de los cuales 76 en los cereales.
