Pide IP resultados al Congreso
Eduardo Dávalos, presidente del CCE, propuso que los diputados asuman la gran responsabilidad de ser un ejemplo de ver por un mejor Sinaloa por los diversos retos que enfrenta.
Una Legislatura de trabajo digno y libre de acuerdos entre partidos y del Ejecutivo estatal reclama el sector empresarial de Mazatlán, porque hay un Sinaloa convulsionado que enfrenta grandes problemáticas.
Desde ayer quedó instalada la 60 legislatura, integrada por siete fuerzas políticas, 19 diputados del PRI, 13 del PAN, tres del Partido Nueva Alianza, dos del PRD, uno del PT, uno de Convergencia y uno más del PVEM, que suma un total de 40 representantes populares.
Entre el listado de expectativas de los nuevos integrantes del Congreso del Estado es de que vengan a realizar una gestión limpia y de compromiso con la sociedad y con los diferentes sectores que requieren de un trabajo legislativo responsable y que no se repitan los mismos patrones del partidismo o paternalismo.
Eduardo Dávalos Zamora, presidente del Consejo Coordinador Empresarial, propuso que los recién estrenados 40 diputados del Congreso del Estado asuman la gran responsabilidad de ser un ejemplo de ver por un mejor Sinaloa por los diversos retos que enfrenta.
"Esperamos que los diputados realmente ejerzan su derecho, libres de acuerdos entre los partidos porque es costumbre que hacen arreglos para velar por los intereses propios y se convierten en comparsas carnavaleras de los gobernantes y de los líderes de las fracciones parlamentarias".
De ahí que habló de que certifiquen el compromiso para establecer los puentes necesarios que saquen adelante al Gobernante en turno.
"Ocupamos que vengan a hacer un trabajo digno y sobre todo comprometidos con la sociedad y con los sectores porque fueron los sinaloenses quienes les dieron el voto de confianza en las pasadas elecciones".
José Ramón Manguart Sánchez, presidente de la Asociación de Hoteles Tres Islas, consideró que uno de los grandes retos de los 40 representantes populares es la de empujar y sumar fuerzas en busca del crecimiento económico del estado, porque hoy en día la situación económica es muy complicada.
"Lo más importante es que empujen el crecimiento económico, que generen incentivos para la inversión e infraestructura y eso de alguna manera fomentará la generación de empleos".
En cuanto a la actividad turística, demandó que los nuevos legisladores le den el peso que reviste dentro del presupuesto estatal para fortalecer a la Secretaria de Turismo estatal.
"Tengo entendido que es la segunda Secretaría en el estado con menor presupuesto y es incongruente como actividad económica importante y generadora de divisas e inversión y que de forma directa compite con la agro industria".
Además de que se requiere etiquetar recursos a proyectos turísticos detonantes y que coadyuven en darle seguridad al estado y en la actualización a la Ley de Alcoholes que no han podido resolver en anteriores legislaturas.
