Fue detenido el alcalde de Totana y el jefe de la policía local en una trama traspasar la planificación de la ciudad de corrupción
La guardia civil ha detenido el alcalde actual del municipio de Totana Murcian popular José martínez Andreo, el jefe de la policía local, el Secretario de la ciudad del Consejo y un empresario hostal sobre la planificación de la ciudad de posibles fuentes de crímenes, nos han informado de hoy.
El edil fue arrestado en su casa abordar y se ha transferido al Consistory, en cuyo imperios es actualmente con varios agentes, que también han ido a la del Consejo Municipal de gestión urbana y la compañía de suelo industrial y la vivienda.
Estas tres arrestos son añadido a seis hizo el pasado lunes en Galicia, Murcia y Madrid, en una operación vinculadas a los requalification de más de 2 millones de hectáreas de rustic terreno para urbanizeable Nuaria Galicia, de modo que la compañía 4.000 construido casas, después de que el pago de las comisiones ilegales durante la última legislatura.
Además, otras dos personas fueron detenidos pero no cobrados en el sumario, que ordena la Totana número 1 del tribunal.
Los seis primero arrestos han ido ante el Tribunal hoy en día.
Según fuentes de información, el anterior alderman de Totana parlamentaria autónoma y real del PP, Juan morales, se está investigando.
Además, la antigua esposa, propietario de una agencia de bienes raíces registrado en Totana, ha sido arraigned, como es el actual novia de ex alderman que reside en Murcia capital.
El director y propietario de el grupo Nuaria, el abogado y industralist Vigo Manuel N.A., fue detenido en Nigrán (Pontevedra), como se decía Pablo José M.G. terreno, director de Inmonuar, una agencia integrada con el mencionado grupo, y a través de la cual los sobornos habría sido hecha.
La investigación es la responsabilidad de la ciudad de planeamiento crímenes grupo de operar oficina Central (UCO) de la Guardia civil, cuyos agentes, además de los arrestos, llevaron a cabo once récords, la mayoría de las empresas vinculadas a los detenidos y situadas en Madrid, Vigo, Murcia, Pontevedra, Madrid y Totana.
Una persona entonces era arrestado en Totana, en particular, el propietario de las aves de corral producto compañía bien conocido en la región, que podría haber actuado como intermediario.
El grupo Nuaria fue responsable de desarrollar lo que se convirtió en el mayor de los complejos residenciales Murcian municipio de Totana, que forman parte de la construcción de más de 5.000 casas, un campo de Golf y dos hoteles con "spa".
La compañía adquirido en Totana 2,2 millones de metros cuadrados de tierra que fueron requalified y su proyecto presuponía la duplicación de la población de los municipios, que ha 25.000 habitantes.
El grupo Nuaria integra empresas como Autesa y Inomonuar, dedicado al desarrollo de bienes raíces; Conycase, que administra los cauces de estacionamiento de las calles de Coruña, Venezuela y la Fernando la plaza católica; Hogartel, dedicado al sector de la comercialización directa; Preconiza defendía centrarse en la promoción, la venta y la instalación de los elementos de la construcción.
