El Congreso apruebe la transposición de la mif que tuvieron lugar el 1º de noviembre
Junto con sus procedimientos parlamentarios, que acabó hoy con la votación parcial del Congreso sobre las enmiendas incorpora para el proyecto en el Senado, el gobierno ha presentado a audiencia pública la regulación que desarrollará la nueva ley, con el objetivo de los próximos ino fuerza antes de que termine el año.
Los representantes de diferentes grupos acordado en hacer hincapié en los esfuerzos realizados por los diputados y senadores para negociar y aceptar la mejor legislación para garantizar la protección de los inversores y regular en detalle la actividad de las organizaciones para que los mercados trabajar de manera eficaz.
La mif, que modifica el acto del mercado de valores, tiene que ver con la modernización de los mercados financieros, mientras que refuerza la protección de los inversores, mejorar las competencias de control de la Comisión Nacional del mercado de valores CNMV y fomenta la cooperación entre los diversos supervisores de la Unión Europea.
Los nuevos reglamentos concedan servicios de asesoría financiera a las empresas especializadas así como a las personas físicas o jurídicas, y crea un nuevo tipo de las compañías de asesoría financiera (ESIS), las compañías de asesoría financiera (AFI), que incluyen las empresas de valores, ayuden a la cartera de gestión, y las empresas.
Además, amplía el número de sistemas disponibles para la ejecución de operaciones financieras, de modo que incluya en el reglamento son los mercados secundarios, los sistemas de comercio multilateral, y la internacionalización de los sistemas de órdenes, puedan competir con la actual los administradores del mercado de valores.
La ley también requiere de empresas de servicios de inversión a revelar al mercado la clave detalles de sus negocios perfil, riesgo exposición y formas de gestión de riesgos, y para mantener un registro de todos sus operaciones a facilitar la supervisión por la CNMV.
En su aprobación a través de la Comisión de asuntos económicos del Congreso, varias modificaciones que se introdujeron las deudas, particularmente securitised debería considerarse como un instrumento financiero "complejo debido a su alto riesgo para los inversores, que ha sido demostrada por lo que sucedió con el alto riesgo (hipotecas de las deudas hipotecas estadounidenses).
Además, la transposición de la directiva se aprovechó para legalmente definir las funciones que pueden desarrollar graduados en la economía y finanzas decreto en 30 años después de la aprobación general en 1977, que delimits funciones reservadas a los profesionales de los economistas profesional.
Por su parte, el Senado promovió la creación de nuevas funciones en el sector financiero, como el asesor financiero, que trabajará para contratar o recompensa, no requieren la aprobación de la Comisión y será capaz de ofrecer sus servicios y la comercialización de productos a los clientes de mediación en diversas empresas de inversión al mismo tiempo.
