Capital político: la guardia húngaro ha agudizado el nivel de riesgo del país
Las acciones por parte de la Guardia húngaro, establecido en agosto con el apoyo del movimiento para una Righter Hungría, ha planteado el riesgo político nivel de Hungría y toda la región desde una serie de aspectos, según el riesgo de analizar la división de capital político.
La investigación "entidad emitió un riesgo advertencia", escribir: las acciones de la Guardia húngaro están provocando un riesgo político "que excedan los ya existentes y las tensiones étnicas entre los gitanos no gitano residentes de Hungría podría atiborren a niveles tóxicos ya en el corto plazo, conduciendo a conflictos étnicos que podrían tornarse violenta."
La principal razón para esto es que la estrategia política de la Guardia húngaro parece estar destinadas a provocar la acción de esta naturaleza, el Instituto de investigación añadido.
Este es el resultado de una de las más graves fracasos de actores políticos de Hungría: "los principales actores en la vida pública entregó el debate público de las cuestiones romá a representantes de las fuerzas políticas y extremistas radicales, que han construido una estrategia política de las diferencias - húngaro gitano".
Esto, capital político cree, ha intensificado el problema, por lo que cualquier diálogo normal imposible, reforzando los extremistas, y aumentar la probabilidad de que se produzcan conflictos violentos.
Además, el Instituto de investigación cree que la frecuente interno e internacional a la atención de los medios de las acciones de la Guardia húngaro ha dañado Hungría "significativamente la imagen internacional, en particular en cuanto a la creencia en la estabilidad del país y en la sofisticación de su democracia".
Señalan que el aumento de la publicidad y el impulso dado a la redistribución de la organización de los grupos radicales y de extrema derecha en Hungría iniciaron en el otoño de 2006 han sido parte de la razón por la que un número de organizaciones llamando a sí mismos "nacional" Autodefensa alianzas de partida fueron creados en el verano de 2007.
"El rasgo común de estos grupos es que se llaman a sí mismos organizaciones cívicas mientras abiertamente declarar que se están preparando para sus miembros - incluyendo armados defensiva de tareas (citando desastre gestión, la defensa nacional, la aplicación de la ley) mientras declarar que la policía y las fuerzas armadas, en otras palabras, el gobierno, es inadecuada para el papel," capital político añade.
Señalaron que todas estas medidas se han cometido dentro de una sociedad que se basa en la configuración de la política y el estado de ánimo de partido político para manto diversos ambiciones políticas bajo el manto de la acción cívica.
En otras palabras, su énfasis en la naturaleza cívica de sus acciones y su elección de la asociación como su forma de organización no son meramente maniobras para esquivar escollos legales a registrarse con los tribunales, sino que también forman parte de una estrategia política.
Según el análisis, la actividad de la Guardia húngaro está acentuando el riesgo de dañar las relaciones con nuestros vecinos, demasiado.
"En los últimos meses varios de los vecinos de Hungría han citado la guardia húngara como un peligro potencial ultranationalist. Los actores políticos entre algunos de estos vecinos se han referido a la creación de la Guardia húngara como un argumento para justificar sus propias políticas anti-húngaro.
Todos estos factores influir sobre la estabilidad política de la región", se suman.
El Instituto de investigación se indica que el establecimiento de la Guardia húngara no es un fenómeno único en Europa central y oriental, y como tal, aumenta el riesgo político para toda la región.
Se observa que el funcionamiento de la Guardia húngaro es similar a la de la guardia nacional búlgaro, establecido en agosto de 2007 por la extrema derecha de la Unión nacional búlgaro. (BNU).
Serios conflictos que estalló entre romaníes y quienes no en un distrito Sofía (Krasna Polyana) inspiraron la creación de la Guardia búlgaro.
BNU se aprovechó de los disturbios para establecer la Guardia, al afirmar que el objetivo de la organización fue "nacional" autodefensa.
Argumentaban que durante los últimos 17 años, Bulgaria había sido objeto de "gitano el terrorismo", en la que el gobierno fue indefensa y indiferentes, capital político observó.
La iniciativa desencadenó acalorado debate entre el pueblo búlgaro, añadió.
Una señal de que el riesgo de un conflicto étnico ha aumentado, los analistas escribió, es que algunas organizaciones romá en Bulgaria han anunciado planes para establecer un guardia de sus propios como una fuerza de resistencia.
Desde la guardia húngaro hasta ahora ha actuado bastante Asimismo a la guardia nacional búlgaro, es muy posible que la comunidad romaní de Hungría podía responder a la amenaza por organizar su propia defensa propia, escribió capital político en la advertencia del riesgo.
La investigación de capital político administrador Attila Juhász respondió a una pregunta desde el MTI húngaro videos diciendo que los análisis de riesgo fue una de las actividades en jefe del Instituto de investigación.
Cada año, dijo, se publican análisis de riesgo, y si se descubre cualquier factor que podría alterar riesgos, que notificar a la opinión pública por publicar un riesgo de advertencia, como lo han hecho ahora.
