Se espera que la Reserva de reducir los tipos de conducir al mundo alza del mercado de valores
Comparte saltó a ambos lados del Atlántico ayer después de mercado esperanzas de que la Reserva Federal intentará calmar las condiciones de crédito con mayor reducciones de los tipos de interés fueron impulsada por complacientes observaciones de los Estados Unidos vicepresidente del Banco Central.
Los mercados de valores volando en Londres, Nueva York y en toda Europa después de Donald Kohn, nº 2 a Ben Bernanke, el Presidente de la Fed, dijo que los dirigentes políticos deben ser "flexible y pragmático" en reaccionar ante el estrés constante en los mercados financieros.
En un claro esfuerzo para asegurar a los mercados fretful producía señales de resurgimiento de cepas de crédito, señor Kohn dijo que los recientes turbulencias "habían invertido en parte algunas de las mejoras en el funcionamiento del mercado durante los fines de parte de septiembre y en octubre de".
Debería la elevada turbulencias persistir, aumentaría la posibilidad de lograr un mayor rigor en condiciones financieras para los hogares y las empresas, dijo.
Los comentarios fueron tomadas por los inversores como una señal de que la Reserva Federal está dispuesta a paso en con nuevas inyecciones de capital en los mercados de los Estados Unidos y otros posibles reducciones de los tipos de interés, estabilizar las condiciones de crédito.
Los comentarios también contribuyó a la calma Wall Street producía más malas noticias sobre la economía estadounidense, como las ventas de los hogares afectó a un nivel muy bajo en octubre.
Las consecuencias de las turbulencias financieras fue subrayado por un anuncio de oso Stearns, el Banco de inversiones, que se recortarán 650 puestos de trabajo, o 4 por ciento de su fuerza de trabajo global, en una ronda de reducir costes para compensar fuertes pérdidas de su perdiendo Apuestas con respecto a los Estados Unidos de las hipotecas de préstamos del sector de la vivienda.
Sólo 20 puestos de aquellos que se espera que van en Londres, donde el Banco emplea 1.500 personas.
En Nueva York, el promedio industrial Dow Jones saltado por 331 puntos o 2,55 por ciento, para cerrar en 13.289,40 más amplio, mientras que el índice S&P 500 se incrementó 2,65 por ciento.
En Londres, el índice FTSE 100 puntos 165,5 rosa, o 2,7 por ciento, para cerrar en 6.306.2, Añadir más que 39 mil millones de libras para el valor de las compañías chip azules de Gran Bretaña.
De Alemania índice Dax aumentó 2,6 por ciento, y CAC40 de Francia se alzó 2,3 por ciento.
Antes, el estrés reemergence de crédito en los mercados de alta lighted después fue fuerte demanda en una subasta de fondos de tres meses por el Banco Central Europeo vieron aquellos prestado a los bancos comerciales de Europa en una pesada 4,7 por ciento, la tasa más alta desde abril de 2001.
La presión sobre el Banco de Inglaterra a seguir el Fed y el BCE y inyectar fondos adicionales en los mercados de dinero en Londres montado como cepas de crédito de tres meses "Libor varios tipos de" para los préstamos entre los bancos del Reino Unido presionado a sus mayores desde finales de septiembre, al 6,59 por ciento, después de una constante trepar desde noviembre de 12.
