El catalán Grupo facilitado miles de pasaportes a Al Qaeda 
Además de los siete presos en Barcelona, en Tailandia había tres 
Los siete pakistaníes y el de un nigeriano detenido por agentes de la policía de Barcelona general inteligencia formado un grupo yihadista que dirigieron en Tailandia, facilitó pasaportes a diferentes grupos de al Qaeda, entre ellos "los Tigres de la liberación de tamilm territorio" (LTTE) y "Laskar y taiba" (¡), autor de este último uno de los atentados de Mumbai, que causó la muerte de 106 personas en 2008. 
El Ministerio de Asuntos Interiores ha prestado atención a estas investigaciones, hasta el punto de asegurar que con "kampai" operación; ha sido "debilitar" el aparato de falsificación de Al Qaeda a nivel internacional y, por lo tanto, su capacidad operativa "". 
Los investigadores calcular que la célula, durante los dos años que ha estado activa en Cataluña, ha podido enviar a miles de pasaportes a Tailandia, donde fueron falseadas y pronto distribuido a los grupos que integrar la galaxia penal de Al Qaeda para que su "combatientes" pueden cruzar las fronteras europeas y las de otros países occidentales con total impunidad. 
El desmantelado celda no es el único que la red yihadista en Europa, por esta razón en las investigaciones no han participado, además de los servicios de Tailandia, otras unidades de policía europeas, razón por la cual no se descarte que en territorio de la UE se producen acontecimientos similares al desarrollado la noche del martes en Barcelona. 
En coordinación con esta operación (la junaid pakistaní, humayun atiqur rehman, jabran, asghar Malik Iftikhar Ahmad, Mohammad saddique Khan Begum, tanveer arshad y la babatunde nigeriano agunbiade estaban todos), detenido en Tailandia otro había desarrollado con la captura de los pakistaníes Muhammad athar culo y zeeshan ehsan culo y la sirikanlaya tailandés kijbumrung. 
El Grupo sentados en España y otros países europeos fue dirigida desde bangcock 
La red catalán, parte de lo que se ha logrado en 2009 - principalmente pasaportes robados a los turistas que cumplen los requisitos marcada por la llaman "frente islámico en todo el mundo". 
Es decir, los documentos tenía que estar en nombre de los hombres entre 25 y 45 años, con validez de varios años y sin visados impresa. 
En los medios de investigación es subrayar que, por el momento, no se ha encontrado datos relativos a las personas detenidas en Cataluña en relación con el ataque de Bombay, aunque el autor de este ataque, "Laskar e taiba", ha sido uno de los grupos de los pasaportes en España y pronto falseada en Tailandia. 
Sin embargo, es preciso mencionar que días antes de este cometido ataque, de Cataluña no fueron enviados a través de una agencia de transferences acerca de algunos miles de dólares que estaban "invertido" en la compra de tarjetas de telefonía móvil que antes eran utilizados por los miembros de la "comandos" que acabó con la vida de 106 personas. 
Los policías han recibido un montón de documentos. 
