El Gobierno español no plantear objeciones con respecto a los vuelos de la CIA 
El Gobierno español no plantear objeciones con respecto a los vuelos de la CIA con los prisioneros talibanes y de Al Qaeda que iban a Guantánamo a través del territorio español, según el embajador de los Estados Unidos en Madrid 's telegrama. 
Así se refleja en el filtrado documentos (cables) por WikiLeaks a diario "el país", donde se añadió que el primer Vicepresidente del Gobierno en aquel momento, Maria Teresa Fernández de la vega, pidió que el ejecutivo española fue informada en orden "para ser capaces de demostrar que se había llevado a cabo un seguimiento adecuado de los procedimientos en los aviones extranjeros que cruzar España". 
En junio de 2006, después de un informe del Consejo Europeo donde hubo acusaciones de complicidad en prácticas contra los derechos humanos en una docena de países, entre los que se encuentra España se celebró una reunión entre los antiguos Norte embajador norteamericano Eduardo Aguirre y Fernández de la vega. 
El Vicepresidente reconoció que el informe del Consejo "había adoptado el Gobierno de Zapatero fuera del juego" y ha insistido en que España no tienen nada que ocultar respecto de este asunto. 
"de la vega subrayó que España no plantear objeción por la inteligencia los vuelos sobre el territorio español". 
"simplemente quieren ser informados" para evitar ser "tomada por sorpresa", Aguirre se refiere en un telegrama. 
También el ex Ministro de Asuntos Exteriores, Miguel Ángel Moratinos, indicó que el embajador español que el ejecutivo "quería dar a este tema tan poca atención posible, aunque están en manos de los jueces, el gobierno tuvo una influencia limitada". 
Por otro lado, en enero de 2007, el Fiscal General Vicente González transmitidas a la embajada de que él no intentar bloquear la iniciativa del juez de solicitar la puesta en entredicho de documentos del Centro Nacional de Inteligencia (CNI) y del Ministerio de Defensa con respecto a los vuelos de la empresa " 
Esta información no contiene ningún elemento exoneración ni ninguna información sensible ", explicó la embajada después de hablar con el fiscal. 
Sin embargo, los Estados Unidos refleja en su preocupación por la aparente "coordinación entre el juez español y alemán fiscales", más de la declassified información del CNI o el Ministerio de Defensa. 
"esta coordinación entre los investigadores independientes complicará nuestros esfuerzos para manejar discretamente el caso entre gobiernos"; señala Aguirre. 
En marzo de 2007 durante un almuerzo entre el embajador de los Estados Unidos y el Ministro del Interior, Alfredo Pérez Rubalcaba, este uno le comentó que "aunque los jueces españoles son rabidly celosos de su independencia y hará lo que se considera", que había dado instrucciones a sus colaboradores "para evitar comentarios de retórica encendidos, en un intento de reducir la temperatura". 
El embajador también expresa su preocupación por la acción del PP en este asunto. 
"a pesar de su pro orientación general americano, nuestra experiencia indica que el PP no duda en la capitalización ningún indicio de que el Gobierno de Zapatero tolerado o ignorar las acciones de los Estados Unidos que podría ser interpretada como posibles violaciones de los derechos humanos, incluso si estas revelaciones tienen consecuencias negativas para el Gobierno de los Estados Unidos", indica. 
