Grammy nombramientos: Jazz cantante esperanza Spalding es una sorpresa escoger en mejor artista nueva categoría 
Llevar a cabo a petición de un Presidente, y la gente está obligado a tomar nota. 
Esperanza Spalding, el Jazz 26 y bassist cantante seleccionado por el Presidente Obama a realizar en su Premio Nobel de la paz ceremonia en 2009, marcó uno de los grammys "sorpresas este año con un destacado nombramiento en el mejor artista nueva categoría. 
Considerando que Spalding, ha sido un célebre figura en la escena Jazz desde su álbum de 2008, "esperanza", el nombramiento está un poco de un head-scratcher, pero es coherente con la grammys "normas de un artista no liberar más de tres álbumes de imitación antes de la grabación que" establece la identidad pública de que artista. " 
Su ambicioso 2010 álbum, "Cámara música" sociedad, sin duda marcado un paso adelante, y dado su airily invitar abiertamente y una mano de deft POP, Funk y las influencias de América Latina, es posible llamar al menos una línea a Spalding de Norah Jones "gran éxito en 2003, el equivalente más cercano a grammy votantes mirando hacia el jazz en el vecindario de esta categoría en los últimos años. 
En otros lugares grammy votantes castigado con razón el trío Vijay iyer la "historicity" en el álbum instrumental categoría, un refuerzo de thrill-ride un récord que era un crítico del año pasado favorito. 
Entre los iyer puede competir contra incluyen veterano saxophonist James Moody 's "Moody' s" 4b y keyboardist John Beasley "positootly". 
Trombone shorty, un raucous favorito de Nueva Orleáns y frecuentes invitado a la "HBO, treme" se cumplen en la categoría Jazz contemporánea, que de lo contrario inclina hacia fuertemente la fusión con asentimiento hacia los discos Stanley Clarke, John mclaughlin y Jeff lorber. 
La salvaje, steampunk-informed darcy James argumentar "sociedad secreta de ganado algunos merecido reconocimiento en el gran colectivo categoría, contra el colectivo Billy Childs la rica chamber-jazz y la ever-adventurous dave Holanda, cuya octet vivir del álbum" caminos "era un buen ejemplo de la bassist democrática de lado como un bandleader. 
