Alerta sobre plaguicidas consumida por los niños. 
Según un estudio publicado o el miércoles por la Asociación de futuras generaciones (formelry movimiento por los derechos y el respeto de las generaciones futuras), un niño de 10 consume en un día 81 diferentes sustancias químicas. 
La asociación que predice que sus resultados no poseen, en vista del pequeño número de muestras analizado, un importante valor estadístico, pero ilustrar el problema está tratando, ha comprado en spermarkets de la oise y de París entre julio y septiembre, la cesta de alimentos en general consumida en cuatro comidas de un niño de diez. 
Estas harinas inclduing recomendaciones oficiales, cinco piezas de las frutas y hortalizas, tres productos lácteos y 1, 5 litros de agua así como los manjares, fueron examinadas por los laboratorios de investigación clínica con productos químicos, pesticidas, metales pesados y otras sustancias contaminantes. 
El balance es asombrosa: 81 sustancias químicas incluidos 42 clasificados como carcinógenos o potencialmente probablemente y cinco clasificados como carcinógenos definitivamente, así como 37 sustancias capaces de inducir a trastornos endocrinos, según los estudios por varias instituciones como el centro internacional de investigación sobre el cáncer. 81 sustancias chimiques dont 42 sont classées cancérigènes possibles et cinq ou probables sustancias classées cancérigènes certaines Ainsi que 37 sustancias susceptibles d 'agir comme perturbateurs (endocriniens educación física), selon des études de plusieurs instituciones telles le centro de internacional recherche Sur le cáncer. 
Según la associaiton, incluso si, en casi todos los casos, los límites legales de cada sustancia química no se sobrepasen, nuestra investigación demuestra que la realidad de la exposición de los consumidores a carcinógenos potencialmente contaminantes es preocupante. 
Para el desayuno, la mantequilla y leche té con sólo contiene más de diez posible y tres demostrado residuos carcinógenos y casi veinte residuos potencialmente capaces de perturbar el sistema hormonal. 
Una manzana de Brasil contenga rastros de seis sustancias químicas incluing un un fungicida, prohibidas en Francia. 
Lo mismo se aplica a las habas de Kenia incluido en un luncheon, en la que el estudio encontrado rastros de un poderosos insecticidas prohibidos en la Unión Europea. 
En addiiton, filete picada, el atún en conserva y incluso un baguette y chicles contenidas pesticidas y otras sustancias químicas. 
Tapwater contenidas nitratos y chloroform. 
Durante la cena, el salmón bistec fue el "", más ricos con 34 residuos químicos e incluso la placa de plástico utilizadas por el calentamiento, la comida en un microondas, no fue exentos. 
Según el estudio, el último riesgo para el consumidor en este "cóctel contaminante" es probablemente subestimarse. 
Por su parte, la alianza ecológico europeo, los Verdes han propuesto, en vista de la urgencia de la situación, la introducción de una moratoria sobre el uso de plaguicidas, para detener el crecimiento de las enfermedades de la civilización. 
En julio, un estudio realizado por la Agencia Europea de Seguridad Alimentaria señala la presencia de residuos de 365 diferentes plaguicidas identificados en las frutas y hortalizas consumida en Europa incluidos 76 en los cereales. 
