Romano va hacia su primer título 
Rubén Roman Omar cuenta con tres derrotas en los finales, habiendo durante su carrera altibajos, pero él sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos laguna y Monterrey en la última, además dos estilos diferentes marcados por sus técnicos ", que se enfrentan entre sí con un cambio marcado por los resultados. 
Rubén Roman Omar cuenta con tres derrotas en los finales, habiendo durante su carrera altibajos, pero él sabía cómo alcanzar en tres ocasiones el decisivo serie, aunque hasta ahora no ha alcanzado el objetivo y esta es la razón por la que esta oportunidad es muy especial para él. 
La ha de Argentina terminó siendo consoled con la medalla de participó, y se mantuvo un paso atrás los ganadores y específicamente con aparatos similares que ha desempeñado las finales consecutivos. 
Santos llegó a su primera como final formadores en el primer partido de 2002, cuando tomó las riendas de morelia con el que ha comenzado a 4-2 antes de toluca; después, en el acto de clausura de 2003 también ha llegado en el duelo decisiva y perdió también a 1 y, de hecho, antes de rayados. 
Ya con Santos laguna, en el Partido bicentennial de 2010, antes de que los diablos, rubén sufre de nuevo un revés, puesto que su equipo igualmente acabados lugares 2-2 antes la salchicha después de los 210 minutos de juego, pero en el turno de las sanciones, se metió en ventaja por 1 con dos oportunidades para sellar el título pero finalmente tres actores fracasado desde el 11 de pasos y sufrido el cambio por 4-3. 
Rubén perdido dos finales con diablos rojos y uno en Monterrey, su rival, a su vez, por lo que no queremos sufrir el mismo destino, quiere celebrar un título por primera vez, y que afirma que el aspecto más importante para él es la institución. 
Quiero ser un defensor, no quiero romper cualquier dato estadístico, es de un club, por una pasión y por consiguiente el título llegará a mí, pero la cosa es más importante, comentó el timonel cuando se preguntarán las cifras que ha de jugar contra las finales. 
Muy eficaz tiene la última anterior, de la que, él asegure, ha aprendido mucho, "la única lección que podemos extraer es que hasta el árbitro señala el fin no podemos celebrar, nos preparamos así como los jugadores, porque en la ocasión anterior, con dos sanciones que estaban a punto de marcharse y creo que es una lección que hay que aprender, no podemos celebrar hasta el juego termina". 
Sabiendo que esta serie podría ser definidos en la derrota de la pena, algo que no tener problemas, porque le confía en sus actores: "uno nunca deberían estar yendo a las sanciones, sino concluir a tiempo regulares; a veces no tienen ninguna alternativa y es necesario estar preparados; en la anterior partido estábamos dispuestos, por desgracia destino desempeñado en nuestras manos; a veces por nervios o ansiedad por haber el título en fuera manos, pero no lo hicimos alcanzar este objetivo, y esto nos dejó algo por este último que esperamos para ganar". 
Roman debe dejar de ser un candidato técnico y por primera vez la gloria, que los títulos dar. 
