"Sangre de mayo", un reto épico por Garci. 
José Luis Garci, inspirado en la novela Episodios Nacionales de Pérez Galdós Banito, en recrea Sangre de mayo la revuelta popular español contra los franceses. Esta es la más ambiciosa labor de su filmografía, con cerca de 15 millones de euros de presupuesto. 
Con esta película, el director ha tratado de "explicar el torrente de personajes y al mismo tiempo, el análisis social", que siempre admiró en la obra del famoso novelista, dijo hoy, durante la presentación de la película, con Quim Gutiérrez y Paula Echevarría partida un mayor elenco de intérpretes. 
Sangre de mayo, una película más de 2.30 horas, se estrenará este viernes en los cines, a convertirse en una cuatro horas de televisión en miniseries Telemadrid en el próximo futuro. 
Gran admirador de Galdós "la literatura, José Luis Garci reclamaciones este rodaje realizado" un sueño de su infancia ". Le gusta dar las gracias a Esperanza Aguirre, quien, tres años antes, le había encargado para disparar una película para conmemorar el segundo centenario de la Madrid 2 de mayo. Este fue el deseo expresado por la Comunidad de Madrid. El Director estuvo de acuerdo con la condición de que la historia basada en la novela Episodios Nacionales. 
Los 15 millones de presupuesto total asignado por la Comunidad de Madrid representa para Garci una "oportunidad única" para recrear el conjuntos y trajes para representar una "sorprendido de que España eligió el mal para luchar contra el líder y el hecho de que la lucha por la independencia condujo personas a un enorme retraso en el desarrollo durante el reinado de Fernando VII ", dijo Garci. 
Sin embargo, el director lamenta no haber recibido fondos de la igualdad de Alatriste o Los fantasmas de Goya - más del doble en comparación con Sangre de mayo. Hasta el momento, no era posible disparar a algunas escenas incluidas en el plan, que él mismo había firmado, junto con Horacio Valcárcel, su carrera a lo largo de colaborador. 
La diferencia de presupuesto influido en la forma habitual de trabajar del director de Volver a empezar: por ejemplo, la puesta en escena con los actores, con quien a menudo utiliza para ensayar antes de filmar, junto con los que no pertenecen a la fundición, teniendo en cuenta este "humillante" y pensar que "la labor del director reside en ir al teatro y al cine para darse cuenta de cómo la industria está trabajando para que está sucediendo". 
Un cierto número de intérpretes, algunos de los cuales entran en el elenco de Sangre de mayo, repita delante de su video-cámara. Es el caso de Michael Rell, Carlos Larrañaga o Fernando Guillén Cuervo. 
Cuatro veces en las nominaciones al Oscar - un ganador - Garci considera que ninguna de las tres películas candidato para representar a España en Hollywood este año, su Sangre de mayo, Siete mesas de Billar francés, y el seleccionado ulitmo Los girasoles ciegos representan el cine español de la generación más joven ", que debe ser conocido lugar". 
Garci no espera premios de esta película. 
"Al principio te parece que trabajan para la posteridad, entonces te das cuenta de que sólo el trabajo para la prosperidad, y en cierto punto que acaba de rodar una película más", dice García después de más de 30 años de carrera. 
