Drogas: Nunca con los zumos de frutas. 
Tenga cuidado de zumo de pomelo, zumo de naranja y zumo de manzana. 
Estas bebidas, sobre todo consumido en el verano porque son la sed de enfriamiento y rica en vitaminas, si se toman junto con algunos medicamentos que salvan vidas puede alterar su absorción, amplificando o atenuando, según el caso, su eficiencia con las consecuencias que también pueden ser graves para la salud. 
Confirmando los riesgos asociados con la asunción de los zumos de frutas si están pre-envasados o frescos con ciertos medicamentos es David Bailey, profesor de la Universidad de Western Ontario en Londres, que a partir de la 236a reunión nacional de la American Chemical Society en Filadelfia en marcha lanzamientos una nueva advertencia: un vaso de zumo de pomelo, zumo de naranja, o zumo de manzana es suficiente para reducir la absorción de ciertos medicamentos que salvan vidas, anular sus efectos beneficiosos y pone en riesgo la salud de los pacientes. 
El zumo de pomelo ya ha sido acusado porque se pensó que se encargue de la recaudación, hasta los niveles de pensamiento a ser tóxicos, los efectos de algunos antirhythmic, antibióticos, tranquilising, antihistamínicos, medicamentos y neurológicas. 
DROGAS EN RIESGO - La misma Agencia de Drogas italiano ha dado el mismo consejo de información en un proyecto de ley hace dos años, alertar a médicos y pacientes a no subestimar los peligros que se derivan de esta mezcla y prestar atención a lo que se bebe en los casos en que las drogas son adoptadas como, por ejemplo, diazepam o la metadona. 
NO SÓLO zumo de pomelo - Según los expertos, incluso zumo de naranja y jugo de manzana contiene sustancias que inhiben las drogas. 
La lista de principios activos inhibidos por las toronjas y otros zumos de frutas es muy larga. 
De ahí la apelación de Michele Carruba, director del Departamento de Farmacología de la Universidad Estatal de Milán: "Por lo general, esos descubrimientos son inmediatamente señaló a la atención de los diversos instrumentos internacionales y los organismos nacionales en materia de drogas que luego cambiar la información de los medicamentos que se desliza. 
Por lo tanto, siempre leer las notas explicativas de los medicamentos tomados y si hay algo que no está claro, no se atrevió a preguntar al médico o farmacéutico para aclaraciones »subrayó el experto de la Agencia Ansa. 
