Adiós viejo Cinema Paradiso, las ciudades cancelar los teatros históricos 
Teatros históricos de las obras cinematográficas estrecha en favor de los multiplex. 
"Una ciudad sin teatros las obras cinematográficas es un ciego la ciudad, es como un rostro sin ojos". 
La imagen ofrecida por el director Giuseppe Tornatore fotografías de manera eficaz lo que está ocurriendo no sólo en los grandes centros urbanos, italiano, sino también en ciudades de provincia. 
El proceso de marginación de los cines, con el nacimiento en las afueras de las grandes multi-sala de teatros y la consiguiente muerte por el consumo de la única sala de teatros en las zonas céntricas de la ciudad, es uno de los acontecimientos que parece inevitable e incontrovertibles y también tiene todas las características de un verdadero crimen cultural. 
Con frecuencia, es que los lugares históricos están llenos de recuerdos que desaparecen, "es como si un amigo se pierde, un conocido con quien hemos compartido el camino y muchos recuerdos», observa el director del Nuevo Cine Paraíso, la película que veinte años atrás Tornatore dio el Oscar y el Gran Premio del jurado de Cannes, y que narra el poema de una sala provincial y la nostalgia por un modo de vida que el cine, tal vez, se ha perdido para siempre. 
Los números proporcionados por la ANEC, los principales operadores de cine asociación, hablar con claridad: en los últimos cinco años 316 estilo tradicional cines han cerrado la tienda, y los que pagan el precio estuviera por encima de todos los teatros en las principales ciudades: 10 menos en Florencia 9, en Milán, Nápoles, Bolonia y Roma, 6 menos en Turín, 5 en Palermo. 
Entre las regiones más gravemente afectadas por los cierres, Emilia-Romagna ocupa el primer lugar con 82 de un solo salón de los cines perdidos, seguido por la Toscana (44), y por Lombardía (41). 
Y para demostrar que la llegada de los múltiplex es el más responsable de su desaparición, estos son exactamente las tres regiones italianas con el mayor número de nuevas salas de cine multiplex registrados: 195 más en las pantallas de Lombardía en los últimos cinco años, 81 en Toscana y Emilia-Romaña. 
«La empresa italiana ha desarrollado de manera irracional» observa Paolo Protti, el presidente de la ANEC, "es útil que las nuevas estructuras se construyen, pero también es esencial que la supervivencia de las existentes está garantizada, porque una vez un teatro en una ciudad se cierra, no todos los sus clientes pueden sentirse inclinados a la transferencia a la multicines. 
Por no mencionar la falta de asignación de fondos a favor de los operadores: el anterior de débito por el estado es de aproximadamente 10 millones de euros. 
Es vergonzoso, desde la ética y desde el punto de vista moral, que el gobierno no respeta las leyes existentes. 
Para sostener el sector de entre 16 y 18 millones de euros al año se requieren ». 
Un ejemplo interesante es el de Bolonia, la primera ciudad italiana que, afectados por los cierres, ha decidido tener cobertura mediante la firma de un protocolo entre el municipio y la ANEC, la primera de su tipo en Italia, para proteger y promover la única sala de cines tanto en el centro histórico, así como en las afueras. 
Entre las disposiciones allí previstas son las medidas de alivio fiscal en favor de los operadores y las ventajas para el público en términos de movilidad: los espectadores pueden entrar en el tráfico limitado en la zona y tienen tarifas especiales para carretera y aparcamientos en algunos aparcamientos. 
«Es una iniciativa que me gusta» señala Giuseppe Tornatore ", y espera que otras ciudades sigan el ejemplo de Bolonia, poniendo en acción otras medidas. 
Es cierto sin embargo, que contrario a la excesiva potencia de los múltiplex, los teatros tienen también para mejorar el sonido y la calidad de la imagen, porque hoy en día el público es más exigente. 
La defensa de los cines es un tema que para mí siempre ha sido importante: el cierre de la Supercinema Bagheria, el lugar de mi infancia y la adolescencia, fue la chispa que me convenció para crear "Nuevo Cinema Paradiso", en la que ya he estado pensando durante los últimos 10 años. 
He estado viviendo en Roma durante 25 años, y cuando pasan delante de los de Rialto o el Quirinal Nacional en la calle cerrada por tanto ahora, allí donde he vivido muchas emociones compartidas, me vuelven la espalda para no ver los carteles ennegrecidos por el polvo ». 
