Járóka: El círculo vicioso de la pobreza, la segregación debe ser eliminado 
La Cumbre europea de la igualdad se ha abierto hoy en París, que es organizada por Francia de este año, en representación de la Presidencia en ejercicio de la Unión Europea. 
En su mensaje que dirigió al Pleno, Lívia Járóka del Fidesz, Representante del Partido Popular Europeo llamó la atención educativa para la segregación, ya que es uno de los más graves de infracción que afectan a los niños romaníes. Además, este es el mayor obstáculo para su prosperidad. 
La conferencia de alto nivel ha sido abrió por Xavier Bertrand, ministro francés de Trabajo y Asuntos Sociales y Vladimir Spidla, Comisario Europeo responsable de Empleo, Asuntos Sociales e Igualdad de Oportunidades. 
Representantes de los gobiernos, los interlocutores sociales europeos y el más importante de Europa de asistencia jurídica y las organizaciones no gubernamentales del ámbito de la igualdad de oportunidades fueron invitados a tener un puesto en la conferencia. 
Járóka - de acuerdo con la oficina de prensa de la FIDESZ grupo en el Parlamento Europeo - señaló que, además de la discriminación que sufren al solicitar un puesto de trabajo, los romaníes son segregados del mercado de trabajo, principalmente a causa de su baja cualificación educativa. 
"La mayoría de los jóvenes romaníes no tienen una cualificación de enseñanza secundaria, y debido a la baja calidad de la educación básica sólo una parte insignificante de ellos puede obtener la universidad o título universitario". 
Járóka también hizo hincapié en que la educación, como un derecho humano fundamental, desempeña un papel clave en la aplicación de otros derechos humanos. 
Invertir en la educación temprana de los niños romaníes pueden contribuir al fortalecimiento de la economía de la Unión Europea los Estados miembros. 
Según el representante, es necesario informar a la más amplia gama de personas - Roma y no-gitanos y - sobre estas interrelaciones. 
El anterior un joven estudiante de romaníes que asisten a la escuela comienza, el más grande de sus posibilidades será la de convertirse en un miembro productivo en el mercado de trabajo, a través de los ingresos y los impuestos pagados por ellos, iban a contribuir al presupuesto nacional. 
"Por razones de la ciudadanía el derecho aplicado en la Unión Europea, el derecho de una educación de calidad debe garantizarse para la población romaní y de baja calidad, la educación segregada deben ser eliminadas", añadió Lívia Járóka. 
También dijo que, a fin de acelerar inmediatamente los procesos de la lucha contra la segregación escolar, es necesario para garantizar un objetivo y orientado a la acción de cooperación dentro de la Unión Europea. Para lograr este objetivo, es fundamental para aplicar correctamente la existente y prevista directivas contra la discriminación. 
"El círculo vicioso de la pobreza, la segregación, el desempleo deben ser eliminadas, los niños romaníes deben contar con las oportunidades de la vida democrática a fin de que puedan contribuir para el futuro de Europa como ciudadanos con plenos derechos", exigió Járóka. 
En el marco del "Año Europeo de la Igualdad de Oportunidades", la Cumbre europea de la igualdad - primera organizada en Berlín el año pasado y desde entonces se celebró sobre una base anual - tiene por objeto proporcionar un foro único para promover los objetivos de la igualdad de oportunidades y la lucha contra la discriminación en Europa y los Estados miembros como así. 
