El geriatra afirma que las muertes fueron causadas por "la carencia de medios" 
Los dueños del centro de Olot no desechan a aquel su asistente matado más de 11 personas mayores 
La gente responsable con el hospital geriátrico que La Caritat de Olot (Gerona) ofreció a una rueda de prensa ayer a fin de subrayar el daño que ha causado a la institución la conducta criminal de Joan Vila Dilmé, la enfermera quien mientras allí mató a al menos once personas mayores que él tenía bajo la vigilancia. 
El director de la residencia, Joan Sala, pareció acompañado por el abogado del centro, la abogada Joan Canada, y anunció que "la intención de La Caritat iba para fijar la culpa en el individuo responsable de las muertes, pero "legalidad y la responsabilidad nos obliga a asumir la situación procesal de la gente responsable civil". 
Y esto además de la pérdida social del prestigio para el cual la organización puede encontrar no haber descubierto a tiempo las actividades criminales del vigilante, la gran amenaza para el Caritat tiene ahora toma la forma de una indemnización sustancial que es calculada ya por los representantes legítimos de los parientes de las víctimas. 
Joan Vila Dilmé ha admitido que el primer delito vuelve hasta el agosto de 2009 y que desde entonces él no dejó de matar. 
El juez ya mencionó en el documento que pidió la exhumación de ocho cuerpos - viejos pacientes del hospital geriátrico - a quien ella sospechó que en muchos casos ningún doctor personalmente exploró los cadáveres, pero, teniendo en cuenta la edad y las patologías de los pacientes, el procedimiento fue hecho por teléfono. 
La Caritat, por su director, totalmente negó este final ayer y mencionó que "la carencia de medidas no podía haber sido en cualquier momento la causa de lo que había pasado". 
El abogado de La Caritat añadió que "en la causa no hay ninguna indicación que hubo una acción imprudente de parte de cualquier otra persona que no es la culpable". 
El que bautizado como "el Ángel de la Muerte" admitió 11 asesinatos anteayer y detalló esto él destinó el primer delito el 29 de agosto de 2009 y un mes y medio más tarde, mató a otra abuela. 
En este caso una sobredosis de insulina le trajo la muerte; a diferencia del primer delito él destinó con una mezcla de pastillas sedativas. 
El director del Caritat dice que es complicado para controlar esto el personal del centro tiene el acceso a medicinas. 
La sobredosis de insulina y el cóctel sedativo habría sido el mecanismo usado en seis de los nueve delitos que la enfermera, en su ansia por aliviar el sufrimiento de los pacientes, usados o matanza de ellos. 
Pero las pruebas que están siendo realizadas en el laboratorio tendrán que clarificar si Vila no está e intentado para asegurar para sus primeras víctimas una muerte menos cruel o de, al contrario, ser quemado ellos internamente dándolos lejía cuando él ya admitió que había hecho con las tres mujeres que él mató entre el 12do y el 17 de octubre. 
En La Caritat ellos no dan la credibilidad al aspecto del vigilante, ni al número de asesinatos admitidos, que ellos no refutan ser superior, y justifica su actitud en las versiones diferentes que Vila ha dado en sus visitas al tribunal y las tonterías de cambiar su método de matar después haber destinado con éxito, ocho asesinatos. 
Esto es por qué ellos dicen que ellos se ponen a la disposición de justicia para clarificar el alcance de este acontecimiento. 
