El grupo catalán facilitó miles de pasaportes a Al Qaida 
Además de los siete presos en Barcelona, en Tailandia había tres 
Los siete paquistaníes y el nigeriano pasaron por agentes de la inteligencia de policía de Barcelona General formó un grupo jihadist que, dirigido de Tailandia, los pasaportes facilitados a grupos diferentes de Al Qaida, entre ellos "los Tigres para la Liberación del Territorio Tamilm" (LTTE) "y Laskar y Taiba" (Dejan), autor este último de los ataques de Bombay que causó la muerte de 106 personas en 2008. 
El Ministerio de Asuntos Internos ha prestado la atención a estas investigaciones, hasta el punto de asegurar esto con la operación "Kampai"; ha sido "debilitan" el aparato de falsificación de Al Qaida a un nivel internacional y, "por lo tanto, su capacidad vigente". 
Los investigadores calculan que la célula, durante los dos años que ha sido activo en Cataluña, ha sido capaz de enviar miles de pasaportes a Tailandia, donde ellos fueron falsificados y pronto distribuidos a los grupos que integran la galaxia criminal Al Qaida de modo que sus "combatientes" puedan cruzar las fronteras europeas y estos de otros países occidentales con la impunidad total. 
La célula desmontada no es la única que la red jihadist tenía en Europa, por esta razón en las investigaciones allí han participado, además de los servicios de Tailandia, otras unidades de policía europeas, razón por qué esto no desecha esto en el territorio de la Unión Europea ocurre que los acontecimientos similares al que desarrollaron la noche de martes en Barcelona. 
En la coordinación con esta operación (Pakistani Junaid Humayun, Atiqur Rehman, Jabran Asghar, Malik Iftikhar Ahmad, Mohammad Saddique Khan Begum, Tanveer Arshad y Nigerian Babatunde Agunbiade fueron todos parados), en Tailandia el otro se había desarrollado con la captura del Extremo de Pakistanis Muhammad Athar y Zeeshan Ehsan Butt y Thai Sirikanlaya Kijbumrung. 
El grupo asentado en España y otros países europeos fue dirigido de Bangcock 
La red catalana - la parte de ello fue golpeada en 2009 - pasaportes principalmente robados a turistas que realizaron las exigencias marcadas por la llamada "frente por todo el Mundo Islámico". 
O sea, los documentos tuvieron que ser en nombre de hombres entre 25 y 45 años, con la validez de varios años y sin visados impresos. 
En los medios de investigación se subraya que, para el momento, ningunos datos han sido encontrados relacionados con las personas detenidas en Cataluña en cuanto al ataque de Bombay, aunque el autor de este ataque, "Laskar e Taiba", haya sido uno de los grupos de recepción de los pasaportes robados en España y pronto falsificara en Tailandia. 
Sin embargo, hay que mencionar que días antes de este ataque comprometido, de Cataluña allí fueron enviados por una agencia de transferencias sobre algunos miles de dólares que fueron "invertidos" en la compra de naipes telefónicos móviles que pronto estuvieron usados por los miembros "del comando" que terminó la vida de 106 personas. 
Los Policías han capturado mucha documentación. 
