El programa nuclear paquistaní genera la gran agitación en los EE. UU 
Islamabad produce armas atómicas "a un precio más rápido que cualquier otro país". 
Las filtraciones de Wikileaks confirman los enlaces entre la gente de Talibán y Paquistán. 
El contenido de la correspondencia entre la embajada americana en Paquistán y el Departamento de estado de los EE. UU filtrados por la puerta Wikileaks confirma la agitación enorme que el programa nuclear paquistaní causa en Washington. 
Además de la ilustración y detalles sustanciales que son ofrecidos en el contenido de las conversaciones y los pensamientos de los representantes diplomáticos norteamericanos creídos en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de la seguridad atómica, en vez de aumento, "disminuciones", y que el país asiático inestable produce armas nucleares "con un ritmo más rápido que cualquier otro país". 
La particularidad del programa nuclear paquistaní - que las armas no son reunidas, pero ellos permanecen almacenados por componentes para hacer difícil su destrucción en caso del ataque - esto constituye una de las causas principales para la preocupación en Washington. 
Así es enumerado por el embajador en Paquistán, Anne W. Patterson, en un informe antes de la visita del ex - el consejero de la Seguridad nacional, James Jones: "la proximidad de algunas centrales nucleares en el territorio en ataque de Talibán, la dispersión rumoreada de los materiales nucleares y la vulnerabilidad de transporte de materiales atómico". 
Varias personas altas implicadas en los arsenales nucleares y los programas de misiles están siendo tenidas en cuenta, no sólo por los EE. UU, sino también por Rusia, como la razón de mantener su guardia. 
"Paquistán ha tenido que alquilar el personal con creencia religiosas estrictas a fin de proteger las centrales nucleares; considerando los niveles educativos y culturales pobres, las organizaciones extremistas tienen más oportunidades de reclutar a la gente para trabajar en los programas nucleares o de misiles", dijo la experta Yuri Carole, del Ministerio ruso de Asuntos Externos, en una reunión con sus americanos homólogos. 
La información más nueva sobre la documentación filtrada por la puerta de Julian Assange es la cooperación decreciente entre los EE. UU y Paquistán en sujetos de la proliferación nuclear y el precio paquistaní alto de la producción de arma nuclear. 
Una oficina de la embajada en mayo, que describe como "la frustración" de la comunicación con Paquistán, dice que: "la transparencia es con frecuencia inexistente; las ofertas de ayuda permanecen sin una respuesta o son rechazadas". 
En otro mensaje, Peter Lavoy, el funcionario de la Inteligencia Nacional para el sur de Asia, declara que "a pesar de la catástrofe económica, Paquistán produce armas nucleares en un ritmo más rápido que cualquier otro país del mundo". 
El embajador Patterson también pide a Washington, durante una visita de la cabeza del Ejército, el general Ashfaq Kayani, dar órdenes claras a la persona responsable que "el Ejército de Paquistán debe terminar el apoyo tácito a los grupos terroristas". 
