Nombramientos de Grammy: el cantante de jazz Esperanza Spalding es una elección de sorpresa en la mejor nueva categoría de artista 
Funcione a petición de un presidente, y la gente es obligada a hacer caso. 
El Esperanza Spalding, el bajista de jazz de 26 años y cantante escogido a mano por el Presidente Obama para funcionar en su ceremonia de Premio Nobel de Paz en 2009, marcó una de las sorpresas de Grammys este año con un nombramiento prominente en la mejor nueva categoría de artista. 
La consideración que Spalding ha sido una cifra famosa en la escena de jazz desde su álbum de 2008, "Esperanza", el nombramiento es un poco de una cabeza-scratcher, pero es consecuente con las reglas de Grammys de un artista que no suelta más de tres álbumes antes de la grabación que "establece la personalidad pública de aquel artista". 
Su álbum de 2010 ambicioso, "Sociedad de Música de Cámara", seguramente marcó un paso adelante, y dado su estilo vocal atractivo de manera confiada y una mano hábil con música pop, canguelo e influencias latinas, es posible dibujar al menos una línea de puntos a Spalding del éxito fugitivo de Norah Jone en 2003, el equivalente más cercano con votantes Grammy que miran hacia la vecindad del jazz en esta categoría en años recientes. 
En Otra parte los votantes de Grammy correctamente cumplieron "la Historicidad" de Vijay Iyer Trio en la categoría de álbum instrumental, un paseo de la emoción vigorizante de un registro que era un favorito crítico el año pasado. 
Entre aquellos Iyer competirá contra incluyen al saxofonista veterano James Moody "Malhumorado 4B" y "Positootly" de John Beasley keyboardist. 
Shorty de Trombón, una Nueva Orleans estentórea invitado favorito y frecuente en "Treme" del HBO, se honró en la categoría de jazz contemporánea, que por otra parte se inclina pesadamente hacia la fusión con cabezadas hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
La Sociedad Secreta de Darcy James Argue salvaje, steampunk-informado ganó un poco de reconocimiento merecido en la categoría de conjunto grande, que compite contra el jazz de la cámara rico de Billy Childs Ensemble y Dave Holland alguna vez aventurero, cuyo álbum vivo del octeto "Caminos" era un ejemplo fino de la mano democrática del bajista como un bandleader. 
