Romano va hacia su primer título 
Rubén Roman Omar cuenta con tres fracasos en los finales, que tienen durante sus altibajos de carrera, pero él sabía alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey en el final, además dos estilos diferentes marcados por la cara de sus técnicos, quiénes encuentran el uno al otro con un contraste marcado por resultados. 
Rubén Roman Omar cuenta con tres fracasos en los finales, que tienen durante sus altibajos de carrera, pero él sabía alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora él no hubiera alcanzado el objetivo y esto es por qué esta oportunidad es muy especial para él. 
El Argentinean ha terminado por ser consolado con la medalla de subcampeón, y permanecido un paso detrás de los ganadores y de modo raro con el equipo similar él ha jugado finales consecutivos. 
Santos llegó a su primer final como el entrenador en el Partido Inicial de 2002, cuando él tomó las rienda de Morelia con el cual él se cayó a 4-2 antes de Toluca; más tarde, en el Acontecimiento de Cierre de 2003 él también llegó al duelo decisivo y él también lo perdió en 3-1 y en efecto antes de Rayados. 
Ya con Santos Laguna, en el Partido de Bicentenario de 2010, otra vez antes Los Diablos, Rubén sufre otra vez un revés, ya que su equipo terminó igualmente coloca 2-2 antes de los fabricantes de salchicha después de que 210 minutos del juego, pero en la vuelta de penas se ponen en la ventaja por 3-1 con dos oportunidades de sellar el título, pero finalmente tres jugadores fallados de los 11 pasos y sufrieron el cambio 4-3. 
Rubén ya perdió dos finales con Diablos Rojos y un con Monterrey, su rival por su parte, por lo tanto él no quiere soportar el mismo destino, él quiere celebrar un título por primera vez, y él afirma que la cosa más importante para él es la institución. 
Quiero ser un campeón, no quiero la ruptura ninguna estadística, esto es para un club, para una pasión y por consiguiente el título vendrá a mí, pero la cosa anterior es lo que es más importante comentó el timonel siendo puesto en duda sobre los números contra los cuales él tiene jugando finales. 
Muy eficaz él tiene el final anterior, del cual, él asegura, ha aprendido mucho, "la única lección que podemos aprender es que hasta que el árbitro señale el final que no podemos celebrar, nos preparamos así como los jugadores porque la vez anterior, con dos penas estuvimos a punto de marcharnos y creo que es una lección para ser aprendida, no podemos divertirnos hasta los finales animosos". 
Sabiendo que esta serie podría ser definida en penaltys, algo que no le preocupa, porque él confía en sus jugadores: "nunca debería buscar yendo a penas, pero mejor dicho terminar en el tiempo regular; a veces usted no tiene ninguna alternativa y es necesario estar listo; en el partido anterior estuvimos preparados, lamentablemente destino jugado en nuestras manos; a veces por nervios o ansiedad de tener el título en da, pero no alcanzamos este objetivo, y esto nos abandonó algo para este final que esperamos ganar". 
El romano debería dejar de ser un subcampeón técnico y prueba por primera vez la gloria que los títulos dan. 
