El grupo catalán facilitó miles de pasaportes a Al Qaida 
Además de los siete presos en Barcelona, en Tailandia había tres 
Los siete paquistaníes y el nigeriano pasaron por agentes de la inteligencia de policía de Barcelona General formó un grupo jihadist que, dirigido de Tailandia, los pasaportes facilitados a grupos diferentes de Al Qaida, entre ellos "Los Tigres para la Liberación del Territorio Tamilm" (LTTE) y "Laskar y Taiba" (Dejan), autor este último de los ataques de Bombay que causó la muerte de 106 personas en 2008. 
El Ministerio de Asuntos internos ha prestado la atención a estas investigaciones, hasta el punto de asegurar esto con la operación "Kampai"; ha sido "debilitan" el aparato de falsificación de Al Qaida en un nivel internacional y, "por lo tanto, su capacidad vigente." 
Los investigadores estiman que la célula, durante los dos años que ha sido activo en Cataluña, ha sido capaz de enviar miles de pasaportes a Tailandia, donde se falsificaron y pronto se distribuyeron a los grupos que integran la galaxia criminal Al Qaida de modo que sus "combatientes" puedan cruzar las fronteras europeas y a estos de otros países occidentales con la impunidad total. 
La célula desmontada no es la única que la red jihadist tenía en Europa, por esta razón en las investigaciones allí han participado, además de los servicios de Tailandia, otras unidades de policía europeas, razone por qué esto no desecha esto en el territorio de la Unión Europea ocurre los acontecimientos similares al que desarrollaron la noche del martes en Barcelona. 
En la coordinación con esta operación (El paquistaní Junaid Humayun, Atiqur Rehman, Jabran Asghar, Malik Iftikhar Ahmad, Begum de Mohammad Saddique Khan, Tanveer Arshad y Babatunde Agunbiade nigeriano todos se pararon), en Tailandia el otro había desarrollado con la captura de los paquistaníes a Muhammad Athar Butt y Zeeshan Ehsan Butt y Sirikanlaya Kijbumrung tailandés. 
El grupo asentado en España y otros países europeos se dirigió de Bangcock 
La red catalana - la parte de ello se golpeó en 2009 - pasaportes principalmente robados a turistas que realizaron los requisitos marcados por la llamada "Frente islámico mundial." 
Es decir, los documentos tuvieron que ser en nombre de hombres entre 25 y 45 años, con la validez de varios años y sin visados impresos. 
En los medios de comunicación de investigación se insiste en que, por el momento, ningunos datos se hayan encontrado relacionados con las personas detenidas en Cataluña con respecto al ataque de Bombay, aunque el autor de este ataque, "Laskar e Taiba", haya sido uno de los grupos de acogida de los pasaportes robados en España y pronto falsificara en Tailandia. 
Sin todo, hay que señalar que días ante este ataque comprometido, de Cataluña allí se enviaron por una agencia de transferencias sobre varios miles de dólares que "se invirtieron" en la compra de tarjetas de telefonía móvil que pronto fueran utilizados por los diputados al "comando" que puso fin a la vida de 106 personas. 
Los Policías han capturado mucha documentación. 
