Los CIEGOS desechan una segunda ola grande de las fusiones en los bancos de ahorro 
El director de una dirección principal de los CIEGOS, Jose Antonio Olavarrieta, desechó ayer que una ola grande de fusiones de las cajas de ahorros va a tener lugar e insistió de nuevo en la rapidez con la que la reconstrucción el sector se está haciendo. 
Una vez que este proceso de concentración de las las cajas de ahorro españolas comenzó, el había varias organizaciones que han asegurado que ellos no participarían en esta primera fase y que serían esperan la segunda vuelta. 
Sin embargo, el jefe de una dirección principal de la Confederación española de Cajas de ahorros (CIEGOS), Jose Antonio Olavarrieta, desechó ayer que esta nueva ola grande de operaciones va a ocurrir. 
Creo que la mayor parte de las fusiones ha ocurrido, la incorporación de Cajasol al grupo de Banca Civica no se puede llamar un segundo round, sólo hay los ajustes. 
"La mayor parte completamente se hace; quizás en vez de 17 podríamos tener 13 o 14 pero todos los grandes procesos se han hecho bajo la vigilancia del Banco de España, que ha colaborado mucho a este asunto," señaló el gerente. 
En declaraciones durante un desayuno de Asociación de gerente y los Ejecutivos del Aragón (ADEA), Olavarrieta ha expuesto que el proceso de concentración se está librando "a la velocidad mayor posible, y debemos muy satisfacer del modo en que ocurre en los términos que entonces, no ahora, se marcaron en los planes del día con el Banco de España," enfatizó él. 
Ir de 45 bancos de ahorro con un promedio de 28.500 millones de volúmenes de activos a 17 con 75.500 millones es un proceso que no tiene la comparación en la historia, reduciendo el número de organizaciones al 62% de modo que sean mucho más grandes para cumplir Basilea, subrayó. 
Olavarrieta ha reconocido que hay "una serie de opiniones bastante pesimistas de la lentitud del proceso" que demuestra "la falta de seriedad y razón," porque "lo que el Banco de España hace debe recordar que hemos de cumplir el término antes de finales del año." 
El director de una dirección principal de CIEGOS, Jose Antonio Olavarrieta, aseguró ayer que España tiene el sistema financiero más riguroso de toda Europa y, "probablemente" de todo el mundo, y atribuyó los que hacen en duda la "ignorancia." 
El gerente mostró que, dentro de la coyuntura económica presente, "nos podemos muy relajar" con la situación de las organizaciones financieras y las cajas de ahorros, un sistema que ha emprendido un proceso de concentración "muy importante" y esto "va con la velocidad mayor posible." 
También recordó que el banco español salió muy bien con las pruebas de la tensión que el BCE hizo en julio. 
