El programa nuclear paquistaní genera la gran agitación en los EE. UU 
Islamabad produce armas atómicas a "un ritmo más rápido que cualquier otro país." 
Las filtraciones de Wikileaks confirman los lazos entre los ciudadanos de Talibán y Paquistán. 
El contenido de los intercambios de cartas entre la embajada americana en Pakistán y el Departamento de Estado de los Estados UU filtrados por el portal de Wikileaks confirma un tremendo trastorno que el programa nuclear paquistaní causa en Washington. 
Además de la ilustración y detalles sustanciales que se ofrecen en el contenido de las conversaciones y los pensamientos de los representantes diplomáticos norteamericanos creídos en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de la seguridad atómica, en vez de aumento, "disminuciones", y que el país asiático inestable produce armas nucleares con "un ritmo más rápido que cualquier otro país." 
La particularidad del programa nuclear paquistaní - que las armas no se reúnen, pero siguen almacenados por componentes para hacer difícil su destrucción en el caso del ataque - esto constituye una de los principales motivos de preocupación en Washington. 
Así es enumerado por el embajador en Paquistán, Anne W. Patterson, en un informe antes de la visita del ex - el consejero de la Seguridad nacional, James Jones: "La proximidad de algunas centrales nucleares en el territorio bajo ataque de Talibán, la dispersión rumoreada de los materiales nucleares y la vulnerabilidad de transporte de materiales atómico." 
Varias personas altas implicadas en los arsenales nucleares y los programas de misiles están siendo tenidas en cuenta, no sólo por los EE. UU, sino también por Rusia, como la razón de mantener su guardia. 
"Paquistán ha tenido que contratar el personal con creencia religiosas rigurosas a fin de proteger las centrales nucleares; considerando los niveles educativos y culturales pobres, las organizaciones extremistas tienen más oportunidades de reclutar a la gente para trabajar en los programas nucleares o de misiles," dijo el experto Yuri Carole, del Ministerio ruso de Asuntos exteriores, en una reunión con sus americanos homólogos. 
La información más nueva sobre la documentación filtrada por el portal de Julian Assange es la cooperación decreciente entre los EE. UU y Paquistán en sujetos de la proliferación nuclear y el precio paquistaní alto de la producción de la arma nuclear. 
Una oficina de la embajada en mayo, que describe como "la frustración" de la comunicación con Paquistán, dice que: "La transparencia es con frecuencia inexistente; las propuestas de ayuda permanecen sin una respuesta o se rechazan." 
En otro mensaje, Peter Lavoy, el funcionario de la Inteligencia Nacional para el sur de Asia, declara que "a pesar de la catástrofe económica, Paquistán produce armas nucleares en un ritmo más rápido que cualquier otro país del mundo." 
El embajador Patterson también pide a Washington, durante una visita de jefe del ejército, el general Ashfaq Kayani, dé órdenes claras a la persona encargada que "el ejército pakistaní es necesario retirar el apoyo tácito a los grupos terroristas." 
