IP solicita resultados del Congreso 
Eduardo Dávalos, el presidente del CEC, propuso que las autoridades asuman la gran responsabilidad de constituir un ejemplo para mejor Sinaloa por los retos diversos que debe hacer frente. 
Una Legislatura de trabajos decentes y libre de acuerdos entre los partidos y el estado Ejecutivo está siendo que pide el sector de la empresa de Mazatlán, porque hay Sinaloa convulsionado que afronta grandes problemas. 
Ayer la 60 legislatura se votó en, integrada por siete fuerzas políticas, 19 diputados del PRI, 13 de la CAZUELA, tres del Partido Nueva Alianza, dos de los PRD, uno del PUNTO, uno de Convergencia y uno más de los PVEM, queriendo decir un total de 40 representantes populares. 
Entre la lista de expectativas de los nuevos miembros del Congreso del S-estado se menciona que vienen para cumplir una dirección limpia de responsabilidad ante la sociedad y los sectores diferentes que requieren un trabajo legislativo responsable. 
Eduardo Dávalos Zamora, el presidente del Consejo de Coordinación de la Empresa, propuso que las 40 autoridades liberadas justas del Congreso del estado asumieran la gran responsabilidad de constituir un ejemplo para mejor Sinaloa por los retos diversos que debe hacer frente. 
Confiamos en que las autoridades realmente ejerzan su derecho, libre de acuerdos entre las partes porque tiene una larga para formalizar acuerdos para que se puedan por sus propios intereses y que se hacen un carácter en un carnaval de los gobernadores y los dirigentes de las fracciones parlamentarias. 
Por este motivo, ha hablado de la certificación de compromiso para fin de establecer los puentes necesarios que podrían ayudar a Gobernador a seguir adelante. 
Esperamos que vengan para hacer un trabajo digno y principalmente destinado a la sociedad y los sectores porque los habitantes de Sinaloa eran aquellos que les dieron el voto de confianza durante las últimas elecciones. 
Jose Ramon Manguart Sanchez, el presidente de la Asociación de Hoteles Tres Islas, consideró que uno de los mayores desafíos para los 40 representantes populares es el que de empujar y añadir fuerzas en busca del crecimiento económico del estado, porque hoy día la situación económica es muy complicada. 
Lo más importante es empujar el crecimiento económico, que genera incentivos para inversión y las infraestructuras y el sentido de que, en cierto modo, formará una nueva creación de puestos de trabajo. 
En lo que se refiere a la actividad turística, exigió que los nuevos legisladores tenga peso revisado en el presupuesto estatales para fortificar a la Secretaría de Turismo. 
Como he comprendido que este es el segundo departamento del Estado en menos presupuestos y es incongruente unas divisas de generación de la actividad económica e importantes y la inversión y la esto directamente rivaliza con la industria agro. 
Aparte del requerimiento de recursos de etiquetaje el turista que detona preve que ayudan a la seguridad que da al estado y actualizan la Ley de Alcohol que no ha sido capaz de solucionar en las legislaturas anteriores. 
