Acusadores no acusarán al senador Ensign 
Los acusadores del ministerio de la justicia han limpiado al senador John Ensign de acusaciones criminales que provienen de su asunto con un ex-ayudante de campaña y sus esfuerzos de asegurar el trabajo de cabildeo para el marido de la mujer, los abogados del senador anunciaron el miércoles. 
La decisión termina la amenaza legal más grave que se enfrentará el señor Ensign, el republicano de Nevada que se consideraba candidato presidencial republicano posible en 2012 hasta que el escándalo de su asunto hiciera titulares nacionales el año pasado y dañara su carrera. 
La oficina del Sr. Ensign dijo que él estuvo "seguramente contento" por la decisión, que siguió una investigación de un año entero. 
El senador todavía podría afrontar la medida disciplinaria por el comité del ética del Senado. 
Los defensores del Sr. Ensign dijeron que el Departamento de Justicia nos había "informado de que el senador Ensign ya no son el objetivo de la su investigación y que no tenga previsto traer presentar cargos contra él en este asunto." 
El Ministerio de la justicia rehusó comentar sobre el caso. 
El anuncio se hizo algo de una sorpresa a muchos abogados del ética fuera del Ministerio de la justicia, que dijeron pareció haber pruebas significativas para indicar que el Sr. Ensign puede haber confabulado violar una prohibición criminal del cabildeo federal. 
Las entrevistas, el correo electrónicos y otros documentos primero revelados en octubre de 2009 en el New York Times perfila que el Sr. Ensign había ayudado a Douglas Hampton, que ésa era una de sus ayudantes, trabajo de cabildeo lucrativo seguro para ganar silencio del Sr. Hampton y su esposa, Cynthia, sobre la cuestión del senador con ella. 
La Sra Hampton una vez sirvió del tesorero de una campaña de la Bandera. 
El Sr. Ensign se puso en contactos con diferentes promotores políticos para encontrar trabajo para el Sr. Hampton y luego abogado en su nombre después de que ambas habían contratado al Sr. Hampton para presionar para que se ellos, según los documentos y entrevistas. 
Como el Sr. Hampton había sido recientemente un ayudante del Sr. Ensign, se excluyó conforme a la legislación de cabildear a su ex-empleador o del Senado de conjunto durante un año. 
Los expertos del ética dijeron el arreglo extraño entre el Sr. Ensign y el Sr. Hampton, que eran amigos íntimos antes del asunto, apareció en conflicto con la llamada prohibición presiones de la puerta giratoria. 
De pruebas que se han hecho público, "allí pareció ser unas presunciones razonables de una conspiración para violar, y la violación sustancial del estatuto de la puerta giratoria," dijo Stanley Brand, un abogado de Washington que se especializa en la defensa de clientes investigados por el gobierno. 
Mientras los funcionarios del Departamento de Justicia rehusaron explicar el razonamiento que subyace la decisión adoptada en el el caso de la Bandera, el Sr. Brand y otros abogados del ética dijeron que los servicios pareció cauteloso de tomar procesamientos políticos tras varios reveses prominentes para su sección de integridad pública, incluso la decisión del año pasado para derribar los procesos judiciales contra el ex-senador Ted Stevens entre los costes de mala conducta de prosecutorial. 
Los acusadores federales "son claramente el arma tímida," dijo Melanie Sloan, el director ejecutivo de Ciudadanos para Responsabilidad y Ética en Washington, un grupo de promoción que trajo varias quejas contra el Sr. Ensign sobre el asunto. 
"Esto básicamente dice que los funcionarios superiores pueden suponer ahora que las leyes no se apliquen a ellos," añadió. 
Paul Coggins, principal defensora del Sr. Ensign, ha expresado en una entrevista que recibió una llamada telefónica de un fiscal del Departamento de Justicia el lunes y un seguimiento al día siguiente, diciéndole que los servicios no buscaba gastos contra su cliente. 
El equipo de defensa del Sr. Ensign había estado cooperando con acusadores en la tentativa de persuadirlos que el senador, ya que su oficina reiteró en una declaración el miércoles, "actuó de acuerdo con la ley." 
El Sr. Coggins rehusó explicar detalladamente los argumentos jurídicos que ha realizado a acusadores. 
"No soy entrar cómodo en los detalles tras mis conversaciones con el Departamento de Justicia salvo para decir que creemos que tomaron la decisión adecuada," dijo. 
El mes pasado, la Comisión electoral federal decidió derribar una investigación sobre una queja separada de un grupo de ética que alega que un pago de 96,000$ de los padres del Sr. Ensign a Hamptons violó la ley electoral federal. 
La comisión electoral dijo que no tenía bastantes pruebas para demostrar que el dinero era algo excepto un regalo. 
Una empresa en la que el Sr. Ensign ayudó al Sr. Hampton a encontrar trabajo de cabildeo era la energía NV, una empresa de Nevada principal que había mucho tiempo apoyando al senador. 
Un correo electrónico enviado al diciembre de 2008 demostró que tras el compañía trajo al Sr. Hampton en como un lobby, el jefe del estado mayor del Sr. Ensign, John Lopez, comunicado con el Sr. Hampton y le ha dicho que le "aporreaba" el Ministerio Interior sobre una cuestión con respecto a la disputa. 
El Sr. Ensign también asistió a un almuerzo con el Sr. Hampton y otro cliente de Nevada, Allegiant Air, y llamó al secretario de transporte para establecer una reunión en el nombre de la línea aérea después de que había contratado al Sr. Hampton para hacer el trabajo de cabildeo. 
Cuando las noticias del asunto primero emergieron el año pasado, el Sr. Ensign pidió perdón a sus componentes y dimitió su posición como el líder republicano que está del modo cuarto en el Senado. 
Después de intentar perfil bajo, durante muchos meses, el señor Ensign dijo a los periodistas hace dos semanas que planeó correr a un tercer mandato en el Senado. 
Al anunciar que el Sr. Ensign ya no eran objetivo de una investigación policial, su portavoz, Jennifer Cooper, ha dicho que el senador esperaba que el comité de ética siguiera rápidamente el ejemplo del Departamento de Justicia y terminaría su pregunta. 
"El senador Ensign tiene ganas de seguir su trabajo duro de parte de la gente de Nevada," dijo. 
