El geriatra afirma que las muertes fueron causadas por "falta de medios" 
Los propietarios del centro de Olot no desechan que su asistente mató a más de 11 personas de edad avanzada 
Las personas en la carga con el hospital geriátrico La Caritat de Olot (Gerona) ofreció una rueda de prensa para subrayar ayer el daño que ha causado a la institución el conducto criminal de Joan Vila Dilmé, la enfermera que mientras allí matado por lo menos once personas de edad avanzada que tuvo bajo vigilancia. 
El director de la residencia, Joan Sala, pareció acompañado del abogado del centre, el abogado Joan Canadá, y anunció que "la intención de La Caritat hace para cargar con la culpa el individuo responsable de de las muertes pero" la legalidad y la responsabilidad nos fuerzan a asumir la situación procesal de personas responsables civiles". 
Y eso aparte de la pérdida social de prestigio que la organización puede encontrarse con para no habiendo discernido calcula en las actividades criminales del guardián, la gran amenaza para el Caritat tiene ahora toma la forma de de una indemnización substancial que ya es calculada por los representantes legales de los parientes de las víctimas. 
Joan Vila Dilmé ha confesado que el primer crimen vuelve a agosto 2009 y que desde entonces él no paró la matanza. 
El juez ya mencionó en el documento que ordenó la exhumación de ocho cuerpos - pacientes viejos del hospital geriátrico- quien sospechó que en muchos casos no médico exploró personalmente los cadáveres pero, teniendo en cuenta la edad y las patologías de los pacientes, el procedimiento fue hecho por teléfono. 
La Caritat, por su director, negó completamente que este fin ayer y mencionó que "la falta de medidas no podría haber sido en cualquier momento la causa de lo que había sucedido". 
El abogado de La Caritat agregó que "en la causa no hay indicación que ha habido una acción imprudente en la parte de cualquier otra persona que no es el culpable". 
El uno bautizó como "Angel exterminador" confesó 11 asesinatos anteayer y detalló que cometió el primer crimen en el 29 de agosto de 2009 y un mes y una mitad mató más tarde, a otra abuela. 
En este caso una sobredosis de insulina le trajo la muerte; a diferencia del primer crimen que cometió con una mezcla de tabletas sedativas. 
El director del Caritat dice que es complicado para controlar que el personal del centro tiene acceso a medicinas. 
La sobredosis de insulina y el cóctel sedativo habría sido el mecanismo utilizado en seis de los nueve crímenes que la enfermera, en su ansia para aliviar el sufrimiento de los pacientes, utilizó o los matando. 
Pero las pruebas que son llevadas a cabo en el laboratorio tendrán que clarificar si Vila no está y trató de asegurarse de para sus primeras víctimas una muerte menos cruel o si, al contrario, los quemó dandolos internamente lejía como él ya confesó eso había hecho con las tres mujeres que mató entre el 12 y el 17 de octubre. 
En La Caritat ellos no le dan la credibilidad a la apariencia del guardián, ni al número de asesinatos confesados, que ellos no niegan ser superior, y justifica su actitud en las versiones diferentes que Vila se ha rendido sus visitas al tribunal y las tonterías de cambiar su método de matanza después de que habiendo cometido exitosamente, ocho asesinatos. 
De ahí que digan que ponen a sí mismo en la disposición de la justicia para clarificar el alcance de este acontecimiento. 
