El Gobierno español no puso objeciones con respecto a los vuelos de CIA 
El Gobierno español no puso objeciones con respecto a los vuelos de CIA con presos de talibán y de al-Qaeda que iban a Guantánamo a través de territorio español, según el el embajador de EEUU en el telegrama de Madrid. 
Así es reflejado por los documentos filtrados (cables) por Wikileaks al periódico El País, donde es agregado que el primer vicepresidente del Gobierno en aquel momento, Maria Teresa Fernandez del Vega, preguntó que el Ejecutivo español fue informado en la orden "poder demostrar que habían llevado a cabo la vigilancia apropiada procedimientos en el avión extranjero que cruza España". 
En junio 2006, después un informe del Concilio europeo donde había acusaciones de la complicidad en prácticas contra derechos humanos en una docena de países, entre que son España, una reunión sucedió entre el ex- embajador norteamericano Eduardo Aguirre y Fernandez de la Vega. 
El vicepresidente reconoció que el informe del concilio "había tomado el Gobierno de Zapatero fuera del juego" e insistido que España no tuviera nada ocultar con respecto a este asunto. 
"De la Vega acentuó que España no pone objeciones para los vuelos de la inteligencia sobre el territorio español". 
"Quieren simplemente ser informados" evitar "ser agarrado por la sorpresa", Aguirre relaciona en un telegrama. 
También el ex-ministro de Asuntos Externos, Miguel Angel Moratinos, indicó al embajador que el Ejecutivo español "quiso dar este asunto tan poca atención como posible, aunque estando en las manos de los jueces, el Gobierno tuvo una influencia limitada". 
Por otro lado, en enero 2007, el fiscal Vicente González transmitió a la Embajada que él no trataría de bloquear la iniciativa del juez de solicitar la desclasificación de documentos del Centro Nacional de la Inteligencia (CNI) y del ministerio de Defensa con respecto a los vuelos de la compañía" 
Esta información no contiene ningún elemento incriminatorio ni información sensible", explicó la Embajada después de hablar con el fiscal. 
No obstante, el EEUU reflejó en su preocupación para "la coordinación aparente entre el juez español y fiscales alemanes", más que la información desclasificada del CNI o el ministerio de Defensa. 
"Esta coordinación entre investigadores independientes complicará nuestros esfuerzos de manejar con discreción el caso entre Gobiernos"; dice Aguirre. 
En el 2007 de marzo durante un almuerzo entre el embajador del EEUU y el ministro de los Asuntos Internos, Alfredo Perez Rubalcaba, éste comentó a él que "aunque los jueces españoles estén rabiosamente celosos de su independencia y harán lo que consideran para tener razón", les había dado instrucciones a sus colaboradores "evitar comentarios de retórica inflamada, en una tentativa para reducir la temperatura". 
El embajador también expresa su preocupación para la acción del PP en este asunto. 
"A pesar de su profesional orientación general norteamericana, nuestra experiencia sugiere que el PP no dudará a capitalizar ninguna indicación que el Gobierno de Zapatero toleró ni acciones deliberadamente ignoradas del EEUU que podría ser interpretado como infracciones posibles de los derechos humanos, incluso si estas revelaciones tengan consecuencias negativas para el Gobierno del EEUU", indica. 
