El programa nuclear pakistaní engendra gran agitación en EEUU 
Islamabad produce armas atómicas en "una tasa más rápido que cualquier otro país". 
Las filtraciones de Wikileaks confirman los bonos entre las personas de talibán y Pakistán. 
El contenido de la correspondencia entre la embajada norteamericana en Pakistán y el Departamento de Estado del EEUU filtró por el pórtico de Wikileaks confirma la enorme agitación que el programa nuclear pakistaní produce en Washington. 
Aparte del aclarar y detalles substanciales que son ofrecidos en el contenido de las conversaciones y los pensamientos de los representantes diplomáticos, norteamericanos y acreditados en Islamabad, los documentos revelan que la cooperación entre ambos países en el asunto de la seguridad atómica, en vez de aumentando, "disminuciones", y que el país asiático inestable produce armas nucleares con "un ritmo más rápido que cualquier otro país". 
La peculiaridad del programa nuclear pakistaní - que los armamentos no son reunidos pero se quedan almacenado por componentes para hacer difícil su destrucción en caso de ataque -- constituye uno de las principales causas para la preocupación en Washington. 
Así es enumerado por el embajador en Pakistán, Anne W. Patterson, en un informe antes de la visita del ex- consejero de la Seguridad Nacional, James Jones: "La proximidad de algunas centrales nucleares en el territorio bajo ataque de talibán, la dispersión de rumoured de los materiales nucleares y la vulnerabilidad de transporte atómico de materiales". 
El número alto de personas implicó en los arsenales nucleares y los programas de misiles es tomado en consideración, no sólo por el EEUU, pero también por Rusia, como la razón para mantener a su guardia. 
"Pakistán ha tenido que emplear el personal con creencias religiosas estrictas para proteger las centrales nucleares; dados los niveles pobres, educativos y culturales, las organizaciones extremistas tienen más oportunidades de alistar a personas por trabajar en los programas nucleares o de misiles", dijo el experto Yuri Carole, del Ministerio ruso de Asuntos Externos, en una reunión con sus norteamericanos homólogas. 
La más nueva información en la documentación filtrada por el pórtico de Julian Assange es la cooperación disminuyente entre el EEUU y Pakistán en sujetos de proliferación de armas nucleares y la tasa pakistaní alta de la producción nuclear de arma. 
Una oficina de la embajada en mayo, que describe como "frustrar" la comunicación con Pakistán, dice que: "La transparencia es con frecuencia inexistente; las ofertas de ayuda se quedan sin una respuesta o son negadas". 
En otro mensaje, Peter Lavoy, el funcionario del estado de la Inteligencia Nacional para el sur de Asia, los estados que "a pesar de la catástrofe económica, Pakistán produce armas nucleares en un ritmo más rápido que cualquier otro país del mundo". 
El embajador Patterson también pregunta Washington, durante una visita de la cabeza del Ejército, el General Ashfaq Kayani, para dar órdenes claras al dirigente que "el Ejército de Pakistán debe terminar el apoyo tácita a los grupos terroristas". 
