Las nominaciones de Grammy: El cantante del jazz Esperanza Spalding es un escogimiento de la sorpresa en la categoría mejor nueva de artista 
Realice a petición de un presidente, y las personas tienen que tomar nota. 
Esperanza Spalding, el bajista de 26 años de edad de jazz y cantante cuidadosamente seleccionados por Presidente Obama para realizar en su Paz de Nobel ceremonia Premiada en 2009, marcaron uno de las sorpresas de los Grammys este año con una nominación prominente en la nueva mejor categoría de artista. 
Teniendo en cuenta ese Spalding ha sido una figura célebre en la escena de jazz desde su 2008 álbum, "Esperanza", la nominación es un poco de un cabeza-scratcher, pero es consecuente con las reglas de los Grammys de un artista que no suelta más de tres álbumes antes que la grabación que "establezca la identidad pública de ese artista". 
Su ambicioso 2010 álbum, "la Sociedad de Música de cámara", ciertamente marcó a un delantero de paso, y dado estilo vocal despreocupadamente atractivo y una la mano hábil con taponazo, el acobardamiento e influencias de latín, es posible dibujar por lo menos una línea de puntos a Spalding de Norah Jones éxito fugitivo en 2003, el equivalente más cercano a votantes de Grammy que miran hacia el vecindario de jazz en esta categoría en los últimos años. 
En otra parte votantes de Grammy honoraron bien la "Historicidad" del Vijay Trío de Iyer en la categoría instrumental de álbum, un emoción-paseo que revigoriza de un registro que fue un favorito crítico el año pasado. 
Entre esos Iyer competirá incluye en contra saxofonista de veterano "Moody 4B" de James Moody y el teclista "Positootly" de John Beasley. 
El trombón Bajo, un favorito ronco de Nueva Orleans y frecuenta a huésped en el HBO "Treme", fue honorado en la categoría contemporánea de jazz, que de otro modo inclina mucho hacia fusión con cabezadas hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
La tierra virgen, steampunk-informó Darcy James Discute la Sociedad Secreta ganó algún reconocimiento merecido en la categoría grande del conjunto, compitiendo contra el cámara-jazz rico Bilis del Conjunto de Niños y el Dave Holanda jamás-aventurero, cuyo "Sendas" vivas de álbum de octeto fueron un ejemplo fino de la mano democrática de bajista como un líder de grupo musical. 
