Con la Literatura ellos pueden poner el dedo en ello 
El segundo alrededor de Los placeres del idioma fue una caminata sobre que los participantes decretaron la narración 
¿Que de sexo en el idioma que comprendo que pero... el dedo en ello? Qué soy esperado hacer?, preguntó al escritor que Luisa invitó Valenzuela invitó a abrir el segundo alrededor de Los placeres del idioma, el acontecimiento que celebra la Literatura en español y en que utilizó esta vez el subtítulo de su pregunta (en otra manera que la mesa redonda fue dedicada al sexo en el idioma, ella explicó). 
El dedo en ello... "Nos pone en una posición difícil", dijo dulcemente derecho fuera el escritor argentino al público, principalmente de jóvenes, que encontró en la Feria Internacional del Libro de Guadalajara (FIL) escuchar este alrededor de mesa moderada por Marisol Shultz y Valenzuela participado, Sergio Ramirez, Montera de Mayra y Montera de Luis Garcia todo participado. 
Luisa Valenzuela leyó un texto que dedicó a Gonzalo Celorio y a que Shultz definiría luego como una gran historia, con Luisa en primero persona como el protagonista que en busca de conocimiento conocido como "", va del médico a tratar, de quien ella no obtiene respuestas aunque consiga atascado en el mismo hilo narrativo. 
Deja al médico convencido: "Quizás paciencia no es mi fuerte, quizá es la llaga". 
Al fin, después un enfoque frustrante con el médico de trauma que que clarifica esa llaga no es un término científico; es el sicoanalista que desenreda el misterio: "La llaga es la cosa abierta verdadera; la cosa simbólica es la cicatriz". 
El protagonista suspiró alivió y concluyó "en la llaga yo sólo logré saber que la cosa verdadera está abierta y que no existe", pero convenció que los placeres y las artimañas del idioma tienen que ser mezclados. 
Valenzuela, el escritor, jugó con los dos. 
El nicaragüense Sergio Ramirez también exhibió una narración deleitosa que tituló Elogio de la invención, donde el dedo en la llaga no es denominado pero es descubierto. 
En términos generales de realismo mágico, él dice la historia de una famosa bruja, que por nubes conmovedoras, devolvió a hombres que habían llegado lejos lejos o reparado las virtudes perdidas por una criada, la narración que se volvió hablar acerca de América, una gran novela que no faltó del empezando muy a sus propios cronistas que dijeron y del mencionado de Bernal Diaz Castillo que critica los excesos de las cosas dichos Por los capitanes que conquistan. 
Cervantes que nos inventó todo (los escritores) reído de los testigos falsos que parecieron en historias presentadas como verdadero, pero de otro modo él nunca habría dicho la historia de América con imaginación que falta la timidez. 
No obstante, acentuó "personas y mentirosos locos son los que mejor se imagina cosas" y es donde realidad y mentira son mezcladas, donde uno sabe si la cosa narrada pertenece a un lado u otro, donde la Literatura ficticia alcanza su apogeo. 
De hecho es denominado "tradición de Cervantes. 
"Para su filosofía de: somos lo que es dicho de nosotros". 
En cuanto a ella, el escritor que Mayra Montera vio y aplaudió la variedad de interpretaciones que la invitación de causas de FIL con ella pospone alrededor El dedo en la llaga. 
El cubano-puertorriqueño señaló su propio hacia la gran llaga de la violencia social que cruza su país - y divide Iberoamérica -producto de las disputas en la venta de tráfico y droga. 
Creo que la Literatura buena, poesía buena, canciones buenas cierran un compromiso tácita que por supuesto no es premeditado, indicó, después de mencionar que la realidad de la Literatura es la comunicación y la dimensión del compromiso que se establece entre autor y lectores, y eso es uno "reacción química" de esto último uno. 
La noche fue cerrada por la Montera española de poeta Luis Garcia cuya intervención también puso énfasis "que el dedo en la llaga del escritor comprometido a escribir". 
Consideró eso en un mundo que vive apurado, también en la aduana y control intelectuales del conocimiento que tiene efectos en dogmatismos, olvidándose "que detrás de cada afirmación que hay un pequeño no y detrás de cada negación hay pequeño sí". 
"Ser propietarios de nuestro pensamiento y la realidad que debemos clarificar: y clarificar a menudo medios para poner el dedo en la llaga y para molestar a esas personas que son mucho más cómodas pensando de la tira humorística, en blanquinegro, en ideas establecidos sin una sombra y también molestando a los poderes que prefieren un mundo blanquinegro", dijo, invitando a recuperar el sentido de escritura. 
