Romano va hacia su primer título 
Rubén que romano Omar cuenta con tres derrotas en los finales, teniendo durante sus subidas y downs profesionales, pero supo cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey en el final, además dos estilos diferentes marcados por la cara de sus técnicos, que encuentra uno al otro con un contraste marcado por resultados. 
Rubén que romano Omar cuenta con tres derrotas en los finales, teniendo durante sus subidas y downs profesionales, pero supo cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora él no hubiera alcanzado el objetivo y de ahí que esta oportunidad sea muy especial para él. 
El argentino ha acabado por ser consolado con la medalla de segundo, y se quedado un paso detrás de los ganadores y típicamente con equipo semejante él ha jugado finales consecutivos. 
Santos llegó a su primer final como entrenador en el Igual de apertura de 2002, cuando tomó las riendas de Morelia con que se cayó a 4-2 antes de Toluca; más tarde, en el Acontecimiento Final de 2003 él también llegó en el duelo decisivo y él perdió también en 3-1 y verdaderamente antes de Rayados. 
Ya con Santos Laguna, en el Igual Bicentenario de 2010, otra vez antes de Los Diablos, Rubén sufre otra vez un revés, desde que su equipo terminado coloca igualmente 2-2 antes de los fabricantes de salchicha después de 210 minutos de juego, pero en la vuelta de penas se puso en la ventaja por 3-1 con dos oportunidades de sellar el título pero por último tres jugadores fallaron de los 11 pasos y sufrieron el cambio 4-3. 
Rubén ya perdió dos finales con Diablos Rojos y con uno con Monterrey, su rival en cambio, por lo tanto él no quiere aguantar el mismo destino, él quiere celebrar un título por primera vez, y él afirma que lo más importante para él es la institución. 
Deseo es un campeón, yo no deseo interrupción ninguna estadística, esto es para un club, para una pasión y por consiguiente el título vendrá a mí, pero la cosa anterior es más importante, comentó que el timonel para ser preguntado acerca de los números él tiene jugando en contra finales. 
Muy efectivo tiene el final anterior, de que, se asegura de, ha aprendido mucho, "la única lección que podemos aprender es que hasta que el árbitro señale el fin que nosotros no podemos celebrar, nos preparamos así como los jugadores porque el tiempo anterior, con dos penas nosotros estuvimos a punto de salir y creo que eso es una lección para ser aprendido, nosotros no podemos celebrar hasta que el juego termine". 
Saber que esta serie podría ser definida en penaltis, algo que no lo molesta, porque se fía de sus jugadores: "Uno debe nunca busca ir a penas, sino para terminar en el tiempo regular; a veces usted no tiene ninguna alternativa y es necesario para estar listo; en el igual anterior que fuimos preparados, desafortunadamente destino jugó en las manos; a veces por nervios o ansiedad para tener el título en fuera manos, pero nosotros no alcanzamos este objetivo, y esta izquierda nosotros algo para este final que esperamos Para ganar". 
Romano debe parar ser un segundo técnico y probando por primera vez la gloria que los títulos dan. 
