NASA anunciará el descubrimiento la vida extraterrestre 
La agencia norteamericana del espacio llamó la prensa a presentar mañana un descubrimiento que causará impacto en la búsqueda de seres vivos en el espacio. 
La Administración Nacional para el Espacio y la Aeronáutica (NASA) de Estados Unidos presentará mañana, el jueves, un descubrimiento de astrobiological, que podría demostrar la teoría que hay la vida extraterrestre. 
El descubrimiento será presentado en una rueda de prensa mañana el jueves a las 13:00 de la tarde en sede de NASA en Washington por expertos en la astrobiología; una ciencia describió como el que estudia el origen, la evolución, la distribución y el futuro de la vida en el Universo. 
Al llamar la prensa, NASA se aseguró de que presentará "un descubrimiento que causará impacto en la búsqueda de la vida extraterrestre", que provocó especulación por expertos en otros países. 
El descubrimiento podría demostrar la teoría que hay criaturas que se parecen a nosotros viviendo en espacios hostiles que son pensados de como inhabitable, y pondrían la mesa la posibilidad que llegan a ser seres inteligentes como humanos si mejoran sus condiciones de vida. 
Aparentemente es concentrado en un microbio que fue encontrado en el fondo del Lago de Mono en el Parque Nacional Yosemite, California, donde vive en un ambiente que fue considerado demasiado tóxico para cualquier forma de la vida, desde que el lago es rico en el arsénico. 
De algún modo, la criatura utiliza arsénico para supervivencia y fuera de esta capacidad aumenta la posibilidad que la vida semejante podría existir en otros planetas que no tienen nuestro ambiente benévolo. 
Según astrobiologists, si estos organismos utilizan arsénico en su metabolismo, será demostrado que "hay verdaderamente otra forma de la vida, una segunda forma de la vida, diferente del uno nosotros sabemos". 
La agencia del espacio presentará la extensión llena de los descubrimientos en la rueda de prensa de mañana el jueves. 
Pamela Conrad, que estudia la posibilidad de la vida en Marte; y el biólogo Steven Benner, uno de los científicos que estudian a Titán (la luna más grande de Saturno), bajo la perspectiva que su química es semejante al uno de la Tierra que ambos asistirán la conferencia. 
