La totana detenidos el alcalde y el jefe de la policía local en un presunto de city-planning la corrupción
La guardia civil ha retenido la actual alcalde del municipio de murcian totana, "la" José Martínez andreo, el jefe de la policía local, el Secretario del Ayuntamiento y un empresario sobre posibles city-planning hostal crímenes, fuentes nos han informado de hoy.
La edil fue detenido en su casa, abordar y se ha transferido al consistory, en cuya dependencias en estos momentos con varios agentes, que también han ido a la gestión y el Consejo urbana industriales y las viviendas de suelo.
Estos tres detenciones se añaden a seis presentadas el pasado lunes en Galicia, Murcia y Madrid, en una operación vinculada a la recalificar de más de 2 millones de hectáreas de tierra a rustic urbanizeable para que los gallegos, empresa nuaria construido 4.000 casas, tras el pago de comisiones durante la última legislatura.
Además, otras dos personas fueron detenidas pero no en el resumen, que establece que el Tribunal totana el número 1.
Los seis primeras detenciones han ido ante el Tribunal hoy.
Según fuentes de información, el anterior alderman de totana autonomic parlamentaria y real del PP, Juan morales, se está investigando.
Además, la antigua esposa, propietario de una agencia inmobiliarios en totana, ha sido arraigned, como es el actual de la antigua girlfriend alderman que reside en Murcia capital.
El director y propietario del Grupo nuaria, el abogado y industralist Vigo Manuel n.a., fue detenido en nigrán (Pontevedra), como se Pablo José m.g., terreno director de inmonuar, una agencia de integración en el mencionado Grupo, y a través de los cuales los sobornos, se han hecho.
La investigación es la responsabilidad de los crímenes city-planning grupo de oficina central (uco) de la guardia civil, cuyos agentes, además de las detenciones, once de registros, la mayoría de las empresas relacionadas con los detenidos y situadas en Madrid, Vigo, Murcia, Pontevedra, Madrid y totana.
Una persona fue detenido en totana, en particular, el propietario de las aves de corral producto empresa conocido en la región, que podría haber actuado como intermediaria.
El Grupo nuaria responsable para el desarrollo de lo que se ha convertido en el mayor de los complejos residenciales murcian municipio de totana, que incluye la construcción de más de 5.000 casas, un campo de golf y dos hoteles con "ZPE".
La empresa adquiridos en totana 2,2 millones de metros cuadrados de tierra que fueron recalificados y su proyecto presupone la duplicación de la población del municipio, que ha 25.000 habitantes.
El Grupo nuaria inomonuar autesa y empresas como integra, dedicada al desarrollo inmobiliarios; conycase, que gestiona el estacionamiento sedes de las calles de Coruña, Venezuela y la plaza de Fernando católicos; hogartel, dedicado al sector de la comercialización directa, preconiza por centrarse en la promoción, la venta y la instalación de los elementos de la construcción.
