El seis por ciento y Hungría environmin
Ministra de Medio Ambiente, ha dicho que gábor fodor nivel profesional reuniones sobre el clima internacional posterior a 2012 terminará el martes. La propia Conferencia abre oficialmente el miércoles, cuando los Ministros tomar la palabra.
Los profesionales y políticos de 192 países Bali slated para debatir la hoja de ruta que se centra en los esfuerzos para reducir las emisiones de gases de efecto invernadero para después de 2012, cuando el Protocolo de Kioto expira.
En la actualidad, los países en vías de desarrollo y países desarrollados en medio de una gran controversia.
Los Estados Unidos han hecho saber que no está dispuesto a negociar cifras exactas, aunque no se opone a un 25-40 por ciento reducción de los gases de efecto invernadero de aquí a 2020 con respecto a 1990.
La otra cuestión en la Conferencia es si los países desarrollados están dispuestos no solo a reducir sus emisiones sino también a ofrecer asistencia técnica y financiera a los países que la necesiten.
Un acuerdo alcanzado el apoyo a los países en vías de desarrollo.
Un Consejo 16-member va a gestionar los fondos, que se establece en el Protocolo de Kyoto, y más probable es que el trabajo en el seno de las Naciones Unidas para el medio ambiente mundial gef), escribe la publicación piac és beneficios.
Hungría seis por ciento de
En Hungría, Ministro de Medio Ambiente gábor fodor está dispuesta a apoyar los esfuerzos de la UE para mantener su buque insignia papel en la protección del clima mundial y promover un nuevo acuerdo internacional, para el año 2009.
Fodor observar que la Unión Europea tiene su mirada en un 20 por ciento de las emisiones de gases de efecto invernadero de aquí a 2020 con respecto a 1990, si la "para después de 2012 de acuerdo" es alcanzado o no, y está dispuesta a reducir en un 30 por ciento si las otras grandes regiones del mundo y los países en vías de desarrollo estén también dispuestos a aceptar compromisos a la medida de sus posibilidades y responsabilidades.
Fodor ha dicho que en 1997, los países que se adhieren al Protocolo de Kyoto ha dirigido el 5,2% de reducción de las emisiones. En el seno de ese grupo, la UE de 15 miembros acordaron un 8 por ciento.
Hungría acordado reducir sus emisiones de gases de efecto invernadero del 6 por ciento en comparación con 1985-1987, un objetivo va a cumplir, dijo que la nota de prensa del Ministerio de Medio Ambiente.
Lo que está en juego en Bali son elevadas, por un acuerdo internacional sobre la política climática a largo plazo debe ser en secreto dentro de dos años, o bien, sin duda no podrán entrar en vigor para el año 2012. De este tipo, las promesas hechas durante la vigencia del protocolo de Kioto no se siguió inmediatamente por otro régimen emissions-reduction, la necesidad de que la ONU nobel-prize ganar órgano científico, el panel intergubernamental sobre el cambio climático, ipcc- ha señalado en su último informe.
El resultado podría ser un retraso en la reducción de emisiones, que pondría la tierra en el camino hacia un aumento de la temperatura media superior a 2 grados Celsio. Si esto ocurre, los científicos dicen las consecuencias graves e irreversible.
