Israel : Chaos Lab.
"Nada viene de la violencia y nada podía," de Sting Fragile, donde uno de los versos del estribillo es "Para que no olvidemos lo frágiles que somos."
"Si mis hijos no querían la guerra, no habría ninguna", dijo el Schnapper Gutle morir, esposa de Mayer Amschel Rothschild en 1849.
La última ola de violencia entre Israel y la Franja de Gaza, como siempre, ha suscitado una gran reacción.
Algunas soporte por parte de Israel, argumentando que tiene derecho a la legítima defensa, y los palestinos son presentados como terroristas, mientras que otros apoyan a los palestinos, alegando que el racismo por el Estado de Israel, alegando que el genocidio que se está cometiendo contra los árabes palestinos, y que Israel es un estado terrorista.
No quiero detenerme, en estas ondas periódicas repetidas de asesinato, el que es el transgresor y quién es la víctima, después de todo, los actuales habitantes de Israel, incluidos los territorios autónomos, han nacido en la actual situación política y no vivir con el inicio de la violencia.
Me gustaría ofrecer a los lectores un vistazo detrás de las escenas, una mirada a los que, por encima de todo, esta tensión a largo de 95 años está sirviendo (a partir de la declaración de Balfour, en noviembre de 1917) en este pequeño pedazo de tierra en el Oriente Medio.
Algunos de mis pensamientos son compatibles con los hechos históricos disponibles, mientras que otros se derivan de mi propia comprensión de quién, es decir, a qué grupo de personas es la fuente principal de los acontecimientos de la historia moderna.
La historia humana es, en primera instancia acerca de la lucha por el poder.
En todas las épocas podemos encontrar un Alejandro Magno o un Napoleón.
Lo que no es tan evidente es si éstas eran las personas que habían elegido su camino de forma independiente, o si detrás de su trono puso alguien que dirige sus acciones hacia un objetivo previamente calculado.
Tenemos que aceptar que vivimos en una época en que la riqueza del mundo se concentra en manos de unos pocos individuos, y que esta concentración de la riqueza y el poder que emana no podría suceder en la vida útil de una generación.
Entre estas familias astronómicamente ricos, se destaca, que podría ser considerado el maestro de las marionetas (si alguien está por encima de ellos, no estoy seguro, pero yo no lo descartaría) - los Rothschild.
No se ha escrito mucho acerca de ellos.
Es comprensible.
La primera agencia de noticias (Reuters) se compró en los años 90 del siglo 19, con el fin de evitar que su nombre está relacionado con actos de alta criminalidad, que aparecieron en sus antecedentes y que siempre significaba el poder de fijación, aumento de la riqueza, o ambas cosas.
Ellos tienen participaciones mayoritarias en casi todos los bancos centrales del mundo, y en contra de los países donde aún no tienen una participación, o bien son librando o la preparación para la guerra (antes del asalto a Afganistán fue 7 países, después de que Irak era 5, tras el derrocamiento de Gadafi 4 se mantuvo, pero mientras tanto Rusia presentó su banco central al Gobierno de Rusia).
El que intentó desafiar a esta familia murió.
Abraham Lincoln se negó a renovar la condición de que el banco central del Banco Rothschild de América, y durante la Guerra Civil comenzó a emitir su propia (que es emitida por el estado) el dinero y fue asesinado en 1865 en el teatro.
JFK comenzó a emitir su propio dinero y quería cerrar la Fed (Reserva Federal), y murió en 1963, el congresista Louis McFadden fue envenenado en 1936, después de que él tenía la intención de demandar a la Fed para hacer que la Gran Depresión de 1929.
Su sed de poder mundial llevó en los años de 1859 - 1871 para la formulación de un plan de tres en el mundo de la guerra por el líder masón del grado 33, Albert Pike.
La primera guerra para eliminar los grandes cuerpos del Estado monárquico en Europa, el segundo fue para eliminar la dominación colonial, especialmente de Gran Bretaña, y la tercera será reducir la población mundial a 0,5 hasta 1000 millones de personas (el número de esclavos serán suficientes para la comodidad y el lujo, y no consumir tantos recursos), la creación de una fe universal (ecumenismo es sólo un aperitivo para esta solución), y, finalmente, la toma del poder absoluto.
El método, que el grupo de familias adineradas con los Rothschild a la cabeza, el empleo es la instigación de las crisis, seguido por la oferta de una solución (para ab chao - orden del caos).
Estas soluciones son falsas, sin embargo, y siempre conducen a una situación peor (vide creación de la Reserva Federal, por lo que la crisis de 1907 no se repita).
Por lo tanto, después de haber logrado asesinar a Ferdinand, el heredero de los Habsburgo al trono austro -húngaro, en Sarajevo, desencadenando con ello la Primera Guerra Mundial, que destruyeron la Rusia zarista con la revolución bolchevique.
La Primera Guerra Mundial terminó abruptamente, militar y económicamente sin fundamento, con la capitulación alemana (la guerra ya no era necesaria para destruir la Rusia zarista) y las potencias europeas centrales de Austria -Hungría fueron posteriormente desmantelados.
Para facilitar el inicio de la Segunda Guerra Mundial, permitieron que banqueros y políticos para crear una situación de conflicto latente por ensillar Alemania con enormes reparaciones de guerra, haciendo con ello un ejemplo radicalist de las masas empobrecidas, no quedaba más que introducir un culpable suficientemente convincente y un líder con una solución sencilla y al mismo tiempo crear una Checoslovaquia multirracial con una fuerte minoría alemana que desempeñar, y de hecho lo hizo, el papel de la quinta colonia, una vez que la guerra había sido encendido.
A finales del siglo 19, los Rothschild instigó la creación del movimiento sionista, una rama de la que se esforzó para formar el Estado judío, en busca de un espacio histórico de Judea, Jerusalén, para que su capital (el retorno a Sión).
La Declaración Balfour mencionado sirvió de base para la inmigración masiva de Judios a Palestina, donde comenzaron los primeros conflictos con la población árabe local.
Los ataques terroristas ocurridos en ambos lados.
Segunda Guerra Mundial estalló, y si Hitler se liberó de la correa, que los banqueros internacionales lo tenían encendido, o si sus acciones eran parte del plan, es difícil de determinar, sin embargo, el sufrimiento de los Judios Europea en los campos de concentración creados la base de la aceptación en el mundo del Estado judío.
Israel se formó oficialmente en 1948, y al igual que las reparaciones de guerra de la Segunda Guerra Mundial se nos extienden a Alemania, el anuncio de que el Estado de Israel se convirtió en caldo de cultivo de la tercera guerra.
Siempre que los banqueros internacionales tienen éxito, la nación judía, al igual que el segundo, serán las víctimas en la línea del frente, ahora junto con el árabe - o, más generalmente, los musulmanes - la población de Oriente Medio.
Israel es como un inmenso laboratorio, una fuente de la discordia y el caos no sólo dentro del país sino a nivel internacional (basta con ver la fuerza con las personas se dividen en partidarios y adversarios de Israel).
¿Quién es el malhechor y quién es la víctima en el conflicto entre Palestina e Israel, donde la injusticia engendra la injusticia en un ciclo sin fin de la violencia, mientras que todo comenzó a partir de la codicia de unos pocos y sus ansias de poder global?
En este caso, hay que diferenciar entre la población general de Israel y sus líderes, ya que, tal como sucede aquí, los banqueros internacionales introducen su propia selección de los candidatos a la gente a votar.
Actual primer ministro de Israel, Netanyahu ' halcón ', es un ejemplo típico de un político fascista, fiel a los banqueros internacionales, que hace de todo para instigar a la guerra con Irán, lo que, debido a su pertenencia a la Organización de Cooperación de Shanghai (China, India, Rusia, Pakistán,...) conducen a una mayor amenaza de un conflicto mundial, ya través de su control del estrecho de Ormuz, donde el 20% del petróleo del mundo, debe navegar (el canal está a sólo 2 millas de ancho), a la destrucción de la economía del mundo.
En lo que la luz se destacan las palabras, pronunciadas por David Rockefeller en 1994 : "Todo lo que necesitamos es una gran crisis y las naciones aceptarán el Nuevo Orden Mundial."
El Nuevo Orden Mundial en sus ojos es una de amo y esclavo.
Un mundo en el que el resto de la población humana servir el lujo de un puñado de aristócratas financieros.
Un mundo en el que cada recién nacido es implantado con un chip, lo que hace que su existencia completamente subyugado.
" Y hacía que a todos, pequeños y grandes, ricos y pobres, libres y esclavos, se les pusiese una marca en la mano derecha o en la frente, de modo que nadie pudiera comprar ni vender, sino el que tuviese la marca, que es el nombre de la bestia o el número de su nombre.
El que tiene entendimiento, cuente el número de la bestia,
pues es número de hombre. Y su número es seiscientos sesenta y seis ".
