'Sangre de mayo', la apuesta épica de Garci 
Inspirándose en los Episodios Nacionales de Benito Pérez Galdós, José Luis Garci recrea el célebre levantamiento de los españoles contra los franceses en Sangre de mayo, la que es la película más ambiciosa en su filmografía con cerca de 15 millones de euros de presupuesto. 
De esta forma, el cineasta ha intentado "ilustrar el torrente de personajes y el análisis social" que siempre ha admirado en la obra del conocido novelista, ha explicado hoy durante la presentación de la cinta, con Quim Gutiérrez y Paula Echevarría al frente de un amplio elenco de intérpretes. 
Sangre de mayo, con un metraje superior a las dos horas y media, se estrena este viernes en las salas cinematográficas, para convertirse en el futuro en una miniserie para Telemadrid de más de cuatro horas de duración. 
Gran admirador de la literatura de Galdós, José Luis Garci asegura haber cumplido con este rodaje "un sueño de infancia", que debe agradecer a Esperanza Aguirre, quien desde la Comunidad de Madrid le encargó hace tres años rodar una cinta conmemorativa por el segundo centenario del 2 de mayo madrileño, algo que aceptó siempre y cuando el relato estuviera basado en los Episodios Nacionales. 
Los 15 millones de presupuesto que ha aportado en su totalidad la Comunidad de Madrid constituyen para Garci una "oportunidad única" de ambientar con los decorados y el vestuario adecuado el retrato de "una España atolondrada que se equivocó de jefe por el que luchar, ya que, la lucha por la independencia llevó al pueblo a enorme retraso con el reinado de Fernando VII", ha apuntado. 
Pero el cineasta lamenta no haber contado con una financiación como la de Alatriste o Los fantasmas de Goya - más del doble de la de Sangre de mayo-, por lo que no ha podido rodar algunas escenas plasmadas en un guión firmado junto a Horacio Valcárcel, con quien ha colaborado en casi toda su carrera. 
Por ello, el director de Volver a empezar, ha incidido en la que es su forma habitual de trabajo, la puesta en escena con los actores, con los que suele ensayar antes de iniciar el rodaje y a los que no hace casting, por parecerle "humillante" y considerar que "parte del oficio del director reside en acudir al teatro y al cine para conocer lo que ocurre en la industria en la que trabaja". 
Muchos de los intérpretes con los que coincide en Sangre de mayo repiten ante su cámara, como es el caso de Miguel Rellán, de Carlos Larrañaga o de Fernando Guillén Cuervo. 
Candidato al Oscar en cuatro ocasiones - de las cuales ganó una-, Garci considera que cualquiera de las tres candidatas a representar a España este año ante la Academia de Hollywood, la propia Sangre de mayo, Siete mesas de billar francés y la finalmente seleccionada, Los girasoles ciegos, no representan a una joven generación del cine español, "que es la que debe darse a conocer", ha asegurado. 
Con esta película Garci no espera premios. 
"En los inicios crees que trabajas para la posteridad, luego te das cuenta de que sólo trabajas para la prosperidad, y ahora te conformas con hacer una película más", explica Garci tras más de 30 años de trayectoria profesional. 
