Las elites en peligro 
El fenómeno se había ya manifestado algunos días atrás con el voto de la camera de los representantes contra el plan de salvación de 700 millones de dólares puesto en marcha por la Casa Blanca: una parte significativa de americanos era, y esta, mas interesada a castigar Wall Street que a salvar la economía. 
Nos da una confirma el New York Times de ayer informándonos que la crisis en curso está desarmando el partido Republicano, siempre mas dividido entre su vieja alma de la Costa Este, moderada, favorable a las instituciones federales y al business community, y su nueva alma, en cambio, conservadora, hostil a"aquellos de Washington» y al mundo de la finanzas, fuertes sobretodo en los estados del Centro y del Sur. 
El alma, de hecho, que se ha convertido prepotente con el voto de quien hablaba al principio. 
Esto apenas citado es solo un ejemplo de las mutaciones, de los grandes mutaciones, que el terremoto económico en curso anuncia: no solo en los Estados Unidos sino en todos el Occidente y no solo aquí solamente. 
Sea en los Estados Unidos como en Europa desde hace tiempo la crisis parece funcionar como acelerador de fenómenos de incubación que con el nuevo clima se solidifican y salen a la luz. 
El primero de estos fenómenos es la re actualización, la extraordinaria reactivación, de la doble categoría estado-soberanía en relación a un tipo de re nacionalización de la economía. 
La crisis, efectivamente, es una crisis de instituciones bancarias- financiaría las cuales tienen, si, fuertes relaciones financiarías con el exterior, pero sobretodo están comprometidas mucho más los balances de las familias que viven en un único país y en un único estado. 
El que crea inmediatamente un problema político para quien lo gobierna: es decir cómo responder a la dificultad y a las protestas de aquellas personas y de aquellas familias que, por otra parte son electores. 
La crisis aparece económicamente mundial pero es políticamente y exclusivamente nacional. 
El internacionalismo político parece sustancialmente fuera de juego o no tienen mucho para decir: la prueba crucial es La Unión Europea que dividida como siempre entre los distintos intereses y las diferentes estrategias estatales no alcanza decidir ninguna política en común. 
Es del gobierno de cada estado que todos se esperan una intervención, planes de rescate y de reactivación, de nuevas reglas y sobretodo  la subvención de fondos: desde el momento que se llega al corte  es solo el estado que posee los recursos económicos y la masa de recursos financiaros para remediar las cosas. 
Y poseen también los medios necesarios y la legitimación a usarlos: dos recursos de valor incalculable, valores en ciertas circunstancias en la cual ningún mercado probablemente y ninguna organización podrá jamás disponer en la misma medida. 
Esta nueva énfasis que la crisis pone sobre el estado-nación es en perfecta sintonía, con la mayor importancia siempre que el nuevo desarrollo de la  economía tiende a atribuirle a un factor muy coligado a ese elemento: la territorialidad. 
Paradójicamente, mientras estábamos convencidos de haber entrado en la red de la tecnología siempre mas sofisticada, del inmaterial, mientras estábamos convencidos que la finanza global estaba ya destinada a dominar el mundo, nos dimos cuenta que nuestro futuro tendrá en cambio que hacer las cuentas cada vez mas con las cosas poco inmateriales como el agua, los cultivos y el petróleo. 
Todas cosas que, fíjate, pueden ser ciertamente transportadas de un lugar al otro de la tierra pero son igualmente unidas en modo absoluto en un espacio circunscrito, un territorio. 
Así que quien se encuentra como soberano, posee ciertamente muchas mas cartas respecto a quien no lo es, y a quien tiene la desgracia de vivir en un puesto sin cultivos, sin petróleo y sin agua. 
Llego a la segunda novedad que pero presagia una fractura. 
Quien dice Territorio, Estado, Gobierno, inevitablemente dice Política y Liderazgo. 
En este sentido la crisis económica parece producir dos fenómenos convergentes. 
Por un lado la conciencia objetiva de la necesidad de una liderazgo, la petición de alguno que sepa tomar en mano la situación. 
Por otro lado una onda de descrédito para los liderazgos existente, de especie económica relevada inadecuadas con muchas zonas oscuras. 
Y juntos algo mas profundo y en un cierto sentido inquietante: un descrédito, una intolerancia, una imagen inadecuada, un sentido de lejanía, que tiende a  implicar la entera clase dirigente de los países del Occidente en un número creciente. 
Parece avanzar siempre más, en diversos lugares de la población, la convicción que antes que sus acciones sean las mismas que las de las elites sociales hasta ahora en auge, el mismo modo de sentir y de ser, su cultura en la excepción comprensiva del termine, a haber hecho el propio tiempo y a ser mas extraño a las opiniones de la mayoría. 
La demanda de liderazgo, en pocas palabras, alimenta subterráneamente un movimiento ramificado pero potente de  deslegitimación de las clases  dirigentes y de los estructuras políticas tradicionales, que se manifiestan en una"revuelta» electoral o en los cambios repentinos de humores colectivos de estos últimos tiempos, desde la salida conservadora en Austria-Baviera al colapso del consenso social-democrático en Gran Bretaña, a la rebelión de los hombres del congreso americanos contra Bush (y capas también con la victoria de la derecha en Italia que tiene algo que ver). 
Se tiene la impresión que las elites tradicionales, sus partidos, sus programas, pero también sus ritos, sus periódicos, sus intelectuales acreditados, su formato diría alguno, hagan siempre más dificultad a comprender y entonces a representar, aquello que desde hoy que está tomando forma son los estratos profundos de la sociedad occidental y que la crisis económica renueva, acrecienta y agita potencialmente en desmedida. 
De frente a todo esto hablar de una"rebelión de masas» hoy en día es francamente exagerado. 
Pero tener los ojos abiertos ciertamente no lo es. 
