Eres lo que dices de ti mismo 
En su décimo cumpleaños el Google puede afirmar: se le puede encontrar tanto en el bolsillo de la gente, como en el cielo por encima de su cabeza; sabe donde pasaron sus vacaciones, a qué médicos visitan y qué es lo que les interesa. 
Pero según Eric Schmidt, uno de los ejecutivos de la compañía, esto aún no es suficiente. 
Por otra parte los escépticos que hacen un paralelo con la visión orweliana no ven la esencia de la Web 2.0. 
Eric Schmidt hace poco declaró al periódico Financial Times que el objetivo principal de Google es reunir la mayor cantidad posible de datos personales sobre sus usuarios, y esto es necesario para poder cumplir los objetivos originales de los fundadores de Google: "¡reunamos en un sistema todas las informaciones del mundo!". 
Según el líder del Google, la compañía incluso después de diez años de trabajo que revolvió al Mundo está aún en la fase inicial del empeño de poder tratar toda la información. 
A la pregunta que qué es lo que va a pasar dentro de cinco años Schmidt contestó así: quisiera que el Google pudiera contestar a las preguntas como "¿Qué hacer mañana?" o "¿Cuál sería el trabajo que mejor me convendría?" - sin embargo, los software no podrán contestar a preguntas aparentemente tan simples mientras no existan suficientes informaciones de los usuarios. 
No todos los internautas están conscientes de que durante su navegación en la Red se almacenan con precisión las palabras claves buscadas, las direcciones de IP y las páginas adonde pasaron al terminar la búsqueda. 
Gracias por ejemplo a Personalized Search que debutó hace dos años, los usuarios pueden almacenar su propio historial de navegación, pueden volver a consultar lo que buscaban antes, lo que abrieron y gracias a este historial generará búsquedas mucho más personalizada -en esta misma lógica se basará el Recommendations, en la que el sistema nos ofrecerá productos y servicios en base de las preferencias anteriormente definidas y almacenadas. 
¿Qué ocurrirá si aprovechan mis datos contra mi mismo, si recogen informaciones sobre mis actividades? - preguntan aquellos usuarios que se preocupan viendo el monopolio informativo de Google. 
En la mayoría de los casos más bien el potencial representado por la compañía es lo que puede ser temeroso y no el remordimiento, el temor por el castigo, el anhelo por la libertad o la rebelión contra el poder. 
Sin embargo es un hecho ya confirmado que no únicamente conservan, sino en casos justificables también ceden a terceros todas las expresiones buscadas, en estos casos no hay nada que proteja los derechos personales de los internautas. 
El ejemplo más debatido de los últimos tiempos fue quizás la acción coordinada contra los pedófilos brasileños, cuando Google le entregó al gobierno brasileño las informaciones de su página de Web, llamada Orkut, para identificar a los pedófilos. 
En cambio, los internautas que se preocupan por los derechos de las personas, en el mes de mayo se aliviaron cuando la compañía junto con la EFF, organización para la defensa de los derechos electrónicos, demostró exitosamente ante el tribunal que tenía razón en su litigio con la FBI: según la sentencia, no se le podrá obligar a Google, mediante ninguno de los puntos de la constitución a suministrar cualquier tipo de información solicitada en secreto por la FBI. 
(Al mismo tiempo el gobierno federal logró conseguir so pretexto de reforzar la ley de protección de la infancia aprobada años atrás, cerca de cincuenta mil direcciones de Web y unos mil frases buscadas, pero sin obtener las listas de búsqueda de los usuarios individuales, ni tampoco las listas completas de páginas Web y de palabras claves de los últimos dos meses.) 
Así es bastante contradictoria la opinión sobre el Google: lo critican aquellos que temen suministrar sus datos personales porque piensan que se perjudica su intimidad, su vida privada al comenzar a utilizar los servicios de Google, y se rebelan contra ella como contra las compañías multinacionales de imagen conservadora. 
Mientras tanto, la cultura geek norteamericana y sus entusiastas seguidores, internautas y usuarios de otros países, ven en ellos la futura generación, la "corporación de vanguardia", no así a su rival, el Microsoft, catalogado por su Windows como conquistador del Mundo, por mucho que ambos luchen por el mismo objetivo. 
Esto puede ocurrir porque el Google al contrario del Microsoft, no pide de los usuarios ningún código de identificación, ni dinero por sus aplicaciones, el código es abierto y el paquete de programa gratuito, constantemente actualizad y parece más juvenil, más colaborador que la práctica del gigante oficial de los software. 
Pero puede ser también porque los geek ven con precisión la relación muy problemática existente entre los derechos de las personas y el Internet que se produjo justamente por una de las palabras claves más mencionadas en los últimos años: la Web 2.0. 
La Web 2.0 se trata de la colaboración, de dejar huellas intencionadas detrás de nosotros y aprovechar los canales de comunicación disponibles, y mientras la medidas de estos varia individualmente, la esencia sigue siendo la misma: mostrarnos a nosotros mismos. 
Un joven normal puede tener perfil en numerosas páginas colectivas, desde Facebook hasta Xanga, e incluso puede unirlas con otros servicios, como por ejemplo el Twitter o el last.fm que ofrece lista de sus costumbres de música, después a estos los puede incluir en un sistema de seguimiento como el FriendFeed o el Blip.fm, puede tener además un blog, en el que aparecen automáticamente las más recientes galerías de fotos que se almacena en el Flickr o en el Picasa. 
Podemos conocer numerosos casos de los que se desprende que por ejemplo la novia, al ver el flujo de fotografías de la mañana siguiente de los amigos comunes, se entera con quién pasó la noche anterior su novio fraudulento o pueden despedir al empleado de una compañía porque este escribe su opinión sincera en su blog sobre la dirección de la empresa: una cosa es segura, la definición de la vida privada se revalorizó completamente. 
La vida "on line" de una persona es lo que ella muestra de sí misma - esta es la definición que se esconde detrás de la conducta de la juventud de nuestros días. 
Y el que desea ocultar algo, o al menos pretende esquivar el monopolio de Google, lo puede hacer (empezando por ejemplo con el Scroogle que utiliza el sistema de búsqueda de Google, pero no deja huellas). 
Hay muchas personas que no quieren registrarse en las páginas colectivas para evitar que los puedan encontrar, pero se pueden reemplazar las aplicaciones "on line" de Google, desde el software de redacción de textos hasta las aplicaciones de imagen y lectura de noticias con versiones alternativas los cuales no se conectan con gigantescos servidores ni preparan el perfil más perfecto posible sobre nosotros. 
La opinión pública espera casi que abiertamente el día en que el Google muestre su verdadera cara. 
La compañía con su valor actual de 156 mil millones de dólares vale más que la IBM (140 mil millones de dólares), la Intel (124 mil millones de dólares) o la Coca-Cola (110 mil millones de dólares), las superficies de publicidad de AdWords/AdSense amenazan los ingresos de las agencias de publicidad, en tanto que los servicios que se introducen cada vez más rápidamente causan graves dolores de cabeza no solamente para el Microsoft, sino también a numerosas otras empresas desarrolladores de software. 
Los observadores críticos sin embargo, encontrarán las contradicciones alarmantes también: por ejemplo la dirección superior rechazó rotundamente la protesta de los empleados luego de duplicar el precio de la guardería infantil de la empresa, consideraron demasiado cara el número ilimitado de alimentación de los empleados, pero todo esto no es nada en comparación con el hecho de que en el año 2006 el Google cedió ante la presión del gobierno chino y la compañía según el acuerdo filtró toda información que violara la buena moral y los intereses del régimen chino. 
Uno de los reglamentos internos de la compañía dice que no anunciarán ningún servicio nuevo con antelación, sino que sólo cuando ya estuviera listo para funcionar, lo que si es seguro es que los problemas previsibles de los próximos meses y años podrán revolver al Mundo: mientras que algunos creen que el proyecto de escaneo y archivo de libros y revistas de Google adquirirá tales dimensiones que la compañía pronto será citada por el Tribunal Supremo de los Estados Unidos, otros temen de su sistema Health, porque en ella podemos crear nuestro propio perfil sanitario completo, con análisis anteriores, con nuestros médicos y nuestros problemas. 
Y el hecho de que Google vaya a crear una base de datos genética, podrá proporcionar una buena materia prima para los escritores de obras de ciencia ficción, la Scroogled, novela del popular de Cory Doctorow, describe en forma orweliana aquél futuro, en el cual un hombre solamente de los datos del Google se puede describir alarmantemente bien. 
