Open Office, eco la tercera edición del paquete"anti-Microsoft» 
Es el día del lanzamiento del OpenOffice.org 3.0, la suite open source de productividad personal que mira a atraer siempre mas utilizadores, desde la casa a la oficina a los profesionistas de la administración pública, como alternativa gratuita al conocido Microsoft Office. 
Después de un trabajo de casi un año de parte de los desarrolladores voluntarios,  de los cuales sus espaldas están vigiladas por SUN Microsystem, el nuevo Open Office se muestra al público con varias novedades: a la pantalla de bienvenida y a la interfaz revista menos grosera, se agregan otras mas consistentes, como la compatibilidad para el sistema operativo Apple Mac OS X y el soporte para el nuevo formato ODF(Open Document Format) 1.2,la ultima versión estándar ISO. 
Atención puesta también al multi funcionamiento con la suite Office 2007, Open Office es en grado de abrir los documentos con la nueva extensión de Microsoft (.docx, .xlsx, .pptx). 
Interesante algunas funciones especificas de algunos módulos como aquel que permite reducir la dimensión de la presentación de PowerPoint, útil por ejemplo, para enviarla vía posta electrónica, o la posibilidad de importar el file PDF en el modulo de elaboración grafica, conservando el aspecto original de la pagina. 
Siempre sobre este frente se pueden crear documentos "PDF híbridos", que acumulan la grafica típica del formato de Adobe con los elementos de una hoja de cálculo o de un elaborador de texto. 
La Colaboración es un elemento que ha recibido diferentes mejorías en el interior de los aplicativos: en la hoja de cálculo pueden intervenir en diversos usuarios, evitando los conflictos de las modificas, en la elaboración de textos, a cada colaborador viene dado un color en el comento para un mejor reconocimiento en la fase de revisión. 
Algunas empresas están también trabajando para llevar algunas funciones de OpenOffice al Web (on the cloud, sobre las nubes), y en las próximas semanas deberían dar el resultado definitivo. 
La versión en italiano se puede descargar en la dirección http://it.openoffice.org/download/3.0.0/download300.html y se agrego a la ingles que se encontraba en el mirror desde el viernes. 
Además que para Windows y Mac OS, como normalmente la suite es también disponible para el sistema operativo Linux. 
A pedido puede ser mandado también el cd de instalación a casa o al trabajo. 
Y si el tema del gratuito puede ser un gancho para la difusión en las casas, es en ámbito business que Open Office la suite prueba, intenta la grande apuesta, pudiendo ya contar con varios proyectos realizados en la pública administración y en las escuelas. 
Y no faltan ni siquiera las realidades que ofrecen un servicio de formación, consultas y de asistencia ideal para las pequeñas y medianas empresas, en las que se podrían abrir prospectivas de business. 
Open Office se compone de cinco módulos principales: Writer, para la video escritura  el correspondiente de Word; Calc, es la hoja de cálculo que sustituye Excel; Impress, para la presentación de Powerpoint; Dbase, come en el caso del conocido Access es el programa que consiente a trabajar en el data base; y por ultimo Draw el modulo grafico. 
Objetivo para el 2008 es de llegar a 5 millones de download, y considerando que hasta hoy llegamos a casi ya 3 millones 600 mil, con la salida de la versión nueva es probable que se pueda superar la cifra prevista. 
