Járóka: Hay que romper el círculo vicioso de la pobreza y de la segregación 
Hoy se ha iniciado en París la Cumbre Europea para la Igualdad de Oportunidades, su anfitrión es Francia que este año es también presidente de turno de la Unión Europea. 
Lívia Járóka, diputada del Partido Popular Europeo por el Fidesz, en su mensaje dirigido al pleno, como uno de los principales oradores de este encuentro profesional, llamó la atención acerca de la segregación en la educación, porque es una de las violaciones más graves que azotan a los niños gitanos y además es también el obstáculo más grande ante el prevale cimiento de sus intereses. 
Esta conferencia de alto nivel fue inaugurada - en nombre de la presidencia francesa - por Xavier Bertrand, ministro francés de empleo y asuntos sociales y por Vladimir Spidla, comisario europeo responsable por los empleos, asuntos sociales y de igualdad de oportunidades. 
Asistieron a la reunión representantes de los gobiernos, interlocutores sociales europeos y representantes de las más importantes organizaciones europeas de protección de los derechos sociales. 
Járóka - según el buró de prensa del grupo de diputados del Fidesz en el Parlamento Europeo - advirtió que además de la discriminación en el empleo, los gitanos quedan fuera del mercado laboral en primer lugar por su bajo nivel de escolaridad. 
"La mayor parte de los jóvenes gitanos no han terminado la enseñanza media y debido a la mala calidad de la enseñanza básica, tan sólo una parte insignificante puede obtener diploma universitario". 
Járóka destacó además que la educación, como derecho humano fundamental, tiene un papel determinante en el prevale cimiento de los demás derechos humanos también. 
La inversión en la enseñanza de los niños gitanos a una temprana edad puede fortalecer la economía de los Estados miembros de la Unión Europea. 
Según la eurodiputada, es necesario concientizar ampliamente estas cuestiones tanto entre los gitanos como entre los no gitanos. 
Pues mientras más temprano comience la escuela un estudiante gitano, más posibilidades tendrá para convertirse en un miembro activo del mercado laboral; a través de los impuestos a la renta y de consumo ellos también contribuirán al presupuesto nacional. 
"A los gitanos, como ciudadanos de la Unión Europea, hay que asegurarles el derecho para una educación de calidad y garantizar la abolición de la educación segregada y de bajo nivel" - destacó Lívia Járóka. 
Según la eurodiputada, es necesaria la unidad objetiva y activa de la Unión Europea para acelerar de inmediato los procesos de desegregación escolar, para eso es de importancia fundamental el correcto cumplimiento de las directivas antidiscriminatorias existentes y planificadas. 
"Hay que romper el círculo vicioso de la pobreza, la segregación y el desempleo, hay que ofrecerle a los niños gitanos la posibilidad que garantiza el espacio democrático para que puedan contribuir al futuro de Europa como ciudadanos de plenos derechos" - exigió Járóka. 
El objetivo de la Cumbre Europea para la Igualdad de Oportunidades organizada anualmente desde el encuentro berlinés del año pasado que se celebró en el signo del "Año Europeo de la Igualdad de Oportunidades", es asegurar un foro singular para promover la abolición de la discriminación y la igualdad de oportunidades a nivel europeo y a nivel nacional de los Estados miembros. 
