La oposición de Lukashenko: 110-0 
Tras las elecciones del domingo, no habrá ningún diputado opositor en el parlamento bielorruso. 
Según los observadores rusos, esto se explica con el bienestar y la estabilidad que garantiza en el país Alexandr Lukashenko, en cambio según la Organización para la Seguridad y la Cooperación en Europa (OSCE), esto se explica más bien con las violaciones de la ley cometidas durante el conteo de los votos. 
La OSCE que envió 450 observadores procedentes de 43 países, no reconoció el resultado electoral. 
Si bien la legislatura del país de 10 millones de habitantes, integrada por ciento y diez diputados, hace más de un decenio no tiene oposición, antes de las elecciones de ayer la oposición unida bajo el nombre de Fuerzas Democráticas Unidas (ODSZ) esperaba que Lukashenko, que por cuarta vez renovó su mandato tras las elecciones de 2006 de dudosa legitimidad, por consecuencia de la modificación de la Constitución esta vez "permitiría" la entrada de algunos diputados de la oposición en el parlamento. 
Así la ODSZ suprimió el boicot que originalmente quería hacer. 
En el fondo de las expectativas de la oposición estaba el que Bielorrusia, que cada vez depende más económicamente de Rusia - que tomó un crédito para moderar la importación de gas natural cada vez más cara de Rusia y que contribuyó a la venta a Rusia del Beltransgaz, propietario del gasoducto que pasa por el país - deseó mejorar sus relaciones con la Unión Europea, que no le da permiso de entrada a Lukashenko y a los demás políticos de alto nivel por tener un régimen político considerado antidemocrático. 
Fue un signo de distensión cuando la OSCE, al evaluar la campaña electoral, colocó énfasis más bien sobre los fenómenos positivos y no sobre los errores - como por ejemplo la prohibición de participar impuesto a un tercio de los candidatos de la oposición. 
Sin embargo el informe primario del lunes de la OSCE criticó incluso la propia campaña - en la cual los candidatos de la oposición no pudieron aparecer en la prensa - y especialmente que la oposición no pudo estar presente en el conteo de los votos. 
Con todo esto en opinión de la oposición se siente un mejoramiento en el clima político: quedaron en libertad los presos políticos y Minsk está dispuesta a una pequeña confrontación con Moscú, negando el reconocimiento de la separación de Osetia del Sur y Abhasia de Georgia, aunque Rusia - con el cual Bielorrusia teóricamente constituye un Estado federal - hace ya un mes que considera las dos regiones como independientes. 
- Hemos dado dos pasos hacia adelante y uno hacia atrás, pero lo más importante es que se ha iniciado el diálogo entre Bielorrusia y la Unión Europea - declaró a nuestro periódico Alexandr Milinkevich. 
Según el candidato de la oposición de las elecciones presidenciales de 2006 es deseable mantener esta situación, a pesar de que "el régimen teme permitir la entrada de tan siquiera un opositor en ese parlamento sin peso". 
La oposición no planea organizar manifestaciones de protesta al ver los resultados, más bien intenta hacer llegar a los electores su mensaje sobre la necesidad de hacer reformas económicas. 
- Esto claro nos causa muchos problemas porque debemos imprimir la prensa de la oposición en Rusia, las autoridades locales ponen dificultades ante su distribución, pero incluso así veo que cada vez son más los que apoyan el cambio entre los mayores de edad también - dijo Milinkevich, haciendo alusión a que al régimen de Lukashenko, que cree que su resultado principal es la creación de la seguridad social, no lo consideran adecuado ni siquiera los jubilados, los que oficialmente son los más subvencionados por el régimen. 
Debido al endeudamiento del país y el aumento del déficit comercial, es sólo cuestión de tiempo la descomposición de la seguridad social que "se parece al silencio de los cementerios" - opinó Milinkevich. 
Los observadores rusos al contrario del político de la oposición calificaron de democráticas a las elecciones. 
Serguei Lebedev, jefe de la misión de la Comunidad de Estados Independientes declaró a la agencia rusa de noticias Ria Novosti: "la gente no cree en las palabras sino en los hechos", de manera que la falta de la oposición no es otra cosa que el testimonio de la madurez de los electores bielorrusos. 
