El grupo catalán facilitado miles de pasaportes a Al Qaeda 
Además de los siete detenidos en Barcelona, en Tailandia hubo tres 
Los siete pakistaníes y el un nigeriano detenido por agentes de la policía secreta de Barcelona formado un grupo yihadista que, desde Tailandia, facilitado los pasaportes a los diferentes grupos de Al Qaeda, entre ellos "Los Tigres para la Liberación de Tamilm territorio" (LTTE) y "Laskar y Taiba" (Let), autor de este último uno de los ataques de Bombay que causó la muerte de 106 personas en 2008. 
El Ministerio del Interior ha prestado atención a estas investigaciones, hasta el punto de asegurar que con "Kampai" operación; ha sido "debilitar" el aparato de falsificación de Al Qaeda a nivel internacional y, "por tanto, su capacidad operativa". 
Los investigadores calculan que la celda, durante los dos años que ha estado activo en Cataluña, ha sido capaz de enviar miles de pasaportes a Tailandia, donde fueron falsificarse y pronto a los grupos criminales que integrar la galaxia Al Qaeda para que su "combatientes" pueden cruzar las fronteras europeas y los de otros países occidentales con total impunidad. 
La célula desmantelada no es la única que la red yihadista en Europa, por este motivo en las investigaciones se han participado, además de los servicios de Tailandia, otras unidades de policía europea, razón por la que no se descarte que en territorio de la UE se producen acontecimientos similares al elaborado la noche del martes en Barcelona. 
En coordinación con esta operación (La pakistanís Junaid Humayun, Atiqur Rehmen, Jabran Asghar, Malik Iftikhar Ahmad, Mohammad Saddique Khan Begum, Tanveer Arshad y el nigeriano Agunbiade Babatunde se paró), en Tailandia otro ha desarrollado con la captura de los pakistaníes Muhammad Athar Butt y Zeeshan Ehsan Butt y el tailandés Kijbumrung Sirikanlaya. 
El grupo con sede en España y otros países europeos se dirigieron en Bangcock 
La red catalana, parte de ella fue alcanzado en 2009, principalmente robado los pasaportes de los turistas que cumple los requisitos marcados por el llamado "Worldwide frente islámico". 
Es decir, los documentos han de ser en el nombre de los hombres entre 25 y 45 años, con validez de varios años y sin reproducido los visados. 
En los medios de la investigación se hace hincapié en que, de momento, no se ha encontrado datos relativos a los detenidos en Cataluña en relación con el ataque de Bombay, aunque el autor de este ataque, "Laskar e Taiba", ha sido uno de los grupos de acogida de los pasaportes robado en España y pronto falsificarse en Tailandia. 
Sin embargo, cabe mencionar que días antes de este cometido ataque, de Cataluña no fueron enviadas a través de una agencia de transferences sobre algunos miles de dólares que fueron "invertido" en la compra de tarjetas de telefonía móvil que antes eran utilizados por los miembros del "comando" que acabó con la vida de 106 personas. 
Los policías han capturado una gran cantidad de documentación. 
