El programa nuclear pakistaní genera gran intranquilidad en los Estados Unidos 
Islamabad produce armas atómicas en "un ritmo más rápido que cualquier otro país". 
Las filtraciones de Wikileaks confirmar los lazos entre los talibanes y el Pakistán. 
El contenido de la correspondencia entre la Embajada estadounidense en Pakistán y el Departamento de Estado de los Estados Unidos filtrados por el portal de Wikileaks confirma la enorme inquietud que el programa nuclear pakistaní provoca en Washington. 
Además de la esclarecedora y sustancial que se ofrecen detalles sobre el contenido de las conversaciones y los pensamientos de los representantes diplomáticos acreditados de América del Norte en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de seguridad nuclear, en lugar de aumentar, "disminuya," y que la inestable país asiático produce armas nucleares con "un ritmo más rápido que cualquier otro país". 
La peculiaridad del programa nuclear pakistaní, que las armas no son reunidos pero siguen almacenadas por componentes para dificultar su destrucción en caso de attack-- que constituye una de las principales causas de preocupación en Washington. 
Por lo tanto es enumeradas por el embajador en Pakistán, Anne W. Patterson, en un informe previo a la visita del ex asesor de Seguridad Nacional, James Jones: "La proximidad de algunas centrales nucleares en el territorio bajo ataque de los talibanes, los rumores de la dispersión de los materiales nucleares y la vulnerabilidad de transporte de materiales nucleares". 
El elevado número de personas implícita en los arsenales nucleares y los programas de misiles se tenga en cuenta, no sólo por los Estados Unidos, sino también por Rusia, como la razón para mantener la guardia. 
"Pakistán ha tenido que contratar a personal con estrictas creencias religiosas para proteger las plantas de energía nuclear; dada la escasa éducative y cultural, las organizaciones extremistas tienen más oportunidades para reclutar personas a trabajar en los programas nucleares o de misiles", dijo el experto Yuri Carole, desde el Ministerio de Asuntos Exteriores, en una reunión con sus homólogos estadounidenses. 
La información más reciente sobre los documentos filtrados por el portal de Julian Assange, es la disminución de la cooperación entre los Estados Unidos y Pakistán en temas de la proliferación nuclear y la alta tasa de pakistaníes de producción de armas nucleares. 
Una oficina de la embajada en mayo, que describe como "frustrante" la comunicación con el Pakistán, dice que: "La transparencia es con frecuencia inexistente; los ofrecimientos de ayuda siguen sin respuesta o se negó". 
En otro mensaje, Peter Lavoy, funcionario de la Inteligencia Nacional para el sur de Asia, afirma que "a pesar de la catástrofe económica, el Pakistán produce armas nucleares en un ritmo más rápido que cualquier otro país del mundo". 
El embajador Patterson también pide a Washington, durante una visita del jefe del Ejército, el general Ashfaq Kayani, para dar órdenes claras a la persona encargada de que "el Ejército de Pakistán debe terminar el apoyo tácito a los grupos terroristas". 
