Grammy candidaturas: Cantante de jazz Esperanza Spalding es una sorpresa seleccionaros nueva categoría de mejor artista 
Realizar a petición de un presidente, y la gente está obligado a tomar nota. 
Esperanza Spalding, la libra bassist cantante de jazz y seleccionado por el Presidente Obama a cumplir en su Premio Nobel de la Paz ceremonia en 2009, marcó uno de los Grammys "sorpresas este año con una candidatura en la categoría de mejor nuevo artista. 
Considerando que Spalding ha sido un célebre figura en el escenario de jazz desde su álbum de 2008, "Esperanza", la candidatura es un poco head-scratcher, pero es compatible con las normas de Grammys de un artista no liberar a más de tres álbumes antes de la grabación que "la identidad de ese artista". 
Su ambicioso de 2010 álbum, "Sociedad de música de cámara," sin duda marcó un paso adelante, y dada su airily invitar abiertamente un estilo y una hábil parte con pop, y las influencias Latina acto realmente cobarde, es posible sacar al menos una línea de puntos para Spalding de Norah Jones "gran éxito en 2003, el equivalente más cercano a los votantes Grammy mirando hacia el vecindario de jazz en esta categoría en los últimos años. 
En otros lugares Grammy con razón los votantes a Vijay Iyer del trío "Historicity" en la categoría, un álbum instrumental thrill-ride vigorizadora de un registro que fue una gran favorita del año pasado. 
Entre esos Iyer puede competir contra incluir saxophonist veterano James Moody 's "Moody 4B" y la "keyboardist John Beasley Positootly". 
Trombone Shorty, un favorito raucous Nueva Orleans y frecuentes invitado a la HBO "Treme", fue conmemorado en la categoría de jazz contemporáneo, que de lo contrario se inclina intensamente a favor de la fusión con cierto Stanley Clarke hacia discos, John McLaughlin y Jeff Lorber. 
La salvaje, steampunk-informed Darcy James sostienen 's Secret Society earned algunos merecido reconocimiento en la gran ensemble categoría, competir contra el Billy Childs ensemble la rica chamber-jazz y la ever-adventurous Dave Holland, cuya octet vivir del álbum "Pathways" fue un buen ejemplo de la mano del bassist democrático como bandleader. 
