Romano va hacia su primer título 
Rubén Omar Romano cuenta con tres derrotas en la final, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey, en la última, además de dos estilos diferentes marcado por sus técnicos ", que se enfrentan a encontrarse con un contraste marcado por los resultados. 
Rubén Omar Romano cuenta con tres derrotas en la final, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora no había alcanzado el objetivo y esta es la razón por la que esta oportunidad es muy especial para él. 
El argentino, que ha acabado con la medalla de recibir el segundo clasificado, y se quedaron un paso por detrás de los ganadores y particularmente con equipo similar ha desempeñado consecutive finales. 
Santos llegó a su primera final en el Apertura Match como instructor de 2002, cuando tomó las riendas de Morelia con la que cayó a 4-2 ante Toluca; más tarde, en la ceremonia de clausura de 2003 también llegó al duelo decisivo y perdió también en 3-1 y, de hecho, antes de Rayados. 
Ya con Santos Laguna, en el Bicentenario 2010, una vez más, antes de Match Los Diablos, Rubén sufre un nuevo contrario, ya que su equipo acabó igual de lugares 2-2 antes de que los encargados de la salchicha después de 210 minutos de juego, pero en el turno de las penas colocado en ventaja por 3-1 con dos oportunidades para sellar el título, pero finalmente no tres jugadores de los 11 pasos y sufrido el cambio 4-3. 
Rubén perdido ya dos finales con Diablos Rojos y uno con Monterrey, su rival en su vez, por lo que no queremos sufrir la misma suerte, quiere celebrar un título por primera vez, y afirma que lo más importante para él es la institución. 
Quiero ser campeón, no quiero romper cualquier dato estadístico, es para un club, por una pasión y por consiguiente el título llegará a mí, pero la anterior es más importante, comentó el timonel al ser interrogado sobre el número ha contra jugando finales. 
Muy eficaz ha la anterior final, de la que, asegura, ha aprendido mucho, "la única lección es que hasta el árbitro señala el final no podemos celebrar, nos preparamos así como los actores porque el tiempo anterior, con dos sanciones que estaban a punto de abandonar y creo que es una lección, no podemos celebrar hasta el juego termina". 
A sabiendas de que esta serie podría definirse la pena patadas, algo que no, porque le confía en sus actores: "Uno nunca debería espera para ir a las sanciones, sino para terminar en tiempo ordinario; a veces no tienen ninguna alternativa y es necesario estar preparados; en el partido anterior, lamentablemente destino en nuestras manos, a veces por los nervios o ansiedad por haber el título en manos, pero no lo hicimos llegar a ese objetivo, y esto nos deja algo para esta última que esperamos para ganar". 
Roman debe dejar de ser un candidato técnica y degustación por primera vez la gloria que los títulos. 
