IP pide resultados del Congreso 
Eduardo Dávalos, presidente de la CEC, propone que los diputados asumir la gran responsabilidad de ser un ejemplo para una mejor Sinaloa por los diversos problemas que afronta. 
Un digno Legislature de obras y libre de acuerdos entre las partes y el Ejecutivo Estado es exigido por el sector empresarial de Mazatlán, porque hay una convulsionada Sinaloa que se enfrenta a grandes problemas. 
Ayer fue votado en la 60 legislatura, integrada por siete fuerzas políticas, 19 diputados del PRI, 13 del PAN, tres del Partido Nueva Alianza, dos del PRD, uno del PT, uno de Convergencia y uno más del PVEM, lo que significa un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso de la S-state se menciona que llegan a cumplir una gestión limpia de compromiso con la sociedad y los distintos sectores que requieren un responsable de la labor legislativa. 
Eduardo Dávalos Zamora, presidente de la Empresa Consejo de Coordinación, propuso que la que acaba de publicarse 40 diputados del Congreso del Estado asumió la gran responsabilidad de ser un ejemplo para una mejor Sinaloa por los diversos problemas que afronta. 
Esperamos que los diputados realmente ejercer su derecho, libre de acuerdos entre las partes porque es una costumbre de hacer acuerdos a fin de guardia por sus propios intereses y de convertirse en un personaje de un carnaval de los gobernadores y dirigentes de las fracciones parlamentarias. 
Por ello habló de certificar el compromiso para establecer los necesarios puentes que podría ayudar al Gobernador para seguir adelante. 
Esperamos que vienen a hacer un buen trabajo y, principalmente, a la sociedad y de los sectores porque la habitants de Sinaloa fueron los que les dio el voto de confianza durante las últimas elecciones. 
José Ramón Manguart Sánchez, presidente de la Asociación de Hoteles Tres Islas, consideró que uno de los mayores retos para las 40 representantes populares es el de impulsar y añadiendo fuerzas en búsqueda del crecimiento económico de la situación, ya que hoy en día la situación económica es muy complicado. 
La más importante es impulsar el crecimiento económico, que genera incentivos para la inversión y la infraestructura y que, de alguna manera, formarán una nueva generación de puestos de trabajo. 
En cuanto a la actividad turística, pidió que los nuevos legisladores dar el peso revisada en el presupuesto estatal para fortificar la Secretaria de Turismo. 
Como he entendido este es el segundo departamento del Estado con menos presupuestos y es incongruente una importante actividad económica y la generación de divisas y la inversión y que compite directamente con la industria de productos agrícolas. 
Aparte de que el etiquetado recursos deflagrantes proyectos turísticos que ayudar a dar seguridad a la situación y actualizar la Ley del Alcohol que no ha sido capaz de resolver en las legislaturas anteriores. 
