Crímenes anti-Moslem han aumentado en un 50%
Entre 2009 y 2010, anti-Moslem crímenes aumentar en casi un 50%, mientras que en el mismo período de otras formas de violencia racial y religiosa había disminuido ligeramente, o no había cambiado, según las estadísticas del FBI publicado el lunes.
Según estas cifras, el número total de casos de violencia contra los musulmanes se trasladó de 107 en 2009 a 160 en 2010, equivalente a un aumento de 49%, frente a un aumento del 13% de los casos de violencia contra los católicos, una caída del 4% de los ataques contra los judíos y un aumento global de 14% en los delitos antirreligiosa.
El número global de crímenes de odio aumentó muy ligeramente a 6 628 casos, de los cuales 47,3% estaban motivados por diferencias raciales y 20% por las diferencias religiosas, según el FBI.
"Después de una disminución en 2009, es inquietante ver estos crímenes aumentar nuevamente, destacó la organización de derechos humanos, Human Rights First," el aumento de casos de violencia anti-Moslem es especialmente significativo ", añadió la organización en un comunicado.
"Human Rights First durante mucho tiempo ha subrayado que los actos de violencia contra los musulmanes, así como todas las formas de crimen de odio, deben ser considerados como graves violaciones de los derechos humanos", añade uno de los directores de la organización, Paul Legendre.
"El gobierno estadounidense puede y debe hacer más para tratar su abuso, agrega, estimando que esto podría deberse a la edición de los informes policiales sobre los crímenes de odio".
"Crimen de odio" en la legislación federal, es un legado de la época de la lucha por los derechos civiles.
Esta legislación fue aprobada después de la muerte de Martin Luther King para castigar los actos de violencia vinculados a la raza, color de piel, religión, origen y ahora la orientación sexual.
