El "enojado personas" desafío a las autoridades en Nueva York
Cientos de manifestantes fueron que se acercaban delante de la plaza Zuccotti al campamento.
Una parte de los manifestantes escuchado la orden de desalojo y se trasladó a un parque cercano.
Los miembros del movimiento Occupy Wall Street desafió el martes a las autoridades de Nueva York cuando intentaba entrar de nuevo, bajo la protección de una orden judicial, en la plaza de Manhattan, donde fueron evacuadas en la madrugada cuando intentaban ocupar otro parque del Big Apple.
Cientos de manifestantes concurrido ronda la plaza Zuccotti, donde querían entrar gracias a una orden judicial que permite que "las airadas personas" al campamento en el sitio, mientras que otra parte del movimiento respondió al desalojo por la ocupación de un parque al norte de la ciudad, donde se han realizado nuevos arrestos.
"Nuestra idea es que si el tribunal no nos permiten regresar al campamento en la plaza, vamos a campamento en otro sitio y continuar la batalla legal para retornar a Zuccotti, y a través de manifestaciones y sentadas pacíficas", dijo uno de los portavoces del movimiento "Occupy Wall Street", Mark Bray.
Bray explicó que la respuesta de la "enojado personas" a la evacuación del campamento emitido personalmente por el alcalde de Nueva York, Michael Bloomberg, llegó al tribunal, donde la jueza Lucy Billings emitió una orden que prohíbe la evacuación forzosa del lugar y permitir a los manifestantes a permanecer acampados.
Además, el "enojado personas" procedió a la ocupación de un nuevo parque situado en la confluencia de la calle Canal del centro y de la Sexta Avenida, cerca de la entrada del Túnel Holland, que conecta a Nueva York y Nueva Jersey, propietaria de la parroquia de Trinity Church.
En menos de una hora fueron capaces de ocupar el lugar, pero luego la policía procedió a arrestar a algunos de los manifestantes, aunque Bray no pudo confirmar el número exacto, mientras diciendo a Efe que vio a varios periodistas que también fueron esposados.
La organización asegura que hay varios cientos de personas acampadas en ese punto, donde una delegación de líderes religiosos ya ha ido para mostrar su apoyo a los miembros del movimiento intentando mediar con la policía.
Mientras tanto, la plaza Zuccotti, que es un sitio de propiedad privada, sigue cerrado a la espera de una audiencia prevista para este martes en el que examinar la legalidad de la evacuación de esta mañana.
Algunos de los manifestantes se trasladaron allí pudieron transportar y distribuir en ese momento copias de esa orden judicial e incluso dieron estas copias a los agentes que custodiaban el lugar, lo que llevó a "algunos pequeños enfrentamientos", dijo Bray, quien afirmó que algunos oficiales golpearon a los manifestantes.
La orden judicial prohíbe a las autoridades a evacuar a los miembros de Occupy Wall Street y aplicar "leyes que fueron emitidos después del comienzo de la ocupación o prohibir los manifestantes recuperar el acceso al parque con tiendas y otros bienes utilizados antes."
El alcalde Bloomberg dijo a los periodistas que, debido a que la orden judicial, la ciudad había suspendido la reapertura del espacio público y manifestantes fueron informados, sin embargo, que las leyes locales no les permiten restablezcan con acampar en tiendas y sacos de dormir.
El councilman personalmente defendió la evacuación de la plaza Zuccotti llevada a cabo al amanecer, de una operación en la que unos 200 detenciones y esto fue decidido porque los manifestantes fueron "violar la ley".
Bloomberg dijo que dio la orden de evacuar la plaza porque era "un lugar donde la gente no viene a protestar, pero para romper la ley y, en algunos casos, para hacer daño a los demás" como "Algunas empresas han recibido amenazas" y los vecinos temían "por la calidad de vida".
"La evacuación de esta mañana fue repugnante y demuestra que en las profundidades Bloomberg está más interesada en la preservación de los intereses financieros de los trabajadores estadounidenses", añadió el portavoz del movimiento, que acusó al alcalde de "falta de respeto por la libertad de expresión".
Los responsables de "Occupy Wall Street" también indicó que tienen la intención de organizar "grandes hazañas" para el jueves, en colaboración con las organizaciones de la comunidad y los sindicatos, para conmemorar los dos últimos meses de protestas, que comenzó el 17 de septiembre.
