Que analizar la posibilidad de un "voto por voto" contar en Michoacán
Según los datos transmitidos por la PERP la diferencia entre el primero y segundo lugar en las elecciones a gobernador es de sólo 27%, incluso sin contar los votos correspondientes a 879 del total de 6.074 minutos.
La posibilidad de que el recuento "voto por voto" es una realidad en lo que respecta al proceso electoral de este año en Michoacán, donde, según los datos aportados por el Programa de Resultados Electorales Preliminares (PERP) la diferencia entre el primero y el segundo lugar de la elección de Gobernador es de sólo 27%, incluso sin contar los votos que corresponden a 879 del total 6.074 minutos.
En este sentido, el Presidente del Consejo General del Instituto Electoral de Michoacán (MEI), María de los Angeles Llanderal Zaragoza, recordó que hace pocos días, el pasado 9 de noviembre, el órgano electoral aprobó un conjunto de directrices para armonizar los reglamentos locales con la reforma federal electoral.
Como se recordará, Michoacán no autorizó a la Constitución ni el Código Electoral del Estado o de la Ley de Justicia Electoral, desde el Congreso del Estado aprobó las reformas poco antes del plazo legal para que entren en vigor en este proceso electoral y el Gobernador Leonel Godoy Rangel omitido su publicación dentro de los plazos especificados en la ley en el Boletín Oficial del Estado, argumentando que había algunas objeciones.
El 9 de noviembre, la Suprema Corte de Justicia (SCJ) resuelva la controversia constitucional promovida por el poder legislativo local y calificó de "nula e ilegal" la votación de la representante estatal para las reformas constitucionales, ya que él no tiene derecho "a la sanción o la votación."
Entrevistado sobre la posibilidad de que el "voto por voto", María de los Angeles Llanderal indicó que con la aprobación de las directrices apropiadas por el Consejo General del MEI será posible realizar recuentos parciales y totales de la votación por el órgano electoral local.
Así, el recuento parcial de uno o más cajas electorales puede ocurrir en los supuestos que: Los resultados de los registros no concuerdan; no hay constancia de que el contar con el acta de la caja o no están incluidos en el poder del presidente; o cuando hay errores obvios o alteraciones de los minutos.
Además, el número total de los votos recibidos en todas las cajas de las elecciones pueden tener lugar cuando hay un indicio de que la diferencia entre el presunto candidato ganador de la elección en cuestión y el que ha obtenido el segundo lugar en la votación, es igual o menos de un punto porcentual, mientras al inicio de la sesión, hay una solicitud de la representante del partido o coalición que nominado el segundo de los mencionados candidatos.
El total de la votación contar también será posible si al final de la calle cálculo se estableció que la diferencia entre el ganador y el candidato colocado en segunda posición es igual o menos de un punto porcentual, mientras hay una solicitud de la representante del partido político cuyo candidato llegó en la segunda posición, caso en el que haya excluido de las cajas electorales que se han considerado durante el recuento parcial.
Se debe señalar que en esta situación es la elección de Morelia, donde según PERP la diferencia entre el primero y el segundo lugar es de sólo el 0,16%, incluso sin contar con los votos de 129 de los 923 total minutos.
