Debe haber hecho contribuciones a obras
Las obras sociales en los programas como Hábitat, Rescate de Espacios Públicos y 3x1 para migrantes corren el riesgo de no ser completado o a tener serios retrasos debido a la falta de fondos, dijo Miguel Ángel López Miranda.
El director de Desarrollo Social Municipal indicó que aunque hasta ahora los programas de trabajo han avanzado que están en riesgo porque el Gobierno del Estado fracasado a la hora de hacer las aportaciones que corresponden, que representan un recurso superior a los 11 millones de pesos en los tres programas.
Señaló que la inversión total en estos tres programas es de casi 50 millones de pesos, de los que el Estado ha de contribuir con 25% y hasta ahora sólo la Federación y el Municipio han proporcionado los recursos para las obras, de modo que el posible retraso en la finalización de estos está en vigor.
"Tienen que contribuir con casi 12 millones, y aunque el año que termina no han dado un dime, ya que a partir de julio tuvieron que nos dan una parte", dijo, "a fin de no retrasar hemos comenzado las obras y están muy avanzadas, pero necesitamos el dinero".
Mencionó que el año pasado, durante la administración de Jesús Aguilar Padilla, el Estado no cumple con las contribuciones que se tenía que hacer, por lo que al inicio de la administración de la municipalidad tuvo que pedir dinero prestado para cubrir más de 7 millones de dólares, una suma que no se presentó en esa ocasión por la administración estatal.
"Se nos ocurrió en la anterior administración, porque el Estado no tiene la capacidad financiera para participar y los programas continuó avanzando, y este año para acceder a estos programas que teníamos que conseguir los recursos para cubrir lo que el estado pendientes", explicó.
Aunque existe el compromiso de las autoridades estatales para cumplir con la entrega de estos recursos, dijo que la petición fue realizado por el Secretario de Administración y Finanzas, Armando Villarreal, para acelerar los esfuerzos para que los porcentajes que le corresponden a llegar lo más rápidamente posible.
"Tienen que contribuir con casi 12 millones, y aunque el año que termina no han dado un dime".
