Apoyo a los trabajadores "Unión va a demandar ciudad más despidos
El sindicato que representa a cientos de escolares de apoyar a los trabajadores que perdieron sus empleos el mes pasado planes para demandar a la ciudad el miércoles, alegando que los despidos eran innecesarias y discriminatorio debido a su impacto desproporcionado en escuelas que sirven a los estudiantes pobres.
La demanda es posiblemente la última arma de la unión, el Consejo del Distrito 37, en su esfuerzo por revertir los despidos.
Seiscientos setenta y dos ayudantes escolares, padres coordinadores y otros empleados que se encontraban entre los salarios más bajos de la ciudad perdieron sus empleos en octubre. 7, en una jugada de los líderes sindicales han descrito como una venganza política por su negativa a permitir el acceso a la ciudad de un fondo de atención a la salud de los grupos de trabajo para cerrar la brecha presupuestaria en la pasada primavera.
Funcionarios de la ciudad han negado categóricamente esa acusación.
Ayuntamiento en una audiencia el mes pasado, las Escuelas Canciller Dennis M. Walcott, dijo que los despidos eran una parte del presupuesto se firmó en junio.
Un miembro del concejo disparó hacia atrás, diciéndole que nada en el presupuesto se especificaba que los miembros del personal de apoyo escolar serían despedidos.
Distrito Consejo 37 funcionarios dijeron que presentó un escrito de reclamación, advirtiendo al Departamento de Educación que sería demandado; se va a celebrar una conferencia de prensa el miércoles para anunciar la presentación de la demanda formal, en la Corte Suprema estatal en Manhattan.
El pleito estará lista el Sr. Walcott y la ciudad del Departamento de Educación como imputados, y cuenta con ocho trabajadores despedidos como demandantes, todos ellos negros o latinos mujeres, al igual que la mayoría de los asistentes que perdieron sus puestos de trabajo.
Elizabeth Thomas, un portavoz del Departamento de Derecho de la ciudad, dijo que la ciudad no había visto la demanda y, por lo tanto, no podía comentar sus denuncias concretas.
Según un borrador de la denuncia obtenida por The New York Times, el sindicato ha se centró en el número de despidos en las escuelas de las regiones pobres de la ciudad para apoyar una reclamación de trato desigual, diciendo colegios pobres perdieron más ayudantes porque habían sido crónicamente desfinanciadas.
Señala que, si bien no hubo despidos en Staten Island y pocos los despidos en las escuelas en el Upper East Side o TriBeCa, 17 escuela ayudantes perdieron sus empleos en el distrito 23 en Brownsville, Brooklyn, y 46 fueron en los Distritos 8 y 9 en el South Bronx.
Observando la pérdida de cinco de las ocho asesores contratados por la Escuela Pública 36 en Harlem, donde el 68% de los estudiantes que viven en la pobreza, la querella dice, "Esto no es un barrio de adinerados padres que pueden fund-raise para compensar el déficit presupuestario".
P. 36 "recorte del presupuesto del 3,26% este año, y también ha perdido dinero cuando la ciudad cambió la forma en que se calcula que la financiación adicional para cada estudiante pobre escuelas apuntar.
El sindicato afirma también que altos directores de escuela podrían haber sido engañados por el idioma en un memorándum autorizando el despido de padre coordinadores.
El memorándum utilizó la palabra "exceso" para describir la acción, aunque "exceso" más comúnmente describe el acto de traslado de un maestro de una escuela en la nómina de pagos de un grupo de trabajadores disponibles cuyos salarios son pagados por la oficina central.
"Sesenta y seis padres coordinadores fueron despedidos," el proyecto de denuncia, dice, "y no simplemente excessed."
