Detuvo a cabeza del Totana al alcalde y del policía local en un diagrama presumido de la corrupción del ciudad-planeamiento
El protector civil ha detenido a alcalde actual del municipio de Murcian de Totana, Jose "popular" Martinez Andreo, la cabeza del policía local, la secretaria del consejo de ciudad y un hombre de negocios hostal en los crímenes posibles del ciudad-planeamiento, fuentes nos ha informado hoy.
El edil fue arrestado en su dirección casera y se ha transferido al consistorio, en que dependencias está en el momento con varios agentes, que también han ido al consejo urbano y a la compañía de gerencia municipal del suelo industrial y de la cubierta.
Estas tres detenciones se agregan a seises hicieron el lunes pasado en Galicia, Murcia y Madrid, en una operación ligada al requalification de más de 2 millones de hectáreas de tierra rústica a urbanizeable de modo que la compañía gallega Nuaria construyera 4.000 casas, después del pago de comisiones ilegales durante la legislatura pasada.
Además, detuvieron pero no fueron cargadas a dos otras personas en el resumen, que manda a la corte del número 1 del Totana.
Las seis primeras detenciones han ido antes de la corte hoy.
Según fuentes de información, están investigando al concejal anterior de Totana y de parlamentario autonómico real de los PP, morales de Juan.
Además, la esposa anterior, propietario de una agencia registrada de las propiedades inmobiliarias en Totana, arraigned, al igual que la novia actual del concejal anterior que reside en el capital de Murcia.
Detuvieron al director y al propietario del grupo Nuaria, del abogado y del industralist Vigo Manuel N.A., en Nigrán (Pontevedra), al igual que Pablo Jose M.G., director de tierra de Inmonuar, una agencia integrada con el grupo mencionado, y con cuál habrían sido hechos los sobornos.
La investigación es la responsabilidad del grupo de los crímenes del Ciudad-planeamiento de funcionar sede (UCO) del protector civil, que agentes, además de las detenciones, realizaron once expedientes, la mayoría a las compañías relacionadas con los detainees y situadas en Madrid, Vigo, Murcia, Pontevedra, Madrid y Totana.
Entonces arrestaron a una persona en Totana, en detalle, el dueño de la compañía del producto de las aves de corral bien conocida en la región, que habría podido actuar como intermediario.
El grupo de Nuaria era responsable de desarrollar qué se convirtió en el complejo residencial más grande del municipio de Murcian de Totana, de que implicó la construcción de más de 5.000 casas, un curso de golf y dos hoteles con el "balneario".
La compañía adquirida en Totana 2.2 millones de metros cuadrados de la tierra que eran requalified y de su proyecto presupuso la duplicación de la población del municipio, de que tiene 25.000 habitantes.
El grupo de Nuaria integra las compañías como Autesa e Inomonuar, dedicados al desarrollo de propiedades inmobiliarias; Conycase, de que maneja los lugares del estacionamiento de las calles de Coruña, de Venezuela y del Fernando el cuadrado católico; Hogartel, dedicado al sector de comercialización directa; Preconiza abogó centrarse en la promoción, la venta y la instalación de los elementos de la construcción.
