Bono acepta para dirigir la candidatura del PSOE hacia Toledo y para presidir el congreso si está ganado.
El ministro ex José Bono de la defensa ha aceptado la oferta del presidente y del general Secretary de los socialistas, Jose Luis Rodriguez Zapatero del gobierno, para dirigir la lista del PSOE de Toledo hacia las elecciones generales siguientes y para ser presidente del congreso en caso de que los socialistas ganen las elecciones generales.
Esto fue anunciada en una rueda de prensa por la secretaria de la organización del PSOE, del Jose Blanco, y del Bono mismo, después de la reunión que fue celebrada esta tarde en el asiento federal del partido con Zapatero.
El ejecutivo ha justificado la oferta al ministro ex porque "es importante tener el mejor" de vida política y Bono "está entre el mejor".
Además, también fue precisado que "se parece" que presidirá el candidato socialista del grupo de Manchego el congreso si los socialistas ganan en las elecciones siguientes.
Bono substituiría a presidente Manuel Marín, de que del congreso el 15 el público hecho de noviembre su decisión de no estar parado para las elecciones generales siguientes y abandonaría su carrera en política para dedicarse a la lucha contra el cambio climático en el nivel de la universidad.
El ministro ex ha reconocido que el presidente del gobierno no ha parado el insistir de que él vuelve a la vanguardia política puesto que él se fue hace dos años.
Además, él ha indicado que, como los ciudadanos sepa quién será el vice presidente económico si el PSOE gana las elecciones, él tiene deseó anunciar quién presidirá el congreso, en un "acto de la transparencia".
Si él gana la oficina, Bono espera dar vuelta a la casa en "la casa del respecto y no insultarla o no gritar". Y haga "más y más visible a los ciudadanos".
"a veces desafortunadamente aparece que el único lugar en Madrid donde no está posible estar hable con confianza y el calmness es el congreso, el presidente del gobierno en una ocasión fue interrumpido en el senado 26 veces".
También, él ha elogiado el presidente actual, Manuel Marín y "el buen trabajo que él está haciendo" y no los tiene deseó ser visto como ya ocupar su poste, para no caer en qué, sus adversarios podría visión como "arrogancia".
