El céltico mirando en Milano al punto digno de octavo
Milano y célticos están jugando el martes en San Siro en la búsqueda del punto que necesitaron alcanzar sus metas respectivas en el cierre de la liga de los "campeones", como utilizan a los italianos para ser primeros y el Scots para su clasificación que condena.
Los italianos agregaron diez puntos y certificaron ya en el quinto paso del día con un lazo en Portugal, mientras que son célticos tienen nueve puntos, pero todavía necesitan otros cerciorarse de que el Shakhtar, con seises, y que Benfica, que tiene cuatro, no lo alcance.
Estos dos fósforos del grupo D serán jugados en una semana antes del final del sexto día, puesto que Milano tiene que jugar en el Mundial de Clubes en Japón, en donde hacen su principio en los 13 en los semi-finales en búsqueda de un lugar para el final en 16.
Así pues, este grupo será cerrado antes del resto y Giuseppe Meazza se parece contar con un lazo como el resultado, pero los dos equipos intentarán ir para un triunfo, y los italianos no desearán especular en el país y céltico sabe que el ganar sería primer y aseguraría una travesía mejor en los finales cuartos.
A Gordon Strachan el equipo podría servir incluso una derrota para los triunfos clasificados de Shakhtar si no, pero puede no ser confiado en porque la igualdad en nueve puntos significa que el paso de Ukranians, que la semana pasada perdida en Glasgow (2-1), pero ganado (2-0) en otro duelo vivo.
Así, Milanists amenaza hacerle una noche amarga para el Scots, que confía en conseguir en los cuartos para la segunda vez en una fila en la liga reestructurada de los campeones, después de que fueran derrotados exacto en este último redondo por una meta de Kaka en el tiempo extendido (1-0) después de 0-0 en el redondo.
Esperar la victoria del "rossoneri" será el Shakhtar a el cual solamente el triunfo hará, en caso que sea céltico perdiera ambos consigan en cuartos continuar en el UEFA.
Y en cuanto a Benfica, a pesar de ser el pasado y sin ninguna esperanza de permanecer en la competición europea superior, podría alcanzar el tercer lugar con una victoria, que juegan UEFA.
