Capital Político: El protector húngaro ha aumentado el nivel del riesgo de país
Las acciones del protector húngaro, establecido en agosto con la ayuda del movimiento para una Hungría más derecha, han levantado el nivel político del riesgo de Hungría y la región entera de un número de aspectos, según el riesgo analizando la división del capital político.
La entidad de la investigación publicó una "advertencia del riesgo," escritura: las acciones del protector húngaro están accionando un riesgo político excedente "que las tensiones étnicas ya existentes entre los residentes gitanos y del no-Gitano de Hungría podrían calentar hasta niveles tóxicos desde el a corto plazo, conduciendo a los conflictos étnicos que podrían dar vuelta violento."
La razón principal de esto es que húngaro guardaron estrategia política aparece ser dirigido provocando la acción de esta naturaleza, el instituto de investigación agregado.
Éste es el resultado de una de las faltas más serias de los jugadores políticos de Hungría: "los agentes primarios en el discusión público turned.over vida pública de Roma publican a los representantes de las fuerzas políticas radicales y extremistas, que han construido una estrategia política fuera de diferencias Gitano-Hu'ngaras."
Esto, capital político cree, ha intensificado el problema, haciendo cualquier diálogo normal imposible, reforzando a los extremistas, y aumentando la probabilidad que ocurrirán los conflictos violentos.
Además, el instituto de investigación cree que la atención doméstica e internacional extensa de los medios a las acciones húngaras del protector tiene "imagen internacional de Hungría perceptiblemente dañada, particularmente en lo que concierne a creencia en la estabilidad del país y en la sofisticación de su democracia."
Precisan que la publicidad y el ímpetu de aumento dados a la reorganización del radical y de grupos adecuados lejanos en Hungría que comenzaba en el otoño de 2006 han sido parte de la razón por la que un número de organizaciones que se llamaban las alianzas de la "autodefensa nacional" eran el comenzar establecido en el verano de 2007.
"la característica común de estos grupos es que se llaman las organizaciones cívicas mientras que abiertamente declaran que están preparando a sus miembros para la defensiva - incluyendo armado - las tareas (que citan a la gerencia del desastre, defensa nacional, aplicación de ley) mientras que declara que el policía y las fuerzas armadas, es decir el gobierno, es inadecuados para el papel," el capital político agrega.
Observaron que todos estos movimientos se han hecho dentro de una configuración que confía en la contra-poli'tica de la sociedad y el humor del contra-poli'tico-partido para disimular varias ambiciones políticas debajo de una capa de la acción cívica.
Es decir su énfasis en la naturaleza cívica de sus acciones y su opción de la asociación como su forma de organización no son simplemente ruses para evadir trampas legales al registro con las cortes, sino son también parte de una estrategia política.
Según el análisis, la actividad del protector húngaro está aumentando el riesgo de dañar nuestras relaciones con nuestros vecinos, también.
"en meses recientes varios de los vecinos de Hungría han citado a protector húngaro como peligro potencial. Los jugadores políticos ultranacionalistas entre algunos de estos vecinos han referido al establecimiento del protector húngaro como discusión para justificar sus propias políticas contra-Hu'ngaras.
Todos estos factores influencian la estabilidad política de la región, "él agregan.
El instituto de investigación observa que el establecimiento del protector húngaro no es un fenómeno único en central y Europa Oriental, y pues tal él aumenta el riesgo político para el conjunto de la región.
Observa que la operación del protector húngaro es similar a la del protector nacional búlgaro, establecido en agosto de 2007 por la unión nacional búlgara lejos derecha. (BNU).
Los conflictos serios que explotaron entre Roma y no-Roma en un districto de Sofía (Krasna Polyana) estaban detrás del establecimiento del protector búlgaro.
BNU se aprovechó de los disturbios para establecer a su protector, demandando que la meta de la organización era "autodefensa nacional."
Discutieron que durante los últimos 17 años Bulgaria hubiera estado conforme a "terror gitano," en cuál era capital el gobierno desamparado e indiferente, político conocido.
La iniciativa accionó el discusión calentado entre el público búlgaro, él agregó.
Una muestra que el riesgo del conflicto étnico ha aumentado, los analistas escribió, es que algunas organizaciones de Roma en Bulgaria han anunciado planes para establecer a un protector sus el propios como fuerza de la resistencia.
Puesto que el protector húngaro ha actuado hasta ahora absolutamente semejantemente al protector nacional búlgaro, es absolutamente posible que la comunidad de Roma de Hungría podría responder a la amenaza organizando su propia autodefensa, escribió el capital político en la advertencia del riesgo.
El encargado capital político Attila Juhász de la investigación respondió a una pregunta del servicio húngaro del alambre de MTI diciendo que el análisis del riesgo era una actividades del instituto de investigación de las principales.
Cada año,él dijo, publican análisis del riesgo, y si descubren cualquier factor que pudiera alterar riesgos, ellos notifican la opinión pública publicando una advertencia del riesgo, como ahora han hecho.
