Fue cantante de jazz de candidaturas: Esperanza Spalding es una sorpresa meterse en la categoría de mejor nueva artista 
Llevar a cabo a petición de un presidente, y la gente está obligado a tomar nota. 
Esperanza Spalding, la cantante y bassist de jazz de 26 años designado por el presidente Obama a cumplir en su ceremonia del premio Nobel de la paz en 2009, marcó uno de los grammys "sorpresas este año con una nominación en la categoría de mejor nueva artista. 
Considerando que Spalding ha sido un célebre figura en la escena su álbum de jazz desde 2008, "Esperanza", la candidatura es un poco head-scratcher, pero es coherente con el Grammys " reglas de un artista no liberar a más de tres álbumes antes de la grabación que establece la "identidad pública de este artista". 
Su ambicioso 2010 álbum de música de cámara, "la sociedad", sin duda marcado un paso adelante, y habida cuenta de su airily invitar abiertamente el estilo y una hábil mano del pop, funk y el latin influencias, es posible sacar al menos una línea de puntos para Norah Jones " Spalding de gran éxito en 2003, el equivalente más cercano a los votantes fue mirando hacia el vecindario de jazz en esta categoría en los últimos años. 
Los votantes de otros países cumplieron con razón fue la Vijay Iyer trío de "historicity" en la estimulación de la categoría, un álbum instrumental thrill-ride de un acta que fue una crítica de los favoritos del año pasado. 
Entre esas Iyer competirá en contra de incluir veterano saxophonist James Moody 's y Moody 4B "keyboardist" John Beasley el "positootly". 
Trombone Shorty, un raucous de Nueva Orleans favorito y frecuentes invitado a HBO el "Treme", se apresura en la categoría de jazz contemporáneo, que de lo contrario se inclina considerablemente hacia la fusión con NODS hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
El salvaje, Darcy steampunk-informed James sostienen la sociedad secreta ganado algunos merecido reconocimiento en la gran ensemble categoría, compite contra el Billy Childs Ensemble del rico chamber-jazz y el ever-adventurous Dave Holland, cuyo álbum "Live octet caminos" fue un buen ejemplo de la bassist democrática de la mano como un bandleader. 
