Con la literatura puede poner su dedo sobre ella 
La segunda ronda de los placeres de la lengua fue un paseo en el que los participantes promulgó la narración 
De sexo en un idioma que entiendo que pero... con el dedo sobre él? ¿qué tengo que hacer?, se pregunta el escritor Luisa Valenzuela invitó a inaugurar la segunda ronda de los placeres de la lengua, acontecimiento que celebra la literatura en español y que esta vez utilizó el subtítulo de su pregunta (en otra forma de la mesa redonda dedicada al sexo en el idioma, explicó). 
El dedo en ella... "Esto nos coloca en una posición difícil", dijo sweetly salidos el escritor argentino al público, principalmente de los jóvenes, que se reunió en la Feria Internacional del Libro de Guadalajara (FIL) para escuchar esta mesa redonda, moderada por Marisol Schultz y participó Valenzuela, Sergio Ramírez, Mayra Montero y Luis García Montero participaron todos. 
Luisa Valenzuela leer un texto que ha dedicado a Gonzalo Celorio y que Shultz definiría más tarde como una gran historia, con Luisa en primera persona, el protagonista que en la búsqueda del conocimiento, conocido como "", va de médico en médico, de quien no obtener respuestas aunque se mantuvo en el mismo hilo narrativo. 
La oradora deja el doctor convencidos: "quizá paciencia no es mi forte, tal vez es mi dedo". 
Al final, después de una frustrante enfoque con el trauma médico que duele que aclara que no es un término científico; es el psicoanálisis que vaya desentrañando el misterio: "El dolor es el verdadero abierto; el simbólico es la cicatriz". 
La protagonista suspiró aliviado y concluyó "sobre el dolor sólo he podido saber que la verdadera cuestión es abierto y que no existen", pero convencido de que los placeres y las trampas de la lengua han de ser mixtos. 
Valenzuela, el escritor, jugó con ambos. 
El nicaragüense Sergio Ramírez también mostraron un delicioso narración que tituló elogios de la invención, donde el dedo en el dedo no es el nombre sino es descubierto. 
En términos generales del realismo mágico, que narra la historia de un famoso bruja, que por las nubes, volver a tocar a los hombres que habían ido lejos o reparar las virtudes perdidas por una sirvienta, la narración que se convirtió en hablando de Estados Unidos, una gran novela en la que no falta desde el comienzo de su propio chroniclers quien ha dicho, y ha mencionado Bernal Díaz del Castillo, que critica los excesos de las cosas que dijo el tratamiento de los capitanes. 
Cervantes quien inventó todos nosotros (los escritores) reían de los falsos testigos que han comparecido en historias presenta como real, pero que nunca le dijo a la historia de Estados Unidos con imaginación que falta timidez. 
Sin embargo, destacó la "locura de personas y mentirosos son quienes mejor imaginar cosas" y es donde la realidad y falsedad son mixtos, donde se sabe si la cosa narrada pertenece a un lado u otro, en que la literatura de ficción alcanza su apogeo. 
De hecho, es llamado "Cervantes tradición. 
"por su filosofía de: somos lo que dicen de nosotros". 
Como para ella, el escritor Mayra Montero vio y aplaudió la variedad de interpretaciones que la invitación de FIL causas con su mesa el dedo en la dolorosa. 
La cuban-puerto costarricense señaló su propia hacia el gran dolor de la violencia social que atraviesa su país - y divide a América Latina -product de las controversias sobre el tráfico y venta de drogas. 
Creo que la buena literatura, buena poesía, buenas canciones encierra un compromiso tácito que por supuesto no es premeditada, indicó, tras señalar que la realidad de la literatura es la comunicación y la dimensión de los compromisos que se establece entre el autor y los lectores, y que es una "reacción química" de esta última. 
La noche fue cerrado por el poeta español Luis García Montero cuya intervención también hizo hincapié de que "el dedo en el dedo del escritor comprometido por escrito". 
Consideró que, en un mundo que vive en Prisa, también en el ámbito intelectual y control de aduanas de la conciencia que tiene efectos en dogmatismos, olvidando "que detrás de cada afirmación no hay un pequeño y detrás de cada negación hay pequeñas sí". 
"para ser dueños de nuestro pensamiento y la realidad debemos aclarar: y aclarar a menudo significa poner el dedo en el dolor y las molestias a las personas que son mucho más cómodo pensar en la caricatura, en blanco y negro, en ideas sin una sombra y también preocuparse de los poderes que prefieren un mundo en blanco y negro", dijo, invitando a recuperar el sentido de la escritura. 
