IP pide resultados del Congreso 
Eduardo Dávalos, Presidente de la CEC, propuso que los diputados asumir la gran responsabilidad de ser un ejemplo para un mejor Sinaloa por los diversos desafíos que enfrenta. 
Una legislatura de obras decente y libre de acuerdos entre los partidos y el Ejecutivo Estado está siendo solicitadas por el sector empresarial de Mazatlán, porque hay una convulsionada Sinaloa que se enfrenta a grandes problemas. 
Ayer la 60 legislatura fue votado, integrado por siete fuerzas políticas, 19 diputados del PRI, PAN, tres de los 13 del Partido Nueva Alianza, dos del PRD, uno del PT, uno del partido y uno más del PVEM, es decir, un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso de la s-state se menciona que llegan a cumplir una gestión limpia de compromiso a la sociedad y a los distintos sectores que requieren un responsable de la labor legislativa. 
Eduardo Dávalos Zamora, presidente del Consejo Coordinador Empresarial, propuso que el recién liberado 40 diputados del Congreso del Estado asumido la gran responsabilidad de ser un ejemplo para un mejor Sinaloa por los diversos desafíos que enfrenta. 
Esperamos que los diputados realmente va a ejercer su derecho, libre de acuerdos entre las partes porque es una costumbre de hacer acuerdos para proteger sus propios intereses y convertirse en un personaje en un carnaval de los gobernadores y los líderes de las fracciones parlamentarias. 
Para ello ha hablado de certificar el compromiso para establecer los necesarios puentes que podría ayudar al Gobernador para seguir adelante. 
Esperamos que vienen a hacer un trabajo digno y principalmente a la sociedad y a los sectores porque los habitantes de Sinaloa fueron los que les dio el voto de confianza durante las últimas elecciones. 
José Ramón Manguart Sánchez, presidente de la Asociación de Hoteles Tres Islas, consideró que uno de los mayores retos para el 40 representantes populares es el de presionar y sumar fuerzas en la búsqueda del crecimiento económico del Estado, porque hoy en día la situación económica es muy complicado. 
El más importante es impulsar el crecimiento económico, que genera incentivos para la inversión y la infraestructura y que, de alguna manera, formarán una nueva generación de puestos de trabajo. 
En cuanto a la actividad turística, exigió que los nuevos legisladores dar el peso revisado en el presupuesto del Estado para fortificar la secretaria de Turismo. 
Como he entendido esta es la segunda del Departamento de Estado con menos presupuestos y es incongruente una importante actividad económica y la generación de divisas y la inversión y que compite directamente con la industria agrícola. 
Aparte de exigir el etiquetado recursos turísticos de la detonación de los proyectos que contribuyan a dar seguridad al Estado de derecho y actualizar el alcohol que no ha sido capaz de resolver en las legislaturas anteriores. 
