Los crímenes anti musulmán han aumentado por 50%
Entre 2009 y 2010, crímenes anti musulmán aumentan por casi 50%, mientras durante el mismo período otras formas de violencia racial y religiosa se hubieran caído ligeramente, o no habían cambiado, según la estadística de FBI publicaron el lunes.
Según estas figuras, el número total de casos de violencia contra musulmanes movidos de 107 en 2009 a 160 en 2010, iguala a un aumento de 49%, como contra un aumento de 13% de casos de violencia contra católicos, una caída de 4% de ataques en judíos y un aumento global de 14% en crímenes antirreligiosos.
El número global de delitos de odio aumentó muy ligeramente a 6 628 casos, de que 47.3% fue motivado por diferencias raciales y 20% por diferencias religiosas, según FBI.
"Después de una disminución en 2009, perturba para ver estos crímenes que aumentan otra vez, enfatizaron los derechos de asociación de hombre, los Derechos humanos Primero," el aumento de casos de violencia anti musulmán es especialmente significativos," agregó la asociación en un comunicado.
"Derechos humanos Primero han enfatizado mucho tiempo que actos de violencia contra musulmanes, así como todas las formas de delito de odio, deben ser consideradas como infracciones graves de derechos humanos," agrega uno de los directores de la asociación, Paul Legendre.
"El gobierno norteamericano puede y debe hacer más tratar con su abuso, él agrega, juzgando que esto podría estar debido a la redacción de informes de policía en delitos de odio".
El "delito de odio" en la ley Federal, es un legado del período de lucha para derechos civiles.
Esta legislación fue pasada después de que la muerte de Martin Luther Rey para castigar actos de violencia que es ligada competir, el color de piel, la religión, el origen y orientación ahora sexual.
