Las Sras anuncian un protocolo para encontrar gene de obesidad
La Seguridad social dirige una investigación a encontrar el gene para la obesidad en niños y jóvenes; es apoyado por especialistas del IPN
El Instituto mexicano de la Seguridad social (MSSI) ha anunciado que eso realiza una investigación para descubrir el gene para la obesidad en niños y jóvenes, llamó el protocolo de 'la Genética de la obesidad en la niñez y la adolescencia', que proporcionará contando con marcadores asociados con peso excesivo.
En una declaración, la cabeza de la Unidad Médica de Investigación en la Bioquímica del Hospital de Especialidades, Siglo de XXI el Centro Médico Nacional, Miguel Cruz Lopez, explicó que fue integrado un equipo multidisciplinar de médicos, las enfermeras, los nutricionistas y los asistentes sociales.
El equipo es apoyado por especialistas y estudiantes de posgrado del Instituto Nacional de Sanitaria (NIPH) y el Centro para la Investigación y Estudios Avanzados (Cinvestav) el Instituto Politécnico Nacional (NPI).
La investigación invita la población permitida o no, para participar yendo al participante unidades deportivo del MSSI en el Valle de México, donde allí les será llevado a cabo las pruebas a niños, todos los sábados de 8:00 en punto.
Enfatizó que el protocolo comenzó en la unidad de deporte de Cuauhtémoc (Estado Occidental de México) y desde 8 de octubre, la actividad sucede en el Netzahualcoyotl unidad Deportivo (Estado Oriental de México).
Una vez que alcanzó el objetivo de traer 500 a 600 niños, el estudio continuará en la Unidad del Deporte de Independencia (Sur el México D.F.) y por último en la Unidad de Deporte de Morelos (al norte el México D.F.).
Explicó que el propósito de esta investigación es de comprender que los componentes y la importancia de la genética en relación con el desarrollo de la obesidad e identificar en niños y jóvenes mexicanos los factores de riesgo para prevenir la apariencia de enfermedades degenerativas crónicas.
En el 14 de noviembre, allí será celebrado el Día Mundial de la Diabetes, y el objetivo es de reunir tres mil niños y a jóvenes entre 6 y 14 años, con el consentimiento y supervisión paternal para la implementación de cuestionarios específicos en el alimento.
Ellos también serán preguntados por actividad e historia física hereditaria familiar de la enfermedad, para evitar los factores de riesgo que ocasionan las enfermedades como la diabetes o la insuficiencia renal.
Explicó que el sábado a todos los participantes será aplicado anthropometric medidas (peso, la altura, y circunferencia de cintura), medidas de tensión, y la determinación de glucosa, los triglicéridos, el colesterol y la insulina y genético (procurando identificar genes que son asociados a la obesidad de la niñez).
Cruz Lopez dijo que esta investigación refleja la preocupación de profesionales de la medicina para el aumento de peso alarmante en niños.
La salud Inspecciona hecho entre 1999 y 2006 informaron que en sólo seis años había un aumento en el caso de los chicos, el 77 por ciento fue obeso, y el 47 por ciento en el caso de las chicas; en función de peso excesivo allí también fue observado una subida dramática, "dijo el especialista del MSSI.
Dijo que la justificación para buscar los marcadores son basados en que la población del país varía de otro en su historia genética.
Informó que en el promedio, el mexicano tiene un 65 por ciento de herencia, el 30 por ciento europeo y el cinco por ciento africano india norteamericana y esta condición son reflejados en los genes que son asociados con la diabetes y peso excesivo.
Explicó eso generalmente, la genética de la obesidad tiene como resultado la incapacidad para quemar el exceso de energía que consumimos (calorías) y que es almacenado como la grasa.
El investigador explicó que el beneficio directo para los participantes es una evaluación completa de los niños, que puede discernir si tienen cualquier grado de peso excesivo u obesidad.
Aún, dijo, la presencia de dobleces oscuridad-de color (acantos) en el cuello y el antebrazo indica la probabilidad de sufrimiento de desórdenes metabólicos e incluso de prediabetes.
La información es manejada con la confidencialidad, los médicos lo entregan por escrito a los padres, a quien explican cada uno de las medidas y cambios en el estilo de vida que tiene que ser emprendido a prevenir la enfermedad.
Cruz Lopez explicó que hay tres componentes mayores que causan peso excesivo, la obesidad y otras enfermedades crónicas: estilo de vida sedentario, que es la falta de actividad diariamente física, permaneciendo la mayor parte del día y mirar la televisión y utilizar medio de transporte en vez de andando distancias cortas.
También está debido a la toma calórica alta, debido a significar, y debido al consumo aumentado de bebidas azucaradas, el carbohidrato (tamales, el pan, la pizza, la hamburguesa, etc.) con la grasa y la proteína alta y la genética analizó en este protocolo.
