El asfalto de UNAM evitaría baches
Rafael Herrera, un investigador en la Facultad de la Química de UNAM, desarrolla asfalto polímero-modificado para producir una mezcla con el mejor desempeño, a pesar de las condiciones y la temperatura ambientales
Si las señales enviadas por la superficie del camino fueron asistidas, sería necesario para reparar aproximadamente 200 mil baches cada estación de las lluvias en el Area Metropolitana del Valle de México, dijo Rafael Herrera Najera, un investigador en la Facultad de la Química (CF) del UNAM, que dijo que si el proceso de construcción y mantenimiento de un pavimento de asfalto es adecuado, los baches podrían ser reducidos o aún completamente eliminados.
En su conferencia UNA vista tecnológica del bache, publicado bajo el Año Internacional de la Química, anunció que el laboratorio él es responsable de desarrolla un polímero asfalto modificado para producir una mezcla con características semejantes al asfalto, pero con una mejor fuerza mecánica, en temperaturas altas y bajas.
Herrera Nájera dijo que este tipo de asfalto modificado podría ser utilizado en los lugares donde el tiempo está muy caliente, como algunas ciudades en el norte, para mejorar su desempeño, y por lo tanto la formación de baches.
Explicó que el asfalto, la parte más pesada de petróleo es un conjunto de moléculas de hidrocarburo, de algún de peso alto molecular, de llamado asphaltenes, y de otro de peso molecular bajo, llamado maltenes, que juntos da el camino surge su viscoelastic conducta típica.
La conducta de viscoelastic del asfalto consiste en el hecho que en temperaturas altas cerca de 180 grados, se comporta como un líquido en 120° C, su viscosidad es muy alta y en 50 grados centígrados tiene un casi estado sólido, mientras que en temperaturas muy bajas el asfalto llega a ser frágil, dijo.
Esto significa que la resistencia del asfalto de la calle no es uniforme, pero es modificado durante el día según las condiciones y la temperatura ambientales, dijo el especialista en la ingeniería química.
El investigador de CF observó que las calles de México D.F. son cubiertas en su mayor parte por pavimento flexible, que es compuesto de seis capas de material, fuera de que el último tres implica el asfalto.
Entre las capas más superficiales es el asfalto, compuesto de pequeñas piedras mojada en el asfalto y entonces comprimido.
Cada uno de las piedras que componen esta cubierta, él dijo, es mojado con asfalto.
Al conducir vehículos y engendrar el esfuerzo, permite las fuerzas para esparcir muy bien en el pavimento.
Si fue modificado asfalto que esparciría aún mejor, dijo el ingeniero químico.
En la cubierta de asfalto, él agregó, es colocado una capa final llamado arrollar cubrir, que es hecho un material de piedra fino, significando arena también mojado en el asfalto.
Desde que esto es la capa que estará en el contacto con las ruedas del vehículo, debe tener una mejor fuerza mecánica que el asfalto que cubre y proporciona el camino fricción.
Como siendo la parte del pavimento que recibirá y difundirá los esfuerzos, el arrollar cubierta también requiere el espesor apropiado y el material que está hecho de debe ser toma en consideración.
El tiempo, especialmente variaciones de humedad y temperatura son también un factor muy importante de considerar, regar especialmente, dijo, porque afecta mucho el desempeño del asfalto.
Cuando el suelo es mojado, es regado difunde dentro de la cubierta y es difícil de salir, este causar un ablandar de todas las capas del pavimento, y por lo tanto la formación de baches.
En la formación de un bache, él dijo, el primer llevar es el arrollar que cubre y sólo después de que eso sea afectado el asfalto, pero el daño no sucede instantáneamente, es un proceso que debe ser asistido en los primeros signos con programas apropiados de mantenimiento.
También un miembro del Sistema Nacional de Investigadores explicó que la carga de vehículo es otro factor importante en la formación de baches, y por lo tanto el espesor de cada capa del pavimento siempre debe ser hecho en relación con la carga del vehículo y asegura este cumplimiento, para prevenir la formación frecuente de baches.
Rafael Herrera dijo que hay de todavía investigar mucho y para trabajar para hacer en el asfalto, por ejemplo, emulsiones de asfalto, que en otros países es ya en el mercado e incluso en baches de reparación de ayuda con la facilidad y sin utilizar temperaturas altas.
