Allí debe ser hecho contribuciones a trabajo
Los trabajo sociales se refirieron a en los programas como Hábitat, el Rescate de Espacios Públicos y 3x1 para emigrantes se arriesga para no ser completado ni para tener tardanzas graves debido a la falta de fondos, dijeron Miguel Angel Lopez Miranda.
El Director del Desarrollo Social Municipal indicó que aunque hasta ahora los programas de trabajo hayan avanzado están en peligro porque el Gobierno de Estado falló de hacer las contribuciones que corresponden, que representa un superior de recurso a 11 millones de pesos en tres programas.
Notó que la inversión total en estos tres programas es de casi 50 millones de pesos, de que el Estado tiene que contribuir con el 25 por ciento y hasta ahora sólo la Federación y el Municipio han proporcionado recursos para los trabajo, así que la tardanza posible en la terminación de éstos es vigente.
"Tienen que contribuir con casi 12 millones e incluso aunque el año termina ellos no nos han dado una moneda de diez centavos, desde que comenzando con julio ellos tuvieron que darnos una parte," dijo, "para no retrasar hemos comenzado los trabajo y ellos son avanzados muy, pero necesitamos el dinero".
Mencionó eso el año pasado, durante la administración de Jesús Aguilar Padilla, el Estado no se conformó con las contribuciones que tuvo que hacer, para que al principio de la administración el municipio tuviera que pedir dinero prestado cubrir más de 7 millones, una suma que no fue proporcionada en aquella ocasión por la administración de estado.
"Sucedió a nosotros en la administración anterior porque el Estado no tuvo la capacidad financiera para participar y los programas siguieron avanzando, y este año para conseguir acceso a estos programas que tuvimos que conseguir los recursos para cubrir lo que el estado dejó pendiente," explicó.
Aunque hay un compromiso de las autoridades de estado de conformarse con la entrega de estos recursos, él dijo que la petición fue hecha al Secretario de la Administración y Finanzas, Armando Villarreal, para acelerar los esfuerzos para que los porcentajes que correspondan a ellos venir lo más rápidamente que posible.
"Tienen que contribuir con casi 12 millones e incluso aunque el año termina ellos no nos han dado una moneda de diez centavos".
