El tribunal valida "transición digital de televisión" en México en 2015
El reemplazo de analógico con digital es uno de los cambios más importantes que ha golpeado el mundo en los últimos años
El Tribunal Supremo (SCJ) rechazó las controversias constitucionales traídas por el Senado y la Cámara de Representantes contra el presidencial decretan que eso trae hacia adelante el llamado "transición digital de televisión" de 2021 a 2015, desde que los ocho votos necesitaron para invalidarlo no fue obtenido.
Una minoría de cuatro ministros, inclusive el Presidente del Tribunal, Juan Silva Meza, consideró ese Presidente que Felipe Calderon no excedió su autoridad publicando un decreta detallando las acciones para tomar para lograr la transición a la televisión terrestre digital.
Con este resultado, la controversia constitucional promovida por el Senado, fue rechazada para no encontrar la mayoría calificada de ocho votos para el Tribunal para pronunciar en la constitucionalidad ni la inconstitucionalidad del decreta, y esto se queda vigente.
El proyecto de la oración preparado por el Ministro Olga Sánchez Cordero, propuso declarar inconstitucional el decreta, porque la regulación de materiales de radio y televisión es un poder reservado por la ley a la Comisión Federal de la Telecomunicaciones (Cofetel), en la infracción de los principios de subordinación y ley jerárquicas reserva.
Sólo Zaldivar, Jorge Mario Pardo, Margarita Luna y Sánchez Cordero votaron para el proyecto.
Con este discusión, tanto el Senado como la Cámara de Diputados promovieron dos controversias constitucionales para contradecir el decreta, y para apoyar los reclamos, el ministro Sánchez Cordero suspendió la aplicación del decreta y todas las acciones estipularon allí con respecto a la transición digital.
En los ministros" encontrar allí también fue decidido rechazar el reclamo archivado por la Cámara de Diputados, sin entrar en la discusión del proyecto, también a cargo del ministro Sánchez Cordero.
En su discurso, el ministro dijo que él no concordaba con los discusiones del proyecto en el sentido que el ejecutivo federal no puede estructurar por general gobierna las medidas para la administración pública ser preparadas.
"Ni considero que si hecho afectaría la autonomía del cuerpo regulativo," y recordaría que la planificación de políticas públicas en áreas estratégicas como el sector de telecomunicaciones corresponde a al ejecutivo federal, que tiene un mandato constitucional, la guía del Estado.
El reemplazo de analógico a digital es uno de los cambios más importantes que han golpeado el mundo en los últimos años, y tienen como resultado una mejor utilización del espectro radio-eléctrico, mejor calidad de la señal y más canales.
Retrasando el cambio, él dijo, significaría retrasando los beneficios de digitalización, que implica una decisión pública de interés, que tiene no sólo una dimensión técnica, "como cubre asuntos económicos, sociales, políticos y nacionales de seguridad".
Estos asuntos, él dijo, "requiere la operación del sistema entero establecido bajo el principio del estado gerencia económica, comprende un grupo de los poderes que la Constitución lleva al estado el poder ejecutivo".
Recordó que muchos países alrededor del mundo ahora han completado la transición digital, y lo han hecho por el ejecutivo, a pesar de de habiendo especializado sumamente los cuerpos técnicos.
Allí no puede ser concluido que el gobierno, publicando el refutó decreta, que invade en ninguna manera la competencia del Congreso, proporciona en el área administrativa la observación de las leyes publicadas por la Legislatura, él dijo.
