La adversidad climática fue más despacio la economía
Durante el primer año de gestión de Mario Lopez Valdez, en Sinaloa aumentó el paro y la informalidad, la inversión en el extranjero disminuyó y la economía fue reducida.
2011 son un año que será recordado en la historia económica de Sinaloa, para ser relacionado al primer año del gobierno de Mario Lopez Valdez también llamó el año del cambio, que engendró gran esperanzas como considera el desarrollo de la economía, pero dada la adversidad climática del principio del año, no había crecimiento, como allí fue experimentado un descenso en los principales indicadores del desarrollo económico.
Las temperaturas bajas de febrero, no sólo hicieron causan pérdidas de millones para el sector agrícola, pero limitaron las posibilidades de la economía de estado a crecer, causando una contracción de la actividad económica en general de 3,6 por ciento en la primera mitad del año, principalmente apoyado por la caída histórica del 31,16 por ciento en la agricultura, que afectó la dinámica de otros sectores económicos.
Según el informe con respecto a las áreas afectadas por el escarcha, publicado por el Concilio mexicano para el Desarrollo Rural Sostenible allí fueron dañados 835,582 hectáreas, fuera de que 78,03 por ciento sufrió daño total y quedarse del 21,07 por ciento tuvieron daño parcial. Las principales cosechas dañadas fueron las verduras, el maíz y el garbanzo.
La caída en la actividad económica ha engendrado, hasta noviembre, un aumento constante del paro en el estado, según el Instituto Nacional de la Estadística y la Geografía, la tasa de estado de paro durante los primeros tres cuartos del año registró un crecimiento acelerado, de enero a 55,053 de marzo habitantes de Sinaloa estuvo parado, con una tasa del 4,53 por ciento de la población económicamente activa para el segundo trimestre, la tasa llegó a ser El 5,28 por ciento, y entre julio y septiembre el promedio continuó aumentar al 6,19 por ciento, una tasa que en función del número de personas representa más de 74,000 de a habitantes parados de Sinaloa, un aumento comparó a la primera mitad de 18,969 individuos.
Liquidez más baja
El paro en Sinaloa durante el año es multi-factorial, para el economista Gerardo Lopez Cervantes, el director en la Facultad de la Economía y ciencias sociales del UAS, el crecimiento del paro puede ser explicado indirectamente, dependiendo de las acciones que la política pública ha sido tomada.
"Lo que vemos ahora es un aumento del paro que tiene que ver con varios factores, inclusive la pérdida de liquidez en el mercado para el propósito de una limitación de recurso impuesta por la legislación que entró el Congreso para combatir el lavado de dinero desde entonces para las personas que poseen ilegalmente dólares no son el trabajo fáciles con, invierten y los utilizan en algo" dijo.
Inmigración parada
Lopez Cervantes dijo que en el aumento del paro hay también un factor demográfico.
"El número de personas que deja el estado en busca de un trabajo en el extranjero, en Estados Unidos ha sido restringido, ante todo debido a las dificultades para entrar, y para apoyar de todo porque una vez ellos entran ellos ya tienen demasiadas dificultades en encontrar un trabajo, que grupo de personas permanece y demanda los trabajos aquí, en el estado, causando que la tasa del paro a subir," dijo.
Informalidad
El análisis de mercado de trabajo de Sinaloa consigue peor cuando teniendo en cuenta el nivel alto de informalidad que prevalece entre las condiciones de trabajo, según INEGI, el 60,38 por ciento de la población activa en los trabajo de estado sin ser citado como trabajadores a cualquier institución de la seguridad social.
Además del paro y la informalidad, otro recordatorio de trabajo de estado es representado por sueldos bajos; la entidad tiene los sueldos más bajos en el país, según los registros del Instituto mexicano de Seguridad social y el Ministerio de Trabajo y asistencia social.
Los ingresos medios mensuales de trabajadores de Sinaloa fueron, hasta septiembre, 5,352 pesos, bien debajo de la media nacional, eso es de 7,375 pesos.
La contracción de FDI
Además de la caída en la actividad económica y la tasa alta del paro, en 2011 allí fue registrado el descenso más grande en la inversión directa extranjera durante los últimos 10 años, según el Ministerio de Finanzas de enero a junio el estado FDI totalizó 630,697 dólares, que representa una caída del 87,74 por ciento comparado a los dólares 5.143.312 durante el mismo período del año pasado.
Por su parte, el Ministerio del Desarrollo Económico del Gobierno de Estado dio cuenta una inversión total de pesos 17.280.000 durante el año, que ocurrió principalmente en compañías terciarias de sector.
Deuda
Contra el fondo de baja económica, el gobierno de estado preguntó en julio durante el estado Congreso, la aprobación de un crédito de 3 mil millones de pesos, que sería para la inversión en proyectos de infraestructura en 18 municipios, para reactivar la economía, la aprobación congresional local fue para un suma de 2,600 millones de pesos, y hasta noviembre no beneficios de la deuda fueron observados en cualquier sector del estado Economía.
Reacciones
Para representantes de negocio, el primer año del gobierno de Mario Lopez Valdes demuestra una falta de la capacidad del gobierno.
Miguel Loredo Lopez, el presidente de la Cámara Nacional de la Industria de Transformación, dijo que durante 2011 había una falta de armonización de las voluntades de varios sectores, inclusive el gobierno de estado mismo.
"El desempeño de la economía en Sinaloa este año ha sido realmente pobre, uno tiene que trabajar duro recobrar el suelo perdió este año, en 2012 debemos redoblar nuestros esfuerzos, nosotros fallamos de alinear los esfuerzos de todo y sobre todo el movimiento bueno y sincronizado del nuevo equipo del gobierno, nosotros esperamos que eso será el año próximo mejor" dijo.
Lentitud económica
Lopez Loredo dijo que los acontecimientos como escarcha temprano este año paraba la economía de estado y su desempeño y el crecimiento fue restringido.
"El flujo económico bajo es el producto de varios acontecimientos, inclusive escarcha, uno de los principales efectos ha sido una economía lenta que no gira lo bastante rápido para engendrar un dinamismo económico que permite teniendo un nivel aceptable de flujo de los procesos, los productos y los servicios y por lo tanto, a fines del año nosotros lo cerramos debajo de nuestras esperanzas," dijo.
Redefinir la vocación
Teodoro Salazar Uriarte, el presidente de los Empleadores" la Confederación de la República mexicana en Sinaloa, dijo que el estado es requerido a procesar las actividades productivas más dinámicas.
"En términos generales, nosotros encontramos que allí hemos estado trabajando en, creemos que es necesario para desarrollar un programa a largo plazo que redefine la vocación y el curso económico del estado, es importante detonar todo el material y recurso potencial humano que Sinaloa tiene," dijo.
El trabajo para Hacer
El Presidente de Coparmex enfatizó la importancia de establecer una futura visión para indicar mejor los esfuerzos del gobierno.
"En conjunto yo diría que el Gobierno ha estado esforzándose por tener éxito en varios campos, en función del desarrollo económico que hay algún progreso pero es importante desarrollar un programa a largo plazo," dijo.
Notó que la administración actual ha mostrado progreso en su propia manera de dirigir la política pública.
"Hay elementos que permiten nosotros diciendo que el gobierno llega a ser más inclusivos, y lo que puedo decir es que hay el trabajo hecho y yo pienso que el gobierno está enterado que hay el trabajo de hacer," dijo.
