Mujica viaja a México para reforzar corbatas políticas
Una delegación oficial dirigió por el Presidente José Mujica uruguayo, y compuso de varios ministros y empresarios, empezará este el martes una visita a México para expandir el comercio entre los dos países y para acercarse cuestiones políticas en la región.
Mujica encontrará el próximo miércoles su mexicano iguala, Felipe Calderon, el punto más alto de un orden del día extenso de reuniones con autoridades políticas y comerciales y una reunión con la comunidad de uruguayos que viven en México, según el horario soltado por la Presidencia uruguaya.
La reunión entre ambos presidentes, en la ciudad de Guadalajara, será "favorable para el cambio de información como considera las cuestiones políticas entre las dos naciones," como publicó la Presidencia del país sudamericano en su sitio web.
Según los medios locales, Mujica procura conseguir el apoyo de Calderon para Uruguay en el incidente con Francia que surgió cuando el Presidente Nicolas Sarkozy francés, incluyó el país sudamericano en una lista de paraísos fiscales en la reunión G20 en la ciudad francesa de Cannes.
En su discurso, Sarkozy amenazó a excluir de la comunidad internacional esos países que se quedan paraísos fiscales, una declaración que causó la negativa de Uruguay y la llamada a la consulta de su embajador en el país europeo.
México preside desde noviembre, el G20, un grupo compuesto de los países más poderoso, desarrollado y nacientes de mundo, y tiene vigente con el país sudamericano desde enero este año, un acuerdo para cambiar información de impuesto para evitar dobles imposiciones.
El gobierno de uruguayo ha procurado acelerar en los últimos años la conclusión de arreglos de cambiar de impuesto para dejar la "lista gris" de la Organización para la Cooperación y el Desarrollo Económicos (la OCDE), compuesto de los países que no aplicaron todos los estándares internacionales de cooperación de impuesto.
En la utilidad mercantil, México y Uruguay tienen vigente desde que 2004 un Acuerdo de libre cambio (FTA) que ha aumentado el cambio de bienes entre ambos países.
