El Gobierno Español no elevaba objeciones en cuanto a los vuelos de CIA 
El Gobierno Español no elevaba objeciones en cuanto a los vuelos de CIA con prisioneros Taliban y de Al Qaeda que estaban yendo a Guantánamo vía territorio español, según el el embajador de EE.UU. en el telegrama de Madrid. 
De esta forma es reflejado por los documentos filtrados (cables) por Wikileaks al periódico El País, dónde se añade que el primer vicepresidente del Gobierno en ese tiempo, Maria Teresa Fernandez del Vega, preguntaba que el Ejecutivo Español se informaba en orden "a poder demostrar que habían realizado procedimientos de control apropiados en el avión extranjero esa España disgustada". 
En junio 2006, después de un informe del Consejo europeo donde había acusaciones de complicidad en prácticas en contra de derechos humanos en una docena de países, entre el cual es reunión de Spain,a tenía lugar entre el ex- el embajador americano Septentrional Eduardo Aguirre y Fernandez de la Vega. 
El vicepresidente reconocía que el informe del consejo "había llevado el Gobierno de Zapatero fuera del juego" e insistido que España no tenía nada para esconderse en cuanto a esta cuestión. 
"De la Vega enfatizaba que España no eleva objeción para los vuelos de inteligencia sobre territorio español". 
"Sencillamente quieren ser informado" en orden para evitar "ser cogido por sorpresa", Aguirre se refiere en un telegrama. 
También el Ex-Ministro de Asuntos Externos, Miguel Angel Moratinos, indicados al embajador al cual el Ejecutivo Español "quería darle esta cuestión tan poca atención como posible, aunque siendo en manos de los jueces, el Gobierno tenía una influencia limitada". 
Por otra parte, en enero de 2007, el fiscal Vicente González transmitía la desclasificación de documentos del Centro Nacional de Inteligencia (CNI) y del ministerio de Defensa en cuanto a los vuelos de la compañía" a la Embajada que no intentaría bloquear la iniciativa del juez de pedir" 
Esta información no contiene ningún elemento incriminatory ni cualquier información sensible", explicaba la Embajada después de haber hablado con el fiscal. 
Sin embargo, los EE.UU. reflejados en su preocupación para "la coordinación aparente entre el juez español y los fiscales alemanes", más de la información desclasificada del CNI o el ministerio de Defensa. 
"Esta coordinación entre investigadores independientes complicará nuestros esfuerzos por comportarse discretamente el caso entre Gobiernos"; dice Aguirre. 
En marzo de 2007 durante una comida entre el embajador de los EE.UU. y ministro de los Asuntos Internos, Alfredo Perez Rubalcaba, éste comentaba a él eso "aunque los jueces españoles son rabiosamente celoso de su independencia y hará lo que consideran ser correcto", había dado instrucciones a su colaboracionistas" a evitar comentarios de retórica avivada, en un intento de reducir la temperatura". 
El embajador también expresa su preocupación para la acción del PP en esta cuestión. 
"A pesar de su orientación general pro americana, nuestra experiencia sugiere que el PP no dudará al capitalizar indicación de que el Gobierno de Zapatero toleraba o deliberadamente ignoraba acciones de los EE.UU. que se podrían interpretar como posibles violaciones de los derechos humanos, aunque estas revelaciones tengan negativo consecuencias para el Gobierno de los EE.UU".,indica. 
