El geriatra afirma que las muertes eran causadas por "la falta de medio" 
Los propietarios del centro de Olot no descartan que su asistente mataba a más de 11 personas mayores 
La gente a cargo con el hospital geriátrico que La Caritat de Olot (Gerona) ofrecía una rueda de prensa ayer para subrayar el daño que ha hecho a la institución la conducta criminal de Joan Vila Dilmé, el enfermero el cual mientras allí matado por lo menos once personas mayores que tenía bajo vigilancia. 
El director de la residencia, Joan Sala, parecía acompañado por el abogado del centro, abogado Joan Canada, y anunciado eso "el intención de La Caritat would sujetar la culpa sobre el individual responsable para de las muertes pero "legalidad y la responsabilidad nos obliga a asumir la situación pragmática de gente responsable civil". 
Y que además de la pérdida social de prestigio que la organización puede encontrar para no haber detectado a tiempo las actividades criminales del centinela, la gran amenaza para el Caritat tiene ahora toma la forma de de una indemnización sustancial que es calculada ya por los apoderados de los familiares de las víctimas. 
Joan Vila Dilmé ha confesado que el primer crimen se remonta a agosto de 2009 y que desde entonces no paraba de matar. 
El juez ya mencionaba en el documento que ordenaba la exhumación de ocho cuerpos - pacientes viejos del hospital geriátrico- que sospechaba que en muchos casos ningún doctor personalmente examinaba los cuerpos absolutos pero, teniendo en cuenta la edad y las patologías de los pacientes, el procedimiento era hecho por teléfono. 
La Caritat, por su director, completamente negaba este extremo ayer y mencionaba que "la falta de medidas no podría haber sido en ningún momento la causa de lo que había sucedido". 
El abogado de La Caritat añadía que "en la causa no hay indicación que ha habido una acción imprudente por parte de ninguna otra persona que no es la culpable". 
Éste bautizado como "Ángel de Muerte" confesaba 11 asesinatos anteayer y detallaba que cometía el primer crimen en el 29º de agosto de 2009 y un mes y una mitad posterior, matada otra abuela. 
En este caso una sobredosis de insulina le daba la muerte; a diferencia del primer crimen cometía con una mezcla de comprimidos sedativos. 
El director del Caritat dice que se complica para controlar que el personal del centro tiene acceso a medicinas. 
La sobredosis de insulina y el cóctel sedativo habría sido el mecanismo utilizado en seis de los nueve crímenes que el enfermero, en su ansia por aliviar el sufrimiento de los pacientes, utilizaba o que acabe con ellos. 
Pero las pruebas que se están realizando en el laboratorio se tendrán que aclarar si Vila no se está tendiendo e intentaba asegurar para sus primeras víctimas una muerte menos cruel o si, por el contrario, los quemaba internamente dándoles lejía como ya confesaba que había hecho con las tres mujeres que mataba entre el 12º y el 17 de octubre. 
En La Caritat no dan credibilidad a la llegada del centinela, ni al número de confesado asesinatos, que no refutan superior que es, y justifica su actitud en las versiones diferentes que Vila ha entregado sus visitas al tribunal y el disparate de cambiar su método de matar después de haber cometido con éxito, ocho asesinatos. 
Esto es por qué dicen que se ponían en la disposición de justicia para aclarar el alcance de este acontecimiento. 
