El grupo catalán facilitaba miles de pasaportes a Al Qaida 
Además de los siete prisioneros en Barcelona, en Tailandia había tres 
Los siete paquistaníes y el nigeriano detenido por agentes de la inteligencia de policía de Barcelona General formaba un grupo de jihadist que, dirigido de Tailandia, facilitaba pasaportes a grupos diferentes de Al Qaida, entre ellos "el Tigres para la Liberación de Tamilm Territory" (LTTE) y "Laskar y Taiba" (Deje), es autor de esto por última vez uno de los ataques de Bombay que causaban la muerte de 106 personas en 2008. 
El Ministerio de Asuntos Internos ha prestado atención a estas investigaciones, hasta el punto de asegurar eso con operación De "Kampai"; tiene sido"debilitar"el aparato de falsificación de Al Qaida a un nivel internacional y", por lo tanto, su capacidad operativa". 
Los investigadores calculan eso la celda, durante los dos años que ha sido activo en Catalonia, ha podido enviar miles de pasaportes a Tailandia, dónde se falsificaban y pronto se distribuía a los grupos que integran la galaxia criminal Al Qaida para que suya "combatientes" puede cruzar los bordes europeos y el uno de otros países occidentales con la impunidad total. 
La celda desmantelada no es la única que la red de jihadist tenía en Europa, por esto en las investigaciones allí han participado, además de los servicios de Tailandia, otras unidades de policía europeas, razón por qué no descarta que en territorio de la UE ocurre los acontecimientos similares a éste desarrollaban la noche de martes en Barcelona. 
En la coordinación con esta operación (El Junaid Humayun paquistaní, Atiqur Rehman, Jabran Asghar, Malik Iftikhar Ahmad, Mohammad Saddique Khan Begum, Tanveer Arshad y el Babatunde Agunbiade nigeriano eran detenidos todos), en Tailandia otro se había desarrollado con la captura de los paquistaníes Muhammad Athar Butt y Zeeshan Ehsan Butt y el tailandés Sirikanlaya Kijbumrung. 
El grupo sentado en España y otros países europeos se dirigía de Bangcock 
La red catalana - se golpeaba parte de ello en 2009 - principalmente robaba pasaportes a turistas que cumplían los requisitos marcados por la llamada "Mundialmente frente islámico". 
Es decir, los documentos tenían que ser en nombre de hombres entre 25 y 45 años, con la validez de varios años y sin visados imprimidos. 
En el modo de investigación se enfatiza que, por el momento, no se ha encontrado que ningún datos se relatan a las personas detenidas en Catalonia en cuanto al ataque de Bombay, aunque el autor de este ataque",Laskar e Taiba", se le ha robado a uno de los grupos de recepción de los pasaportes en España y pronto se ha falsificado en Tailandia. 
Sin embargo, se debería mencionar que los días antes de esto cometían ataque, de Catalonia allí eran enviados por una agencia de transferencias sobre algunos miles de dólares que se"invertían" en la compra de tarjetas de teléfono móviles que pronto se usaban por los miembros del "comando" que terminaba la vida de 106 personas. 
Los Policías han capturado mucha documentación. 
