El programa nuclear paquistaní genera gran agitación en los EE.UU. 
Islamabad produce armas atómicas a "un ritmo más rápido que cualquier otro país". 
Las filtraciones de Wikileaks confirman los bonos entre la gente Taliban y Pakistán. 
El contenido de la correspondencia entre la embajada americana en Pakistán y el Departamento de Estado de los EE.UU. filtrados por el portal de Wikileaks confirma la gran agitación que el programa nuclear paquistaní provoca en Washington. 
Además de los detalles que instruyen y sustanciales que se ofrecen en el contenido de las conversaciones y los pensamientos de los representantes diplomáticos americanos Septentrionales a los cuales se les atribuye en Islamabad, la jamba de documentos que la cooperación entre los dos países en la cuestión de seguridad atómica, en lugar de aumentar, "reduce" ", y que el país asiático inestable produce armas nucleares con "un ritmo más rápido que cualquier otro país". 
La peculiaridad del programa nuclear paquistaní - que los brazos no se montan pero permanecen almacenados por componentes para hacer difícil su destrucción en caso de ataque -- constituye una de las causas principales para asunto en Washington. 
De esta forma es enumerado por el embajador en Pakistán, Anne W. Patterson, en un informe anterior a la visita del ex-asesor de Seguridad Nacional, James Jones: "La proximidad de un poco de energía nuclear planta en el territorio bajo ataque Taliban, la dispersión dicha de los materiales nucleares y la vulnerabilidad de transporte de materiales atómico". 
La cantidad alta de gente implicada en los arsenales nucleares y los programas de misiles se está tomando en consideración, no solamente junto a los EE.UU., sino también por Rusia, como la razón para mantener su guarda. 
"Pakistán ha tenido que contratar personal con creencias religiosas estrictas para proteger la energía nuclear planta; dados los niveles educativos y culturales pobres, las organizaciones extremistas tienen más oportunidades de reclutar gente para trabajar en los programas nucleares o de misiles", decía el experto Yuri Carole, del Ministerio Ruso de Asuntos Externos, en una reunión con sus americanos homólogo. 
La información más nueva acerca de la documentación filtrada por el portal de Julian Assange es la cooperación decreciente entre los EE.UU. y Pakistán en temas de proliferación nuclear y el ritmo paquistaní alto de producción de arma nuclear. 
Una oficina de la embajada en mayo, eso describe como "frustrar" la comunicación con Pakistán, dice eso: "La transparencia es frecuentemente no-existente; las ofertas de ayuda quedan sin una respuesta o se rechazan". 
En otro mensaje, Peter Lavoy, funcionario público de la Inteligencia Nacional para el sur de Asia, afirma que "a pesar de la catástrofe económica, Pakistán produce armas nucleares en un ritmo más rápido que cualquier otro país del mundo". 
El embajador Patterson también pide a Washington, durante una visita de la cabeza del Ejército, General Ashfaq Kayani, que le dé órdenes claros a la persona a cargo que "el Ejército de Pakistán debe terminar el apoyo tácito a los grupos terroristas". 
