Nominaciones de Grammy: El cantante de jazz Esperanza Spalding es una cresta de sorpresa en la mejor nueva categoría de artista 
Actúe a petición de un presidente, y la gente es decidida de tener en cuenta. 
Esperanza Spalding, el bassist de jazz de 26 años y cantante escogido de mano por el Presidente Obama para actuar en su ceremonia de Premiado de Paz de Nobel en 2009, puntuada una de las sorpresas del Grammys este año con una nominación de perfil alto en la mejor nueva categoría de artista. 
Teniendo en cuenta que Spalding ha sido una cifra celebrada en la escena de jazz desde su 2008 álbum, "Esperanza", la nominación está un poco de una rasqueta de cabeza, pero es coherente con las reglas del Grammys de un artista no editar más de tres álbumes antes de la grabación que "establece la identidad pública de ese artista". 
Su invitando 2010 álbum ambicioso, "Sociedad de Música de Cámara", naturalmente puntuado un paso hacia adelante, y al cual se da su airily a estilo vocal y una mano diestra con la explosión, funk e influencias latinas, es posible sacar por lo menos una línea punteada a Spalding del éxito fugitivo de Norah Jones en 2003, el equivalente más estrecho a votantes de Grammy que miran hacia el vecindario de jazz en esta categoría en los últimos años. 
En otro sitio los votantes de Grammy correctamente honraban la "historicidad" del Vijay Iyer Trio en la categoría de álbum instrumental, un paseo de emoción estimulante de un disco que era un último año favorito crítico. 
Entre esos Iyer estará compitiendo en contra incluir el saxofonista veterano James Moody's "4B melancólico" y keyboardist John "el Positootly" de Beasley". 
Trombón Shorty, un favorito de Nueva Orleans ronco e invitado frecuente en HBO "Treme",era honrado en la categoría de jazz contemporánea, que de lo contrario se inclina fuertemente hacia fusión con cabezadas hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
El Darcy James Argue Secret Society salvaje, informado de steampunk ganaba un poco de reconocimiento merecido bien en la categoría de conjunto grande, que competía con el jazz de cámara rico del Billy Childs Ensemble y el Dave Holland atrevido siempre, el álbum vivo de cuyo octeto "Vías de acceso" era un ejemplo bueno de la mano democrática del bassist como un bandleader. 
