Con Literatura pueden poner su dedo sobre ello 
La segunda ronda de Los placeres de lengua era un paseo sobre el cual los participantes representaban la narración 
Que de sexo en la lengua entiendo eso pero ... ¿el dedo sobre ello? ¿Qué se me espera que haga?, preguntaba al escritor Luisa Valenzuela invitado invitaba a abrir la segunda ronda de Los placeres de la lengua, acontecimiento que celebra Literatura en español y que esta vez utilizaba el subtítulo de su cuestión (de otra manera la mesa redonda se dedicaba a sexo en la lengua, explicaba). 
El dedo sobre ello ... "Él lanzamientos nosotros en una posición difícil", decía dulcemente sin vacilar al escritor argentino al público, principalmente de gente joven, quien se encontraba en la Feria Internacional del Libro de Guadalajara (FIL) para escuchar esto alrededor de mesa moderada por Marisol Shultz y participada Valenzuela, Sergio Ramirez, Mayra Montero y Luis Garcia Montero todo participaba. 
Luisa Valenzuela leía un texto que dedicaba a Gonzalo Celorio y ese Shultz definiría más tarde como gran historia, con Luisa en primera persona como el protagonista que en busca de conocimiento sabido como "ello", va de doctor a doctor, del cual no obtiene respuestas aunque consigue clavado en el mismo hilo narrativo. 
Deja al doctor convencido: "quizás la paciencia no es mi forte, quizás ello es mi llaga". 
Al final, después de una aproximación frustrante con el doctor de trauma que quien aclara esa llaga no es un plazo científico; es el psychoanalyst que desentraña el misterio: "la llaga es la cosa abierta real; la cosa simbólica es la cicatriz". 
El protagonista suspirado aliviaba y concluía "en la llaga que solamente conseguía saber que la cosa real es abierta y que no existe"", pero convencía de que los placeres y los trucos de la lengua se tienen que mezclar. 
Valenzuela, el escritor, jugaba con los dos. 
El nicaragüense Sergio Ramirez también mostraba una narración deliciosa que titulaba Elogio de la invención, donde el dedo en la llaga no se nombra pero se descubre. 
En amplio plazos de mágico realismo, dice la historia de una bruja famosa, quién tocando nubes, restauraba hombres que habían ido muy lejos o reparaba las virtudes perdidas por una criada, narración que se giraba en hablar de América, una gran novela a la cual no faltaba del principio very sus propios cronistas quien lo decía y mencionaba a Bernal Diaz del Castillo quien critica los excesos de las cosas dichas por el conquistar capitanea. 
Cervantes quien inventaba a todos nosotros (los escritores) reía de los testigos falsos quien aparecía en historias presentaba como real, pero de lo contrario él nunca habría contado a la historia acerca de América con imaginación qué timidez de falta. 
Sin embargo, enfatizaba "gente loca y mentirosos son los que mejor imaginan cosas" y es dónde se mezclan la realidad y mentira, dónde sabe uno si la cosa narrada pertenece a un lado u otro, dónde alcanza la Literatura ficticia su apogeo. 
De hecho se nombra "Tradición de Cervantes. 
"Para su filosofía de: somos a qué se le cuenta acerca de nosotros". 
En cuanto a ella, el escritor Mayra Montero veía y aplaudía la variedad de interpretaciones que la invitación de FIL causa con su mesa redonda El dedo en la llaga. 
El Cuban-Puerto Rican señalaba su propio hacia la gran llaga de la violencia social que cruza su país - y divide Latinoamérica -producto de las disputas sobre venta de tráfico y droga. 
Creo que buena Literatura, buena poesía, las buenas canciones encierran un compromiso tácito que por supuesto no es premeditado, indicado, después de haber mencionado que la realidad de Literatura es la comunicación y la dimensión del compromiso que se instala entre autor y lectores, y eso es una "reacción química" de éste último. 
La noche era cerrada por el poeta español Luis Garcia Montero cuya intervención también ponía énfasis "que el dedo en la llaga del escritor comprometía a escribir". 
Consideraba que en un mundo que vive en una prisa, también en la aduana intelectual y control de la conciencia que tiene efectúa en dogmatismos, olvidando "que detrás de cada aseveración hay un pequeño no y detrás de cada negación hay pequeño sí". 
"Para ser propietarios de nuestro pensamiento y realidad nos debemos aclarar: y aclare a menudo medio poner el dedo en la llaga y molestar a esa gente que es mucho más cómodo pensar sobre el dibujo humorístico, en blanco y negro, en ideas establecidas sin una sombra y que también se preocupan a los poderes que prefieren un mundo blanco y negro", decía, invitando a recuperar el sentido de escritura. 
