Romano va hacia su primer título 
Cálculos de Rubén Roman Omar con tres derrotas en las finales, teniendo durante su carrera ups y plumones, pero sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey en la final, además dos estilos diferentes marcaban por la cara de sus técnicos, que se encuentran con un contraste marcado por resultados. 
Cálculos de Rubén Roman Omar con tres derrotas en las finales, teniendo durante su carrera ups y plumones, pero sabía cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora no había alcanzado la meta y esto es por qué es esta oportunidad muy especial para él. 
El Argentinean ha acabado siendo consolado con la medalla de corredor arriba, y seguía siendo un paso detrás de los ganadores y peculiarmente con equipamiento similar que ha jugado a finales consecutivas. 
Santos llegaba a su primera final como entrenador en la Correspondencia de Apertura de 2002, cuándo llevaba los reinos de Morelia con los cuales caía a 4-2 delante de Toluca; más tarde, en el Acontecimiento de Cierre de 2003 también llegaba al duelo decisivo y perdía también a ello en 3-1 y en efecto delante de Rayados. 
Ya con Santos Laguna, en la Correspondencia Bicentenaria de 2010, otra vez antes de Los Diablos, Rubén sufre otra vez un reverso, desde que su equipo terminaba igualmente lugares 2-2 delante de los creadores de salchicha después de 210 minutos de juego, pero en la vuelta de sanciones se ponía en la ventaja por 3-1 con dos oportunidades de sellar el título pero que finalmente tres jugadores fallan de los 11 pasos y sufrir el cambio 4-3. 
Rubén ya perdía dos finales con Diablos Rojos y uno con Monterrey, su rival a su vez, por lo tanto no quiere soportar el mismo destino, quiere celebrar un título para la primera vez, y afirma que la cosa más importante para él es la institución. 
Quiero ser un campeón, no quiero pausa cualquier estadística, esto es para un club, para una pasión y por consiguiente el título vendrá a mí, pero la cosa anterior es más importante, comentado el timonel cuando siendo preguntado sobre los números tiene en contra jugando a finales. 
Muy efectivo tiene la final anterior, de la cual, asegura, ha aprendido mucho", el solamente lección que podemos aprender es que hasta que el árbitro indica por señas el extremo que no podemos celebrar, nos preparamos nos mismos así como los jugadores porque el tiempo anterior, con dos sanciones que estábamos a punto de dejar y creo que eso es una lección que se aprender, no podemos celebrar hasta que el juego termina". 
Sabiendo que esta serie se podría definir en serie de penaltis, algo que no lo preocupa, porque confía en sus jugadores: "Uno debía nunca mira para ir a sanciones, pero más bien terminar en tiempo regular; a veces no tiene ninguna alternativa y es necesario estar preparado; en la correspondencia anterior se nos preparaba, desafortunadamente el destino jugaba en nuestras manos; a veces por nervios o ansiedad para tener el título dentro fuera de manos, pero no alcanzábamos este objetivo, y esto nos dejaba algo para esta final que esperamos ganar". 
El romano debería parar de ser un técnico corredor arriba y cata para la primera vez la gloria que los títulos dan. 
