El Congreso apruebe la transposición de MIFID que tuvo lugar el 1 de noviembre
Junto con sus procedimientos parlamentarios, que terminaron con la votación parcial del Congreso sobre las enmiendas incorporadas al proyecto en el Senado, el Gobierno ha presentado a la audiencia pública la regulación que desarrollará la nueva ley, con el objetivo de que llega la fuerza antes de finales de año.
Los representantes de diversos grupos de acuerdo en acentuar los esfuerzos hechos por los diputados y senadores para negociar y aceptar la mejor legislación para garantizar la protección de los inversores y regular en detalle la actividad de las organizaciones de modo que los mercados funcionen eficazmente.
La MiFID, que corrige el hecho de mercado de valores, tiene que ver con la modernización de los mercados financieros, que refuerza la protección del inversor, mejorando los poderes de la Comisión nacional de valores (cnmv) y la cooperación entre los diversos supervisores de la Unión Europea.
La nueva reglamentación concederán asesor financiero de servicios a las empresas especializadas así como a individuos naturales o legales, y crea un nuevo tipo de compañías consultores financieras (esis), las compañías consultores financieras (afi), que incluyen las empresas, los corredores, y la lista de gestión de empresas.
Además, amplía el número de sistemas disponibles para la ejecución de operaciones financieras, para incluir en el Reglamento son los mercados secundarios, los sistemas de comercio multilaterales, y los sistemas de órdenes, puedan competir con los gerentes de mercado de valores actuales.
La ley requiere también que las compañías de servicios de inversión para descubrir el mercado la clave de los detalles de su perfil del negocio, la exposición de riesgo y las formas de gestión del riesgo, y mantener un registro de todos sus operaciones para facilitar la supervisión por el cnmv.
En su paso por el Comité de Asuntos Económicos del Congreso, se introdujeron varias modificaciones, sobre todo las deudas deben ser consideradas como un instrumento financiero "complejo" debido a su alto riesgo para el inversor, que ha demostrado por lo que sucedió con el alto riesgo norteamericano hipoteca deudas (de).
Además, la transposición aprovechó la directiva legalmente definir las funciones que pueden desarrollar licenciados en la economía y las finanzas en 30 años después de la aprobación del decreto en 1977, que delimita las funciones profesionales reservado a los economistas profesionales.
Por su parte, el Senado promovió la creación de nuevos puestos en el sector financiero, tales como el asesor financiero, que trabajará para contratar o la recompensa y no requiere la aprobación del SEC y será capaz de ofrecer sus servicios y el corretaje de productos de comercialización para los clientes en varias empresas de inversión al mismo tiempo.
