El capital político: la guardia húngaro ha aumentado el nivel de riesgo del país
Las acciones por la Guardia húngara, establecida en el mes de agosto con la ayuda del Movimiento para una Hungría ha levantado el nivel de riesgo político de Hungría y de toda la región de una serie de aspectos, según los análisis de riesgo de división de capital político.
La entidad de investigación publicadas "un aviso de riesgo", escribe: las acciones de la guardia húngara provocan un riesgo político que excede "que las tensiones étnicas ya existentes entre los gitanos y los residentes de Hungría podrían calentar a niveles tóxicos tan pronto como el corto plazo, llevando a los conflictos étnicos que podría convertir violento".
La principal razón de ello es que la estrategia política de la guardia húngara parece estar destinadas a provocar la acción de esta naturaleza, la institución de investigación.
Este es el resultado de una de las más graves faltas de Hungría actores políticos: "los principales actores en la vida pública dada sobre el debate público de cuestiones de Roma a los representantes de las fuerzas políticas radicales y extremistas, que han construido una estrategia política de las diferencias.
Esto, capital político cree, ha intensificado el problema, haciendo imposible cualquier diálogo normal, reforzando los extremistas y aumentando la probabilidad de que los conflictos violentos.
Además, el Instituto de Investigación cree que la extensa interna e internacional de la atención de los medios de comunicación a las acciones de guardia húngaras "ha perjudicado considerablemente la imagen internacional de Hungría, en particular en cuanto a la confianza en la estabilidad del país y en la sofisticación de su democracia".
Indican que el aumento de la publicidad y el impulso dado a la reorganización de los grupos radicales y de extrema derecha en Hungría empezar en el otoño de 2006 han formado parte de la razón de un número de organizaciones que se llaman las alianzas nacionales de defensa propia fueron establecidas en el verano de 2007.
"el rasgo común de estos grupos es que se llama a sí mismo organizaciones cívicas declaran abiertamente que están preparando a sus miembros para defensivo - incluso armados - (citando las tareas de gestión del desastre, la defensa nacional, la aplicación de la ley) al declarar que la policía y las fuerzas armadas, en otras palabras, el Gobierno, es inadecuado para el papel," capital político suma.
Señalaron que todas estas medidas se han hecho dentro de una configuración que confía en la sociedad y el ánimo para encubrir varias ambiciones políticas bajo una capa de acción cívica.
En otras palabras, su énfasis en la naturaleza cívica de sus acciones y su elección de la asociación como su forma de organización no son solamente ardides para esquivar escollos legales al registro con los tribunales, pero también son parte de una estrategia política.
Según el análisis, la actividad de la guardia húngara aumenta el riesgo de perjudicar nuestras relaciones con nuestros vecinos, demasiado.
"en los últimos meses, varios de los vecinos de Hungría ha citado la guardia húngara como un peligro potencial. Los actores políticos entre algunos de estos vecinos se han referido al establecimiento de la guardia húngara como argumento para justificar sus propias políticas'.
Todos estos factores influyen en la estabilidad política de la región, "suma.
El Instituto de Investigación se observa que el establecimiento de la guardia húngara no es un fenómeno único en Europa Central y Oriental, y como tal se aumenta el riesgo político para el conjunto de la región.
Esto indica que la operación de la guardia húngaro es similar a la de la Guardia Nacional búlgara, establecido en agosto de 2007 por la extrema derecha la Unión Nacional búlgara. (bnu).
Los conflictos serios que estalló entre Roma y quienes no lo son en Sofía (krasna polyana) estaban detrás del establecimiento de la guardia búlgara.
Bnu sacaba provecho de los disturbios a establecer la guardia, afirmando que el objetivo de la organización haya sido "nacional".
Se argumentó que durante los últimos 17 años, Bulgaria había sido objeto de "terror gitano", en el que el Gobierno fue indefensa y indiferente, capital político eminente.
La iniciativa provocó un debate acalorado entre el público búlgaro, añadió.
Una señal de que el riesgo de un conflicto étnico ha aumentado, los analistas escribió, es que algunas organizaciones de Roma en Bulgaria se han anunciado planes de crear una guardia de su propio como una fuerza de resistencia.
Desde la guardia húngaro ha actuado hasta ahora bastante similar a la Guardia Nacional búlgara, es muy posible que la Comunidad de Roma de Hungría podría responder a la amenaza por organizar su propia defensa propia, escribió el capital político en la advertencia de riesgo.
Gerente de investigación de capital político Atila respondió a una pregunta de la agencia de noticias húngara diciendo que el análisis del riesgo fue una de las actividades principales del Instituto de Investigación.
Cada año, decía, publican análisis de riesgo, y si se descubren cualquier factor que podría cambiar los riesgos, notifican a la opinión pública por publicar un aviso de riesgo, como han hecho ahora.
