El grupo catalán ha facilitado miles de pasaportes a Al Qaeda 
Además de los siete detenidos en Barcelona, en Tailandia hubo tres 
Los siete pakistaníes y un nigeriano detenido por agentes de la policía de Barcelona general de inteligencia forman un grupo yihadista que, dirigida por Tailandia, facilitado los pasaportes a diferentes grupos de Al Qaeda, entre ellos "los Tigres para la liberación de territorio tamilm" (LTTE) y "Laskar y Taiba" (Let), autor de este último uno de los ataques de Bombay que causó la muerte de 106 personas en 2008. 
El Ministerio del Interior ha prestado atención a estas investigaciones, hasta el punto de asegurar que con la "operación kampai", ha sido "debilitar" del aparato de falsificación de Al Qaeda en el plano internacional y, por tanto, su capacidad operativa ". 
Los investigadores calculan que la celda, durante los dos años que ha actuado en Cataluña, ha sido capaz de enviar miles de pasaportes a Tailandia, donde fueron falsificadas y pronto distribuida a los grupos criminales que integrar la galaxia Al Qaida para que su "combatientes" pueden cruzar las fronteras europeas y las de otros países occidentales con total impunidad. 
La célula desmantelada no es el único que la red yihadista celebrado en Europa, por este motivo en las investigaciones no han participado, además de los servicios de Tailandia, otras unidades de policía europea, razón por la que no se descarte que en territorio de la UE ocurren acontecimientos similares a la que se desarrolló la noche del martes en Barcelona. 
En coordinación con esta operación (el junaid paquistaní, Humayun atiqur, Rehman Malik, Asghar Jabran, Mohammad Iftikhar Ahmad Khan SADDIQUE Begum, Tanveer Arshad y el nigeriano agunbiade Babatunde se detuvo), en Tailandia, otro había desarrollado con la captura de los pakistaníes Muhammad Athar blanco y Ehsan zeeshan blanco y el tailandés kijbumrung sirikanlaya. 
El Grupo sentado en España y otros países europeos fue dirigido por bangcock 
La red catalana, parte de ella fue sorprendido en 2009, principalmente robado los pasaportes de los turistas que cumplan los requisitos marcados por el llamado "frente islámico mundial". 
Es decir, los documentos tuvo que ser en nombre de los hombres de entre 25 y 45 años, con validez de varios años y sin visados impresos. 
En los medios de investigación es subrayar que, por el momento, no se ha encontrado datos relacionados con los detenidos en Cataluña en relación con el atentado de Bombay, aunque al autor de este ataque, "Laskar e Taiba", ha sido uno de los grupos que reciben el robo de pasaportes falsificados en España y pronto en Tailandia. 
Sin embargo, cabe mencionar que días antes de este cometido ataque, desde Cataluña había enviado a través de una agencia de transferences sobre algunos miles de dólares que se han "invertido" en la compra de tarjetas de telefonía móvil, que antes eran utilizadas por los miembros del " comando " que acabó con la vida de 106 personas. 
Los policías han capturado un montón de documentación. 
