Candidaturas: fue cantante de jazz, Esperanza Spalding es una sorpresa recoger en la categoría de mejor nueva artista 
Lleva a cabo a petición de un presidente, y la gente está obligado a tomar nota. 
Esperanza Spalding, la cantante y bassist de jazz al menos, designado por el presidente Obama a cumplir en la ceremonia del premio Nobel de la paz en 2009, marcó uno de los grammys "sorpresas este año con una nominación en la categoría de mejor nueva artista. 
Teniendo en cuenta que Spalding ha sido un célebre figura de la escena del jazz desde su álbum de 2008, "Esperanza", la nominación es un poco head-scratcher, pero es coherente con el Grammys "reglas de un artista no liberar a más de tres álbumes antes de la grabación que" establece la identidad pública de este artista ". 
Su ambicioso 2010, "Álbum de Música de Cámara de la sociedad", sin duda marcado un paso adelante, y habida cuenta de su airily invitar abiertamente y una mano hábil estilo pop, funk y el latin influencias, es posible sacar al menos una confirmación por escrito, Norah Jones Spalding de "gran éxito en 2003, el más cercano fue equivalente a los electores de cara hacia el vecindario de jazz en esta categoría en los últimos años. 
Los votantes de otros países cumplieron con razón fue la "del trío Iyer Vijay historicity en la categoría" Álbum Instrumental, un thrill-ride la estimulación de un registro que fue una crítica de los favoritos del año pasado. 
Entre esos Iyer competirá en contra de incluir veterano saxophonist James Moody 's y Moody 4B "keyboardist" positootly "de John Beasley". 
Trombone Shorty, un raucous de Nueva Orleans y favorito de la HBO invitado frecuente "Treme", se apresura a la categoría de jazz contemporáneo, que de lo contrario se inclina en gran medida hacia la fusión con NODS hacia álbumes, John McLaughlin por Stanley Clarke y Jeff Lorber. 
El salvaje, Darcy steampunk-informed James sostienen la sociedad secreta ganado un merecido reconocimiento en la categoría de conjunto grande, compitiendo contra los ricos del conjunto Childs Billy chamber-jazz y a los ever-adventurous octet Dave Holland, cuyo álbum Live "vías" fue un buen ejemplo de la bassist democrática del lado como un bandleader. 
