Romano va hacia su primer título 
Rubén Omar Romano cuenta con tres derrotas en la final, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey en la final, además de dos estilos diferentes caracterizado por sus técnicos ", que se enfrentan a reencontrarse con una diferencia marcada por los resultados. 
Rubén Omar Romano cuenta con tres derrotas en la final, que durante su carrera altibajos, pero sabía cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora no había alcanzado el objetivo, y esta es la razón por la que esta oportunidad es muy especial para él. 
El argentino ha acabado con la medalla de consuelo segundo clasificado, y se mantuvo un paso atrás los ganadores y particularmente con el mismo equipo que ha jugado las finales consecutivas. 
Santos llegó a su primera última como entrenador en el primer partido de 2002, cuando tomó las riendas de Morelia con la que se le cayó por 4-2 ante Toluca; más tarde, en el acto de clausura de 2003 también llegaron al duelo decisivo y perdió también en 3-1 y de hecho antes de Rayados. 
Ya con Santos Laguna, en el bicentenario partido de 2010, una vez más antes de los diablos, Rubén sufre de nuevo un revés, puesto que su equipo acabó igual de lugares 2-2 ante las autoridades embutidos después de 210 minutos de juego, pero en el giro de sanciones colocado en ventaja de 3-1 con dos oportunidades para sellar el título, pero finalmente tres jugadores desde los 11 pasos falló y sufrió el 4-3 cambio. 
Rubén perdido ya dos diablos rojos con las finales y uno con Monterrey, su rival en turno, por lo que no queremos sufrir la misma suerte, quiere celebrar un título por primera vez, y afirma que lo más importante para él es la institución. 
Quiero ser un campeón, no quiero romper cualquier dato, esto es por un club, por una pasión y por consiguiente el título llegará a mí, pero la última cosa es más importante, comentó el timonel al ser cuestionado sobre las cifras que ha de jugar contra las finales. 
Muy eficaz tiene el final de la anterior, de la que, asegura, ha aprendido mucho, "la única lección que podemos aprender es que hasta el árbitro señala el fin no podemos celebrar, prepararnos así como los actores porque la anterior ocasión, con dos penas que estaban a punto de abandonar y creo que es una lección que aprender, no podemos celebrar hasta que termine el juego". 
A sabiendas de que esta serie podría definirse de pena, algo en lo que no, porque confía en sus jugadores: " uno nunca espera para ir a sanciones, sino para terminar en tiempo regular; a veces no tienen ninguna alternativa y es necesario estar preparados; en el partido anterior estábamos preparados, lamentablemente destino desempeñado en nuestras manos; a veces, por los nervios o ansiedad por tener el título en un mano, pero nosotros no alcanzar este objetivo, y esto nos queda algo por este último que esperamos ganar ". 
Roman debe dejar de ser un tercer técnico y saboreando por primera vez la gloria que los títulos dan. 
