Los resultados del Congreso IP solicitudes 
Eduardo Dávalos, Presidente de la CEC, propuso que los diputados asumir la gran responsabilidad de ser un ejemplo para un mejor Sinaloa por los diversos desafíos que enfrenta. 
Una legislatura de obras decente y libre de acuerdos entre los partidos y el Ejecutivo Estado está siendo solicitadas por el sector empresarial de Mazatlán, porque hay una convulsión que Sinaloa tiene grandes problemas. 
Ayer se votó en el 60 legislatura, integrada por siete fuerzas políticas, 19 diputados del PRI, 13 del pan, tres del partido Nueva Alianza, dos del PRD, uno del PT, uno del partido y uno más del PVEM, es decir, un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso de la s-state se menciona que vienen a cumplir una gestión limpia de compromiso con la sociedad y los distintos sectores que requieren una labor legislativa responsable. 
Eduardo Dávalos Zamora, presidente del Consejo Coordinador Empresarial, propuso que la justa liberado 40 diputados del Congreso del Estado asumido la gran responsabilidad de ser un ejemplo para un mejor Sinaloa por los diversos desafíos que enfrenta. 
Esperamos que los diputados realmente va a ejercer su derecho, libre de acuerdos entre las partes porque es una costumbre de hacer acuerdos para cuidar de sus propios intereses y convertirse en un personaje en un carnaval de los gobernadores y dirigentes de las fracciones parlamentarias. 
Por esa razón se refirió a certificar el compromiso para establecer los necesarios puentes que podría ayudar al Gobernador para seguir adelante. 
Esperamos que vienen a hacer un trabajo digno y principalmente comprometido con la sociedad y los sectores porque los habitantes de Sinaloa fueron los que les dio el voto de confianza durante las últimas elecciones. 
José Ramón Manguart Sánchez, presidente de la Asociación de Hoteles Tres Islas, considera que uno de los mayores retos para los 40 representantes populares es el de promover y sumar fuerzas en la búsqueda del crecimiento económico del Estado, porque hoy en día la situación económica es muy complicado. 
Lo más importante es impulsar el crecimiento económico, que genera incentivos para la inversión y la infraestructura y que, de alguna manera, formarán una nueva generación de empleos. 
En cuanto a la actividad turística, exigió que los nuevos legisladores dar el peso revisado en el presupuesto del Estado para fortificar el secretario de Turismo. 
Como he entendido este es el segundo departamento del Estado con menos presupuestos y es incongruente una importante actividad económica y la generación de divisas y la inversión y que compite directamente con el sector agrario. 
Aparte de exigir el etiquetado recursos de los proyectos turísticos detonante que contribuyan a dar seguridad al Estado y actualizar la ley del alcohol que no ha sido capaz de resolver en las legislaturas anteriores. 
