El asfalto de UNAM evitaría agujeros
Rafael Herrera, investigador en la facultad de química de UNAM, desarrolla el asfalto polímero-modificado para producir una mezcla con el mejor funcionamiento, sin importar las condiciones ambientales y la temperatura
Si las señales enviadas por la superficie de la carretera fueran asistidas, sería necesario reparar cerca de 200 mil agujeros cada estación de lluvias en la zona metropolitana del valle de México, dijo Rafael Herrera Najera, investigador en la facultad de la química (CF) del UNAM, que dijo que si el proceso de la construcción y del mantenimiento de un pavimento del asfalto es adecuado, los agujeros podría ser reducido o aún ser eliminado totalmente.
En su opinión tecnológica de la conferencia A del agujero, publicada bajo año internacional de química, anunció que el laboratorio que él es responsable de está desarrollando un asfalto modificado polímero para producir una mezcla con las características similares al asfalto, pero con una mejor fuerza mecánica, ambos en las temperaturas del cielo y tierra.
Herrera Nájera dijo que este tipo de asfalto modificado se podría utilizar en lugares donde está extremadamente caliente el tiempo, como algunas ciudades en el norte, mejorar su funcionamiento y, por lo tanto, la formación de agujeros.
Él explicó que el asfalto, la pieza de un aceite cuanto más pesada es un sistema de las moléculas del hidrocarburo, algunas de peso de molecularidad elevada, llamado los asphaltenes, y otro de poco peso molecular, llamado los maltenes, que junto dan a superficie de la carretera su comportamiento característico viscoelástico.
El comportamiento viscoelástico del asfalto consiste en el hecho que en las temperaturas altas cerca de 180 grados, se comporta como un líquido en 120° C, su viscosidad es muy alto y en 50 grados Celsius tiene un casi de estado sólido, mientras que en las temperaturas muy bajas el asfalto llega a ser frágil, que él dijo.
Esto significa que la resistencia del asfalto de la calle no es uniforme, pero se modifica durante el día según las condiciones ambientales y la temperatura, dijo al especialista en la ingeniería química.
El investigador de los CF observó que las calles de Ciudad de México son cubiertas sobre todo por el revestimiento flexible, que se compone de seis capas de material, fuera de quien los tres pasados implica el asfalto.
Entre las capas más superficiales es el asfalto, integrado por las pequeñas piedras sumergidas en el asfalto y después condensadas.
Cada uno de las piedras que componen este recubrimiento, él dijo, se sumerge con asfalto.
Al conducir los vehículos y generando esfuerzo, permite que las fuerzas se separen muy bien en el pavimento.
Si fuera asfalto modificado que separaría incluso mejor, dijo al ingeniero químico.
En la cubierta del asfalto, él añadió, se coloca una capa final llamada la cubierta rodante, que se hace de un material de piedra fino, significando la arena también sumergida en el asfalto.
Puesto que ésta es la capa que estará en contacto con las ruedas del vehículo, debe tener una mejor fuerza mecánica que la cubierta del asfalto y proporcionar la fricción del camino.
Como siendo la parte del pavimento que recibirá y difunde los esfuerzos, el balanceo que cubre también requiere grueso apropiado y el material que se hace de debe ser toma en la consideración.
Las variaciones del tiempo, especialmente de la humedad y de la temperatura son también un factor muy importante a considerar, regar especialmente, él dijo, porque afecta grandemente al funcionamiento del asfalto.
Cuando la tierra es mojada, el agua difunde dentro de la cubierta y es duro salir, éste que causa un ablandamiento de todas las capas del pavimento y, por lo tanto, de la formación de agujeros.
En la formación de un agujero, él dijo, el primer a llevar es la cubierta del balanceo y sólo después de ése se afecta el asfalto, pero el daño no sucede inmediatamente, él es un proceso que se debe asistir en las primeras muestras con programas de mantenimiento apropiados.
También un miembro del sistema nacional de investigadores explicó que la carga del vehículo es otro factor importante en la formación de agujeros y, por lo tanto, el grueso de cada capa del pavimento debe ser hecho en relación con la carga del vehículo y asegurar siempre este cumplimiento, para prevenir la formación frecuente de agujeros.
Rafael Herrera dijo que todavía hay mucho a investigar y trabajo a hacer en el asfalto, por ejemplo, las emulsiones de asfalto, que en otros países están ya en el mercado e incluso ayudan a agujeros de la reparación con sencillez y sin usar temperaturas altas.
