Analizan la posibilidad “voto por de una cuenta del voto” en Michoacán
Según los datos transmitidos por el PERP la diferencia entre el primer y segundo lugar en la elección gubernativa está del solamente 27 por ciento, incluso sin la cuenta de los votos correspondiente a 879 del total de 6,074 minutos.
La posibilidad de contar “voto por voto” es una realidad por lo que se refiere al proceso electoral de este año en Michoacán, en donde según los datos obtenidos de los resultados electorales preliminares programe (PERP) la diferencia entre la primera y el segundo lugar de la elección del gobernador está del solamente 27 por ciento, incluso sin la cuenta de los votos que corresponden a 879 de los 6,074 minutos totales.
A este respecto, el presidente del general consejo del instituto electoral de Michoacán (MEI), Maria de Los Ángeles Llanderal Zaragoza, recordado que hace algunos días, el pasado 9 de noviembre, el cuerpo electoral aprobó un sistema de pautas para armonizar las regulaciones locales con la reforma federal electoral.
Pues será recordado, Michoacán no autorizó la constitución o el código electoral del estado o del acto electoral de la justicia, puesto que el congreso del estado aprobó las reformas poco antes el plazo legal para que entren en la fuerza en este proceso electoral y el gobernador Leonel Godoy Rangel omitió su publicación dentro de los períodos especificados en la ley en la gaceta de autoridad estatal, sosteniendo que él tenía algunas objeciones.
El mismo 9 de noviembre, el Tribunal de Justicia supremo (SCJ) resolvió la controversia constitucional promovida por la legislatura local y la describió como “inválido e ilegal” el voto del representante del estado para las reformas constitucionales, puesto que él tiene no a la derecha “sancionarlas o votar.”
Entrevistado con sobre la posibilidad del “voto por voto,” Maria de Los Ángeles Llanderal indicó que con la adopción de las pautas apropiadas del general consejo del MEI será posible realizar las cuentas parciales y totales del voto por el cuerpo electoral local.
Así, el recuento parcial de una o más cajas electorales puede ocurrir en las suposiciones eso: los resultados de los expedientes no hacen juego\; no hay expediente de la cuenta en el expediente de la caja o no se incluyen en el poder del presidente\; o cuando hay claros errores o alteraciones de los minutos.
Además, la cuenta total del voto recibido en todas las cajas de la elección puede ocurrir cuando hay una indicación a la cual la diferencia entre el ganador alegado del candidato de la elección en la pregunta y la persona que ha obtenido el segundo lugar en la votación, es igual o menos de un punto de porcentaje, mientras al principio de la sesión haya una petición del representante del partido y/o de la coalición que nombraron el segundo de los candidatos mencionados.
La cuenta total del voto también será hecha si en el final del cálculo ordinario se establece al cual la diferencia entre el ganador y el candidato colocados en la segunda posición es igual o menos de un punto de porcentaje, mientras haya una petición del representante del partido político cuyo candidato vino en la segunda posición, el caso en la cual allí será excluido las cajas electorales que se han considerado durante el recuento parcial.
Allí debe ser observado que en esta situación es la elección de Morelia, donde según PERP está la diferencia entre la primera y el segundo lugar del apenas 0,16 por ciento, incluso sin la cuenta de los votos de 129 de los 923 minutos totales.
