La adversidad climática retrasó la economía
Durante el primer año de gestión de Mario López Valdez, en Sinaloa aumentó el desempleo y la informalidad, la inversión extranjera disminuyó y la economía fue reducida.
2011 es un año que será recordado en la historia económica de Sinaloa, siendo relacionado con el primer año de gobierno de Mario López Valdez también llamado el año de cambio, que generó granes expectaciones por lo que se refiere al desarrollo de la economía, pero dado la adversidad climática del principio del año, había crecimiento nulo, no obstante se registró una disminución en los indicadores principales del desarrollo económico.
Las temperaturas bajas de febrero, no sólo hicieron ellas causan pérdidas de millones para el sector agrícola, pero limitaron las posibilidades de la economía del estado para crecer, causando una contracción de la actividad económica en el general del 3,6 por ciento en el primer semestre del año, apoyado principalmente por la caída histórica del 31,16 por ciento en la agricultura, que afectó a la dinámica de otros sectores económicos.
Según el informe con respecto a las áreas afectadas por la helada, publicada por el consejo mexicano para el desarrollo rural sostenible se dañó 835,582 hectáreas, fuera de las cuales el 78,03 por ciento sufrió daño total y el sigue habiendo del 21,07 por ciento tenía daño parcial. Las cosechas dañadas tubería eran las verduras, el maíz y el garbanzo.
La caída en la actividad económica ha generado, hasta noviembre, un aumento constante del desempleo en el estado, según el instituto nacional de estadísticas y de la geografía, la tarifa del estado del desempleo durante el primer tres cuartos del año registró un crecimiento acelerado, de enero a marzo 55,053 habitantes de Sinaloa estaban parados, con un índice del 4,53 por ciento de la población económicamente activa para el segundo trimestre, la tarifa se convirtió en el 5,28 por ciento, y entre julio y septiembre la media continuó aumentando al 6,19 por ciento, una tarifa que en términos de número de gente representa más de 74,000 de los habitantes de Sinaloa de los parados, un aumento comparado a la primera mitad de 18,969 individuos.
Baje la liquidez
El desempleo en Sinaloa durante el año es multifactorial, para el economista Gerardo López Cervantes, director en la facultad de economía y las ciencias sociales del UAS, el crecimiento del desempleo se pueden explicar indirectamente, dependiendo de las acciones que se ha tomado el orden público.
“Qué ahora estamos viendo somos un aumento del desempleo que tiene que hacer con varios factores, incluyendo la pérdida de liquidez en el mercado con el fin una restricción del recurso impuesta por la legislación que pasó en el congreso para combatir blanqueo de dinero puesto que para la gente que posee ilegal dólares no está el trabajo fácil con, no los invierte y no utiliza en algo” él dijera.
Inmigración parada
López Cervantes dijo que eso en el aumento del desempleo allí es también un factor demográfico.
“El número de gente que deja el estado en busca de un trabajo al extranjero, en los Estados Unidos se ha restringido, en primer lugar debido a las dificultades entrar, y de todos porque una vez que entran tienen ya demasiadas dificultades en encontrar un trabajo, que el grupo de personas es que permanece y exigente trabajos aquí, en el estado, haciendo el índice de desempleo subir, “él dijo en segundo lugar.
Informalidad
El análisis del mercado laboral de Sinaloa consigue peor cuando en vista de alto nivel de la informalidad que prevalece entre las condiciones de trabajo, según INEGI, el 60,38 por ciento de la población activa en el estado trabaja sin ser citado como trabajadores a cualquier institución de Seguridad Social.
Además del desempleo y de la informalidad, otro recordatorio del trabajo del estado es representado por los salarios bajos\; la entidad tiene los salarios más bajos en el país, según los expedientes del instituto mexicano de la Seguridad Social y del ministerio del trabajo y de la asistencia social.
Los ingresos medios mensuales de los trabajadores de Sinaloa eran, hasta septiembre, 5,352 Pesos, bien debajo de la media nacional, que está de 7,375 Pesos.
Contracción de FDI
Además de la caída en indice de la actividad económica y de paro elevado, en 2011 se registró la disminución más grande de la inversión directa extranjera durante los últimos 10 años, según el Ministerio de Finanzas de enero a junio que el estado FDI sumó 630,697 dólares, que representa una caída del 87,74 por ciento comparado a los 5.143.312 dólares durante el mismo período del año pasado.
Para su parte, el ministerio del desarrollo económico del gobierno estatal consideró una inversión total de 17.280.000 Pesos durante el año, que ocurrió principalmente en compañías del sector terciario.
Deuda
Contra el contexto del descenso económico, el gobierno estatal preguntado en julio durante el congreso del estado, la aprobación de un crédito de 3 mil millones Pesos, que estarían para la inversión en proyectos de la infraestructura en los 18 municipios, para reactivar la economía, la autorización del congreso local estaba para un total de 2,600 millones de Pesos, y hasta noviembre no se observó ningunas ventajas de la deuda en ningún sector de la economía del estado.
Reacciones
Para los representantes del negocio, el primer año de gobierno de Mario López Valdes demuestra una falta de capacidad del gobierno.
Miguel Loredo López, presidente de la cámara nacional de industria de la transformación, dijo que ése durante 2011 allí era una falta de armonización de las voluntades de diversos sectores, incluyendo el gobierno estatal sí mismo.
“El funcionamiento de la economía en Sinaloa este año ha sido realmente pobre, uno tiene que trabajar difícilmente para recuperar la tierra perdida este año, en 2012 debemos redoblar nuestros esfuerzos, no pudimos alinear los esfuerzos de todos y sobre todo el movimiento bueno y sincronizado del nuevo equipo del gobierno, esperamos que el próximo año será” él dijo mucho mejor.
Lentitud económica
López Loredo dijo que los acontecimientos tales como helada temprana este año pararon la economía del estado y su funcionamiento y crecimiento era restricto.
“El flujo económico bajo es el producto de varios acontecimientos, incluyendo helada, uno de los efectos principales ha sido una economía lenta que no da vuelta rápidamente bastante para generar un dinamismo económico que permita el tener de un nivel aceptable del flujo de los procesos, de los productos y de los servicios y por lo tanto, al final del año somos cerrados él debajo de nuestras expectativas,” él dijo.
Redefinición de la vocación
Teodoro Salazar Uriarte, presidente confederación de los patrones” de la república mexicana en Sinaloa, dijo que el estado está requerido procesar las actividades productivas más dinámicas.
“Total, encontramos que ha estado trabajando encendido, nosotros creemos que es necesario desarrollar un programa a largo plazo que redefina la vocación y el curso económico del estado, él es importante detonar todo el material y el recurso potencial humano que Sinaloa tiene,” él dijo.
Trabajo a hacer
El presidente de Coparmex subrayó la importancia de establecer una visión futura para dirigir mejor los esfuerzos del gobierno.
“Total diría que el gobierno se ha estado esforzando ser acertado en diversos campos, en términos de desarrollo económico allí soy un cierto progreso pero es importante desarrollar un programa a largo plazo,” él dijo.
Él observó que la administración actual ha mostrado progreso en su propia manera de llevar el orden público.
“Hay los elementos que nos permiten que dicen que el gobierno esté haciendo más inclusivo, y qué puedo decir soy que hay trabajo hecho y pienso que el gobierno es consciente que hay trabajo a hacer,” él dijo.
