Allí se debe hacer las contribuciones a los trabajos
Los trabajos sociales mencionados en los programas tales como hábitat, rescate de espacios públicos y 3x1 para los nómadas arriesgan para no ser terminados o tener retrasos serios debido a la falta de fondos, dijo el ángel López Miranda de Miguel.
El director del desarrollo social municipal indicó que aunque los programas de trabajo hayan avanzado hasta ahora son en peligro porque el gobierno estatal no pudo hacer las contribuciones que corresponden, que representan a un superior del recurso a 11 millones de Pesos en los tres programas.
Él observó que la inversión total en estos tres programas está de casi 50 millones de Pesos, cuyo el estado tiene que contribuir con el 25 por ciento y hasta ahora solamente la federación y el municipio han proporcionado los recursos para los trabajos, así que el retraso posible en la realización de éstos está en vigor.
“Tienen que contribuir con casi 12 millones y aunque el año es terminando ellos no nos ha dado una moneda de diez centavos, desde comenzar con julio tuvieron que darnos una pieza,” él dijo, “para no retrasar nos hemos comenzado los trabajos y son muy avanzados, pero necesitamos el dinero.”
Él mencionó que el año pasado, durante la administración de Jesús Aguilar Padilla, el estado no cumplió con las contribuciones que tuvo que hacer, de modo que al principio de la administración el municipio tuviera que pedir prestado el dinero para cubrir más de 7 millones, una suma que no fue proporcionada en esa ocasión por la administración del Estado.
“Nos sucedió en la administración anterior porque el estado no tenía la capacidad financiera de participar y los programas continuaron avanzando, y este año para tener acceso a estos programas que tuvimos que conseguir los recursos para cubrirlo qué el estado salió pendientes,” explicó.
Aunque haya un compromiso de las autoridades estatales a cumplir con la entrega de estos recursos, él dijo que la petición fue hecha a la secretaria de la administración y de las finanzas, Armando Villarreal, para acelerar los esfuerzos de modo que los porcentajes que corresponden a ellos para venir lo más rápidamente posible.
“Tienen que contribuir con casi 12 millones y aunque el año está terminando ellos no nos han dado una moneda de diez centavos.”
