La corte valida la “transición de la televisión digital” en México en 2015
El reemplazo del análogo con digital es uno de los cambios más importantes que ha golpeado el mundo estos últimos años
El Tribunal de Justicia supremo (SCJ) rechazó las controversias constitucionales traídas por el Senado de representantes contra el decreto presidencial que presenta la supuesta “transición de la televisión digital” a partir de 2021 a 2015, puesto que los ocho votos necesarios para invalidarla no fueron obtenidos.
Una minoría de cuatro ministros, incluyendo el presidente de la corte, Silva Meza de Juan, consideraba que presidente Felipe Calderon no excedió su autoridad publicando un decreto que detallaba las acciones para admitir orden para alcanzar la transición a la televisión terrestre digital.
Con este resultado, la controversia constitucional promovida por el senado, fue rechazada para no resolver el por mayoría cualificada de ocho votos para que la corte pronuncie en la constitucionalidad o el unconstitutionality del decreto, y ésta permanece en vigor.
El proyecto de la frase preparado por el ministro Olga Sánchez Cordero, propuesto para declarar inconstitucional el decreto, porque la regulación de los materiales de la radio y de la televisión es un poder reservado por la ley a la Comisión federal de las telecomunicaciones (Cofetel), con violación de los principios de subordinación y de reserva jerárquicas de la ley.
Solamente Zaldivar, Jorge Mario Pardo, Margarita Luna y Sánchez Cordero votaron por el proyecto.
Con esta discusión, el senado y la cámara de diputados promovieron dos controversias constitucionales para contradecir el decreto, y para apoyar las demandas, el ministro Sánchez Cordero suspendió el uso del decreto y todas las acciones estipularon allí con respecto a la transición digital.
En los ministros” que se encontraban allí también era decidido rechazar la demanda archivada por la cámara de diputados, sin entrar en la discusión del proyecto, también responsable del ministro Sánchez Cordero.
En su discurso, el ministro dijo que él no estuvo de acuerdo con las discusiones del proyecto en el sentido que el ejecutivo federal no puede estructurar con reglas generales las medidas para que la administración pública consiga preparado.
“Ni considero que si estuvo hecho afectaría a la autonomía del cuerpo regulador,” y recordé que el planeamiento de órdenes públicos en áreas estratégicas tales como el sector de telecomunicaciones corresponde al ejecutivo federal, que tiene un mandato constitucional, la dirección del estado.
El reemplazo de analógico a digital es uno de los cambios más importantes que han golpeado el mundo estos últimos años, y de los resultados en una mejor utilización del espectro radioelectricidad, de la mejor calidad de señal y de más canales.
El retraso del cambio, él dijo, significaría el retraso de las ventajas de la numeración, que implica una decisión del interés público, que tiene no sólo una dimensión técnica, “como cubre problemas de seguridad económicos, sociales, políticos y nacionales.”
Estos problemas, él dijo, “requieren la operación del sistema entero establecido bajo principio de la administración económica del estado, comprenden a un grupo de los poderes que la constitución lleva al poder ejecutivo de estado.”
Él recordó que un gran número de países en todo el mundo ahora han terminado la transición digital, y lo ha hecho a través del ejecutivo, desafío del tener cuerpos técnicos sumamente especializados.
Allí no puede ser concluido que el gobierno, publicando el decreto disputado, que invade de cualquier manera la capacidad del congreso, está proporcionando en el dominio administrativo que la observación de las leyes publicó por la legislatura, él dijo.
