Abra la Oficina, aqu� est� la tercera edici�n del paquete "de antiMicrosoft". 
Hoy ve la liberaci�n de Openoffice.org 3.0, la suite de productividad personal de la fuente abierta que apunta a la ganancia de m�s usuarios, de dom�stico a usuarios de casa, de profesionales a la administraci�n p�blica, como una alternativa libre para la Oficina de Microsoft mejor conocida. 
Despu�s de un esfuerzo que dura durante casi un a�o de parte de reveladores de voluntario, con la supervisi�n de Microsistema de SOL en sus espaldas, la nueva Oficina Abierta es revelada al gran p�blico con varias novedades: a la pantalla bienvenida y a un visitado de nuevo, menos interfaz de usuario Espartano, son a�adidos otros m�s sustanciales como la compatibilidad natal con la Manzana Mac OS X sistema operativo y apoyo al nuevo formato ODF (Formato de Documento Abierto) 1.2, el �ltimo est�ndar de versi�n de ISO. 
La atenci�n tambi�n fue colocada en la interoperabilidad con la suite de 2007 de Oficina, la Oficina Abierta es capaz de documentos que se abren con la nueva extensi�n de Microsoft (.docx, .xlsx, .pptx). 
Interesante son algunas funciones espec�ficas a algunos m�dulos como el que que tiene la reducci�n en cuenta del tama�o de presentaciones PowerPoint, �tiles por ejemplo para enviarles v�a el correo electr�nico, o la posibilidad de importar un archivo PDF en el m�dulo de gr�ficos, manteniendo el aspecto original de la p�gina. 
Siempre en la misma pista, es posible crear "PDF h�brido" documentos, que se afilian a la gr�fica est�ndar del formato de Adobe con los elementos de una hoja de c�lculo o un procesador de textos. 
La colaboraci�n es uno de los rasgos dentro de las aplicaciones que ha sido bastante mejorado: en la aplicaci�n de hoja de c�lculo varios usuarios pueden funcionar simult�neamente, evitando conflictos en las modificaciones, en el procesador de textos, cada uno los usuarios son adjudicados un color que comenta para mejorar el reconocimiento durante la revisi�n. 
Algunas compa��as tambi�n trabajan en virar a babor algunas funcionalidades de OpenOffice en la Web (en la nube), y durante las pr�ximas pocas semanas ellos deber�an liberar el producto definitivo. 
La versi�n italiana est� disponible para la telecarga en la direcci�n http: // it.openoffice.org/download/3.0.0/download300.html y es a�adida a la versi�n inglesa que ha estado disponible en sitios de espejo desde el viernes. 
Adem�s para el Windows y Mac OS, como de costumbre la suite est� tambi�n disponible para el sistema operativo Linux. 
Por la petici�n la instalaci�n cd puede ser enviada a su casa o lugar de trabajo. 
Y si el reclamo de los libres podr�a ser una fuerza impulsora para la difusi�n en casas, esto est� en el negocio que pone lo que Se abre la Oficina intenta la apuesta grande ya que esto puede contar ya con varios proyectos realizados dentro de la administraci�n p�blica y escuelas. 
Y hay hasta las instituciones que ofrecen servicios de formaci�n, consulta, y ayuda, ideal peque�o a empresas medias, que podr�an crear m�s oportunidades comerciales. 
La Oficina Abierta es formada de cinco m�dulos principales: Escritor, para onscreen que escribe a m�quina correspondiente a Palabra; Calc, la aplicaci�n de hoja de c�lculo que apunta a substituci�n de Excel; Impresione, para presentaciones en la emulaci�n de Powerpoint; el Dbase, como en caso del Acceso m�s famoso es la aplicaci�n que consiente el funcionamiento en bases de datos; Empate, es el m�dulo gr�fico. 
El objetivo para 2008 es conseguir 5 millones de telecargas, y considerando que hasta hoy estamos en casi 3 millones 600 mil, con la liberaci�n de la nueva versi�n es probable que la figura predicha pudiera ser hasta excedida. 
