�Lazos entre pol�tica y? el ndrangheta detuvo al alcalde de Gioia Tauro 
"El alcalde de Gioia Tauro fue dispuesto hacia intereses municipales correspondientes con aquellos de la cuadrilla de Piromalli". 
Las acusaciones que los magistrados de la Oficina de Antimafia Calabrese directa contra el alcalde y el diputado del alcalde de Gioia Tauro Giorgio Dal Torrione y Rosario Schiavone, y el alcalde de Rosarno Carlo Martelli, qui�nes han sido detenidos esta ma�ana por la competici�n externa con la asociaci�n de mafia, son muy serios. 
Tambi�n detenido es Gioacchino Piromalli, el mediador mayor entre el clan y las oficinas de administraci�n p�blicas, y su sobrino - un abogado, el tocayo del jefe, ya condenado para la asociaci�n de criminal de estilo de mafia, condenada para reembolsar 10 millones de euros. 
"En el desprecio de todas las reglas judiciales y morales, y sentido com�n", escriben los fiscales, las dos administraciones locales hab�an expresado la voluntad para pagar honorarios de consulta al abogado Piromalli. 
�"De esta manera, fue permitido para la cuadrilla? �los jueces escriben? penetrar oficialmente dentro de la municipalidad que alivia las posibilidades ya enormes de control y direcci�n de la administraci�n p�blica". 
El presidente del consejo local Calabrese Agazio Loiero no se esconde "colusiones entre instituciones locales y delito organizado es numeroso" dentro de su regi�n: "hay �reas donde la presencia de mafia es m�s fuerte y m�s intensa que en otros, donde la colusi�n es casi inevitable. 
Sin embargo, hay muchos pol�ticos locales que resisten a la presi�n puesta por el 'ndrangheta, h�roes que permanecen limpios". 
Las detenciones de esta ma�ana siguen aquellos en julio con los cuales la polic�a anunci� para haber degollado la cuadrilla de Piromalli. 
Al final de abril pasado, el consejo municipal de Gioia Tauro fue disuelto, pero ya en 1991, y siempre para el acondicionamiento supuesto entre delito organizado y administraci�n local, los pol�ticos locales hab�an sido aliviados de deberes de la administraci�n de la municipalidad. 
Giorgio Dal Torrione, el alcalde de UDC en el momento de la disoluci�n, hab�a sido decidido la cabeza de una coalici�n derecha de centro, despu�s de la votaci�n de mayo de 2006. 
�l hizo un esc�ndalo de ello cuando la Prefectura pidi� la disoluci�n del consejo municipal. 
�l hizo entrar la causa de entonces viceministro de los asuntos interiores Marco Minniti que lo acusa de haber trazado todo para motivos pol�ticos, sin embargo los jueces, en la orden de arresto firmada esta ma�ana, han explicado que la cuadrilla de Piromalli hab�a llegado hasta a la petici�n de la variaci�n del proyecto de A3. 
De las interceptaciones pedidas en Dal Torrione, escribe el procesamiento p�blico, ha surgido "una buena voluntad de casarse con las necesidades de un empresario, el representante de un grupo m�s grande notoriamente cerca del Piromalli, alineando las opciones de la administraci�n p�blica con los intereses de la cuadrilla". 
