Lukashenko-oposici�n: 110-0 
Ning�n representante de oposici�n fue decidido al parlamento bielorruso durante la elecci�n del domingo. 
Seg�n observadores rusos, los motivos de este son el bienestar y la estabilidad en el pa�s conducido por Alexander Lukashenko, mientras la Organizaci�n para Seguridad y Cooperaci�n en Europa (OSCE) lo explica como el voto contando fraudes. 
La OSCE que delega a 450 observadores de 43 pa�ses rechaza reconocer la elecci�n. 
Aunque la 100 legislaci�n de miembro del pa�s de 10 millones haya estado perdiendo la oposici�n durante m�s de una d�cada, antes de que la elecci�n ayer se uniera las fuerzas de la oposici�n bajo el nombre de Fuerzas Democr�ticas Unidas (UDF) hab�an esperado seriamente que Lukashenko, que renov� su presidencia por cuarta vez durante las elecciones pol�micas en 2006 despu�s de las enmiendas de la constituci�n, iba "a permitir" la presencia de algunos representantes de oposici�n en el parlamento esta vez. 
Basado en este, UDF desisti� del boicot antes considerado, tambi�n. 
El fondo de las expectativas de la oposici�n era que la Bielorrusia econ�micamente cada vez m�s dependiente de Rusia - que hab�a levantado un pr�stamo para reducir la importaci�n de gas rusa cada vez m�s cara y hab�a concordado a Beltransgas la posesi�n de gasoductos que cruzan el pa�s que se hace la propiedad rusa - dese� mejorar sus relaciones con la Uni�n Europea, donde el visado no es concedido para Lukashenko y para varios pol�ticos superiores debido al sistema pol�tico bielorruso, que es considerado antidemocr�tico. 
El hecho que la OSCE cuando habiendo evaluado la campa�a electoral mejor dicho se concentr� en cambios positivos en vez de carencias - como prohibir a un tercero de los candidatos de oposici�n participar en las elecciones - distensi�n indicada antes. 
Sin embargo, el OESC'S el lunes la hoja de minuto puso objeciones contra la campa�a durante cuales a candidatos de oposici�n no les permitieron pr�cticamente aparecer en los medios y sobre todo oposici�n no permitida estar presentes en contar de votos. 
Seg�n la oposici�n, la mejora es todav�a perceptible en el sistema pol�tico: los presos pol�ticos han sido descargados y Minsk es inclinado a encarar con Mosc� de un modo menor por todav�a no reconociendo Ossetia del sur y Abjasia que se han separado de Georgia, aunque Rusia - la formaci�n de un estado federal con Bielorrusia en el papel - haya estado considerando ya los dos territorios independientes durante un mes. 
"Hemos tomado dos medidas delante y un hacia atr�s, pero la cosa m�s importante consiste en que el di�logo entre Bielorrusia y la Uni�n Europea ha comenzado", cont� Alexander Milinkevich a nuestro papel. 
Seg�n el candidato de oposici�n de la elecci�n presidencial de 2006, este di�logo tiene que ser mantenido a pesar de que "el poder tiene con miedo del permiso hasta un miembro de oposici�n para entrar en el parlamento de ning�n peso". 
Viendo los resultados, la oposici�n no planea acciones que protestan, mejor dicho pretende alcanzar a votantes con su mensaje sobre la importancia de reformas econ�micas. 
"Tenemos mucho problema con este por supuesto, tenemos que imprimir peri�dicos de oposici�n en Rusia, la distribuci�n es dificultada por las autoridades locales, pero todav�a puedo ver que los cambios son favorecidos por cada vez m�s la gente, entre el viejo, tambi�n", dijo Milinkevich que se refiere al hecho que el r�gimen de Lukashenko, que considera el establecimiento de la seguridad social como su resultado m�s importante, es considerado inadecuado hasta por jubilados que son la clase oficialmente m�s apoyada de la sociedad de todos. 
"Debido al endeudamiento del pa�s y el aumento del d�ficit comercial, la aver�a de seguridad social 'similar al silencio m�s absoluto' es una pregunta de tiempo", reclam� Milinkevich. 
Los observadores rusos describieron las elecciones como democr�ticas, en la contradicci�n al pol�tico de oposici�n. 
La Comunidad Brit�nica de Naciones del l�der de misi�n de Estados Independiente Sergei Lebedev dijo la agencia de noticias rusa, Ria Novosti: "la gente cree en acciones no palabras", entonces la carencia de oposici�n no es nada m�s que pruebas de la madurez de los votantes bielorrusos. 
