Israel: caos laboratorio.
"No sale nada de violencia y nada lo frágil de podría" de picar, donde uno de los principales verses desde el estribillo es "no lo olvidemos lo frágil que son".
"Si mis hijos no quieren guerra, no sería nada", dijo el moribundo Gutle schnapper, esposa de mayer Amschel rothschild en 1849.
La última ola de violencia entre israel y la franja de gaza, como siempre, ha provocado una gran cantidad de reacción.
Algunos están por parte de israel, argumentando que tiene derecho a defenderse, y los palestinos se presentan como terroristas, mientras que otros apoyo a los palestinos, alegando el racismo del estado israelí, alegando que se está cometiendo genocidio contra árabes palestinos, y que israel es un estado terrorista.
No quiero insistir, en las sucesivas oleadas periódicas de la matanza, de quién es el infractores y quién es la víctima, después de todo, territorios autónomos habitantes de israel, incluido el de hoy, han nacido en la situación política actual, y no vive con el inicio de la violencia.
Quiero ofrecer a los lectores una peek detrás del escenario, un vistazo a los que, por encima de todo, este 95-year largo tensión está cumpliendo (a partir de la declaración de Balfour en noviembre de 1917) en esta pequeña porción de tierra en el oriente medio.
Algunos de mis pensamientos están apoyadas por los hechos históricos, mientras que otros son derivados de mi propio conocimiento de que grupo de personas, es decir, que es la principal fuente de los acontecimientos de la historia moderna.
La historia de la humanidad está en el primer lugar sobre la lucha por el poder.
En cada época podemos encontrar un alejandro el grande o un napoleón.
Lo que no está tan claro es si estas fueron las personas, que había elegido su camino independiente, o si detrás de su trono era alguien que dirige sus acciones hacia un objetivo pre-calculated.
Debemos aceptar que vivimos en un momento en el que la riqueza del mundo se concentra en manos de unos pocos individuos, y que la concentración de la riqueza y el poder que exuda no podría suceder en la vida de una generación.
Entre estas astronómicamente ricas familias, uno destaca, lo que podría considerarse la marionetas (si alguien más está por encima de ellas, no sé, pero yo no hubiera estado lo) - los rothschilds.
No está escrito mucho sobre ellos.
Comprensible.
La Primera agencia de noticias (reuters) que adquirieron en los 90 años del siglo xix, con el fin de evitar que su nombre se relacionados con actos de alta delincuencia, que apareció en su origen y que siempre significa garantizar el poder, aumentar la riqueza, o ambas cosas a la vez.
Ellos tienen mayoría participaciones en casi todos los bancos centrales en el mundo, y en contra de los países, donde no poseen un juego, están llevando a cabo o prepararse para la guerra (antes el ataque en afganistán fue 7 países, después de irak fue 5, después de la caída de Kaddafi 4 se mantuvo, pero mientras tanto rusia presentó su banco central para el gobierno ruso).
Quien ha intentado desafiar esta familia murieron.
Abraham lincoln se negó a renovar el estatuto del banco central para el banco rothschild de américa, y durante la guerra civil que comenzó a emitir su propio (que es state-issued) dinero y fue asesinado en 1865 en el teatro.
Jfk comenzó a emitir su propio dinero y quieren cerrar la fed (reserva federal), y que fue asesinado en 1963, el congresista luis McFadden fue envenenado en 1936, después de que él tenía la intención de demandar la reserva federal por causar la gran depresión de 1929.
Su sed de poder global llevó en los años de 1859 - 1871 a la formulación de un plan three-world-war por la freemason líder de los 33 grados, albert pike.
La Primera guerra era eliminar la gran monárquico organismos estatales en europa, el segundo fue para eliminar el régimen colonial, especialmente por parte de gran bretaña, y la tercera será reducir la población mundial hasta 0,5 - 1 000 millones de personas (el número de esclavos será suficiente para su comodidad y lujo, y no va a utilizar tantos recursos), la creación de una fe universal (ecumenismo es sólo un aperitivo de si esta solución), y por último la incautación de poder absoluto.
El método, que el grupo de familias adineradas con los rothschilds a la cabeza, emplean es el impulso de las crisis, seguido por la oferta de una solución (orden ab chao - orden del caos).
Sin embargo, estas soluciones son falsas, y siempre dar lugar a una situación peor (vide creación de la reserva federal, para que no se repita la crisis de 1907).
Así, después de haber logrado el asesinato de fernando, el heredero al trono austro-húngaro habsburgo, en sarajevo para desatar la Primera guerra mundial, que destruyó la rusia zarista con la revolución bolchevique.
La Primera guerra mundial terminó abruptamente, militar y económicamente débiles, con capitulación alemana (la guerra ya no era necesario para destruir la rusia zarista) y el central europea poderes de austria-hungría posteriormente fueron desmanteladas.
Para facilitar la creación de la segunda guerra mundial, han permitido que los banqueros y los políticos para crear una situación de conflicto latente por agobiando a alemania con gran guerra reparaciones, dando un ejemplo radicalist de las masas empobrecidas, se encontraba solo para introducir un suficientemente convincente culpable y un líder con una solución simple, aunque también crear un multirracial checoslovaquia con una fuerte minoría alemana que desempeñar, y de hecho hizo, el papel de una quinta colonia, después de la guerra había sido enecendió.
Al final del siglo xix, los rothschilds instigado la creación del movimiento sionista, una rama de la que luchó para formar el estado judío, buscar un espacio histórico de judea, jerusalén, para que su capital (el retorno de sión).
La mencionada declaración constituyó la base para la inmigración masiva de judíos a palestina Balfour donde los primeros conflictos comenzó con la población árabe local.
Los ataques terroristas se produjo en ambas partes.
Estalló la segunda guerra mundial, y si hitler se libre de la raya, que los banqueros internacionales estaban manteniendo con él, o si sus acciones eran parte del plan, es difícil de determinar, sin embargo el sufrimiento de los judíos en los campos de concentración creó la fundación europea para la aceptación del mundo del estado judío.
Israel se constituyó oficialmente en 1948, y así como la guerra reparaciones por la segunda guerra mundial fueron layed en alemania, el anuncio del estado de israel se convirtió en la tercera guerra del foco.
Siempre que los banqueros éxito internacional, la nación judía, como con el segundo, serán las víctimas en la Primera línea, ahora junto con el árabe o, más generalmente, musulmanes, con una población de oriente próximo.
Israel es como un gran laboratorio, una fuente de discordia y el caos no sólo en el país, pero a nivel internacional (basta con ver cómo firmemente personas están divididos en seguidores y opositores de israel).
¿quién es el wrong-doer y quién es la víctima en el conflicto de palestina-israel, donde injusticia engendra la injusticia en un ciclo interminable de violencia, mientras que todo partió de la codicia de unos pocos y su hambre de poder global?
En este punto, hay que diferenciar entre la población general de israel y sus dirigentes, porque, al igual que sucede aquí, los banqueros internacionales introducir su propia selección de candidatos a la gente a votar a favor.
El actual primer ministro de israel, netanyahu "el halcón", es un ejemplo típico de un político fascista, leal a los banqueros internacionales, que hace todo lo posible por promover una guerra con irán, que, debido a su condición de miembro de la organización de cooperación de shanghai (china, india, rusia, pakistán,...) a crear una mayor amenaza de conflicto global, y a través de su control sobre el estrecho de ormuz, donde el 20% de la petrolera del mundo debe seguir (el canal es sólo 2 kilómetros de ancho), a la destrucción de la economía mundial.
En vista de lo que están las palabras, pronunciadas por david rockefeller en 1994: "todo lo que necesitamos es una crisis importante y las naciones van a aceptar el nuevo orden mundial".
El nuevo orden mundial en sus ojos es uno de maestro y esclavos.
Un mundo en el que el resto de la población humana servir el lujo de un puñado de aristócratas financiera.
Un mundo, donde cada recién nacidos es implantado con un chip, lo que hace su existencia completamente subyugados.
"él también ha obligado a todos, grandes y pequeños, ricos y pobres, libre y esclavos, a recibir una marca en su mano derecha o por su forehead, por lo que nadie podía comprar o vender a menos que tenía la marca, que es el nombre de la bestia o el número de su nombre.
Si alguien tiene información, ¡que calcular el número de la bestia,
Para ello es el número del hombre. su número es seiscientos sesenta y seis ".
