El Gobierno español no plantearon objeciones en cuanto a los vuelos de la CIA 
El Gobierno español no plantearon objeciones en cuanto a los vuelos de la CIA con los prisioneros talibanes y de Al Qaeda que iban a Guantánamo a través de territorio español, según el el Embajador de Estados Unidos en el telegrama de Madrid. 
Así se refleja a través de los documentos filtrados (cables) por Wikileaks para el diario El País, donde se añade que el Vicepresidente primero del Gobierno en ese momento, María Teresa Fernández de la Vega, pidió que el Ejecutivo español informó en orden "para poder demostrar que llevaron a cabo procedimientos adecuados de vigilancia en el exterior aviones que cruzan España". 
En junio de 2006, después de un informe del Consejo Europeo cuando hubo acusaciones de complicidad en prácticas contra los derechos humanos en una docena de países, entre los que se encuentra España, celebró una reunión entre el ex embajador norteamericano Eduardo Aguirre y Fernández de la Vega. 
El Vicepresidente reconoció que el informe del Consejo "ha tomado el Gobierno de Zapatero fuera de juego" e insistió en que España no tenía nada que ocultar en relación con este asunto. 
"De la Vega destacó que España no plantea objeciones para los vuelos de inteligencia en territorio español". 
"Simplemente quieren informarse" para evitar que se tomó"por sorpresa", Aguirre se refiere en un telegrama. 
También el ex Ministro de Asuntos Exteriores, Miguel Angel Moratinos, indicó el Embajador que el Ejecutivo español "al querido dar a esta cuestión tan poca atención posible, aunque está en manos de los jueces, el Gobierno tuvo una influencia limitada". 
Por otra parte, en enero de 2007, el fiscal que Vicente González transmitida a la Embajada que no tratará de bloquear la iniciativa del juez de solicitar la desclasificación de documentos del Centro Nacional de inteligencia (CNI) y del Ministerio de defensa en cuanto a los vuelos de la empresa" 
Esta información no contiene ningún elemento incriminatory ni cualquier información confidencial",explicó la Embajada después de hablar con el fiscal. 
No obstante, los Estados Unidos se reflejaban en su preocupación por "la coordinación aparente entre el juez español y alemán fiscales", más que la información desclasificada de la CNI o el Ministerio de defensa. 
"Esta coordinación entre investigadores independientes complicará nuestros esfuerzos para manejar con discreción el caso entre los gobiernos"; dice Aguirre. 
En marzo de 2007 durante un almuerzo entre el Embajador de los Estados Unidos y el Ministro del interior, Alfredo Pérez Rubalcaba, éste comentó le "aunque los jueces españoles son rabiosamente celosos de su independencia y harán lo que consideran correcto"había dado instrucciones a sus colaboradores" para "evitar comentarios de retórica inflamada, en un intento de reducir la temperatura. 
El Embajador también expresa su preocupación por la acción del PP en esta materia. 
"A pesar de su orientación general pro estadounidense, nuestra experiencia indica que el PP no dude en aprovechar cualquier indicación de que el Gobierno de Zapatero tolerado o ignorado deliberadamente las acciones de los Estados Unidos que podría interpretarse como posibles violaciones de los derechos humanosincluso si estas revelaciones tienen consecuencias negativas para el Gobierno de los Estados Unidos, "indica. 
