El programa nuclear paquistaní genera gran inquietud en los Estados Unidos 
Islamabad produce armas atómicas a "un ritmo más rápido que cualquier otro país". 
Las filtraciones de Wikileaks confirman los lazos entre el pueblo de talibanes y Pakistán. 
El contenido de la correspondencia entre la embajada estadounidense en Pakistán y el departamento de estado de los Estados Unidos filtrados por el portal de Wikileaks confirma el enorme inquietud que nos lleva al programa nuclear paquistaní en Washington. 
Además de los detalles esclarecedoras y sustanciales que se ofrecen en el contenido de las conversaciones y los pensamientos de los representantes diplomáticos norteamericanos acreditados en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de seguridad nuclear, en lugar de aumentar, "disminuye" y que el país asiático inestable produce armas nucleares con "un ritmo más rápido que cualquier otro país". 
La particularidad del programa nuclear paquistaní - que las armas no son montados pero permanecen almacenados por componentes para dificultar su destrucción en caso de ataque--constituye una de las principales causas de preocupación en Washington. 
Por lo tanto es enumerados por el Embajador en Pakistán, Anne W. Patterson, en un informe previo a la visita del ex asesor de seguridad nacional, James Jones: "La proximidad de algunas plantas de energía nuclear en el territorio bajo ataque de los talibanes, la dispersión rumores de los materiales nucleares y la vulnerabilidad de transporte de materiales atómicos". 
El elevado número de personas implicadas en los arsenales nucleares y los programas de misiles se tiene en cuenta, no sólo por los Estados Unidos, pero también por Rusia, tales como la razón para mantener su guardia. 
"Pakistán ha tenido que contratar a personal con estrictas creencias religiosas a fin de proteger las plantas de energía nuclear; dados los pobres niveles educativos y culturales, las organizaciones extremistas tienen más oportunidades para reclutar personas para trabajar en los programas nucleares o de misiles",dijo el experto Yuri Carole, desde el Ministerio ruso de Relaciones Exteriores, en una reunión con sus homólogos estadounidenses. 
La información más reciente sobre la documentación que se filtra por el portal de Julian Assange es la disminución de cooperación entre Estados Unidos y Pakistán en temas de proliferación nuclear y la alta tasa pakistaní de producción de armas nucleares. 
Una Oficina de la Embajada en mayo, que describe como "frustrante" la comunicación con Pakistán, que dice: "la transparencia es frecuentemente inexistente; las ofertas de ayuda siguen sin respuesta o deniegan". 
En otro mensaje, Peter Lavoy, funcionario de la inteligencia nacional para el sur de Asia, afirma que "a pesar de la catástrofe económica, Pakistán produce armas nucleares en un ritmo más rápido que cualquier otro país del mundo". 
La Embajadora Patterson también pide a Washington, durante una visita del jefe del ejército, el General Ashfaq Kayani, a dar órdenes claras a la persona a cargo que "el ejército de Pakistán debe terminar el tácito apoyo a los grupos terroristas". 
