Nominaciones a los Grammy: cantante de Jazz Esperanza Spalding es una selección sorpresa en la categoría de mejor nuevo artista 
Realizar a petición de un Presidente, y las personas están obligadas a tener en cuenta. 
Esperanza Spalding, el bajista de jazz de 26 años de edad y cantante cosechadas por el Presidente Obama a realizar en su ceremonia de entrega del Premio Nobel de la paz en 2009, una de las sorpresas de los Grammys marcó este año con una nominación de alto perfil en la categoría de artista mejor nuevo. 
Considerando que Spalding ha sido una figura célebre de la escena jazzística desde su álbum de 2008, "Esperanza", la nominación es un poco de un Scratchers de cabeza, pero es coherente con las normas de los Grammys de un artista que no más de tres álbumes antes de la grabación que "establece la identidad pública de que el artista". 
Su álbum ambicioso de 2010, "Sociedad de música de cámara", sin duda marcó un paso adelante y dado airily invitando a estilo vocal y una mano hábil con el pop, funk y influencias latinas, es posible extraer al menos una línea de puntos a Spalding de éxito arrollador de Norah Jones en 2003, el equivalente más cercano a los votantes de Grammy mirando hacia el barrio de jazz en esta categoría en los últimos años. 
En otros lugares los votantes Grammy habían honrado con razón "Historicidad del Vijay Iyer trío" en la categoría de álbum instrumental, un viaje estimulante en la emoción de un registro que fue un favorito de la crítico el año pasado. 
Entre los Iyer estará compitiendo contra incluyen veterano "4B Moody de saxofonista James Moody" y "Positootly del pianista John Beasley". 
Trombón Shorty, un invitado estridente de favorito y frecuente de Nueva Orleans en HBO "Treme", fue galardonado en la categoría de jazz contemporánea, que lo contrario inclinaciones fuertemente hacia la fusión con asiente hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
Sociedad secreta de los salvajes, informó steampunk Darcy James Argue había ganado algunos merecido reconocimiento en la categoría de gran ensemble, compitiendo contra el Billy Childs Ensemble Rico cámara-jazz y el aventurero nunca Dave Holland, álbum de cuyo octeto "Vías" fue un buen ejemplo de mano Democrática del bajista como un líder de la banda. 
