Romano va hacia su primer título 
Rubén romano Omar cuenta con tres derrotas en las finales, que durante sus carrera subidas y bajadas, pero él sabía cómo llegar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey en la final, además de dos estilos diferentes, marcados por la cara de sus técnicos, que encontrar entre sí con un contraste marcado por los resultados. 
Rubén romano Omar cuenta con tres derrotas en las finales, que durante sus carrera subidas y bajadas, pero él sabía cómo llegar en tres ocasiones la serie decisiva, aunque hasta ahora no llegó a destino y esto es por qué esta oportunidad es muy especial para él. 
El argentino terminó se consuela con la medalla de finalista y mantenido un paso detrás de los ganadores y curiosamente con equipos similares ha jugado finales consecutivas. 
Santos llegó a su primera final como entrenador en el partido de apertura del 2002, cuando tomó las riendas de Morelia, que cayó a 4-2 ante Toluca; más tarde, en el caso de cierre de 2003 también llegó en el duelo decisivo y lo perdió también 3-1 y de hecho antes de Rayados. 
Ya con Santos Laguna, en el Bicentenario de 2010, una vez más antes de Los Diablos, Rubén nuevamente sufre un revés, ya que su equipo terminó igualmente lugares 2-2 ante los fabricantes de embutidos después de 210 minutos de juego, pero a la vez de las sanciones que se puso en ventaja por 3-1 con dos oportunidades para sellar el título pero finalmente tres jugadores error de los 11 pasos y sufrió el cambio 4-3. 
Rubén ya perdió dos finales con los Diablos Rojos y uno con Monterrey, su rival a su vez, por lo tanto, no quiere soportar la misma suerte, quiere celebrar un título por primera vez, y afirma que lo más importante para él es la institución. 
Quiero que ser campeón, no quiero romper cualquier estadística, se trata de un club, una pasión y en consecuencia el título llegará a mí, pero lo anterior es más importante, comentó el timonel al ser interrogado sobre los números que tiene contra jugando finales. 
Muy eficaz tiene la final anterior, de que, asegura, ha aprendido mucho, "la única lección que podemos aprender es que hasta que el árbitro señala el final no podemos celebrar, preparamos nosotros mismos, así como a los jugadores porque la vez anteriorcon penas de dos estábamos a punto de salir y creo que es una lección que aprender, no podemos celebrar hasta el juego termina. " 
Sabiendo que esta serie podría definirse en pena de patadas, algo que no problemas para él, porque él confía en sus jugadores: "uno nunca debe busca va a sanciones, sino más bien para terminar en el tiempo regular; a veces no tienen otra alternativa y es necesario estar preparados; Lamentablemente en el partido anterior que estábamos preparados, destino jugó en nuestras manos; a veces por los nervios o ansiedad por tener el título a manos, pero no llegar a este objetivo, y esto nos dejó algo para esta final que esperamos ganar. " 
Romano debe dejar de ser una técnica finalista y degustación por primera vez la gloria que le dan los títulos. 
