« Sangre de mayo ", un reto épico de Garci. 
José Luis Garci, inspirada en la novela episodios nacionales de Banito Pérez Galdós, recreates en sangre de mayo el español revuelta popular contra el francés. Esta es la más ambiciosa de su filmography, con un presupuesto de casi 15 millones de euros. 
Con esta película, el director ha intentado "explicar el torrente de personajes y, al mismo tiempo, el análisis social" que él siempre admirado en el trabajo del famoso novelista, dijo hoy durante la presentación de la película, con Quim Gutiérrez y Paula Echevarría dirige una mayor emitidos de intérpretes. 
Sangre de mayo, una película más de las 2.30 horas, debuts este viernes en los cines, a convertirse en una televisión Telemadrid miniseries de cuatro horas en el próximo futuro. 
Gran admirador de Galdós », afirma José Luis Garci este tiroteo se dio cuenta de que "el sueño de su infancia", le gusta a Esperanza Aguirre, que, tres años antes, había encargado a disparar una película para conmemorar el segundo centenario del 2 de mayo en Madrid, lo que fue el deseo expresado por la Comunidad de Madrid. El director de acuerdo con la condición de que la historia basado en la novela episodios nacionales. 
Los 15 millones de euros del presupuesto total asignado por la Comunidad de Madrid, representado por Garci una "oportunidad única" para recrear las series y trajes para dibujar un "a España que eligió para luchar por el líder y el hecho de que la lucha por la independencia condujo a la gente a un enorme retraso en el desarrollo durante el reinado de Fernando VII" dijo Garci. 
Sin embargo, el director se lamenta de no haber recibido fondos de igualdad Alatriste o los fantasmas de Goya - más del doble en comparación con sangre de mayo. Hasta ahora, no fue posible para disparar algunas escenas contenidas en el plan, él mismo había firmado junto con Horacio Valcarcel, su provenga de colaborador. 
La diferencia de presupuesto influido en la forma habitual del trabajo del director de volver una empezar: por ejemplo, la organización con los actores, con quien se utiliza a menudo repetido antes de disparar junto con los que no pertenecen al emitir, teniendo en cuenta esta "humillante" y pensando que "el trabajo del director reside en ir al teatro y el cine a cuenta de cómo la industria está trabajando para está pasando". 
Un cierto número de intérpretes, algunas de las cuales quedan dentro del puesto de Sangre de mayo, repetir en frente de su video-camera. Es el caso de Michael Rell, Carlos Larranaga o Fernando Guillen Cuervo. 
Cuatro veces al Oscar nominaciones - ganar - Garci cree que ninguno de los tres películas candidatos para representar a España en Hollywood este año, su sangre de mayo, siete mesas de billar francés, y Los girasoles ciegos ulitmo seleccionados representan al cine español de la generación más joven ", que debería ser conocido en su lugar". 
Garci no esperar los premios de esta película. 
"Al principio cree usted de trabajar para la posteridad, entonces se dan cuenta de que sólo trabajan para la prosperidad y a cierto punto acaba de disparar una película más", dice García después de más de 30 años de carrera. 
