Las drogas: nunca con los zumos de frutas. 
Tener cuidado de grapefruit zumo, zumo de naranja, y el zumo de manzana. 
Estas bebidas, especialmente consumida en verano porque son sed quenching y rica en vitaminas, junto con algunos de los medicamentos que salvan vidas pueden alterar su absorción, amplificando o disminuyendo, dependiendo del caso, su eficiencia con consecuencias que también puede ser grave para la salud. 
Confirmando los riesgos asociados con la asunción de los zumos de frutas si son prefabricadas o nueva con determinados medicamentos es David Bailey, profesor en la Universidad de Ontario occidentales en Londres, que desde el 236th encuentro nacional de la sociedad químico estadounidense en Filadelfia lanza una nueva advertencia: un vaso de grapefruit zumo, zumo de naranja, o el zumo de manzana es suficiente para reducir la absorción de determinados medicamentos que salvan anulando sus efectos benéficos y poner en riesgo la salud de los pacientes. 
Grapefruit salsa ya ha sido acusado porque estaba pensado para ser responsable para elevar los niveles, pensado para ser tóxicos, los efectos de algunos antirhythmic, antibiótico, tranquilising, antihistaminic y neurológicas medicinas. 
Las drogas en riesgo el mismo la agencia italiana había dado el mismo Consejo en una información Bill hace dos años, alertar a los médicos y los pacientes para no subestimar los peligros que se derivan de esta mezcla y prestar atención a lo que se consume en casos cuando se consume como, por ejemplo, Diazepam o metadona. 
No sólo grapefruit salsa, según los expertos, incluso de zumo de naranja y el zumo de manzana contienen sustancias que inhiben la droga. 
La lista de principios activos ha impedido por grapefruit los zumos de frutas y otros es muy largo. 
De ahí el llamamiento de Michele Carruba, director del departamento de Farmacología del Estado de la Universidad de Milán: "normalmente, estos descubrimientos son inmediatamente que acaparan la atención de los diversos organismos nacionales e internacionales de la droga que luego cambiar la información desprendimientos de medicamentos. 
Por lo tanto, siempre leer el texto explicativo de las medicinas y si hay algo que no está claro, no tener miedo a pedir al médico o farmacéutico aclaraciones » para subrayar el experto de la agencia Ansa. 
