Ustedes lo que usted comparte 
En su décimo cumpleaños Google puede admitir: hay en el bolsillo de los ciudadanos, así como sobre su cabeza, en el cielo. Google sabe donde la gente ir de vacaciones, ¿qué tipo de consultas médicas que visita y lo que les interesa. 
A pesar de todo, Eric Schmidt, una persona clave de la compañía aún no está satisfecho. 
Por otro lado, los escépticos que llevarlo en paralelo con Orwell terrible fantasía sólo puede ver la esencia de la web 2.0. 
Eric Schmidt declaró recientemente al Financial Times que el principal objetivo de Google para recabar más información personal de los usuarios. Es necesario mantener el objetivo original de los fundadores de Google, a saber: "para crear un sistema para toda la información del mundo", añadió. 
Según el Google-chief, la compañía - después de haber manipulado a todo el mundo en los últimos 10 años, sigue al inicio del camino hacia la capacidad de tratamiento de toda la información. 
Respondiendo a la pregunta sobre sus planes para los próximos 5 años, dijo que le gustaría asegurar que Google será capaz de responder a preguntas como "¿Qué debo hacer mañana?", o "¿Qué tipo de puestos de trabajo que me gusta hacer mejor?". Sin embargo, el software no puede dar las respuestas adecuadas a estas cuestiones aparentemente simple desde la cantidad disponible de información al usuario no es suficiente. 
No todos los usuarios de Internet son conscientes del hecho de que los términos registrados por ellos están registrados, así como la dirección IP utilizados para la búsqueda y las páginas visitados por ellos después. 
2-year-old personalizada utilizando la búsqueda de funcionar, los usuarios pueden almacenar sus propias historias de navegación, pueden revisar lo que estaban buscando, qué tipo de vínculos que buscadas en antes. En el largo plazo, puede ofrecer a los usuarios con personalizada conclusiones. La función llamó recomendaciones se basará en la misma lógica: será capaz de ofrecernos productos y servicios con la ayuda de las preferencias y registrado antes. 
"¿Qué pasa si mis datos personales son utilizados contra mí, si es descubrir qué hago yo? », se preguntan algunos de los usuarios preocupados por la information-monopoly de Google. 
Suele ser el grado del potencial representada por la compañía que genera contrarrestar reacción en los usuarios, no el sentimiento de culpa, el miedo al castigo, deseo de libertad o la rebelión contra la autoridad. 
No obstante, se ha confirmado que todos los términos Hidalgo registrados y, en su caso, quienes incluso pueden ser transferidos a terceros. En estos casos no protege la privacidad de los usuarios de Internet. 
El mejor ejemplo de esto es la acción concertada contra algunos de los pedófilos brasileña; Google transferido el Gobierno brasileño alguna información de uno de sus redes sociales páginas, llamado Orkut. Los datos facilitados ayudó al Gobierno identificar varios pederastas. 
Los usuarios que estaban preocupados por la invasión de la intimidad personal podría alivio en mayo, cuando Google - en asociación con la organización de ayuda jurídica Eef electrónicos probado con éxito su derecho contra el FBI: el Tribunal confirmó que en ningún punto de la Constitución puede el FBI obligan a Google para dar ningún tipo de información, pidió en secreto. 
(Sin embargo, - refiriéndose a la confirmación de la ley de protección de la infancia aprobado varios años antes, el Gobierno Federal consiguió acceder a 50 000 direcciones web y 1 000 búsqueda. Sin embargo, no podía adquirir la búsqueda de los usuarios individuales listas, ni una lista completa de las páginas web y claves que abarca un período de dos meses). 
Como parece, hay opiniones controvertidas en google. Es atacada por quienes temen de dar sus datos personales, pues consideran que su esfera íntima y vida privada se vería afectada por el uso de los servicios prestados por Google. Así, que representan más del Grupo conservador de resistirse a las empresas multinacionales. 
Mientras tanto, el estadounidense Geek cultura y su salvaje OAT incluidos entusiastas seguidores informáticos, activistas, los usuarios en varios países considerarlas como la próxima generación de grandes compañías, "una corporación fría", en contraste con su opinión sobre su rival, Microsoft, del creador de Windows y al vencedor del mundo, a pesar del hecho de que las dos empresas que lucha por el mismo objetivo. 
Uno de los motivos por los que puede ser que Google - a diferencia de Microsoft - no requiere identificación nombre de sus usuarios y dinero para las aplicaciones. Además, el código fuente abierto y actualizada continuamente y el programa conjunto - comparar al gigante del software oficial de la práctica - parece más disponibles, juvenil y frío. 
O tal vez es porque el hecho de que especialistas puede ver precisamente la problemática relación entre el privilegio personal y de Internet, que está en consonancia con la expresión más debatida clave de los últimos años, la web 2.0. 
La web 2.0 es una colaboración que intencionadamente dejar rastros de nuestro ordenador actividades y explotar los canales de comunicación. Aunque el grado de este acto puede ser diferentes, dependiendo del usuario, el punto principal es el mismo: mostrarnos al mundo. 
Un promedio joven puede abrir un perfil público en varias páginas como Facebook o Xanga, incluso pueden vincularlos a otros servicios como Twitter o la música lista hacedor last.fm, entonces los puede estar conectado a un sistema de seguimiento como FriendFeed o Blip.fm. además, los usuarios pueden crear blogs que automáticamente actualizar la recientemente uploaded foto galerías almacenados en Picasa o Flickr. 
Podemos leer en varios artículos como esta: la niña - comprobar la abundancia de fotos uploaded en la mañana por amigos comunes - donde se encuentra su digno de su anterior novio pasaron la noche. U otro: un empleado podría perder su puesto de trabajo porque la compartió su opinión sobre la gestión en su bitácora. Una consecuencia puede ser definitivamente: la definición de la privacidad ha sido revaluadas. 
Si alguien vive una vida online, son las que muestran de sí mismos - este es el concepto básico del comportamiento de la juventud. 
Si alguien tiene algo de mantener en secreto o si alguien sencillamente quiere evitar el monopolio de Google, también es posible utilizar Scroogle (por ejemplo, que también se aplica el sistema de búsqueda Google intencionada pero no deja rastro tras). 
El número de registro de redes sociales no intencionalmente a sitios es importante. De este modo se puede evitar que se descubrieron las aplicaciones online de Google, director gerente del texto a imagen y newsreader puede ser sustituidos por las versiones alternativas que no están en relación con gran servidor parques y no intentar crear nuestra mejor perfil nunca. 
Público en general está deseando ver lo que está siendo disimulados por Google. 
La compañía - con su valor de 156 millones de dólares - vale más que IBM (140 millones de dólares), Intel (124 millones de dólares) o Coca-Cola (110 millones de dólares). Además, los espacios publicitario AdWords y AdSense de amenazar a los ingresos de las agencias de publicidad y servicios introdujo a gran velocidad causa y varios otros desarrolladores de software Microsoft un serio quebradero de cabeza. 
Sin embargo, los críticos también puede encontrar la preocupante counterpoints: la gestión totalmente rechazado la objeción de los empleados, que reventó porque el cobro del maestro de la compañía se había duplicado. El comedor diario - el uso de que había sido autorizados en cualquier momento e incluso varias veces - también fue considerada demasiado costoso por la Administración. Sin embargo, todas estas no son nada en comparación con el hecho de que Google cedido antes del Gobierno chino en 2006 y, según el acuerdo, la compañía ha filtrado todos los resultados de búsqueda que ofenden a buen sabor o los intereses del régimen chino. 
Uno de los reglamentos internos de la compañía dice que los nuevos servicios no será anunciado por adelantado, sólo cuando están listos para ser utilizado. Aún, los próximos meses y años, sin ninguna duda, tendrán una enorme influencia en el mundo: algunas personas predicen que el libro y a la revista y archivo de proyecto de Google pronto llegarán a tales proporciones que tendrá que enfrentarse al Tribunal Supremo. Otros tienen miedo del sistema de salud, que tiene la capacidad para construir una completa del perfil de la Salud de Estados Unidos, incluida nuestra anterior descubrimientos médicos, los médicos y los problemas. 
Por último, el hecho de que Google es construir una base de datos genética puede ofrecer una base material perfecto para la sci-fi escritores de la próxima generación. Cory Doctorow popular novela, Scroogled se aplica al estilo de Orwell en la descripción de un futuro donde una persona puede ser imaginamos bien hecho sólo mediante el uso de Google datos. 
