Járóka: el círculo vicioso de la pobreza, la segregación deben ser eliminados 
La Cumbre Europea de la igualdad se ha abierto hoy en París, que está organizado por Francia este año, que representa a la Presidencia de la Unión Europea. 
En su mensaje de que ha dirigido al Pleno, Lívia Járóka de Fidesz, representante del Partido Popular Europeo llamó la atención de la segregación educativa que es uno de los más graves de violación que afectan a los niños romaníes. Además, este es el mayor obstáculo para su prosperidad. 
La conferencia de alto nivel ha sido abierto por Xavier Bertrand, ministro de Trabajo y Asuntos Sociales y Vladimir Spidla, el comisario europeo de Empleo, Asuntos Sociales e Igualdad de Oportunidades. 
Los representantes de los Gobiernos, los interlocutores sociales europeos y la más importante de las organizaciones de ayuda jurídica europea y las ONG del ámbito de la igualdad de oportunidades fueron invitados a tener un puesto en la Conferencia. 
Járóka - según la oficina de prensa del grupo Fidesz en el PE - señaló que, además de la discriminación experimentada a la hora de solicitar un puesto de trabajo, los romaníes aislado del mercado laboral, principalmente debido a su baja cualificación educativa. 
"La mayoría de los jóvenes romaníes no tienen una calificación secundaria, y debido a la baja calidad de la educación básica sólo una parte insignificante de ellos pueden obtener del colegio o grado universitario". 
Járóka también subrayó que la educación, como un derecho humano fundamental, desempeña un papel clave en la aplicación de los derechos humanos. 
Invertir en los principios de la educación de los niños de etnia romaní puede contribuir al fortalecimiento de la economía de los Estados miembros de la Unión Europea. 
Según el representante, es necesario informar al mayor número de personas - romaníes y no romaníes personas así - sobre estas interrelaciones. 
La anterior un joven estudiante romaní empieza a asistir a la escuela, el mayor de sus posibilidades productivas para convertirse en un miembro del mercado laboral; a través de los ingresos y los impuestos pagados por ellos podrían contribuir al presupuesto nacional. 
"sobre la base del derecho de ciudadanía aplicando en la Unión Europea, el derecho a la educación de calidad debe estar garantizada para el pueblo romaní y de baja calidad, segregado la educación debe ser eliminados", añadió Lívia Járóka. 
También ha dicho que para instantáneamente acelerar los procesos de escuela desegregación, es necesario garantizar un objective- y orientado a la cooperación en el seno de la Unión Europea. Para lograr este objetivo, es fundamental para la aplicación y planificado adecuadamente las actuales directivas contra la discriminación. 
"El círculo vicioso de la pobreza, la segregación, el desempleo deben ser eliminados, los niños romá debe ser siempre con las oportunidades de vida democrática para que puedan contribuir al futuro de Europa como ciudadanos con plenos derechos", exigió Járóka. 
Dentro del marco del « Año europeo de la igualdad de oportunidades ", la igualdad, la primera cumbre organizada en Berlín el año pasado y desde entonces mantuvieron sobre una base anual - pretende ofrecer un foro único para promover los objetivos de igualdad de oportunidades y la lucha contra la discriminación a nivel europeo y de los Estados miembros. 
