SMS anuncia un protocolo para encontrar la obesidad gen
La Seguridad Social dirige una investigación para encontrar el gen de la obesidad en los niños y jóvenes; es apoyados por los especialistas de la
El Instituto Mexicano del Seguro Social (MSSI) ha anunciado que realiza una investigación para descubrir el gen de la obesidad en los niños y jóvenes, pidió el Protocolo de "genética de la obesidad en la infancia y la Adolescencia", que permitirá contar con marcadores relacionados con el sobrepeso.
En un comunicado, el Jefe de la Unidad de Investigación Médica en Bioquímica del Hospital de Especialidades, del Centro Médico Nacional Siglo XXI, Miguel Cruz López, explicó que se integró un equipo multidisciplinario de médicos, enfermeras, nutricionistas y trabajadores sociales.
El equipo está apoyado por especialistas y estudiantes del Instituto Nacional de Salud Pública y el Centro de Investigación y Estudios Avanzados (Cinvestav) del Instituto Politécnico Nacional (las ISFL).
La investigación invita a la población o no derecho a participar por ir al participante del deporte de las unidades MSSI en el Valle de México, donde se realizan las pruebas a los niños, todos los sábados de ocho horas.
Destacó que el Protocolo se inició en la unidad deportiva Cuauhtémoc (oeste) y el Estado de México desde el 8 de octubre de la actividad se lleva a cabo en la Unidad Deportiva Netzahualcoyotl (este Estado de México).
Una vez alcanzado el objetivo de acercar a 500 a 600 niños, el estudio continuará en la Unidad Deportiva de la Independencia de la Ciudad de México (sur) y, por último, en la Unidad Deportiva de Morelos (Norte de la Ciudad de México).
Explicó que el objetivo de esta investigación es comprender los componentes y la importancia de la genética en relación al desarrollo de la obesidad e identificar a los niños y jóvenes mexicanos los factores de riesgo para prevenir la aparición de las enfermedades crónicas degenerativas.
El 14 de noviembre, se celebró el Día Mundial de la Diabetes, y el objetivo es recoger tres mil niños y jóvenes de entre 6 y 14 años, con el consentimiento y la supervisión de los padres para la aplicación de cuestionarios específicos sobre los alimentos.
También se ha preguntado sobre la actividad física y la familia de la historia de las enfermedades hereditarias, a fin de evitar los factores de riesgo que provocan enfermedades como la diabetes o insuficiencia renal.
Explicó que el sábado a todos los participantes se aplicarán mediciones antropométricas (peso, estatura y cintura circunferencia), las mediciones de la presión arterial, y la determinación de glucosa, colesterol y triglycerides, insulina y genética (tratando de identificar los genes que están asociados a la obesidad infantil).
Cruz López dijo que esta investigación refleja la preocupación de los profesionales de la salud para el alarmante aumento de peso en los niños.
Las encuestas de salud entre 1999 y 2006, informó que en sólo seis años hubo un aumento en el caso de los varones, el 77% eran obesos y el 47% en el caso de las niñas; en términos del sobrepeso también se observó un aumento espectacular ", dijo el especialista del MSSI.
Dijo que la justificación para la búsqueda de los marcadores se basa en que la población del país difiere de otros en su historia genética.
Dijo que, en promedio, el mexicano un 65% de los indios americanos, el 30% del patrimonio europeo y cinco por ciento de África y esta condición se refleja en los genes que están asociados a la diabetes y el sobrepeso.
Explicó que, en términos generales, la genética de la obesidad resultado en la incapacidad para quemar el exceso de la energía que consumimos (calorías) y que se almacena en grasa.
El investigador explicó que el beneficio directo para los participantes es una evaluación completa de los niños, que pueden detectar si tienen algún grado de sobrepeso u obesidad.
Incluso, dijo, la presencia de dark-colored pliegues (acanthuses) del cuello y antebrazo indica la probabilidad de sufrir de enfermedades metabólicas e incluso prediabetes.
La información se maneje con la confidencialidad, los médicos entregarlo por escrito a los padres, a los que explicarán cada una de las mediciones y los cambios en el estilo de vida que han emprendido para prevenir la enfermedad.
Cruz López explicó que hay tres componentes principales causantes del sobrepeso, la obesidad y otras enfermedades crónicas: el sedentarismo, que es la falta de actividad física diaria, que permanece la mayor parte del día y viendo la TELEVISIÓN y utilización de medios de transporte en lugar de caminar distancias cortas.
También es debido a la Alta ingesta calórica, significado y el aumento del consumo de las bebidas azucaradas, tamales, hidratos de carbono (PAN, pizzas, hamburguesas, etc.) con un alto grado de grasa y proteínas y genética analizado en este Protocolo.
