Austria
La inscripción de una "regla de oro presupuestaria" en la Constitución
El Gobierno de la gran coalición de socialdemócratas y democratacristianos en el poder en Austria decidió el martes para escribir una "regla de oro presupuestaria" en la Constitución, a fin de reducir los déficits públicos y evitar así una posible rebaja por parte de las agencias de calificación de crédito soberano de Austria rsting (triple A).
El Canciller socialdemócrata de la elf, Werner Faymann, quien anunció esta decisión al término de una reunión del Consejo de Ministros, con la deuda pública austriaca a 74,6%, muy superior a la norma de un máximo de 60% fijado por el Tratado de Maastricht, pero por debajo de la deuda pública de países como Italia, Grecia o España.
"Si la solvencia de Austria no había caído por un peldaño, de AAA a AA+, tendríamos que pagar tres mil millones de euros de intereses más cada año", afirmó el Ministro de Asuntos Exteriores y los vicerrectores de la democracia cristiana, Michael Spindelegger.
Por ello, Austria cumple con una petición de la Cumbre de Bruselas de los Estados miembros de la zona euro del 26 de octubre; los Jefes de Estado y de Gobierno pidió una reducción por la final de 2102 de los déficits públicos y un retorno al equilibrio de las cuentas públicas en la Constitución o en una ley para el mismo efecto.
Las disposiciones aprobadas por el Gobierno austríaco enfoque, el "modelo alemán", ha sido el primer país europeo para adoptar esta "norma".
En 2017, el público déficit estructural deben caer por el 0,75% del PIB) y a partir de 2017, el déficit público estructural del Estado Federal de Austria no debe superar el 0,43% del PIB en cada año, mientras que los Länder, así como a las comunidades, deben presentar presupuestos equilibrados.
El objetivo es el de la deuda pública por debajo del 60% del criterio fijado por el Tratado de Maastricht por 2020/2021.
