Debe haber hecho aportaciones a obras
Las obras sociales que se menciona en los programas como Hábitat, Rescate de Espacios Públicos y 3x1 para migrantes corren el riesgo de no ser completados o a tener serios retrasos debido a la falta de fondos, dijo Miguel Ángel López Miranda.
El Director de Desarrollo Social Municipal indicó que, aunque hasta ahora los programas de trabajo han avanzado corren riesgo porque el Gobierno del Estado no pudo hacer las aportaciones que corresponden, lo que representan un recurso superior a los 11 millones de pesos en los tres programas.
Señaló que la inversión total en estos tres programas es de casi 50 millones de pesos, de los que el Estado tiene que contribuir con el 25% y hasta ahora sólo la Federación y el Municipio han proporcionado los recursos para las obras, por lo que el posible retraso en la finalización de estos está en vigor.
"tienen que contribuir con casi 12 millones de dólares y aunque el año termina no nos han dado un momento, ya que a partir de julio tuvieron que darnos una parte", dijo, "para no retrasar nos hemos comenzado las obras y están muy avanzadas, pero necesitamos el dinero."
Mencionó que el año pasado, durante la administración de Jesús Aguilar Padilla, el Estado no cumple con las contribuciones que tenía que hacer, así que al inicio de la administración el municipio tuvo que pedir dinero prestado para cubrir más de 7 millones de dólares, una suma que no estaba prevista en esa ocasión por la administración estatal.
"se nos ocurrió en la administración anterior porque el Estado no tiene la capacidad financiera para participar y los programas continuaron avanzando, y este año, con el fin de acceder a estos programas teníamos que conseguir los recursos para cubrir lo que el Estado dejó pendiente", explicó.
Aunque hay un compromiso de las autoridades estatales para cumplir con la entrega de estos recursos, dijo que la petición fue realizada al Secretario de Administración y Finanzas, Armando Villarreal, para acelerar los esfuerzos para que los porcentajes que corresponden a los lleguen lo antes posible.
"tienen que contribuir con casi 12 millones de dólares y aunque el año termina no nos han dado una dime."
