Las adversidades climatológicas frenó la economía
Durante el primer año de gestión de Mario López Valdez, en Sinaloa el aumento del desempleo y la informalidad, la inversión extranjera disminuyó y la economía se redujo.
2011 es un año que será recordado en la historia económica de Sinaloa, está relacionado con el primer año de gobierno de Mario López Valdez pidió también el año del cambio, que generó grandes expectativas en cuanto al desarrollo de la economía, pero dada la adversidad climáticas del comienzo del año, no hay crecimiento, sin embargo, se registró un descenso en los principales indicadores del desarrollo económico.
Las bajas temperaturas de febrero, no sólo causan pérdidas de millones para el sector agrícola, pero se limitan las posibilidades del Estado de la economía para crecer, causando una contracción de la actividad económica en general del 3,6% en el primer semestre del año, apoyado principalmente por la histórica caída de 31.16% en la agricultura, que afectó a la dinámica de otros sectores económicos.
Según el informe sobre las zonas afectadas por las heladas, emitidas por el Consejo Mexicano para el Desarrollo Rural Sostenible no resultaron dañadas 835.582 hectáreas, de las cuales 78.03% sufrieron daños totales y el resto de 21.07% tenía daños parciales. Los principales cultivos dañados fueron las hortalizas, el maíz y el garbanzo.
La caída de la actividad económica ha generado, hasta noviembre, un constante aumento del desempleo en el Estado, según el Instituto Nacional de Estadística y Geografía, la tasa de desempleo durante los tres primeros trimestres del año registró un crecimiento acelerado, de enero a marzo 55.053 Sinaloa habitantes están desempleados, con una tasa del 4,53% de la población económicamente activa para el segundo trimestre, la tasa se convirtió en 5.28%, y entre julio y septiembre del promedio siguió aumentando a 6.19%, una tasa que en términos del número de personas que representa más de 74.000 de desempleados Sinaloa habitantes, un aumento en comparación con el primer semestre de 18.969 personas.
Escasa liquidez
El desempleo en Sinaloa durante el año tiene múltiples facetas, por el economista Gerardo López Cervantes, director de la Facultad de Ciencias Económicas y Sociales de la UAS, el crecimiento del desempleo puede explicarse indirectamente, dependiendo de las medidas que se ha tomado la política pública.
"Lo que estamos viendo ahora es un aumento del desempleo, que tiene que ver con varios factores, incluidos la pérdida de liquidez en el mercado con el fin de la limitación de recursos impuesta por la legislación aprobada en el Congreso para combatir el lavado de dinero desde para las personas que posean ilegalmente dólares no es fácil trabajar con, invertir y utilizarlos en algo", dijo.
Dejó de Inmigración
López Cervantes dijo que en el aumento del desempleo también es un factor demográfico.
"El número de personas que abandona el Estado en busca de un empleo en el extranjero, en los Estados Unidos han sido restringido, en primer lugar debido a las dificultades para entrar, y en segundo lugar porque una vez que entren ya tienen demasiadas dificultades para encontrar un empleo, ese grupo de personas que se encuentren y exigiendo empleos aquí en el Estado, causando la tasa de desempleo en aumento", dijo.
Informalidad
El análisis del mercado laboral de Sinaloa empeora cuando examine el alto nivel de informalidad que reina entre las condiciones de trabajo, según el INEGI, 60.38% de la población activa en el Estado de las obras sin ser citadas como trabajadores a ninguna institución de seguridad social.
Además del desempleo y la informalidad, otro Estado recordatorio laboral está representado por los bajos salarios, la entidad tiene los salarios más bajos en el país, según los registros del Instituto Mexicano del Seguro Social y el Ministerio de Trabajo y Bienestar Social.
El promedio mensual de los ingresos de los trabajadores de Sinaloa, hasta septiembre, 5.352 pesos, muy por debajo de la media nacional, que es de 7.375 pesos.
La contracción de la IED
Además de la caída de la actividad económica y la alta tasa de desempleo, en 2011 se registró el mayor descenso de la inversión extranjera directa en los últimos 10 años, según el Ministerio de Finanzas de enero a junio del Estado de la IED ascendió 630.697 dólares, lo que representa una caída de 87.74% frente al dólar 5.143.312 durante el mismo período del año pasado.
Por su parte, el Ministerio de Desarrollo Económico del Gobierno del Estado representa una inversión total de 17.280.000 pesos durante el año, que se produjo principalmente en las empresas del sector terciario.
La deuda
Contra el telón de fondo de la desaceleración económica, el Gobierno del Estado solicitó en julio durante el Congreso del Estado, la aprobación de un crédito de 3 millones de pesos, que serán destinados a la inversión en proyectos de infraestructura en los 18 municipios, con el fin de reactivar la economía local fue la aprobación del Congreso para un total de 2.600 millones de pesos, y hasta noviembre de ninguno de los beneficios de la deuda se observó en cualquier sector de la economía estatal.
Las reacciones
Para los representantes empresariales, el primer año de gobierno de Mario López Valdés demuestra una falta de capacidad del Gobierno.
Miguel Loredo López, Presidente de la Cámara Nacional de la Industria de Transformación, dijo que durante 2011 hubo una falta de armonización de las voluntades de diversos sectores, incluidos el propio Gobierno estatal.
"El desempeño de la economía en Sinaloa este año ha sido realmente pobres, uno tiene que trabajar duro para recuperar el terreno perdido este año, en 2012 debemos redoblar nuestros esfuerzos, no hemos logrado sumar los esfuerzos de todos y, sobre todo, la buena y sincronizados moción del nuevo equipo de gobierno, esperamos que el próximo año será mucho mejor", dijo.
Ralentización económica
López Loredo dice que los acontecimientos como las heladas de este año dejó del Estado de la economía y su desempeño y el crecimiento fueron restringido.
"El escaso flujo económico es el producto de varios acontecimientos, incluidos las heladas, uno de los principales efectos han sido una economía lenta que no pasa con la rapidez suficiente para generar un dinamismo económico que permita tener un nivel aceptable del flujo de los procesos, productos y servicios y, por lo tanto, al final del año estamos cerrando por debajo de nuestras expectativas", dijo.
La redefinición de la vocación
Teodoro Salazar Uriarte, Presidente de la Confederación Patronal de la República Mexicana "en Sinaloa, dijo que el Estado está obligado a enjuiciar las más dinámicas actividades productivas.
"En general, constata que se ha estado trabajando en, creemos que es necesario elaborar un programa a largo plazo que redefine la vocación y el rumbo económico del Estado, es importante para detonar el potencial de los recursos materiales y humanos que Sinaloa tiene", dijo.
El trabajo a Do
Coparmex Presidente destacó la importancia de establecer una visión de futuro para orientar mejor los esfuerzos del Gobierno.
"En general, quiero decir que el Gobierno ha estado luchando para tener éxito en diversos ámbitos, en términos de desarrollo económico, hay algunos avances, pero es importante desarrollar un programa de largo plazo", dijo.
Señaló que la actual administración ha mostrado progresos en su manera de dirigir la política pública.
"hay elementos que nos permiten decir que el Gobierno se está volviendo más inclusivo, y lo que puedo decir es que hay trabajo y creo que el Gobierno es consciente de que hay que hacer", dijo.
