El apoyo del Sindicato de Trabajadores Will Sue City Over Layoffs
El sindicato que representa a cientos de trabajadores de apoyo escolar que perdieron sus empleos el mes pasados planes para demandar a la ciudad el miércoles, alegando que los despidos eran innecesarias y discriminatorias debido a su impacto desproporcionado en las escuelas para estudiantes pobres.
La demanda es posiblemente la última arma al sindicato, el Consejo Distrital de 37, en su esfuerzo para revertir los despidos.
Seiscientas setenta y dos ayudantes escolares, padres coordinadores y otros empleados que se encuentran entre los salarios más bajos de la ciudad perdieron sus empleos en el 7 de octubre, en un acto político de los líderes sindicales han descrito como venganza por su negativa a permitir el acceso a la ciudad de un fondo de atención de la salud administrados por los grupos de trabajo para cerrar la brecha presupuestaria de la primavera pasada.
Los funcionarios municipales han negado categóricamente que la acusación.
En una audiencia el mes pasado, el Ayuntamiento de Escuelas Canciller Dennis M. Walcott dijo que los despidos son parte del presupuesto se firmaron en junio.
Un miembro del concejo disparó hacia atrás, diciéndole que nada en el presupuesto de apoyo escolar, especificó que los funcionarios serían despedidos.
El Consejo del distrito de 37 funcionarios dijeron que presentaron una notificación de la denuncia, la advertencia del Departamento de Educación que sería demandado; se celebrará una conferencia de prensa el miércoles para anunciar la demanda interpuesta formalmente en el Tribunal Supremo del Estado en Manhattan.
La lista al Sr. Walcott y la ciudad del Departamento de Educación en calidad de acusados y cuentan ocho trabajadores despedidos como demandantes, todos ellos de la mujer negra o Latina, así como la mayoría de los asistentes que perdieron sus empleos.
Elizabeth Thomas, portavoz del Departamento de Derecho de la ciudad, dijo que la ciudad no había visto la demanda y, por lo tanto, no puede comentar sus alegaciones específicas.
Según un borrador de la denuncia obtenida por The New York Times, el sindicato ha reducido a cero en el número de despidos en las escuelas de las regiones más pobres de la ciudad para apoyar una reclamación de trato desigual, diciendo las escuelas pobres perdieron más ayudantes porque habían sido crónicamente subfinanciadas.
Señala que, si bien no hay despidos en Staten Island y pocos despidos en las escuelas en el Upper East Side o TriBeCa, 17 auxiliares escolares perdieron su empleo en el distrito 23 en Brownsville, Brooklyn, y 46 fueron despedidos en distritos 8 y 9 en el sur del Bronx.
Observando la pérdida de cinco de los ocho auxiliares de escuela empleada por la Escuela Pública 36 en Harlem, donde el 68% de los estudiantes que viven en la pobreza, la demanda dice: "Esto no es un barrio adinerado de padres que pueden recaudar fondos para compensar el déficit presupuestario."
S. 36 "el presupuesto se redujo un 3,26% este año, y también perdió dinero cuando la ciudad cambió la forma en que se calcula la financiación adicional para cada estudiante matricular escuelas pobres.
El sindicato también afirma que los altos directivos de escuelas podrían haber sido engañado por el idioma en un memorando autoriza la destitución de los coordinadores de los padres.
El memo utilizó la palabra "exceso" para describir la acción, aunque el "exceso" más comúnmente describe el hecho de pasar un profesor de una escuela en la nómina de un grupo de trabajadores disponibles que tienen salarios pagados por la Oficina central.
"sesenta y seis coordinadores de los padres fueron despedidos," el proyecto de denuncia dice, "y no simplemente excessed."
