Mujica viaja a México para fortalecer los lazos políticos
Una delegación oficial encabezada por el Presidente uruguayo, José Mujica, y compuesto por varios ministros y empresarios, comenzarán este martes una visita a México para ampliar el comercio entre los dos países y abordar las cuestiones políticas en la región.
Mujica se reunirá el próximo miércoles su igualdad de México, Felipe Calderón, el punto más alto de un amplio programa de reuniones con autoridades políticas, comerciales y una reunión con la comunidad de los uruguayos que viven en México, según el calendario publicado por la Presidencia uruguaya.
La reunión entre ambos Presidentes, en la ciudad de Guadalajara, será "favorable para el intercambio de información con respecto a las cuestiones políticas entre las dos naciones", como publicó la Presidencia del país sudamericano en su sitio web.
Según los medios locales, Mujica intenta conseguir el apoyo de Calderón para Uruguay en el incidente con Francia que surgió cuando el Presidente francés Nicolas Sarkozy, incluido el país sudamericano en una lista de paraísos fiscales en la reunión del G20 en la ciudad francesa de Cannes.
En su discurso, Sarkozy amenaza con excluir de la comunidad internacional a los países que siguen siendo paraísos fiscales, una declaración que provocó la negativa del Uruguay y la llamada a consultas a su Embajador en el país europeo.
México preside desde noviembre, el G20, un grupo integrado por la más potente del mundo desarrollado y los países emergentes, y en efecto con el país sudamericano desde enero de este año, un acuerdo para intercambiar información fiscal para evitar la doble imposición.
El Gobierno uruguayo ha intentado en los últimos años para acelerar la conclusión de acuerdos de intercambio de impuestos para salir de la "lista gris" de la Organización para la Cooperación y el Desarrollo Económico (OCDE), integrado por los países que no apliquen todas las normas internacionales de cooperación tributaria.
Sobre el plan del comercio, México y Uruguay tienen en vigor desde 2004 un Acuerdo de Libre Comercio (TLC) que ha aumentado el intercambio de mercancías entre ambos países.
