Detained el alcalde de Totana y el jefe de la policía local sobre una conspiración de corrupción city-planning presumió  
La Guardia Civil ha detenido el alcalde actual de la Murcian municipio de Totana "," popular Andreo José Martinez, el jefe de la policía local, el secretario del consejo de la ciudad y un empresario hostal sobre los crímenes de city-planning posibles fuentes, nos han informado de hoy.  
La edil fue arrestado en su casa, abordar y ha sido trasladada a la Consistory , en cuyo dependencias es actualmente con varios agentes, que también se han ido al Consejo y la empresa de gestión urbana municipales de Confederaciones de suelo y vivienda.  
Estos tres detenciones se añaden a seis hizo el lunes en Galicia, Murcia, Madrid, en una operación vinculada a la recalificar, más de 2.000 millones de hectáreas de rustic terreno para urbanizeable para que la compañía gallega Nuaria construido 4.000 casas, después de que el pago de las comisiones ilegales durante la última legislatura.  
Además, hay otros dos personas fueron detenidos, pero no acusa a la conclusión, que ordena al Tribunal de la Totana número 1.  
Los seis primeros arrestos han ido ante el tribunal de hoy.  
Según las fuentes de información, la anterior alderman de Totana y autonomic parlamentaria real del PP, Juan Morales, se está investigando.  
Además, la antigua esposa, propietario de una agencia inmobiliario inscritas en Totana , ha sido tramitando ni, como lo es la novia actual de la antigua alderman Murcia- que reside en la capital.  
El director y propietario del Grupo Nuaria , el abogado y industralist Vigo Manuel N.A. , fue detenido en Nigrán (Pontevedra), como se decía Pablo José M.G. , terreno director de Inmonuar , de una agencia integrado con el mencionado grupo, y a través del cual los sobornos se habría hecho.  
La investigación es la responsabilidad del Grupo de Crímenes de City-planning Operar Oficina Central (UCO ) de la Guardia Civil, cuyos agentes, además de las detenciones, llevó a cabo once discos, la mayoría de las empresas se refería a los detenidos y situadas en Madrid, Vigo, Murcia, Pontevedra, Madrid y Totana .  
Una persona después fue arrestado en Totana , en particular, el propietario de las aves de corral producto empresa bien conocido en la región, que podría haber actuado como intermediaria.  
El Grupo Nuaria fue responsable del desarrollo de lo que se convirtió en el complejo residenciales más grande de la Murcian municipio de Totana , en el que participaron en la construcción de más de 5.000 casas, un golfo y dos hoteles con "balneario".  
La empresa adquirido en Totana 2.200 millones de metros cuadrados de tierra que fueron recalificados y su proyecto presuponía la duplicación de la población del municipio, que ha 25.000 habitantes.  
El Grupo Nuaria integra a empresas como Autesa y Inomonuar , dedicado al desarrollo; Conycase inmobiliario, que gestiona el estacionamiento de las sedes de las calles de Coruña, Venezuela y la Fernando la cuadratura; Hogartel católica, dedicada al sector de la comercialización directa; Preconiza defendido centrarse en la promoción, la venta y la instalación de los elementos de la construcción.  
