Congreso apruebe la transposición de Mifid que tuvo lugar en noviembre de 1ª  
Junto con sus procedimientos parlamentarios, que terminó hoy con el voto parcial del Congreso sobre las enmiendas incorporadas al proyecto en el Senado, el gobierno ha sometido a la audiencia pública la regulación que se va a desarrollar la nueva ley, con el objetivo de la fuerza ino antes de que termine el año que viene.  
Los representantes de diferentes grupos acordado en enfatizando los esfuerzos realizados por diputados y senadores para negociar y de acuerdo en la mejor legislación para garantizar la protección de los inversores y regular en detalle las organizaciones de la actividad para que los mercados trabajar de manera eficaz.  
La Mifid , que modifique la Ley del Mercado de Valores, implica la modernización de los mercados financieros, mientras que refuerza la protección de los inversores, la mejora de los poderes de control de la Comisión Nacional del Mercado de Valores (CNMV ) y fomenta la cooperación entre los diversos supervisores de la Unión Europea.  
Los nuevos reglamentos concederán consultivo a las compañías especializadas de los servicios financieros, así como a las personas físicas o jurídicas, y crea un nuevo tipo de empresas asesores financieros (ESIS ), las empresas de asesores financieros (AFI ), que incluye a las empresas de valores, los corredores, y las empresas de gestión de la cartera.  
Además, amplía el número de los sistemas disponibles para la ejecución de operaciones financieras, para incluir en la reglamentación son los mercados secundarios, los sistemas de comercio multilateral, y la internacionalización de los sistemas de órdenes, estos va a competir con los gerentes de la actual de los mercados de valores.  
La ley también exige revelar a las compañías de servicios de inversión en el mercado de los detalles clave de su negocio perfil, la exposición a los riesgos y las formas de gestión del riesgo y mantener un registro de todos sus operaciones a facilitar la supervisión por la CNMV .  
En su paso a través de la Comisión de Asuntos Exteriores del Congreso, varios modificaciones se introdujeron, principalmente securitised deudas debería considerarse como un instrumento financiero "complejo", debido a su alto riesgo para los inversores, que se ha demostrado por lo que sucedió con las deudas (hipotecas de alto riesgo hipotecas estadounidenses).  
Además, la transposición aprovecharon la directiva de jurídicamente definir las funciones que puedan desarrollar graduados de Economía y Hacienda decreto en 30 años después de la aprobación general en 1977, que delimits las funciones profesionales reservado a los economistas profesionales.  
Por su parte, el Senado promovió la creación de un nuevo papel en el sector financiero, como el asesor financiero, que van a trabajar para contratar o recompensa, no requieren SEC aprobación y serán capaces de proporcionar servicios de sus productos y de la comercialización de intermediación a clientes en varias empresas de inversión, al mismo tiempo.  
