La Celtic mirando en Milán, un punto que vale la pena octavo  
Milán y Celtic están desempeñando el martes a San Siro en busca de la cuestión que se necesita para alcanzar sus respectivos objetivos en el cierre de la liga "campeones", como los italianos están acostumbrados a ser primero y los escoceses por su condena clasificación.  
Los italianos añadió diez puntos y certificadas en el quinto día ya pasar con una corbata en Portugal, mientras que ha celta nueve puntos, pero todavía hay otro para asegurarnos de que el Shakhtar , con seis, y que Benfica , que tiene cuatro, no apoderarse de ella.  
Estos dos partidos de Grupo D será desempeñado en una semana antes del final de la sexta día, desde Milán tiene que desempeñar en el Mundial de Clubes en Japón, donde se hacen su debut sobre el 13 en la semi-finals en busca de un lugar durante el último sobre 16.  
Por lo tanto, este grupo será cerrado antes de que el resto y Giuseppe Meazza parece a esperar una corbata como el resultado, pero los dos equipos intentará ir por una victoria, y los italianos no quieren especular en casa y Celtic sabe que ganar sería la primera y aseguraría una cruce a la cuarta parte premios mejor.  
Para el equipo Gordon Strachan podría servir incluso una derrota para clasificadas Shakhtar si no gane, pero puede no ser confiaron porque la igualdad de nueve puntos significa que la Ukranians adóptenla, quienes perdieron la semana pasada en Glasgow (2-1 ), pero ganó (2-0 ) en otro duelo vivir.  
Así, Milanists amenazar a hacer una amarga noche para los escoceses, que dependen de entrar en los círculos por segunda vez en una disputa en la Liga de Campeones reestructurados, después de que fueron precisamente derrotado en esta última ronda por una meta de Kaka en el prolongado tiempo (1-0 0-0 ) después de la ronda.  
Esperar a la victoria de la "rossoneri " será el Shakhtar a la que sólo el ganar hará, en el caso de que perdieron tanto celta entrar en cuartos de continuar con la UEFA.  
Y como a Benfica , a pesar de ser la última y sin cualquier esperanza de permanecer en la cima la competencia europea, podría llegar a un tercer lugar con una victoria, que desempeñar UEFA.  
