La Guardia húngara Capital Políticos: el nivel de riesgo del país se ha agudizado  
Las acciones por la Guardia húngara, establecido en agosto de con el apoyo del Movimiento para una Righter Hungría, ha planteado el nivel de riesgo político de Hungría y toda la región desde una serie de aspectos, según la División Analizar Riesgo de Capital Políticos.  
La investigación entidad emitió un riesgo advertencia "," escribir: las acciones de la Guardia húngara son desencadenar un riesgo político extralimitándose "que las tensiones étnicas ya existentes entre los gitanos y de los residentes de Hungría podría non-Gypsy recalentando a niveles tóxicos tan pronto como el liderazgo de corto plazo, a los conflictos étnicos que podrían tornarse violenta".  
La principal razón para esto es que la estrategia política de la Guardia húngara parece estar destinada a provocar una acción de esta naturaleza, los institutos de investigación añadido.  
Este es el resultado de uno de los más graves fracasos de actores políticos de Hungría: "Los principales actores de la vida pública se convirtió en el debate público de cuestiones relacionadas con los representantes de las fuerzas políticas radicales y extremistas, y que han desarrollado una estrategia política fuera de Gypsy-Hungarian diferencias".  
Esto, Capital Políticos cree, se ha intensificado el problema, haciendo que cualquier diálogo normal imposible, reforzando los extremistas, y avivar la probabilidad de que los conflictos violentos.  
Además, los institutos de investigación cree que la amplia atención de los medios de comunicación nacionales e internacionales a las acciones de la Guardia húngara "ha dañado seriamente Hungría, la imagen internacional, sobre todo en cuanto a la creencia en la estabilidad del país y en la sofisticación de su democracia".  
Señalan que el aumento de la publicidad y el impulso dado a los grupos radicales y ðåîðãàíèçàöèþ de extrema derecha en Hungría empezando en el otoño de 2006 han sido parte de la razón por la que una serie de organizaciones llaman a sí mismos "nacional" autodefensa alianzas partida se han establecido en el verano de 2007.  
"La característica común de estos grupos es que no se autodenominan organizaciones cívicas mientras abiertamente declarar que se están preparando a sus miembros a la defensiva, incluida la gestión de catástrofes, armados tareas (Aludiendo, la defensa nacional, la aplicación de la ley), mientras que la declaración de que la policía y las fuerzas armadas, en otras palabras, el gobierno, resulta inapropiada para el papel," Capital Políticos añade.  
Señalaron que todas estas medidas se han hecho dentro de una configuración que depende de la sociedad y anti-political-party anti-politics humor para manto diferentes ambiciones políticas bajo el manto de acción cívica.  
En otras palabras, su insistencia en la naturaleza cívica de sus acciones y su elección de la asociación no son meramente como su forma de organización ruses a esquivar escollos legales para el registro en los tribunales, sino que también forman parte de una estrategia política.  
Según el análisis, la actividad de la Guardia húngara está acentuando el riesgo de dañar las relaciones con nuestros vecinos, también.  
"En los últimos meses de varios de los vecinos de Hungría han citado a la Guardia húngara como un potencial peligro. La ultranacionalistas podrían obligar a los actores políticos entre algunos de esos países vecinos se han referido a la creación de la Guardia húngara como argumento para justificar sus propias políticas antihúngaro.  
Todos estos factores que influyen en la estabilidad política de la región, "añade.  
La investigación instituto se observa que el establecimiento de la Guardia húngara no es un fenómeno único en la Europa central y oriental y, por lo tanto, se acentúa el riesgo político para toda la región.  
Se observa que el funcionamiento de la Guardia húngaro es similar al de la guardia nacional búlgaro, establecido en agosto de 2007 por la extrema derecha de la Unión Nacional búlgara. (BNU ).  
Serios conflictos que estalló entre romaníes como no en un distrito Sofía (Krasna Polyana ) estaban detrás de la creación de la guardia búlgaro.  
BNU se ha aprovechado de los disturbios para establecer la guardia, al afirmar que el objetivo de la organización era autodefensa "nacional".  
Señalaron que durante los últimos 17 años, Bulgaria había sido objeto de terror "gitano", en que el gobierno era impotente e indiferente, Capital Políticos nota.  
La iniciativa desencadenó acalorado debate entre la opinión pública búlgara, se añadió.  
Una señal de que el riesgo de un conflicto étnico ha aumentado, los analistas escribió, es que algunas organizaciones romaní en Bulgaria han anunciado planes para establecer un guardia de sus propios como una fuerza de resistencia.  
Desde la Guardia húngara hasta ahora ha actuado muy similar a la guardia nacional búlgaro, es muy posible que la comunidad romaní de Hungría podrían responder a la amenaza por organizar su propia defensa propia, escribió en riesgo la advertencia de Capital Políticos.  
Políticos gestor de investigación de Capital Atila Juhász respondió a un servicio de alambre húngara demanda de la MTI diciendo que el análisis fue uno de los institutos de investigación, el jefe de actividades.  
Cada año, dijo, publican análisis de riesgo, y si se descubre cualquier factor que pudiera alterar riesgos, que notificar a la opinión pública por publicar una advertencia de riesgo, como lo han hecho ahora.  
