Las esperanzas de que la Reserva Federal de reducir los tipos a conducir al mundo que marcaron un mercado de valores  
Shares saltó a ambos lados del Atlántico ayer mercado después de que se espera que la Reserva Federal va a tratar de calmar las condiciones de crédito con nuevas reducciones de los tipos de interés se han impulsado por tranquilizadores comentarios de los Estados Unidos vicepresidente del banco central.  
los mercados bursátiles crecido en Londres, Nueva York y en toda Europa después de Donald Kohn , nº 2 a Ben Bernanke, el presidente de la Reserva Federal, dijo que los estrategas políticos deben ser "flexibles y pragmáticos", en respuesta al estrés constante en los mercados financieros.  
En un esfuerzo claro para tranquilizar a los mercados fretful resurge en medio de signos de cepas de crédito, el Sr. Kohn dijo que la reciente turbulencia "se habían deshecho parcialmente algunas de las mejoras en el funcionamiento del mercado durante la década de parte de septiembre y en octubre de".  
Si la elevada turbulencias persistirán, aumentaría la posibilidad de un endurecimiento adicional en condiciones financieras para los hogares y las empresas, dijo.  
Los comentarios fueron tomadas por los inversores como una señal de que la Reserva Federal está dispuesta a paso en con nuevas inyecciones de capital en los mercados estadounidenses, y a otros posibles reducciones de los tipos de interés, para estabilizar las condiciones de crédito.  
Las observaciones también contribuyó a la calma Wall Street en medio de más malas noticias sobre la economía estadounidense, como las ventas de los hogares afectó a un récord bajos en octubre.  
Las consecuencias de las turbulencias financieras fue subrayado por un anuncio de Tengan Stearns , el banco de inversión, que se recortarán 650 puestos de trabajo, o 4 por ciento de su fuerza de trabajo global, en una ronda de ahorro para compensar pérdidas de su perdiendo confíe en el sector de los préstamos hipotecarios de las hipotecas de los Estados Unidos.  
Sólo el 20 de estos cargos se espera que ir en Londres, donde el banco emplea a 1.500 personas.  
En Nueva York, el promedio industrial Dow Jones saltó por 331 puntos, o 2.55 por ciento, cerrar en 13,289.40 calado, mientras que el índice S & P 500 aumentó el 65 por ciento.  
En Londres, el índice FTSE 100 aumentó 165.5 puntos, o un 2,7%, cerrar en 6,306.2 , añadiendo más de £39 mil millones para el valor de las empresas blue-chip de Gran Bretaña.  
Alemania aumentó el índice bursátil 2,6%, y CAC40 de Francia estaba 2,3 por ciento.  
Anteriormente, el estrés en los mercados reemergence de crédito fue puesto suficientemente en evidencia después de una fuerte demanda en una subasta de fondos de tres meses por el Banco Central Europeo vio prestado a los bancos comerciales de Europa en una fuerte 4,7 por ciento, la tasa más alta desde abril de 2001.  
La presión sobre el Banco de Inglaterra a seguir la Reserva Federal y el BCE e inyectar fondos adicionales en los mercados de dinero en Londres montado como vimos Libor cepas de crédito "de tres meses de los tipos de" para los préstamos entre bancos del Reino Unido presionó a su punto más alto desde finales de septiembre, en 6.59 por ciento, después de un constante escalar desde noviembre de 12.  
