EnvironMin seis por ciento de Hungría y  
Gábor ministra de Medio Ambiente, ha dicho que Fodor nivel profesional reuniones sobre cuestiones del clima internacional posterior a 2012 terminará el martes. La conferencia misma oficialmente abre el miércoles, cuando los ministros retomar el asunto.  
Los profesionales y políticos de 192 países están proyectadas para discutir la Bali Hoja de ruta que se centra en los esfuerzos para reducir las emisiones de gases de efecto invernadero posteriores a 2012, cuando expire el Protocolo de Kyoto.  
En la actualidad, las naciones en desarrollo y desarrollados son en medio de una gran controversia.  
Los Estados Unidos ha hecho saber que no está dispuesto a negociar cifras exactas, aunque no se opone a aceptar un recorte 25-40 por ciento de los gases de efecto invernadero en 2020, en comparación con los años 1990.  
El otro gran pregunta en la conferencia es si las naciones desarrolladas están preparados no sólo para reducir sus emisiones, sino también a ofrecer asistencia financiera y tecnológica a los países que lo necesitan.  
Un acuerdo alcanzado fue en el apoyo a las naciones en desarrollo.  
Un consejo 16-member lograrán la financiación de esta, que está fijado por el Protocolo de Kyoto, y lo más probable es que el trabajo dentro de las Naciones Unidas para el Medio Ambiente Mundial Facility (GEF ), escribe la publicación locales Piac és Lucro.  
seis por ciento de Hungría  
Representando Hungría. ministra de Medio Ambiente Gábor Fodor está dispuesta a apoyar los esfuerzos de la UE para conservar su papel en la protección del clima global insignia esfuerzo y promover un nuevo acuerdo internacional, que se alcanzó en 2009.  
Fodor observó que la UE tiene su mirada en un 20 por ciento de la caída en las emisiones de gases de efecto invernadero en 2020 en comparación con los niveles de 1990, si el "o" no se puede alcanzar un acuerdo posterior a 2012, y está dispuesta a los redujera por el 30 por ciento, si las otras grandes regiones desarrolladas del mundo y las naciones en desarrollo también están dispuestos a aceptar las obligaciones de la magnitud de sus capacidades y responsabilidades.  
Fodor decía en 1997, los países que se adhieren al Protocolo de Kyoto había focalizado un 5,2% de reducción de las emisiones globales. Dentro de ese grupo, la UE de 15 miembros acordaron un 8 por ciento de la decadencia.  
Hungría acordadas a reducir sus emisiones de gases de efecto invernadero por 6 por ciento en comparación con el 1985-1987 , un objetivo va a cumplir, dijo el ministerio de prensa del medio ambiente.  
Las apuestas en Bali son altas, para un acuerdo internacional a largo plazo sobre el clima política debe estar bajo la manta dentro de dos años o sin duda no serán capaces de entrar en vigor en 2012. Si ese tipo, las promesas hechas durante la validez del Protocolo de Kyoto no sería seguido inmediatamente por otro emissions-reduction régimen, la necesidad de que Nobel-Prize órgano científico ganador de la ONU, el Panel Intergubernamental sobre Cambio Climático, IPCC- ha señalado en su último informe.  
El resultado podría ser un retraso de las emisiones de reducción de la Tierra, lo que pondría en el camino hacia un aumento en la temperatura media superior a 2 grados centígrados. Si que esto suceda, los científicos decir las consecuencias serían graves e irreversible.  
