Asfalto UNAM evitaría baches
Rafael Herrera, un investigador de la Facultad de química de la UNAM, desarrolla asfalto modificado con polímeros para producir una mezcla con el mejor rendimiento, independientemente de las condiciones ambientales y la temperatura
Si las señales enviadas por la superficie de la carretera fueron atendidas, sería necesario para reparar unos 200 mil baches cada temporada de lluvias en la zona metropolitana del Valle de México, dijo Rafael Herrera Najera, un investigador en la Facultad de química (CF) de la UNAM, quien dijo si el proceso de construcción y mantenimiento de un pavimento de asfalto son adecuadas, los baches podrían ser reducidos o incluso completamente eliminados.
En su Conferencia vista tecnológico del bache, publicados en relación con el año internacional de química, anunció que el laboratorio que es responsable está desarrollando un asfalto de polímeros modificados para producir una mezcla con características similares en el asfalto, pero con una mejor resistencia mecánica, tanto en altas y bajas temperaturas.
Herrera Nájera dijo que este tipo de asfalto modificado podría ser usado en lugares donde el clima es extremadamente caluroso, como algunas ciudades en el norte, para mejorar su rendimiento y, por tanto, la formación de baches.
Explicó que el asfalto, la parte más pesada del petróleo es un conjunto de moléculas de hidrocarburos, algunos de alto peso molecular, llamado asphaltenes, y otro de bajo peso molecular, llamado maltenes, que juntos el camino de superficie su comportamiento característico de viscoelástica.
El comportamiento de viscoelástica del asfalto consiste en el hecho de que a altas temperaturas cerca de 180 grados, se comporta como un líquido a 120 ° C, su viscosidad es muy alta y a 50 grados Celsius tiene un estado casi sólido, mientras que a muy bajas temperaturas, el asfalto se convierte en frágil, dijo.
Esto significa que la resistencia del asfalto de la calle no es uniforme, pero se modifica durante el día de acuerdo a las condiciones ambientales y la temperatura, dijo el especialista en ingeniería química.
Investigador CF observó que las calles de la ciudad de México en su mayoría están cubiertas por pavimento flexible, que está compuesto de seis capas de materiales, de los cuales los tres últimos implican el asfalto.
Entre las capas más superficiales es el asfalto, compuesto de pequeñas piedras cruce en el asfalto y luego compactada.
Cada una de las piedras que componen esta cobertura, dijo, se cruce con asfalto.
Al conducir vehículos y generar esfuerzo, permite las fuerzas difundir muy bien sobre el pavimento.
Si se han modificado asfalto lo haría propagación aún mejor, dijo el ingeniero químico.
Sobre el asfalto cubriendo, agregó, se coloca una capa final llamada rodando cubriendo, que está hecha de un material de piedra fino, lo que significa arena también cruce en el asfalto.
Ya que es la capa que se pondrá en contacto con las ruedas del vehículo, debe tener una mejor resistencia mecánica que el recubrimiento de asfalto y proporcionar la fricción de la carretera.
Siendo parte del pavimento que recibirá y difundir los esfuerzos, la sucesiva cubriendo también requiere espesor adecuado y debe ser el material de que está hecho tomar en consideración.
El clima, especialmente variaciones de temperatura y humedad son también un factor muy importante a considerar, especialmente agua, dijo, porque afecta considerablemente el rendimiento del asfalto.
Cuando el terreno está húmedo, agua difunde dentro de la cobertura y es difícil salir, esta provocando una flexibilización de todas las capas del pavimento y, por tanto, la formación de baches.
En la formación de un bache, dijo, el primero en vestir es liar cubriendo y sólo después de está había afectado el asfalto, pero el daño no ocurrir instantáneamente, es un proceso que debe ser atendido en los primeros signos con programas apropiados de mantenimiento.
También un miembro del sistema nacional de investigadores explicó que la carga del vehículo es otro factor importante en la formación de baches y, por lo tanto, el espesor de cada capa del pavimento debe ser siempre hecho en relación con el vehículo de carga y garantizar este cumplimiento, a fin de evitar la frecuente formación de baches.
Rafael Herrera, dijo que todavía hay mucho que investigar y trabajar sobre el asfalto, por ejemplo, asfalto emulsiones, que en otros países ya están en el mercado y que incluso ayudar a reparar los baches con facilidad y sin utilizar altas temperaturas.
