Deben hacerse las contribuciones a las obras
Las obras sociales contempladas en los programas como hábitat, rescate de espacios públicos y 3 x 1 para riesgo de migrantes no completarse o tener graves retrasos debido a la falta de fondos, dijo Miguel Angel Lopez Miranda.
El Director de Desarrollo Social Municipal indicó que aunque hasta ahora han avanzado los programas de trabajo están en riesgo porque el Gobierno del Estado no ha podido hacer las contribuciones que corresponden, que representan un recurso superior a 11 millones de pesos en los tres programas.
Señaló que la inversión total en estos tres programas es de casi 50 millones de pesos, de los cuales el Estado tiene que contribuir con 25 por ciento y hasta el momento sólo la Federación y el municipio ha proporcionado recursos para las obras, por lo que el posible retraso en la terminación de estos está en vigor.
"Tienen que contribuir con casi 12 millones y aunque está terminando el año no nos han dado un centavo, desde el comienzo de julio tenían que darnos una parte", dijo, "a fin de no retrasar la hemos empezado las obras y están muy avanzadas, pero necesitamos el dinero".
Mencionó que el año pasado, durante la administración de Jesús Aguilar Padilla, el Estado no se ajustan las contribuciones que tenía que hacer, por lo que al comienzo de la administración de la municipalidad tuvo que pedir dinero prestado para cubrir más de 7 millones, una suma que no fue proporcionada en esa ocasión por la administración del Estado.
"Sucedió a nosotros en la anterior administración porque el Estado no tenía la capacidad financiera para participar y los programas siguió avanzando y este año a fin de acceder a estos programas que teníamos para obtener los recursos necesarios para cubrir lo que el Estado dejó pendiente," explicó.
Aunque hay un compromiso de las autoridades del Estado para cumplir con la entrega de estos recursos, dijo que la solicitud se hizo a la Secretaria de administración y finanzas, Armando Villarreal, para acelerar los esfuerzos para que los porcentajes que corresponden a ellos llegar lo más rápidamente posible.
"Tienen que contribuir con casi 12 millones y aunque está terminando el año no nos han dado un centavo".
