La adversidad climática desaceleración de la economía
Durante el primer año de gestión de Mario López Valdez, en Sinaloa aumentó el desempleo y la informalidad, extranjera disminuyó la inversión y la economía se redujo.
2011 es un año que será recordado en la historia económica de Sinaloa, también están relacionadas con el primer año de Gobierno de Mario López Valdez llamado el año del cambio, que genera grandes expectativas en cuanto al desarrollo de la economía, pero ante la adversidad climática del comienzo del año, no hubo ningún crecimiento, sin embargo había registrado una disminución en los principales indicadores de desarrollo económico.
Las bajas temperaturas de febrero, no sólo causan pérdidas de millones para el sector agrícola, sino limita las posibilidades de la economía del Estado para crecer, provocando una contracción de la actividad económica en general de 3,6 por ciento en el primer semestre del año, apoyado principalmente por la histórica caída del 31.16% en la agricultura, que afectó a la dinámica de otros sectores económicos.
Según el informe relativo a las zonas afectadas por las heladas, emitido por el Consejo Mexicano para el Desarrollo Rural Sostenible que fueron dañados 835.582 hectáreas, de las cuales 78.03% sufrieron daños totales y el resto de 21.07% tuvieron daños parciales. Los principales cultivos dañados fueron las verduras, maíz y garbanzos.
La caída en la actividad económica, hasta noviembre, ha generado un aumento constante del desempleo en el Estado, según el Instituto Nacional de Estadística y geografía, la tasa de desempleo estatal durante los tres primeros trimestres del año registró un crecimiento acelerado, de enero a marzo de Sinaloa 55.053 habitantes estaban desempleados, con una tasa de 4,53 por ciento de la población económicamente activa en el segundo trimestre, la tasa fue de 5.28 por ciento, y entre julio y septiembre el promedio siguió aumentando a 6.19 por ciento, una tasa que, en términos del número de personas, representa más de 74.000 de habitantes desempleados de Sinaloa, un aumento en comparación con la primera mitad de 18.969 individuos.
Menor liquidez
Desempleo en Sinaloa durante el año es multifactoriales, para el economista Gerardo López Cervantes, director de la Facultad de economía y ciencias sociales de la UAS, el crecimiento del desempleo se explica indirectamente, dependiendo de las medidas que ha adoptado la política pública.
"Ahora lo que estamos viendo es un aumento del desempleo que tiene con varios factores, incluyendo la pérdida de liquidez en el mercado con el fin de una restricción de recursos impuesta por la legislación que se aprobó en el Congreso a fin de combatir el blanqueo de dinero ya que para las personas que ilegalmente poseen dólares no es fácil trabajar con, invertir y utilizar en algo", dijo.
Inmigración detenida
Lopez Cervantes dijo que el aumento del desempleo también es un factor demográfico.
"El número de personas que deja el estado en busca de un trabajo en el extranjero, en los Estados Unidos ha sido restringido, en primer lugar debido a las dificultades para entrar, y segundo lugar porque una vez que entran ya tienen muchas dificultades para encontrar un trabajo, ese grupo de personas es quedarse y exigentes trabajos aquí, en el Estado, causando la tasa de desempleo aumentará, "dijo.
Informalidad
El análisis del mercado laboral de Sinaloa empeora cuando teniendo en cuenta el alto nivel de informalidad que prevalece entre las condiciones de trabajo, de acuerdo con INEGI, 60,38% de la población activa en los trabajos del Estado sin ser citado como trabajadores a cualquier institución de seguridad social.
Además del desempleo y la informalidad, otro recordatorio de mano de obra de Estado está representado por bajos salarios; la entidad tiene los salarios más bajos en el país, según los registros del Instituto Mexicano del Seguro Social y el Ministerio de trabajo y Previsión Social.
El ingreso promedio mensual de los trabajadores de Sinaloa fue, hasta septiembre, 5.352 pesos, muy por debajo de la media nacional, que es de 7.375 pesos.
Contracción de las inversiones extranjeras directas
Además de la caída en la actividad económica y la alta tasa de desempleo, en 2011 había registrado la mayor caída en inversión extranjera directa en los últimos 10 años, de acuerdo con el Ministerio de Hacienda desde enero a junio el estado IED totalizó 630.697 dólares, que representa una caída de 87.74% en comparación con los 5.143.312 dólares durante el mismo período del año pasado.
Por su parte, el Ministerio de desarrollo económico del Gobierno del estado representan una inversión total de 17.280.000 pesos durante el año, que se produjo principalmente en empresas del sector terciario.
Deuda
Contra el telón de fondo de la recesión económica, el Gobierno del Estado pidió en julio durante el Congreso del Estado, la aprobación de un crédito de 3 millones de pesos, que sería para la inversión en proyectos de infraestructura en 18 municipios, a fin de reactivar la economía, la aprobación del Congreso local fue para un total de 2.600 millones de pesos, y hasta noviembre no se observó ningún beneficio de la deuda en cualquier sector de la economía del Estado.
Reacciones
Para representantes de las empresas, el primer año de Gobierno de Mario López Valdés demuestra una falta de capacidad del Gobierno.
Miguel Loredo López, Presidente de la Cámara Nacional de industria transformación, dijo que durante el 2011 fue una falta de armonización de las voluntades de diversos sectores, incluyendo el propio Gobierno del Estado.
"El desempeño de la economía en Sinaloa este año ha sido realmente pobre, uno tiene que trabajar duro para recuperar el terreno perdido este año, en el 2012 debemos redoblar nuestros esfuerzos, hemos podido alinear los esfuerzos de todos y sobre todo la propuesta buena y sincronizada el nuevo equipo de Gobierno, esperamos que el próximo año será mucho mejor", dijo.
Lentitud económica
Lopez Loredo dijo que los eventos como las primeras heladas este año dejó la economía del Estado y su rendimiento y crecimiento fueron restringidos.
"El bajo flujo económico es el producto de varios eventos, incluyendo las heladas, uno de los principales efectos ha sido una economía lenta que hace no turno lo suficientemente rápido para generar un dinamismo económico que permite tener un nivel aceptable de flujo de los procesos, productos y servicios y por lo tanto, al final del año estamos cerrando lo debajo de nuestras expectativas"dijo.
Redefinición de la vocación
Teodoro Salazar Uriarte, Presidente de la patronal"Confederación de la República Mexicana en Sinaloa, dijo que el estado es necesario para procesar las actividades productivas más dinámicas.
"En general, encontramos que ha habido trabajando, creemos que es necesario desarrollar un programa de largo plazo que redefine la vocación y el curso económico del Estado, es importante detonar todo el material y recursos potenciales humanos que Sinaloa," dijo.
Trabajar para hacer
Presidente de COPARMEX destacó la importancia de establecer una visión de futuro para orientar mejor los esfuerzos del Gobierno.
"En general diría que el Gobierno ha sido tratando de ser exitosa en diversos campos, en términos de desarrollo económico hay algunos progresos, pero es importante desarrollar un programa a largo plazo," dijo.
Señaló que la actual administración ha mostrado progreso en su propia manera de dirigir la política pública.
"Hay elementos que nos permiten decir que el Gobierno es cada vez más incluyente, y lo que puedo decir es hay es trabajo y creo que el Gobierno es consciente de que hay trabajo por hacer", dijo.
