La Corte valida "transición de la televisión digital" en México en el año 2015
La sustitución de analógico a digital es uno de los cambios más importantes que ha golpeado el mundo en los últimos años
La Corte Suprema de Justicia (SCJ) rechazó las controversias constitucionales llevadas por el Senado y la cámara de representantes contra el decreto presidencial que lleva adelante la denominada "televisión digital transición" de 2021 a 2015, desde los ocho votos necesario para invalidarlo no obtuvieron.
Una minoría de cuatro ministros, incluido el Presidente de la Corte, Juan Silva Meza, consideró que el Presidente Felipe Calderón no excediera su autoridad mediante la emisión de un decreto que detalla las acciones a tomar a fin de lograr la transición a la televisión digital terrestre.
Con este resultado, la controversia constitucional promovida por el Senado, fue rechazado por no cumplir la mayoría de ocho votos de la Corte a pronunciarse sobre la constitucionalidad o inconstitucionalidad del decreto, y esto sigue en vigor.
El proyecto de sentencia elaborado por la Ministra Olga Sánchez Cordero, propuso declarar inconstitucional el decreto, porque el Reglamento de radio y televisión de materiales es una potencia reservada por ley a la Comisión Federal de telecomunicaciones (Cofetel), en violación de los principios de subordinación jerárquica y la ley de reserva.
Sólo Zaldivar, Jorge Mario Pardo, Margarita Luna y Sánchez Cordero votaron para el proyecto.
Con este argumento, el Senado y las controversias constitucionales de diputados promovió dos contradecir el decreto y para apoyar las reclamaciones, el Ministro Sánchez Cordero suspendió la aplicación del decreto y todas las acciones se establece sobre la transición digital.
En la "reunión de Ministros hay también decidió rechazar la reclamación presentada por la cámara de diputados, sin entrar en la discusión del proyecto, también a cargo de la Ministra Sánchez Cordero.
En su discurso, el Ministro dijo que no está de acuerdo con los argumentos del proyecto en el sentido de que el ejecutivo federal no estructura a través de normas generales las medidas para la administración pública obtener preparados.
"Ni lo considero que si afectaría la autonomía del órgano regulador," y recordó que la planificación de políticas públicas en áreas estratégicas como el sector de las telecomunicaciones corresponden al poder ejecutivo federal, que tiene un mandato constitucional, la orientación del Estado.
La sustitución de analógico a digital es uno de los más importantes cambios que han afectado el mundo en los últimos años y los resultados en una mejor utilización del espectro radio-eléctrico, mejor calidad de señal y más canales.
Retrasar el cambio, dijo, significaría retrasar los beneficios de la digitalización, que implica una decisión de interés público, que tiene no sólo una dimensión técnica, "que"cubre los aspectos económico, social, político y de seguridad nacional.
Estas cuestiones, dijo, "requieren la operación de todo el sistema establecido en virtud del principio de la administración económica del Estado, comprende un grupo de facultades que la Constitución conduce al poder ejecutivo del Estado".
Recordó que un gran número de países alrededor del mundo ha completado la transición digital y lo ha hecho a través del Ejecutivo, a pesar de tener altamente especializado organismos técnicos.
Allí no puede concluirse que el Gobierno, al emitir el decreto impugnado, que invade en modo alguno la competencia del Congreso, está ofreciendo en el área administrativa la observación de las leyes emitidas por la legislatura, dijo.
