La señora Sofía: "son instrumentos de progreso y esperanza"
La Reina destaca el lugar "dominante" en España en relación con este tipo de financiación
"España ha logrado un lugar destacado en el papel de microfinanciación mundial".
Reina Sofía recordó ayer que el país se ha convertido en las últimas dos décadas el segundo donante "en relación con los instrumentos de cooperación, cuya esencia" dijo radica en ser un "instrumento para el progreso social, justicia y la esperanza de un futuro mejor para toda la humanidad, basada en la confianza en los seres humanos".
La Reina inauguró ayer la quinta cumbre mundial microcréditos en Valladolid con la creencia de que "no hay duda" de que estas operaciones son "absolutamente esencial" para lograr los Objetivos del Milenio establecidos por las Naciones Unidas para 2015, y ", sobre todo teniendo como objetivo reducir a la mitad el volumen de personas que viven con menos de un dólar al día, con este" fijar el umbral de la pobreza ".
España es "siguen trabajando" para ampliar la red de beneficiarios en todo el mundo, y asume la tarea con "responsabilidad", dijo la señora Sofía, que esperaban que el esfuerzo y aportaciones se originó en la cumbre, que se celebrará hasta el jueves, va a "garantizar la creación de nuevas capacidades y mejores oportunidades para los más pobres, y especialmente para las mujeres", los principales beneficiarios de estos préstamos.
"Hay muchos logros" y "muchos desafíos a los que nos enfrentamos".
La cumbre de microcrédito no sólo se plantea como un foro de debate, pero también como una plataforma que promueve "dos objetivos básicos".
Así, Su Majestad explicó que espera que a finales de 2015, 175 millones de familias pobres se han accedido a estos servicios financieros y cien millones de esos hogares va a salir de la pobreza en la que están inmersos.
El impulso para la creación de micro créditos en España y en el resto del mundo "ha seguido el camino iniciado hace años" por Muhammad Yunus, puso de manifiesto la señora Sofía como un "acto de justicia y reconocimiento".
Y ella describió el padre de esta herramienta como un "admirable idealista de la causa universal de la lucha contra la pobreza", cuyo trabajo es conocido desde hace 15 años, cuando la Reina fue a Bangladesh para ver en el campo de la política de préstamos.
Esta experiencia ha sido seguida un año después de la primera cumbre mundial en Washington y otras reuniones como las celebradas en Costa de Marfil en 1999, Canadá 2006 ", y en todo lo que he visto la continua evolución", afirmó ayer Su Majestad, cuya vinculación con este proyecto que ha hecho su ganan el título de "El jefe de la familia" en Valladolid desde el "banquero de los pobres".
Por último, la reina la señora Sofía firmados por hacer participar a los presentes en el debate y encontrar soluciones para avanzar en la lucha contra la pobreza.
"imperativo ético"
El ministro de Asuntos Exteriores, Trinidad Jiménez, ha dicho que la solidaridad "es un imperativo ético" a cada Estado democrático.
En este sentido, dijo que sería un error de vincular la cooperación con los países en vías de desarrollo en tiempos de bonanza económica, ya que es una obligación "constante".
Jimenez determinó que supone "una política seria y rigurosa de microcréditos dedicadas a la erradicación de la pobreza", y ahora más que nunca "", los gobiernos de los países desarrollados deben trabajar bajo los criterios de solidaridad y no dejar que esta caída como víctimas de ajustes.
Para España, microcrédito es "una de las principales líneas de cooperación al desarrollo".
El secretario de Estado de Cooperación Internacional, Soraya Rodríguez, alabó el "éxito" para dar "confianza" a personas "descarta" a quien todas las puertas están cerradas, y el alcalde de Valladolid, Francisco Javier León de la Riva, dio la bienvenida a los presentes que una ciudad que "abre sus puertas atrapada por el espíritu de solidaridad".
