"El Tribunal valida" transición a la televisión digital en México en 2015
La sustitución de analógica a digital es uno de los cambios más importantes que ha afectado al mundo en los últimos años
El Tribunal Supremo de Justicia (SCJ) rechazó las controversias constitucionales presentado por el Senado y la Cámara de Representantes contra el decreto presidencial que adelanta la llamada "transición a la televisión digital" de 2021 para 2015, desde los ocho votos necesarios para invalidar que no han obtenido.
Una minoría de cuatro ministros, incluido el presidente de la Corte, Juan Silva Meza, consideró que el presidente Felipe Calderon no exceder su autoridad al emitir un decreto sobre las medidas a adoptar para lograr la transición a la televisión digital terrestre.
Con este resultado, la controversia constitucional promovida por el Senado, fue rechazado por no cumplir la mayoría cualificada de ocho votos para el Tribunal unconstitutionality o para pronunciarse sobre la constitucionalidad del decreto, y esto sigue en vigor.
El proyecto de sentencia elaborado por la ministra Olga Sánchez Cordero, propuesto para declarar inconstitucional el decreto material, porque el reglamento de radio y televisión es un poder reservada por ley a la Comisión Federal de Telecomunicaciones (Cofetel), en violación de los principios de subordinación jerárquica y reserva de ley.
Sólo ella la Zaldivar, Jorge Mario Pardo, Margarita Luna y Sánchez Cordero votado a favor del proyecto.
Con este argumento, el Senado y la Cámara de Diputados promovido dos controversias constitucionales que contradicen el decreto, y que apoye las demandas, la ministra Sánchez Cordero suspende la aplicación del decreto y todas las acciones establecidas allí para la transición digital.
En la reunión de ministros "también había decidido rechazar la queja presentada por la Cámara de Diputados, sin entrar en la discusión del proyecto, también a cargo de la ministra Sánchez Cordero.
En su intervención, el ministro ha dicho que no estaba de acuerdo con los argumentos del proyecto en el sentido de que el Ejecutivo federal no puede estructura a través de normas generales las medidas de la administración pública para llegar preparados.
"Tampoco creo que si afectaría a la autonomía del organismo regulador", y recordó que la planificación estratégica de las políticas públicas en ámbitos como el sector de las telecomunicaciones se corresponde con el Ejecutivo federal, que tiene un mandato constitucional, la dirección del Estado.
La sustitución de analógica a la digital es uno de los cambios más importantes que han asolado el mundo en los últimos años, y se traduce en una mejor utilización de los radio-electric espectro, una mejor calidad de señal y más canales.
Retrasar el cambio, dijo, supondría retrasar la decisión de beneficios de digitization, que implica un interés público, que no solo tiene una dimensión técnica ", ya que abarca cuestiones económicas, sociales, políticos y de seguridad nacional".
Estas cuestiones, ha dicho, "requieren el funcionamiento de todo el sistema establecido desde el principio de la administración económica estatal, comprende un grupo de potencias que conduce a la Constitución el Poder Ejecutivo Estatal".
Ha recordado que un gran número de países de todo el mundo ha completado la transición digital, y lo ha hecho por el Ejecutivo, a pesar de tener organismos técnicos altamente especializados.
No puede haber llegó a la conclusión de que el gobierno, al emitir el decreto impugnado, que invade las competencias del Congreso, en modo alguno es ofrecer en el ámbito administrativo de la observación de las leyes dictadas por el Legislativo, dijo.
