Apoyar a los trabajadores "Unión va a demandar ciudad sobre los despidos
La escuela de unión que representan cientos de apoyar a los trabajadores que han perdido sus puestos de trabajo el mes pasado planes para demandar a la ciudad el miércoles, argumentando que los despidos eran innecesarias y discriminatorio debido a su impacto desproporcionado en escuelas que sirven a estudiantes pobres.
La acción legal es posiblemente la última arma disponibles para la Unión, consejo de distrito 37, en su esfuerzo para revertir los despidos.
Seiscientos asesores escuela 72, de padre coordinadores y otros empleados que estaban entre los peor pagados de la ciudad perdieron sus puestos de trabajo a PTU. 7, en una decisión política de los líderes de la Unión han descrito como venganza por su rechazo a que la ciudad acceso un fondo de asistencia sanitaria dirigido por grupos de cerrar su brecha presupuestaria de mano de obra de la pasada primavera.
Funcionarios de la ciudad han negado categóricamente esta acusación.
En un Ayuntamiento audiencia el mes pasado, las escuelas la canciller Dennis M. Walcott dijo que los despidos fueron una parte del presupuesto se firmado en junio.
Un miembro del Consejo disparó atrás, recordándole que nada en el presupuesto especificó que personal de apoyo escolar diputados sería despedido.
Consejo de distrito 37 funcionarios dijeron que presentó un aviso de alerta afirman, el Departamento de Educación que sería demandó; el miércoles se celebrará una conferencia de prensa para anunciar la acción legal de presentación, formalmente en la Corte Suprema estatal en Manhattan.
La lista de traje, señor Walcott y el departamento de Educación de la ciudad como acusados, y cuenta ocho trabajadores despedidos como demandantes, todas las mujeres de negro o latino, al igual que la mayoría de los visitantes que han perdido sus puestos de trabajo.
Elizabeth Thomas, un portavoz del Departamento de Derecho de la ciudad, dijo que la ciudad no había visto la acción legal y, por lo tanto, no podía hacer comentarios sobre sus acusaciones específicas.
Según un borrador de la queja obtenidos por el New York Times, la Unión ha zeroed en sobre el número de despidos en las escuelas en regiones pobres de la ciudad para apoyar una acusación de trato desigual, diciendo escuelas pobres perdieron más asesores porque habían sido permanentemente de suficiente financiación.
Señala que, si bien no ha habido despidos en Staten Isla y pocos los despidos en las escuelas en la Escuela Superior de Oriente Medio o Tribeca, 17 visitantes perdieron sus puestos de trabajo en el distrito 23 en Brownsville, Brooklyn y 46 se les van en distritos 8 y 9 en el sur Bronx.
Observar la pérdida de cinco de ocho colaboradores escolares que trabajan por la escuela pública 36 en Harlem, donde el 68% de los estudiantes que viven en la pobreza, el pleito dice, "no se trata de un barrio de que los padres que pueden fund-raise para compensar el déficit presupuestario".
P.S. 36 partidas presupuestarias se redujo un 3,26% este año, y que también perdió dinero cuando la ciudad cambió la forma en que se calcula la financiación adicional para cada estudiante escuelas a pobres.
La unión también afirma que la escuela secundaria directivos pueden haber sido engañados por la lengua en un memorándum autoriza el despido de coordinadores matriz.
El memorándum usó la palabra "exceso" para describir la acción, aunque "exceso" más comúnmente describe el acto de la nómina de trasladar a un profesor de una escuela en una reserva de trabajadores cuyos sueldos son pagados por la oficina central disponibles.
"Sesenta y seis coordinadores fueron despedidos matriz", dice el proyecto de queja, "y no sólo excessed".
