Mujica viaja a México para reforzar los lazos políticos
Una delegación encabezada por el presidente José Mujica uruguayan oficial, y compuesta por varios ministros y empresarios, se iniciará este martes una visita a México para expandir el comercio entre los dos países y abordar cuestiones políticas en la región.
Mujica se reunirán el próximo miércoles su igualdad mexicano, Felipe Calderon, el punto culminante de una amplia agenda de reuniones con autoridades políticas, comerciales y una reunión con la comunidad de uruguayans que viven en México, según el calendario publicado por la presidencia uruguayan.
La reunión entre ambos presidentes, en la ciudad de Guadalajara, "será favorable para el intercambio de información en cuanto a las cuestiones políticas entre las dos naciones", tal y como lo publicó la Presidencia del país sudamericano en su sitio web.
Según los medios de comunicación locales, Mujica intenta conseguir el apoyo de Calderon a Uruguay en el incidente con Francia que surgió cuando el presidente francés, Nicolas Sarkozy, incluido el país sudamericano en una lista de paraísos fiscales en la reunión del G20 en la ciudad francesa de Cannes.
En su intervención, Sarkozy ha amenazado con excluir de la comunidad internacional a los países que siguen siendo paraísos fiscales, una declaración que provocó el rechazo de Uruguay y el llamado a consultas de su embajador en el país europeo.
México preside desde noviembre, el G20, un grupo compuesto por los países desarrollados y emergentes más poderosos del mundo, y en efecto con el país sudamericano desde enero de este año, un acuerdo de intercambio de información con el fin de evitar la doble imposición fiscal.
El Gobierno uruguayan ha intentado en los últimos años para acelerar la conclusión de acuerdos de intercambio de impuestos para salir de la "lista gris" de la Organización para la Cooperación y el Desarrollo Económicos (OCDE), compuesta por países que no apliquen todas las normas internacionales de cooperación en materia fiscal.
Sobre el plan de Comercio, México y Uruguay en vigor desde 2004 un acuerdo de libre comercio (TLC) que ha aumentado el intercambio de mercancías entre ambos países.
