La asociación UDF levanta el tono y advierte al Nuevo Centro sobre el uso de su sigla
La asociación UDF (Unión para la Democracia Francesa), controlada por el MoDem (Movimiento Democrático) de François Bayrou, reaccionó este viernes ante el intento del presidente del Nuevo Centro, Hervé Morin, de lanzar una OPA (Oferta Pública de Adquisición) sobre la sigla del ex partido giscardista, intimándole a retirarla de todo soporte, so pena de ser demandado.
Hervé Morin anunció públicamente su intención de recuperar la sigla UDF, ya que considera que François Bayrou no estaba en posición de defender su herencia política tras haberle tendido la mano a la izquierda.
Por otra parte, el Ministro de Defensa, cuyo partido está asociado a la UMP, había previsto confirmar la estrategia el sábado ante el Consejo Nacional del NC.
Como apoyo a su gestión, recibió la ayuda del diputado Hervé de Charette (ex UMP, actual NC) quien reivindica la propiedad de la marca UDF, pues fue el primero en registrarla en el Instituto Nacional de Propiedad Industrial en 2004.
Pero el viernes por la noche, la oficina de la asociación UDF, controlada por los amigos de François Bayrou que no quieren verse privados de ésta, rompió el silencio para lanzar un requerimiento al Ministro y al diputado intimándolos a renunciar a la sigla y a transferirles los derechos de propiedad de la marca, so pena de demanda judicial.
Estos últimos días, ustedes han hecho muchas declaraciones insinuando que iban a proponer a su movimiento político recuperar la sigla UDF, escribe la asociación en un carta firmada por 19 de los 24 miembros de la oficina, incluyendo a François Bayrou y a Marielle de Sarnez del MoDem, como también al senador Jean Athuis de la Alianza Centrista.
También creen correcto continuar con el uso del nombre del movimiento, el +Nouveau centre+, y del slogan +l'UDF d'aujourd'hui+ en su material militante y en la página de presentación de su sitio, sostienen los firmantes de la carta.
Como ya lo saben, no tienen ningún derecho a utilizar la sigla, explica la oficina de la UDF que exige que el NC retire "inmediatamente la mención del nombre de la UDF de todo soporte, como también de (su) sitio de Internet".
También pide a Hervé de Charette "que transfiera la propiedad de (la) marca a los legítimos derechohabientes".
De no hacerlo, se apelará a la justicia para hacer respetar la ley y los derechos legítimos de los miembros de la UDF, advierten los firmantes.
En la carta, precisan que la UDF "es un verdadero movimiento político desde 1978" y recuerdan que Morin y sus amigos "eligieron" irse en 2007 "para crear un nuevo partido, como ya lo habían hecho otros en 2002 para crear la UMP".
Por lo tanto, el Nuevo Centro no tiene, según ellos, ningún derecho a utilizar la sigla UDF.
Asimismo recuerdan que el último congreso de la UDF votó en 2007 su adhesión al MoDem por tres años y la creación de una oficina encargada de defender "los intereses materiales y morales" del movimiento fundado por Valéry Giscard d'Estaing.
En cuanto a Hervé de Charette, prosigue la oficina, "cuando registró la marca", ya no era "miembro de la UDF desde hacía tres años", sino de la UMP.
Aprovecha de forma escandalosa y fraudulenta la ausencia de registro del acrónimo UDF para realizarlo por su cuenta.
Esta indiscreción se está transformando en delito, denuncian, antes de burlarse de la estrategia del NC: "Creemos que en política, como en la vida, es más digno hacerse su propio nombre que intentar salir del anonimato tomando de manera fraudulenta un nombre al que no se tiene derecho".
