Un grupo de la ONU esboza un plan para reducir las emisiones
La conferencia sobre el clima patrocinada por la ONU, caracterizada hasta ahora por posturas desafiantes y recriminaciones mutuas, captó una renovada atención el viernes con la divulgación de un documento que prevé ambiciosas reducciones de los gases de efecto invernadero durante los próximos 40 años, con las naciones industrializadas que llevan sobre sus hombros la mayor parte de la carga en el corto plazo.
El texto, que podría proporcionar la base para un acuerdo político final para regular los gases de efecto invernadero, destacó los obstáculos restantes y destacó el camino a seguir.
Pero se vio como un avance importante en una negociación que se está quedando sin tiempo, con más de 100 líderes mundiales que llegarán a Copenhague la próxima semana.
Elaborado por un grupo de trabajo ad hoc de la ONU, el texto no habla de cuánto dinero le darían los países ricos a los pobres para enfrentarse al calentamiento global a corto y largo plazo.
Y esto ofrece una variedad de opciones para las preguntas claves, que incluyen cómo las economías desarrolladas y las principales economías emergentes recortarían su producción de carbón, y cuál sería el límite del aumento global de la temperatura que los estrategas políticos estarían dispuestos a tolerar.
Esto le da mucha flexibilidad al proceso, dijo John Coequyt, alto representante en Washington para el Sierra Club.
Michael Zammit Cutajar, que redactó el documento de seis páginas, resumió un texto de negociación de 180 páginas para concentrarse en lo que el máximo funcionario climático de la ONU, Yvo de Bóer, describió como "el gran panorama."
Muestra los perfiles para un posible acuerdo, en el cual las naciones industrializadas recortarían colectivamente sus emisiones para 2020 entre un 25 y un 45 por ciento, en comparación con los niveles de 1990, mientras que los principales países en desarrollo reducirían las suyas durante el mismo período entre un 15 y un 30 por ciento.
Juntos, los países recortarían las emisiones entre un 50 y un 95 por ciento hacia 2050.
La Unión Europea también estimuló las conversaciones el viernes, prometiendo proporcionar 3.600 millones de dólares anuales durante los próximos tres años, para ayudar a los países más pobres a adaptarse al impacto del cambio climático, desde las inundaciones y sequías hasta la deforestación.
De todos modos, el viernes se presentó la misma clase de fuegos artificiales verbales que han dominado las conversaciones la semana pasada.
El enviado climático especial de Estados Unidos, Todd Stern, rechazó las afirmaciones que solicitan recortes obligatorios de emisiones de gases de efecto invernadero para los países industrializados, en comparación con los voluntarios de parte de las economías emergentes principales, si no fueran financiados por el mundo desarrollado.
La maniobra indicó que la administración Obama está adoptando una línea más dura con China, con respecto a lo que hicieron los funcionarios de la administración Bush hace sólo dos años.
Los Estados Unidos no van a hacer un acuerdo sin que los principales países en vías de desarrollo avancen y tomen medidas, manifestó Stern, quién también lamentó que el texto no hizo lo suficiente para asegurar que los recortes podrían ser verificados por observadores externos.
Stern hizo sus comentarios una hora después de que el vice Ministro de Asuntos Exteriores chino He Yafei, afirmara que el máximo negociador climático de Estados Unidos carecía de "sentido común", o era " muy irresponsable" por haber dicho antes en la semana que los Estados Unidos no ayudarían a China económicamente a enfrentarse con el recalentamiento global.
Con la futura trayectoria económica de las principales potencias del mundo en juego, las líneas de falla han hecho erupción tanto dentro del mundo en vías de desarrollo, como entre el mundo industrial y las economías emergentes.
La actual batalla es tanto para salvar las economías individuales como para salvar al planeta, con China y los Estados Unidos enfrentándose sobre sus respectivas obligaciones, mientras las naciones más pobres insisten en que los veinticuatro países del mundo más influyentes están ignorando el imperativo científico para tomar la acción más valiente.
Ricardo Ulate, un delegado de Costa Rica, dijo que no es sorprendente que las principales potencias estén discutiendo sobre quién debería costear los gastos para limitar los gases de efecto invernadero, aún cuando los países vulnerables se han vuelto más agresivos buscando contener a los grandes emisores responsables de sus acciones.
Esto es claramente un juego donde se está desarrollando una nueva hegemonía económica, sostuvo Ulate, quien también trabaja como consejero regional sobre cambio climático de México y América Central, para Conservación Internacional.
Algunos de los países más vulnerables al impacto del cambio climático indicaron que seguirían presionando para un tratado legalmente obligatorio en Copenhague, aunque la mayoría de los principales participantes digan que las conversaciones producirán a lo sumo un acuerdo político.
La Alianza de Pequeños Estados Insulares, que cuenta con 43 miembros, elaboró una propuesta de tratado preliminar de 24 páginas temprano en la mañana del viernes.
Artur Runge-Metzger, que encabeza negociaciones climáticas internacionales en nombre de la Comisión europea, dijo que el empuje de las pequeñas naciones insulares ha "metido presión política sobre el proceso político entero," en parte porque ahora están unificados y exigen la acción de las economías emergentes, tales como China e India.
Las conversaciones asumieron una nueva urgencia mientras los delegados se enfocaban en el hecho de que deben resolver la mayoría de las cuestiones excepcionales antes de que los jefes de gobierno lleguen a cerrar un trato.
Los funcionarios de alto nivel, como el ministro de Medio Ambiente indio Jairam Ramesh y el vice ministro chino, descendieron de los aviones y corrieron hacia los pasillos del Bella Center, a reuniones a puertas cerradas y conferencias de prensa, para poder delimitar los reclamos que se arbitrarán durante la próxima semana.
El absoluto desorden de la reunión (donde cada día 13.000 personas entran y salen del centro de convención, los activistas que tocan la guitarra presentan espectáculos nocturnos burlándose de los países que según ellos se están vendiendo, y se pasan propuestas preliminares de mano en mano en vez de vía mail), plantea un desafío.
La intensidad sólo construye: casi todos los ministros clave están aquí en este momento, y el miércoles 60 jefes de gobierno estarán en Copenhague.
Estamos entrando en las ligas mayores, dijo Carlos Manuel Rodríguez, vicepresidente para la política global de Conservación Internacional.
Los pesos pesados están llegando.
