Atenas se retroalimenta las dudas
Papademos dijo que los ajustes serán aprobados, pero los conservadores no firmará ningún compromiso por escrito
Con los subsidios periféricos de riesgo y la incertidumbre en marcha reintegrado en los parques, Grecia sigue enredado en el laberinto que conduce a la salida de la crisis de la deuda europea grande.
La sensación de que el &quot;consentimiento&quot; del nuevo gobierno de transición de Helena viene impuesta más por las exigencias de Bruselas, que por una convicción genuina de las fuerzas políticas comenzaron a ser confirmada por los hechos.
Mientras que el nuevo primer ministro, Lukas Papademos, advirtió ayer que no hay alternativa a las reformas estructurales y que el plazo de cien días acordados en su nombramiento puede ser subestimado para la aplicación de ellos, el líder del partido conservador Nueva Democracia, Antonis Samaras, aseguró que no va a apoyar nuevas medidas de austeridad en todo caso, y reiteró su exigencia de nuevas elecciones programadas para el 19 de febrero.
&quot;La principal tarea de este Gobierno está poniendo en práctica las decisiones de la cumbre del 26 de octubre&quot;, dijo Papademos ayer, cuando la apertura de un debate parlamentario que culminará mañana con un voto de confianza al nuevo Ejecutivo.
Un paquete de 24 programas para fomentar el empleo, la reforma del código disciplinario de los funcionarios públicos y las nuevas medidas contra la evasión fiscal serán las primeras iniciativas.
Sin embargo, el mensaje de Samaras no borra las dudas sobre su posición: &quot;Estamos comprometidos a ayudar al gobierno de transición, pero no se han comprometido a nada&quot;.
El líder conservador fue un paso más en su pulso a la UE y el FMI, las entidades que deben descongelar los 8.000 millones que Atenas necesita con urgencia, y dejó claro que no dará su aprobación a cualquier carta de compromiso para cumplir con la ajustes.
Sin embargo, la Comisión Europea, sigue teniendo una dermatitis del pañal por el impacto causado por la declaración de todo o nada del referéndum Papandreu, reiteró ayer que su demanda es clara: no va a desbloquear la ayuda si el nuevo Gobierno y los líderes de los helenos principales partidos no firmar &quot;un compromiso por escrito, sin ambigüedad y tan pronto como sea posible.&quot;
El portavoz de Asuntos Económicos, Amadeu Altafaj, dijo que los inspectores de la troika volvería &quot;muy pronto&quot; a Atenas para discutir con el nuevo gobierno &quot;lo que hay que hacer para pagar el sexto tramo&quot; de 8.000 millones de dólares, aunque no hay fecha definitiva.
La madeja griega todavía tiene un hilo por el momento.
