Anti-musulmanes los delitos han aumentado en un 50%
Entre 2009 y 2010, anti-musulmanes los delitos aumentan en casi un 50%, mientras que durante el mismo período otras formas de violencia racial y religiosa había caído un poco, o no había cambiado, de acuerdo con estadísticas del FBI publicados el lunes.
De acuerdo con estas cifras, el número total de casos de violencia contra los musulmanes pasó de 107 en 2009 a 160 en 2010, lo que equivale a un aumento del 49%, frente a un aumento del 13% de los casos de violencia contra los católicos, una caída de 4 % de los ataques contra Judios y un aumento global del 14% en los delitos contra la religión.
El número total de crímenes de odio aumentó muy ligeramente a 6 628 casos, de los cuales 47,3% fueron motivadas por las diferencias raciales y el 20% de las diferencias religiosas, de acuerdo con el FBI.
&quot;Después de una disminución en el año 2009, es preocupante ver a estos crímenes cada vez más, hizo hincapié en los derechos de organización del hombre, Human Rights First,&quot; el aumento de los casos de anti-musulmana la violencia es particularmente importante &quot;, ha añadido la organización en un comunicado.
&quot;Human Rights First hace mucho hincapié en que los actos de violencia contra los musulmanes, así como todas las formas de crimen de odio, debe ser considerado como violaciónes graves de los derechos humanos&quot;, explicó uno de los directivos de la organización, Pablo Legendre.
&quot;El gobierno de Estados Unidos puede y debe hacer más para hacer frente a su abuso, añade, considerando que esto podría deberse a la edición de los informes policiales sobre crímenes de odio.&quot;
&quot;Crimen de odio&quot; en la ley federal, es un legado de la época de la lucha por los derechos civiles.
Esta legislación fue aprobada después de la muerte de Martin Luther King para castigar los actos de violencia relacionados con la raza, color de piel, religión, origen y orientación sexual, ahora.
