Mujica viaja a México para fortalecer los lazos políticos
Una delegación oficial encabezada por el presidente uruguayo, José Mujica, e integrada por varios ministros y hombres de negocios, se iniciará este martes una visita a México con el fin de ampliar el comercio entre los dos países y abordar temas políticos en la región.
Mujica se reunirá el próximo miércoles que su equivalente mexicano, Felipe Calderón, el punto más alto de una extensa agenda de reuniones con autoridades políticas, comerciales y una reunión con la comunidad de uruguayos residentes en México, según el calendario publicado por la Presidencia uruguaya.
El encuentro entre ambos presidentes, en la ciudad de Guadalajara, será &quot;favorable para el intercambio de información con respecto a las cuestiones políticas entre las dos naciones&quot;, que se publica la Presidencia del país sudamericano en su página web.
De acuerdo con los medios de comunicación locales, Mujica busca obtener el apoyo de Calderón para el Uruguay en el incidente con Francia, que surgió cuando el presidente francés, Nicolas Sarkozy, incluido el país sudamericano en una lista de paraísos fiscales en la reunión del G-20 en la ciudad francesa de Cannes.
En su discurso, Sarkozy amenazó con excluir de la comunidad internacional a los países que siguen siendo los paraísos fiscales, una declaración que provocó el rechazo de Uruguay y la llamada a consultas de su embajador en el país europeo.
México preside desde noviembre, el G-20, un grupo compuesto por los países más poderosos del mundo, desarrollados y emergentes, y tiene en vigor con el país sudamericano desde enero de este año, un acuerdo para intercambiar información tributaria con el fin de evitar la doble imposición.
El gobierno uruguayo ha intentado en los últimos años para acelerar la conclusión del régimen del impuesto sobre el intercambio con el fin de salir de la &quot;lista gris&quot; de la Organización para la Cooperación y el Desarrollo Económico (OCDE), integrada por países que no apliquen todas las normas internacionales de impuestos la cooperación.
En el plano comercial, México y Uruguay tienen en vigor desde 2004 un Tratado de Libre Comercio (TLC) que ha aumentado el intercambio de bienes entre ambos países.
