Los delitos antimusulmanes han aumentado en el 50%
Entre 2009 y 2010, los delitos antimusulmanes aumentan en casi un 50%, mientras en el mismo período otras formas de violencia racial y religiosa se habían caído ligeramente o no habían cambiado, según las estadísticas del FBI publicada el lunes.
Según estas cifras, el número total de casos de violencia contra Musulmanes pasó de 107 en 2009 a 160 en 2010, igual a un aumento del 49%, en comparación con un aumento del 13% de casos de violencia contra católicos, una caída del 4% de ataques contra judíos y un aumento global del 14% en delitos antireligiosos.
El número global de crímenes de odio aumentó muy ligeramente a 6 628 casos, de los cuales el 47,3% fue motivado por diferencias raciales y el 20% por diferencias religiosas, según el FBI.
"Después de una disminución en 2009, es inquietante para ver estos delitos aumentar otra vez, acentuó los derechos de la organización del hombre, Derechos humanos Primero, "el aumento de los casos de violencia antimusulmana es particularmente significativo," añadió la organización en un comunicado.
"Los derechos humanos Primero han subrayado mucho tiempo que los actos de violencia contra Musulmanes, así como todas las formas del delito de odio, se deben considerar como graves violaciones de los derechos humanos," añade uno de los directivos de la organización, Paul Legendre.
"El gobierno americano puede y debe hacer más para hacer frente a su abuso, él añade, juzgando que esto podría deberse a la edición de informes de policía sobre delitos de odio."
"Delito de odio" en la Ley federal, es un legado en el período de lucha por los derechos civiles.
Esta legislación se pasó después de la muerte de Martin Luther King para castigar actos de violencia relacionada a raza, color de la piel, religión, origen y ahora orientación sexual.
