Las "personas enojadas" desafían las autoridades de Nueva York
Cientos de protestantes se apiñaban por ahí delante de Zuccotti square para acampar.
Una parte de los manifestantes escuchó el orden de desahucio y se movió a un parque cercano.
Los miembros del movimiento Ocupan Wall Street desafiada el martes las autoridades de Nueva York tratando de entrar otra vez, bajo la protección de una orden judicial, en la Plaza de Manhattan donde se evacuaron al amanecer tratando de ocupar otro parque de la Gran manzana.
Cientos de protestantes se apiñaron alrededor de Zuccotti square, donde ellos quisieron entrar gracias a una orden judicial que permite "que las personas enojadas" pongan el sitio de espera, mientras otra parte del movimiento respondió al desahucio ocupando un parque al norte la ciudad en los casos en que cabe han hecho detenciones adicionales.
"Nuestra idea es que si el tribunal no permite que nosotros volvamos para acampar en la plaza, acamparemos en otra parte y seguiremos la batalla legal para volver a Zuccotti, y a través de sentadas pacíficas y demostraciones," dijo uno de los portavoces del movimiento "Ocupa la Wall Street," Mark Bray.
El rebuzno explicó que la respuesta de las "personas enojadas" a la evacuación del campo publicado personalmente por el alcalde de Nueva York, Michael Bloomberg, vino al tribunal, donde el juez Lucy Billings publicó una orden que prohíbe la evacuación forzada de los lugares y permitiendo a los manifestantes permanecer acampó.
Además, las "personas enojadas" siguieron a la ocupación de un nuevo parque situado en la confluencia del centro de la ciudad. Canal Street y Avenida 6, cerca de la entrada al Túnel de Holanda, que une Nueva York y Nueva Jersey, propiedad de la parroquia de la iglesia de la Trinidad.
Al menos durante una hora ellos eran capaces de ocupar el lugar, pero entonces la policía vino y se ha puesto a detener a algunos protestantes, aunque el Rebuzno no pudiera confirmar el número preciso, diciendo a Efe que él vio a varios periodistas que también se esposaron.
La organización asegura que haya varios cientos de personas acampados a ese punto, donde una delegación de líderes religiosos ya ha ido para mostrar su apoyo a los miembros del movimiento que trata de mediar con la policía.
Mientras tanto, Zuccotti square, que es un sitio privado, permanece la espera cerrada de una audiencia del tribunal programada para este martes en el que examinar la legalidad de la evacuación de esta mañana.
Algunos protestantes movidos allí llevaban y distribuían entonces copias de esa orden judicial y hasta ellos dieron estas copias a oficiales que protegen el lugar, que llevó "a algunas pequeñas confrontaciones," dijo el Rebuzno, quien afirmó que algunos oficiales pegados los demostradores.
La orden judicial prohíbe las autoridades para evacuar a los miembros de Ocupan Wall Street y hacen cumplir "leyes que se publicaron después del inicio de la ocupación o prohibir a demostradores recobran el acceso al parque con tiendas y otra propiedad usada antes."
El alcalde Bloomberg dijo a reporteros que, debido a esa orden judicial, la ciudad había suspendido la reapertura del lugar público y los protestantes se informaron, sin embargo, que las leyes locales no permiten que ellos instalen de nuevo con tiendas que acampan y sacos de dormir.
El concejal personalmente defendió la evacuación de Zuccotti square realizada al amanecer, una operación en la cual aproximadamente 200 detenciones se hicieron y esto se decidió por tanto porque los protestantes "violaban la ley."
Bloomberg dijo lo que dio orden de evacuar la plaza porque se hacía "un lugar donde la gente no vino a la protesta, pero violar la ley y, en algunos casos, hacer el daño a otros" como "Algunos negocios había recibido las amenazas y los vecinos temieron" por la calidad de vida."
"La evacuación de esta mañana ha sido asquerosa y demuestra que profundamente dentro de Bloomberg más se interesa en la conservación de los intereses financieros de trabajadores americanos," añadió el portavoz del movimiento, que acusó al alcalde "del desacato para la libertad de expresión."
Los responsables de "Ocupan la Wall Street" también indicó que ellos tienen la intención de organizar "grandes hechos" el jueves en la colaboración con las organizaciones de la comunidad y uniones, a fin de conmemorar los últimos dos meses de protestas, que comenzaron el 17 de septiembre.
