El tribunal valida "la transición de televisión digital" en México en 2015
El reemplazo de análogo con el digital es uno de los cambios más importantes que ha golpeado a el mundo en los últimos años
La Corte Suprema de Justicia (SCJ) rechazó las controversias constitucionales aportadas por el Senado y Cámara de Representantes contra el decreto presidencial que presenta la llamada "transición de televisión digital" de 2021 a 2015, ya que los ocho votos lo tenían que invalidar no se obtuvieron.
Una minoría de cuatro ministros, incluido el Presidente del Tribunal, Juan Silva Meza, consideró que el presidente Felipe Calderon no excedió su autoridad publicando un decreto que detalla las acciones para tomar a fin de conseguir la transición a la televisión terrestre digital.
Con este resultado, la controversia constitucional promovida por el Senado, se rechazó para no encontrar la mayoría cualificada de ocho votos por el Tribunal para expresar una opinión sobre la constitucionalidad o no constitucionalidad del decreto, y esto sigue vigente.
El proyecto de la oración elaborado por la ministra Olga Sánchez Cordero, propuesta para declarar inconstitucional el decreto, porque la regulación de radio y materiales de televisión es una potencia reservado según la ley de la Comisión de Telecomunicaciones federal (Cofetel), en la violación de los principios de subordinación jerárquica y reserva de la ley.
Sólo Zaldivar, Jorge Mario Pardo, Margarita Luna y Sánchez Cordero hemos votado a favor del proyecto.
Con este argumento, tanto el Senado como la Cámara de Diputados promovieron dos controversias constitucionales para contradecir el decreto y apoyar las reclamaciones, el ministro Sánchez Cordero suspendió la aplicación del decreto y todas las acciones estipuladas allí en cuanto a la transición digital.
En los ministros" que se encuentran allí también se decidió para rechazar la reclamación archivada por la Cámara de Diputados, sin firmar la discusión del proyecto, también responsable del ministro Sánchez Cordero.
En su discurso, el ministro dijo que no estaba de acuerdo con los argumentos del proyecto en el sentido de que el ejecutivo federal no puede estructurar a través de reglas generales las medidas para la administración pública para estar preparada.
"Tampoco considero que de ser hecho afectaría la autonomía del órgano regulador," y recordó que la planificación de las políticas públicas en áreas estratégicas como el sector de las telecomunicaciones equivale al ejecutivo federal, que tiene un mandato constitucional, la dirección del estado.
El reemplazo de análogo al digital es uno de los cambios más importantes que han afectado a el mundo en los últimos años, y produce una mejor utilización del espectro eléctrico en la radio, mejor señale la calidad y más canales.
Retrasar el cambio, él dijo, significaría retrasar las ventajas de digitalización, que implica una decisión de interés público, que no solo tiene una dimensión técnica, "ya que cubre cuestiones de seguridad nacional y económicas, sociales, políticas."
Estas cuestiones, él dijo, "requiera que el funcionamiento del sistema entero previsto en el principio de la administración económica estatal, comprenda un grupo de poderes que la Constitución lleva al poder ejecutivo estatal."
Él recordó que un gran número de países de todo el mundo ha completado ahora la transición digital y lo ha hecho a través del ejecutivo, a pesar de haber especializado muy cuerpos técnicos.
Allí no se puede concluir que el gobierno, publicando el decreto impugnado, que invade en ningún caso la competencia del Congreso, presta en el área administrativa la observación de las leyes publicadas por la Legislatura, él dijo.
