La adversidad climática hizo más lenta la economía
Durante el primer año de la dirección de Mario Lopez Valdez, en Sinaloa aumentó el desempleo y la informalidad, la inversión extranjera disminuyó y la economía se redujo.
2011 es un año que se recordará en la historia económica de Sinaloa, relacionados con el primer año del gobierno de Mario Lopez Valdez también llamó el año de cambio, que generó grandes expectativas en cuanto al desarrollo de la economía, pero dado la adversidad climática del principio del año, no había ningún crecimiento, sin embargo allí se registró una disminución de los principales indicadores de desarrollo económico.
Las temperaturas del febrero bajas, no sólo causaron pérdidas de millones de euros para el sector agrícola, pero ellos limitaron las posibilidades de la economía estatal de crecer, causando una contracción de la actividad económica en general del 3.6 por ciento en la primera mitad del año, principalmente apoyado por la caída histórica del 31.16 por ciento en la agricultura, que afectó la dinámica de otros sectores económicos.
Según el informe en cuanto a las zonas afectadas por la helada, emitida por el Consejo mexicano para el Desarrollo rural Sostenible allí se dañaron 835.582 hectáreas, de las cuales el 78.03 por ciento sufrió el daño total y el restante del 21.07 por ciento tenía el daño parcial. Las cosechas dañadas principales eran las verduras, maíz y garbanzo.
La caída de la actividad económica ha generado, hasta noviembre, un aumento constante del desempleo en el estado, según el Instituto Nacional de Estadística y Geografía, el precio del estado de paro durante los tres primeros cuartos del año registró un crecimiento acelerado, de enero a marzo 55.053 habitantes de Sinaloa estaban desempleados, con una tasa del 4.53 por ciento de la población económicamente activa para el segundo cuarto, el precio se hizo el 5.28 por ciento, y entre julio y septiembre que el promedio siguió aumentando al 6.19 por ciento, un precio que en términos del número de personas representa a más de 74.000 de habitantes de Sinaloa desempleados, un aumento en comparación con la primera mitad de 18.969 individuos.
Liquidez inferior
El desempleo en Sinaloa durante el año es el multifactorial, para el economista Gerardo Lopez Cervantes, director en la Facultad de Economía y las Ciencias sociales del UAS, el crecimiento de paro se puede explicar indirectamente, según las acciones que las políticas públicas se han tomado.
"Lo que vemos ahora es el aumento del paro que tiene que ver con varios factores, incluso la pérdida de la liquidez en el mercado de una coacción del recurso impuesta por la legislación que ocurrió en el Congreso a fin de lucha contra el blanqueo de capitales desde para la gente que ilegalmente posee dólares no es tarea fácil con, invierta y úselos en algo" él dijo.
Inmigración parada
Lopez Cervantes dijo que en el aumento del desempleo también hay un factor demográfico.
"Varias personas que abandonan el estado en busca de un empleo en el extranjero, en los Estados Unidos se han restringido, en primer lugar debido a las dificultades de entrar, y segundo de todos porque una vez que se entran ya tienen demasiadas dificultades para encontrar un trabajo, ese grupo de la gente se queda y empleos exigentes aquí, en el estado, haciendo el precio del paro elevarse, "él dijo.
Informalidad
El análisis del mercado de trabajo de Sinaloa empeora considerando el alto nivel de informalidad que prevalece entre las condiciones laborales, según INEGI, el 60.38 por ciento de la población activa en las labores estatales sin citarse como trabajadores a cualquier institución de la seguridad social.
Además del paro e informalidad, otro recordatorio de trabajo estatal está representado por salarios bajos; la entidad tiene los salarios más bajos en el país, según los archivos del Instituto de la Seguridad social mexicano y el Ministerio de la Asistencia social y de Trabajo.
Los ingresos medios mensuales de trabajadores de Sinaloa eran, hasta septiembre, 5.352 pesos, bajo de la media nacional, que es de 7.375 pesos.
Contracción de FDI
Además de la caída de actividad económica y elevada tasa de desempleo, en 2011 allí se registró la decadencia más grande en la inversión extranjera directa en los últimos 10 años, según el Ministerio de Finanzas de enero a junio FDI estatal sumó 630.697 dólares, que representa una caída del 87.74 por ciento comparado con 5.143.312 dólares en el mismo período del año pasado.
Por su parte, el Ministerio de Desarrollo económico del Gobierno estatal consideró una inversión total de 17.280.000 pesos durante el año, que ocurrió principalmente en las empresas del sector terciarias.
Deuda
Con el telón de fondo de la recesión económica, el gobierno estatal preguntó en julio durante el congreso estatal, la aprobación de un crédito de 3 mil millones de pesos, que serían para la inversión en proyectos de infraestructura en 18 municipalidades, a fin de reactivar la economía, la aprobación del Congreso local era para un total de 2.600 millones de pesos, y hasta noviembre ningunas beneficios de la deuda se observaron en ningún sector de la economía estatal.
Reacciones
Para representantes comerciales, el primer año del gobierno de Mario Lopez Valdes demuestra la falta de la capacidad del gobierno.
Miguel Loredo Lopez, el presidente de la Cámara Nacional de la Industria de Transformación, dijo que durante 2011 hubo una falta de armonización de los testamentos de varios sectores, incluso el propio gobierno estatal.
"El desempeño de la economía en Sinaloa este año ha sido realmente pobre, uno tiene que trabajar mucho a fin de recuperar la tierra perdida este año, en 2012 debemos redoblar nuestros esfuerzos, no pudimos alinear los esfuerzos de todos y sobre todo el movimiento bueno y sincronizado del nuevo equipo del gobierno, esperamos que el próximo año sea mucho mejor que" él dijera.
Lentitud económica
Lopez Loredo dijo que los acontecimientos como la helada temprana este año pararon la economía estatal y su actuación y crecimiento se restringieron.
"El flujo económico bajo es el producto de varios acontecimientos, incluso la helada, uno de los efectos principales ha sido una economía lenta que no se hace bastante rápida para generar un dinamismo económico que permite contar con un nivel del flujo aceptable de los procesos, productos y servicios y por lo tanto, a finales del año lo cerramos debajo de nuestras expectativas," dijo él.
Redefinición de la vocación
Teodoro Salazar Uriarte, el presidente de los Empleadores" la Confederación de la república mexicana en Sinaloa, dijo que se requiere que el estado procese las actividades productivas más dinámicas.
"En general, encontramos que se haya estado siguiendo trabajando, creemos que es necesario desarrollar un programa a largo plazo que redefine la vocación y el curso económico del estado, es importante hacer detonar todo el recurso potencial material y humano que Sinaloa tiene," dijo él.
Trabajo para hacer
El presidente de Coparmex subrayó la importancia de establecer una futura visión para dirigir mejor los esfuerzos del gobierno.
"En general yo diría que el Gobierno se ha esforzado por tener éxito en varios campos, en términos de desarrollo económico hay algún progreso pero es importante desarrollar un programa a largo plazo," dijo él.
Él señaló que la actual administración ha mostrado un progreso en su propia manera de dirigir las políticas públicas.
"Hay elementos que nos permitan diciendo que el gobierno se hace más global, y lo que puedo decir es que hay trabajo hecho y creo que el gobierno es consciente que hay trabajo para hacer," dijo él.
