La elite en peligro 
El fenómeno ya había manifestado un par de días atrás con la votación en la Cámara de Representantes contra el plan de rescate de 700.000 millones de dólares, aprobado por la Casa Blanca: Una parte importante de los estadounidenses era, y sigue siendo, más interesados en castigar a Wall Street que en el rescate de la economía. 
La confirmación ayer fue dada por el New York Times cuando se informó de que la actual crisis está provocando una división en el seno del Partido Republicano, cada vez más dividido entre sus antiguos alma Costa Este, moderado en favor de las instituciones federales y la comunidad empresarial, y su nueva alma, en lugar de los conservadores, hostil a "aquellos en Washington » y para el mundo financiero, especialmente fuertes en el centro y el sur de Estados. 
El alma, para ser exactos, que se ha hecho a sí mismo overbearingly vivo con la votación mencionado inicialmente. 
La última es sólo un ejemplo de los cambios, de los grandes cambios, que el terremoto económico actual permite o tal vez anuncia que se percibe: No sólo en los Estados Unidos, sino también en todo Occidente y tal vez no sólo aquí. 
Tanto en Estados Unidos como en Europa la crisis parece actuar como catalizador de fenómenos que han sido en incubación desde hace tiempo y que en el nuevo clima han ido acercando y finalmente están saliendo a la luz. 
El primero de estos fenómenos es el traer al día, la extraordinaria relanzar, de la categoría de dobles state-sovereignty en relación a una especie de renacionalización de la economía. 
La crisis, en efecto, es una crisis de las instituciones financial-banking que, de hecho, fuertes vínculos con países extranjeros, pero que, sobre todo en los presupuestos de las personas y familias que viven en una sola nación, en un único Estado. 
Este inmediatamente crea un problema político de quien está en el Gobierno: Y eso es cómo hacer frente a las dificultades y las protestas de las personas y las familias que, además, también de forma el electorado. 
En otras palabras, la crisis parece ser económicamente en todo el mundo, pero políticamente es casi exclusivamente de un problema nacional. 
Internacionalismo político parece ser sustancialmente fuera de juego o que no tienen mucho que decir: La clara la prueba de ello es la Unión Europea que, dividida como es habitual entre los distintos intereses y las diversas estrategias estatales, no puede decidir sobre una senda política común. 
Y lo es desde el Gobierno de cada Estado único que todos esperar a la intervención, planes de relanzar y rescate, nuevas normas, y sobre todo ayuda financiera: Desde que cuando se trata de peor es sólo los Estados que tienen los recursos financieros, la cantidad de recursos financieros capaces para intentar arreglar las cosas. 
Y también disponen de los medios necesarios, y las razones legítimas para utilizarlas: Dos recursos de incommensurable valor, bajo determinadas circunstancias, de la que no es probable que el mercado y ninguna organización internacional podría vender en la misma medida. 
Este nuevo énfasis que la crisis plantea sobre el elemento statal-national, después de todo, está perfectamente en sintonía con la cada vez mayor importancia que los últimos acontecimientos económicos tienden a atribuir a un coeficiente que está muy estrechamente relacionado con este elemento: La territorialidad. 
Paradójicamente, de hecho, mientras estábamos convencidos de que había entrado en el reino de la web, de una tecnología cada vez más sofisticados, de la inmaterial, mientras estábamos convencidos de que Hacienda globalizado ya estaba destinado a dominar el mundo, de repente, nos dimos cuenta de que nuestro futuro había en lugar de tratar de una creciente moda con las cosas que están muy poca importancia como el agua, las cosechas, el petróleo. 
Accidentalmente, todos son elementos que pueden ser transportados de un lugar a otro, pero en cualquier caso están empatados en una forma absoluta a un espacio bien definida, a un territorio. 
De modo que quien va a ser el soberano, seguramente es más cartas en su cubierta que quien no está, que lo que sucede a vivir en un lugar sin cultivos, el petróleo, o el agua. 
Estoy yendo a la segunda novedad que sin embargo predicen una división. 
Quien dice Territorio, Estado, de Gobierno, inevitablemente, implica Politics, y de ahí Liderazgo. 
En este sentido, la crisis económica parece producir dos fenómenos convergentes. 
Por un lado, el conocimiento de la necesidad objetiva de Gobierno autorizado, la demanda de alguien que sabe cómo manejar la situación. 
Por otra parte, una ola de desacreditar al liderazgo existentes, un tipo económico, reveló a ser tan insuficiente y lleno de incertidumbres. 
Y juntos algo cada vez más profunda y en cierto modo inquietante: Un descrédito, intolerancia, una imagen de insuficiencia, un sentido de la lejanía que tiende a implicar a toda la clase dirigente de un número cada vez mayor de los países occidentales. 
Más bien parece abrirse camino en amplios sectores de la población la convicción de que antes de que sus acciones son las mismas ideas como de la elite social hasta ahora a favor, su forma de ser y de sentimiento, de su cultura aceptado en todos los sentidos de la palabra, que tuvieron su día, y siempre será más ajeno a la opinión de la mayoría. 
En otras palabras, la petición de liderazgo alimenta underhandedly pero se lanzaron un potente movimiento de deslegitimación de la clase empresarial y de las estructuras políticas tradicionales, que manifestarse en la repentina electoral "giros abrupta » o las revueltas en el ánimo colectivo en estos últimos y recientes tiempos, desde el conservador lugar en Austria – Baviera a la caída del consenso laboral en Gran Bretaña, a la rebelión de los congresistas estadounidenses contra Bush (y tal vez incluso la victoria de la razón en Italia tiene algo que ver con ella). 
Uno tiene la impresión de que la elite tradicionales, sus partidos, sus programas, sino también sus ritos, sus periódicos, su acreditada intelectuales, algunos dirán sus formatos, siempre les resulta más difícil de entender, y de ahí que represento, que ha estado tomando forma en las capas más profunda de las sociedades occidentales y que la crisis económica está fortaleciendo, aumentando, potencialmente agitación sin mesura. 
En vista de todo esto, hablando de un "rebelión de las masas » como el orden del día puede ser francamente exagerado. 
Pero mantener los ojos bien abiertos, no es seguro. 
