Cine viejo goodbye Paradiso, ciudades cancelar los teatros históricos 
Cinematográficas históricos de los teatros estrecha en favor de Multiplex. 
"Una ciudad sin los teatros cinematográfica es una ciudad, es una cara sin ojos". 
La imagen ofrecida por el director Giuseppe Tornatore efficaciously fotografías de lo que está ocurriendo no sólo en los grandes centros urbanos italiana, sino también en las ciudades de provincias. 
El proceso de prescindir de las salas de cine, con el nacimiento en las afueras de grandes multi-hall teatros y la consiguiente muerte por consumo de los teatros single-hall en el centro de la ciudad, es uno de los acontecimientos que parece inevitable e indisputable y también tiene todas las características de un verdadero crimen cultural. 
Con frecuencia, es que los lugares históricos se llena de recuerdos que desaparecen ", es como si un amigo está perdido, un conocido con los que ha compartido la forma y muchos recuerdos », señala el director del Nuevo Cine Paradise, la película que hace veinte años dio Tornatore el Oscar y el Gran Premio del jurado de Cannes, y que narrada el poema de una sala provinciales y la nostalgia de una forma de vida el cine que, tal vez, se ha perdido para siempre. 
Las cifras facilitadas por ANEC, la principal asociación cinema-operators, hablar con claridad: En los últimos cinco años 316 estilo tradicional cines han cerrado compras, y los que tienen que pagar el precio fueron sobre todo los teatros en las principales ciudades: 10 menos en Florencia, 9 en Milán, Nápoles, Bolonia, y Roma, 6 menos en Turín, 5 en Palermo. 
Entre las regiones más afectado por los cierres, Emilia-Romaña toma la iniciativa con 82 single-hall cines perdido, seguida de la Toscana (44), y por Lombardía (41). 
Y para demostrar que la llegada del multiplex es el máximo responsable de su desaparición, estos son exactamente las tres regiones italianas con el mayor número de nuevo multiplex cines registradas: 195 más pantallas de Lombardía en los últimos cinco años, 81 tanto en la Toscana y Emilia-Romaña. 
« La empresa italiana se ha convertido en una forma irracional » observa Paolo Protti, el presidente de ANEC, "es útil que nuevas estructuras están construidas pero es también esencial que la supervivencia de las existentes queda garantizada, porque una vez al teatro en una ciudad cierra, no todos sus patrocinadores pueden estar dispuestos a transferir a la multiplexes. 
No olvidó mencionar la asignación de fondos en favor de los operadores: El débito anteriores por el Estado es de unos 10 millones de euros. 
Es una vergüenza, de la ética y desde el punto de vista moral, que el Gobierno no respetar las leyes existentes. 
Para mantener el sector entre 16 y 18 millones de euros al año son necesarias ». 
Un ejemplo interesante es que de Bolonia, la primera ciudad italiana que, preocupada por los cierres, ha decidido dar cobertura por parte de la firma de un protocolo entre el ayuntamiento y ANEC, la primera de su clase en Italia, para proteger y promover los cines single-hall tanto en el centro histórico, así como en las afueras. 
Entre las disposiciones previstas son exenciones fiscales medidas en favor de los operadores y ventajas para el público en términos de movilidad: Los espectadores puede entrar en la zona traffic-limited y han tarifas especiales para estacionamiento de carretera y en algunos de los aparcamientos. 
« Es una iniciativa que me gusta » observa Giuseppe Tornatore "y espera que otras ciudades seguir el ejemplo de Bolonia, poniendo en marcha otras medidas. 
Es cierto, sin embargo, que a diferencia de la prepotencia del multiplex, los teatros tradicionales también para mejorar la calidad de imagen y sonido, porque el público hoy en día es más exigente. 
La defensa de los cines tradicional es un tema que para mí siempre ha sido importante: El cierre de la Bagheria Supercinema, el lugar de mi infancia y adolescencia, fue la chispa que me convenció para crear "Nuevo Cine Paradiso", en la que ya he estado pensando en los últimos 10 años. 
He estado viviendo en Roma de 25 años, y cuando pasan por delante de la Rialto o del Quirinal en National Street tanto cerrado por ahora, allí donde he visto muchas emociones compartidas, me dirijo para no ver los carteles blackened por el polvo ». 
