La CECA descartes una segunda gran oleada de fusiones en los bancos de ahorro 
El jefe de la Dirección principal de la CECA, José Antonio Olavarrieta, descartó ayer que una gran ola de fusiones de cajas de ahorro va a tener lugar e insistió una vez más por la rapidez con la que la reconstrucción del sector. 
Cuando el proceso de concentración de las cajas de ahorro españolas empezó, hubo varias organizaciones que aseguró que no participarán en esta primera etapa y que tendrían que esperar a la segunda ronda. 
Sin embargo, el jefe de la Dirección principal de la Confederación Española de Cajas de Ahorros (CECA), José Antonio Olavarrieta, descartó ayer que esta nueva gran ola de operaciones va a tener lugar. 
Creo que la mayor parte de las fusiones, la incorporación de Cajasol al grupo de banca Civica no puede llamarse una segunda vuelta, sólo hay ajustes. 
"La mayor parte es completamente y quizás en lugar de 17 podríamos haber 13 ó 14 años, pero todos los grandes procesos se han llevado a cabo bajo la supervisión del Banco de España, que ha colaborado muy muchos a este asunto", apuntó el manager. 
En declaraciones durante un desayuno gerente de la Asociación y los ejecutivos de Aragón (ADEA), Olavarrieta ha puesto de manifiesto que el proceso de concentración se lleva a cabo "con la mayor rapidez posible, y debemos estar muy satisfechos de cómo esto ocurre en los términos que por el momento, no ahora, han marcado en los planes de negocio con el Banco de España", subrayó. 
Al pasar de 45 salvar a los bancos con un promedio de 28.500 millones de volumen de activos a 17 con 75.500 millones de dólares es un proceso que no tienen comparación en la historia, reducir el número de organizaciones a un 62%, de modo que son mucho mayores para cumplir con Basilea al hemiciclo, subrayó. 
Olavarrieta reconoció que existe "una serie de opinión bastante pesimista sobre la lentitud del proceso" que demuestra " la falta de gravedad y la razón ", porque" lo que el Banco de España no hace más que recordar que debemos cumplir el plazo antes de final de año ". 
El jefe de la Dirección principal de la CECA, José Antonio Olavarrieta, aseguró ayer que España tiene más riguroso sistema financiero de toda Europa y "probablemente" de todo el mundo y se le atribuyó a quienes cuestionan la "falta de información". 
El gerente reveló que, en la actual coyuntura económica, "podemos estar muy tranquilo" con la situación de las organizaciones financieras y las cajas de ahorros, un sistema que ha llevado a cabo un proceso de concentración "muy importante" y que "va con la mayor rapidez posible". 
También ha recordado que el banco español salió muy bien con las pruebas de estrés que el BCE hizo en julio. 
