Costa de Marfil está esperando el nerviosismo anuncio de los resultados de las elecciones. 
El Secretario General de la ONU, Ban Ki-moon, ha exigido la publicación "sin demora" de los resultados de las elecciones presidenciales de Costa de Marfil, sobre la expiración del plazo marcado. 
"El Secretario General destaca la necesidad de que la Comisión Electoral Independiente para completar su labor y anunciar los resultados provisionales sin demora", subrayó un portavoz del jefe de la Oficina de las Naciones Unidas ". 
"Pide a todas las partes y las instituciones de Costa de Marfil para demostrar responsabilidad y abstenerse de toda iniciativa hasta la annoucement de los resultados provisionales". 
A pesar de las presiones que ejercen ciertos gobiernos extranjeros, la Comisión Electoral ha autorizado Th plazo hasta la medianoche del miércoles para aprobar, sin publicar los resultados de tres días después de la votación del domingo. 
Alrededor de cuarenta minutos antes de la expiración del plazo marcado el presidente de la Comisión Electoral Independiente "siguieron trabajando" sobre el announbcement de los resultados. 
En todo el mundo, llamados pasaron a ser más frecuentes el miércoles por la Comisión Electoral por último a declarar el nombre del ganador de la segunda vuelta, Laurent Gbagbo y Alassane Ouattara su opponenent. 
Pero el campamento de Gbagbo está contando ont su cancelación por el Consejo Constitucional de "fraudulenta" votos en el Norte, recibido por los antiguos rebeldes de las Fuerzas Nuevas (FN) desde el fallido golpe de Estado en septiembre de 2002. 
Pascal Affi N 'buessan, director de la campaña de Costa de Marfil presidente, declaró que el manœeuvres de intimidación de los electores por las FN en el norte del país ha disuadido a los partidarios de la salida Presidente de votantes. 
Cualquier elección podría ser anulada, si las denuncias por ghagbo son aceptadas por el Consejo Constitucional. 
Gbagbo los enemigos alegan que el Tribunal Superior de la coutry no es imparcial, ya que está presidida por Paul Yao N 'dré, un político cercano aliado de Gbagbo. 
Alassane Ouattara, el hombre desde el norte, que niega cualquier vinculación con los antiguos rebeldes, ha calificado de "inaceptable" la demora en hacer el anuncio de los resultados y ha pedido a Gbagbo a respetarlos, pero no ha ido tan lejos como para cantar victoria. 
Sus aliados Estado que Gbagbo está bloqueando la publicación de los resultados, porque sabe que perdió y que presentar una queja ante el Consejo Constitucional, después de haber impedido que la Comisión Electoral de la publicación de los resultados, sería ilegal. 
La segunda ronda de votaciones en las elecciones presidenciales del domingo se estima que han culminado el proceso de reunificación y de reconciliación de un país dividido en dos años. 
El miércoles por la ONU advirtió de la Costa de Marfil clase política que podría celebrarse respoonsible de cualquier tipo de violencia. 
Laurent Gbagbo ha terminado en los primeros puestos en la primera ronda celebrada el 11 de octubre, con el 38% de los votos contra 32% de Alassane Ouattara, quien recibió el apoyo de la opinión pública del ex Presidente Henri Konan Bedié (25% en la primera vuelta). 
