Pide resultados de Propiedad Intelectual del Congreso 
Eduardo Dávalos, Presidente de la CEC, propuso que los diputados asumir la gran responsabilidad de ser un ejemplo para un mejor Sinaloa por los diversos desafíos que enfrenta. 
Una legislatura de obras decente y libre de acuerdos entre los partidos y el Ejecutivo Estado está siendo exigidas por el sector empresarial de Mazatlán, porque hay una convulsión Sinaloa que se enfrenta a grandes problemas. 
Ayer la 60 legislatura fue votado, integrada por siete fuerzas políticas, 19 diputados del PRI, PAN, tres de los 13 del Partido Nueva Alianza, dos del PRD, uno del PT, uno del partido y uno más del PVEM, lo que significa un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso de la s-state se menciona que llegan a cumplir una gestión limpia de compromiso con la sociedad y los distintos sectores que requieren un responsable de la labor legislativa. 
Eduardo Dávalos Zamora, presidente del Consejo Coordinador Empresarial, sugiere que el recientemente liberado 40 diputados del Congreso del Estado ha asumido la gran responsabilidad de ser un ejemplo para un mejor Sinaloa por los diversos desafíos que enfrenta. 
Esperamos que los diputados realmente va a ejercer su derecho, libre de acuerdos entre las partes porque es una costumbre de hacer acuerdos para proteger sus propios intereses y convertirse en un personaje de un carnaval de los gobernadores y dirigentes de las fracciones parlamentarias. 
Por ello se refirió a certificar el compromiso para establecer los necesarios puentes que podría ayudar al Gobernador para seguir adelante. 
Esperamos que vienen a hacer un buen trabajo y principalmente a la sociedad y a los sectores ya que los habitantes de Sinaloa fueron los que les dio el voto de confianza durante las últimas elecciones. 
José Ramón Manguart Sánchez, presidente de la Asociación de Hoteles Tres Islas, considera que uno de los mayores retos para el 40 representantes populares es el de presionar y sumar fuerzas en busca del crecimiento económico del Estado, porque hoy en día la situación económica es muy complicado. 
Lo más importante es impulsar el crecimiento económico, que genera incentivos para la inversión e infraestructura y que, de alguna manera, formarán una nueva generación de empleos. 
En cuanto a la actividad turística, exigió que los nuevos legisladores dar el peso revisada en el presupuesto del Estado para fortificar la secretaria de Turismo. 
Según tengo entendido esta es la segunda Departamento del Estado con menos presupuestos y es incongruente una importante actividad económica y la generación de divisas y la inversión y que compite directamente con el sector agrario. 
Además de imponer una obligación de etiquetado recursos turísticos de la detonación de proyectos que contribuyen a la seguridad del Estado y actualizar la ley del alcohol que no ha sido capaz de resolver en las legislaturas anteriores. 
