El gobierno español no plantear objeciones con respecto a los vuelos de la cia 
El gobierno español no plantear objeciones con respecto a los vuelos de la cia con prisioneros talibanes y de al qaeda que iban a guantánamo a través del territorio español, según el telegrama del embajador de los estados unidos en madrid. 
Así se refleja en los cables filtrado documentos () por wikileaks a diario "el país", en la que se añade que el primer vicepresidente del gobierno en aquel momento, maria teresa fernández, de la vega, ha pedido que el ejecutivo español fue informada para "para ser capaces de demostrar que se había llevado a cabo un seguimiento adecuado de los procedimientos de los aviones que españa". 
En junio de 2006, después de un informe del consejo europeo en el que ha habido acusaciones de complicidad en prácticas contra los derechos humanos de una docena de países, entre los que se encuentra españa, se celebró una reunión entre el ex embajador eduardo aguirre de américa del norte y fernández de la vega. 
El vicepresidente reconoce que el informe del consejo "hubiera dado el gobierno de zapatero fuera del juego" y ha insistido en que españa no tenemos nada que esconder en relación con este asunto. 
"De la vega subrayar que españa no plantear objeción por los vuelos de inteligencia en territorio español". 
"Simplemente quieren ser informado" para evitar ser tomada por sorpresa "", aguirre se refiere en un telegrama. 
También el ex ministro de asuntos exteriores, el sr. miguel ángel moratinos, indicó que el embajador español que el ejecutivo "quería dar a este asunto de poca atención como sea posible, aunque está en manos de los jueces, el gobierno tuvo una influencia limitada". 
Por otro lado, en enero de 2007, la fiscalía vicente gonzález transmitidos a la embajada de que no intentar bloquear la iniciativa del juez de solicitar la clasificación de los documentos del centro nacional de inteligencia (cni) y el ministerio de defensa con respecto a los vuelos de la empresa " 
Esta información no contiene ningún elemento incriminación ni cualquier información sensible, "fiscal explicado la embajada después de hablar con el público. 
No obstante, los estados unidos reflejada en su preocupación por la aparente "coordinación entre la juez español y fiscales", más que la desclasificación información alemán del cni o el ministerio de defensa. 
Esta coordinación entre investigadores independientes "va a complicar nuestros esfuerzos para manejar discretamente el caso entre gobiernos", dice aguirre. 
En marzo de 2007 durante un almuerzo entre el embajador de los estados unidos y el ministro de asuntos interiores, alfredo pérez rubalcaba, eso se le comentó que "aunque los jueces españoles están uso furiosamente celosos de su independencia y hará lo que consideran un derecho", que había dado instrucciones a sus colaboradores "para evitar comentarios de deterioradas retórica, en un intento de reducir la temperatura". 
El embajador también expresa su preocupación por la acción del pp en este asunto. 
"A pesar de su orientación pro general americano, nuestra experiencia indica que el pp no duda en la capitalización ninguna indicación de que el gobierno de zapatero tolerado o ignorado deliberadamente acciones de los estados unidos que podrían interpretarse como las posibles violaciones de los derechos humanos, incluso si estas revelaciones tienen consecuencias negativas para el gobierno de los estados unidos", indica. 
