El geriatrician afirma que las muertes fueron causadas por la falta de "significa" 
Los propietarios del centro de olot no descartar que sus mató a más de 11 personas mayores 
Las personas responsables con la geriátrica hospital de la caritat ayer de olot (gerona) ofreció una conferencia de prensa para subrayar los daños que ha causado a la institución la conducta criminal de joan vila dilmé, la enfermera que mientras que mató al menos once personas mayores que había bajo vigilancia. 
El director de la residencia, joan sala, apareció acompañado por el centro del abogado abogado, joan canadá, y ha anunciado que "la intención de la caritat de echar la culpa a los responsables de las muertes individuales pero" la legalidad y la responsabilidad nos obliga a asumir la situación de personas responsables civiles procesales. " 
Y que, además de la pérdida de prestigio que la organización social puede encontrar por no haber detectado en tiempo las actividades delictivas de los vigilante, la gran amenaza para la caritat ha ahora adopta la forma de una indemnización sustancial que ya está calculada por los representantes legales de los familiares de las víctimas. 
Joan vila dilmé ha confesado que el primer crimen se remonta a agosto de 2009 y que desde luego no dejar de matar. 
El juez ya mencionado en el documento que ordenó la exhumación de los pacientes de la geriátrica de ocho organismos hospital - que se sospecha que en muchos casos no médico personalmente explorar los muertos, pero, teniendo en cuenta la edad y las patologías de los pacientes, el procedimiento fue por teléfono. 
La caritat ayer, a través de su director, niega este final y ha dicho que "la falta de medidas no han sido la causa de lo que había ocurrido en ningún momento". 
El abogado de la caritat añadido que "en la causa no hay ningún indicio de que ha habido un imprudente acción por parte de cualquier otra persona que no es la culpable". 
La baptized como "ángel de la muerte" confesado 11 de asesinatos el día antes de ayer y que cometió el primer delito detalladas sobre el 29 de agosto de 2009 y un mes y medio después, asesinados otro abuela. 
En este caso una sobredosis de la insulina traído la muerte; a diferencia de la primera crimen que cometió con una mezcla de tranquilizante tabletas. 
El director de la caritat dice que es complicado de control que el personal del centro tengan acceso a los medicamentos. 
La sobredosis de la insulina y sedante cóctel habría sido el mecanismo utilizado en seis de los nueve delitos que la enfermera, en su afán de aliviar el sufrimiento de los pacientes, utilicen o matando. 
Pero las pruebas que se están llevando a cabo en el laboratorio tendrá que aclarar si vila no miente y ha intentado asegurar por sus primeras víctimas menos cruel muerte o si, por el contrario, quemados internamente por darles lye como ya ha confesado que habían hecho con los tres mujeres que mató entre el 12 y el 17 de octubre. 
En la caritat no dar credibilidad a la aparición de los vigilante, ni el número de asesinatos confesado, que no refutar superiores y justifica su actitud en las distintas versiones que vila ha dado en sus visitas a la corte y el sentido de cambiar su método de matar después de tener éxito, ocho asesinatos. 
Esta es la razón por la que dicen que poner a disposición de la justicia a aclarar el alcance de este caso. 
