La ceca descartes una segunda gran ola de amalgamas en el ahorro bancos 
El jefe de la principal dirección de la ceca, josé antonio olavarrieta, ayer desechados que una gran ola de amalgamas de las cajas de ahorro va a tener lugar y ha insistido una vez más por la rapidez con que se está realizando la reconstrucción del sector. 
Cuando el proceso de concentración de la inició cajas de ahorros, el español había varias organizaciones que aseguró que no participar en esta primera etapa y que esperamos la segunda ronda. 
No obstante, el jefe de la principal dirección de la confederación de cajas de ahorros (ceca) español, josé antonio olavarrieta, descartan ayer que esta nueva gran ola de operaciones va a tener lugar. 
Creo que se ha producido la mayor parte de las amalgamas, la incorporación de cajasol al grupo de banca civica no puede ser considerada una segunda ronda, sólo hay ajustes. 
"La mayor parte es completamente hecho, de 17 tal vez podríamos haber 13 o 14, pero todos los grandes procesos han realizado bajo la vigilancia del banco de españa, que ha colaborado muy muchos de esta cuestión", ha señalado el gestor. 
En declaraciones durante un desayuno del gestor de la asociación y ejecutivos de aragón (adea), olavarrieta ha puesto de manifiesto que se está llevando a cabo el proceso de concentración "con la mayor rapidez posible, y debemos estar muy satisfechos de cómo esto ocurre en los términos que en el tiempo, no ahora, se marcó en los planes de negocio con el banco de españa", subrayó. 
Para ir de 45 salvar bancos con una media de 28.500 millones de volumen de activos a 17 con 75.500 millones de euros es un proceso que no tiene comparación con la historia, la reducción del número de organizaciones de un 62% de manera que son mucho mayores que cumplir basilea, ha subrayado. 
Olavarrieta "reconocido que existe una serie de opiniones bastante pesimista sobre la lentitud de la" proceso "que demuestra una falta de seriedad y de la razón", porque "lo que hace el banco de españa es recordar que hemos de cumplir el plazo antes de finales de año". 
El jefe de la principal dirección general, josé antonio olavarrieta, seguros de que españa tiene el sistema financiero más rigurosas de toda europa y de todo el mundo, "probablemente" y "ha atribuido a los que cuestionan la falta de conocimiento". 
El gerente demostró que, en la actual coyuntura económica ", que puede ser muy flexible" con la situación de los organismos financieros y las cajas de ahorros, un sistema que ha emprendido un proceso de concentración "importante" y que "con la mayor rapidez posible". 
Además, recordar que el banco español ha salido muy bien con las pruebas de estrés que el bce en julio. 
