El programa nuclear paquistaní genera un gran agitación en los ee. uu. 
Islamabad produce armas nucleares a un ritmo más rápido que cualquier otro país ". 
Las filtraciones de wikileaks confirmar los lazos entre los talibanes y pakistán. 
El contenido de la correspondencia entre la embajada de los estados unidos en pakistán y el departamento de estado de los estados unidos filtrarse en el portal de wikileaks confirma la enorme agitación que proporciona el programa nuclear paquistaní en washington. 
Además de la información y detalles sustanciales que se ofrecen en el contenido de las conversaciones y los pensamientos del mérito representantes diplomáticos en islamabad de américa del norte, los documentos revelan que la cooperación entre ambos países en el tema de la seguridad nuclear, en lugar de aumentar, disminuye "", y que "la inestable país asiático produce armas nucleares con un ritmo más rápido que el de cualquier otro país". 
La peculiaridad de los pakistaníes programa - que las armas nucleares no se ensamblan pero siguen almacenados por componentes para hacer difícil su destrucción en caso de ataque - constituye una de las principales causas de preocupación en washington. 
Por lo tanto es enumeradas por el embajador en pakistán, anne w. patterson, en un informe anterior a la visita de la ex asesor de seguridad nacional, james jones: "la proximidad de algunas centrales nucleares en el territorio bajo los talibanes ataque, habló de dispersión de los materiales nucleares y la vulnerabilidad del transporte de materiales nucleares". 
El elevado número de personas implicadas en los programas arsenales nucleares y los misiles se tenga en cuenta, no solo por los estados unidos, sino también en rusia, como la razón para mantener la guardia. 
"Pakistán ha tenido para contratar personal con creencias religiosas para proteger a las centrales nucleares, dada la escasa niveles educativos y culturales, las organizaciones extremistas tienen más oportunidades para reclutar personas para trabajar en los programas nucleares o de misiles", dijo el experto yuri carole, desde el ministerio ruso de asuntos exteriores, en una reunión con su estadounidenses homólogas. 
El más reciente información sobre la documentación filtradas por el portal de julian assange es la disminución de la cooperación entre los estados unidos y pakistán en temas de la proliferación nuclear y la alta tasa de pakistaní de la producción de armas nucleares. 
Una oficina de la embajada en mayo, que describe como "frustrante" la comunicación con pakistán, que dice: "la transparencia es a menudo inexistente; las ofertas de ayuda que siguen sin una respuesta o se les niega la". 
En otro mensaje, peter lavoy, funcionario de la inteligencia para el sur de asia, los estados nacionales que a pesar de la catástrofe económica, pakistán "produce armas nucleares a un ritmo más rápido que el de cualquier otro país del mundo". 
El embajador patterson también pide a washington, durante una visita de el jefe del ejército, el general ashfaq kayani, para dar órdenes claras a la persona que "el ejército de pakistán debe poner fin al apoyo tácito a los grupos terroristas". 
