Grammy candidaturas: jazz esperanza spalding una sorpresa recoger en mejores artista categoría 
Realizar en la solicitud de un presidente, y los ciudadanos están obligados a tener en cuenta. 
Esperanza spalding, de 26 años de edad jazz bassist y cantante a dedo por el presidente obama de desempeñar en su ceremonia de premios nobel de la paz en 2009, uno de los grammys "sorpresas este año con un nombramiento de alto nivel en la categoría de mejores artista. 
Considerando que spalding ha sido una cifra en la escena jazz desde su célebre álbum, "esperanza", el nombramiento de 2008 es un poco de un jefe scratcher, pero es coherente con las normas de la grammys de un artista no liberar a más de tres discos remasterizados antes la identidad de registro que "establece que el público que artista". 
Su ambicioso 2010 álbum, "cámara música la sociedad", sin duda marcado un paso adelante, y dado su airily invitar abiertamente y una tan parte con el pop, como el del sr. funk influencias de américa latina, es posible para llamar al menos una línea spalding de norah jones "gran éxito en 2003, los votantes equivalente más cercano a grammy mirar hacia jazz en esta categoría de vecindad" en los últimos años. 
En otros lugares grammy votantes acertadamente el vijay iyer trío de cumplirse "historicity" en el álbum categoría instrumental, un impulso de la emoción favorito de pelo de un registro que era un crítico el año pasado. 
Entre los iyer competir contra veterano saxophonist james moody 's "moody' s 4 ter" y "del keyboardist john beasley positootly". 
Trombone shorty favorito, un raucous nueva orleans y frecuentes invitado en territorio de la treme "de hbo", se cumplen en la categoría de jazz contemporánea, que de lo contrario se inclinan hacia la fusión con gestos hacia discos remasterizados de stanley clarke, john mclaughlin y jeff lorber. 
La salvaje, steampunk informados darcy james sostienen "sociedad secreta de ganado algo bien merecido reconocimiento en la categoría de gran colectivo, competir contra la billy childs colectivo de la cámara - jazz ricos y la cada vez dave aventureros" vivir álbum de holanda, cuyo octet caminos "fue un buen ejemplo de la parte de la bassist democrática como bandleader. 
