Con literatura puede poner el dedo en lo 
La segunda ronda de los placeres de la lengua fue un paseo más que los participantes promulgó la narration 
Entiendo que de sexo en un lenguaje que pero... con el dedo sobre? ¿qué esperaba el escritor luisa invitado pregunté a hacer?, valenzuela invitado a abrir la segunda ronda de los placeres de la lengua, caso de que celebra la literatura en español y que este tiempo el subtítulo de su pregunta (de otro modo la mesa redonda ha dedicado al sexo en la lengua, ha explicado). 
El dedo en la llaga... ", nos coloca en una posición difícil", dijo sweetly directamente el escritor argentino a los ciudadanos, sobre todo de los jóvenes, que se reunieron en la justa del libro de guadalajara internacional (fil) para escuchar esta mesa redonda moderado, marisol el señor schultz, así como valenzuela, sergio ramírez, mayra montero y luis garcía montero participado. 
Luisa valenzuela leer un texto que ha dedicado a gonzalo celorio y definir después que el señor schultz, así como un gran historia, con luisa en la primera persona como protagonista que en la búsqueda del conocimiento conocido como "", va de médico médico, de los cuales no obtener respuestas aunque se pone en el mismo argumento hilo. 
Que deja la paciencia médico convencido: "tal vez no es mi afincado, quizá es mi". 
Al final, después de que un enfoque frustrante con el trauma médico que aclara que no es imponer un plazo; es el psicoanálisis científico, que se debilita el misterio: "el delicado es el verdadero abierto; lo simbólico es la cicatriz". 
La protagonista suspiró aliviado y concluyó "en las heridas que sólo ha de saber que el verdadero es abierto y que no existe, pero convencido de que" los placeres y los trucos de la lengua han de ser mezclados. 
Valenzuela, el escritor, se ha jugado con ambos. 
La nicaragüense sergio ramírez también ilustra una encantadora narration que titulado elogio de la invención, donde el dedo en la llaga en las heridas no nombrados pero es descubierto. 
En términos generales de realismo, dice la historia de un famoso mágicos brujas, que por tocar las nubes, devolver los hombres que habían ido lejos o reparar las virtudes perdido por un criada, narration que se convirtió en hablando de los estados unidos, un gran novela que no falta desde el principio su propio historiadores que dicho y recordado bernal díaz del castillo que critica los excesos de las cosas en la conquista de los capitanes. 
Cervantes quien inventó todos nosotros (los escritores) se rieron de la falsa testigos que apareció en historias presentado como real, pero, por lo demás, que nunca han dicho la historia de los estados unidos con imaginación que falta shyness. 
Sin embargo, subrayó "locos personas y mentiras son las que mejor imaginar las cosas", y es en realidad y la falsedad encontrados, donde se sabe si lo transmitirlas pertenece a uno u otro lado, donde la literatura ficticios llega su apogeo. 
De hecho es "cervantes tradición. 
"Para su filosofía de: de lo que nos dicen de ee. uu". 
Como para ella, el escritor mayra montero vi y aplaudir la diversidad de interpretaciones que la invitación de fil causas con su mesa redonda el dedo en la herida. 
Los cubano - puerto rica señalaron su propio hacia el gran motor de la violencia social que atraviesa su país y divide a américa latina - producto de las disputas sobre el tráfico y la venta de drogas. 
Creo que la literatura, la poesía, buena canciones cerrar un compromiso tácito que naturalmente no es premeditada, indicó, tras mencionar que la realidad de la literatura es la comunicación y la dimensión del compromiso que se establece entre autor y lectores ", y que es una reacción química" de este último. 
La noche fue cerrado por el poeta español luis garcía montero cuya intervención también poner el acento "que con el dedo sobre las heridas del escritor comprometido por escrito". 
Se considera que en un mundo que vive en un intelectual prisa, también en el control de la conciencia y de aduanas que tiene efectos en la dogmatismos, olvidando "que detrás de cada afirmación no es un pequeño y detrás de cada negación es pequeño sí". 
"Para ser dueños de nuestro pensamiento y la realidad que debemos aclarar: y aclarar a menudo significa para poner el dedo en la llaga en la herida y a las personas que son mucho más cómodo, pensando en la caricatura en blanco y negro, en ideas sin un poco y también molesta a los poderes que prefieren un mundo blanco y negro", dijo, invitando a recuperar el sentido de escrito. 
