Ip solicitudes resultados del congreso 
Eduardo dávalos, presidente de la junta electoral central, propuso que los diputados asumir la gran responsabilidad de ser un ejemplo para una mejor de sinaloa por los diversos retos a los que se enfrenta. 
Una legislatura de obras decentes y estado libre de acuerdos entre las partes y el ejecutivo es exigido por la empresa sector de mazatlán, porque hay una convulsionada sinaloa que se enfrenta a grandes problemas. 
Ayer el 60 legislatura fue votado en, integrada por siete fuerzas políticas de el partido revolucionario institucional (pri), 13, 19 diputados del partido, tres de la nueva alianza paneuropea, dos del prd, uno de los pt, uno de la convergencia y que más de la pvem, es decir, un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del congreso del estado - se ha dicho que vienen a cumplir una gestión limpia de compromiso a la sociedad y los distintos sectores que requieren una labor legislativa responsable. 
Coordinación eduardo dávalos zamora, presidente de la empresa, ha propuesto que el consejo sólo liberados 40 diputados del congreso del estado asumido la gran responsabilidad de ser un ejemplo para una mejor de sinaloa por los diversos retos a los que se enfrenta. 
Esperamos que los diputados ejerzan su derecho, libre de acuerdos entre las partes, porque es una costumbre hacer acuerdos para vigilar por sus propios intereses y se convierta en un personaje de carnaval parlamentaria de los gobernadores y los líderes de las facciones. 
Por esa razón ha hablado de la certificación del compromiso a fin de establecer los puentes que podría ayudar al gobernador a seguir adelante. 
Esperamos que llegue a hacer un buen trabajo y cometidos principalmente a la sociedad y los sectores porque los habitantes de sinaloa fueron los que les dieron el voto de confianza durante las últimas elecciones. 
José ramón manguart sánchez, presidente de la asociación de los hoteles tres islas, consideró que uno de los mayores retos para los representantes 40 popular es el de presionar y añadir fuerzas en la búsqueda del crecimiento económico del estado, porque hoy en día, la situación económica es muy complicado. 
Lo más importante es para impulsar el crecimiento económico, que genera incentivos para la inversión e infraestructura y que de alguna forma una nueva generación de puestos de trabajo. 
En cuanto a la actividad turística, pidió que los nuevos legisladores dar el peso revisada en el presupuesto del estado para fortalecer el secretario del turismo. 
Como he entendido esta es la segunda departamento del estado con menos presupuestos y es incongruente una importante actividad económica y generar monedas y la inversión y que compita directamente con la industria agrícola. 
Además de imponer una obligación de etiquetado recursos el detonante de proyectos turísticos que ayudar a dar seguridad al estado derecho y actualizar el alcohol que no ha sido capaz de resolver en las legislaturas anteriores. 
