Israel: El caos Lab.
"Nada viene de la violencia y nunca nada podría", de Sting Frágil, donde uno de los principales versos del estribillo es "Prohibido olvidar cómo somos frágiles".
"Si mis hijos no quiere la guerra, no habría ninguna", dijo el moribundo Gutle Schnapper, esposa de Mayer Amschel Rothschild en 1849.
La última oleada de violencia entre Israel y la franja de Gaza, como siempre, ha provocado un montón de reacción.
Algunos están por Israel, argumentando que tiene el derecho de legítima defensa, y los palestinos son presentados como terroristas, mientras que otras de apoyo a los palestinos, alegando que el racismo por parte del Estado de Israel, afirmando que se está cometiendo un genocidio contra los árabes palestinos, y que Israel es un Estado terrorista.
Yo no quiero detenerme, en estas repetidas olas periódicas de matar, sobre quién es el transgresor y quién es la víctima, después de todo, los habitantes de hoy de Israel, incluyendo los territorios autónomos, nacieron en la situación política actual, y no vivir el comienzo de la violencia.
Me gustaría ofrecer a los lectores un vistazo detrás de las escenas, un vistazo a los que, por encima de todo, el 95 años de tensión es servir (a partir de la declaración Balfour en noviembre de 1917) en este pequeño pedazo de tierra en el Oriente Medio.
Algunos de mis pensamientos están apoyados por los hechos históricos, mientras que otros se derivan de mi propia idea de quién, es decir, que un grupo de personas es la principal fuente de los acontecimientos en la historia moderna.
La historia humana está en el primer lugar de la lucha por el poder.
En cada época podemos encontrar un Alejandro Magno o un Napoleón.
Lo que no es tan claro es si estas fueron las personas, que había elegido su camino de manera independiente, o si detrás de su trono era alguien que ha dirigido sus acciones hacia un objetivo pre-calculada.
Debemos aceptar que vivimos en un momento en que el mundo de la riqueza está concentrada en las manos de unos pocos individuos, y que esta concentración de la riqueza y el poder que emana no podía suceder en una generación de la vida.
Entre estos astronómicamente ricas familias, destaca uno, lo que podría considerarse el titiritero (si alguien se sitúa por encima de ellos, estoy seguro, pero yo no descartarla) - los Rothschilds.
No se ha escrito mucho sobre ellos.
Comprensiblemente.
La primera agencia de noticias (Reuters) compraron en la década de los 90 del siglo XIX, para evitar su nombre está relacionado con los actos de la delincuencia, que apareció en sus antecedentes y siempre que significó obtener el poder, la creciente riqueza, o ambos.
Ellos tienen participaciones mayoritarias en casi todos los bancos centrales en el mundo, y en contra de los países, donde no celebrar un juego, están librando o preparando para la guerra (antes del asalto a Afganistán fue siete países, después de Irak fue 5, tras el derrocamiento de Kaddafi 4 se mantuvo, pero entretanto Rusia presentó su banco central para el Gobierno ruso).
Quienquiera que intentaron desafiar esta familia murieron.
Abraham Lincoln se negó a renovar el estatuto del banco central a los Rothschild Bank of America, y durante la Guerra Civil comenzó a emitir su propia (que se emitirá el estado) y el dinero fue asesinado en 1865 en el teatro.
JFK comenzó a expedir su propio dinero y quería cerrar la Reserva Federal (Fed), y fue asesinado en 1963, el congresista Luis McFadden fue envenenado en 1936, después de que él tenía la intención de demandar a la Fed por causar la Gran Depresión de 1929.
De su formulación del lo y 1871 deseo a un centenares de de 3 mundiales y poder de mundo dirigir del la en, y Albert Pike 5 licenciatura del líder planificar freemason por la la guerra
La primera guerra fue para eliminar los grandes organismos estatales monárquica en Europa, el segundo fue para eliminar dominio colonial, especialmente de Gran Bretaña, y la tercera reducirá la población del mundo hasta 0,5 - 1 mil millones de personas (este número de esclavos será suficiente para su confort y lujo, y no hará uso de tantos recursos), la creación de una fe universal (ecumenismo es sólo un aperitivo para esta solución) y, finalmente, la toma del poder absoluto.
El método, que el grupo de familias adineradas con los Rothschilds abriendo el camino, emplean es la instigación de crisis, seguido por el ofrecimiento de una solución (fin ab Chao, el orden del caos).
Estas soluciones son falsas, sin embargo, y siempre conducen a una situación peor (vide establecimiento de la Reserva Federal, para que no se repita la crisis de 1907).
Así, tras haber logrado asesinar a Ferdinand, el heredero al trono austrohúngaro en Sarajevo, lo que desencadena Primera Guerra Mundial, destruyeron Zar de Rusia con la revolución bolchevique.
La Primera Guerra Mundial terminó abruptamente, militar y económicamente infundadas, con capitulación alemana (la guerra ya no era necesario para destruir Zar de Rusia) y las principales potencias europeas de Austria-Hungría fueron desmanteladas.
Para facilitar la creación de la Segunda Guerra Mundial, que permitió a los banqueros y políticos para crear una situación de conflicto latente por embargar Alemania con enormes las reparaciones de guerra, haciendo un ejemplo radicalist de las masas empobrecidas, sigue siendo sólo para introducir un culpable lo suficientemente convincentes y un líder con una solución simple, mientras que también crear un multi-racial Checoslovaquia con una fuerte minoría alemana para jugar y, de hecho, hizo el papel de un quinto colonia, una vez que la guerra había sido encendió.
Al final del siglo XIX, los Rothschilds instigaron la creación del movimiento sionista, una rama de los que trabajaron para formar el Estado judío, buscar una zona de Judea, Jerusalén, para hacer su capital (el retorno a Sión).
La citada Declaración Balfour formó la base de la inmigración masiva de judíos a Palestina, donde comenzó la primera conflictos con la población árabe local.
Los ataques terroristas ocurrieron en ambos bandos.
Estalló la Segunda Guerra Mundial, y si Hitler rompió libres desde la raya, que los banqueros internacionales estaban celebrando en él, o si sus acciones fueron parte del plan, es difícil de determinar, sin embargo, el sufrimiento de los judíos europeos en los campos de concentración creó la fundación a la aceptación del mundo del Estado judío.
Israel fue oficialmente fundado en 1948, y tal como las reparaciones de guerra de la Segunda Guerra Mundial, en Alemania, el anuncio del Estado de Israel se convirtió en el tercer foco de la guerra.
Proporcionó el éxito los banqueros internacionales, la nación judía, como con el segundo, serán las víctimas en la primera línea, ahora junto con la población árabe, o más generalmente, los musulmanes del Oriente Medio.
Israel es como un gran laboratorio, una fuente de discordia y el caos no sólo en el país, pero a nivel internacional (sólo miren cómo las personas están divididos en partidarios y detractores de Israel).
¿Quién es el hacedor y quién es la víctima en el conflicto Israel-Palestina, donde la injusticia alimenta la injusticia en un ciclo interminable de violencia, mientras que todo comenzó desde la codicia de unos pocos y su ansia de poder global?
Aquí, debemos diferenciar entre la población general de Israel y sus dirigentes, porque, al igual que ocurre aquí, los banqueros internacionales introducir su propia selección de candidatos a la gente a votar.
El actual primer ministro de Israel, Netanyahu "el halcón", es un ejemplo típico de un político fascista, leales a los banqueros internacionales, que hace todo lo posible para instigar la guerra con Irán, que, debido a su ingreso en la Organización de Cooperación de Shanghai (China, India, Rusia, Pakistán,...) conducirá a una mayor amenaza de un conflicto mundial y, a través de su control del estrecho de Ormuz, donde el 20% del petróleo del mundo deben navegar (el canal está a sólo 2 kilómetros de ancho), a la destrucción de la economía mundial.
En vista de lo que son las palabras, pronunciadas por David Rockefeller en 1994: "Todo lo que necesitamos es una gran crisis y las naciones acepten el Nuevo Orden Mundial".
El Nuevo Orden Mundial en sus ojos es uno de maestro y esclavo.
Un mundo donde el resto de la población humana servir el lujo de un puñado de aristocracia financiera.
Un mundo, donde cada recién nacido se implanta con un chip, lo que hace que su existencia completamente sometida.
"Él también obligó a todos, grandes y pequeños, ricos y pobres, libre y esclavo, para recibir una marca en su mano derecha o en la frente, por lo que nadie podía comprar o vender a menos que él tenía la marca, que es el nombre de la bestia o el número de su nombre.
Si alguien tiene información, calcular el número de la bestia,
Para ello es el número del hombre y su número es seiscientos sesenta y seis ".
