La señora Sofía: &quot;Son instrumentos de progreso y esperanza&quot;
La reina pone de relieve la &quot;dominante&quot; en España en relación con este tipo de financiación
España &quot;ha logrado un lugar destacado en todo el mundo en el papel de las microfinanzas&quot;.
Reina Sofía, recordó ayer que el país se ha convertido en las últimas dos décadas, el segundo donante en relación con los instrumentos de cooperación, cuya &quot;esencia&quot;, dijo radica en ser un instrumento &quot;para el progreso de la justicia social, y la esperanza de un futuro mejor para todos la humanidad, basada en la confianza en los seres humanos. &quot;
La Reina inauguró ayer la Quinta Conferencia Mundial de Microcrédito celebrada en Valladolid con la creencia de que &quot;no hay duda&quot; de que estas operaciones son &quot;absolutamente esencial&quot; para alcanzar los Objetivos del Milenio fijados por las Naciones Unidas para el año 2015, y, &quot;sobre todo teniendo como meta reducir a la mitad el volumen de personas que viven con menos de un dólar por día, con esta fijación de la &quot;línea de pobreza.&quot;
España se &quot;sigue trabajando&quot; para ampliar la red de beneficiarios en todo el mundo, y asume la tarea con &quot;responsabilidad&quot;, dijo la señora Sofía, que espera que los esfuerzos y contribuciones se originó en la Cumbre, que se celebrará hasta el jueves, se &quot;garantizar la creación de nuevas capacidades y mejores oportunidades para las personas más pobres, y especialmente para las mujeres,&quot; los principales beneficiarios de estos préstamos.
Hay &quot;muchos logros&quot; y &quot;muchos desafíos que enfrentamos.&quot;
La Cumbre del Microcrédito se plantea no sólo como un foro para el debate, sino también como una plataforma que promueve &quot;dos objetivos fundamentales.&quot;
Por lo tanto, Su Majestad explicó que espera que a finales de 2015, 175 millones de familias pobres se han adherido a estos servicios financieros y de cien millones de estos hogares va a salir de la pobreza en que están inmersos.
El impulso para la creación de microcréditos en España y en el resto del mundo &quot;ha seguido el camino iniciado hace años&quot; por Muhammad Yunus, destacó la señora Sofía como un &quot;acto de justicia y reconocimiento&quot;.
Y ella se describe el padre de esta herramienta como un &quot;idealista admirable de la causa universal de la lucha contra la pobreza&quot;, cuyo trabajo es conocido desde hace 15 años, cuando la reina se fue a Bangladesh para conocer en el ámbito de la política de préstamos.
Esta experiencia fue seguida un año después por la primera Cumbre Mundial en Washington y en otras reuniones como las celebradas en Costa de Marfil en 1999, Canadá 2006, y &quot;en todo lo que he visto la evolución continua&quot;, dijo Su Majestad, cuyo vínculo con este del proyecto la hizo ganar ayer el título de &quot;jefe de familia&quot; en Valladolid desde el &quot;banquero de los pobres.&quot;
Por último, el Reina Sofía, la señora concluyó alentando a los presentes a participar en el debate y encontrar soluciones para avanzar en la lucha contra la pobreza.
&quot;Imperativo ético&quot;
Ministro de Asuntos Exteriores, Trinidad Jiménez, dijo que la solidaridad &quot;es un imperativo ético&quot; para todos los estados democráticos.
En este sentido, dijo que sería un error vincular la cooperación con los países en desarrollo en tiempos de bonanza económica, ya que es una &quot;obligación de continuar.&quot;
Jiménez encontró que el microcrédito supone &quot;una política seria y rigurosa dedicada a la erradicación de la pobreza,&quot; y ahora &quot;más que nunca,&quot; los gobiernos de los países desarrollados deben trabajar bajo los criterios de solidaridad y no dejar que esta caída como víctima de los ajustes.
Para España, el microcrédito es &quot;una de las principales líneas de cooperación al desarrollo.&quot;
El Secretario de Estado de Cooperación Internacional, Soraya Rodríguez, alabó el &quot;éxito&quot; para dar &quot;confianza&quot; a los &quot;excluidos a la que todas las puertas están cerradas&quot;, y el alcalde de Valladolid, Francisco Javier León de la Riva, dio la bienvenida a los presentes a una ciudad que &quot;abre sus puertas atrapadas por el espíritu de solidaridad&quot;.
