El tribunal valida &quot;transición a la televisión digital&quot; en México en 2015
La sustitución de analógico a digital es uno de los cambios más importantes que ha golpeado el mundo en los últimos años
La Corte Suprema de Justicia (SCJ) rechazó las controversias constitucionales presentadas por el Senado y la Cámara de Representantes contra el decreto presidencial que lleva adelante la llamada &quot;transición a la televisión digital&quot;, desde 2021 hasta 2015, ya que los ocho votos necesarios para invalidar fuera no obtenerse.
Una minoría de cuatro ministros, incluido el Presidente de la Corte, Juan Silva Meza, consideró que el presidente Felipe Calderón no excedió su autoridad al emitir un decreto que detalla las acciones a tomar con el fin de lograr la transición a la televisión digital terrestre.
Con este resultado, la controversia constitucional promovida por el Senado, fue rechazado por no cumplir con la mayoría calificada de ocho votos para que la Corte se pronuncia sobre la constitucionalidad o inconstitucionalidad del decreto, y esto sigue vigente.
El proyecto de sentencia elaborado por el ministro Olga Sánchez Cordero, propuso que se declare inconstitucional el decreto, debido a que la regulación de los materiales de radio y televisión es un poder reservado por ley a la Comisión Federal de Telecomunicaciones (Cofetel), en violación de los principios de subordinación jerárquica y ley de la reserva.
Sólo Zaldívar, Jorge Mario Pardo, Margarita Luna y Cordero Sánchez votó por el proyecto.
Con este argumento, tanto en el Senado y la Cámara de Diputados promovió dos controversias constitucionales en contradicción con el decreto, y para apoyar las reivindicaciones, la ministra Sánchez Cordero, suspendió la aplicación del decreto y todas las acciones que se estipula que con respecto a la transición digital.
A los ministros de la &quot;reunión se decidió también a rechazar la demanda interpuesta por la Cámara de Diputados, sin entrar en la discusión del proyecto, también a cargo de la ministra Sánchez Cordero.
En su discurso, el ministro dijo que no estaba de acuerdo con los argumentos del proyecto en el sentido de que el ejecutivo federal no se puede estructurar a través de normas generales de las medidas de la administración pública para prepararse.
&quot;Tampoco considero que si se afectaría la autonomía del órgano regulador&quot;, y recordó que la planificación de las políticas públicas en áreas estratégicas como el sector de las telecomunicaciones corresponde al Ejecutivo Federal, que tiene un mandato constitucional, la orientación de la Estado.
La sustitución de analógico a digital es uno de los cambios más importantes que han afectado al mundo en los últimos años, y resulta en un mejor aprovechamiento del espectro radioeléctrico, una mejor calidad de señal y más canales.
El retraso en el cambio, dijo, significaría retrasar los beneficios de la digitalización, lo que implica una decisión de interés público, que no sólo tiene una dimensión técnica, &quot;ya que cubre económico, social, política y temas de seguridad nacional.&quot;
Estos temas, dijo, &quot;requieren la operación de todo el sistema establecido en virtud del principio de la administración económica del Estado, comprende un conjunto de atribuciones que la Constitución conduce al poder ejecutivo del estado.&quot;
Recordó que un gran número de países de todo el mundo se ha completado la transición digital, y lo ha hecho a través de la ejecutiva, a pesar de contar con organismos técnicos altamente especializados.
No se puede concluir que el gobierno, mediante la emisión de la sentencia impugnada, que invade, en modo alguno la competencia del Congreso, está prestando en el área administrativa de la observación de las leyes emitidas por el Poder Legislativo, dijo.
