La adversidad climática desaceleró la economía
Durante el primer año de gestión de Mario López Valdez, en Sinaloa aumentó el desempleo y la informalidad, la inversión extranjera disminuyó y la economía se redujo.
2011 es un año que será recordado en la historia económica de Sinaloa, que se relaciona con el primer año de gobierno de Mario López Valdez, también llamado el año del cambio, lo que generó grandes expectativas en cuanto al desarrollo de la economía, pero dada la adversidad climática del comienzo del año, no hubo crecimiento, sin embargo, había registrado una disminución en los principales indicadores de desarrollo económico.
Las bajas temperaturas de febrero, no sólo causan pérdidas millonarias para el sector agrícola, sino que se limitan las posibilidades de la economía del estado para crecer, provocando una contracción de la actividad económica en general del 3,6 por ciento en el primer semestre del año, apoyado principalmente por la caída histórica del 31,16 por ciento en la agricultura, lo que afectó la dinámica de otros sectores económicos.
De acuerdo con el informe sobre las zonas afectadas por las heladas, emitido por el Consejo Mexicano para el Desarrollo Sostenible del Medio Rural que se dañaron 835.582 hectáreas, de las cuales 78,03 por ciento sufrió daños totales y el resto del 21,07 por ciento tenía daños parciales. Los cultivos dañados fueron los principales hortalizas, maíz y garbanzo.
La caída en la actividad económica ha generado, hasta noviembre, un aumento constante del desempleo en el estado, según el Instituto Nacional de Estadística y Geografía, la tasa estatal de desempleo durante los tres primeros trimestres del año registró un crecimiento acelerado, a partir de de enero a marzo de 55.053 habitantes de Sinaloa estaban en el paro, con una tasa de 4,53 por ciento de la población económicamente activa para el segundo trimestre, la tasa se convirtió en 5,28 por ciento, y entre julio y septiembre el promedio siguió aumentando a 6.19 por ciento, una tasa que, en términos del número de personas que representa a más de 74.000 desempleados de los habitantes de Sinaloa, un aumento en comparación con el primer semestre de 18.969 personas.
La menor liquidez
El desempleo en Sinaloa durante el año es multi-factorial, para el economista Gerardo López Cervantes, director de la Facultad de Ciencias Económicas y Sociales de la UAS, el crecimiento del desempleo se puede explicar indirectamente, en función de las acciones que la política pública ha sido tomada.
&quot;Lo que estamos viendo ahora es un aumento del desempleo que tiene que ver con varios factores, incluyendo la pérdida de liquidez en el mercado con el fin de una limitación de recursos impuesta por la legislación que fue aprobada en el Congreso con el fin de combatir el blanqueo el lavado, ya que para las personas que ilegalmente poseen dólares no es un trabajo fácil con, invertir y usarlos en algo &quot;, dijo.
Inmigración detuvo
López Cervantes dijo que en el aumento del desempleo hay también un factor demográfico.
&quot;El número de personas que abandona el estado en busca de un trabajo en el extranjero, en los Estados Unidos se ha restringido, en primer lugar debido a las dificultades para entrar, y en segundo lugar, porque una vez que entran ya tienen demasiadas dificultades para encontrar un trabajo, ese grupo de personas que se encuentren y exigiendo puestos de trabajo aquí, en el estado, haciendo que la tasa de desempleo en aumento &quot;, dijo.
Informalidad
El análisis del mercado laboral de Sinaloa se agrava cuando se considera el alto nivel de informalidad que prevalece entre las condiciones de trabajo, de acuerdo con el INEGI, 60.38 por ciento de la población activa trabaja en el estado sin ser citado por los trabajadores a cualquier institución de seguridad social.
Además del desempleo y la informalidad, otro recordatorio de la mano de obra del estado está representado por los bajos salarios, la entidad tiene los salarios más bajos en el país, de acuerdo con los registros del Instituto Mexicano del Seguro Social y el Ministerio de Trabajo y Previsión Social.
El ingreso mensual promedio de los trabajadores de Sinaloa era, hasta septiembre de 5.352 pesos, muy por debajo de la media nacional, que es de 7.375 pesos.
La contracción de la IED
Además de la caída de la actividad económica y la alta tasa de desempleo, en el año 2011 no se registró la mayor caída de la inversión extranjera directa en los últimos 10 años, de acuerdo con el Ministerio de Hacienda, de enero a junio, la IED ascendió a 630.697 dólares del Estado, lo que representa una caída del 87,74 por ciento en comparación con los 5.143.312 de dólares durante el mismo período del año pasado.
Por su parte, el Ministerio de Desarrollo Económico del Gobierno del Estado representaron una inversión total de 17.280.000 de pesos durante el año, que tuvo lugar principalmente en las empresas del sector terciario.
Deuda
En el contexto de crisis económica, el gobierno del estado pidió en julio durante el Congreso del Estado, la aprobación de un crédito de 3 mil millones de pesos, lo que sería para la inversión en proyectos de infraestructura en 18 municipios, con el fin de reactivar la economía, el local de la aprobación del Congreso era para un total de 2.600 millones de pesos, y hasta noviembre no los beneficios de la deuda se observaron en todos los sectores de la economía del estado.
Reacciones
Para los representantes empresariales, el primer año de gobierno de Mario López Valdés demuestra una falta de capacidad del gobierno.
Miguel Loredo López, presidente de la Cámara Nacional de la Industria de la Transformación, dijo que durante el año 2011 hubo una falta de armonización de las voluntades de los diversos sectores, incluyendo el propio gobierno del Estado.
&quot;El desempeño de la economía en Sinaloa este año ha sido muy pobre, uno tiene que trabajar duro para recuperar el terreno perdido este año, en el año 2012 tenemos que redoblar nuestros esfuerzos, pero no hemos podido alinear los esfuerzos de todos y sobre todo la el bien y el movimiento sincronizado del nuevo equipo de gobierno, esperamos que el próximo año será mucho mejor &quot;, dijo.
La lentitud económica
López Loredo, dijo que los eventos como las heladas a principios de este año se detuvo la economía del estado y su desempeño y el crecimiento se limita.
&quot;El flujo económico bajo es el producto de varios eventos, incluyendo las heladas, uno de los principales efectos ha sido una desaceleración de la economía que no gire lo suficientemente rápido como para generar un dinamismo económico que permite tener un nivel aceptable de flujo de los procesos, productos y servicios y por lo tanto, al final del año lo estamos cerrando por debajo de nuestras expectativas &quot;, dijo.
La redefinición de la vocación
Teodoro Salazar Uriarte, presidente de la patronal &quot;Confederación de la República Mexicana en Sinaloa, dijo que el Estado está obligado a enjuiciar a las actividades productivas más dinámicas.
&quot;En general, encontramos que se ha estado trabajando, creemos que es necesario desarrollar un programa a largo plazo que redefine la vocación y el rumbo económico del estado, es importante para detonar todo el material y recurso potencial humano que tiene Sinaloa , &quot;, dijo.
Trabajo por hacer
Coparmex Presidente hizo hincapié en la importancia de establecer una visión de futuro para orientar mejor los esfuerzos del gobierno.
&quot;En general, diría que el Gobierno se ha esforzado para tener éxito en diversos ámbitos, en términos de desarrollo económico ha habido algún progreso, pero es importante para desarrollar un programa a largo plazo&quot;, dijo.
Señaló que la actual administración ha demostrado un progreso en su propia manera de conducir la política pública.
&quot;Hay elementos que nos permiten decir que el gobierno es cada vez más incluyente, y lo que puedo decir es que hay trabajo por hacer y creo que el gobierno es consciente de que hay trabajo por hacer&quot;, dijo.
