No se deben hacer aportes a las obras
Las obras sociales que se refieren los programas como Hábitat, Rescate de Espacios Públicos y 3x1 para el riesgo de los migrantes no deben ser completadas o tener graves retrasos debido a la falta de fondos, dijo Miguel Ángel López Miranda.
El Director de Desarrollo Social Municipal indicó que si bien hasta ahora los programas de trabajo han avanzado que están en riesgo debido a que el Gobierno del Estado dejó de pagar las contribuciones que correspondan, que representan un recurso superior a los 11 millones de pesos en los tres programas.
Señaló que la inversión total en estos tres programas es de cerca de 50 millones de pesos, de los cuales el Estado tiene que contribuir con 25 por ciento y hasta el momento sólo la Federación y el Municipio han proporcionado recursos para las obras, por lo que el posible retraso en la finalización de ellos está en vigor.
&quot;Tienen que contribuir con casi 12 millones y, aunque el año está por terminar no nos han dado ni un centavo, ya que a partir de julio se nos tenía que dar una parte&quot;, dijo, &quot;a fin de no retrasar la hemos iniciado el obras y son muy avanzado, pero necesitamos el dinero &quot;.
Mencionó que el año pasado, durante la administración de Jesús Aguilar Padilla, el Estado no cumplió con las contribuciones que tenían que hacer, por lo que al principio de la administración del municipio tuvo que pedir dinero prestado para cubrir más de 7 millones de dólares, una suma que no fue proporcionada para esa ocasión por la administración del Estado.
&quot;Se nos pasó a nosotros en la administración anterior, porque el Estado no tiene la capacidad financiera para participar y los programas continuó avanzando, y este año con el fin de acceder a estos programas que teníamos que conseguir los recursos para cubrir lo que el Estado dejó pendiente&quot; explicó.
Aunque no existe un compromiso de las autoridades estatales para cumplir con la entrega de estos recursos, dijo que la petición fue hecha a la Secretaría de Administración y Finanzas, Armando Villarreal, para acelerar los esfuerzos para que los porcentajes que corresponden a que vengan lo más rápidamente posible.
&quot;Tienen que contribuir con casi 12 millones y, aunque el año está por terminar no nos han dado ni un centavo.&quot;
