" Sangre del mayo ", un desaf¡o pico por Garci. 
Jos Luis Garci, inspirado por el nuevo Episodios Nacionales de Banito P+©rez Gald+Ýs, recrea en Sangre del mayo el alboroto popular espa¤ol contra el francs. ste es el trabajo m s ambicioso de su filmograf¡a, con un casi 15 millones de euro presupuesto. 
Con esta pel¡cula, el director ha intentado explicar el torrente de car cteres y al mismo tiempo el an lisis " social que l siempre admir¢ en el trabajo del novelista famoso, l dijo hoy, durante la presentaci¢n de la pel¡cula, con Quim Gutierrez y Paula Echevarr+­a que encabezan un lanzamiento m s grande de intrpretes. 
Sangre del mayo, una pel¡cula m s largo que 2.30 horas, debuts este viernes en los cines, para volverse un cuatro miniserie de TELEVISIàN de horas en TeleMadrid en el pr¢ximo futuro. 
El gran entusiasta de literatura de Gald+Ýs', Jos Luis Garci exige este tiroteo comprendi¢ " un sue¤o de su ni¤ez ". Le gusta agradecer Esperanza Aguirre que, tres a¤os m s temprano, lo hab¡a comisionado disparar una pel¡cula para conmemorar el segundo centenario de la Madrid 2 de mayo. ste era el deseo expresado por la Comunidad de Madrid. El director estaba de acuerdo en condici¢n que la historia conect¢ con tierra en el nuevo Episodios Nacionales. 
El 15 millones de presupuesto totalmente asignado por la Comunidad de Madrid representada para Garci una " £nica oportunidad " de recrear los juegos apropiados y trajes para retratar una " Espa¤a aturdida que escogi¢ al l¡der malo para luchar para y el hecho que la lucha para la independencia llev¢ a las personas a un retraso grande en el desarrollo durante el reino de Ferdinand VII " Garci. 
Sin embargo, el director siente no habiendo recibido fondos iguales de Alatriste o fantasmas de Los de Goya - m s de dos veces compar¢ a Sangre del mayo. Hasta ahora, no era posible disparar algunas escenas incluido en el plan, l hab¡a firmado junto con Horacio Valcarcel, su colaborador carrera-largo. 
La diferencia de presupuesto influy¢ en la manera usual de trabajar del director de Volver un empezar: por ejemplo, el organizando con los actores con quienes l usa a menudo para ensayar antes de disparar junto con el ones que no pertenece al lanzamiento, mientras considerando este " humillante " y pensando que " el trabajo del director queda yendo al teatro y al cine para comprender c¢mo la industria para que l est  trabajando est  siguiendo. 
Un cierto n£mero de intrpretes algunos de los cuales se caen dentro del lanzamiento de Sangre del mayo repite delante de su video-c mara. Es el caso de Michael Rell, Carlos Larranaga o Fernando Guillen Cuervo. 
Cuatro veces en el Oscar las nominaciones - ganando uno - Garci cree que ninguno de las tres pel¡culas del candidato represente Espa¤a en Hollywood este a¤o, su Sangre del mayo, las colinas de Siete del franc+©s del billar, y el Los seleccion¢ los ciegos de girasoles de ulitmo representan la generaci¢n m s joven del cine espa¤ol " que debe conocerse en cambio ". 
Garci no espera los premios de esta pel¡cula. 
" Al principio usted piensa en funcionamiento para la posteridad, entonces usted s¢lo comprende usted trabaja para la prosperidad, y a cierto punto usted dispara apenas m s una pel¡cula, " dice Garcia despus de m s 30 a¤os de carrera. 
