Las drogas: Nunca con los jugos de fruta. 
Tenga cuidado de jugo de la toronja, jugo de naranja, y jugo de la manzana. 
Estas bebidas, sobre todo consumi¢ en verano porque ellos son sed que apaga y rico en las vitaminas, si tomado de salvamento junto con algunos que las drogas pueden alterar a su absorci¢n, mientras amplificando o disminuyendo, dependiendo del caso, su eficacia con consecuencias que tambin pueden ser serio para la salud. 
Confirmando los riesgos asociados con la asunci¢n de jugos de fruta si ellos se pre-empaquetan o fresco con ciertas medicinas la David Bailey est , profesor en la universidad de Ontario Occidental en Londres que de la 236 reuni¢n nacional de la Sociedad Qu¡mica americana pasando en los lanzamientos de Filadelfia una nueva advertencia: un vaso de jugo de la toronja, el jugo de naranja, o el jugo de la manzana es bastante para reducir la absorci¢n de salvamento de cierto las drogas, mientras anulando sus efectos beneficiosos y poniendo al riesgo la salud de pacientes. 
El jugo de la toronja ya se ha acusado porque se pensaba que era responsable para levantar, a a los niveles pens¢ ser t¢xico, los efectos de alg£n antirhythmic, antibi¢tico, tranquilising, antihistaminic, y las medicinas neurol¢gicas. 
Las DROGAS Al RIESGO â La muy misma italiano Droga Agencia hab¡a dado el mismo consejo en una factura de informaci¢n hace dos a¤os, alertando a doctores y pacientes para no infravalorar los peligros que derivan de esta mezcla y prestar la atenci¢n acerca de lo que es bebido en los casos cuando se toman las drogas como por ejemplo Diazepam o Methadone. 
No s¢lo el JUGO de la TORONJA â seg£n los expertos el jugo de naranja igual y jugo de la manzana contienen substancias que inhiben las drogas. 
La lista de principios activos inhibida por la toronja y otros jugos de fruta son muy largos. 
De la apelaci¢n de Michele Carruba, director de la Secci¢n de Farmacolog¡a de la Universidad Estatal de Milan: " Normalmente, se traen los tales descubrimientos inmediatamente a la atenci¢n de las varias agencias de droga internacionales y nacionales que entonces cambian los resbalones de informaci¢n de medicinas. 
Por consiguiente, siempre lea las notas explicativas de las medicinas tomadas y si hay algo que no est  claro, no tenga miedo preguntarellos al doctor o a qu¡mico para clarificaci¢n-+ acentu¢ al experto de la Agencia de Ansa. 
