La lite en el peligro 
El fen¢meno ya se hab¡a manifestado atr s un par de d¡as con el voto en la C mara de Representantes contra el plan del rescate de 700 mil millones d¢lares americanos pasado por la Casa Blanca: una porci¢n significante de americanos era, y todav¡a es, m s interesado castigando la Calle de la Pared que ahorrando la econom¡a. 
Una confirmaci¢n se dio por los Nueva York Times de ayer cuando inform¢ que la crisis actual est  causando una raja dentro del Partido Republicano, en la vida m s dividido entre su alma de la Costa Oriental vieja, modere, en el favor de instituciones federales y la comunidad comercial, y su nueva alma, en cambio el to"those conservador, hostil en Washington-+ y al mundo financiero, especialmente fuerte dentro de los estados Centrales y Del sur. 
El alma, ser exacto que se han hecho vivo arrogantemente con el voto mencionaron inicialmente. 
El £ltimo es pero s¢lo un ejemplo de los cambios, de los cambios grandes que el terremoto econ¢mico actual quiz s heraldos o permite ser percibido: no s¢lo en los Estados Unidos pero tambin en todo el Oeste y quiz  no s¢lo aqu¡. 
Ambos en el EE.UU. como en Europa la crisis parece actuar como un catalizador para fen¢menos que han estado en la incubaci¢n durante alg£n tiempo y qu en el nuevo clima ha solidificado y ha estado viniendo a encender finalmente. 
El primero de estos fen¢menos es el trayendo moderno atr s, el re-lanzamiento extraordinario, de la estado-soberan¡a de la categor¡a gemela respecto a una clase de re-nationalisation de la econom¡a. 
La crisis, de hecho, es una crisis para las instituciones financiero-banca que tienen, de hecho, los lazos fuertes con los pa¡ses extranjeros, pero que sobre todo el trato con los presupuestos de personas o familias que viven en una sola naci¢n, en un solo estado. 
Esto crea un problema pol¡tico inmediatamente para quienquiera est  en el gobierno: y eso es c¢mo responder a las dificultades y las protestas de esas personas y esas familias que, adem s de, tambin forme el electorado. 
En otros trminos la crisis parece ser econ¢micamente mundial pero pol¡ticamente es casi exclusivamente un problema nacional. 
El internacionalismo pol¡tico aparece estar fuera substancialmente de obra o no tener mucho que decir: la prueba clara de esto se da por la Uni¢n europea que, dividi¢ como de costumbre entre los varios intereses y las estrategias estatales diversas, no puede decidir en un camino pol¡tico com£n. 
Y para que es del gobierno de cada solo Estado que toda la espera para la intervenci¢n, bailout y el re-lanzamiento planea, las nuevas reglas, y la ayuda especialmente financiera: desde que eso cuando viene a peor que es s¢lo los Estados que tienen los recursos financieros, la masa de recursos financieros capaz intentar y arreglar las cosas. 
Y ellos poseen los medios necesarios igualmente, y las razones leg¡timas para usarlos: dos recursos de valor inconmensurable, bajo ciertas circunstancias de que probablemente ning£n mercado y ning£n organisation internacional podr¡a disponer en la vida de en una medida an loga. 
Este nuevo nfasis que la crisis propone en el elemento statal-nacional est  perfectamente despus de todos puestos a punto con el en la vida importancia creciente que los £ltimos desarrollos econ¢micos tienden a atribuir a un coeficiente que es muy estrechamente conect¢ a ese elemento: el territoriality. 
Parad¢gicamente, de hecho, mientras nos convencieron que nosotros hab¡amos entrado en el reino del tejido, de una tecnolog¡a en aumento m s sofisticado, del inmaterial, mientras nos convencieron que la finanzas del globalised fue destinada para dominar el mundo ahora, nosotros nos dimos cuenta repentinamente que nuestro futuro ten¡a que repartir en en cambio un en la vida la moda creciente con esas cosas que son muy peque¤o inmaterial como el agua, cosechas, el aceite. 
Accidentalmente, todos son art¡culos que pueden transportarse ciertamente de un lugar a otro pero en cualquier caso pueden atarse en una moda absoluta a un espacio bien definido, a un territorio. 
Para que quienquiera se encuentre ser el soberano, ciertamente contiene m s tarjetas su engalane que l quin no es, que l quin pasa para vivir en un lugar sin las cosechas, aceite, o agua. 
Yo estoy consiguiendo a la segunda novedad que sin embargo predice una raja. 
Quienquiera dice el Territorio, el Estado, el Gobierno, implica la Pol¡tica inevitablemente, y de la Direcci¢n. 
En este respeto la crisis econ¢mica parece producir dos fen¢menos convergentes. 
En la una mano el conocimiento de la necesidad objetiva para la direcci¢n autoritaria, la demanda para alguien que conoce ocuparse de la situaci¢n. 
Por otro lado una ola de descrdito para la direcci¢n existente, una clase econ¢mica, revelada para ser tan inadecuado y lleno de  reas grises. 
Y juntos algo en la vida m s profundo y un cierto manera perturbando: un descrdito, una intolerancia, una imagen de insuficiencia, un sentido de lejan¡a que tiende a involucrar la clase gobernante entera de un n£mero en la vida-creciente de pa¡ses Occidentales. 
M s bien, parece hacer su manera llevar m s all  en las inmensas secciones de la poblaci¢n la convicci¢n que antes de que sus acciones son ahora las mismas ideas a partir de la lite social a la gaveta en el favor, su manera de sentirse y ser, que su cultura en todos acept¢ los significados de la palabra, haber tenido su d¡a, y para siempre ser m s extranjero a la opini¢n de la mayor¡a. 
En otros trminos, la llamada para la direcci¢n alimenta clandestinamente un ech¢ ramas pero movimiento poderoso de delegitimization de la clase directiva y de las estructuras pol¡ticas tradicionales, ese manifiesto l en los electoral"revolts-+ s£bitos o las torceduras abruptas en los humores colectivos en stos dura y los £ltimos tiempos, del levantamiento conservador en Austria â Baviera al derrumbamiento del acuerdo general del labour en Gran Breta¤a, a la rebeli¢n de los diputados americanos contra Bush (y quiz s incluso la victoria del derecho en Italia tiene algo que hacer con l). 
Uno consigue la impresi¢n que la lite tradicional, sus fiestas, sus programas, pero tambin sus ritos, sus peri¢dicos, sus intelectuales acreditado, que algunos dir¡an a sus formatos, siempre est n encontr ndolo m s dif¡cil comprender, y de para representar, que que ha estado tomando la forma dentro de las capas m s profundas de sociedades occidentales y qu la crisis econ¢mica est  fortaleciendo, aumentando, agitando potencialmente sin el refrenamiento. 
En la cara de todos esto, hablando sobre el a"rebellion del masa-+ como ser el orden del d¡a puede exagerarse francamente. 
Pero guardando los ojos de uno ancho abren, no es con seguridad. 
