Usted es eso que usted la porci¢n 
En su 10 cumplea¤os Google puede admitir: est  all¡ en el bolsillo de las personas, as¡ como anteriormente su cabeza, en el cielo. Google sabe donde las personas siguen la vacaci¢n, qu tipo de consultaciones mdicas ellos visitan y lo en que ellos est n interesados. 
A pesar de todos que, Eric Schmidt, una persona importante de la compa¤¡a todav¡a no se satisface. 
Por otro lado, los sceptics que lo traen paralelo simplemente con la fantas¡a terrible de Orwell no pueden ver el ser de tejido 2.0. 
Eric Schmidt declar¢ recientemente a los Financial Times que la meta principal de Google era coleccionar la informaci¢n personal m s all  sobre los usuarios. Es necesario mantener el objetivo del original de los fundadores de Google, a saber,: para crear un sistema para toda la informaci¢n del mundo ", l agreg¢. 
Seg£n el Google-jefe, la compa¤¡a - despus de haber subvertido el mundo entero en los £ltimos 10 a¤os - todav¡a es al principio del camino hacia la habilidad de tratar toda la informaci¢n. 
¨Contestando la pregunta que involucra sus planes durante los pr¢ximos 5 a¤os l dijo que le gustar¡a asegurar ese Google podr  contestar a las preguntas gusta " Qu yo har ma¤ana "? , o " Qu tipo de traje de los trabajos yo el mejor "?. Sin embargo, el software no puede dar las respuestas correctas a stos las preguntas aparentemente simples desde la cantidad disponible de informaci¢n del usuario no es suficiente. 
No todos los usuarios de Internet son conscientes del hecho que las condiciones investigaron por ellos se graba, as¡ como la direcci¢n de IP us¢ para la b£squeda y las p ginas visitaron despus por ellos. 
Usando la funci¢n de la B£squeda Personalizada 2-a¤o-vieja, los usuarios pueden guardar sus propias historias del surf, ellos pueden repasar lo para que ellos estaban pareciendo, qu tipo de eslabones antes de que ellos hicieron clic adelante. En el trmino largo, puede proporcionarles los resultados personalizados a los usuarios. La funci¢n llamada que las Recomendaciones ser n basadas en la misma l¢gica: podr  ofrecernos los productos y servicios por la ayuda de las preferencias proporcion¢ y grab¢ antes. 
" Qu pasa si mis datos personales se usan contra m¡, si se descubre lo que yo hago "?, pregunte algunos de los usuarios que se preocupan por el informaci¢n-monopolio de Google. 
Normalmente es el grado del poder potencial representado por la compa¤¡a que genera la reacci¢n del contador en los usuarios, no el sentido de culpa, el miedo de castigo, el deseo para libertad o rebeli¢n contra la autoridad. 
No obstante, ha sido inveterado que todas las condiciones investigadas se graban y - donde apropiado - aqullos incluso pueden transferirse a terceras fiestas. En cosas as¡ embala nada protege el retiro de los usuarios de Internet. 
El ejemplo mejor para eso es la acci¢n convenida contra alg£n paedophiles brasile¤o; Google transfiri¢ al gobierno brasile¤o un poco de informaci¢n de uno de sus p ginas de la gesti¢n de redes sociales, Orkut llamado. Los datos proporcionados ayudado al gobierno a identificar varios paedophiles. 
Los usuarios que estaban preocup ndose por la invasi¢n de retiro personal pudieron el alivio atr s en mayo cuando Google - en la asociaci¢n con el EEF la organizaci¢n de ayuda legal electr¢nica - con xito demostrado su derecho contra el FBI: la corte confirmada eso bajo ning£n punto de la Constituci¢n enlata el FBI le obliga a Google a que proporcione cualquier amable de, la informaci¢n en secreto preguntada. 
(No obstante, - refirindose a la confirmaci¢n de la ley de la protecci¢n del ni¤o aprobaron varios a¤os m s temprano - el gobierno federal manej¢ hacer el acceso a 50 000 tejido se dirige y 1 000 condiciones de la b£squeda. Sin embargo, no podr¡a adquirir la b£squeda de los usuarios individuales lista, ni una lista completa de p ginas de tejido y palabras claves que cubren un periodo del dos-mes.) 
Como l parece, hay opiniones polmicas en Google. Se ataca por aqullos que temen de repartir sus datos personales porque ellos se sienten que su esfera ¡ntima y la vida privada ser¡an disminuidas usando los servicios proporcionados por Google. As¡, ellos prefieren represente el grupo resistindose de compa¤¡as de la multinacional conservadoras. 
Entretanto, los geek americanos cultivan y su avena salvaje que incluye la computadora entusi stica abanica, activistas, los usuarios en varios pa¡ses los consideran como la pr¢xima generaci¢n de compa¤¡as grandes, una " corporaci¢n " fresca, en contraste con su opini¢n sobre su rival, Microsoft, el creador de Windows y el conquistador del mundo, a pesar del hecho que las dos compa¤¡as luchan para la misma meta. 
Una de las razones para l puede ser ese Google - Microsoft diferente - no requiera el nombre de identificaci¢n de sus usuarios y dinero para las aplicaciones. Adem s, el abierto y continuamente puso al d¡a c¢digo de la fuente y paquete del programa - comparando a la pr ctica del gigante del software oficial - parece m s disponible, juvenil y fresco. 
O quiz  est  debido al hecho que los geeks pueden ver la relaci¢n problem tica precisamente entre el privilegio personal e Internet que est n de acuerdo con la expresi¢n importante frecuentemente discutida de los £ltimos a¤os tejido 2.0. 
Web 2.0 est  a punto de una colaboraci¢n para dejar los rastros intencionalmente sobre nuestras actividades de la computadora y aprovecharse de los cauces de comunicaci¢n disponibles. Aunque el grado de este acto puede ser varios, mientras dependiendo del usuario, el punto principal es el mismo: nosotros nos mostramos al mundo. 
Una media persona joven puede abrir un perfil en las varias p ginas p£blicas como Facebook o Xanga, ellos pueden unirselos incluso a otros servicios como Twitter o la m£sica liste a fabricante last.fm, entonces aqullos pueden conectarse a un sistema rastreando como FriendFeed o Blip.fm. Adem s, los usuarios pueden crear blogs que autom ticamente pone al d¡a el recientemente las galer¡as de fotograf¡a de uploaded guardaron en Flickr o Picasa. 
Nosotros podemos leer sobre varias historias as¡: la muchacha - verificando el uploaded de las fotograf¡as suficiente por la ma¤ana por los amigos com£nes - los hallazgos fuera d¢nde su novio poco fiable se pas¢ su noche anterior. U otro uno: un empleado podr¡a perder su trabajo s¢lo porque l comparti¢ su opini¢n en la direcci¢n en su blog. Una consecuencia puede dibujarse definitivamente: la definici¢n de retiro se ha revaluado. 
Si alguien vive una vida en l¡nea, ellos son lo que ellos muestran de ellos - ste es el concepto b sico detr s del behaviour de la juventud de hoy. 
Si alguien tiene algo que guardar confidencial o si alguien absolutamente s¢lo necesidades para desviar el monopolio de Google, tambin es posible (por ejemplo usando Scroogle que tambin aplica el Google investigan el sistema pero intencionalmente las hojas ning£n rastro detr s). 
El n£mero de aqullos que no registra intencionalmente a los sitios de la gesti¢n de redes sociales es significante. Esta manera ellos pueden evitar a ser descubierto, las aplicaciones en l¡nea de Google de editor del texto a gerente de la imagen y locutor pueden ser reemplazadas por versiones alternativas que no est n en relaci¢n con los parques del servidor grandes y no intentando crear nuestro perfil mejor en la vida. 
El p£blico general est  esperando ver lo que todav¡a est  oculto por Google. 
La compa¤¡a - con su valor de USD 156 mil millones - merece la pena m s de IBM (USD 140 mil millones), Intel (USD 124 mil millones) o Coca-cola (USD 110 mil millones). Adem s, la publicidad espacia de AdWords/AdSense amenaza el ingreso de anunciar agencias y servicios introducido a la causa de velocidad en la vida-creciente Microsoft y varios otros dise¤adores del software un dolor de cabeza serio. 
No obstante, los cr¡ticos tambin pueden encontrar los contrapuntos perturbando: la direcci¢n rechaz¢ la objeci¢n de los empleados fuera que estall¢ completamente porque la cuota del jard¡n de infantes de la compa¤¡a hab¡a sido doblada. La cantimplora diaria - el uso de que se hab¡a permitido en cuando quiera e incluso varios momentos - tambin se consideraba que era demasiado costoso por la direcci¢n. Sin embargo, todos stos son nada comparado al hecho que Google arque¢ antes del gobierno chino en 2006 y - seg£n su acuerdo - la compa¤¡a se ha filtrado todos los resultados de la b£squeda que ofenden sabor bueno o los intereses del rgimen chino. 
Uno de las regulaciones interiores de la compa¤¡a dice que no se anunciar n los nuevos servicios de antemano, s¢lo cuando ellos est n listos ser usado. Todav¡a, los pr¢ximos meses y a¤os tendr n la influencia grande definitivamente en el mundo: algunas personas predicen que el libro y revista examinando y archivando proyecto de Google alcanzar n cosas as¡ pronto proporciones que tendr  que enfrentar la Corte Suprema. Otros tienen miedo del sistema de Salud que tiene la capacidad de construir un perfil de salud completo sobre nosotros mientras incluyendo nuestros resultados mdicos anteriores, mdicos y problemas. 
Finalmente, el hecho que Google est  construyendo a un banco de datos gentico puede mantener un material bajo perfecto los escritores del sci-fi de la pr¢xima generaci¢n. La novela popular de Cory Doctorow, Scroogled aplica el estilo de Orwell en la descripci¢n de un futuro d¢nde una persona puede pintarse espantosamente bien s¢lo usando los datos de Google. 
