Los lazos entre la pol¡tica y ândrangheta arrestaron al alcalde de Gioia Tauro 
" El alcalde de Gioia Tauro estaba dispuesto hacia conformar los intereses municipales con aqullos de la banda " de Piromalli. 
Las imputaciones que los magistrados de la Calabrese Anti-mafia Oficina directo contra el alcalde y el alcalde del diputado de Gioia Tauro Giorgio Dal Torrione y Rosario Schiavone, y el alcalde de Rosarno Carlo Martelli que ha sido arrestado esta ma¤ana para el concurso externo con la asociaci¢n de la mafia es muy serio. 
Tambin arrestado es Gioacchino Piromalli, el mayor mediador entre el clan y las oficinas de administraci¢n p£blicas, y su sobrino - abogado, el hom¢nimo del jefe, ya condenado para el mafia-estilo la asociaci¢n delictiva, condenada para reembolsar 10 millones de euro. 
" En el desprecio de reglas todo judiciales y morales, y sentido com£n ", escr¡bales a los fiscales p£blicos, las dos administraciones locales hab¡an expresado el testamento para pagar las cuotas de consultor¡a al abogado Piromalli. 
" De esta manera, se permiti¢ la banda â los jueces le escriben a â para penetrar oficialmente dentro de la municipalidad que alivia el ya las inmensas posibilidades de controlar y dirigir la administraci¢n " p£blica. 
El presidente del Calabrese concilio local que Agazio Loiero no esconde que " las colusiones entre las instituciones locales y el crimen organizado son numerosas " dentro de su regi¢n: hay  reas d¢nde la presencia de la mafia es m s fuerte y m s intenso que en otros, d¢nde la colusi¢n es casi inevitable. 
Hay muchos pol¡ticos locales que se resisten la presi¢n puestos adelante por sin embargo, el ' el ndrangheta, hroes que permanecen limpios ". 
Los arrestos de esta ma¤ana siguen en julio aqullos con que la polic¡a anunci¢ para haber decapitado la banda de Piromalli. 
Al final del pasado de abril, el concilio municipal de Gioia Tauro se disolvi¢ pero ya en 1991, y siempre por el condicionar presunto entre el crimen organizado y la administraci¢n local, los pol¡ticos locales hab¡an sido relevado de los deberes de administraci¢n de la municipalidad. 
Giorgio Dal Torrione, el alcalde de UDC en el momento de la disoluci¢n, se hab¡a elegido de cabeza de una uni¢n del centro-derecho, despus del mayo 2006 papeleta de voto. 
l extendi¢ un esc ndalo de l cuando la Prefectura pidi¢ la disoluci¢n del concilio municipal. 
l trajo la causa el entonces el viceministro del Marco Minniti Interior que lo acusa de haber trazado todo para los motivos pol¡ticos, sin embargo los jueces, en la garant¡a del arresto firm¢ esta ma¤ana, ha explicado que la banda de Piromalli incluso hab¡a llegado a pedir la variaci¢n del proyecto de A3. 
De las interceptaciones pedidas en Dal Torrione, escribe la prosecuci¢n p£blica, ha salido " un buena gana para casarse las necesidades de un empresario, representante de un grupo m s grande notoriamente cerca del Piromalli, encuadrando las opciones de la administraci¢n p£blica con los intereses de la banda ". 
