J+¡r+Ýka: El c¡rculo vicioso de pobreza, la segregaci¢n debe eliminarse 
La C£spide de Igualdad europea se ha abierto hoy en Par¡s que es organizado por Francia este a¤o que representa el Presidencia-en-oficina de la Uni¢n europea. 
En su mensaje que ella se dirigi¢ al plenum, L+­via J+¡r+Ýka de Fidesz, Representante de la Fiesta de las Personas europeas llamado la atenci¢n por la segregaci¢n educativa desde que es una de la infracci¢n m s seria los ni¤os de Roma conmovedores. Es m s, sta es la barrera m s grande a su prosperidad. 
La conferencia nivelada alta se ha abierto por Xavier Bertrand, francs Atiende para la Labor y Asuntos Sociales y Vladimir Spidla, el Comisionado europeo responsable para el Empleo, Asuntos Sociales y Oportunidades Iguales. 
Representantes de los gobiernos, los compa¤eros sociales europeos y el europeo m s significante se invitaron las organizaciones de ayuda legales y NGOs del campo de oportunidades iguales a tener un asiento en la conferencia. 
J+¡r+Ýka - seg£n la oficina de la prensa del grupo de Fidesz en el EP - puntiagudo fuera eso, adem s de la discriminaci¢n experimentada al solicitar un trabajo, se segregan las personas de Roma principalmente del mercado del labour debido a su calificaci¢n educativa baja. 
La " mayor¡a de las personas de Roma j¢venes no tiene una calificaci¢n de la preparatoria, y debido a la calidad baja de la educaci¢n b sica s¢lo una parte insignificante de ellos puede obtener universidad o grado " de la universidad. 
J+¡r+Ýka tambin dio nfasis a que esa educaci¢n, como un derecho humano fundamental, juega un papel importante en la entrada en vigor de otros derechos humanos. 
Invirtiendo en la educaci¢n temprana de ni¤os de Roma pueden contribuir a fortalecer la econom¡a de los estados de miembro de Uni¢n europeos. 
Seg£n el representante, es necesario informar el rango m s ancho de las personas - Romas y las personas del non-Roma tambin - sobre estas relaciones mutuas. 
El m s temprano un estudiante de Roma joven empieza asistiendo a la escuela, el m s grande sus oportunidades ser n volverse un miembro productivo del mercado del labour; a travs del ingreso y los impuestos pagados por ellos que ellos contribuir¡an al presupuesto nacional. 
" En las tierras del derecho de la ciudadan¡a aplicadas en la Uni¢n europea, el derecho de educaci¢n de calidad debe asegurarse para las personas de Roma y la calidad baja, la educaci¢n segregada debe eliminarse ", L+­via J+¡r+Ýka agregado. 
Ella tambin dijo que para acelerar los procesos de desegregaci¢n escolar al instante, es necesario garantizar un objetivo - y acci¢n-orient¢ la cooperaci¢n dentro de la Uni¢n europea. Para lograr esta meta, es fundamental dar fuerza al directives de la anti-discriminaci¢n existiendo y plane¢ propiamente. 
" El c¡rculo vicioso de pobreza, la segregaci¢n, que el desempleo debe eliminarse, deben proporcionarse las oportunidades de vida democr tica a los ni¤os de Roma para que ellos pudieran contribuir al futuro de Europa como los ciudadanos con los derechos " llenos, J+¡r+Ýka exigido. 
Dentro del armaz¢n del " A¤o europeo de Oportunidades " Iguales, la C£spide de Igualdad europea - primero organiz¢ en Berl¡n el a¤o pasado y desde entonces sujet¢ una base anual - apunta para proporcionar un £nico foro para promover los objetivos de oportunidades iguales y anti-discriminaci¢n tambin al europeo y miembro el nivel estatal. 
