El geriatra afirma que las muertes fueron causadas por la "falta de medios" 
Los dueños del centro de Olot no desechan que su asistente mató a más de 11 personas mayores 
La gente responsable con el La geriátrico Caritat de Olot (Gerona) del hospital ofreció una rueda de prensa ayer para subrayar el daño que ha causado a la institución la conducta criminal de Joan Vila Dilmé, la enfermera que mientras que allí estaba matada por lo menos once personas mayores que él tenía bajo vigilancia. 
El director de la residencia, Joan Sala, aparecido acompañado por el abogado del centro, abogado Joan Canadá, y anunciado que "la intención del La Caritat fijaría la culpa en el individuo responsable de las muertes pero "legalidad y responsabilidad nos fuerza a asumir la situación procesal de la gente responsable civil". 
Y eso además de la pérdida social de prestigio que la organización puede encontrar para detectar a tiempo las actividades criminales del vigilante, la gran amenaza para el Caritat tiene ahora toma la forma de una indemnización sustancial que sea calculada ya por los representantes legales de los parientes de las víctimas. 
Joan Vila Dilmé ha confesado que el primer crimen vuelve al agosto de 2009 y que él no paró desde entonces el matar. 
El teléfono hizo el juez mencionado ya en el documento que pidió la exhumación de ocho cuerpos - viejos pacientes del hospital geriátrico que ella sospechó que en muchos casos ningún doctor exploró personalmente los cadáveres pero, teniendo en cuenta la edad y las patologías de los pacientes, el procedimiento. 
El La Caritat, a través de su director, negó completamente este extremo ayer y mencionó que "la falta de medidas no habría podido ser en todo momento la causa de qué había sucedido". 
El abogado del La Caritat añadió que "en la causa no hay indicación que ha habido una acción imprudente de parte de cualquier otra persona que no sea la culpable". 
El que está bautizado como "ángel de la muerte" confesó 11 asesinatos anteayer y los detalló que él confió el primer crimen el 29 de agosto de 2009 y un mes y medio más adelante, matado otra abuela. 
En este caso una sobredosis de insulina le trajo la muerte\; a diferencia del primer crimen él confió con una mezcla de tabletas sedativas. 
El director del Caritat dice que está complicado para controlar que los personales del centro tienen acceso a las medicinas. 
La sobredosis de insulina y del cóctel sedativo habría sido el mecanismo usado en seis de los nueve crímenes que la enfermera, en su impaciencia de aliviar el sufrimiento de los pacientes, utilizó o matanza ellos. 
Pero las pruebas que se están realizando en el laboratorio tendrán que aclarar si no está estando situado Vila e intentado asegurar para sus primeras víctimas una muerte menos cruel o si, por el contrario, quemado les internamente dándoles la lejía como él confesó ya eso había hecho con las tres mujeres a que él mató entre las 12mas y el 17 de octubre. 
En el La Caritat no dan credibilidad al aspecto del vigilante, ni al número de asesinatos confesados, que no refutan ser superiores, y justifican su actitud en las diversas versiones que Vila ha dado en sus visitas a la corte y al absurdo de cambiar su método de matanza después que confiaba con éxito, ocho asesinatos. 
Esta es la razón por la cual dicen que se ponen a disposición de justicia para aclarar el alcance de este acontecimiento. 
