El grupo catalán facilitó millares de pasaportes al al - qaida 
Además de los siete presos en Barcelona, en Tailandia había tres 
Los siete pakistaníes y el nigeriano parados por los agentes de la inteligencia de la policía de general Barcelona formaron a un grupo del jihadist que, dirigido de Tailandia, facilitó pasaportes a diversos grupos de al - qaida, entre ellos "los tigres para la liberación del territorio" (LTTE) de Tamilm y "Laskar y Taiba" (deje), son autor este último de los ataques de Bombay que causaron la muerte de 106 personas en 2008. 
El ministerio de asuntos internos ha prestado la atención a estas investigaciones, hasta el punto de asegurar eso con la operación de "Kampai"\; ha sido "debilita" el aparato de la falsificación del al - qaida en un nivel internacional y, "por lo tanto, su capacidad operativa". 
Los investigadores calculan que la célula, durante los dos años que ha sido activa en Cataluña, ha podido enviar millares de pasaportes a Tailandia, en donde los falsificaron y pronto fueron distribuidos a los grupos que integran el al criminal de la galaxia - qaida de modo que sus "combatientes" puedan cruzar las fronteras europeas y las que está de otros países occidentales con impunidad total. 
La célula desmontada no es la única que la red del jihadist tenía en Europa, por este motivo en las investigaciones allí ha participado, además de los servicios de Tailandia, otras unidades policiales europeas, razón por la que no desecha eso en el territorio de la UE ocurre los acontecimientos similares al que está desarrollado la noche de martes en Barcelona. 
En coordinación con esta operación (pararon el Junaid paquistaní Humayun, Atiqur Rehman, Jabran Asghar, Malik Iftikhar Ahmad, Begum de Mohammad Saddique Khan, Tanveer Arshad y al Nigerian Babatunde Agunbiade todo), en Tailandia otro se había convertido con la captura del extremo de Mohamed Athar de los pakistaníes y del extremo de Zeeshan Ehsan y el Sirikanlaya tailandés Kijbumrung. 
Dirigieron al grupo asentado en España y otros países europeos de Bangcock 
La red catalana - parte de ella fue pegado en 2009 - principalmente pasaportes con túnica a los turistas que satisficieron los requisitos marcados por la llamada el "frente islámico mundial". 
Es decir, los documentos tuvieron que estar en nombre de hombres entre 25 y 45 años, con la validez de varios años y sin visas impresas. 
En los medios de la investigación se acentúa que, por el momento, no se ha encontrado ningunos datos relacionados a las personas arrestadas en Cataluña con respecto al ataque de Bombay, aunque el autor de este ataque, "Laskar e Taiba", haya sido uno de los grupos de recepción de los pasaportes robados en España y pronto falsificados en Tailandia. 
Sin embargo, debe ser mencionado que los días antes de que este ataque confiado, de Cataluña allí fuera enviado a través de una agencia de transferencias sobre algunos millares de dólares que "fueron invertidos" en la compra de las tarjetas del teléfono móvil que pronto fueron utilizadas por los miembros del "comando" que terminó la vida de 106 personas. 
Los policías han capturado mucha documentación. 
