Los querellantes no cargarán a senador Ensign 
Los querellantes del departamento de justicia han despejado a senador John Ensign de las alegaciones criminales que se presentaban de su asunto con un asistente anterior de la campaña y de sus esfuerzos de asegurar el trabajo de cabildeo para el marido de la mujer, los abogados del senador anunciados miércoles. 
La decisión termina la amenaza legal más seria para Sr. Ensign, el republicano de Nevada que era considerado un candidato presidencial republicano posible en 2012 hasta que el escándalo sobre su asunto hizo títulos del nacional el año pasado y dañó su carrera. 
La oficina de Sr. Ensign's dijo que él estaba "ciertamente contento" por la decisión, que siguió una investigación de un año. 
El senador podría todavía hacer frente a la acción disciplinaria del comité de ética del senado. 
Los abogados de Sr. Ensign's dijeron que el departamento de justicia "nos había informado que senador Ensign es no más una blanco de su investigación y que no tiene ningún plan para traer ningunas cargas contra él en esta materia". 
El departamento de justicia disminuyó comentar respecto al caso. 
El aviso vino como algo de una sorpresa a muchos abogados de los éticas fuera del departamento de justicia, que dijo allí aparecido ser pruebas significativas para indicar que Sr. Ensign pudo haber conspirado violar una prohibición criminal en el cabildeo federal. 
Las entrevistas, el email y otros documentos primero divulgaron en octubre de 2009 en New York Times indicaron que Sr. Ensign había ayudado a Douglas Hampton, que era uno de sus asistentes, trabajo de cabildeo lucrativo seguro para ganar el silencio de Sr. Hampton y su esposa, Cynthia, sobre el asunto del senador con ella. 
Señora Hampton sirvió una vez como tesorero de una campaña de la bandera. 
Sr. Ensign entró en contacto con varios soportes políticos para encontrar el trabajo para Sr. Hampton y entonces abogado en nombre su después de que hubieran contratado a Sr. Hampton para cabildear para ellos, según los documentos y las entrevistas. 
Porque Sr. Hampton había sido recientemente un asistente a Sr. Ensign, la ley lo barró de cabildear su patrón anterior o el senado en conjunto por un año. 
Los expertos de los éticas dijeron el arreglo inusual entre Sr. Ensign y Sr. Hampton, que eran amigos cercanos antes del asunto, aparecían en desacuerdo con la prohibición de cabildeo de la supuesta puerta giratoria. 
De las pruebas que se han hecho públicas, "aparecía ser a primera vista un caso de una conspiración a violar, y violación sustancial del estatuto de la puerta giratoria", dijo la marca de Stanley, abogado de Washington que se especializa en los clientes de defensa investigados por el gobierno. 
Mientras que los funcionarios del departamento de justicia disminuyeron explicar el razonamiento detrás de la decisión en la caja de la bandera, Sr. Brand y otros abogados de los éticas dijo que el departamento aparecía cuidadoso de adquirir procesamientos políticos después de varios reveses destacados para su sección pública de la integridad, incluyendo la decisión el año pasado para caer el procesamiento contra senador anterior Ted Stevens en medio de cargas de la mala conducta fiscal. 
Los querellantes federales "son claramente arma tímido", dijo a Melanie Sloan, el director ejecutivo de los ciudadanos para la responsabilidad y los éticas en Washington, grupo de presión que trajo varias denuncias contra Sr. Ensign en el caso. 
"Esto dice básicamente los altos oficiales del gobierno pueden ahora asumir que las leyes no se aplican a ellos", ella añadió. 
Paul Coggins, abogado de ventaja de Sr. Ensign's, dijo en una entrevista que él recibió una llamada de teléfono de un querellante del departamento de justicia el lunes y una continuación el next day, diciéndole que el departamento no buscaba carga contra su cliente. 
El equipo de defensa de Sr. Ensign's había estado cooperando con los querellantes en intentar persuadirlos que el senador, como su oficina reiterada en una declaración miércoles, "actuaba de acuerdo con la ley". 
Sr. Coggins disminuyó explicar las discusiones legales que él hizo a los querellantes. 
"No soy el entrar cómodo los detalles de mis discusiones con el departamento de justicia excepto decir que pensamos que tomaron la decisión correcta", él dijo. 
El mes pasado, la comisión electoral federal decidía caer una investigación en una denuncia separada por el grupo de los éticas que alegaba que un pago $96.000 de padres de Sr. Ensign's al Hamptons violó ley federal de la elección. 
La comisión electoral dijo no tenía bastantes pruebas a probar que el dinero era cualquier cosa excepto un regalo. 
Una compañía para quien Sr. Ensign ayudó a Sr. Hampton a encontrar el trabajo de cabildeo era energía del nanovoltio, compañía importante de Nevada que había apoyado de largo al senador. 
Un email enviado en diciembre de 2008 mostró que después de que la compañía trajera a Sr. Hampton encendido como cabildero, jefe de personal de Sr. Ensign's, Juan López, comunicado con Sr. Hampton y le dijo que él "golpeaba" el departamento interior sobre un problema en conflicto. 
Sr. Ensign también asistió a un almuerzo con Sr. Hampton y otro cliente de Nevada, aire Allegiant, y llamó a la secretaria de transporte para poner una reunión en nombre la línea aérea después de que hubiera contratado a Sr. Hampton para hacer el trabajo de cabildeo. 
Cuando emergieron las noticias del asunto primero el año pasado, Sr. Ensign se disculpó a sus componentes y dimitió su posición como el líder republicano de la cuarto-graduación en el senado. 
Después de guardar un perfil bajo por muchos meses, Sr. Ensign dijo a reporteros hace dos semanas eso que él planeó correr para un tercer término en el senado. 
En la anunciación de que Sr. Ensign era no más la blanco de una investigación penal, su portavoz, tonelero de Jennifer, dijo el senador esperaba que el comité de ética siguiera rápidamente la ventaja del departamento de justicia y que terminara su investigación. 
"Senador Ensign mira adelante a continuar su trabajo duro en nombre de la población de Nevada", ella dijo. 
