Doña Sofía: "Son instrumentos para el progreso y la esperanza"
La Reina destaca el lugar "preponderante" de España en relación a este tipo de finanzas
España "ha alcanzado un lugar preponderante a nivel mundial en el papel de la Microfinanzas".
La Reina Doña Sofía recordó ayer que el país se ha convertido en estas dos últimas décadas en el segundo donante del plantea en relación a este intrumento de cooperación, cuya "esencia" señaló que radica en ser un "instrumento para el progreso social, la justicia y la esperanza de un futuro mejor para toda la humanidad, basado en la confianza en el ser humano".
La Reina inauguró ayer la V Cumbre Mundial del Microcrédito en Valladolid con el convencimiento de que "no hay duda" de que esté tipo de operaciones son "absolutamente indispensables" para alcanzar los Objetivos del Milenio establecidos por Naciones Unidas con horizonte 2015, y, "muy especialmente, en aquél que tiene como meta la reducción a la mitad del volumen de personas que viven con ingresos inferiores a un dolar diario, con en el que se fija el "umbral de pobreza".
España "sigue trabajando" para ampliar la red de beneficiarios "a todos los rincones del planeta, y asume esta tarea con "responsabilidad", señaló Doña Sofía, que esperó que las iniciativas y aportaciones que se originen en la Cumbre, que se prolongará hasta el jueves, "garanticen la creación de nuevas capacidades y mejores oportunidades para los más pobres, y sobre todo para las mujeres", principales beneficiarias de estos préstamos.
Son "muchos los logros alcanzados" y "muchos los desafíos a los que nos enfrentamos".
La Cumbre del Microcrédito se plantea no sólo como un foro de debate, sino también como la plataforma desde la que impulsar "dos metas básicas".
Así, Su Majestad explicó que se aspira a que a finales de 2015 sean 175 los millones de familias pobres que hayan accedido a estos servicios financieros y que cien millones de esos hogares salgan del umbral de pobreza en el que están sumidos.
El impulso en la concepción de los microcréditos en España y en el resto del mundo "ha seguido la senda iniciada hace años de forma pionera" por Muhammad Yunus, resalto Doña Sofía como un "acto de justicia y reconocimiento debido".
Y es que describió al padre de esta herramienta como un "idealista admirable en la causa universal de la lucha contra la pobreza", cuyo trabajo conoce desde hace 15 años, cuando la Reina viajó a Bangladesh para conocer sobre el terreno su política de préstamos.
A esta experiencia le siguieron un año más tarde la primera Cumbre Mundial en Washington y otros encuentros como los celebrados en Costa de Marfil en 1999, Canadá 2006, y "en todos he podido constatar la continua evolución", explicó Su Majestad, cuyo vínculo con este proyecto le valió ayer el calificativo de la "cabeza de familia" congregada en Valladolid por parte del "baquero de los pobres".
Finalmente, la Reina Doña Sofía concluyó su intervención animando a los presentes a participar en el debate y en la búsqueda de soluciones para avanzar en la lucha contra la pobreza.
"Imperativo ético"
La ministra de Asuntos Exteriores, Trinidad Jiménez, advirtió que la solidaridad "es un imperativo ético" para todo estado democrático.
En este sentido, expuso que sería un error vincular la cooperación con paises en vías de desarrollo a épocas de bonanza económica, ya que es una "obligación permanente".
Jiménez consideró que los microcréditos suponen "una política seria y rigurosa dedicada a erradicar la pobreza", y ahora "más que nunca" los gobiernos de países desarrollados deben trabajar bajo criterios de solidaridad y no dejar que ésta sea víctima de los recortes.
Para España, el microcrédito consiste en "una de las principales líneas de cooperación al desarrollo".
Por su parte, la Secretaria de Estado de Cooperación Internacional, Soraya Rodríguez, aplaudió "el éxito" de dar "confianza" a las personas "excluidas a quienes todos cierran las puertas"; y el alcalde de Valladolid, Francisco Javier León de la Riva, dio la bienvenida a los presentes a una ciudad que "abre sus puertas contagiada del espíritu solidario".
