Los crímenes y delitos contra musulmanes han aumentado un 50%
Los crímenes y delitos contra los musulmanes han aumentado cerca de un 50% entre 2009 y 2010, mientras que, en el mismo período, los restantes tipos de violencia racial y religiosa han disminuido o aumentado solo ligeramente, según indican las estadísticas publicadas por el FBI el lunes.
Según dichas cifras, el número total de actos de violencia cometidos contra musulmanes ha pasado de 107 en 2009 a 160 en 2010, es decir, ha aumentado en un 49%, frente a una subida del 13% en el caso de los actos de violencia contra los católicos, una reducción del 4% en los delitos contra judíos y un aumento global del 14% en el número de crímenes y delitos antirreligiosos.
El número total de "crímenes de odio" ha crecido ligeramente hasta los 6.628 casos, de los cuales un 47,3% se debe a diferencias raciales y un 20% a diferencias religiosas, según indica el FBI.
"Tras un declive en 2009, resulta preocupante que hayan vuelto a aumentar este tipo de crímenes y delitos", destacó la organización de defensa de los derechos humanos Human Rights First, "el aumento de los actos de violencia contra musulmanes resulta especialmente significativo", añadió la organización en un comunicado.
"Human Rights First lleva mucho tiempo señalando que la violencia contra los musulmanes, así como todos los tipos de crímenes de odio, deberían considerarse una grave violación de los derechos humanos", añade un responsable de la organización, Paul Legendre.
"El Gobierno estadounidense puede y debe esforzarse por poner fin a dichos abusos", añade, considerando que dichos esfuerzos podrían incluir una mejora de los informes de la policía sobre los "crímenes de odio".
El "crimen de odio" en el Derecho federal estadounidense se heredó de la época de la lucha por los derechos civiles.
Dicha legislación se adoptó tras la muerte de Martin Luther King para castigar los actos de violencia vinculados a la raza, el color de la piel, la religión, el origen y, ahora, la inclinación sexual.
