Los "indignados" desafían a autoridades en Nueva York
Centenares de manifestantes se agolpaban ante la plaza Zuccotti para acampar.
Una gran parte atendió la orden de desalojo y se trasladó a un paruqe cercano.
Los integrantes del movimiento Ocupa Wall Street desafiaron este martes a las autoridades de Nueva York al tratar de entrar de nuevo, bajo el amparo de una orden judicial, a la plaza de Manhattan de donde fueron desalojados de madrugada y al tratar de ocupar otro parque de la Gran Manzana.
Centenares de manifestantes se agolpaban ante la plaza Zuccotti, donde querían acceder gracias a una orden judicial que permite a los "indignados" volver a acampar en el lugar, mientras que otra parte del movimiento respondió al desalojo ocupando un parque más al norte de la ciudad, donde ha habido nuevas detenciones.
"Nuestra idea es que, si el tribunal no nos permite volver a acampar en la plaza, nos vamos a instalar en algún otro lugar y continuaremos la batalla legal por volver a Zuccotti, así como a través de sentadas y manifestaciones pacíficas", dijo uno de los portavoces del movimiento "Ocupa Wall Street", Mark Bray.
Bray detalló que la respuesta de los "indignados" al desalojo de su campamento dictado personalmente por el alcalde de Nueva York, Michael Bloomberg, llegó hasta los tribunales, donde la jueza Lucy Billings emitió una orden que prohibía la evacuación forzosa del lugar y permitía a los manifestantes a mantenerse acampados.
Además, los "indignados" procedieron a la ocupación de un nuevo parque situado en la confluencia de las céntricas Canal Street y la Sexta Avenida, muy cerca de la entrada al túnel Holland, que une Nueva York y Nueva Jersey, y propiedad de la parroquia de Trinity Church.
Al menos durante una hora consiguieron ocupar el lugar, pero después la Policía acudió y procedió a detener a algunos de los manifestantes, aunque Bray no pudo confirmar la cifra concreta, mientras aseguró a Efe que vio a varios periodistas que fueron también esposados.
La organización asegura que son varios centenares de personas las que se habían instalado en ese punto, donde ya se ha desplazado una delegación de líderes religiosos en muestra de apoyo a los integrantes del movimiento y que ha tratado de mediar con la Policía.
Entre tanto, la plaza Zuccotti -que es un recinto de propiedad privada- sigue cerrada a la espera de la celebración de una vista judicial prevista para este mismo martes en la que se debe analizar la legalidad de la evacuación de esta madrugada.
Algunos de los manifestantes desplazados hasta ahí portaban y repartían a estas horas copias de esa orden judicial e incluso las entregaban a los agentes que custodiaban la plaza, lo que provocó "algunos pequeños enfrentamientos", indicó Bray, quien denunció que algunos oficiales propinaron golpes a los manifestantes.
La orden judicial prohibe a las autoridades desalojar a los miembros de Ocupa Wall Street o aplicar "leyes que se publicaron después de que empezara la ocupación o prohibir a los manifestantes acceder de nuevo al parque con tiendas u otras propiedades que utilizaban anteriormente".
El alcalde Bloomberg indicó ante la prensa que, debido a esa orden judicial, la ciudad había suspendido la reapertura del espacio al público y a los manifestantes, a los que alertó, sin embargo, que las leyes locales no les permiten volverse a instalar con tiendas de campaña y sacos de dormir.
El regidor defendió personalmente el desalojo llevado a cabo de madrugada de la plaza Zuccotti, una operación en la que se procedió a alrededor de 200 detenciones y que se decidió porque los manifestantes estaban "violando la ley".
Bloomberg explicó que dio la orden de evacuar la plaza porque ésta se estaba convirtiendo "en un lugar en el que las personas no venÍan a protestar, sino a violar las leyes y, en algunos casos, a hacer daño a otras personas", ya que "algunos negocios habÍan recibido amenazas" y los vecinos temÍan "por su calidad de vida".
"El desalojo de esta madrugada fue asqueroso y demuestra que en el fondo Bloomberg está más interesado en preservar los intereses financieros que los de los trabajadores estadounidenses", añadió el portavoz del movimiento, quien acusó al alcalde de "faltar el respeto a la libertad de expresión".
Los responsables de "Ocupa Wall Street" indicaron también que piensan organizar "grandes acciones" para el jueves en colaboración con organizaciones comunitarias y sindicatos, para conmemorar los dos meses que duran las protestas, que comenzaron el 17 de septiembre.
