MSS anuncia protocolo para hallar gen de obesidad
Dirige el Seguro Social una investigación para descubrir el gen de la obesidad en niños y jóvenes; está apoyado en especialistas del IPN
El Instituto Mexicano del Seguro Social (IMSS) anunció que dirige una investigación para descubrir el gen de la obesidad en niños y jóvenes, denominado protocolo 'Genética de la obesidad de la infancia y la adolescencia', que permitirá contar con marcadores asociados al sobrepeso.
En un comunicado, el jefe de la Unidad de Investigación Médica en Bioquímica del Hospital de Especialidades del Centro Médico Nacional Siglo XXI, Miguel Cruz López, explicó que se integró un equipo multidisciplinario de médicos, enfermeras, nutriólogos y trabajadoras sociales.
Dicho equipo está apoyado por especialistas y alumnos de postgrado del Instituto Nacional de Salud Pública (INSP) y del Centro de Investigación y de Estudios Avanzados (Cinvestav) del Instituto Politécnico Nacional (IPN).
En la investigación se invita a participar a la población sea o no derechohabiente, acudir a las unidades deportivas participantes del IMSS en el Valle de México, donde se llevan a cabo las pruebas a los menores, todos los sábados a partir de las 8:00 horas.
Destacó que el protocolo comenzó en la Unidad Deportiva Cuauhtémoc (Estado de México Poniente) y que desde el 8 de octubre, la actividad se lleva a cabo en la Unidad Deportiva Nezahualcóyolt (Estado de México Oriente).
Una vez que se cumpla el objetivo de reunir a 500 o 600 menores, el estudio continuará en la Unidad Deportiva Independencia (sur del Distrito Federal) y finalmente en la Unidad Deportiva Morelos (al norte del Distrito Federal).
Explicó que el propósito de esta investigación es conocer los componentes y la importancia de la genética con respecto al desarrollo de la obesidad e identificar en niños y jóvenes mexicanos factores de riesgo para prevenir la aparición de enfermedades crónico degenerativas.
Al celebrarse este 14 de noviembre el Día Mundial de la Diabetes, precisó que el objetivo es reunir a tres mil niños y jóvenes entre seis y 14 años de edad, con el consentimiento y supervisión de sus padres, para la aplicación de cuestionarios específicos sobre alimentación.
También se les preguntará sobre la actividad física y antecedentes heredofamiliares de enfermedades, con el propósito de evitar factores de riesgo que desencadenen padecimientos como diabetes o insuficiencia renal.
Detalló que los sábados se les aplica a todos los participantes mediciones antropométricas (peso, talla, circunferencia de cintura), toma de presión arterial, determinación de los niveles de glucosa, triglicéridos, colesterol e insulina y genéticos (se busca identificar genes que se asocien a la obesidad infantil).
Cruz López señaló que esta investigación obedece a la preocupación de los profesionales de la salud por el alarmante aumento de peso en los menores.
'Las encuestas de salud de 1999 y 2006 señalaron que en tan solo seis años hubo un incremento, en el caso de los niños, de 77 por ciento en obesidad, y de las niñas de 47 por ciento; en términos de sobrepeso también se observó un ascenso dramático', destacó el especialista del IMSS.
Indicó que la justificación para la búsqueda de los marcadores se sustenta en que la población del país difiere de otras por su historia genética.
Informó que en promedio, el mexicano tiene 65 por ciento de herencia indio americana, 30 por ciento europea y cinco por ciento africana y esta condición se refleja en los genes que se asocian a diabetes y exceso de peso.
Explicó que de manera general, la genética de la obesidad se traduce en la incapacidad de quemar el exceso de energía que consumimos (calorías) y que se almacena en forma de grasa.
El investigador explicó que el beneficio directo para los participantes es la evaluación integral de los niños, lo que permite detectar si presentan algún grado de sobrepeso u obesidad.
Incluso, dijo, la presencia de pliegues de color obscuro (acantosis) en cuello y antebrazo, que indican la probabilidad de que padezca alteraciones metabólicas y hasta prediabetes.
La información se maneja de forma confidencial, los médicos la entregan por escrito a los padres, a quienes se les explica cada una de las mediciones y los cambios en el estilo de vida que deben realizar para prevenir enfermedades.
Cruz López explicó que existen tres componentes principales que causan sobrepeso, obesidad y otros padecimientos crónicos: el sedentarismo, que es la falta de actividad física diaria, permanecer la mayor parte del día sentado frente al televisor y utilizar medios de transporte en lugar de caminar distancias cortas.
También se debe a la alta ingesta calórica, es decir, el mayor consumo de bebidas azucaradas, de carbohidratos (tamales, pan, pizza, hamburguesa, etcétera) con elevado contenido en grasas y proteínas y la genética que se analiza en este protocolo.
