Asfalto de la UNAM evitaría baches
Rafael Herrera, investigador de la Facultad de Química de la UNAM, desarrolla asfaltos modificados con polímeros para producir una mezcla con mejor desempeño, independientemente de las condiciones ambientales y de temperatura
Si las señales que envía el pavimento fueran atendidas, no sería necesario reparar cerca de 200 mil baches cada temporada de lluvias en la Zona Metropolitana del Valle de México, advirtió Rafael Herrera Nájera, investigador de la Facultad de Química (FQ) de la UNAM, quien aseguró que si el proceso de construcción y mantenimiento de un pavimento asfáltico es el adecuado, los baches podrían reducirse en cantidad o, incluso, eliminarse por completo.
En su conferencia Una opinión tecnológica de los baches, dictada en el marco del Año Internacional de la Química, dio a conocer que el laboratorio a su cargo desarrolla asfaltos modificados con polímeros para producir una mezcla con características semejantes a las del asfalto, pero con una mayor resistencia mecánica, tanto a altas como a bajas temperaturas.
Herrera Nájera estimó que este tipo de asfaltos modificados podrían utilizarse en lugares donde el clima es extremadamente caliente, como algunas ciudades del norte del país, para mejorar su desempeño y, por lo tanto, la formación de baches.
Explicó que el asfalto, la parte más pesada del petróleo, es un conjunto de moléculas de hidrocarburos, unas de alto peso molecular, llamadas asfaltenos, y otras de bajo peso molecular, llamadas maltenos, que juntas le dan al pavimento su característico comportamiento viscoelástico.
El comportamiento viscoelástico del asfalto consiste en que a altas temperaturas, cerca de los 180 grados, se comporta como un líquido, a 120 grados centígrados su viscosidad es muy alta y a 50 grados centígrados presenta un estado casi sólido, mientras que a temperaturas muy bajas, el asfalto se vuelve quebradizo, añadió.
Lo anterior significa que en las calles la resistencia del asfalto no es uniforme, sino que se va modificando durante el día de acuerdo con las condiciones ambientales y de temperatura, advirtió el especialista en ingeniería química.
El investigador de la FQ observó que las calles de la Ciudad de México en su mayoría están cubiertas por pavimento flexible, el cual se compone de seis capas de materiales, de las cuales las últimas tres involucran al asfalto.
Entre las capas más superficiales se encuentra la carpeta asfáltica, conformada por pequeñas piedras bañadas en asfalto y luego compactadas.
Cada una de las piedritas que constituye la carpeta, apuntó, está bañada con asfalto.
Al transitar los vehículos y generarse esfuerzos, éste permite que las fuerzas se difundan muy bien en el pavimento.
Si se tratara de asfalto modificado se difundirían aún mejor, opinó el ingeniero químico.
Sobre la carpeta asfáltica, abundó, se coloca una última capa llamada carpeta de rodadura, la cual está hecha de un material de piedra fino, es decir, una arena que también se baña en asfalto.
Como se trata de la capa que va a estar en contacto con las llantas de los vehículos, debe tener más fuerza mecánica que la carpeta asfáltica y proporcionar fricción en el camino.
Al ser la parte del pavimento que va a recibir y difundir los esfuerzos, la carpeta de rodadura requiere, asimismo, tener el espesor adecuado y se debe cuidar el material del que está hecha.
El clima, especialmente la humedad y las variaciones de temperatura, también son un factor muy importante a considerar, en especial el agua, dijo, porque afecta considerablemente el desempeño de la carpeta asfáltica.
Cuando el terreno se humedece, el agua se difunde en el interior de la carpeta y es difícil que salga, esto ocasiona un reblandecimiento de todas las capas del pavimento y, por lo tanto, la formación de baches.
En el proceso de formación de un bache, dijo, la primera en desgastarse es la película de rodamiento y sólo después se afecta la carpeta asfáltica, pero el daño no ocurre instantáneamente, sino que es un proceso que debería atenderse a las primeras señales con adecuados programas de mantenimiento.
El también miembro del Sistema Nacional de Investigadores explicó que la carga vehicular es otro factor importante en la formación de baches y, por ello, el espesor de cada una de las capas del pavimento debe ir siempre en relación con la carga vehicular y garantizar que se cumpla, para evitar que se formen baches frecuentemente.
Rafael Herrera advirtió que aún hay mucho que investigar y trabajar sobre el asfalto, por ejemplo, las emulsiones asfálticas, que en otros países ya se encuentran incluso en el mercado y permiten reparar los baches con facilidad y sin necesidad de usar altas temperaturas.
