Analizan posibilidad de un conteo "voto por voto" en Michoacán
De acuerdo con los datos arrojados por el PREP la diferencia entre primero y segundo lugar de la elección de gobernador es de apenas 27 por ciento, aún sin contabilizarse los votos correspondientes a 879 de las 6 mil 74 actas totales.
La posibilidad del conteo "voto por voto" es una realidad en lo que se refiere al proceso electoral de este año en Michoacán, donde de acuerdo con los datos arrojados por el Programa de Resultados Electorales Preliminares (PREP) la diferencia entre primero y segundo lugar de la elección de gobernador es de apenas 27 por ciento, aún sin contabilizarse los votos correspondientes a 879 de las 6 mil 74 actas totales.
Al respecto, la presidenta del Consejo General del Instituto Electoral de Michoacán (IEM), María de los Ángeles Llanderal Zaragoza, recordó que hace unos días, apenas el pasado 9 de noviembre, el órgano electoral aprobó una serie de lineamientos con el fin de armonizar las normas locales con la reforma federal en materia electoral.
Como se recordará, Michoacán no homologó su Constitución Política ni su Código Electoral del Estado o su Ley de Justicia Electoral, toda vez que el Congreso del Estado aprobó las reformas poco antes de concluir el plazo legal para que pudieran entrar en vigor en el presente proceso electoral y el gobernador Leonel Godoy Rangel omitió su publicación en los plazos previstos en la Ley del Periódico Oficial del Estado, con el argumento de que tenía algunas objeciones.
El mismo 9 de noviembre, la Suprema Corte de Justicia de la Nación (SCJN) resolvió la controversia constitucional promovida por el Poder Legislativo local y calificó como "inválido e ilegal" el voto del mandatario estatal a las reformas constitucionales, toda vez que no tiene derecho de "sancionarlas o vetarlas".
Entrevistada en torno a la posibilidad del "voto por voto", María de los Ángeles Llanderal expuso que gracias a la aprobación de los lineamientos correspondientes por parte del Consejo General del IEM será posible la realización de recuentos parciales y totales de la votación por parte del órgano electoral local.
De esa forma, el recuento parcial de votos, de uno o más paquetes electorales, podrá darse en los supuestos de que: los resultados de las actas no coincidan; no exista el acta de escrutinio y cómputo en el expediente de la casilla o no obre en poder del presidente de la misma; o, cuando existan errores o alteraciones evidentes de las actas.
Además, el recuento total de la votación recibida en todas las casillas de la elección podrá realizarse cuando exista indicio de que la diferencia entre el candidato presunto ganador de la elección de que se trate y el que haya obtenido el segundo lugar en la votación, es igual o menor a un punto porcentual; siempre y cuando al inicio de la sesión exista la petición expresa del representante del partido y/o coalición que postuló al segundo de los candidatos señalados.
El recuento total de la votación también podrá realizarse si al terminar el cómputo ordinario se establece que la diferencia entre el candidato presuntamente ganador y el ubicado en segundo lugar es igual o menor a un punto porcentual, siempre y cuando exista la petición expresa del representante del partido político cuyo candidato quedó en segundo lugar, caso en el cual se excluirán los paquetes electorales que hayan sido objeto de recuento parcial.
Cabe mencionar que en dicha situación se encuentra la elección de Morelia, donde de acuerdo con el PREP la diferencia entre el primero y el segundo lugar es de apenas el 0.16 por ciento, aunque sin contabilizar los votos de 129 de las 923 actas totales.
