Debe aportaciones para obras
Las obras de carácter social contempladas en programas como Hábitat, Rescate de Espacios Públicos y 3x1 para migrantes se encuentran en riesgo de no ser concluidos o de tener serios retrasos debido a la falta de recursos económicos, señaló Miguel Ángel López Miranda.
El director de Desarrollo Social municipal indicó que si bien hasta ahora los programas de obra han avanzado, sí se encuentran en riesgo al no haber cumplido el Gobierno del Estado con las aportaciones que le corresponden las cuales suman un recurso superior a los 11 millones de pesos en los tres programas.
Señaló que en total la inversión en estos tres programas es de casi 50 millones de pesos, de los cuales al Estado corresponde el 25 por ciento y que hasta ahora solo la Federación y el Municipio han aportado recursos para las obras, por lo que el posible retraso en la conclusión de estas se hace vigente.
"Son casi 12 millones lo que les toca aportar y a pesar de que el año está por terminar no nos han dado ni un quinto, cuando desde julio debieron darnos una parte", expresó, "nosotros para no retrasarnos hemos iniciado las obras y van muy avanzadas, pero nos hace falta el dinero".
Mencionó que el año pasado, en la administración de Jesús Aguilar Padilla, el Estado no cumplió con las aportaciones que les correspondían, por lo que al inicio de la administración el Municipio tuvo que solicitar un crédito para cubrir los mas de 7 millones que no aportó en aquella ocasión la administración estatal.
"Ya nos pasó en el sexenio anterior porque el Estado no tuvo la capacidad económica para participar y los programas siguieron caminando, y este año nosotros para poder acceder a estos programas tuvimos que conseguir los recursos para cubrir lo que dejó pendiente el Estado", detalló.
Pese a que existe el compromiso de las autoridades estatales para cumplir con la entrega de estos recursos, comentó que se ha hecho la solicitud al Secretario de Administración y Finanzas, Armando Villarreal, de apresurar las gestiones para que los porcentajes que les corresponden lleguen lo antes posible.
"Son casi 12 millones lo que les toca aportar y a pesar de que el año está por terminar no nos han dado ni un quinto". 
