El sindicato de trabajadores de apoyo demandará a la ciudad por los despidos
El sindicato que representa a cientos de trabajadores de apoyo escolar que perdieron sus empleos el mes pasado planea demandar a la ciudad el miércoles, alegando que los despidos eran innecesarios y discriminatorios debido a su impacto desproporcionado sobre las escuelas que atienden a estudiantes pobres.
La demanda es, posiblemente, la última arma a disposición del sindicato, del distrito municipal 37, en su esfuerzo por revocar los despidos.
Seiscientos setenta y dos ayudantes de la escuela, los coordinadores de padres y otros empleados que estaban entre los peor pagados de la ciudad perdieron su trabajo el 7 de octubre, en un movimiento que los líderes sindicales han descrito como una venganza política por su negativa a permitir, la primavera pasada, el acceso por parte de la ciudad a un fondo de asistencia sanitaria a cargo de grupos de trabajo para cerrar su brecha presupuestaria.
Las autoridades municipales han negado categóricamente esa acusación.
En una audiencia en el Ayuntamiento el mes pasado, el consejero de educación, Dennis M. Walcott, dijo que los despidos eran una parte del presupuesto aprobado en junio.
Un miembro del Consejo contraatacó diciéndole que nada en el presupuesto especificaba que los miembros del personal de apoyo de la escuela serían despedidos.
Funcionarios del distrito municipal 37 dijeron que presentaron la reclamación por escrito, advirtiendo al Departamento de Educación de que sería demandado. Se celebrará una conferencia de prensa el miércoles para anunciar la presentación oficial de la demanda, en el Tribunal Supremo Estatal en Manhattan.
La demanda incluirá al Sr. Walcott y al Departamento de Educación de la ciudad como acusados, y cuenta con ocho trabajadores despedidos como demandantes, todas ellas mujeres negras o latinas, al igual que la mayoría de los asistentes que perdieron sus empleos.
Elizabeth Thomas, portavoz del Departamento Legal de la ciudad, dijo que la ciudad no había visto la demanda y por lo tanto no podía hacer comentarios sobre sus alegaciones específicas.
Según un borrador de la demanda obtenido por The New York Times, el sindicato se ha centrado en el número de despidos en las escuelas de zonas pobres de la ciudad para apoyar una reclamación por trato injusto, diciendo que las escuelas pobres perdieron más asistentes, ya que habían sido insuficientemente subvencionados de forma crónica.
Se señala que si bien no hubo despidos en Staten Island y unos pocos despidos en las escuelas en el Upper East Side o TriBeCa, 17 asistentes escolares perdieron sus empleos en el Distrito 23 en Brownsville, Brooklyn, y 46 fueron despedidos en los Distritos 8 y 9 en el Sur del Bronx.
Teniendo en cuenta la pérdida de cinco de los ocho asistentes empleados por la Escuela Pública 36 en Harlem, donde el 68 por ciento de los estudiantes viven en la pobreza, la demanda dice, "Esto no es un barrio de padres adinerados que puedan recaudar fondos para cubrir el déficit presupuestario".
P.D. El presupuesto del distrito 36 se redujo en un 3,26 por ciento este año, y también perdió dinero cuando la ciudad cambió la forma en que calcula la financiación adicional para cada matriculación por estudiante pobre en las escuelas.
El sindicato también afirma que los directores de escuelas secundarias pueden haber sido engañados por el lenguaje en un memorándum que autoriza el despido de los coordinadores de padres.
El memorándum utilizaba la palabra "excedente" para describir la acción, a pesar de que "excedente" describe con mayor frecuencia el acto de trasladar a un maestro de la nómina de una escuela a una bolsa de trabajo, cuyos sueldos son pagados por la oficina central.
"Sesenta y seis coordinadores de padres fueron despedidos", dice el borrador de la queja, "y no sólo en excedente".
