El Gobierno español no plantear objeciones sobre los vuelos de la CIA 
El Gobierno español no plantear objeciones sobre los vuelos de la CIA con prisioneros talibanes y de Al Qaeda que iban a Guantánamo a través de territorio español, según el el embajador de Estados Unidos en el telegrama de Madrid. 
Así se refleja en los documentos filtrados (cables) de Wikileaks para el diario El País, donde es añadir que el primer vice-presidente del Gobierno en ese momento, María Teresa Fernández de la Vega, ha pedido que el Ejecutivo español fue informado en orden "para ser capaces de demostrar que se había llevado a cabo un seguimiento adecuado de los procedimientos de las aeronaves extranjeras que cruzan España". 
En junio de 2006, tras un informe del Consejo Europeo, donde hubo acusaciones de complicidad en prácticas en contra de los derechos humanos en una docena de países, entre los que está España, una reunión tuvo lugar entre los antiguos norteamericanas el embajador Eduardo Aguirre y Fernández de la Vega. 
El vice-presidente reconoció que el consejo del informe "había tomado el Gobierno de Zapatero fuera del juego" y ha insistido en que España no tienen nada que ocultar en relación con este asunto. 
"De la Vega recalcó que España no plantear objeción a la inteligencia de los vuelos sobre el territorio español". 
"Simplemente queremos ser informados" para evitar que "cogidos desprevenidos", Aguirre se refiere en un telegrama. 
También el ex Ministro de Asuntos Exteriores, Miguel Ángel Moratinos, indicó que el embajador que el Ejecutivo español "quería dar a esta cuestión tan poca atención posible, a pesar de estar en manos de los jueces, el Gobierno ha tenido una influencia limitada". 
Por otro lado, en enero de 2007, el fiscal Vicente González transmitió a la Embajada de que él no intentar bloquear la iniciativa del juez de solicitar la desclasificación de documentos del Centro Nacional de Inteligencia (CNI) y del Ministerio de Defensa sobre los vuelos de la compañía ". 
Esta información no contiene ningún elemento incriminatory ni ninguna información sensible ", explicó la Embajada después de hablar con la fiscalía. 
Sin embargo, los Estados Unidos se refleja en su preocupación por "la aparente coordinación entre el juez español y alemán fiscales," más que el declassified información del CNI o el Ministerio de Defensa. 
"Esta coordinación entre los investigadores independientes complicará nuestros esfuerzos para gestionar discretamente el caso entre Gobiernos", dice Aguirre. 
En marzo de 2007 durante un almuerzo entre el embajador de los Estados Unidos y el ministro del Interior, Alfredo Pérez Rubalcaba, éste ha dicho de él que "aunque los jueces españoles están rabidly celoso de su independencia y hará lo que consideran que es correcto," había dado instrucciones a sus colaboradores "para evitar comentarios de inflamed retórica, en un intento de reducir la temperatura". 
El embajador también expresa su preocupación por la acción del PP en este asunto. 
"A pesar de su pro americano orientación general, nuestra experiencia sugiere que el PP no duda en puede explotarse inteligentemente ningún indicio de que el Gobierno de Zapatero tolerado o ignorado deliberadamente las acciones de los Estados Unidos, que podría interpretarse como posibles violaciones de los derechos humanos, aunque estas revelaciones tienen consecuencias negativas para el Gobierno de los Estados Unidos", indica. 
