El grupo catalán ha facilitado miles de pasaportes a Al Qaeda 
Además de los siete detenidos en Barcelona, en Tailandia hubo tres 
Los siete pakistaníes y el nigeriano, detenido por agentes de la policía de Barcelona inteligencia formaban un grupo yihadista que dirige de Tailandia, facilitó un pasaporte a diferentes grupos de Al Qaeda, entre ellos "Los Tigres para la Liberación de Tamilm Territorio" (LTTE) y "Laskar e Taiba" (Dejad), autor de este último uno de los atentados de Bombay que causó la muerte de 106 personas en 2008. 
El Ministerio de Interior ha prestado atención a estas investigaciones, hasta el punto de asegurar que con "Kampai operación", ha sido "debilitar" del aparato de falsificación de Al Qaeda a nivel internacional y, "por tanto, su capacidad operativa". 
Los investigadores calculan que la celda, durante los dos años que ha estado activa en Cataluña, ha sido capaz de enviar miles de pasaportes a Tailandia, donde fueron falsificados y pronto distribuida a los grupos que integran la galaxia Al Qaeda para que su "combatientes" pueden cruzar las fronteras europeas y los de otros países occidentales con total impunidad. 
El desmantelado células no es el único que la red yihadista en Europa, por este motivo en las investigaciones no han participado, además de los servicios de Tailandia, unidades policiales europeas, razón por la que no descartar que en territorio de la UE se producen sucesos similares a las que se ha desarrollado la noche del martes en Barcelona. 
En coordinación con esta operación (La Junaid pakistaní Humayun, Atiqur Rehman, Jabran Asghar, Malik Iftikhar Ahmad, Mohammad Saddique Khan Begum, Tanveer Arshad y el nigeriano Babatunde Agunbiade fueron detenidos), en Tailandia otra había desarrollado con la captura de los pakistaníes Muhammad Athar Butt y Zeeshan Ehsan Butt y los tailandeses Sirikanlaya Kijbumrung. 
El grupo se encuentra en España y otros países europeos se dirige desde Bangcock 
La red catalana, parte de que se ha alcanzado en 2009, principalmente robado pasaportes a los turistas que cumplían los requisitos marcados por la llamada "Worldwide islámica frente". 
Es decir, los documentos tenía que estar en el nombre de hombres de entre 25 y 45 años, con validez de varios años y sin visados impresos. 
En medios de la investigación se destaca que, por el momento, no hay datos ha sido encontrado relacionados con las personas detenidas en Cataluña en relación con el atentado de Bombay, aunque el autor de este ataque, "Laskar e Taiba", ha sido uno de los grupos que reciben de los pasaportes robado en España y pronto falsificado en Tailandia. 
Sin embargo, cabe mencionar que días antes de este ataque comprometido, desde Cataluña había enviado a través de una agencia de transferences sobre algunos miles de dólares que "se han invertido" en la compra de teléfonos móviles, tarjetas que antes eran utilizados por los miembros del "comando" que acabó con la vida de 106 personas. 
Los policías han capturado un gran cantidad de documentación. 
