La CECA descarta la segunda gran oleada de propósito en las cajas de ahorro 
El jefe de una dirección general de la CECA, José Antonio Olavarrieta, descartado ayer que una enorme ola de propósito de cajas de ahorro va a tener lugar y insistió de nuevo en la rapidez con la que la reconstrucción del sector está siendo. 
Cuando el proceso de concentración de las cajas de ahorro, la había varias organizaciones que aseguró que no participar en esta primera etapa y que sería esperar a la segunda ronda. 
Sin embargo, el jefe de una dirección general de la Confederación Española de Cajas bancos (CECA), José Antonio Olavarrieta, descartado ayer que este nuevo gran ola de operaciones va a tener lugar. 
Creo que la mayor parte del propósito se ha producido, la incorporación de Cajasol para el grupo de Banca Civica no puede llamarse una segunda ronda, no son sólo los ajustes. 
"La mayor parte es totalmente hecho; tal vez de 17 podríamos tener 13 o 14, pero todos los grandes procesos se han llevado a cabo bajo la supervisión del Banco de España, que ha colaborado muchos a este asunto", señaló el directivo. 
En declaraciones durante un desayuno de la Asociación de nuevo, y los ejecutivos de Aragón (ADEA), Olavarrieta ha puesto de manifiesto que el proceso de concentración se ha comprometido "con la mayor rapidez posible, y debemos estar muy satisfecho de cómo esto ocurre en los términos que al tiempo, no ahora, estaban marcadas en los planes de negocio con el Banco de España,", subrayó. 
Para ir de 45 salvar bancos con una media de 28.500 millones de volumen de activos a 17 con 75.500 millones es un proceso que no tienen comparación en la historia, reduciendo el número de organizaciones de un 62%, de modo que son mucho mayores a cumplir Basilea al Hemiciclo, subrayó. 
Olavarrieta reconoció que existe "una serie de opiniones bastante pesimista sobre la lentitud del proceso" que demuestra « la falta de seriedad y razón, "porque" lo que el Banco de España se limita a recordar que debemos cumplir el plazo antes de finales de año ". 
El jefe de una dirección general de la CECA, José Antonio Olavarrieta, asegurado ayer que España tiene el más riguroso sistema financiero de Europa y que "probablemente" de todo el mundo, y se le atribuyen a quienes ponen en duda la "falta de conocimiento". 
El directivo demostró que, en la actual coyuntura económica, "puede ser muy relajado" con la situación de las entidades financieras y los ahorros de los bancos, un sistema que ha emprendido una "muy importante" proceso de concentración y que "vaya con la mayor rapidez posible". 
También ha recordado que el banco español salió muy bien con el estrés de comprobar que el BCE en julio. 
