Grammy candidaturas: Cantante de jazz esperanza Spalding mejor es una sorpresa al mejor nuevo artista categoría 
Desempeñar en la petición de un presidente, y están obligados a tomar nota. 
Esperanza Spalding, los 26 años de edad de jazz bassist y cantante mano a dedo por el presidente Obama para llevar a cabo en su premio Nobel de la Paz ceremonia en 2009, marcó uno de los Grammys "sorpresas este año con un alto perfil nominación a mejor nuevo artista categoría. 
Considerando que Spalding se ha celebrado una cifra sobre el escenario de jazz desde su álbum de 2008, "esperanza," la nominación es un poco de un jefe de scratcher, pero es coherente con los Grammys "normas de un artista no la liberación de más de tres álbumes antes de la grabación que" establece la identidad pública de este artista ". 
Su ambicioso 2010 álbum, "Cámara Music Society," sin duda marcó un paso adelante, y dada su airily invitación verbal al estilo y una filigrana mano del pop, funk e influencias de América Latina, es posible sacar al menos una confirmación de Spalding de Norah Jones "gran éxito en 2003, los más cercanos equivalente al Grammy votantes mirando hacia el jazz neighborhood en esta categoría en los últimos años. 
En otros lugares Grammy votantes honored acertadamente la Vijay Iyer del Trío "Historicity" en el álbum instrumental categoría, un vigorizante emocionante-paseo de una grabación que fue un crítico favorite el año pasado. 
Entre los Iyer estarán compitiendo contra incluyen veterano saxophonist James Moody 's "Moody 4B" y keyboardist John Beasley "del Positootly". 
Trombone Shorty, un raucous Nueva Orleans favorite y invitado frecuente acerca del asunto HBO "Treme," fue honored del jazz contemporáneo categoría, que por lo demás inclina decididamente hacia la fusión con cierto reconocimiento hacia álbumes por Stanley Clarke, John McLaughlin y Jeff Lorber. 
Los salvajes, steampunk informados Darcy James argumentan Secreto de la Sociedad ganaron algunos bien merecido reconocimiento en el gran colectivo categoría, compitiendo contra la Billy Childs colectivo ricos de la cámara de jazz y nunca-aventurero Dave Holanda, cuya octet vivos del álbum "Pathways" fue un buen ejemplo del bassist democrática del lado como bandleader. 
