Romano va hacia su primer título 
Rubén Omar Romano cuenta con tres derrotas en las finales, que durante su carrera subidas y bajadas, pero sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey en la final, además de dos estilos diferentes marcada por sus técnicos de cara, que se encuentran entre otros con un contraste marcado por los resultados. 
Rubén Omar Romano cuenta con tres derrotas en las finales, que durante su carrera subidas y bajadas, pero sabía cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora ha hadn no se ha alcanzado el objetivo y esta es la razón por la que esta oportunidad es muy especial para él. 
El argentino ha acabado se consuela con la medalla del corredor de, y se quedaron un paso por detrás de los ganadores y peculiares con equipos similares ha jugado finales consecutivas. 
Santos llegó a su primera final como entrenador en la apertura Match de 2002, cuando tomó las riendas de Morelia con que él cayó por 4-2 ante Toluca; más tarde, en el Encuentro Closing de 2003 también ha llegado al duelo decisivo y él también perdió por 3-1 e incluso antes de Rayados. 
Ya con Santos Laguna, en la Bicentennial Match de 2010, una vez más ante Los Diablos, Rubén sufre un nuevo revés, ya que su equipo terminó hace igualmente 2-2 ante la salchicha decisiones después de 210 minutos de juego, pero en el turno de sanciones que el propio con ventaja de 3-1 con dos oportunidades para sellar el título, pero finalmente tres jugadores fallaron desde los 11 pasos y sufrió el cambio de 4-3. 
Rubén ya perdió dos finales con Diablos Rojos y uno con Monterrey, su rival en turno, por lo tanto, no lo hace a sufrir la misma suerte, él quiere celebrar un título por primera vez, y afirma que lo más importante para él es la institución. 
Quiero ser un campeón, yo no quieren romper la estadística, se trata de un club, por una pasión y, en consecuencia, el título llegará a mí, pero lo anterior es más importante, comentó el timonel al ser interrogado sobre el número ha contra jugando finales. 
Muy eficaz ha la anterior final, de la que, asegura, ha aprendido mucho, "la única lección que podemos aprender es que hasta que el árbitro el final no podemos celebrar, nos preparamos, así como los jugadores, porque el tiempo anterior, con dos sanciones que estaban a punto de abandonar y creo que es una lección que deben aprender, no podemos celebrar hasta el juego termina". 
Sabiendo que esta serie podría definirse en la pena de diversión, algo que da problemas, porque él confía en sus jugadores: « uno nunca espera para ir a las sanciones, sino para acabar en tiempo regular; a veces que no tienen ninguna alternativa y es necesario estar preparados; en el partido anterior estábamos preparados, lamentablemente destino desempeñó en nuestras manos; a veces los nervios o ansiedad para celebrar el título en un mano, pero no alcanzar este objetivo, y esto nos ha dejado algo de esta última que esperamos ganar ". 
Roman debe dejar de ser un corredor técnico-y degustación por primera vez la gloria que los títulos dan. 
