IP peticiones resultados del Congreso 
Eduardo Dávalos, presidente de la CEC, propuso que los suplentes asumen la gran responsabilidad de ser un ejemplo para una mejor Sinaloa por los diversos desafíos a los que se enfrenta. 
Un Legislation buenas obras y libre de acuerdos entre los partidos y el Ejecutivo estatal está reclamado por el sector empresarial de Mazatlán, porque hay un convulsed Sinaloa que se enfrenta a grandes problemas. 
Ayer la 60 legislatura fue votado en, integrada por siete fuerzas políticas, 19 diputados del PRI, 13 del PAN, tres del Partido Nueva Alianza, dos del PRD, del PT, uno de los Convergencia y uno más del PVEM, lo que significa un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso de los S-Estado es mencionado que llegan a cumplir una gestión limpia de compromiso con la sociedad y los distintos sectores que requieren un responsable trabajo legislativo. 
Eduardo Dávalos Zamora, presidente de la Empresa del Consejo Coordinador, propuso que los liberados hace 40 diputados del Congreso del Estado ha asumido la gran responsabilidad de ser un ejemplo para una mejor Sinaloa por los diversos desafíos a los que se enfrenta. 
Esperamos que los suplentes realmente va a ejercer su derecho, libre de acuerdos entre los partidos, porque es la costumbre de hacer acuerdos con el fin de proteger a sus propios intereses y convertirse en un personaje en un carnaval de los gobernadores y los líderes de las fracciones parlamentarias. 
De ello habló de certificar el compromiso para establecer los necesarios puentes que podría ayudar al Gobernador para seguir adelante. 
Esperamos que vienen a hacer un trabajo digno y, sobre todo, su compromiso con la sociedad y los sectores porque los habitantes de Sinaloa fueron los que les dio el voto de confianza durante las últimas elecciones. 
José Ramón Manguart Sánchez, presidente de la Asociación de Hotels Tres Islas, considera que uno de los mayores retos para los 40 representantes populares es la de impulsar y añadir fuerzas en busca del crecimiento económico del Estado, porque hoy en día, la situación económica es muy complicado. 
Lo más importante es impulsar el crecimiento económico, que genera incentivos para la inversión y la infraestructura y que de alguna manera constituirá una nueva generación de puestos de trabajo. 
En cuanto a la actividad turística, ha exigido que los nuevos legisladores dan el peso revisado en el presupuesto estatal a fin de fortalecer la Secretaria de Turismo. 
Como he entendido es el segundo departamento del Estado con menos presupuestos y es incongruente un importante y la actividad económica generando monedas y la inversión y que directamente compite con la industria agrosilvicultura. 
Aparte de que el etiquetado recursos el detonante proyectos turísticos que contribuyen a la seguridad del Estado y actualizar la Ley del Alcohol, que no ha sido capaz de resolver en las legislaturas anteriores. 
