Los fiscales no cargo senador Pabellón 
El Departamento de Justicia, los fiscales han despejado el senador John Pabellón de acusaciones penales derivadas de su expediente con una campaña antiguo ayudante y sus esfuerzos para garantizar los grupos de trabajo de la mujer del marido, el senador de abogados anunció el miércoles. 
La decisión final la más grave amenaza legal ante el señor Pabellón, Nevada republicano que era considerado un republicano posible candidato presidencial en 2012 hasta el escándalo sobre su caso hizo titulares nacionales del año pasado y han dañado su carrera. 
Señor del Pabellón oficina dijo que estaba "muy contento" por la decisión, que ha seguido una investigación yearlong. 
El senador aún podría enfrentarse a acciones disciplinarias por el Senado comité ético. 
Señor del Pabellón de abogados dijo que el Departamento de Justicia había "nos informa de que el senador Pabellón no es ya un objetivo de su investigación y que no tiene planes para presentar cargos contra él en este asunto". 
El Departamento de Justicia se negó a comentar el caso. 
El anuncio fue algo de sorpresa a la ética muchos abogados fuera del Departamento de Justicia, quien ha dicho que parecía ser una prueba importante para indicar que el señor Pabellón puede haber conspirado para violar una prohibición de presión federal. 
Entrevistas, e-mail y otros documentos publicados por primera vez en octubre de 2009 en The New York Times indicó que el señor Pabellón había ayudado a Douglas en Hampton Court, que fue uno de sus acompañantes, asegurar la presión lucrativo trabajo para ganar el silencio del Señor en Hampton Court y su esposa, Cynthia, la senadora del asunto con ella. 
La señora en Hampton Court una vez sirvió como tesorero del Pabellón de la campaña. 
Señor Pabellón en un número de representantes políticos para encontrar trabajo para el señor en Hampton Court y luego ha defendido por su nombre después de que habían alquilado señor en Hampton Court de presión para ellos, según los documentos y entrevistas. 
Porque el señor en Hampton Court recientemente había sido un ayudante al señor Pabellón, fue prohibido por ley la presión de su ex empleador o el Senado como un conjunto de un año. 
La ética expertos dijeron el acuerdo inusual entre el señor Pabellón y señor en Hampton Court, que eran amigos cercanos antes del asunto, parecía reñida con la así llamada puerta giratoria presión prohibición. 
De la prueba que se ha hecho público, "no parecía ser una prima facie de una conspiración para violar y violación sustancial de la puerta giratoria estatuto," dijo Stanley Brand, un abogado de Washington que se está especializando en la defensa de los clientes investigados por el gobierno. 
Mientras que el Departamento de Justicia funcionarios se negó a explicar el razonamiento detrás de la decisión en el Pabellón caso, señor Brand y ética otros abogados dijo que el departamento apareció cautelosos a la hora de asumir las persecuciones políticas tras una serie de alto perfil contratiempos para su integridad pública sección, incluida la decisión del año pasado para retirar la acusación contra el ex senador Ted Stevens en medio de acusaciones de mala conducta prosecutorial. 
Los fiscales federales "son claramente gun tímido," dijo Melanie Sloan, el director ejecutivo de Ciudadanos de Responsabilidad y Ética en Washington, un grupo de defensa que hizo varias denuncias contra el señor Pabellón en el caso. 
"Esto dice básicamente de alto rango funcionarios gubernamentales ahora puede asumir las leyes no se aplican para ellos", ha añadido. 
Paul Coggins, señor del Pabellón de plomo abogado, dijo en una entrevista que recibió una llamada telefónica de un Departamento de Justicia fiscal el lunes como consecuencia de la próxima jornada, diciéndole que el departamento no se buscan cargos contra su cliente. 
Señor del Pabellón de equipo de defensa han estado colaborando con los fiscales en intentar convencerles de que el senador como su oficina ha reiterado en una declaración el miércoles, "ha actuado de conformidad con la ley". 
Señor Coggins se negó a explicar los argumentos jurídicos que hizo a los fiscales. 
"No estoy cómodo entrar en los detalles de las conversaciones con el Ministerio de Justicia, salvo para decir que creemos que tomó la decisión correcta", dijo. 
El mes pasado, la Comisión Electoral decidió abandonar una investigación sobre una queja por el grupo de ética alegando que dólares 96,000 pago desde el Pabellón de los padres de los Hamptons violó federal de la ley electoral. 
La comisión electoral lo dijo no tener pruebas suficientes para demostrar que el dinero fue nada salvo un regalo. 
Una empresa para que el señor Pabellón ayudó al señor en Hampton Court encontrar trabajo presión fue NV Energía, una gran empresa Nevada que durante mucho tiempo había apoyado el senador. 
Un e-mail enviado en diciembre de 2008 demostró que, después de que la compañía ha llevado al Señor en Hampton Court de como un grupo de presión, Pabellón del jefe del equipo, Juan López, comunicarse con el señor en Hampton Court y le dijo que era "golpes" el Ministerio del Interior en un tema de controversia. 
Señor Pabellón también asistió a un almuerzo con el señor en Hampton Court y otro cliente Nevada, Allegiant Air, y pidió al secretario de transporte para crear una reunión sobre la compañía del nombre después de que había contratado el señor en Hampton Court de los grupos de trabajo. 
Cuando la noticia del suceso han surgido por primera vez el año pasado, señor Pabellón disculpó a sus electores y dimitió de su cargo como la cuarta rango líder republicano en el Senado. 
Tras mantener un perfil bajo durante muchos meses, señor Pabellón dijo a los reporteros dos semanas que tiene previsto presentarse a un tercer mandato en el Senado. 
En el anuncio de que el señor Pabellón no era ya el objetivo de una investigación penal, su portavoz, Jennifer Cooper, dijo el senador esperaba la comisión ética podría seguir rápidamente el Departamento de Justicia de plomo y poner fin a su investigación. 
"El senador Pabellón espera continuar su trabajo en nombre del pueblo de Nevada," dijo. 
