El congreso aprueba la transposición de Mifid que tenía lugar el 1de noviembre
Junto a sus actas parlamentarias, que terminado hoy con la votación parcial del Congreso sobre las modificaciones incorporadas al proyecto en el Senado, el gobierno se ha sometido a audiencia pública la regulación que desarrollará la nueva ley, con el objetivo de fuerza de ino que llega antes de los extremos de año.
Los representantes de grupos diferentes aceptados al enfatizar los esfuerzos hechos por delegados y senadores para negociar y aceptar la mejor legislación para garantizar la protección de los inversores y regular en detalle la actividad de organizaciones para que los mercados funcionen eficazmente.
El Mifid, que corrige el Acto de Bolsa de Valores, implica la modernización de mercados de capitales, mientras refuerza la protección de inversor, mejorando las facultades de fiscalización del Comisión Nacional del Mercado de Valores (CNMV) e impulsa cooperación entre los diversos supervisores de la Unión Europea.
La nueva reglamentación les concederá servicios consultivos financieros a compañías especializadas así como a individuos naturales o legales, y crea un nuevo tipo de compañías consultivas financieras (ESIS), las compañías consultivas financieras (AFI), que incluyen empresas estándares, corredores, y las empresas de administración de títulos en cartera.
Además, extiende la cantidad de sistemas disponibles para la ejecución de operaciones financieras, tan incluido en la regulación están los mercados de valores ya emitidos, los sistemas comerciales multilaterales, y los sistemas de interiorización de órdenes, éstos competirán con los directores de mercado bursátil actuales.
La ley también exige que las compañías de servicios de inversión revelen que al mercado los detalles clave de su negocio retratan, se exponen a exposición y formas de gestión del riesgo, y para mantenerse en un registro de todas sus operaciones facilitan la supervisión por el CNMV.
En su pasaje por el Comité en Asuntos Económicos del Congreso, varias modificaciones se introducían, más notablemente las deudas de securitised se deberían considerar como un instrumento financiero "complejo" debido a su riesgo alto para el inversor, que se ha demostrado por qué sucedía con el americano de riesgo alto deudas hipotecarias (subprincipio).
Además, la transposición sacaba provecho de la directiva para definir legalmente las funciones que pueden desarrollar graduados en Economía y Contabilidad en 30 años después de la aprobación de decreto en 1977, eso delimita las funciones profesionales reservado a profesional economistas.
Para su parte, el Senado promovía la creación de nuevos papeles en el sector financiero, como el asesor financiero, que trabajará de alquiler o recompensará, no requerir aprobación de SEC y podrá proporcionar sus servicios y corretaje de productos de mercadotecnia a clientes en diversas empresas de inversión al mismo tiempo.
