Mirando el celta en Milán un punto válido octava parte
Milán y celta están jugando en martes en San Siro en busca del punto que necesitaban lograr sus objetivos respectivos en el cierre de la liga de "campeones", como se utiliza a los italianos para estar primero y el escocés para su clasificación que sentencia.
Los italianos añadían diez puntos y ya certificaban en la quinta parte pase de día con una corbata en Portugal, mientras el celta tiene nueve puntos, pero todavía necesita que otro se asegurara de que el Shakhtar, con seis, y ese Benfica, que tiene cuatro, no lo adelantan.
Estas dos correspondencias del Grupo D se tocarán en una semana antes del extremo del sexto día, desde que Milán tiene que jugar en el Mundial de Clubes en Japón, donde hacen su inicio sobre el 13 en las semi-finales en busca de un lugar por la final en 16.
Así, este grupo se cerrará antes del descanso y Giuseppe Meazza parece que espera una corbata como el resultado, pero los dos equipos intentarán ponerse manos a la obra con una victoria, y los italianos no querrán especular en casa y el celta sabe que ganar estaría primero y garantizaría un cruce mejor en las finales de cuarto.
Al Gordon Strachan el equipo podría servir incluso una derrota a Shakhtar clasificado si no victorias, pero puede no ser confiado porque la igualdad sobre nueve puntos significa que los Ukranians pasan, quién perdía la última semana en Glasgow (2-1), pero ganaba (2-0) en otro duelo en vivo.
De esta forma, Milanists amenazan con hacer de ello una noche amarga para el escocés, el cual confiar en meterse en los cuartos por segunda vez en fila en los Campeones reestructurados League, después de que se derrotaran precisamente en esto por última vez alrededor por un objetivo de Kaka en el tiempo extendido (1-0) después de 0-0 en la ronda.
Esperando ya que la victoria del "rossoneri" será el Shakhtar al cual solamente la victoria servirá, en el acontecimiento que el celta perdía los dos entran en cuartos para continuar en el UEFA.
Y en cuanto a Benfica, a pesar de ser el último y sin ninguna esperanza de quedarse en la competencia europea superior, podría llegar a tercer lugar con una victoria, lo cual juega a UEFA.
