Esperanzas que Fed cortará ritmos conducen a oleada demercado bursátil mundial
Leapt de acciones en los dos lados del Atlántico ayer después de que las esperanzas de mercado de que la Reserva Federal intentará calmar condiciones de crédito con otros cortes de tipos de interés se aumentaran calmando comentarios del vice-presidente del banco central de EE.UU.
Mercados bursátiles subidos en Londres, Nueva York y a través de Europa después de Donald Kohn, 2 a Ben Bernanke, el Presidente de la Fed, no decía que policymakers deben ser "flexibles y pragmáticos" al responder a estrés continuado en mercados de capitales.
En un esfuerzo claro por tranquilizar mercados preocupados entre señales de tensiones de crédito renacientes, el Sr. Kohn decía que la turbulencia reciente "había revocado en parte parte de la mejora en el funcionamiento de mercado sobre la última parte de septiembre y en octubre".
Si la turbulencia elevada persista, aumentaría la posibilidad de fijación más lejana en condiciones financieras para unidades familiares y negocios, decía.
Los comentarios eran tomados por inversores como señal que la Fed se mantiene preparada de entrar con inyecciones nuevas de capital en mercados de EE.UU., y los posibles tipos de interés más lejanos cortan, para estabilizar condiciones de crédito.
Los comentarios también ayudaban a calmar Wall Street entre más malas noticias sobre la economía de EE.UU., como las ventas de casas de EE.UU. alcanzaban un disco bajo en octubre.
El fallout de la confusión financiera era enfatizado por un anuncio de Bear Stearns, el banco de inversiones, de que cortará 650 trabajos, o 4 por ciento de su mano de obra global, en una ronda de recorte de coste para compensar fuertes pérdidas de sus apuestas que perdían por el sector de préstamos de ahorro-vivienda sub-principales de EE.UU.
Se espera que solamente 20 de esos puestos vayan en Londres, donde el banco emplea a 1,500 personas.
En Nueva York, el promedio industrial de Dow Jones saltado por 331 puntos, o 2.55 por ciento, a cierre en 13,289.40, mientras el índice de S&P 500 más ampliamente basado subía por 2.65 por ciento.
En Londres, los FTSE 100 clasifican 165.5 puntos rosados, o 2.7 por ciento, a cierre en 6,306.2, añadiéndose más que el £39 mil millones por valor de las compañías de ficha de azul de Gran Bretaña.
El Dax de Alemania clasificar 2.6 por ciento rosado, y el CAC40 deFrancia era hacia arriba de 2.3 por ciento.
Más temprano, la resalida de estrés de crédito en los mercados era encendía a gran altura después de que la demanda fuerte en una subasta de fondos junto al Banco Central Europeo de tres meses viera que ésos prestaban a los bancos mercantiles de Europa a un 4.7 por ciento pesado, el ritmo más alto desde abril de 2001.
Presión sobre el Banco de Inglaterra para seguir el Fed y ECB e inyectar extra fondos en mercados monetarios en Londres montados como el crédito tira veía los ritmos de "interés Libor" para prestar entre bancos de UK de tres meses cerraban su más alto desde último septiembre, a las 6.59 por ciento, después de una subida firme desde noviembre 12.
