EnvironMin y el seis por ciento de Hungría
Ministro para el Ambiente, Gábor Fodor ha dicho que reuniones de nivel profesionales en post-2012 las cuestiones de clima internacionales terminarán el martes. La conferencia misma oficialmente se abre el miércoles, cuándo examinan los ministros la cuestión.
Los profesionales y los políticos de 192 países son destinados a discutir el Mapa de Carreteras de Bali que se concentra en esfuerzos por cortar emisiones de gas de efecto invernadero después de 2012, cuándo expira el Protocolo de Kyoto.
En este momento el desarrollar y las naciones urbanizadas están en el medio de una disputa acalorada.
Los Estados Unidos lo han dejado ser sabido que es reticente negociar números precisos aunque uno no se opone a ello a aceptar un 25-40 por ciento corte en gases de efecto invernadero por 2020 cuándo era comparable a 1990.
La otra gran cuestión en la conferencia es si las naciones urbanizadas están preparadas de no solamente reducir sus emisiones sino también ofrecer ayuda financiera y tecnológica a países que lo necesitan.
Un acuerdo alcanzado estaba en apoyo a naciones que se desarrollan.
Un consejo de 16 miembro gestionará la financiación para esto, que se establece por el Protocolo de Kyoto, y funcionará más probablemente dentro de la Facilidad de Ambiente Global de ONU (GEF), escribe el Beneficio de Piac és de publicación local.
El seis por ciento de Hungría
Representando Hungría. El Ministro de Ambiente Gábor Fodor está dispuesto de respaldar esfuerzos de UE por conservar su papel de buque insignia en el esfuerzo de protección de clima global y promover un nuevo acuerdo internacional, ser alcanzado por 2009.
Fodor se fijaba en que la UE hace a sus vistas sobre un 20 por ciento bajar en emisiones de gas de efecto invernadero por 2020 comparadas con 1990, si el "post-2012 el acuerdo" es alcanzado o no, y está preparado de cortarlos por 30 por ciento si el otro comandante urbanizaba regiones del globo y las naciones que se desarrollan están también preparadas de aceptar obligaciones al alcance de sus capacidades y las responsabilidades.
Fodor decía que respalda en 1997, los países que se adherían al Protocolo de Kyoto habían apuntado a una 5.2 por ciento reducción en emisiones en conjunto. Dentro de ese grupo, el 15 miembro UE aceptaba una 8 por ciento caída.
Hungría aceptaba cortar su emisiones de gas de efecto invernadero por 6 por ciento comparados con 1985-1987, un objetivo que pretende encontrar, decía la nota de prensa del ministerio de ambiente.
Los intereses en Bali son a gran altura, ya que un tratado internacional a largo plazo sobre política de clima necesita estar bajo envoltorios dentro de dos años o seguro no será competente entrar en efecto por 2012.. Si eso suceda, las promesas hechas durante la validez del Protocolo de Kyoto no serían seguidas inmediatamente por otro régimen de reducción de emisiones, la necesidad para el cual ganando el Nobel-Prize de la ONU cuerpo científico, el Panel Intergubernamental en Cambio Climático - IPCC- ha señalado en su último informe.
El resultado podría ser una demora en la reducción de emisiones, que pondría Tierra en un cierto curso hacia un calentamiento medio que superaba 2 celsios de grados. Si eso sucede, los científicos dicen que las consecuencias serían espantosas e irreversibles.
