El catalán grupo facilitado millas de pasaportes a Al Qaeda 
Además de los siete presos en Barcelona, en Tailandia hubo tres 
Los siete Paquistaníes y la Nigeriano de las Naciones Unidas detenido por agentes de la Asamblea Barcelona policía inteligencia constituido de las Naciones Unidas grupo yihadista que, dirigido desde Tailandia, facilitado pasaportes a los diferentes grupos de Al Qaeda, entre ellos "El Liberación Tigres para la de Tamilm Territorio" (LTTE) y "Laskar y Taiba" (Vamos a), autor esta última uno de los ataques de Bombay que causó la muerte de 106 personas en 2008. 
El Ministerio del Interior ha prestado atención a estas investigaciones, hasta el punto de asegurando que con "Kampai" operación; se ha "menoscabaría" la aparatos de falseamiento de Al Qaeda a nivel internacional y, "por tanto, su capacidad dispositiva". 
Los investigadores calcular que la celular, durante los dos años que ha participado activamente en Cataluña, ha podido enviar millas de pasaportes a Tailandia, en los que se falsificaron y pronto distribuido a los grupos que integrar la penal Al Qaeda galaxia para que su "combatientes" pueden cruzar las fronteras europeas y los de otros países occidental con total impunidad. 
La desmantelado celular no es la única que la yihadista rojo tenido en Europa, por este motivo en las investigaciones han participado, Tailandia además de los servicios, otras unidades de policía europea, razón no descartar que en el territorio de la UE ocurren acontecimientos similares a una adelantados la noche del martes en Barcelona. 
En coordinación con esta operación (El Paquistaní Junaid Humayun, Atiqur Rehman, Jabran Asghar, Malik Iftikhar Ahmad, Mohammad Khan Saddique Begum, Tanveer Arshad y la Babatunde Nigeriano Agunbiade todos fueron detenidas), en Tailandia otro ha desarrollado con la de captar la Paquistaníes Muhammad Athar Culata y Zeeshan Ehsan Culata y la Sirikanlaya Tailandia Kijbumrung. 
El Grupo sentado en España y otros países europeos estaba dirigida de Bangcock 
El catalán rojo -parte de ella se consiguió en 2009- principalmente robado pasaportes de turistas que cumplen los requisitos marcado por el llamamiento "En todo el mundo islámica frente". 
Es decir, los documentos han de estar en nombre de los hombres entre 25 y 45 años, con validez de varios años y sin imprimirá visados. 
En los medios de investigación se destacó que, por el momento, datos no se ha encontrado relativas a las personas detenidas en Cataluña sobre el ataque de Bombay, aunque el autor de este ataque, "Laskar e Taiba", ha sido uno de los receptores de grupos de los pasaportes robado en España y pronto falsificado en Tailandia. 
Sin embargo, cabe mencionar que días antes de este ataque cometido, de Cataluña había enviado a través de una agencia de transferencias sobre algunos millas de dólares que se "invertido" en la adquisición de telefonía móvil cartas que antes eran utilizados por los miembros de la "comando" que finalizó la vida de 106 personas. 
La Policías han capturado mucha documentación. 
