La geriatra afirma que las muertes fueron causadas por "falta de medios" 
Los propietarios del centro de Olot no descartar que sus asistente muertas más de 11 personas mayores 
Las personas a cargo con el geriátricos hospital La Caritat de Olot (Gerona) ofrecido una conferencia de prensa que ayer para destacar el daño que ha causado a la institución la conducta penal de Joan Vila Dilmé, la enfermera que aunque se mata a menos de una vez personas mayores que había bajo vigilancia. 
El director de la residencia, Joan Sala, aparecido acompañado por el centro del abogado, abogado Joan Canadá, y anunció que "la intención de La Caritat habría que pasador la culpa sobre la persona responsable de la muerte pero" legalidad y responsabilidad nos obliga a asumir la situación procesal civil responsable de personas. " 
Y que además de la pérdida de prestigio sociales que la organización puede encontrar por no haber detectado en tiempo de las actividades delictivas de los sereno, la gran amenaza para la Caritat tiene ahora toma la forma de de las Naciones Unidas considerable indemnización que ya se calculó por los representantes legales de los parientes de víctimas. 
Joan Vila ha Dilmé confesó que el primer delito remonta a agosto de 2009 y que desde entonces el orador no detener la matanza. 
El juez mencionado en el documento que encargadas de la exhumación de ocho organismos -antiguos pacientes de la geriátricos hospital- los cuales ella ya sospechaba que en muchos casos ningún médico personalmente estudian los muertos órganos pero, teniendo en cuenta la edad y la patologías de los pacientes, el procedimiento se formuló por teléfono. 
La Caritat, a través de su director, plenamente negar este fin ayer y mencionó que "la falta de medidas no habría sido en cualquier momento la causa de lo que ha ocurrido". 
El abogado de La Caritat añadido que "en la causa no hay indicios de que haya de las Naciones Unidas imprudente acción por parte de cualquier otra persona que no es el culpable una". 
Una bautizados como "Angel de la muerte" confesó 11 asesinatos anteayer y detallada que ha cometido el delito en primer lugar el 29 de agosto de 2009 y de las Naciones Unidas mes y medio después, muerte a otro abuela. 
En este caso de las Naciones Unidas sobredosis de la insulina ante ella la pena; a diferencia del primer delito ha comprometido con una combinación de sedante comprimidos. 
El director de la Caritat dice que es complicado controlar que el personales del centro de tener acceso a medicamentos. 
La sobredosis de la insulina y la sedante cóctel habría sido el mecanismo utilizado en seis de los nueve delitos de que la enfermera, en su afán por aliviar el sufrimiento de los pacientes, utilizado o matanza de ellos. 
Pero las pruebas que se realizan en el laboratorio tendrá que aclarar si Vila no es acostado y intentado asegurar que sus primeras víctimas de de las Naciones Unidas menor pena cruel o si, por el contrario, quemadas ellos internamente por proporcionarles lejía como él ya confesó que había hecho con el que mató a tres mujeres entre los 12 y la 17 de octubre. 
A La Caritat de no dar credibilidad a la aparición de la sereno, ni al número de asesinatos confesó, que ellos no refutar siendo superior, y justifica su actitud en las diferentes versiones que Vila ha dado en sus visitas a los tribunales y el absurdo de cambiar su método de asesinato después de haber cometido con éxito, ocho asesinatos. 
Por eso dicen que sí mismos puesto a disposición de la justicia aclarar el alcance de este acontecimiento. 
