El Gobierno español no plantear objeciones respecto de los vuelos de la La CIA 
El Gobierno español no plantear objeciones respecto de los vuelos de la La CIA con los presos talibanes y AlQaida que iba a través de Guantánamo territorio español, según los EEUU embajador en Madrid el telegrama. 
Así pues se manifiesta a través de la filtrada documentos (cables) por Wikileaks que el diario El País, donde se añadió que la primera vice -presidente del Gobierno en ese momento, Maria Teresa Fernández de la Vega, pedido que España Ejecutivo fue informado en el orden" demostrar que se realizaron correspondientes procedimientos de vigilancia en el exterior de aeronaves que cruzar España. " 
En junio de 2006, después de de las Naciones Unidas informe del Consejo Europeo donde hubo acusaciones de complicidad en prácticas contra los derechos humanos en una docena de países, entre las que es España, una reunión tuvo lugar entre el Norte -ex embajador norteamericano Eduardo Aguirre y Fernández de la Vega. 
El presidente -vice reconoce que el Consejo el informe de" ha adoptado el Gobierno de Zapatero fuera de juego "y insistido en que España no tienen nada que ocultar al respecto. 
"De la Vega subrayar que España no plantear objeción a la inteligencia de vuelos en territorio español". 
"Sencillamente queremos ser informados" para evitar que se "atrapado por sorpresa", Aguirre se refiere en de las Naciones Unidas telegrama. 
También -el ex Ministro de Relaciones Exteriores, Miguel Angel Moratinos, indicó que el embajador español que el Ejecutivo" quería dar a esta cuestión tan poca atención posible, aunque está en manos de los jueces, el Gobierno tiene una influencia limitada. " 
Por otra parte, en enero de 2007, el fiscales Vicente González transmitido a la Embajada que él no intentar bloquear la iniciativa del juez de pedir la desclasificación de documentos del Centro Nacional del Inteligencia (CNI) y de la Ministerio de de Defensa sobre los vuelos de la empresa " 
Esta información no contiene ningún elemento incriminatorio ni ningún tipo de información sensible, "explicado la Embajada después de hablar con el ministerio público. 
No obstante, los Estados Unidos a reflexionar sobre su preocupación por "la aparente coordinación entre el juez alemán español y de fiscales", más de la desclasificados información de la CNI o la Ministerio de de Defensa. 
"Esta coordinación entre los investigadores independientes se complicar nuestros esfuerzos para hacer frente discretamente el caso entre los gobiernos"; dice Aguirre. 
En marzo de 2007 durante una almuerzo entre el embajador de EEUU y Ministro del Interior, Alfredo Pérez Rubalcaba, éste observó que a él "aunque los jueces españoles son rabiosamente celoso de su independencia y qué consideran derecho", había dado instrucciones a su colaboradores "evitar comentarios de inflamado retórica, en de las Naciones Unidas intento de reducir la temperatura". 
El embajador también expresa su preocupación por la acción del PP en este asunto. 
"A pesar de su Pro americana orientación generales, nuestra experiencia sugiere que el PP no duda en capitalizando cualquier indicación de que el Gobierno de Zapatero tolerado o deliberadamente ignoradas acciones de los Estados Unidos que podría interpretarse como posibles violaciones de los derechos humanos, incluso si estos revelaciones tener consecuencias negativas para el Gobierno de los Estados Unidos", indica. 
