El programa nucleares Paquistaní genera gran inquietud en los Estados Unidos 
Islamabad da las armas atómicas en "de las Naciones Unidas ritmo más rápido que cualquier otro país". 
La filtraciones de Wikileaks confirmar los vínculos entre los talibanes personas y el Pakistán. 
El contenido de la correspondencia entre los americanos Embajada en el Pakistán y el Departamento de Estado de los Estados Unidos filtrada por la Wikileaks Portal confirma la enorme inquietud que la Paquistaní programa nucleares de deriva en Washington. 
Además de los esclarecedores y sustanciales que se ofrecen detalles sobre el contenido de la conversaciones y las reflexiones del Norte acreditado Americanos representantes diplomáticos en Islamabad, los documentos revelan que la cooperación entre ambos países en la cuestión de la seguridad nucleares, en lugar de aumentar, "disminuye", y que el inestable país asiático da armas nucleares con "de las Naciones Unidas ritmo más rápido que cualquier otro país". 
La peculiaridad de la Paquistaní programa nucleares -que las armas pequeñas no son reunidos pero siguen almacenados por componentes que hacen difícil su destrucción en caso de ataque- -constituye una de las principales causas de preocupación en Washington. 
Así pues es enumeré por el embajador en el Pakistán, Anne W. Patterson, en de las Naciones Unidas informe anterior a la visita de la ex -asesor de Seguridad Nacional, James Jones:" El proximidad de algunas centrales nucleares en el territorio bajo talibanes ataque, la rumorea dispersión del materiales nucleares y la vulnerabilidad de materiales nucleares transporte. " 
El elevado número de personas supone en los arsenales nucleares y los programas los misiles se tiene en cuenta, no sólo por los Estados Unidos, sino también por Rusia, como el motivo por el mantenimiento de la guardia. 
"El Pakistán ha tenido contratar personales con estricta creencias religiosas para proteger a las centrales nucleares; dado los pobres educativo y culturales los niveles, las organizaciones extremistas tienen más oportunidades para reclutar personas para trabajar en los programas nucleares o de los misiles", dicho el experto Yuri Carole, de los rusos Ministerio de Relaciones Exteriores, en una reunión con su estadounidenses homólogo. 
La más reciente información sobre la documentación filtrada por el Portal de Julian Assange es el descenso de la cooperación entre los Estados Unidos y el Pakistán en temas de proliferación nucleares y la elevada tasa de Paquistaní arma nucleares la producción. 
Una oficina de la Embajada en mayo, que describir como "frustrante" la comunicación con el Pakistán, dice que: "La transparencia menudo es inexistente; las ofertas de ayuda siguen sin una respuesta o se les negó la". 
En otro mensaje, Pedro Lavoy, funcionario de la Nación Inteligencia para el sur de Asia, señala que "a pesar de la catástrofe económica, Pakistán da armas nucleares en de las Naciones Unidas ritmo más rápido que cualquier otro país del mundo". 
El embajador Patterson también pide a Washington, durante una visita del Jefe del Ejército, General Ashfaq Kayani, dar órdenes claras a la persona encargada que "el Ejército del Pakistán debe poner fin a la tácita apoyo a los grupos terroristas". 
