Pide al iP resultados del Congreso 
Eduardo Dávalos, presidente de la CCA, propuesto que los diputados asumir la gran responsabilidad de ser de las Naciones Unidas ejemplo para una mejor Sinaloa por los diversos desafíos que enfrenta. 
Una Asamblea Legislativa de obra y decente libre de acuerdos entre las partes y ejecutivo Estado se ha pedido por la empresa del sector de Mazatlán, porque hay una convulso Sinaloa que enfrenta grandes problemas. 
Ayer los 60 legislatura fue votado en, integrado por siete fuerzas políticas, 19 diputados de la PRI, 13 de los PAN, tres del Partido Nueva Alianza, dos de los PRD, uno de los PT N, uno de la Convergencia y uno más de la PVEM, significado de las Naciones Unidas total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso de los -Estado S se mencionó que llegan a cumplir una limpia gestión de compromiso con la sociedad y los diferentes sectores que requieren de las Naciones Unidas responsable trabajo legislativo. 
Eduardo Dávalos Zamora, presidente de la Empresa Coordinación Consejo, propuesto que la libertad apenas cuarenta diputados del Congreso del Estado asumido la gran responsabilidad de ser de las Naciones Unidas ejemplo para una mejor Sinaloa por los diversos desafíos que enfrenta. 
Esperamos que los diputados realmente será ejercer su derecho, libre de acuerdos entre las partes porque es una costumbre formular acuerdos a fin de guardia por sus propios intereses y se conviertan en de las Naciones Unidas carácter en de las Naciones Unidas carnaval de los gobernadores y los dirigentes de la fracciones parlamentaria. 
Por ello el orador habló certificación la autorización para establecer la necesaria puentes que podría contribuir el Gobernador seguir adelante. 
Esperamos que llegan a hacer de las Naciones Unidas trabajo digno y principalmente con la sociedad y los sectores porque la habitantes de Sinaloa fueron quienes les dio el voto de confianza en las últimas elecciones. 
Jose Ramón Manguart Sánchez, presidente de la Asociación de Hoteles Tres Islas, considera que uno de los mayores retos para los 40 representantes populares es uno de iniciar y añadiendo fuerzas en la búsqueda del crecimiento económico del Estado, porque hoy en día la situación económica es muy complicado. 
La más importante es impulsar el crecimiento económico, elementos lo que provoca incentivos para la inversión y la infraestructura y que de algún modo formará una nueva generación de empleo. 
Como el turismo actividad, exigió que el nuevo legislador dar el peso revisado dentro del presupuesto estatal para fortalecer el Secretario de Turismo. 
Como que entendido esta es la segunda departamento del Estado con menos presupuestos y es incongruente una importante actividad económica y generando monedas y de inversión y que compite directamente con el agro industria. 
Aparte de etiquetado que necesitan recursos el turismo detonante proyectos que ayudar a dar seguridad a la situación y actualizar el Alcohol Ley que no ha podido resolver en la anterior asamblea legislativa. 
