Los fiscales no acusación Senador Alférez 
La justicia Departamento los fiscales han aprobado Senador John Alférez de acusaciones penales derivados de su asunto con una antigua campaña ayudante y sus esfuerzos para garantizar grupos de presión trabajo para la mujer al marido, el senador de abogados anunciado miércoles. 
La decisión termina la más graves amenaza que enfrenta jurídico señor. Alférez, la Nevada Republicano que se considera una posible Republicano candidatos presidenciales en 2012 hasta el escándalo en su asunto nacional titulares hizo el año pasado y dañada su carrera. 
Señor. Alférez la oficina dijo que época "ciertamente satisfacción" por la decisión, que han seguido una anual investigación. 
El senador podría aún enfrentamos medida disciplinaria por el Senado comité ético. 
Señor. Alférez de abogados dicho el Departamento de Justicia había "nos ha informado de que Senador Alférez ya no es de las Naciones Unidas objetivo de su investigación y que no tiene planos para presentar cualquier cargos contra él en esta cuestión". 
El Departamento de Justicia rechazó comentar el caso. 
El anuncio vino como algo inesperado a muchos ética abogados fuera de la Justicia Departamento, que ha dicho no parecían importantes pruebas que indican que el señor. Alférez pueden tener conspiraron a perturbar una prohibición penal federales de presión. 
Las entrevistas, e -mail y otros documentos primera divulgación de en octubre de 2009 en La Nuevo York Tiempos señalado que el señor. Alférez han ayudado Douglas Hampton, que fue uno de sus ayudantes, lucrativa trabajo seguras de presión para ganar el silencio del señor. Hampton y su esposa, Cynthia, sobre el senador el asunto con su. 
Mrs. Hampton una vez que actuó como tesorero de de las Naciones Unidas Alférez campaña. 
Señor. Alférez contacto de una serie de políticas patrocinadores encontrar trabajo para el señor. Hampton y entonces transmitido en su nombre después de que hubiera contratados señor. Hampton de vestíbulo para ellos, según los documentos y las entrevistas. 
Porque señor. Hampton acaban de de las Naciones Unidas ayudante al señor. Alférez, época prohibido por ley de campañas su antiguo empleador o el Senado en su conjunto por de las Naciones Unidas año. 
Ética expertos dicho el señor arreglo inusual entre. Alférez y el señor. Hampton, que fueron amigos antes de cerrar el asunto, aparecido en desacuerdo con el así llamado -giratorio puerta de presión prohibición. 
De las pruebas que se ha hecho público, "no parecía ser una prima facie caso de la conspiración que violen, y sustanciales violación de la giratorio puerta estatuto", dicho Stanley Marca, de las Naciones Unidas abogado de Washington que se especializa en defensa clientes investigadas por el Gobierno. 
Aunque Justicia Departamento funcionarios disminuido a explicar el razonamiento que sustenta la decisión en el Alférez caso, señor. Marca y otros ética abogados dicho el departamento aparecido cautelosa de adopción de políticas enjuiciamiento después de una serie de alto perfil -reveses para su integridad pública sección, incluida la decisión del año pasado que merma la persecución contra ex Senador Ted Stevens en medio de acusaciones de mala conducta fiscales. 
Los fiscales federales "son claramente pistola timido", dicho Melanie Sloan, el director ejecutivo de Ciudadanos para Responsabilidad y Ética en Washington, de las Naciones Unidas grupo de promoción que se señalan varias denuncias contra el señor. Alférez en el caso. 
"Esto básicamente dice alto- ranking funcionarios de gobierno puede ahora asumir las leyes no se aplican a ellos, "la oradora añade. 
Paul Coggins, señor. Alférez de conducir abogado, dicho en una entrevista que ha recibido una llamada de teléfono de de las Naciones Unidas Departamento de Justicia fiscales el lunes y de las Naciones Unidas seguimiento de -hasta el próximo día, él dice que el departamento no se busca de acusaciones contra su cliente. 
Señor. Alférez de defensa equipo había sido cooperar con los fiscales en intentar persuadirlos de que el senador, como su oficina reiteraron en una declaración miércoles, "actuado de conformidad con la ley". 
Señor. Coggins disminuido precisar los argumentos jurídicos que ha hecho a los fiscales. 
"No estoy de acuerdo entrar en detalles de mis conversaciones con el Departamento de Justicia salvo para decir que pensamos que fórmula la decisión correcta", dijo. 
El mes pasado, la Comisión Electoral Federal decidió que merma en una investigación independiente denuncia por la ética grupo basado en la que de las Naciones Unidas pago de $96,000 señor. Alférez los padres a Hamptons violado la ley electorales federales. 
La comisión electorales dicho no tenía suficientes pruebas para demostrar el dinero fue nada excepto de las Naciones Unidas regalo. 
Una empresa para que el señor. Alférez ayudado señor. Hampton encontrar grupos de presión trabajo fue NV de Energía, Nevada una gran empresa que tenía tiempo apoyado el senador. 
Uno e -mail enviada en diciembre de 2008 mostró que después de la empresa señalado el señor. en Hampton como cabildero, señor. Alférez el jefe de personales, John López, comunicarse con el señor. Hampton y-le-dijo que época" golpeteo "Departamento del Interior en una cuestión en litigio. 
Señor. Alférez también asistió a una almuerzo con el señor. Hampton y otra de Nevada cliente, Allegiant Aire, y pide el transporte secretario de establecer una reunión sobre la compañía aérea el nombre después de que había contratados señor. Hampton hacer campañas trabajo. 
Cuando noticia del asunto primera superficie año pasado, señor. Alférez disculpado a sus electores y dimitido de su posición como el cuarto -ranking Republicano líder en el Senado. 
Tras mantener de las Naciones Unidas perfil bajo durante muchos meses, señor. Alférez dicho los periodistas hace dos semanas que se proyecta plazo para de las Naciones Unidas tercer mandato en el Senado. 
En anunciando que el señor. Alférez ya no fuera el objetivo de una investigación penal, su portavoz, Jennifer Cooper, dicho el senador espera el comité ético sería más rápido seguimiento de la Justicia del Departamento conducir y finalizar su investigación. 
"Senador Alférez espera con interés seguir su duro trabajo en nombre del pueblo de Nevada", dijo. 
