El Gobierno español no plantear objeciones con respecto a los vuelos de la CIA 
El Gobierno español no plantear objeciones con respecto a los vuelos de la CIA con prisioneros talibanes y de Al Qaeda que iban a Guantánamo a través de territorio español, según el embajador de los Estados Unidos en Madrid el telegrama. 
Así se refleja en el filtrado documentos (cables) por WikiLeaks a diario "el país", donde se añadió que el primer Vicepresidente del Gobierno en aquel momento, Maria Teresa Fernández de la vega, pidió que el ejecutivo española fue informada en orden "para ser capaces de demostrar que se habían llevado a cabo procedimientos de control adecuado en los aviones extranjeros que cruzan España". 
En junio de 2006, después de un informe del Consejo Europeo, donde hubo acusaciones de complicidad en prácticas contra los derechos humanos en una docena de países, entre los que se encuentra España, se celebró una reunión entre el Norte ex- embajador estadounidense Eduardo Aguirre y Fernández de la vega. 
El Vicepresidente reconoció que el Consejo había adoptado el informe "el Gobierno de Zapatero fuera del juego" e insistió en que España no tienen nada que ocultar con respecto a esta cuestión. 
"de la vega subrayaron que España no plantear objeción por la inteligencia los vuelos sobre el territorio español". 
"simplemente quieren ser informado" para evitar ser "tomada por sorpresa", Aguirre se refiere en un telegrama. 
También el ex Ministro de Asuntos Exteriores, el Sr. Miguel Ángel Moratinos, indicó que el embajador español que el ejecutivo "quería dar a esta cuestión tan poca atención posible, aunque está en manos de los jueces, el gobierno tuvo una influencia limitada". 
Por otro lado, en enero de 2007, el Fiscal General Vicente González transmitidos a la embajada de que él no intentar bloquear la iniciativa del juez de la desclasificación de documentos del Centro Nacional de Inteligencia (CNI) y el Ministerio de Defensa con respecto a los vuelos de la empresa " 
Esta información no contiene ningún elemento incriminatory ni ninguna información sensible ", explicó la embajada después de hablar con el fiscal. 
Sin embargo, los Estados Unidos se refleja en su preocupación por la aparente coordinación entre el juez español y alemán fiscales ", más que la información desclasificado del CNI o el Ministerio de Defensa. 
"de esta coordinación entre investigadores independientes se complique nuestros esfuerzos para manejar discretamente el caso entre los gobiernos"; dice Aguirre. 
En marzo de 2007 durante un almuerzo entre el embajador de los Estados Unidos y el Ministro del Interior, Alfredo Pérez Rubalcaba, ésta ha comentado que le "aunque los jueces españoles son rabidly celosos de su independencia y hará lo que considero derecho", que había dado instrucciones a sus colaboradores "para evitar comentarios de retórica abierto, en un intento de reducir la temperatura". 
El embajador también expresa su preocupación por la acción del PP en este asunto. 
"a pesar de su pro norteamericanos orientación general, nuestra experiencia indica que el PP no duda en la capitalización cualquier indicio de que el Gobierno de Zapatero tolerado o ignorar las acciones de los Estados Unidos, que podría ser interpretada como posibles violaciones de los derechos humanos, incluso si estas revelaciones tienen consecuencias negativas para el Gobierno de los Estados Unidos", indica. 
