Grammy nombramientos: Jazz cantante esperanza Spalding es una sorpresa recoger en mejor artista nueva categoría 
Con la petición de un Presidente, y las personas están obligados a tomar nota. 
Esperanza Spalding, el Jazz 26 y bassist cantante designado por el Presidente Obama a desempeñar en la ceremonia de premios Nobel de la paz, en 2009, una de las grammys "sorpresas este año con una propuesta tan destacada en la mejor artista nueva categoría. 
Teniendo en cuenta que Spalding ha sido un célebre figura en la escena Jazz desde su álbum de 2008, "esperanza", el nombramiento está un poco de un head-scratcher, pero es coherente con la grammys "normas de un artista no liberar a más de tres discos antes de la grabación que" se establece la identidad pública de que el artista. " 
Su ambicioso álbum de 2010, "Cámara música la sociedad", sin duda, un paso adelante, y dado su airily una invitación abierta y una forma parte con POP, Funk y las influencias de América Latina, es posible recurrir al menos una línea de puntos a Spalding de Norah Jones "gran éxito en 2003, el equivalente más cercano a los votantes grammy Jazz mirar hacia el barrio en esta categoría en los últimos años. 
En otros lugares grammy votantes con razón a la iyer Vijay de la "historicity & quot; en la categoría del instrumental, un refuerzo de thrill-ride un récord que era un crítico el año pasado favorito. 
Entre los iyer estarán compitiendo en contra de incluir veterano saxophonist James Moody 's "Moody' s" 4b y keyboardist John Beasley "positootly". 
Trombone shorty, un raucous Nueva Orleans y favorito invitado frecuente en la treme HBO "", le fue en la categoría de jazz contemporánea, de lo contrario, fuertemente inclina hacia la fusión con asentimiento hacia discos por Stanley Clarke, John mclaughlin y Jeff lorber. 
La naturaleza, steampunk-informed darcy James sostienen la sociedad secreta ganó un merecido reconocimiento en la gran ensemble categoría, contra la edad Billy Childs ensemble ricos de la chamber-jazz y la ever-adventurous dave Holanda, cuyo octet viven del álbum "conductos & quot; fue un buen ejemplo de la bassist democrático del lado como un bandleader. 
