Alerta sobre plaguicidas consumida por los niños. 
Según un estudio publicado o el miércoles por la Asociación de las futuras generaciones (formelry movimiento para los derechos y el respeto de las generaciones futuras), un niño de 10 consume en un día 81 diferentes sustancias químicas. 
La asociación que predice que sus resultados no poseen, en vista del pequeño número de muestras analizado, un importante valor estadístico, pero ilustrar el problema que nos ocupa, ha comprado en spermarkets de la oise y de París entre julio y septiembre, la cesta de los productos alimenticios en general consumida en cuatro comidas de un niño de diez. 
Estos menús inclduing recomendaciones oficiales, cinco piezas de fruta y verduras frescas, tres productos lácteos y 1,5 litros de agua así como los manjares, fueron examinadas por los laboratorios de investigación clínica con productos químicos, pesticidas, metales pesados y otras sustancias contaminantes. 
El balance es asombrosa: 81 incluye 42 clasificados como sustancias químicas potencialmente o probablemente cancerígeno y cinco clasificados como carcinógenos definitivamente, así como 37 sustancias capaces de inducir a trastornos endocrinos, según los estudios por varias instituciones tales como el centro internacional de investigación sobre el cáncer. 81 sustancias chimiques dont 42 sont classées cancérigènes ou probables possibles et cinq sustancias classées cancérigènes certaines Ainsi que 37 sustancias susceptibles d 'agir comme perturbateurs endocriniens (PE), selon des études de plusieurs instituciones telles le centro internacional de recherche Sur le cáncer. 
Según la associaiton, incluso si, en casi todos los casos, los límites legales de cada sustancia química no se sobrepasen, nuestra investigación demuestra que la realidad de la exposición de los consumidores a potencialmente cancerígenas contaminante es preocupante. 
Para el desayuno, té con la mantequilla y leche solo contienen más de diez posible y tres demostrado residuos carcinógenos y casi veinte residuos potencialmente puede perturbar el sistema hormonal. 
Una manzana de Brasil contenga rastros de seis sustancias químicas incluing un un fungicida, prohibidas en Francia. 
Lo mismo se aplica a la sopa de Kenia incluido en un almuerzo, en la que el estudio encontrado rastros de un poderoso insecticida prohibidos en la Unión Europea. 
En addiiton, medias filetes de atún en conserva, e incluso un baguette y chicles contenía pesticidas y otras sustancias químicas. 
Tapwater contenía nitratos y chloroform. 
Durante la cena, el filete de salmón fue el "", más ricos y 34 de los residuos químicos e incluso el plato de plástico utilizadas por el calentamiento, la comida en un microondas, no fue la excepción. 
Según el estudio, el último riesgo para el consumidor en este "cóctel contaminante" es probablemente subestimado. 
Por su parte, la alianza ecológico europeo, los Verdes han propuesto, en vista de la urgencia de la situación, la introducción de una moratoria sobre el uso de plaguicidas, para detener el crecimiento de las enfermedades de la civilización. 
En julio, un estudio realizado por la Agencia Europea de Seguridad Alimentaria ha señalado la presencia de residuos de 365 diferentes plaguicidas identificados en las frutas y hortalizas consumida en Europa, incluido el 76 en los cereales. 
