Romano va hacia su primer título 
Rubén Roman Omar cuenta con tres derrotas en el que, durante su carrera altibajos, pero él sabía cómo alcanzar en tres ocasiones el decisivo. 
Con el duelo de Santos laguna y Monterrey en la última, además de dos estilos diferentes marcada por sus técnicos ", que encontrar con un cambio marcado por los resultados. 
Rubén Roman Omar cuenta con tres derrotas en el que, durante su carrera altibajos, pero él sabía cómo alcanzar en tres ocasiones la serie decisivo, aunque hasta ahora no ha alcanzado el objetivo, y esta es la razón por la que esta oportunidad es muy especial para él. 
La Argentina ha acabado siendo consoled con la medalla de participó, y siguen siendo un paso atrás respecto a los ganadores y específicamente con aparatos similares ha desempeñado finales consecutivos. 
Santos llegó a su primera última como formadores en el primer partido de 2002, cuando tomó las riendas de morelia con el que ha comenzado a 4-2 antes de toluca; más tarde, en el acto de clausura de 2003 también llegó al duelo decisivo y ha perdido también por 3-1 en rayados y de hecho antes. 
Ya con Santos laguna, en el Partido bicentennial de 2010, antes de los diablos, rubén sufre de nuevo un revés, puesto que su equipo acabado igualmente lugares 2-2 antes de la salchicha después de los 210 minutos de juego, sino en el de las sanciones se metió en ventaja por por 3-1 con dos oportunidades para sellar el título, pero finalmente no tres jugadores de los 11 medidas y sufrió el cambio por 4-3. 
Rubén perdido dos finales con diablos rojos y uno en Monterrey, su rival, a su vez, por lo que no queremos para soportar el mismo destino, quiere celebrar un título por primera vez, y que afirma que la más importante para él es la institución. 
Quiero ser paladín, no quiero romper cualquier dato, este es un club, por una pasión y, por consiguiente, el título llegará a mí, pero la cosa es más importante, comentó el timonel cuando cuestionada sobre los números que ha de presentarse en contra de la igualdad. 
Muy eficaz que tiene el final de la anterior, de que le asegura, ha aprendido mucho, "la única lección que podemos aprender es que hasta el árbitro señala el fin no podemos celebrar, nos preparamos así como los jugadores, porque el tiempo, con dos sanciones que estaban a punto de salir y creo que es una lección que hay que aprender, no podemos celebrar hasta el juego termina". 
Sabiendo que esta serie podría ser definida en la pena de diversión, algo que no problemas, porque le confía en sus actores: "uno nunca parece para ir a las sanciones, sino para terminar en un tiempo; a veces no tienen ninguna alternativa y que es necesario estar preparados; en la anterior partido estábamos dispuestos, por desgracia destino desempeñado en nuestras manos; a veces por nervios o ansiedad por haber el título en las manos, pero no lo hicimos alcanzar este objetivo, y esto nos queda algo por esta última que esperamos para ganar". 
Roman debe dejar de ser un candidato técnica y saboreando por primera vez la gloria, que los títulos. 
