Con la literatura pueden poner el dedo en 
La segunda ronda de los placeres de la lengua es un ejemplo más de que los participantes promulgó la narration 
Que de sexo en lengua entiendo que pero... el dedo sobre? ¿qué se espera hacer?, preguntó el escritor Luisa invitado Valenzuela invitado a abrir la segunda ronda de los placeres de la lengua, caso de que se celebre la literatura en español y que ese tiempo el subtítulo de su pregunta (de otro modo la Mesa Redonda consagrado al sexo en la lengua, ha explicado). 
El dedo sobre ella... "que nos coloca en una posición difícil", dijo a sweetly directamente el escritor argentino a la opinión pública, sobre todo de los jóvenes, que se reunieron en la justa internacional del libro de Guadalajara (fil) para escuchar esta mesa redonda moderado por marisol Shultz y participado Valenzuela, Sergio Ramírez, Mayra montero y Luis García montero participado. 
Luisa Valenzuela leer un texto que ha dedicado a Gonzalo celorio y que Shultz definiría como una gran historia, con Luisa en primera persona como protagonista que en la búsqueda del conocimiento conocido como "", va de médico de médico, de los cuales no obtener respuestas, aunque no en el mismo narrativa hilo. 
Ella deja el médico: "quizás paciencia no es mi forte, tal vez es mi viva". 
Al final, después de que un enfoque frustrante con el trauma médico que que aclara que viva no es un término científico; es la psychoanalyst que vaya desentrañando el misterio: "la herida abierta real es la cosa; el símbolo es el estigma". 
El protagonista suspiró aliviado y concluyó "sobre las heridas sólo he conseguido saber que la verdadera cuestión es abierto y que no existe", pero seguro que los placeres y los trucos de la lengua tiene que ser mixto. 
Valenzuela, el escritor, desempeñado con ambos. 
La autoridad nicaragüense Sergio Ramírez también ilustra una asombrosa narration que titulado elogio de la invención, donde el dedo sobre las heridas de nombre pero no se descubrió. 
En términos generales, de realismo mágico, diga la historia de un famoso, de brujas que por tocar las nubes, devuelto hombres que habían ido lejos o repara las virtudes perdido por un maid, que se convirtió en narration hablando de los Estados Unidos, un gran novela que no falta desde el principio de su propio chroniclers que les y mencionado Bernal Díaz del castillo que critica los excesos de lo dicho por la conquista de los capitanes. 
Cervantes quien inventó todos nosotros (los escritores) se rió de la falsa testigos que apareció en la historia presentada como real, pero de lo contrario habría nunca dijo a la historia de los Estados Unidos con imaginación que falta shyness. 
No obstante, subrayó "crazy personas y mentirosos son quienes mejor imaginar las cosas" y es en realidad y la falsedad son mixtas, donde se sabe si los narrada cosa pertenece a un lado o de otro, donde la literatura ficticia alcanza su apogeo. 
En realidad, llamado "tradición de Cervantes. 
"para su filosofía de: ¿qué nos dijo". 
En cuanto a su, el escritor Mayra montero vimos y aplaudir la diversidad de interpretaciones que la invitación de fil causas con su mesa redonda el dedo en la herida. 
La cuban-puerto rica ha señalado su propio hacia la gran latente de la violencia social que atraviesa su país - y divide a los Estados Unidos de América Latina -product de las disputas sobre el tráfico y la venta de drogas. 
Creo que una buena literatura, buena la poesía, buena canciones encierra un compromiso tácito que por supuesto no es premeditada, indicó, después de mencionar que la realidad de la literatura de la comunicación y la dimensión del compromiso que se asiente entre autor y lectores, y que es una "reacción química" de este último. 
La noche fue cerrada por el poeta español Luis García montero cuya intervención también hacer hincapié "que el dedo sobre las heridas del escritor cometidos por escrito". 
Consideraba que en un mundo que vive en una prisa, también en las aduanas intelectual y el control de la conciencia que tiene efectos negativos en dogmatismos, olvidando "que detrás de cada afirmación hay un pequeño y no detrás de cada negación hay pequeñas sí". 
"para ser dueños de nuestro pensamiento y la realidad debemos aclarar: y aclarar a menudo significa poner el dedo en la herida y preocupar a aquellas personas que son mucho más cómodos pensando en la caricatura, en blanco y negro, en ideas sin una sombra y también preocuparse de los poderes que prefieren un mundo blanco y negro", dijo, invitando a recuperar el sentido de escribir. 
