Congreso apruebe la transposición que tuvo lugar de Mifid 1 de noviembre 
Junto con sus procedimientos parlamentarios, que hoy terminó con la votación parcial del Congreso sobre las enmiendas incorporadas al proyecto del Senado, el gobierno ha presentado a audiencia pública la reglamentación que se desarrolle la nueva ley, con el objetivo de fuerza ino llegan antes de fines del año. 
Los representantes de diferentes grupos acordado en subrayar los esfuerzos realizados por diputados y senadores para negociar y acordar la mejor legislación para garantizar la protección de los inversores y regular en detalle las organizaciones actividad para que los mercados trabajen eficientemente. 
La Mifid, que modifica la Ley del Mercado de Valores, implica la modernización de los mercados financieros, mientras refuerza la protección de los inversores, la mejora de las competencias de control del Comisión Nacional del Mercado De Valores (CNMV) y fomenta la cooperación entre los diversos supervisores de la Unión Europea. 
Los nuevos reglamentos conceder asesor de servicios financieros a compañías especializadas así como a los individuos legal o natural, y crea un nuevo tipo de empresas asesores financieros (ESIS), las empresas asesores financieros (AFI), que incluyen empresas valores, intermediarios, y las empresas de gestión de cartera. 
Además, amplía el número de sistemas disponibles para la ejecución de operaciones financieras, tan incluidos en el reglamento son los mercados secundarios, el sistema comercial multilateral, y los sistemas de internalización órdenes, van a competir con los directores del mercado de valores actuales. 
La ley exige también servicios de inversión a las empresas a revelar al mercado de los detalles clave de su perfil empresarial, riesgo y formas de gestión de riesgos, y para mantener un registro de todos sus operaciones a facilitar la supervisión de la CNMV. 
En su paso a través de la Comisión de Asuntos Económicos del Congreso, se han introducido varias modificaciones, principalmente deudas securitised debería considerarse como un instrumento financiero "complejo" debido a su alto riesgo para el inversor, que ha demostrado por lo que sucedió con el alto riesgo hipotecas estadounidenses deudas (de hipotecas de alto riesgo). 
Además, aprovechó la transposición de la directiva para definir legalmente las funciones que pueden desarrollar licenciados en Economía y Finanzas en 30 años después de la aprobación decreto en 1977, que delimits las funciones profesionales reservado a los economistas profesionales. 
Por su parte, el Senado promovió la creación de nuevas funciones en el sector financiero, como el asesor financiero, que trabajan para contratar o recompensa, no requiere la aprobación SEC y serán capaces de dar sus servicios y productos correduría a clientes en varias empresas de inversión al mismo tiempo. 
