El capital político: La Guardia húngaro ha agudizado el país del nivel de riesgo 
Las acciones por la Guardia húngara, establecido en agosto con el apoyo del Movimiento para un Righter Hungría, ha planteado el riesgo político nivel de Hungría y a la región entera de una serie de aspectos, según la División Analizar riesgos del capital político. 
La investigación entidad emitió un riesgo aviso "," escrito: las acciones de la Guardia húngara desencadenar un riesgo político rebasamiento "que ya existentes tensiones étnicas entre los gitanos y non-Gypsy residentes de Hungría podría calor a niveles tóxicos tan pronto como el corto plazo, conduciendo a conflictos étnicos que podría convertir violenta". 
La razón principal es que la estrategia política Guardia húngara parece estar destinada a provocar acción de esta naturaleza, añadido el instituto de investigación. 
Este es el resultado de uno de los más graves fracasos de Hungría de los actores políticos: "El principal agentes de la vida pública entregada debate público de cuestiones romaníes a representantes de las fuerzas políticas radicales y extremistas, que han construido una estrategia política de Gypsy-Hungarian diferencias". 
Este capital político cree, ha intensificado el problema, permitiendo diálogo normal, reforzando los extremistas, y acentuando la probabilidad de que los conflictos violentos ocurran. 
Además, el instituto de investigación cree que los medios internacionales y nacionales amplia atención a las acciones Guardia húngaro ha "perjudicado notablemente la imagen internacional Hungría, sobre todo en cuanto a la creencia en la estabilidad del país y en la sofisticación de su democracia". 
señalar que el aumento de la publicidad y el impulso dado a los ðåîðãàíèçàöèþ de grupos radicales y extrema derecha en Hungría partida en el otoño de 2006 han sido parte de la razón por la que una serie de organizaciones exigirse "nacionales" autodefensa alianzas se establecieron empezando en el verano de 2007. 
"El rasgo común de estos grupos es que llamarse organizaciones cívicas mientras declara abiertamente que se están preparando sus miembros para defensiva - incluyendo armada - tareas (citando gestión de catástrofes, defensa nacional, ley) mientras declarar que la policía y las fuerzas armadas, en otras palabras, el gobierno, inadaptada por el papel," capital político añade. 
observó que se han hecho todos estos mueve en una configuración que se basa en la sociedad y anti-politics anti-political-party ánimo a diferentes manto ambiciones políticas bajo un manto de acción cívica. 
En otras palabras, su insistencia en la naturaleza cívica de sus acciones y su elección de la asociación como su forma organizacional no son sólo trucos a esquivar escollos legales al registro con los tribunales, sino también son parte de una estrategia política. 
Según el análisis, la actividad de la Guardia húngara está acentuando el riesgo de dañar nuestras relaciones con nuestros vecinos. 
"En varios meses recientes de los vecinos de Hungría han citado la Guardia húngara como un potencial peligro. Los actores políticos ultranacionalistas entre algunos de esos vecinos han referido al establecimiento de la Guardia húngara como un argumento para justificar sus propias políticas antihúngaro. 
Todos estos factores influencia de la estabilidad política de la región, "añade. 
El instituto de investigación señala que el establecimiento de la Guardia húngara no es un fenómeno único en Europa Central y Oriental, y como aumenta el riesgo político para el conjunto de la región. 
señala que el funcionamiento de la Guardia húngara es similar al de la Guardia Nacional búlgara, establecida en agosto de 2007 por la Unión Nacional búlgara extrema derecha (BNU). 
Los conflictos graves que estalló entre romaníes como no en un distrito Sofía (Krasna Polyana) estaban tras el establecimiento de la guardia búlgara. 
BNU se ha aprovechado de los disturbios para establecer su guardia, alegando que el objetivo de la organización autodefensa "nacionales". 
Se argumentó que durante los últimos 17 años Bulgaria había sido objeto de terror gitano "," en el que el gobierno fue indefensa y indiferente, capital político observado. 
La iniciativa desencadenó acalorado debate entre el público búlgaro, añadido. 
Una señal de que ha aumentado el riesgo de un conflicto étnico, escribió los analistas, es que algunas organizaciones romá en Bulgaria han anunciado planes para establecer una guardia de su propio como una fuerza resistencia. 
Desde la Guardia húngara hasta ahora ha actuado muy similar a la Guardia Nacional búlgara, es muy posible que la comunidad romá de Hungría podrían responder a la amenaza de organizar su propia defensa, escribió capital político en advertencia del riesgo. 
La investigación gestor capital político Juhász Attila respondió a una pregunta del servicio MTI húngaro alambre diciendo que el análisis de riesgo fue una de las actividades jefe instituto de investigación. 
Cada año, ha dicho, publicar análisis de riesgo, y si descubrir cualquier factor que pudiera alterar riesgos, notificar la opinión pública por publicar una advertencia riesgo, como lo han hecho ahora. 
