EnvironMin y el seis por ciento Hungría 
El Ministro del Medio Ambiente, Fodor Gábor ha dicho que profesionales reuniones a nivel posterior a 2012 cuestiones internacionales sobre el clima final jueves. La propia conferencia abre oficialmente miércoles, cuando los ministros de tomar el asunto. 
Profesionales y políticos de 192 países son proyectadas para discutir la Hoja Bali que se centra en los esfuerzos para reducir las emisiones de gases de efecto invernadero después de 2012, cuando el Protocolo de Kyoto expira. 
En la actualidad las naciones en desarrollo y desarrollados en medio de una disputa acalorada. 
Los Estados Unidos no sabe que no está dispuesto a negociar cifras precisas, aunque no se opone a aceptar un recorte 25-40 por ciento de los gases de invernadero 2020 frente a 1990. 
La otra gran pregunta en la conferencia es si los países desarrollados no sólo están dispuestos a reducir sus emisiones, sino también para ofrecer asistencia técnica y financiera a los países que necesitan. 
Un acuerdo estaba en el apoyo a las naciones en desarrollo. 
Un consejo 16 - miembro gestionar la financiación, que está fijado por el Protocolo de Kyoto, y más probable es que trabajan en el Fondo para el Medio Ambiente Mundial de las Naciones Unidas (FMAM), escribe la publicación local Lucro és Piac. 
En el seis por ciento Hungría 
Representando Hungría. Fodor Gábor ministra de Medio Ambiente está dispuesto a apoyar UE esfuerzos para conservar su papel emblemático del esfuerzo de protección del clima global y promover un nuevo acuerdo internacional, alcanzado en 2009. 
Fodor observar que la UE tiene su mirada en una caída del 20 por ciento de las emisiones de gases de efecto invernadero 2020 con respecto a 1990, si el acuerdo "posterior a 2012 llegó" o no, y está dispuesta a reducir al 30 por ciento si las otras grandes regiones desarrolladas del mundo y las naciones en desarrollo también están dispuestos a aceptar las obligaciones del alcance de sus capacidades y responsabilidades. 
Fodor dicho que atrás en 1997, los países que se adhieren al Protocolo de Kyoto había focalizado una reducción de las emisiones de 5,2% en general. En este grupo, los 15 miembros de la UE acordaron un declive 8 por ciento. 
Hungría acordaron reducir sus emisiones de gases de efecto invernadero en un 6 por ciento en comparación con 1985-1987, un objetivo piensa cumplir, dijo el ministerio de la prensa medioambiental. 
La apuesta en Bali son altos, para un acuerdo internacional a largo plazo en la política climática debe ser ocultado dentro de dos años o que no serán capaces de entrar en vigor en 2012... Si ocurrir, las promesas hechas durante la validez del Protocolo de Kyoto no será seguido inmediatamente por otro régimen emissions-reduction, la necesidad de la ONU Nobel-Prize ganar órgano científico, el Panel Intergubernamental sobre Cambio Climático (IPCC - ha señalado en su último informe. 
El resultado podría ser un retraso de reducción de emisiones, que Tierra cierta hacia un aumento temperatura media sobrepasar 2 grados Celsio. Si ocurrir, científicos y las consecuencias funestas irreversible. 
