El Celtic mirante en Milán un valor de punto octavo 
Milán y Celtic están siguiendo el martes tocando en San Siro en la búsqueda del punto que necesitaron lograr sus objetivos respectivos en el cierre de la liga de "campeones", mientras se les usa a los italianos para ser primero y el Scots para su clasificación de sentencia. 
Añade y los italianos certificados ya diez puntos con una ligadura en Portugal en el pasado de día quinto, mientras Celtic tiene nueve puntos, pero necesita todavía asegurarse que el Shakhtar, con seis y que Benfica, que tiene cuatro, no lo adelante. 
Se jugarán estas dos correspondencias de grupo D antes del final del sexto día en una semana, ya que Milán tiene que jugar en el de Mundial Clubes en Japón, donde hacen su presentación en el 13 en el semi-finals en la búsqueda de un lugar el último en 16. 
Tan, se le cerrará a este grupo antes de que el descanso y Giuseppe Meazza parezca para esperar una ligadura como el resultado, pero los dos equipos intentarán ir para un triunfo y los italianos no querrán sabe especular en la casa y en el Celtic que la ganancia sería primera y aseguraría un más mejor cruce dentro del cuarto finals. 
Al equipo Gordon Strachan podría servir aun una derrota para Shakhtar clasificado si no gana, pero no puede estar confiado porque la igualdad a nueve puntos significa que el Ukranians pasa, que perdió en Glasgow (2-1) la semana pasada, pero ganado (2-0) en otro duelo vivo. 
Así, Milanists amenaza hacerlo una noche amarga para el Scots, que cuenta con llegar por la segunda vez dentro de los cuartos en una fila en la liga de campeones restructurada, después de que se hayan derrotado precisamente en esta última ronda por un objetivo de Kaka después del 0-0 en la ronda en el tiempo extendido (1-0). 
La espera la victoria del "rossoneri" será el Shakhtar a que únicamente el triunfo hará, en caso que Celtic perdió, ambos llegan dentro de cuartos para continuar en el UEFA. 
Y en cuanto a Benfica, a pesar de ser el último y sin cualquier esperanza de permaneciendo en la competencia más importante europea, se podría extender el lugar tercero con una victoria, que juega UEFA. 
