El grupo catalán ha facilitado miles de pasaportes a Al Qaeda 
Además de los siete detenidos en Barcelona, en Tailandia hubo tres 
Los siete pakistaníes y el nigeriano detenido por agentes de inteligencia policial en el Barcelona General formaban un grupo yihadista que dirige de Tailandia, facilitó un pasaporte a diferentes grupos de Al Qaeda, entre ellos "Los Tigres para la Liberación de Territorio Tamilm" (LTTE) y "Laskar e Taiba" (Dejad), autor de este último uno de los atentados de Bombay, que causó la muerte de 106 personas en 2008. 
El Ministerio de Interior ha prestado atención a estas investigaciones, hasta el punto de asegurar que con la operación "Kampai", ha sido "debilitar" del aparato de falsificación de Al Qaeda en el plano internacional y, "por tanto, su capacidad operativa". 
Los investigadores calculan que la celda, durante los dos años que ha estado activa en Cataluña, ha sido capaz de enviar miles de pasaportes a Tailandia, donde fueron falsificados y pronto distribuida a los grupos que integran la galaxia criminal Al Qaeda para que su "combatientes" pueden cruzar las fronteras europeas y los de otros países occidentales con total impunidad. 
La célula desmantelada no es el único que la red yihadista en Europa, por este motivo en las investigaciones han participado, además de los servicios de Tailandia, otras unidades policiales europeas, razón por la que no descartar que en el territorio de la UE se producen sucesos similares a las que se ha desarrollado la noche del martes en Barcelona. 
En coordinación con esta operación (La Humayun Junaid paquistaní, Rehman Atiqur, Asghar Jabran, Ahmad Malik Iftikhar Mohammad Saddique Khan Begum, Tanveer Arshad y el nigeriano Babatunde Agunbiade fueron detenidos), en Tailandia otra había desarrollado con la captura de los pakistaníes Muhammad Athar Butt y Zeeshan Ehsan Butt y el Kijbumrung Sirikanlaya tailandés. 
El grupo se encuentra en España y otros países europeos se dirige desde Bangcock 
La red catalana parte de fue golpeado en 2009 -principalmente robado pasaportes a los turistas que cumplían los requisitos marcados por la llamada "Worldwide islámica frente". 
Es decir, los documentos que en nombre de los hombres de entre 25 y 45 años, con validez de varios años y sin visados impresa. 
En medios de la investigación se ha subrayado que, por el momento, no se han encontrado datos relacionados con las personas detenidas en Cataluña en relación con el atentado de Bombay, aunque el autor de este ataque, "Laskar e Taiba", ha sido uno de los grupos que reciben de los pasaportes robado en España y pronto falsificado en Tailandia. 
Sin embargo, cabe mencionar que días antes de este ataque comprometido, desde Cataluña se enviaron a través de una agencia de transferences sobre algunos miles de dólares que "se han invertido" en la compra de tarjetas de telefonía móvil que pronto fueron utilizadas por los miembros del "comando" que acabó con la vida de 106 personas. 
Los policías han capturado un montón de documentación. 
