El programa nuclear paquistaní genera una gran agitación en los EE.UU. 
Islamabad produce armas atómicas en "un ritmo más rápido que cualquier otro país". 
Las filtraciones de Wikileaks confirman los lazos entre el pueblo talibanes y Pakistán. 
El contenido de la correspondencia entre la embajada estadounidense en Pakistán y el Departamento de Estado de los EE.UU. filtrados por el portal de Wikileaks confirma la enorme agitación que lleva el programa nuclear de Pakistán en Washington. 
Además los detalles sustanciales y esclarecedor que ofrecen sobre el contenido de las conversaciones y los pensamientos del credited norteamericanas representantes diplomáticos en Islamabad, los documentos revelan que la cooperación entre ambos países en materia de seguridad nuclear, en lugar de aumentar, "disminuye," y que el país asiático inestable produce armas nucleares con "un ritmo más rápido que cualquier otro país". 
La peculiaridad del programa nuclear paquistaní que las armas no están reunidos, pero permanecen almacenadas por componentes para hacer difícil su destrucción en caso de attack-- constituye una de las principales causas de preocupación en Washington. 
Así se enumerados por el embajador de Pakistán, Anne W. Patterson, en un informe anterior a la visita de los antiguos el asesor de Seguridad Nacional, James Jones: "La proximidad de algunas centrales nucleares en el territorio bajo ataque talibán, rumoreado la dispersión de los materiales nucleares y la vulnerabilidad de transporte de materiales nucleares". 
El elevado número de personas implícita en los arsenales nucleares y de los programas de misiles que se tenga en cuenta, no sólo por los Estados Unidos, sino también por Rusia, como la razón para mantener su guardia. 
"Pakistán ha tenido que contratar personal con estrictas creencias religiosas para proteger a las centrales nucleares, dada la mala educación y niveles culturales, las organizaciones extremistas tienen más oportunidades para reclutar gente para trabajar en los programas nuclear y de misiles", dijo el experto Yuri Carole, desde el Ministerio ruso de Exteriores, en una reunión con su estadounidenses homologous. 
Los datos más recientes sobre los documentos filtrados por el portal de Julian Assange está disminuyendo la cooperación entre los Estados Unidos y Pakistán en temas de la proliferación nuclear y el alto índice de Pakistán de la producción de armas nucleares. 
Una oficina de la embajada en mayo, que describe como "frustrante" la comunicación con Pakistán, afirma que: "La transparencia es a menudo inexistente; las ofertas de ayuda siguen sin respuesta o se les niega". 
En otro mensaje, Peter Lavoy, funcionario de la Inteligencia Nacional para el sur de Asia, afirma que "a pesar de la catástrofe económica, Pakistán produce armas nucleares a un ritmo más rápido que cualquier otro país del mundo". 
El embajador Patterson también pide Washington, durante una visita del jefe del Ejército, el general Ashfaq Kayani, dar órdenes claras a la persona encargada de que "el Ejército de Pakistán debe acabar con el apoyo tácito a los grupos terroristas". 
