Grammy candidaturas: La cantante de jazz esperanza Spalding mejor es una sorpresa en el mejor de los casos, una nueva categoría artista 
Llevar a cabo a petición de un presidente, y la gente está obligada a tomar nota. 
Esperanza Spalding, de 26 años de edad-jazz bassist y cantante parte-elegido por Obama para llevar a cabo su premio Nobel de la Paz ceremonia en 2009, marcó uno de los Grammys "sorpresas este año con una candidatura de alto perfil en el mejor nuevo artista categoría. 
Considerando que Spalding ha sido un personaje famoso sobre el escenario de jazz desde su álbum de 2008, "esperanza" la nominación es un poco de un jefe scratcher, pero es compatible con las normas de Grammys de un artista no liberar a más de tres álbumes antes de la grabación que establece la identidad pública de este artista ". 
Su ambicioso 2010 álbum, "Cámara Music Society," sin duda marcó un paso adelante, y dada su airily invitar al estilo verbal y una mano de filigrana con el pop, funk e influencias de América Latina, es posible sacar al menos una confirmación Spalding de Norah Jones "gran éxito en 2003, el equivalente más cercanos a los votantes Grammy mirando hacia el jazz neighborhood en esta categoría en los últimos años. 
En otros lugares Grammy votantes honored acertadamente la Vijay Iyer Trío Historicity "del" en la categoría de álbum instrumental, un emocionante vigorizante-paseo de una grabación que fue un crítico favorite el año pasado. 
Entre esos Iyer estará compitiendo contra incluyen veterano saxophonist James de Moody "Moody 4B" y keyboardist John Beasley "Positootly del". 
Trombone Shorty, raucous Nueva Orleans favorite e invitado frecuente acerca del asunto HBO "Treme", fue honored en la categoría de jazz contemporáneo, que de lo contrario se inclina excesivamente hacia la fusión con cierto hacia álbumes de Stanley Clarke, John McLaughlin y Jeff Lorber. 
Los salvajes, steampunk-informado Darcy James argumentan Secreto de la Sociedad ganaron un reconocimiento bien merecido en la categoría de gran colectivo, compitiendo contra el Billy Childs ricos cámara del colectivo-jazz y nunca-aventurero Dave Holanda, cuya octet vivos del álbum "Pathways" fue un buen ejemplo de la parte democrática bassist como bandleader. 
