Romano va hacia su primer título 
Rubén Omar Romano cuenta con tres derrotas en las finales, que durante su carrera venturas y desventuras, pero sabía cómo alcanzar en tres ocasiones la serie decisiva. 
Con el duelo de Santos Laguna y Monterrey, en la final, además de dos estilos diferentes marcada por el rostro de sus técnicos, que parece mutuamente con un contraste marcado por los resultados. 
Rubén Omar Romano cuenta con tres derrotas en las finales, que durante su carrera venturas y desventuras, pero sabía cómo alcanzar en tres ocasiones la serie decisiva, aunque hasta ahora ha hadn no llegó a la meta, y esta es la razón por la que esta oportunidad es muy especial para él. 
El argentino ha acabado se consuela con la medalla del corredor-, y se quedaron un paso por detrás de los ganadores y peculiares con equipos similares ha jugado finales consecutivas. 
Santos llegó a su primera final como entrenador en la apertura Match de 2002, cuando tomó las riendas de Morelia con él cayó por 4-2 ante Toluca; más tarde, en el Encuentro Closing de 2003 también ha llegado al duelo decisivo y él también perdió por 3-1 y, de hecho, antes de Rayados. 
Ya con Santos Laguna, en la Match Bicentennial de 2010, una vez más, ante Los Diablos, Rubén sufre un nuevo revés, ya que su equipo acabados igualmente coloca 2-2 ante la salchicha decisiones después de 210 minutos de juego, pero en el turno de sanciones colocado con ventaja de 3-1 con dos oportunidades para sellar el título, pero finalmente tres jugadores fallaron desde los 11 pasos y sufrió el cambio de 4-3. 
Rubén ya perdió dos finales con Diablos Rojos y uno con Monterrey, su rival en turno, pues él doesn 't quieren sufrir la misma suerte, quiere celebrar un título por primera vez, y él afirma que lo más importante para él es la institución. 
Quiero ser campeón, no quiero romper cualquier dato, se trata de un club de pasión y, en consecuencia, llegará el título para mí, pero lo anterior es más importante, comentó el timonel al ser preguntados por los números tiene en contra por jugar finales. 
Muy eficaz tiene la anterior final, de la que, asegura, ha aprendido mucho, "la única lección que podemos extraer es que hasta que el árbitro señala el fin no podemos celebrar, nos preparamos así como los jugadores, porque el tiempo anterior, con dos penas que estaban a punto de abandonar y creo que es una lección, no podemos celebrar hasta que termina el partido". 
Sabiendo que esta serie podría definirse en golpes de castigo, algo que da problemas, porque él confía en que sus jugadores: « uno nunca espera para ir a las sanciones, sino para terminar en tiempo regular; a veces, usted no tiene ninguna alternativa y es necesario estar preparados; en el partido anterior estábamos preparados, lamentablemente destino jugó en nuestras manos; a veces con nervios o ansiedad por tener el título en las manos, pero se agarraba alcanzar este objetivo, y esto nos ha dejado algo de esta última que esperamos ganar ". 
Roman debe dejar de ser un corredor técnico-y el sabor de la gloria de la primera vez que los títulos dan. 
