Las peticiones de IP resultados del Congreso 
Eduardo Dávalos, presidente de la CEC, propuso que los suplentes asumen la gran responsabilidad de ser un ejemplo para un Sinaloa mejor por los diversos desafíos a los que se enfrenta. 
Una Legislation de obras decente y libre de acuerdos entre los partidos y el Ejecutivo estatal está reclamado por el sector empresarial de Mazatlán, porque existe un Sinaloa convulsed que se enfrenta a grandes problemas. 
Ayer se votó la 60 legislatura, integrada por siete fuerzas políticas, 19 diputados del PRI, 13 del PAN, tres del Partido Nueva Alianza, dos del PRD, del PT, uno de la Convergencia y uno más del PVEM, lo que significa un total de 40 representantes populares. 
Entre la lista de las expectativas de los nuevos miembros del Congreso del S-Estado se menciona que vienen a realizar una gestión limpia de compromiso a la sociedad y los distintos sectores que requieren un trabajo legislativo responsable. 
Eduardo Dávalos Zamora, presidente del Consejo Coordinador Enterprise, propuso que el recién liberado 40 diputados del Congreso del Estado ha asumido la gran responsabilidad de ser un ejemplo para un Sinaloa mejor por los diversos desafíos a los que se enfrenta. 
Esperamos que los suplentes realmente va a ejercer su derecho, libre de acuerdos entre las partes, porque es la costumbre de hacer acuerdos para advertir a sus propios intereses y convertirse en un personaje en un carnaval de los gobernadores y los líderes de las fracciones parlamentarias. 
Por esa razón habló de certificar el compromiso con el fin de establecer los necesarios puentes que podría ayudar al Gobernador para seguir adelante. 
Esperamos que vienen a hacer un trabajo digno y, sobre todo, comprometida con la sociedad y los sectores porque los habitantes de Sinaloa fueron aquellos que les dio el voto de confianza durante las últimas elecciones. 
José Ramón Manguart Sánchez, presidente de la Asociación de Hotels Tres Islas, consideró que uno de los mayores retos para los 40 representantes populares es la de impulsar y añadiendo fuerzas en busca del crecimiento económico del Estado, porque hoy en día, la situación económica es muy complicado. 
Lo más importante es impulsar el crecimiento económico, que genera incentivos para la inversión y la infraestructura y que, de alguna manera, constituirá una nueva generación de puestos de trabajo. 
En cuanto a la actividad turística, ha exigido que los nuevos legisladores dan el peso revisado dentro del presupuesto estatal para fortalecer la Secretaria de Turismo. 
Como he entendido que este es el segundo departamento del Estado con menos presupuestos y es incongruente una actividad económica importante y la generación de divisas y la inversión y que compite directamente con la industria de la agroindustria. 
Aparte de que el etiquetado recursos los proyectos turísticos pirotécnico que contribuyen a la seguridad del Estado y actualizar la Ley del Alcohol, que no ha sido capaz de resolver en las legislaturas anteriores. 
