Los fiscales no acusación senador Pabellón 
La Consejería fiscales han despejado el senador John Pabellón de acusaciones penales derivadas de su historia con un antiguo ayudante de campaña y sus esfuerzos para garantizar el trabajo de los grupos de presión para el marido de la mujer, los abogados del senador anunció el miércoles. 
La decisión pone fin a la amenaza legal más graves a los que se enfrenta el Pabellón, el republicano Nevada, quien fue considerado un posible candidato presidencial republicana en 2012 hasta el escándalo sobre su caso hizo titulares nacionales del año pasado y han dañado su carrera. 
Señor oficina del Pabellón dijo que estaba "muy contento" por la decisión, a la que siguió una investigación yearlong. 
El senador aún podría enfrentarse a acciones disciplinarias por el comité de ética del Senado. 
Los abogados del Sr. Pabellón dijo que el Departamento de Justicia "había informado de que el senador Pabellón ya no es un objetivo de su investigación y que no tiene planes para presentar cargos contra él en este asunto". 
El Departamento de Justicia se negó a comentar el caso. 
El anuncio llegó como algo de sorpresa a muchos abogados ética fuera del Departamento de Justicia, quien dijo que parecía ser una prueba importante para indicar que el señor Pabellón puede haber conspirado para violar la prohibición criminal de cabildeo federal. 
Entrevistas, e-mail y otros documentos publicados por primera vez en octubre de 2009 en The New York Times indicó que había ayudado al Pabellón Douglas en Hampton Court, que fue uno de sus asistentes, los grupos de interés lucrativo trabajar para ganar el silencio del señor en Hampton Court y su esposa Cynthia, sobre el asunto del senador con ella. 
La señora en Hampton Court una vez sirvió como tesorero del Pabellón de la campaña. 
Señor Pabellón en contacto con varios representantes políticos para encontrar trabajo para el señor en Hampton Court y defendía entonces en su nombre después de que habían alquilado en Hampton Court señor para presionar a favor de ellos, según los documentos y entrevistas. 
Porque el señor Hampton Court recientemente había sido un ayudante para el Pabellón fue prohibido por ley la presión de su ex empleador o el Senado en conjunto durante un año. 
Ha dicho expertos ética inusual el acuerdo entre el Pabellón y señor en Hampton Court, que eran amigos cercanos antes del asunto, parecía reñida con el-llamada puerta giratoria prohibición de presión. 
A partir de las pruebas que se han hecho públicos, "parecía una prima facie de una conspiración para violar y violación sustancial del estatuto de la puerta giratoria," dijo Stanley Brand, un abogado de Washington que se está especializando en la defensa de los clientes investigados por el gobierno. 
Mientras que los funcionarios del Departamento de Justicia se negó a explicar el razonamiento detrás de la decisión en el Pabellón caso, señor Brand y otros abogados ética dijo el departamento aparecieron cautelosos a la hora de asumir las persecuciones políticas tras una serie de reveses de alto perfil para su integridad pública sección, incluido el año pasado la decisión de retirar la acusación contra el ex senador Ted Stevens en medio de acusaciones de mala conducta prosecutorial. 
Los fiscales federados "son claramente gun tímido," dijo Melanie Sloan, el director ejecutivo de Ciudadanos de Responsabilidad y Ética en Washington, un grupo de defensa que dio lugar a varias denuncias contra el Pabellón en el caso. 
"Este básicamente dice ahora altos funcionarios del gobierno de clasificación-puede asumir las leyes no se aplican a ellos", ha añadido. 
Pablo Coggins, abogado de plomo del Pabellón, dijo en una entrevista que recibió una llamada telefónica de un fiscal del Departamento de Justicia el lunes y un seguimiento-hasta el día siguiente, diciéndole que el departamento no estaba buscando los cargos contra su cliente. 
Señor equipo de defensa del Pabellón había estado cooperando con los fiscales en intentar convencerles de que el senador como su oficina ha reiterado en una declaración el miércoles, "ha actuado de conformidad con la ley". 
Señor Coggins no quiso detallar los argumentos jurídicos que hizo a los fiscales. 
"Estoy cómodo no entrar en los detalles de mis conversaciones con el Departamento de Justicia, salvo para decir que creemos que tomó la decisión correcta", dijo. 
El mes pasado, la Comisión Federal Electoral decidió abandonar una investigación sobre una queja por separado del grupo de ética alegando que 96,000 dólares de pago por parte de los padres del señor Pabellón en los Hamptons violó la ley electoral federal. 
La comisión electoral dijo que no había pruebas suficientes para demostrar que el dinero era nada salvo un regalo. 
Una empresa de la que el señor Pabellón ayudó al señor Hampton Court encontrar trabajo cabildeo fue NV Energy, una importante empresa de Nevada que durante mucho tiempo había apoyado el senador. 
Un e-mail enviado en diciembre de 2008 demostró que después de que la compañía ha llevado al Señor en Hampton Court de como un grupo de presión, señor director del Pabellón de personal, Juan López, comunicarse con el señor en Hampton Court y le dijo que estaba "golpes" el Departamento de Interior sobre un tema de controversia. 
Señor Pabellón también asistió a un almuerzo con el señor en Hampton Court y otro cliente Nevada, Allegiant Air, y pidió al secretario de transporte para crear una reunión sobre el nombre de la compañía después de que había alquilado en Hampton Court señor para hacer presión laboral. 
Cuando la noticia del suceso han surgido por primera vez el año pasado, señor Pabellón disculpó a sus electores y dimitió de su cargo como la cuarta-rango líder republicano en el Senado. 
Tras mantener un perfil bajo durante muchos meses, señor Pabellón dijo a los reporteros hace dos semanas que tiene previsto presentarse a un tercer mandato en el Senado. 
En el anuncio de que el señor Pabellón ha dejado de ser el objetivo de una investigación criminal, su portavoz, Jennifer Cooper, dijo el senador esperaba el comité de ética seguir rápidamente la delantera del Departamento de Justicia y poner fin a su investigación. 
"El senador Pabellón espera continuar su trabajo en nombre del pueblo de Nevada," dijo. 
